### PR TITLE
bsp: make hugetlb config enabled by default for SBL platform

### PR DESCRIPTION
**Pull request by JasonChenCJ**
switch to hugetlb for SBL platform

Signed-off-by: Jason Chen CJ <jason.cj.chen@intel.com>

### CODE REVIEW

**Comment by JasonChenCJ** [comment]
@dongyaozu yes, it change the SOS cmdline option, UEFI cmdline is out of github's control.

**Comment by dongyaozu** [comment]
@JasonChenCJ then how can end user switch to huge tlb mode? It is not a full solution yet?

**Comment by JasonChenCJ** [comment]
@dongyaozu , end user only need make sure there is enough huge page reserved by /sys/kernel/mm/hugepages-xxxx/nr_hugepages, then call acrn-dm with "-T" option.

**Comment by gvancuts** [comment]
@JasonChenCJ , is there a recommended value for EFI platforms?

We provide a sample `acrn.conf` file that includes a series of kernel parameters - see here: https://github.com/projectacrn/acrn-hypervisor/blob/master/bsp/uefi/clearlinux/acrn.conf#L3

**Comment by JasonChenCJ** [comment]
@gvancuts , for EFI platform, it depends on the platform's configuration, user should input their cmdline option for 1G page by himself - says "hugepagesz=1G hugepages=X", and also he can just ignore the cmdline option, just make sure "echo enough_pages# > /sys/kernel/mm/hugepages/hugepages-2048kB/nr_hugepages" before start UOS. 
I will update Documentation/ACRN_UEFI.txt for this update later.

**Comment by dongyaozu** [comment]
@JasonChenCJ this is not a good solution. It should be atomatically by DM.

**Comment by JasonChenCJ** [comment]
@dongyaozu @gvancuts  added document update, please review.

**Comment by JasonChenCJ** [comment]
@dongyaozu, for 2M hugepage reservation, actually I added into our launch_UOS scripts.

**Comment by JasonChenCJ** [comment]
@dongyaozu  what I want is try to let user has more flexibility to control the reservation, but we do can add more automatic in acrn-dm, let's do it in next patch.

**Comment by NanlinXie** [comment]
Can one of the admins verify this patch?

**Pull request closed without merging**
