### PR TITLE
doc: add waag secure boot enabling

### PR DESCRIPTION
**Pull request by liuyuan-GitHub**
Signed-off-by: Yuan Liu <yuan1.liu@intel.com>

### CODE REVIEW

**Comment by NanlinXie** [comment]
@lidongwangx , Could you help to review and verify this document? Thanks!

**Comment by acrnsi** [comment]
OK to verify

**Comment by acrnsi** [comment]
OK to verify

**Comment by huyuan3x** [comment]
Waag secure boot enable successfully according to this document.

**Pull request merged**
