### PR TITLE
hypervisor: Fix spelling and typo mistakes.

### PR DESCRIPTION
**Pull request by qa-majeed**
Fix spelling and typo mistakes.
Tracked-On: #8488

### CODE REVIEW

**Review by junjiemao1 — APPROVED** [review]
LGTM. Thanks!

**Comment by wenlingz** [comment]
start to run premerge test

**Review by NanlinXie — APPROVED** [review]

**Comment by wenlingz** [comment]
start to run premerge test

**Comment by wenlingz** [comment]
start to run premerge test

**Comment by wenlingz** [comment]
@lifeix please help approve this PR, thanks

**Review by lifeix — APPROVED** [review]

**Comment by wenlingz** [comment]
start to run premerge test

**Comment by wenlingz** [comment]
start to run premerge test

**Pull request merged**
