### PR TITLE
add vpid support

### PR DESCRIPTION
**Pull request by lifeix**
v7:
rename sync_vpid_signal to flush_vpid_signal
rename sync_vpid_global to flush_vpid_global
flush global vpid on PCPU when start VM. 

v6:
add flush all-context vpid in shutdown_vm
always disable invlpg trap out 

v5:
move INVVPID type check support to hardware_detect_support when boot
remove spinlock for vpid allocation
remove flush vpid in reset_vcpu

v4:
please ignore this serail

v3:
add disable vpid feature if allocate vpid failed.

v2:
replace bitmap with increscent count to allocate vpid

@dongyaozu

### CODE REVIEW

**Comment by lijinxia** [comment]
UOS boot failed!

**Comment by lijinxia** [comment]
After rebase, verify PASS

**Comment by NanlinXie** [comment]
Can one of the admins verify this patch?

**Comment by lifeix** [comment]
@dongyaozu 
modify VMX_MAX_NR_VPID to (1 << 5) and add error hit for vpid overflow for test vpid

**Comment by lijinxia** [comment]
Verified+1

**Pull request merged**
