### PR TITLE
hv: switch vLAPIC mode vlapic_reset

### PR DESCRIPTION
**Pull request by sainath14**
Guest OS can use vLAPIC in x2APIC mode. Upon vlapic_reset, vLAPIC should
be set to xAPIC mode.

Tracked-on: #1626
Signed-off-by: Sainath Grandhi <sainath.grandhi@intel.com>

### CODE REVIEW

**Comment by HuiHuangShi** [comment]
1627<br>2 new potential violations to the coding guideline detected. Please help check. Thanks!  <br><br>1.filename:/hypervisor/arch/x86/guest/vlapic.c&nbsp;&nbsp;function:vlapic_reset&nbsp;&nbsp;offset:1592:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Value is not of appropriate type. :  (int and unsigned char): vlapic -> vcpu -> vcpu_id   == 0U<br><br>2.filename:/hypervisor/arch/x86/guest/vlapic.c&nbsp;&nbsp;function:vlapic_reset&nbsp;&nbsp;offset:1592:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Signed/unsigned conversion without cast. :  (int and unsigned int): vlapic -> vcpu -> vcpu_id<br><br>

**Comment by sainath14** [comment]
@HuiHuangShi 
vcpu->vcpu_id == BOOT_CPU_ID is used in multiple places in the code. Not sure why it is a problem in this line number.
Also vcpu_id is uint_16 and BOOT_CPU_ID is 0U. Both are unsigned ints. Why do we get "signed/unsigned conversion without cast."

**Comment by HuiHuangShi** [comment]
> @HuiHuangShi
> vcpu->vcpu_id == BOOT_CPU_ID is used in multiple places in the code. Not sure why it is a problem in this line number.
> Also vcpu_id is uint_16 and BOOT_CPU_ID is 0U. Both are unsigned ints. Why do we get "signed/unsigned conversion without cast."

It's tool's false positive.

**Comment by lijinxia** [comment]
@sainath14 Please rebase your folk branch with upstream and fix the conflicts.

**Comment by sainath14** [comment]
@dongyaozu changed vlapic_create_timer to vlapic_init_timer

**Comment by HuiHuangShi** [comment]
1627<br>4 new potential violations to the coding guideline detected. Please help check. Thanks!  <br><br>1.filename:/hypervisor/arch/x86/guest/vlapic.c&nbsp;&nbsp;function:vlapic_reset&nbsp;&nbsp;offset:1591:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Value is not of appropriate type. :  (int and unsigned char): vlapic -> vcpu -> vcpu_id   == 0U<br><br>2.filename:/hypervisor/arch/x86/guest/vlapic.c&nbsp;&nbsp;function:vlapic_reset&nbsp;&nbsp;offset:1591:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Signed/unsigned conversion without cast. :  (int and unsigned int): vlapic -> vcpu -> vcpu_id<br><br>3.filename:/hypervisor/arch/x86/guest/vlapic.c&nbsp;&nbsp;function:vlapic_init&nbsp;&nbsp;offset:1630:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Signed/unsigned conversion without cast. :  (int and unsigned short): ! ( vlapic -> vcpu -> vcpu_id < phys_cpu_num<br><br>4.filename:/hypervisor/arch/x86/guest/vlapic.c&nbsp;&nbsp;function:vlapic_init&nbsp;&nbsp;offset:1630:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Signed/unsigned conversion without cast. :  (int and unsigned short): ! ( vlapic -> vcpu -> vcpu_id<br><br>

**Comment by sainath14** [comment]
Looks like false positive again. Both vcpu_id and phys_cpu_num are uint_16

**Comment by HuiHuangShi** [comment]
> Looks like false positive again. Both vcpu_id and phys_cpu_num are uint_16

It is false positive,pls skip it.

**Pull request merged**
