### PR TITLE
Remove ASSERT in lib functions

### PR DESCRIPTION
**Pull request by lyan3**
Replace ASSERT in lib functions with error message print and return a
value indicating error to allow the caller of lib functions to handle
the error.

Change-Id: If166484238dc0734041adfdbb19a5b374c044e33
Signed-off-by: Yan, Like <like.yan@intel.com>

### CODE REVIEW

**Comment by lyan3** [comment]
Comments from yakuizhao: 
It seems that the ASSERT can help to dump some infos if HV_DEBUG is enabled. This is helpful.
But it will cause that the system enters the state of "pause" if the HV_DEBUG is not enabled.
In fact the condition check in ASSERT is not expected.
Is it ok to rework the implementation of assert when the HV_DEBUG is not enabled? Maybe like what you mentioned, it can be checked by caller instead of pause.

**Comment by lyan3** [comment]
@yakuizhao  for lib functions, I think ASSERT should not be allowed. And for ASSERT in other parts of code, how about we use another MACRO like "CHECK" to check the condition, dump the context and return a value if condition is false? ASSERT(with pause) will be needed somewhere when HV_DEBUG is not enabled, what do you think?

**Comment by yakuizhao** [comment]
@lyan3 , Your new suggestion make sense. it looks good that the "ASSERT" is forbidden in lib function.

**Comment by lijinxia** [comment]
verified +1

**Pull request merged**
