### PR TITLE
Makefile: fix typo in config.mk

### PR DESCRIPTION
**Pull request by gvancuts**
Fix typo in hypervisor/scripts/makefile/config.mk file.

Tracked-On: #5647
Signed-off-by: Geoffroy Van Cutsem <geoffroy.vancutsem@intel.com>

### CODE REVIEW

**Comment by acrnsi** [comment]
Can one of the admins verify this patch?

**Review by NanlinXie — APPROVED** [review]

**Comment by dbkinder** [comment]
@gvancuts You'll need to add an Issue (with a ``[External_System_ID] ACRN-XXXX`` comment) and add a ``Tracked-On:`` comment in your commit message for this PR.

**Comment by NanlinXie** [comment]
@gvancuts , please help to add below tracked on information in your commit message.
Tracked-On: #5647
@dbkinder , we could use this common issue for typos in code comments.

**Comment by gvancuts** [comment]
> @gvancuts , please help to add below tracked on information in your commit message. Tracked-On: #5647

Done

**Comment by wenlingz** [comment]
start to run premerge test

**Pull request merged**
