### PR TITLE
hv:tiny cleanup

### PR DESCRIPTION
**Pull request by mingqiangchi**
-- remove some unnecessary includes
-- fix a typo
-- remove unnecessary void before launch_vms

Tracked-On: #1842
Signed-off-by: Mingqiang Chi <mingqiang.chi@intel.com>

### CODE REVIEW

**Comment by acrnsi** [comment]
OK to verify

**Comment by HuiHuangShi** [comment]
out of license

**Comment by HuiHuangShi** [comment]
out of license

**Comment by HuiHuangShi** [comment]
3 new potential violations to the coding guideline detected. Please help check. Thanks!<br><1> config:sharing_config filename:/hypervisor/lib/stack_protector.c func:__stack_chk_fail offset:8<br> reason:No prototype for non-static function. : __stack_chk_fail<br><2> config:part_config filename:/hypervisor/lib/stack_protector.c func:__stack_chk_fail offset:8<br> reason:No prototype for non-static function. : __stack_chk_fail<br><3> config:common filename:/hypervisor/include/arch/x86/multiboot.h func: offset:21<br> reason:Struct/union not completely specified.       : acrn_vm<br><br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by HuiHuangShi** [comment]
2 new potential violations to the coding guideline detected. Please help check. Thanks!<br><1> config:common filename:/hypervisor/lib/stack_protector.c func: offset:8<br> reason:User name starts with underscore.            : __stack_chk_fail<br><2> config:common filename:/hypervisor/include/dm/vacpi.h func: offset:49<br> reason:Struct/union not completely specified.       : acrn_vm<br><br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Pull request merged**
