### PR TITLE
update launch_uos.sh to align with ACRN v0.1

### PR DESCRIPTION
**Pull request by ailun258**
update the kernel version to align with ACRN v0.1 and fix a graphic display issue with i915.enable_initial_modeset=1 for UOS

Signed-off-by: ailun258 <ailin.yang@intel.com>

### CODE REVIEW

**Comment by NanlinXie** [comment]
Can one of the admins verify this patch?

**Comment by dongyaozu** [comment]
@binbinwu1  please review

**Comment by binbinwu1** [comment]
@minhe1 Can you help to review the i915 parameter change?

**Comment by dongyaozu** [comment]
let us merge it. @feijiang1  build failed

**Comment by ailun258** [comment]
@minhe1  got it, 
who can help to get approval this patch first, and modify again later,

**Comment by dongyaozu** [comment]
What does it mean? You need to fix it, and update to get +1 from minhe

**Comment by ailun258** [comment]
@minhe1 please help to review again

**Comment by minhe1** [comment]
@ailun258 ，this version looks good to me, but you added a extra space in line 33. Can you upload another version? Thanks.

**Comment by ailun258** [comment]
@minhe1  looks i need to submit another patch to add extra space,  i wanted to modify this patch directly,

**Pull request closed without merging**
