### PR TITLE
doc: update waag GSG according to the latest method

### PR DESCRIPTION
**Pull request by shenfang2019**
Delete Redhad virtio drive, only keep Oracle as reference.
Delete "inject driver into ISO" part.
In a word, QA just need maintain one latest workable method in GSG for creating WaaG image.

Signed-off-by: ffshen <fangfang.shen@intel.com>

### CODE REVIEW

**Comment by ClaudZhang1995** [comment]
@shenfang2019 hi, make doc fail.It`s fail log :
/root/workspace/acrn-hypervisor-premerge-build-image4/acrn-hypervisor/build/doc/rst/tutorials/using_windows_as_uos.rst:186: WARNING: Enumerated list ends without a blank line; unexpected unindent.
/root/workspace/acrn-hypervisor-premerge-build-image4/acrn-hypervisor/build/doc/rst/tutorials/using_windows_as_uos.rst:300: WARNING: Inline emphasis start-string without end-string.
/root/workspace/acrn-hypervisor-premerge-build-image4/acrn-hypervisor/build/doc/rst/tutorials/using_windows_as_uos.rst:321: WARNING: Footnote [1] is not referenced.

**Comment by ClaudZhang1995** [comment]
OK to verify

**Comment by ClaudZhang1995** [comment]
OK to verify

**Comment by ClaudZhang1995** [comment]
OK to verify

**Comment by HuiHuangShi** [comment]
No new violations to the coding guideline detected.<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by shenfang2019** [comment]
> Recommend that a spell check is done on the new changes in the commit.
> Pre-install drivers and re-generate Windows ISO, needs to be added back, else the Windows ISO image windows10-17763-107-LTSC-Virtio-Gfx.iso is not created containing the oracle virtio FE drivers.
> Also ensure inject of drivers batch file only talks about Oracle driver and remove all references of redhat virtio drivers.

@kpanchag  We can use original ISO to create WaaG img now, oracle virtio driver can be installed in the begging of WaaG img creating procedure, and we also added step to install gvt driver once generating WaaG img. And QA have verified the method is workable.

**Comment by wenlingz** [comment]
@shenfang2019 please refer the log:
make[1]: Entering directory '/root/workspace/acrn-hypervisor-premerge-build-image/acrn-hypervisor/doc'

New errors/warnings found, please fix them:
==============================================

/root/workspace/acrn-hypervisor-premerge-build-image/acrn-hypervisor/build/doc/rst/tutorials/using_windows_as_uos.rst:133: WARNING: Title underline too short.

Prepare Script to Create Image
-----------------------------
/root/workspace/acrn-hypervisor-premerge-build-image/acrn-hypervisor/build/doc/rst/tutorials/using_windows_as_uos.rst:133: WARNING: Title underline too short.

Prepare Script to Create Image
-----------------------------

make[1]: Leaving directory '/root/workspace/acrn-hypervisor-premerge-build-image/acrn-hypervisor/doc'
make[1]: *** [Makefile:61: html] Error 1
make: *** [Makefile:159: doc] Error 2
Build step 'Execute shell' marked build as failure

**Comment by ClaudZhang1995** [comment]
OK to verify

**Comment by ClaudZhang1995** [comment]
OK to verify

**Comment by gvancuts** [comment]
@deb-intel do you have this on your radar for a review (or later update)? Tx!

**Comment by deb-intel** [comment]
@gvancuts Yes! I'm currently publishing a few smaller PRs now. Will complete this and #4482 later on today.

**Comment by deb-intel** [comment]
@NanlinXie Do you want me to merge this now?

**Comment by NanlinXie** [comment]
@deb-intel , please hold on, I am waiting for feedback from @kpanchag

**Pull request merged**
