### PR TITLE
doc: update virtio GPU device documentation

### PR DESCRIPTION
**Pull request by dbkinder**
Fix broken formatting of virtio GPU device documentation

Tracked-On: #5692

Signed-off-by: David B. Kinder <david.b.kinder@intel.com>

### CODE REVIEW

**Comment by acrnsi** [comment]
Can one of the admins verify this patch?

**Comment by dbkinder** [comment]
As previously written, the extra indenting breaks the formatting (shown correctly on the virtio block device option above it):
image

**Review by amyreye — APPROVED** [review]

**Comment by dbkinder** [comment]
@NanlinXie Is it OK for me to merge documentation tweaks in the schema files such as this PR, or do you want engineering to do these?

**Comment by dbkinder** [comment]
Duplicate of #7395 (doh)

**Pull request closed without merging**
