### PR TITLE
fix "Attempt to change parameter passed by value."

### PR DESCRIPTION
**Pull request by HuiHuangShi**
parameter can't be changed in the function.
fix "Attempt to change parameter passed by value. : err_code" violations.

Tracked-On: #861
Signed-off-by: Huihuang Shi <huihuang.shi@intel.com>
Acked-by: Eddie Dong <eddie.dong@intel.com>

### CODE REVIEW

**Comment by HuiHuangShi** [comment]
2315<br>No new violations to the coding guideline detected.

**Comment by wenlingz** [comment]
@HuiHuangShi please check your code, build fail

**Comment by HuiHuangShi** [comment]
2315<br>No new violations to the coding guideline detected.

**Comment by wenlingz** [comment]
@HuiHuangShi please rebase your code,thanks

**Comment by HuiHuangShi** [comment]
The newest merged patch have fixed.

**Pull request closed without merging**
