### PR TITLE
config_tools: add passthru devices for logical partition scenario on ehl

### PR DESCRIPTION
**Pull request by szhen11**
add passthru devices for logical partition scenario on ehl.

Tracked-On: #5665

Signed-off-by: Shuang Zheng <shuang.zheng@intel.com>

### CODE REVIEW

**Review by terryzouhao — APPROVED** [review]

**Comment by HuiHuangShi** [comment]
No New Name Conflict<br><No New Function Declaration/Definition Mismatch

**Comment by HuiHuangShi** [comment]
No New Name Conflict<br>No New Function Declaration/Definition Mismatch

**Comment by HuiHuangShi** [comment]
No New Name Conflict<br>No New Function Declaration/Definition Mismatch

**Comment by HuiHuangShi** [comment]
No New Name Conflict<br>No New Function Declaration/Definition Mismatch

**Comment by wenlingz** [comment]
try verify ldra

**Comment by HuiHuangShi** [comment]
No new violations to the coding guideline detected.<br>No New Name Conflict<br>No New Function Declaration/Definition Mismatch

**Comment by HuiHuangShi** [comment]
No new violations to the coding guideline detected.<br>No New Name Conflict<br>No New Function Declaration/Definition Mismatch

**Pull request merged**
