### PR TITLE
doc: remove unreferenced tutorial scripts

### PR DESCRIPTION
**Pull request by dbkinder**
Four scripts were referenced by documentation that was deleted.  Let's
remove those scripts now too.

Signed-off-by: David B. Kinder <david.b.kinder@intel.com>

### CODE REVIEW

**Comment by HuiHuangShi** [comment]
No new violations to the coding guideline detected.<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Review by gvancuts — APPROVED** [review]
Goof catch! Thanks! :+1:

**Comment by gvancuts** [comment]
How about removing the `doc/getting-started/Dockerfile` too as part of this PR?

**Comment by dbkinder** [comment]
@gvancuts @NanlinXie Alas, we can't remove these obsolete scripts from the master branch because there are references to them in older version-specific documentation.  For example, in the v2.1 documentation, references to the ``getting_started/acrn_quick_setup.sh`` script are linked as ``<https://raw.githubusercontent.com/projectacrn/acrn-hypervisor/master/doc/getting-started/acrn_quick_setup.sh>`_`` and such a reference would break if we deleted the (now obsolete) script from the master branch.  Sigh.  Such links need to be made to the version-specific commit and not to master.

**Comment by dbkinder** [comment]
Closing this PR for now because we can't delete these obsolete scripts while we have references to them in the archived documentation.

**Comment by NanlinXie** [comment]
@dbkinder , we could update document to reference link as https://raw.githubusercontent.com/projectacrn/acrn-hypervisor/release_2.1/doc/getting-started/acrn_quick_setup.sh.

**Comment by gvancuts** [comment]
> @dbkinder , we could update document to reference link as https://raw.githubusercontent.com/projectacrn/acrn-hypervisor/release_2.1/doc/getting-started/acrn_quick_setup.sh.

I wouldn't rewrite the git history but perhaps we can patch the previous release branches with a commit that updates these URLs to use the matching release?

**Comment by dbkinder** [comment]
@gvancuts @NanlinXie In addition to going back through the previous ACRN releases and fixing the .rst files with references to scripts and such in the master branch, we also need to fix mentions in code blocks that use ``wget`` or ``curl`` in examples that download from the master branch too.  Then, we'd need to regenerate and republish the older documentation with these fixes.  Not a fun effort.  Alternatively, we leave the files in master for a while longer, and/or we just fix the issue with the 2.* releases and don't worry about earlier ones.  (It may be a good idea to just removed the published 1.* release documentation.)  

I did submit a PR #5472 to fix this problem for the v2.3 release and after, so we won't continue referencing the master branch from tagged version documentation, and we'll be on the lookout for this in code block examples.

**Comment by gvancuts** [comment]
> @gvancuts @NanlinXie In addition to going back through the previous ACRN releases and fixing the .rst files with references to scripts and such in the master branch, we also need to fix mentions in code blocks that use `wget` or `curl` in examples that download from the master branch too. Then, we'd need to regenerate and republish the older documentation with these fixes. Not a fun effort. Alternatively, we leave the files in master for a while longer, and/or we just fix the issue with the 2.* releases and don't worry about earlier ones. (It may be a good idea to just removed the published 1.* release documentation.)

👍 on just fixing the 2.x releases. I have no objection to removing the 1.x documentations.

> 
> I did submit a PR #5472 to fix this problem for the v2.3 release and after, so we won't continue referencing the master branch from tagged version documentation, and we'll be on the lookout for this in code block examples.

Cool feature! :-)

**Pull request closed without merging**
