### PR TITLE
doc: update configuration tool description of vuarts

### PR DESCRIPTION
**Pull request by yuchuyang**
Acrn introduces pci based vuart. Update the existing vuarts and add the
pci based vuart description

1. rename existing vuarts to legacy_vuart
2. add console and communication vuarts general desciption
  - the console vuart is similar to legacy_vuart0 but only contains subtag "base"
  - the communication vuart is similar to legacy_vuart1 but only contains subtags
    "base", "target_vm_id" and "target_uart_id"

Signed-off-by: Yang,Yu-chu <yu-chu.yang@intel.com>

### CODE REVIEW

**Comment by HuiHuangShi** [comment]
No new violations to the coding guideline detected.<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by wenlingz** [comment]
@yuchuyang @NanlinXie this doc only need to in release_2.3 ??

**Comment by yuchuyang** [comment]
@wenlingz  master PR is https://github.com/projectacrn/acrn-hypervisor/pull/5536

**Comment by NanlinXie** [comment]
Document PR need to be filed to mainline. We will align document in v2.3 release branch when we tag v2.3.

**Comment by yuchuyang** [comment]
@NanlinXie  In that case, shall I close this PR for 2.3?

**Comment by wenlingz** [comment]
I close this PR because doc don't need to in branch

**Pull request closed without merging**
