### PR TITLE
doc: add RTC virtualization doc

### PR DESCRIPTION
**Pull request by gaojunhao0504**
add RTC virtualization doc and add entry in hld-emulated-devices

Signed-off-by: Gao Junhao <junhao.gao@intel.com>

### CODE REVIEW

**Comment by acrnsi** [comment]
OK to verify

**Comment by acrnsi** [comment]
OK to verify

**Comment by deb-intel** [comment]
@gaojunhao0504 Please correct the toctree conflict in your file so that I can merge the PR. Thx

 Watchdog virtualization <watchdog-hld>      <------- incorrect list
   GVT-g GPU virtualization <hld-APL_GVT-g>
   RTC emulation in hypervisor <rtc-virt-hld>
=======
   Watchdoc virtualization <watchdog-hld>     <------- correct
   AHCI virtualization <ahci-hld>
   GVT-g GPU Virtualization <hld-APL_GVT-g>
   UART emulation in hypervisor <vuart-virt-hld>

**Comment by deb-intel** [comment]
@gaojunhao0504 Please resolve the conflict in the toctree for hld-emulated-devices.rst. The master branch is correct.

--
<<<<<<< rtc
   Watchdog virtualization <watchdog-hld>
   GVT-g GPU virtualization <hld-APL_GVT-g>
   RTC emulation in hypervisor <rtc-virt-hld>
=======
   Watchdoc virtualization <watchdog-hld>
   AHCI virtualization <ahci-hld>
   GVT-g GPU Virtualization <hld-APL_GVT-g>
   UART emulation in hypervisor <vuart-virt-hld>
>>>>>>> master

**Comment by gaojunhao0504** [comment]
> @gaojunhao0504 Please resolve the conflict in the toctree for hld-emulated-devices.rst. The master branch is correct; remove the rtc branch.

@deb-intel  Thanks for attention, I have rebased the rtc branch and try to push rtc barnch again, then after this merging, could I follow this sequence "hostbridge emulation -> AT Keyboard controller emulation" to rebase and push?

**Pull request merged**
