### PR TITLE
hv: refactor seed management

### PR DESCRIPTION
**Pull request by YadongQi**
New component to maintain seed retrieval and derivation: seed.

1. Retrieve seed from bootloader in Hypervisor's boot stage.
2. Derive virtual seed for Guest/Trusty if need.

Tracked-On: #2724
Signed-off-by: Qi Yadong <yadong.qi@intel.com>
Reviewed-by: Zhu Bing <bing.zhu@intel.com>

### CODE REVIEW

**Comment by HuiHuangShi** [comment]
64 new potential violations to the coding guideline detected. Please help check. Thanks!<br><1> config:common filename:/hypervisor/arch/x86/seed/seed.c func: offset:26<br> reason:Literal value requires a U suffix.           : 0UL<br><2> config:common filename:/hypervisor/arch/x86/seed/seed.c func:parse_seed_arg offset:45<br> reason:Casting operation to a pointer. : (void* to struct multiboot_info*): ( struct multiboot_info * ) hpa2hva ( ( uint64_t ) boot_regs [ 1 ] )<br><3> config:common filename:/hypervisor/arch/x86/seed/seed.c func:parse_seed_arg offset:45<br> reason:Casting operation on a pointer. : (void* to struct multiboot_info*): ( struct multiboot_info * ) hpa2hva ( ( uint64_t ) boot_regs [ 1 ] )<br><4> config:part_config filename:/hypervisor/arch/x86/seed/seed.c func:parse_seed_arg offset:46<br> reason:Pointer not checked for null before use. : mbi<br><5> config:sharing_config filename:/hypervisor/arch/x86/seed/seed.c func:parse_seed_arg offset:46<br> reason:Pointer not checked for null before use. : mbi<br><6> config:part_config filename:/hypervisor/arch/x86/seed/seed.c func:parse_seed_arg offset:47<br> reason:Function return value potentially unused. : cmd_src<br><7> config:sharing_config filename:/hypervisor/arch/x86/seed/seed.c func:parse_seed_arg offset:47<br> reason:Function return value potentially unused. : cmd_src<br><8> config:sharing_config filename:/hypervisor/arch/x86/seed/seed.c func:parse_seed_arg offset:53<br> reason:Pointer not checked for null before use. : cmd_src<br><9> config:part_config filename:/hypervisor/arch/x86/seed/seed.c func:parse_seed_arg offset:53<br> reason:Pointer not checked for null before use. : cmd_src<br><10> config:part_config filename:/hypervisor/arch/x86/seed/seed.c func:parse_seed_arg offset:53<br> reason:Pointer assigned to NULL may be dereferenced. : cmd_src<br><11> config:sharing_config filename:/hypervisor/arch/x86/seed/seed.c func:parse_seed_arg offset:53<br> reason:Pointer assigned to NULL may be dereferenced. : cmd_src<br><12> config:common filename:/hypervisor/arch/x86/seed/seed.c func:parse_seed_arg offset:66<br> reason:Implicit conversion: actual to formal param (MR). :  (char and unsigned char):  param  2<br><13> config:sharing_config filename:/hypervisor/arch/x86/seed/seed.c func:append_seed_arg offset:91<br> reason:Pointer param should be declared pointer to const. : vm<br><14> config:part_config filename:/hypervisor/arch/x86/seed/seed.c func:append_seed_arg offset:91<br> reason:Pointer param should be declared pointer to const. : vm<br><15> config:common filename:/hypervisor/arch/x86/seed/seed.c func:append_seed_arg offset:97<br> reason:Literal value requires a U suffix.           : 0<br><16> config:common filename:/hypervisor/arch/x86/seed/seed.c func:append_seed_arg offset:97<br> reason:Signed/unsigned conversion without cast. :  (unsigned int and int): i<br><17> config:common filename:/hypervisor/arch/x86/seed/seed.c func:append_seed_arg offset:99<br> reason:Use of sizeof on an array parameter.<br><18> config:common filename:/hypervisor/arch/x86/seed/seed.c func:append_seed_arg offset:99<br> reason:(void) missing for discarded return value.<br><19> config:common filename:/hypervisor/arch/x86/seed/seed.c func:append_seed_arg offset:101<br> reason:Use of sizeof on an array parameter.<br><20> config:common filename:/hypervisor/arch/x86/seed/seed.c func:append_seed_arg offset:104<br> reason:Signed/unsigned conversion without cast. :  (unsigned int and signed char): seed_arg [ i ].bootloader_id == BOOTLOADER_SBL<br><21> config:common filename:/hypervisor/arch/x86/seed/seed.c func:append_seed_arg offset:106<br> reason:Casting operation to a pointer. : (void* to struct image_boot_params*): ( struct image_boot_params * ) hpa2hva ( seed_arg [ i ] .addr )<br><22> config:common filename:/hypervisor/arch/x86/seed/seed.c func:append_seed_arg offset:106<br> reason:Casting operation on a pointer. : (void* to struct image_boot_params*): ( struct image_boot_params * ) hpa2hva ( seed_arg [ i ] .addr )<br><23> config:sharing_config filename:/hypervisor/arch/x86/seed/seed.c func:append_seed_arg offset:108<br> reason:Function return value potentially unused. : (boot_params)->p_seed_list<br><24> config:part_config filename:/hypervisor/arch/x86/seed/seed.c func:append_seed_arg offset:108<br> reason:Function return value potentially unused. : (boot_params)->p_seed_list<br><25> config:part_config filename:/hypervisor/arch/x86/seed/seed.c func:append_seed_arg offset:110<br> reason:Function return value potentially unused. : (boot_params)->p_platform_info<br><26> config:sharing_config filename:/hypervisor/arch/x86/seed/seed.c func:append_seed_arg offset:110<br> reason:Function return value potentially unused. : (boot_params)->p_platform_info<br><27> config:common filename:/hypervisor/arch/x86/seed/seed.c func:derive_virtual_seed offset:151<br> reason:Value is not of appropriate type. :  (int and unsigned char): hkdf_sha256 ( seed_list [ i ].seed , sizeof ( seed_list [ i ] .seed ) , g_phy_seed.seed_list [ i ].seed , sizeof ( g_phy_seed.seed_list [ i ] .seed ) , salt , salt_len , info , info_len )   == 0U<br><28> config:sharing_config filename:/hypervisor/arch/x86/seed/seed.c func:derive_attkb_enc_key offset:199<br> reason:Pointer param should be declared pointer to const. : out_key<br><29> config:part_config filename:/hypervisor/arch/x86/seed/seed.c func:derive_attkb_enc_key offset:199<br> reason:Pointer param should be declared pointer to const. : out_key<br><30> config:common filename:/hypervisor/arch/x86/seed/seed.c func:derive_attkb_enc_key offset:205<br> reason:Value is not of appropriate type. :  (unsigned char and char):<br><31> config:common filename:/hypervisor/arch/x86/seed/seed.c func:derive_attkb_enc_key offset:216<br> reason:Use of sizeof on an array parameter.<br><32> config:common filename:/hypervisor/arch/x86/seed/seed.c func:derive_attkb_enc_key offset:216<br> reason:Value is not of appropriate type. :  (int and unsigned char): hmac_sha256 ( out_key , ikm , ikm_len , salt , sizeof ( salt ) )   != 1U<br><33> config:common filename:/hypervisor/arch/x86/seed/seed.c func:init_seed offset:241<br> reason:Switch case not terminated with break.<br><34> config:common filename:/hypervisor/arch/x86/seed/seed.c func:init_seed offset:246<br> reason:(void) missing for discarded return value.<br>.....<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by HuiHuangShi** [comment]
out of time

**Comment by HuiHuangShi** [comment]
47 new potential violations to the coding guideline detected. Please help check. Thanks!<br><1> config:common filename:/hypervisor/arch/x86/seed/seed.c func: offset:27<br> reason:Literal value requires a U suffix.           : 0UL<br><2> config:common filename:/hypervisor/arch/x86/seed/seed.c func:parse_seed_arg offset:41<br> reason:Signed/unsigned conversion without cast. :  (unsigned int): 4U<br><3> config:common filename:/hypervisor/arch/x86/seed/seed.c func:parse_seed_arg offset:41<br> reason:Use of mixed mode arithmetic. :  (unsigned char and signed char): 4U - 1<br><4> config:common filename:/hypervisor/arch/x86/seed/seed.c func:parse_seed_arg offset:47<br> reason:Casting operation to a pointer. : (void* to struct multiboot_info*): ( struct multiboot_info * ) hpa2hva ( ( uint64_t ) boot_regs [ 1U ] )<br><5> config:common filename:/hypervisor/arch/x86/seed/seed.c func:parse_seed_arg offset:47<br> reason:Casting operation on a pointer. : (void* to struct multiboot_info*): ( struct multiboot_info * ) hpa2hva ( ( uint64_t ) boot_regs [ 1U ] )<br><6> config:common filename:/hypervisor/arch/x86/seed/seed.c func:parse_seed_arg offset:71<br> reason:Implicit conversion: actual to formal param (MR). :  (char and unsigned char):  param  2<br><7> config:sharing_config filename:/hypervisor/arch/x86/seed/seed.c func:append_seed_arg offset:97<br> reason:Pointer param should be declared pointer to const. : vm<br><8> config:part_config filename:/hypervisor/arch/x86/seed/seed.c func:append_seed_arg offset:97<br> reason:Pointer param should be declared pointer to const. : vm<br><9> config:common filename:/hypervisor/arch/x86/seed/seed.c func:append_seed_arg offset:105<br> reason:Use of sizeof on an array parameter.<br><10> config:common filename:/hypervisor/arch/x86/seed/seed.c func:append_seed_arg offset:107<br> reason:Use of sizeof on an array parameter.<br><11> config:common filename:/hypervisor/arch/x86/seed/seed.c func:append_seed_arg offset:110<br> reason:Signed/unsigned conversion without cast. :  (unsigned int and signed char): seed_arg [ i ].bootloader_id == BOOTLOADER_SBL<br><12> config:common filename:/hypervisor/arch/x86/seed/seed.c func:append_seed_arg offset:112<br> reason:Casting operation to a pointer. : (void* to struct image_boot_params*): ( struct image_boot_params * ) hpa2hva ( seed_arg [ i ] .addr )<br><13> config:common filename:/hypervisor/arch/x86/seed/seed.c func:append_seed_arg offset:112<br> reason:Casting operation on a pointer. : (void* to struct image_boot_params*): ( struct image_boot_params * ) hpa2hva ( seed_arg [ i ] .addr )<br><14> config:sharing_config filename:/hypervisor/arch/x86/seed/seed.c func:append_seed_arg offset:114<br> reason:Function return value potentially unused. : (boot_params)->p_seed_list<br><15> config:part_config filename:/hypervisor/arch/x86/seed/seed.c func:append_seed_arg offset:114<br> reason:Function return value potentially unused. : (boot_params)->p_seed_list<br><16> config:part_config filename:/hypervisor/arch/x86/seed/seed.c func:append_seed_arg offset:116<br> reason:Function return value potentially unused. : (boot_params)->p_platform_info<br><17> config:sharing_config filename:/hypervisor/arch/x86/seed/seed.c func:append_seed_arg offset:116<br> reason:Function return value potentially unused. : (boot_params)->p_platform_info<br><18> config:sharing_config filename:/hypervisor/arch/x86/seed/seed.c func:derive_attkb_enc_key offset:205<br> reason:Pointer param should be declared pointer to const. : out_key<br><19> config:part_config filename:/hypervisor/arch/x86/seed/seed.c func:derive_attkb_enc_key offset:205<br> reason:Pointer param should be declared pointer to const. : out_key<br><20> config:common filename:/hypervisor/arch/x86/seed/seed.c func:derive_attkb_enc_key offset:211<br> reason:Value is not of appropriate type. :  (unsigned char and char):<br><21> config:common filename:/hypervisor/arch/x86/seed/seed.c func:derive_attkb_enc_key offset:222<br> reason:Use of sizeof on an array parameter.<br><22> config:common filename:/hypervisor/arch/x86/seed/seed.c func:init_seed offset:253<br> reason:Implicit conversion: actual to formal param (MR). :  (struct seed_info and void):  param  1<br><23> config:common filename:/hypervisor/arch/x86/seed/seed_abl.c func:parse_seed_abl offset:46<br> reason:Casting operation to a pointer. : (void* to struct abl_svn_seed*): ( struct abl_svn_seed * ) hpa2hva ( addr )<br><24> config:common filename:/hypervisor/arch/x86/seed/seed_abl.c func:parse_seed_abl offset:46<br> reason:Casting operation on a pointer. : (void* to struct abl_svn_seed*): ( struct abl_svn_seed * ) hpa2hva ( addr )<br><25> config:common filename:/hypervisor/arch/x86/seed/seed_abl.c func:parse_seed_abl offset:73<br> reason:Casting operation to a pointer. : (struct seed_info to void*): seed_list<br><26> config:common filename:/hypervisor/arch/x86/seed/seed_abl.c func:parse_seed_abl offset:76<br> reason:Implicit conversion: actual to formal param (MR). :  (unsigned char and void):  param  3<br><27> config:common filename:/hypervisor/arch/x86/seed/seed_abl.c func:parse_seed_abl offset:83<br> reason:Implicit conversion: actual to formal param (MR). :  (unsigned char and void):  param  1<br><28> config:common filename:/hypervisor/include/arch/x86/guest/vm.h func:vcpu_from_pid offset:192<br> reason:Type conversion without cast. :  (struct acrn_vcpu* and void*): target_vcpu = vcpu<br><29> config:common filename:/hypervisor/arch/x86/seed/seed_sbl.c func:parse_seed_sbl offset:69<br> reason:Casting operation to a pointer. : (void* to struct image_boot_params*): ( struct image_boot_params * ) hpa2hva ( addr )<br><30> config:common filename:/hypervisor/arch/x86/seed/seed_sbl.c func:parse_seed_sbl offset:69<br> reason:Casting operation on a pointer. : (void* to struct image_boot_params*): ( struct image_boot_params * ) hpa2hva ( addr )<br><31> config:sharing_config filename:/hypervisor/arch/x86/seed/seed_sbl.c func:parse_seed_sbl offset:72<br> reason:Function return value potentially unused. : seed_hob<br><32> config:part_config filename:/hypervisor/arch/x86/seed/seed_sbl.c func:parse_seed_sbl offset:72<br> reason:Function return value potentially unused. : seed_hob<br><33> config:common filename:/hypervisor/arch/x86/seed/seed_sbl.c func:parse_seed_sbl offset:72<br> reason:Casting operation to a pointer. : (void* to struct seed_list_hob*): ( struct seed_list_hob * ) hpa2hva ( boot_params -> p_seed_list )<br><34> config:common filename:/hypervisor/arch/x86/seed/seed_sbl.c func:parse_seed_sbl offset:72<br> reason:Casting operation on a pointer. : (void* to struct seed_list_hob*): ( struct seed_list_hob * ) hpa2hva ( boot_params -> p_seed_list )<br>.....<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by acrnsi** [comment]
@YadongQi  please rebase your code ,thanks

**Comment by HuiHuangShi** [comment]
42 new potential violations to the coding guideline detected. Please help check. Thanks!<br><1> config:common filename:/hypervisor/arch/x86/seed/seed.c func:parse_seed_arg offset:39<br> reason:Signed/unsigned conversion without cast. :  (unsigned int): 4U<br><2> config:common filename:/hypervisor/arch/x86/seed/seed.c func:parse_seed_arg offset:45<br> reason:Casting operation to a pointer. : (void* to struct multiboot_info*): ( struct multiboot_info * ) hpa2hva ( ( uint64_t ) boot_regs [ 1U ] )<br><3> config:common filename:/hypervisor/arch/x86/seed/seed.c func:parse_seed_arg offset:45<br> reason:Casting operation on a pointer. : (void* to struct multiboot_info*): ( struct multiboot_info * ) hpa2hva ( ( uint64_t ) boot_regs [ 1U ] )<br><4> config:common filename:/hypervisor/arch/x86/seed/seed.c func:parse_seed_arg offset:69<br> reason:Implicit conversion: actual to formal param (MR). :  (char and unsigned char):  param  2<br><5> config:sharing_config filename:/hypervisor/arch/x86/seed/seed.c func:append_seed_arg offset:95<br> reason:Pointer param should be declared pointer to const. : vm<br><6> config:part_config filename:/hypervisor/arch/x86/seed/seed.c func:append_seed_arg offset:95<br> reason:Pointer param should be declared pointer to const. : vm<br><7> config:common filename:/hypervisor/arch/x86/seed/seed.c func:append_seed_arg offset:103<br> reason:Use of sizeof on an array parameter.<br><8> config:common filename:/hypervisor/arch/x86/seed/seed.c func:append_seed_arg offset:105<br> reason:Use of sizeof on an array parameter.<br><9> config:common filename:/hypervisor/arch/x86/seed/seed.c func:append_seed_arg offset:110<br> reason:Casting operation to a pointer. : (void* to struct image_boot_params*): ( struct image_boot_params * ) hpa2hva ( seed_arg [ i ] .addr )<br><10> config:common filename:/hypervisor/arch/x86/seed/seed.c func:append_seed_arg offset:110<br> reason:Casting operation on a pointer. : (void* to struct image_boot_params*): ( struct image_boot_params * ) hpa2hva ( seed_arg [ i ] .addr )<br><11> config:sharing_config filename:/hypervisor/arch/x86/seed/seed.c func:append_seed_arg offset:112<br> reason:Function return value potentially unused. : (boot_params)->p_seed_list<br><12> config:part_config filename:/hypervisor/arch/x86/seed/seed.c func:append_seed_arg offset:112<br> reason:Function return value potentially unused. : (boot_params)->p_seed_list<br><13> config:part_config filename:/hypervisor/arch/x86/seed/seed.c func:append_seed_arg offset:115<br> reason:Function return value potentially unused. : (boot_params)->p_platform_info<br><14> config:sharing_config filename:/hypervisor/arch/x86/seed/seed.c func:append_seed_arg offset:115<br> reason:Function return value potentially unused. : (boot_params)->p_platform_info<br><15> config:sharing_config filename:/hypervisor/arch/x86/seed/seed.c func:derive_attkb_enc_key offset:204<br> reason:Pointer param should be declared pointer to const. : out_key<br><16> config:part_config filename:/hypervisor/arch/x86/seed/seed.c func:derive_attkb_enc_key offset:204<br> reason:Pointer param should be declared pointer to const. : out_key<br><17> config:common filename:/hypervisor/arch/x86/seed/seed.c func:derive_attkb_enc_key offset:210<br> reason:Value is not of appropriate type. :  (unsigned char and char):<br><18> config:common filename:/hypervisor/arch/x86/seed/seed.c func:derive_attkb_enc_key offset:221<br> reason:Use of sizeof on an array parameter.<br><19> config:common filename:/hypervisor/arch/x86/seed/seed_abl.c func:parse_seed_abl offset:46<br> reason:Casting operation to a pointer. : (void* to struct abl_svn_seed*): ( struct abl_svn_seed * ) hpa2hva ( addr )<br><20> config:common filename:/hypervisor/arch/x86/seed/seed_abl.c func:parse_seed_abl offset:46<br> reason:Casting operation on a pointer. : (void* to struct abl_svn_seed*): ( struct abl_svn_seed * ) hpa2hva ( addr )<br><21> config:part_config filename:/hypervisor/arch/x86/seed/seed_abl.c func:parse_seed_abl offset:75<br> reason:Pointer not checked for null before use. : seed_list<br><22> config:sharing_config filename:/hypervisor/arch/x86/seed/seed_abl.c func:parse_seed_abl offset:75<br> reason:Pointer not checked for null before use. : seed_list<br><23> config:common filename:/hypervisor/arch/x86/seed/seed_abl.c func:parse_seed_abl offset:76<br> reason:Implicit conversion: actual to formal param (MR). :  (unsigned char and void):  param  3<br><24> config:common filename:/hypervisor/arch/x86/seed/seed_abl.c func:parse_seed_abl offset:83<br> reason:Implicit conversion: actual to formal param (MR). :  (unsigned char and void):  param  1<br><25> config:common filename:/hypervisor/include/arch/x86/guest/vm.h func:vcpu_from_pid offset:191<br> reason:Type conversion without cast. :  (struct acrn_vcpu* and void*): target_vcpu = vcpu<br><26> config:common filename:/hypervisor/arch/x86/seed/seed_sbl.c func:parse_seed_sbl offset:69<br> reason:Casting operation to a pointer. : (void* to struct image_boot_params*): ( struct image_boot_params * ) hpa2hva ( addr )<br><27> config:common filename:/hypervisor/arch/x86/seed/seed_sbl.c func:parse_seed_sbl offset:69<br> reason:Casting operation on a pointer. : (void* to struct image_boot_params*): ( struct image_boot_params * ) hpa2hva ( addr )<br><28> config:common filename:/hypervisor/arch/x86/seed/seed_sbl.c func:parse_seed_sbl offset:71<br> reason:Logical conjunctions need brackets.<br><29> config:common filename:/hypervisor/arch/x86/seed/seed_sbl.c func:parse_seed_sbl offset:72<br> reason:Casting operation to a pointer. : (void* to struct seed_list_hob*): ( struct seed_list_hob * ) hpa2hva ( boot_params -> p_seed_list )<br><30> config:common filename:/hypervisor/arch/x86/seed/seed_sbl.c func:parse_seed_sbl offset:72<br> reason:Casting operation on a pointer. : (void* to struct seed_list_hob*): ( struct seed_list_hob * ) hpa2hva ( boot_params -> p_seed_list )<br><31> config:common filename:/hypervisor/arch/x86/seed/seed_sbl.c func:parse_seed_sbl offset:80<br> reason:Cast to an unrelated type. : (unsigned char* to struct seed_entry*): ( struct seed_entry * ) ( ( uint8_t * ) seed_hob + sizeof ( struct seed_list_hob ) )<br><32> config:common filename:/hypervisor/arch/x86/seed/seed_sbl.c func:parse_seed_sbl offset:80<br> reason:Casting operation to a pointer. : (unsigned char* to struct seed_entry*): ( struct seed_entry * ) ( ( uint8_t * ) seed_hob + sizeof ( struct seed_list_hob ) )<br><33> config:common filename:/hypervisor/arch/x86/seed/seed_sbl.c func:parse_seed_sbl offset:80<br> reason:Casting operation on a pointer. : (unsigned char* to struct seed_entry*): ( struct seed_entry * ) ( ( uint8_t * ) seed_hob + sizeof ( struct seed_list_hob ) )<br><34> config:common filename:/hypervisor/arch/x86/seed/seed_sbl.c func:parse_seed_sbl offset:98<br> reason:Cast from integral type to pointer. : (unsigned char to void*): ( void * ) & entry -> seed [ 0U ]<br>.....<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by HuiHuangShi** [comment]
41 new potential violations to the coding guideline detected. Please help check. Thanks!<br><1> config:common filename:/hypervisor/arch/x86/seed/seed.c func:parse_seed_arg offset:39<br> reason:Signed/unsigned conversion without cast. :  (unsigned int): 4U<br><2> config:common filename:/hypervisor/arch/x86/seed/seed.c func:parse_seed_arg offset:45<br> reason:Casting operation to a pointer. : (void* to struct multiboot_info*): ( struct multiboot_info * ) hpa2hva ( ( uint64_t ) boot_regs [ 1U ] )<br><3> config:common filename:/hypervisor/arch/x86/seed/seed.c func:parse_seed_arg offset:45<br> reason:Casting operation on a pointer. : (void* to struct multiboot_info*): ( struct multiboot_info * ) hpa2hva ( ( uint64_t ) boot_regs [ 1U ] )<br><4> config:common filename:/hypervisor/arch/x86/seed/seed.c func:parse_seed_arg offset:69<br> reason:Implicit conversion: actual to formal param (MR). :  (char and unsigned char):  param  2<br><5> config:sharing_config filename:/hypervisor/arch/x86/seed/seed.c func:append_seed_arg offset:95<br> reason:Pointer param should be declared pointer to const. : vm<br><6> config:part_config filename:/hypervisor/arch/x86/seed/seed.c func:append_seed_arg offset:95<br> reason:Pointer param should be declared pointer to const. : vm<br><7> config:common filename:/hypervisor/arch/x86/seed/seed.c func:append_seed_arg offset:103<br> reason:Use of sizeof on an array parameter.<br><8> config:common filename:/hypervisor/arch/x86/seed/seed.c func:append_seed_arg offset:105<br> reason:Use of sizeof on an array parameter.<br><9> config:common filename:/hypervisor/arch/x86/seed/seed.c func:append_seed_arg offset:110<br> reason:Casting operation to a pointer. : (void* to struct image_boot_params*): ( struct image_boot_params * ) hpa2hva ( seed_arg [ i ] .addr )<br><10> config:common filename:/hypervisor/arch/x86/seed/seed.c func:append_seed_arg offset:110<br> reason:Casting operation on a pointer. : (void* to struct image_boot_params*): ( struct image_boot_params * ) hpa2hva ( seed_arg [ i ] .addr )<br><11> config:sharing_config filename:/hypervisor/arch/x86/seed/seed.c func:append_seed_arg offset:112<br> reason:Function return value potentially unused. : (boot_params)->p_seed_list<br><12> config:part_config filename:/hypervisor/arch/x86/seed/seed.c func:append_seed_arg offset:112<br> reason:Function return value potentially unused. : (boot_params)->p_seed_list<br><13> config:part_config filename:/hypervisor/arch/x86/seed/seed.c func:append_seed_arg offset:115<br> reason:Function return value potentially unused. : (boot_params)->p_platform_info<br><14> config:sharing_config filename:/hypervisor/arch/x86/seed/seed.c func:append_seed_arg offset:115<br> reason:Function return value potentially unused. : (boot_params)->p_platform_info<br><15> config:sharing_config filename:/hypervisor/arch/x86/seed/seed.c func:derive_attkb_enc_key offset:204<br> reason:Pointer param should be declared pointer to const. : out_key<br><16> config:part_config filename:/hypervisor/arch/x86/seed/seed.c func:derive_attkb_enc_key offset:204<br> reason:Pointer param should be declared pointer to const. : out_key<br><17> config:common filename:/hypervisor/arch/x86/seed/seed.c func:derive_attkb_enc_key offset:210<br> reason:Value is not of appropriate type. :  (unsigned char and char):<br><18> config:common filename:/hypervisor/arch/x86/seed/seed.c func:derive_attkb_enc_key offset:221<br> reason:Use of sizeof on an array parameter.<br><19> config:common filename:/hypervisor/arch/x86/seed/seed_abl.c func:parse_seed_abl offset:46<br> reason:Casting operation to a pointer. : (void* to struct abl_svn_seed*): ( struct abl_svn_seed * ) hpa2hva ( addr )<br><20> config:common filename:/hypervisor/arch/x86/seed/seed_abl.c func:parse_seed_abl offset:46<br> reason:Casting operation on a pointer. : (void* to struct abl_svn_seed*): ( struct abl_svn_seed * ) hpa2hva ( addr )<br><21> config:part_config filename:/hypervisor/arch/x86/seed/seed_abl.c func:parse_seed_abl offset:75<br> reason:Pointer not checked for null before use. : seed_list<br><22> config:sharing_config filename:/hypervisor/arch/x86/seed/seed_abl.c func:parse_seed_abl offset:75<br> reason:Pointer not checked for null before use. : seed_list<br><23> config:common filename:/hypervisor/arch/x86/seed/seed_abl.c func:parse_seed_abl offset:76<br> reason:Implicit conversion: actual to formal param (MR). :  (unsigned char and void):  param  3<br><24> config:common filename:/hypervisor/arch/x86/seed/seed_abl.c func:parse_seed_abl offset:83<br> reason:Implicit conversion: actual to formal param (MR). :  (unsigned char and void):  param  1<br><25> config:common filename:/hypervisor/include/arch/x86/guest/vm.h func:vcpu_from_pid offset:191<br> reason:Type conversion without cast. :  (struct acrn_vcpu* and void*): target_vcpu = vcpu<br><26> config:common filename:/hypervisor/arch/x86/seed/seed_sbl.c func:parse_seed_sbl offset:69<br> reason:Casting operation to a pointer. : (void* to struct image_boot_params*): ( struct image_boot_params * ) hpa2hva ( addr )<br><27> config:common filename:/hypervisor/arch/x86/seed/seed_sbl.c func:parse_seed_sbl offset:69<br> reason:Casting operation on a pointer. : (void* to struct image_boot_params*): ( struct image_boot_params * ) hpa2hva ( addr )<br><28> config:common filename:/hypervisor/arch/x86/seed/seed_sbl.c func:parse_seed_sbl offset:72<br> reason:Casting operation to a pointer. : (void* to struct seed_list_hob*): ( struct seed_list_hob * ) hpa2hva ( boot_params -> p_seed_list )<br><29> config:common filename:/hypervisor/arch/x86/seed/seed_sbl.c func:parse_seed_sbl offset:72<br> reason:Casting operation on a pointer. : (void* to struct seed_list_hob*): ( struct seed_list_hob * ) hpa2hva ( boot_params -> p_seed_list )<br><30> config:common filename:/hypervisor/arch/x86/seed/seed_sbl.c func:parse_seed_sbl offset:80<br> reason:Cast to an unrelated type. : (unsigned char* to struct seed_entry*): ( struct seed_entry * ) ( ( uint8_t * ) seed_hob + sizeof ( struct seed_list_hob ) )<br><31> config:common filename:/hypervisor/arch/x86/seed/seed_sbl.c func:parse_seed_sbl offset:80<br> reason:Casting operation to a pointer. : (unsigned char* to struct seed_entry*): ( struct seed_entry * ) ( ( uint8_t * ) seed_hob + sizeof ( struct seed_list_hob ) )<br><32> config:common filename:/hypervisor/arch/x86/seed/seed_sbl.c func:parse_seed_sbl offset:80<br> reason:Casting operation on a pointer. : (unsigned char* to struct seed_entry*): ( struct seed_entry * ) ( ( uint8_t * ) seed_hob + sizeof ( struct seed_list_hob ) )<br><33> config:common filename:/hypervisor/arch/x86/seed/seed_sbl.c func:parse_seed_sbl offset:98<br> reason:Cast from integral type to pointer. : (unsigned char to void*): ( void * ) & entry -> seed [ 0U ]<br><34> config:common filename:/hypervisor/arch/x86/seed/seed_sbl.c func:parse_seed_sbl offset:103<br> reason:Cast from integral type to pointer. : (unsigned char to void*): ( void * ) & entry -> seed [ 0U ]<br>.....<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by wenlingz** [comment]
@YadongQi please rebase your code, thanks

**Comment by HuiHuangShi** [comment]
out of time

**Pull request merged**
