### PR TITLE
hv: instr_emul: fix operand size decode

### PR DESCRIPTION
**Pull request by lifeix**
v1-v2:
1) Detail the comments which instruction will raise issue because of the wrong opsize update.
For the instructions which we support now, only for movsx, movzx.
2) Detail when we need to calculate memory operand.

v1:
For some instructions (like movsx, movzx which we support), there're two operands
and the source operand size is not equal to the dest operand size. In this case,
if we update the memory operand size according to the bit 0(w bit) of opcode,
we will lost the register operand size. This patch tries to fix this by calculating
memory operand size when we want to use it.

1) For some instructions (like movsx, movzx which we support), there're two operands
and the source operand size is not equal to the dest operand size. In this case,
if we update the memory operand size according to the bit 0(w bit) of opcode,
we will lost the register operand size. This patch tries to fix this by calculating
memory operand size when we want to use it.
2) Calculate memory operand size form operand size and the bit 0(w bit) of opcode
when we want to operate on memory operand.

Tracked-On: #1337
Signed-off-by: Li, Fei1 <fei1.li@intel.com>
Reviewed-by: Yin Fengwei <fengwei.yin@intel.com>
Acked-by: Eddie Dong <eddie.dong@intel.com>

### CODE REVIEW

**Comment by HuiHuangShi** [comment]
3 new potential violations to the coding guideline detected. Please help check. Thanks!<br><1> config:common filename:/hypervisor/arch/x86/guest/instr_emul.c func:decode_instruction offset:2402<br> reason:Signed/unsigned conversion without cast. :  (int and unsigned int)<br><2> config:common filename:/hypervisor/arch/x86/guest/instr_emul.c func:decode_instruction offset:2402<br> reason:Type mismatch in ternary expression. :  (int and unsigned char)<br><3> config:common filename:/hypervisor/arch/x86/guest/instr_emul.c func:decode_instruction offset:2402<br> reason:Type mismatch in ternary expression. :  (int and unsigned int)<br><br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by acrnsi** [comment]
OK to verify

**Comment by HuiHuangShi** [comment]
3 new potential violations to the coding guideline detected. Please help check. Thanks!<br><1> config:common filename:/hypervisor/arch/x86/guest/instr_emul.c func:decode_instruction offset:2402<br> reason:Signed/unsigned conversion without cast. :  (int and unsigned int)<br><2> config:common filename:/hypervisor/arch/x86/guest/instr_emul.c func:decode_instruction offset:2402<br> reason:Type mismatch in ternary expression. :  (int and unsigned char)<br><3> config:common filename:/hypervisor/arch/x86/guest/instr_emul.c func:decode_instruction offset:2402<br> reason:Type mismatch in ternary expression. :  (int and unsigned int)<br><br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by HuiHuangShi** [comment]
No new violations to the coding guideline detected.<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Pull request merged**
