### PR TITLE
hv: Create E820 entries for OS in partitioning mode ACRN

### PR DESCRIPTION
**Pull request by sainath14**
This patch creates static E820 entries for VMs launced by ACRN in
partition mode.

Signed-off-by: Sainath Grandhi <sainath.grandhi@intel.com>

### CODE REVIEW

**Comment by lijinxia** [comment]
@sainath14 #987 has been merged, would you update the patch?

**Comment by sainath14** [comment]
@lijinxia Resolved the conflict. Please help merge this patch upstream.

**Comment by lijinxia** [comment]
@sainath14 Please remove to commit 54e4dc4, it can't get merged! Would you please rebase on your folk branch and fix the confilicts?

**Comment by sainath14** [comment]
Sure, I will submit a clean commit again.

**Comment by sainath14** [comment]
@lijinxia @dongyaozu Submitted a new commit after a rebase.

**Comment by lijinxia** [comment]
Verified+1

**Pull request merged**
