### PR TITLE
debian: remove changelog in git source tree

### PR DESCRIPTION
**Pull request by jiaqingz-intel**
The changelog file is automatically generated from git commit history when building, it should not be tracked in git source tree.

Tracked-On: #6688

Reviewed-by: Junjie Mao <junjie.mao@intel.com>

### CODE REVIEW

**Comment by wenlingz** [comment]
@NanlinXie please help approve this PR, thanks

**Review by junjiemao1 — APPROVED** [review]

**Comment by wenlingz** [comment]
@NanlinXie please help approve, thanks

**Review by NanlinXie — APPROVED** [review]

**Comment by wenlingz** [comment]
start to run premerge test

**Comment by wenlingz** [comment]
start to run premerge test

**Pull request merged**
