### PR TITLE
HV: do not offline pcpu when lapic pt disabled

### PR DESCRIPTION
**Pull request by jsun26intel**
In current code, wait_pcpus_offline() and make_pcpu_offline() are called by
both shutdown_vm() and reset_vm(), but this is not needed when lapic_pt is
not enabled for the vcpus of the VM.

The patch merged offline pcpus part code into a common
offline_lapic_pt_enabled_pcpus() api for shutdown_vm() and reset_vm() use and
called only when lapic_pt is enabled.

Tracked-On: #4325

Signed-off-by: Victor Sun <victor.sun@intel.com>
Acked-by: Eddie Dong <eddie.dong@intel.com>

### CODE REVIEW

**Comment by wenlingz** [comment]
OK to verify

**Comment by acrnsi** [comment]
OK to verify

**Comment by wenlingz** [comment]
OK to verify

**Comment by wenlingz** [comment]
OK to verify

**Comment by wenlingz** [comment]
OK to verify

**Comment by leilu** [comment]
OK to verify

**Comment by HuiHuangShi** [comment]
18 new potential violations to the coding guideline detected. Please help check. Thanks!<br><1> config:part_config filename:/hypervisor/arch/x86/guest/vm.c func:lapic_pt_enabled_pcpu_bitmap offset:462<br> reason:Procedure contains UR data flow anomalies. : vcpu<br><2> config:sharing_config filename:/hypervisor/arch/x86/guest/vm.c func:lapic_pt_enabled_pcpu_bitmap offset:462<br> reason:Procedure contains UR data flow anomalies. : vcpu<br><3> config:part_config filename:/hypervisor/arch/x86/guest/vm.c func:offline_lapic_pt_enabled_pcpus offset:622<br> reason:Pointer param should be declared pointer to const. : vm<br><4> config:sharing_config filename:/hypervisor/arch/x86/guest/vm.c func:offline_lapic_pt_enabled_pcpus offset:622<br> reason:Pointer param should be declared pointer to const. : vm<br><5> config:part_config filename:/hypervisor/arch/x86/guest/vm.c func:offline_lapic_pt_enabled_pcpus offset:625<br> reason:Procedure contains UR data flow anomalies. : i<br><6> config:sharing_config filename:/hypervisor/arch/x86/guest/vm.c func:offline_lapic_pt_enabled_pcpus offset:625<br> reason:Procedure contains UR data flow anomalies. : i<br><7> config:sharing_config filename:/hypervisor/arch/x86/guest/vm.c func:offline_lapic_pt_enabled_pcpus offset:628<br> reason:Function return value potentially unused. : this_pcpu_id<br><8> config:part_config filename:/hypervisor/arch/x86/guest/vm.c func:offline_lapic_pt_enabled_pcpus offset:628<br> reason:Function return value potentially unused. : this_pcpu_id<br><9> config:common filename:/hypervisor/arch/x86/guest/vm.c func:offline_lapic_pt_enabled_pcpus offset:649<br> reason:Inconsistent usage of loop control variable.<br><10> config:common filename:/hypervisor/arch/x86/guest/vm.c func:offline_lapic_pt_enabled_pcpus offset:649<br> reason:For loop incrementation is not simple.<br><11> config:sharing_config filename:/hypervisor/arch/x86/guest/vm.c func:offline_lapic_pt_enabled_pcpus offset:649<br> reason:Expression has side effects. : i<br><12> config:part_config filename:/hypervisor/arch/x86/guest/vm.c func:offline_lapic_pt_enabled_pcpus offset:649<br> reason:Expression has side effects. : i<br><13> config:common filename:/hypervisor/arch/x86/guest/vm.c func:offline_lapic_pt_enabled_pcpus offset:649<br> reason:Type conversion without cast. :  (enum vm_state and enum vcpu_state): vcpu -> state != VCPU_OFFLINE<br><14> config:common filename:/hypervisor/arch/x86/guest/vm.c func:offline_lapic_pt_enabled_pcpus offset:649<br> reason:No space after semi colon in for expression.<br><15> config:common filename:/hypervisor/arch/x86/guest/vm.c func:offline_lapic_pt_enabled_pcpus offset:649<br> reason:Use of comma operator.<br><16> config:common filename:/hypervisor/arch/x86/guest/vm.c func:offline_lapic_pt_enabled_pcpus offset:649<br> reason:For loop initialisation is not simple.<br><17> config:common filename:/hypervisor/arch/x86/guest/vm.c func:offline_lapic_pt_enabled_pcpus offset:649<br> reason:No brackets to loop body.<br><18> config:common filename:/hypervisor/arch/x86/guest/vm.c func:offline_lapic_pt_enabled_pcpus offset:649<br> reason:Assignment operation in expression.<br><br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by HuiHuangShi** [comment]
16 new potential violations to the coding guideline detected. Please help check. Thanks!<br><1> config:part_config filename:/hypervisor/arch/x86/guest/vm.c func:lapic_pt_enabled_pcpu_bitmap offset:462<br> reason:Procedure contains UR data flow anomalies. : vcpu<br><2> config:sharing_config filename:/hypervisor/arch/x86/guest/vm.c func:lapic_pt_enabled_pcpu_bitmap offset:462<br> reason:Procedure contains UR data flow anomalies. : vcpu<br><3> config:part_config filename:/hypervisor/arch/x86/guest/vm.c func:offline_lapic_pt_enabled_pcpus offset:625<br> reason:Procedure contains UR data flow anomalies. : i<br><4> config:sharing_config filename:/hypervisor/arch/x86/guest/vm.c func:offline_lapic_pt_enabled_pcpus offset:625<br> reason:Procedure contains UR data flow anomalies. : i<br><5> config:sharing_config filename:/hypervisor/arch/x86/guest/vm.c func:offline_lapic_pt_enabled_pcpus offset:628<br> reason:Function return value potentially unused. : this_pcpu_id<br><6> config:part_config filename:/hypervisor/arch/x86/guest/vm.c func:offline_lapic_pt_enabled_pcpus offset:628<br> reason:Function return value potentially unused. : this_pcpu_id<br><7> config:common filename:/hypervisor/arch/x86/guest/vm.c func:offline_lapic_pt_enabled_pcpus offset:649<br> reason:Inconsistent usage of loop control variable.<br><8> config:common filename:/hypervisor/arch/x86/guest/vm.c func:offline_lapic_pt_enabled_pcpus offset:649<br> reason:For loop incrementation is not simple.<br><9> config:sharing_config filename:/hypervisor/arch/x86/guest/vm.c func:offline_lapic_pt_enabled_pcpus offset:649<br> reason:Expression has side effects. : i<br><10> config:part_config filename:/hypervisor/arch/x86/guest/vm.c func:offline_lapic_pt_enabled_pcpus offset:649<br> reason:Expression has side effects. : i<br><11> config:common filename:/hypervisor/arch/x86/guest/vm.c func:offline_lapic_pt_enabled_pcpus offset:649<br> reason:Type conversion without cast. :  (enum vm_state and enum vcpu_state): vcpu -> state != VCPU_OFFLINE<br><12> config:common filename:/hypervisor/arch/x86/guest/vm.c func:offline_lapic_pt_enabled_pcpus offset:649<br> reason:No space after semi colon in for expression.<br><13> config:common filename:/hypervisor/arch/x86/guest/vm.c func:offline_lapic_pt_enabled_pcpus offset:649<br> reason:Use of comma operator.<br><14> config:common filename:/hypervisor/arch/x86/guest/vm.c func:offline_lapic_pt_enabled_pcpus offset:649<br> reason:For loop initialisation is not simple.<br><15> config:common filename:/hypervisor/arch/x86/guest/vm.c func:offline_lapic_pt_enabled_pcpus offset:649<br> reason:No brackets to loop body.<br><16> config:common filename:/hypervisor/arch/x86/guest/vm.c func:offline_lapic_pt_enabled_pcpus offset:649<br> reason:Assignment operation in expression.<br><br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by wenlingz** [comment]
@jsun26intel please check the MISRA -C check, thanks

**Pull request merged**
