### PR TITLE
Makefile: fix build issue when RELEASE=1

### PR DESCRIPTION
**Pull request by gvancuts**
Fix a build issue when using RELEASE=1. This was introduced
by mistake in a previous commit and this one partially reverts
the change and also addresses another issue that had not been
noticed before.

Signed-off-by: Geoffroy Van Cutsem <geoffroy.vancutsem@intel.com>

### CODE REVIEW

**Comment by gvancuts** [comment]
This partially reverts a change introduced in #30 and also addresses a pre-existing issue. With this PR, all combination of `RELEASE` and `PLATFORM` can be successfully compiled. I have not tested those on real hardware though.

| `RELEASE` | `PLATFORM` | Result |
| :-: | :-: | :-: |
| 0 | 0 | OK |
| 0 | 1 | OK |
| 1 | 0 | OK |
| 1 | 1 | OK |

**Comment by dbkinder** [comment]
The commit message should say what the issue actually is that’s being fixed.

**Comment by gvancuts** [comment]
Force-pushed with an updated commit.

**Comment by anthonyzxu** [comment]
@gvancuts 

all c files under debug should be in D_SRC,
please check my comment in 
https://github.com/projectacrn/acrn-hypervisor/pull/30#issuecomment-374797288

**Comment by JasonChenCJ** [comment]
we should only leave printf.c built for release version, and do not build in any others, Please check the SOS kernel cmdline, and make sure under release version, what's the real HW device ttyS0 point to, if this will conflict with others,  the simple way is remove "pci_devices_ignore=(0:18:2)" and "console=ttyS0" from cmdline.

**Comment by gvancuts** [comment]
Got it @anthonyzxu 

It looks like this PR would be superceded by #45 , is that correct? If true, I'll simply close this one.

**Comment by anthonyzxu** [comment]
That's correct, please close this one.
And thank you for bringing this issue up!

**Pull request closed without merging**
