### PR TITLE
script: remove DP-x:d parameters for UP2 board

### PR DESCRIPTION
**Pull request by minhe1**
There's a DP port on UP2 board, so we cannot add video=DP-x:d paramter,
otherwise, DP monitors will not be able to be detected on UP2 boards.

Tracked-On: #2268
Signed-off-by: Min He <min.he@intel.com>
Reviewed-by: Binbin Wu <binbin.wu@intel.com>

### CODE REVIEW

**Comment by HuiHuangShi** [comment]
2269 <br>The PR does not touch any hypervisor source file. Skip coding guideline checks.<br>

**Comment by HuiHuangShi** [comment]
2269 <br>The PR does not touch any hypervisor source file. Skip coding guideline checks.<br>

**Comment by acrnsi** [comment]
Ok to verify

**Comment by HuiHuangShi** [comment]
2269 <br>The PR does not touch any hypervisor source file. Skip coding guideline checks.<br>

**Pull request merged**
