### PR TITLE
HV: enable lapic passthru for logical partition VM1

### PR DESCRIPTION
**Pull request by jsun26intel**
Tracked-On: #2291

Signed-off-by: Victor Sun <victor.sun@intel.com>

### CODE REVIEW

**Comment by HuiHuangShi** [comment]
No new violations to the coding guideline detected.<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by sainath14** [comment]
@jsun26intel noticed that lapic passthrough is not happening because guest kernel is using xAPIC even though ACRN exposes x2APIC.

**Comment by jsun26intel** [comment]
@yakuizhao The build is failed because of the missing of "CONFIG_PARAVIRT=y" and "CONFIG_ACRN=y" in uos config.

**Comment by acrnsi** [comment]
Ok to verify

**Comment by HuiHuangShi** [comment]
No new violations to the coding guideline detected.<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Pull request merged**
