### PR TITLE
acrn-config: add support to parse 'severity' item tag

### PR DESCRIPTION
**Pull request by liuwei987**
- vm: add severity for vm_config
- reset: detect highest severity guest dynamically
- pm: S5: update the system shutdown logical in ACRN
- add support to parse 'severity' item tag
- add severity setting to scenario config xml

    Tracked-On: #3854
    Signed-off-by: Yin Fengwei <fengwei.yin@intel.com>
    Signed-off-by: Wei Liu <weix.w.liu@intel.com>
    Acked-by: Victor Sun <victor.sun@intel.com>

### CODE REVIEW

**Comment by HuiHuangShi** [comment]
No new violations to the coding guideline detected.<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by liuwei987** [comment]
Add PR 4271 patches into this PR.
As acrn-config will generate some MACROs in vm_configurations.c and these they are defined in PR 4271, CI per-merge system now only support validate one PR, it would be failed the merge process for the two PR. Need put them in one PR.

**Comment by HuiHuangShi** [comment]
9 new potential violations to the coding guideline detected. Please help check. Thanks!<br><1> config:common filename:/hypervisor/arch/x86/configs/vm_config.c func:sanitize_vm_config offset:165<br> reason:Logical conjunctions need brackets.<br><2> config:part_config filename:/hypervisor/arch/x86/guest/vm.c func:get_highest_severity_vm offset:129<br> reason:Pointer not checked for null before use. : vm<br><3> config:sharing_config filename:/hypervisor/arch/x86/guest/vm.c func:get_highest_severity_vm offset:129<br> reason:Pointer not checked for null before use. : vm<br><4> config:part_config filename:/hypervisor/arch/x86/guest/vm.c func:get_highest_severity_vm offset:135<br> reason:Pointer not checked for null before use. : vm_config<br><5> config:sharing_config filename:/hypervisor/arch/x86/guest/vm.c func:get_highest_severity_vm offset:135<br> reason:Pointer not checked for null before use. : vm_config<br><6> config:sharing_config filename:/hypervisor/arch/x86/guest/vm.c func:is_ready_for_system_shutdown offset:613<br> reason:Pointer not checked for null before use. : vm<br><7> config:part_config filename:/hypervisor/arch/x86/guest/vm.c func:is_ready_for_system_shutdown offset:613<br> reason:Pointer not checked for null before use. : vm<br><8> config:sharing_config filename:/hypervisor/arch/x86/pm.c func:shutdown_system offset:161<br> reason:Pointer not checked for null before use. : sx_data<br><9> config:part_config filename:/hypervisor/arch/x86/pm.c func:shutdown_system offset:161<br> reason:Pointer not checked for null before use. : sx_data<br><br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by liuwei987** [comment]
https://github.com/projectacrn/acrn-hypervisor/pull/4271#issuecomment-567318928

**Comment by HuiHuangShi** [comment]
9 new potential violations to the coding guideline detected. Please help check. Thanks!<br><1> config:common filename:/hypervisor/arch/x86/configs/vm_config.c func:sanitize_vm_config offset:165<br> reason:Logical conjunctions need brackets.<br><2> config:part_config filename:/hypervisor/arch/x86/guest/vm.c func:get_highest_severity_vm offset:129<br> reason:Pointer not checked for null before use. : vm<br><3> config:sharing_config filename:/hypervisor/arch/x86/guest/vm.c func:get_highest_severity_vm offset:129<br> reason:Pointer not checked for null before use. : vm<br><4> config:part_config filename:/hypervisor/arch/x86/guest/vm.c func:get_highest_severity_vm offset:135<br> reason:Pointer not checked for null before use. : vm_config<br><5> config:sharing_config filename:/hypervisor/arch/x86/guest/vm.c func:get_highest_severity_vm offset:135<br> reason:Pointer not checked for null before use. : vm_config<br><6> config:sharing_config filename:/hypervisor/arch/x86/guest/vm.c func:is_ready_for_system_shutdown offset:613<br> reason:Pointer not checked for null before use. : vm<br><7> config:part_config filename:/hypervisor/arch/x86/guest/vm.c func:is_ready_for_system_shutdown offset:613<br> reason:Pointer not checked for null before use. : vm<br><8> config:sharing_config filename:/hypervisor/arch/x86/pm.c func:shutdown_system offset:161<br> reason:Pointer not checked for null before use. : sx_data<br><9> config:part_config filename:/hypervisor/arch/x86/pm.c func:shutdown_system offset:161<br> reason:Pointer not checked for null before use. : sx_data<br><br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by liuwei987** [comment]
> 9 new potential violations to the coding guideline detected. Please help check. Thanks!
> <1> config:common filename:/hypervisor/arch/x86/configs/vm_config.c func:sanitize_vm_config offset:165
> reason:Logical conjunctions need brackets.
> <2> config:part_config filename:/hypervisor/arch/x86/guest/vm.c func:get_highest_severity_vm offset:129
> reason:Pointer not checked for null before use. : vm
> <3> config:sharing_config filename:/hypervisor/arch/x86/guest/vm.c func:get_highest_severity_vm offset:129
> reason:Pointer not checked for null before use. : vm
> <4> config:part_config filename:/hypervisor/arch/x86/guest/vm.c func:get_highest_severity_vm offset:135
> reason:Pointer not checked for null before use. : vm_config
> <5> config:sharing_config filename:/hypervisor/arch/x86/guest/vm.c func:get_highest_severity_vm offset:135
> reason:Pointer not checked for null before use. : vm_config
> <6> config:sharing_config filename:/hypervisor/arch/x86/guest/vm.c func:is_ready_for_system_shutdown offset:613
> reason:Pointer not checked for null before use. : vm
> <7> config:part_config filename:/hypervisor/arch/x86/guest/vm.c func:is_ready_for_system_shutdown offset:613
> reason:Pointer not checked for null before use. : vm
> <8> config:sharing_config filename:/hypervisor/arch/x86/pm.c func:shutdown_system offset:161
> reason:Pointer not checked for null before use. : sx_data
> <9> config:part_config filename:/hypervisor/arch/x86/pm.c func:shutdown_system offset:161
> reason:Pointer not checked for null before use. : sx_data
> 
> No New Name Conflict
> 
> No New Function Declaration/Definition Mismatch

https://github.com/projectacrn/acrn-hypervisor/pull/4271#issuecomment-567318928

**Comment by HuiHuangShi** [comment]
9 new potential violations to the coding guideline detected. Please help check. Thanks!<br><1> config:common filename:/hypervisor/arch/x86/configs/vm_config.c func:sanitize_vm_config offset:176<br> reason:Logical conjunctions need brackets.<br><2> config:part_config filename:/hypervisor/arch/x86/guest/vm.c func:get_highest_severity_vm offset:129<br> reason:Pointer not checked for null before use. : vm<br><3> config:sharing_config filename:/hypervisor/arch/x86/guest/vm.c func:get_highest_severity_vm offset:129<br> reason:Pointer not checked for null before use. : vm<br><4> config:part_config filename:/hypervisor/arch/x86/guest/vm.c func:get_highest_severity_vm offset:135<br> reason:Pointer not checked for null before use. : vm_config<br><5> config:sharing_config filename:/hypervisor/arch/x86/guest/vm.c func:get_highest_severity_vm offset:135<br> reason:Pointer not checked for null before use. : vm_config<br><6> config:sharing_config filename:/hypervisor/arch/x86/guest/vm.c func:is_ready_for_system_shutdown offset:613<br> reason:Pointer not checked for null before use. : vm<br><7> config:part_config filename:/hypervisor/arch/x86/guest/vm.c func:is_ready_for_system_shutdown offset:613<br> reason:Pointer not checked for null before use. : vm<br><8> config:sharing_config filename:/hypervisor/arch/x86/pm.c func:shutdown_system offset:161<br> reason:Pointer not checked for null before use. : sx_data<br><9> config:part_config filename:/hypervisor/arch/x86/pm.c func:shutdown_system offset:161<br> reason:Pointer not checked for null before use. : sx_data<br><br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by binbinwu1** [comment]
The patch series has some same patches with PR https://github.com/projectacrn/acrn-hypervisor/pull/4271, does patch in PR 4271  replaced by this PR? @fyin1 @liuwei987

**Comment by liuwei987** [comment]
> The patch series has some same patches with PR #4271, does patch in PR 4271 replaced by this PR? @fyin1 @liuwei987
Yes, i think so. This PR will replace PR#4271.
Becasue acrn-config will generate some MACROs in vm_configurations.c and they are defined in PR #4271, CI will check them all pass when put them in one PR.

**Comment by fyin1** [comment]
Yes. This PR includes all patches from PR#4271. And also the code style violations are also covered by document for PR#4271.

**Pull request merged**
