### PR TITLE
No vioapic/pic for RT VM

### PR DESCRIPTION
**Pull request by lyan3**
These two commits remove IOAPIC & PIC related entries in ACPI table for RT VM and skipped the initialization of vIOAPIC and vPIC.

Tracked-On: #3227

### CODE REVIEW

**Comment by acrnsi** [comment]
OK to verify

**Comment by acrnsi** [comment]
OK to verify

**Comment by lyan3** [comment]
Withdraw the PR, because it caused a critical regression that RT VM not able to shut-down, need time to investigate.

**Comment by lyan3** [comment]
Reopen the PR, the RT VM poweroff failure is caused by SCI handler init failure which results in ACPI disabled in RT Linux.
So, with IOAPIC/PIC removed from ACPI table, a patch in RT Linux is needed to skip the SCI handler registration.

**Comment by HuiHuangShi** [comment]
7 new potential violations to the coding guideline detected. Please help check. Thanks!<br><1> config:common filename:/hypervisor/arch/x86/guest/vm.c func:create_vm offset:400<br> reason:Cyclomatic complexity greater than 20.<br><2> config:sharing_config filename:/hypervisor/arch/x86/guest/vm.c func:create_vm offset:501<br> reason:Potential side effect problem in expression. : vm_array.arch_vm.vioapic.mtx<br><3> config:part_config filename:/hypervisor/arch/x86/guest/vm.c func:create_vm offset:501<br> reason:Potential side effect problem in expression. : vm_array.arch_vm.vioapic.mtx<br><4> config:sharing_config filename:/hypervisor/arch/x86/guest/vm.c func:create_vm offset:501<br> reason:Potential side effect problem in expression. : vm_array.arch_vm.vioapic.ready<br><5> config:part_config filename:/hypervisor/arch/x86/guest/vm.c func:create_vm offset:501<br> reason:Potential side effect problem in expression. : vm_array.arch_vm.vioapic.ready<br><6> config:part_config filename:/hypervisor/arch/x86/guest/vm.c func:create_vm offset:501<br> reason:Potential side effect problem in expression. : vm_array.arch_vm.vioapic.vm<br><7> config:sharing_config filename:/hypervisor/arch/x86/guest/vm.c func:create_vm offset:501<br> reason:Potential side effect problem in expression. : vm_array.arch_vm.vioapic.vm<br><br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by HuiHuangShi** [comment]
8 new potential violations to the coding guideline detected. Please help check. Thanks!<br><1> config:sharing_config filename:/hypervisor/arch/x86/guest/vm.c func:register_pm_io_handler offset:396<br> reason:Pointer param should be declared pointer to const. : vm<br><2> config:part_config filename:/hypervisor/arch/x86/guest/vm.c func:register_pm_io_handler offset:396<br> reason:Pointer param should be declared pointer to const. : vm<br><3> config:part_config filename:/hypervisor/arch/x86/guest/vm.c func:create_vm offset:512<br> reason:Potential side effect problem in expression. : vm_array.arch_vm.vioapic.vm<br><4> config:sharing_config filename:/hypervisor/arch/x86/guest/vm.c func:create_vm offset:512<br> reason:Potential side effect problem in expression. : vm_array.arch_vm.vioapic.ready<br><5> config:part_config filename:/hypervisor/arch/x86/guest/vm.c func:create_vm offset:512<br> reason:Potential side effect problem in expression. : vm_array.arch_vm.vioapic.mtx<br><6> config:sharing_config filename:/hypervisor/arch/x86/guest/vm.c func:create_vm offset:512<br> reason:Potential side effect problem in expression. : vm_array.arch_vm.vioapic.mtx<br><7> config:sharing_config filename:/hypervisor/arch/x86/guest/vm.c func:create_vm offset:512<br> reason:Potential side effect problem in expression. : vm_array.arch_vm.vioapic.vm<br><8> config:part_config filename:/hypervisor/arch/x86/guest/vm.c func:create_vm offset:512<br> reason:Potential side effect problem in expression. : vm_array.arch_vm.vioapic.ready<br><br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by dongyaozu** [comment]
@lyan3 are u following up?

**Comment by lyan3** [comment]
> @lyan3 are u following up?

Yes, the suppression table sent.

**Pull request merged**
