### PR TITLE
doc: update inclusive language terms in docs

### PR DESCRIPTION
**Pull request by dbkinder**
Replace white/black master/slave terms with alternatives.  We're not
changing "master" when used in the context of GitHub branches.  GitHub
advises they have a plan to help this transition.  I did though add the
word "branch" to bare uses of "master".

Signed-off-by: David B. Kinder <david.b.kinder@intel.com>

### CODE REVIEW

**Comment by HuiHuangShi** [comment]
No new violations to the coding guideline detected.<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Review by shiqingg — APPROVED** [review]
I am fine with this change. Thanks!

**Comment by HuiHuangShi** [comment]
No new violations to the coding guideline detected.<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by gvancuts** [comment]
This looks good to me, just a question: you did change a number of occurrences of `master` into `main`, this seems contrary to what the commit message say?

**Pull request merged**
