### PR TITLE
HV: coding style change for vm_config initialization

### PR DESCRIPTION
**Pull request by jsun26intel**
Currently VM load_type/uuid/severity are initialized separately in vm_config struct,
developer need to take care all items carefully otherwise hypervisor would have trouble with the configurations.
Given the vm loader_order/uuid and severity are binded tightly, the patch introduced some VM types concept like Safety VM, SOS VM, pre-launched Standard VM, post-launched Standard VM, post-launched RT VM and these settings will merged into one macro for each VM type, then user need not care about uuid/severity settings and just need to know which VM type need to be configured in vm_config struct.
The patch set would benefit acrn-config tool implementation also that uuid management will not be hardcoded any more.

Tracked-On: #4641

Signed-off-by: Victor Sun <victor.sun@intel.com>

### CODE REVIEW

**Comment by binbinwu1** [comment]
@terryzouhao  Could you help to have a review?

**Comment by HuiHuangShi** [comment]
9 new potential violations to the coding guideline detected. Please help check. Thanks!<br><1> config:common filename:/hypervisor/include/arch/x86/vm_config.h func: offset:36<br> reason:Use of ## or # in a macro.<br><2> config:common filename:/hypervisor/include/arch/x86/vm_config.h func: offset:40<br> reason:Use of ## or # in a macro.<br><3> config:common filename:/hypervisor/include/arch/x86/vm_config.h func: offset:44<br> reason:Use of ## or # in a macro.<br><4> config:common filename:/hypervisor/include/arch/x86/vm_config.h func: offset:48<br> reason:Use of ## or # in a macro.<br><5> config:common filename:/hypervisor/include/arch/x86/vm_config.h func: offset:52<br> reason:Use of ## or # in a macro.<br><6> config:part_config filename:/hypervisor/boot/include/boot.h func: offset:44<br> reason:No real declaration for external variable. : boot_regs<br><7> config:part_config filename:/hypervisor/boot/include/boot.h func: offset:46<br> reason:No real declaration for external variable. : efiloader_sig<br><8> config:part_config filename:/hypervisor/scenarios/sdc/vm_configurations.c func: offset:12<br> reason:Variable should be declared static. : vm_configs<br><9> config:common filename:/hypervisor/scenarios/sdc/vm_configurations.c func: offset:22<br> reason:Start of variable is upper case.             : SOS_VM_BOOTARGS<br><br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by dongyaozu** [comment]
Need Terry to review the configuration file change part.

**Comment by terryzouhao** [comment]
Reviewed.  Removed UUID in config file, and added vm_uuids/h to store uuid by default. vCPU was also removed to launch script.

**Comment by HuiHuangShi** [comment]
9 new potential violations to the coding guideline detected. Please help check. Thanks!<br><1> config:common filename:/hypervisor/include/arch/x86/vm_config.h func: offset:36<br> reason:Use of ## or # in a macro.<br><2> config:common filename:/hypervisor/include/arch/x86/vm_config.h func: offset:40<br> reason:Use of ## or # in a macro.<br><3> config:common filename:/hypervisor/include/arch/x86/vm_config.h func: offset:44<br> reason:Use of ## or # in a macro.<br><4> config:common filename:/hypervisor/include/arch/x86/vm_config.h func: offset:48<br> reason:Use of ## or # in a macro.<br><5> config:common filename:/hypervisor/include/arch/x86/vm_config.h func: offset:52<br> reason:Use of ## or # in a macro.<br><6> config:part_config filename:/hypervisor/boot/include/boot.h func: offset:44<br> reason:No real declaration for external variable. : boot_regs<br><7> config:part_config filename:/hypervisor/boot/include/boot.h func: offset:46<br> reason:No real declaration for external variable. : efiloader_sig<br><8> config:part_config filename:/hypervisor/scenarios/sdc/vm_configurations.c func: offset:12<br> reason:Variable should be declared static. : vm_configs<br><9> config:common filename:/hypervisor/scenarios/sdc/vm_configurations.c func: offset:22<br> reason:Start of variable is upper case.             : SOS_VM_BOOTARGS<br><br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by wenlingz** [comment]
OK to verify

**Comment by HuiHuangShi** [comment]
9 new potential violations to the coding guideline detected. Please help check. Thanks!<br><1> config:common filename:/hypervisor/include/arch/x86/vm_config.h func: offset:36<br> reason:Use of ## or # in a macro.<br><2> config:common filename:/hypervisor/include/arch/x86/vm_config.h func: offset:40<br> reason:Use of ## or # in a macro.<br><3> config:common filename:/hypervisor/include/arch/x86/vm_config.h func: offset:44<br> reason:Use of ## or # in a macro.<br><4> config:common filename:/hypervisor/include/arch/x86/vm_config.h func: offset:48<br> reason:Use of ## or # in a macro.<br><5> config:common filename:/hypervisor/include/arch/x86/vm_config.h func: offset:52<br> reason:Use of ## or # in a macro.<br><6> config:part_config filename:/hypervisor/boot/include/boot.h func: offset:44<br> reason:No real declaration for external variable. : boot_regs<br><7> config:part_config filename:/hypervisor/boot/include/boot.h func: offset:46<br> reason:No real declaration for external variable. : efiloader_sig<br><8> config:part_config filename:/hypervisor/scenarios/sdc/vm_configurations.c func: offset:12<br> reason:Variable should be declared static. : vm_configs<br><9> config:common filename:/hypervisor/scenarios/sdc/vm_configurations.c func: offset:22<br> reason:Start of variable is upper case.             : SOS_VM_BOOTARGS<br><br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by HuiHuangShi** [comment]
9 new potential violations to the coding guideline detected. Please help check. Thanks!<br><1> config:common filename:/hypervisor/include/arch/x86/vm_config.h func: offset:36<br> reason:Use of ## or # in a macro.<br><2> config:common filename:/hypervisor/include/arch/x86/vm_config.h func: offset:40<br> reason:Use of ## or # in a macro.<br><3> config:common filename:/hypervisor/include/arch/x86/vm_config.h func: offset:44<br> reason:Use of ## or # in a macro.<br><4> config:common filename:/hypervisor/include/arch/x86/vm_config.h func: offset:48<br> reason:Use of ## or # in a macro.<br><5> config:common filename:/hypervisor/include/arch/x86/vm_config.h func: offset:52<br> reason:Use of ## or # in a macro.<br><6> config:part_config filename:/hypervisor/boot/include/boot.h func: offset:44<br> reason:No real declaration for external variable. : boot_regs<br><7> config:part_config filename:/hypervisor/boot/include/boot.h func: offset:46<br> reason:No real declaration for external variable. : efiloader_sig<br><8> config:part_config filename:/hypervisor/scenarios/sdc/vm_configurations.c func: offset:12<br> reason:Variable should be declared static. : vm_configs<br><9> config:common filename:/hypervisor/scenarios/sdc/vm_configurations.c func: offset:22<br> reason:Start of variable is upper case.             : SOS_VM_BOOTARGS<br><br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by HuiHuangShi** [comment]
8 new potential violations to the coding guideline detected. Please help check. Thanks!<br><1> config:common filename:/hypervisor/include/arch/x86/vm_config.h func: offset:36<br> reason:Use of ## or # in a macro.<br><2> config:common filename:/hypervisor/include/arch/x86/vm_config.h func: offset:40<br> reason:Use of ## or # in a macro.<br><3> config:common filename:/hypervisor/include/arch/x86/vm_config.h func: offset:44<br> reason:Use of ## or # in a macro.<br><4> config:common filename:/hypervisor/include/arch/x86/vm_config.h func: offset:48<br> reason:Use of ## or # in a macro.<br><5> config:common filename:/hypervisor/include/arch/x86/vm_config.h func: offset:52<br> reason:Use of ## or # in a macro.<br><6> config:part_config filename:/hypervisor/boot/include/boot.h func: offset:44<br> reason:No real declaration for external variable. : boot_regs<br><7> config:part_config filename:/hypervisor/boot/include/boot.h func: offset:46<br> reason:No real declaration for external variable. : efiloader_sig<br><8> config:common filename:/hypervisor/scenarios/sdc/vm_configurations.c func: offset:22<br> reason:Start of variable is upper case.             : SOS_VM_BOOTARGS<br><br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Pull request merged**
