### PR TITLE
hv: Cleanup and optimise vioapic.c

### PR DESCRIPTION
**Pull request by rarindam**
Cleaned up usage of vioapic_pincount.
Modified the pin count variables to uint32_t.
Assuming pin count never be below zero, as its
derived from higher level irq value, which
is uint32.

Signed-off-by: Arindam Roy <arindam.roy@intel.com>

### CODE REVIEW

**Comment by NanlinXie** [comment]
Can one of the admins verify this patch?

**Comment by dongyaozu** [comment]
@rarindam can you solve the check failure?

**Comment by rarindam** [comment]
It seems the NUC failed to boot with my patch.
Will have to check what went wrong.
Arindam

**Comment by lijinxia** [comment]
Please rebase your branch.

**Comment by lijinxia** [comment]
@rarindam Please rebase(NOT merge) and resolve the conflicts.

**Comment by rarindam** [comment]
Will be submitting a PR.

**Pull request closed without merging**
