### PR TITLE
Fixed minor wording and typos

### PR DESCRIPTION
**Pull request by ACAVJW4H**
Signed-off-by: Mete Öztürk <mete@stroma.dev>

### CODE REVIEW

**Comment by wenlingz** [comment]
@ACAVJW4H please help add description on your commit and add signed off in your commit, also please create one git issue for this PR, thanks

**Review by gvancuts — APPROVED** [review]

**Comment by wenlingz** [comment]
OK to verify

**Comment by wenlingz** [comment]
@NanlinXie @gvancuts we treat this PR for doc PR or code PR ?
if it's a doc PR, please ignore the label Tracked-On error, just merge it;
if it's a code PR, @ACAVJW4H please add Tracked-On info, thanks

**Comment by gvancuts** [comment]
> 
> 
> @NanlinXie @gvancuts we treat this PR for doc PR or code PR ? if it's a doc PR, please ignore the label Tracked-On error, just merge it; if it's a code PR, @ACAVJW4H please add Tracked-On info, thanks

These are strings in the code, it would be better if we could treat them as doc changes but it's probably safer to treat them as code changes.

**Comment by wenlingz** [comment]
@NanlinXie how to deal with this PR ?

**Review by NanlinXie — APPROVED** [review]

**Comment by NanlinXie** [comment]
@wenlingz , please help to merge it. Let's treat it as doc change.

**Pull request merged**
