### PR TITLE
Enable GuC/HuC firmware loading in SOS

### PR DESCRIPTION
**Pull request by rebeccasf**
Tracked-On: #1638 
Proposed-by: Charles, Daniel <daniel.charles@intel.com>
Signed-off-by: Chang Rebecca Swee Fun <rebecca.swee.fun.chang@intel.com>

### CODE REVIEW

**Comment by rebeccasf** [comment]
@NanlinXie please help to monitor this PR. I have closed the previous one, I think i have screwed up in rebasing.

**Comment by lijinxia** [comment]
@mwang106 Would you please help on the issue?

**Comment by mwang106** [comment]
@lijinxia Please help merge, I will help provide ext-id.

**Comment by ClaudZhang1995** [comment]
Ready to merge

**Pull request merged**
