### PR TITLE
 HV: add the missing brackets to loop body

### PR DESCRIPTION
**Pull request by ying2liu**
MISRA-C requires the use of brackets, even when there is only one
    statement in the loop body.

### CODE REVIEW

**Comment by NanlinXie** [comment]
Can one of the admins verify this patch?

**Comment by dongyaozu** [comment]
@ying2liu check failed, please rebase

**Comment by lijinxia** [comment]
@ying2liu Could you please rebase and fix the conflicts?
Conflicting files
hypervisor/arch/x86/cpu.c

**Comment by lijinxia** [comment]
OK to verify

**Pull request merged**
