### PR TITLE
doc: adding guide to launch 2 Linux UOSes using SDC2 scenario

### PR DESCRIPTION
**Pull request by ttzeng**
This tutorial guides the user how to set up ACRN SDC2 scenario for launching two Linux based UOSes.

Tracked-On: #3462 
Signed-off-by: Tonny Tzeng <tonny.tzeng@intel.com>

### CODE REVIEW

**Comment by acrnsi** [comment]
@ttzeng hi ,you should add Signed-off-by in your commits

**Comment by ttzeng** [comment]
> @ttzeng hi ,you should add Signed-off-by in your commits

@acrnsi thanks for pointing it out. I've added ``Signed-off-by`` and ``Tracked-On`` tags to the commit.

**Comment by ttzeng** [comment]
> SDC2 scenario can support up to three Guest VMs.
> Please add tag info which included the SDC2 scenario
> Newer than (tag: acrn-2019w29.5-140000p)
> Thanks!
@fuzhongl thanks for the comments. I've added the tag info and the UUID for the 3rd VM to the document, please take a look. Thank you.

**Comment by NanlinXie** [comment]
Thanks @ttzeng to contribute document!  One comment, now we are starting using "Service VM" instead of SOS, and “User VM” instead of UOS.

**Comment by ttzeng** [comment]
> Thanks @ttzeng to contribute document! One comment, now we are starting using "Service VM" instead of SOS, and “User VM” instead of UOS.

Thanks @NanlinXie for the correction. Good to know we are renaming ``SOS`` and ``UOS`` terms.

**Comment by dbkinder** [comment]
@NanlinXie I'm thinking we need to get the scenarios document published before we publish this document that references one of these scenarios, right?

**Comment by fuzhongl** [comment]
@ttzeng  Can we add  following info about  the 3rd Guest VM: Must be headless 
-s 2,pci-gvt -G "$3" \ # need to be comment out; because there are only three Pipes available on NUC

BTW: If you don't have eDP screen, please also set the 2nd VM to headless.

**Comment by ttzeng** [comment]
> @ttzeng Can we add following info about the 3rd Guest VM: Must be headless
> -s 2,pci-gvt -G "$3" \ # need to be comment out; because there are only three Pipes available on NUC
> 
> BTW: If you don't have eDP screen, please also set the 2nd VM to headless.

@fuzhongl Gotcha!

**Comment by ttzeng** [comment]
@fuzhongl, you are right! it's amazing, the new ``tap`` device will be added automatically by the DM, no need to add systemd-networkd conf file. I've revised the paragraphs, together with the GVT-g comment you made, PTAL. Thanks.

**Comment by fuzhongl** [comment]
@ttzeng  Please add Signed-off -by info in your commit.
Thanks!

**Comment by ttzeng** [comment]
> @ttzeng Please add Signed-off -by info in your commit.
> Thanks!

@fuzhongl I believe the ``Signed-off-by`` tag has been added since few days ago, please let me know where it was missing if any. Thanks.

**Pull request merged**
