### PR TITLE
HV: code format for memory.c

### PR DESCRIPTION
**Pull request by yonghuah**
replace blank space indent with tabs

Signed-off-by: Yonghua Huang <yonghua.huang@intel.com>

### CODE REVIEW

**Comment by NanlinXie** [comment]
Can one of the admins verify this patch?

**Comment by lijinxia** [comment]
@yonghuah Could you please rebase and fix the conflicts?
Conflicting files
hypervisor/lib/memory.c

**Comment by yonghuah** [comment]
Sure，thanks.

**Comment by yonghuah** [comment]
@lijinxia have rebased , please trigger one more check, thanks.

**Comment by lijinxia** [comment]
Verified+1

**Pull request merged**
