### PR TITLE
update `acrn-dm` parameters documentation

### PR DESCRIPTION
**Pull request by gvancuts**
Update the documentation listing and describing all `acrn-dm` parameters as it
has gone out of sync with the actual implementation. Some parameters are missing
and others are now obsolete.

Tracked-On: #4732
Signed-off-by: Geoffroy Van Cutsem <geoffroy.vancutsem@intel.com>

### CODE REVIEW

**Comment by gvancuts** [comment]
@NanlinXie can you please pull in the right technical expert to verify that the description I've put in (especially for `--windows` and `--cpu_affinity`) is correct?

/cc @ZideChen0

**Comment by HuiHuangShi** [comment]
No new violations to the coding guideline detected.<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by ZideChen0** [comment]
LGTM for the cpu_affinity part.

**Comment by wenlingz** [comment]
@gvancuts please remove "doc" on the PR title,  because this PR is about code, thanks for your understanding.

**Comment by gvancuts** [comment]
@liuwei987 @jsun26intel , is the short description regarding the `--windows` option accurate and complete?

**Comment by gvancuts** [comment]
> @gvancuts please remove "doc" on the PR title, because this PR is about code, thanks for your understanding.

I have split the single commit from this PR into two separate commits (still under this one PR). One commit is only about the doc changes and the other one is for the change in the devicemodel source code. Does that meet your need?

**Comment by HuiHuangShi** [comment]
No new violations to the coding guideline detected.<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by HuiHuangShi** [comment]
No new violations to the coding guideline detected.<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by fuzhongl** [comment]
[External_System_ID] ACRN-6309

**Comment by wenlingz** [comment]
@ywan170 please help review DM part, and help approve this PR,thanks

**Pull request merged**
