### PR TITLE
dm: uart: use mevent_add only when it is a tty

### PR DESCRIPTION
**Pull request by chejianj**
When acrn-dm is started by acrnd as a background process, STDIN is
redirected to journal. In this case mevent_add cannot be called on
the fd of STDIN.

Tracked-On: #2998
Signed-off-by: Jian Jun Chen <jian.jun.chen@intel.com>
Acked-by: Yu Wang <yu1.wang@intel.com>

### CODE REVIEW

**Comment by acrnsi** [comment]
OK to verify

**Comment by wenlingz** [comment]
@dongyaozu please help approve this PR, which is for v1.0 release, thanks

**Comment by HuiHuangShi** [comment]
No new violations to the coding guideline detected.<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by HuiHuangShi** [comment]
out of time

**Pull request merged**
