### PR TITLE
add ACRN CDP support

### PR DESCRIPTION
**Pull request by lyan3**
These commits add CDP support to ACRN and do some RDT code refinement.
CDP is an extension of CAT. It enables isolation and separate prioritization of
code and data fetches to the L2 or L3 cache in a software configurable manner,
depending on hardware support.

The patches are verified on EHL only for now, because it's the only platform with CDP capability we have.

Tracked-On: #4604

### CODE REVIEW

**Comment by wenlingz** [comment]
@lyan3 please refer build fail
arch/x86/rdt.c:30:26: error: 'platform_l3_clos_array' undeclared here (not in a function); did you mean 'platform_clos_info    '?
115    30 |   .platform_clos_array = platform_l3_clos_array,
116       |                          ^~~~~~~~~~~~~~~~~~~~~~
117       |                          platform_clos_info
118 arch/x86/rdt.c:41:26: error: 'platform_l2_clos_array' undeclared here (not in a function); did you mean 'platform_clos_info    '?
119    41 |   .platform_clos_array = platform_l2_clos_array,
120       |                          ^~~~~~~~~~~~~~~~~~~~~~
121       |                          platform_clos_info
122 arch/x86/rdt.c:51:26: error: 'platform_mba_clos_array' undeclared here (not in a function)
123    51 |   .platform_clos_array = platform_mba_clos_array,
124       |                          ^~~~~~~~~~~~~~~~~~~~~~~
125 make[1]: *** [Makefile:543: /root/workspace/acrn-hypervisor-premerge-build-image/artifact/out/hypervisor/arch/x86/rdt.o] Er    ror 1
126 make[1]: Leaving directory '/root/workspace/acrn-hypervisor-premerge-build-image/acrn-hypervisor/hypervisor'
127 make: *** [Makefile:164: hypervisor] Error 2
128 make: Leaving directory '/root/workspace/acrn-hypervisor-premerge-build-image/acrn-hypervisor'

**Comment by lyan3** [comment]
@wenling could you let me know which scenario and board for when the failure seen? 

> @lyan3 please refer build fail
> arch/x86/rdt.c:30:26: error: 'platform_l3_clos_array' undeclared here (not in a function); did you mean 'platform_clos_info '?
> 115 30 | .platform_clos_array = platform_l3_clos_array,
> 116 | ^~~~~~~~~~~~~~~~~~~~~~
> 117 | platform_clos_info
> 118 arch/x86/rdt.c:41:26: error: 'platform_l2_clos_array' undeclared here (not in a function); did you mean 'platform_clos_info '?
> 119 41 | .platform_clos_array = platform_l2_clos_array,
> 120 | ^~~~~~~~~~~~~~~~~~~~~~
> 121 | platform_clos_info
> 122 arch/x86/rdt.c:51:26: error: 'platform_mba_clos_array' undeclared here (not in a function)
> 123 51 | .platform_clos_array = platform_mba_clos_array,
> 124 | ^~~~~~~~~~~~~~~~~~~~~~~
> 125 make[1]: *** [Makefile:543: /root/workspace/acrn-hypervisor-premerge-build-image/artifact/out/hypervisor/arch/x86/rdt.o] Er ror 1
> 126 make[1]: Leaving directory '/root/workspace/acrn-hypervisor-premerge-build-image/acrn-hypervisor/hypervisor'
> 127 make: *** [Makefile:164: hypervisor] Error 2
> 128 make: Leaving directory '/root/workspace/acrn-hypervisor-premerge-build-image/acrn-hypervisor'

**Comment by wenlingz** [comment]
> @Wenling could you let me know which scenario and board for when the failure seen?
> 
> > @lyan3 please refer build fail
> > arch/x86/rdt.c:30:26: error: 'platform_l3_clos_array' undeclared here (not in a function); did you mean 'platform_clos_info '?
> > 115 30 | .platform_clos_array = platform_l3_clos_array,
> > 116 | ^~~~~~~~~~~~~~~~~~~~~~
> > 117 | platform_clos_info
> > 118 arch/x86/rdt.c:41:26: error: 'platform_l2_clos_array' undeclared here (not in a function); did you mean 'platform_clos_info '?
> > 119 41 | .platform_clos_array = platform_l2_clos_array,
> > 120 | ^~~~~~~~~~~~~~~~~~~~~~
> > 121 | platform_clos_info
> > 122 arch/x86/rdt.c:51:26: error: 'platform_mba_clos_array' undeclared here (not in a function)
> > 123 51 | .platform_clos_array = platform_mba_clos_array,
> > 124 | ^~~~~~~~~~~~~~~~~~~~~~~
> > 125 make[1]: *** [Makefile:543: /root/workspace/acrn-hypervisor-premerge-build-image/artifact/out/hypervisor/arch/x86/rdt.o] Er ror 1
> > 126 make[1]: Leaving directory '/root/workspace/acrn-hypervisor-premerge-build-image/acrn-hypervisor/hypervisor'
> > 127 make: *** [Makefile:164: hypervisor] Error 2
> > 128 make: Leaving directory '/root/workspace/acrn-hypervisor-premerge-build-image/acrn-hypervisor'

whl-ipc-i5-uefi-industry

**Comment by HuiHuangShi** [comment]
No new violations to the coding guideline detected.<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Pull request merged**
