### PR TITLE
Replace map_mem with mmu_add

### PR DESCRIPTION
**Pull request by lifeix**
Finally, we can replace all the old map/unmap/modify_mem with
new mmu_add/modify_or_del API and remove all the old code.

NOTE:
THIS PATCH MUST HOLD UNTIL THE RESPONDING REFINE IN SOS VHM HAS BE MERGED INTO CLEAR LINUX !!! Please don't merge it now.

### CODE REVIEW

**Comment by NanlinXie** [comment]
Can one of the admins verify this patch?

**Comment by lifeix** [comment]
@NanlinXie 
This patch can't be merged until  the patch "https://github.com/projectacrn/acrn-kernel/pull/48" be merged into clear linux. Thanks.

**Comment by lifeix** [comment]
@dongyaozu @anthonyzxu 
We can merge this patch now. Please help to review.
Thanks.

**Comment by lifeix** [comment]
@NanlinXie @lijinxia 
Please help to have a test
Thanks.

**Comment by lijinxia** [comment]
Verified+1

**Pull request merged**
