### PR TITLE
Tools: Makefile: correct a typo at acrn-manger-install

### PR DESCRIPTION
**Pull request by lyan3**
Signed-off-by: Yan, Like <like.yan@intel.com>

### CODE REVIEW

**Comment by NanlinXie** [comment]
Can one of the admins verify this patch?

**Comment by lyan3** [comment]
Since it's minor but urgent, I sent PR directly.

**Comment by miguelinux** [comment]
Another PR was sent before this and was sent to ML too

The PR is #376

**Comment by lyan3** [comment]
ok, thanks, I will close this PR then

**Pull request closed without merging**
