### PR TITLE
hv: x2apic support for acrn

### PR DESCRIPTION
**Pull request by sainath14**
All the platforms supported by ACRN supports x2APIC. So enabled
x2APIC for ACRN hv. Removed any code that is needed for xAPIC mode
of operation.

Tracked-On: #1455
Signed-off-by: Sainath Grandhi <sainath.grandhi@intel.com>
Reviewed-by: Eddie Dong <eddie.dong@intel.com>
Reviewed by:  Yonghua Huang <yonghua.huang@intel.com>

### CODE REVIEW

**Comment by dongyaozu** [comment]
@fyin1 can you test if it conflicts with S3 work?

**Comment by fyin1** [comment]
Sure. I will try S3 with this patch applied and let you guys know the test result.

**Comment by wenlingz** [comment]
@sainath14 please rebase  your code to fix conflicting

**Comment by sainath14** [comment]
@wenlingz  done rebasing

**Comment by sainath14** [comment]
@wenlingz done rebasing

**Comment by HuiHuangShi** [comment]
1456<br>31 new potential violations to the coding guideline detected. Please help check. Thanks!  <br><br>1.filename:/hypervisor/arch/x86/lapic.c&nbsp;&nbsp;function:save_lapic&nbsp;&nbsp;offset:176:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Implicit conversion of underlying type (MR). :  (unsigned int and unsigned long): msr_read<br><br>2.filename:/hypervisor/arch/x86/lapic.c&nbsp;&nbsp;function:save_lapic&nbsp;&nbsp;offset:176:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Narrower int conversion without cast. :  (unsigned int and unsigned long): msr_read<br><br>3.filename:/hypervisor/arch/x86/lapic.c&nbsp;&nbsp;function:save_lapic&nbsp;&nbsp;offset:177:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Implicit conversion of underlying type (MR). :  (unsigned int and unsigned long): msr_read<br><br>4.filename:/hypervisor/arch/x86/lapic.c&nbsp;&nbsp;function:save_lapic&nbsp;&nbsp;offset:177:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Narrower int conversion without cast. :  (unsigned int and unsigned long): msr_read<br><br>5.filename:/hypervisor/arch/x86/lapic.c&nbsp;&nbsp;function:save_lapic&nbsp;&nbsp;offset:178:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Narrower int conversion without cast. :  (unsigned int and unsigned long): msr_read<br><br>6.filename:/hypervisor/arch/x86/lapic.c&nbsp;&nbsp;function:save_lapic&nbsp;&nbsp;offset:178:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Implicit conversion of underlying type (MR). :  (unsigned int and unsigned long): msr_read<br><br>7.filename:/hypervisor/arch/x86/lapic.c&nbsp;&nbsp;function:save_lapic&nbsp;&nbsp;offset:179:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Implicit conversion of underlying type (MR). :  (unsigned int and unsigned long): msr_read<br><br>8.filename:/hypervisor/arch/x86/lapic.c&nbsp;&nbsp;function:save_lapic&nbsp;&nbsp;offset:179:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Narrower int conversion without cast. :  (unsigned int and unsigned long): msr_read<br><br>9.filename:/hypervisor/arch/x86/lapic.c&nbsp;&nbsp;function:save_lapic&nbsp;&nbsp;offset:180:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Implicit conversion of underlying type (MR). :  (unsigned int and unsigned long): msr_read<br><br>10.filename:/hypervisor/arch/x86/lapic.c&nbsp;&nbsp;function:save_lapic&nbsp;&nbsp;offset:180:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Narrower int conversion without cast. :  (unsigned int and unsigned long): msr_read<br><br>11.filename:/hypervisor/arch/x86/lapic.c&nbsp;&nbsp;function:save_lapic&nbsp;&nbsp;offset:181:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Narrower int conversion without cast. :  (unsigned int and unsigned long): msr_read<br><br>12.filename:/hypervisor/arch/x86/lapic.c&nbsp;&nbsp;function:save_lapic&nbsp;&nbsp;offset:181:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Implicit conversion of underlying type (MR). :  (unsigned int and unsigned long): msr_read<br><br>13.filename:/hypervisor/arch/x86/lapic.c&nbsp;&nbsp;function:save_lapic&nbsp;&nbsp;offset:182:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Implicit conversion of underlying type (MR). :  (unsigned int and unsigned long): msr_read<br><br>14.filename:/hypervisor/arch/x86/lapic.c&nbsp;&nbsp;function:save_lapic&nbsp;&nbsp;offset:182:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Narrower int conversion without cast. :  (unsigned int and unsigned long): msr_read<br><br>15.filename:/hypervisor/arch/x86/lapic.c&nbsp;&nbsp;function:save_lapic&nbsp;&nbsp;offset:183:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Implicit conversion of underlying type (MR). :  (unsigned int and unsigned long): msr_read<br><br>16.filename:/hypervisor/arch/x86/lapic.c&nbsp;&nbsp;function:save_lapic&nbsp;&nbsp;offset:183:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Narrower int conversion without cast. :  (unsigned int and unsigned long): msr_read<br><br>17.filename:/hypervisor/arch/x86/lapic.c&nbsp;&nbsp;function:save_lapic&nbsp;&nbsp;offset:184:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Implicit conversion of underlying type (MR). :  (unsigned int and unsigned long): msr_read<br><br>18.filename:/hypervisor/arch/x86/lapic.c&nbsp;&nbsp;function:save_lapic&nbsp;&nbsp;offset:184:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Narrower int conversion without cast. :  (unsigned int and unsigned long): msr_read<br><br>19.filename:/hypervisor/arch/x86/lapic.c&nbsp;&nbsp;function:save_lapic&nbsp;&nbsp;offset:185:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Narrower int conversion without cast. :  (unsigned int and unsigned long): msr_read<br><br>20.filename:/hypervisor/arch/x86/lapic.c&nbsp;&nbsp;function:save_lapic&nbsp;&nbsp;offset:185:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Implicit conversion of underlying type (MR). :  (unsigned int and unsigned long): msr_read<br><br>21.filename:/hypervisor/arch/x86/lapic.c&nbsp;&nbsp;function:save_lapic&nbsp;&nbsp;offset:186:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Narrower int conversion without cast. :  (unsigned int and unsigned long): msr_read<br><br>22.filename:/hypervisor/arch/x86/lapic.c&nbsp;&nbsp;function:save_lapic&nbsp;&nbsp;offset:186:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Implicit conversion of underlying type (MR). :  (unsigned int and unsigned long): msr_read<br><br>23.filename:/hypervisor/arch/x86/lapic.c&nbsp;&nbsp;function:save_lapic&nbsp;&nbsp;offset:188:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Narrower int conversion without cast. :  (unsigned int and unsigned long): msr_read<br><br>24.filename:/hypervisor/arch/x86/lapic.c&nbsp;&nbsp;function:save_lapic&nbsp;&nbsp;offset:188:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Implicit conversion of underlying type (MR). :  (unsigned int and unsigned long): msr_read<br><br>25.filename:/hypervisor/arch/x86/lapic.c&nbsp;&nbsp;function:save_lapic&nbsp;&nbsp;offset:190:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Implicit conversion of underlying type (MR). :  (unsigned int and unsigned long): msr_read<br><br>26.filename:/hypervisor/arch/x86/lapic.c&nbsp;&nbsp;function:save_lapic&nbsp;&nbsp;offset:190:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Narrower int conversion without cast. :  (unsigned int and unsigned long): msr_read<br><br>27.filename:/hypervisor/arch/x86/lapic.c&nbsp;&nbsp;function:save_lapic&nbsp;&nbsp;offset:192:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Implicit conversion of underlying type (MR). :  (unsigned int and unsigned long): msr_read<br><br>28.filename:/hypervisor/arch/x86/lapic.c&nbsp;&nbsp;function:save_lapic&nbsp;&nbsp;offset:192:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Narrower int conversion without cast. :  (unsigned int and unsigned long): msr_read<br><br>29.filename:/hypervisor/arch/x86/lapic.c&nbsp;&nbsp;function:save_lapic&nbsp;&nbsp;offset:194:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Narrower int conversion without cast. :  (unsigned int and unsigned long): msr_read<br><br>30.filename:/hypervisor/arch/x86/lapic.c&nbsp;&nbsp;function:save_lapic&nbsp;&nbsp;offset:194:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Implicit conversion of underlying type (MR). :  (unsigned int and unsigned long): msr_read<br><br>31.filename:/hypervisor/arch/x86/lapic.c&nbsp;&nbsp;function:save_lapic&nbsp;&nbsp;offset:195:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Implicit conversion of underlying type (MR). :  (unsigned int and unsigned long): msr_read<br><br><br>.... and more

**Comment by HuiHuangShi** [comment]
1456<br>No new violations to the coding guideline detected.

**Comment by dongyaozu** [comment]
What is the left issue? @wenlingz @sainath14

**Comment by sainath14** [comment]
There shouldn't be any issue. It can be merged.

**Comment by ClaudZhang1995** [comment]
Ready to merge

**Pull request merged**
