### PR TITLE
HV : Add apl-up2_uefi config

### PR DESCRIPTION
**Pull request by ranenikhil19**
Fix proper rootfs partition in sos cmdline
Include ve820 for prelaunched VM in hybrid mode

Tracked-On:#3545
Tracked-On:#3546
Signed-off-by: nrane <nikhil.rane@intel.com>

### CODE REVIEW

**Comment by ranenikhil19** [comment]
@jsun26intel  : Adhering to your review comments below , this patch has been made and verified in multios.

Hi Nikhil,
Usually the bios info(especially ACPI) of UEFI firmware is quite different with SBL on UP2 board, so actually we treat UP2 UEFI and UP2 SBL as different board configs. We'd better not to add MACRO in one board config to distinguish these two boards, this would make interface complex when all board configs would be auto-generated by offline tools in future.
Currently we only support UP2 SBL officially. If UP2 UEFI is also in our official support list, I prefer to add a "apl-up2_uefi" folder to store its configurations.
BR,
Victor

**Comment by HuiHuangShi** [comment]
No new violations to the coding guideline detected.<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by dongyaozu** [comment]
This is too big patches... @jsun26intel  should we rely on offline tool for this？

**Comment by HuiHuangShi** [comment]
No new violations to the coding guideline detected.<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by jsun26intel** [comment]
Offline tool for scenario based configuration will not be ready until R1.3(end of Sep). If the validation work is not urgent on up2 uefi variant, I also suggest not to merge this patch.

@ranenikhil19 , all these configuration code could be auto-generated by offline tool in future, do you still think it is urgent for now to get up2 uefi configurations merged?

**Comment by ranenikhil19** [comment]
@jsun26intel : Our next release cycle date which has UP2 as target board would be around sept end itself. So we would have to start validation from Aug end itself. 

So we need apl-up2_uefi config changes and maybe cannot wait till sept end.

**Comment by gvancuts** [comment]
> Currently we only support UP2 SBL officially.

First time I hear that, has there been some change made recently that I accidentally missed?

> If UP2 UEFI is also in our official support list, I prefer to add a "apl-up2_uefi" folder to store its configurations.

I agree.

**Comment by jsun26intel** [comment]
hi Geoffroy,
We decide to share one configuration for both sbl and uefi variant for now, current configuration could support basic feature for both, so we close the ticket.
In future, user could upload detailed board info file by our acrn-config tool, and corresponding configuration could be override by the tool, then all features could be supported by the new configuration.
BR,
Victor

**Comment by gvancuts** [comment]
Thanks for the clarification @jsun26intel

**Pull request closed without merging**
