### PR TITLE
Schedule noop preparation 

### PR DESCRIPTION
**Pull request by shuox**
hv: sched: move pcpu_id from acrn_vcpu to thread_object
  hv: sched: use get_running_vcpu to replace per_cpu vcpu with cpu
    sharing
  hv: sched: support vcpu context switch on one pcpu
  hv: sched: move schedule initialization to each pcpu init
  hv: sched: add status for thread_object
  hv: sched: add sleep/wake for thread object

### CODE REVIEW

**Comment by acrnsi** [comment]
OK to verify

**Comment by HuiHuangShi** [comment]
40 new potential violations to the coding guideline detected. Please help check. Thanks!<br><1> config:sharing_config filename:/hypervisor/common/schedule.c func:is_idle_thread offset:16<br> reason:Pointer param should be declared pointer to const. : obj<br><2> config:part_config filename:/hypervisor/common/schedule.c func:is_idle_thread offset:16<br> reason:Pointer param should be declared pointer to const. : obj<br><3> config:sharing_config filename:/hypervisor/common/schedule.c func:is_blocked offset:22<br> reason:Pointer param should be declared pointer to const. : obj<br><4> config:part_config filename:/hypervisor/common/schedule.c func:is_blocked offset:22<br> reason:Pointer param should be declared pointer to const. : obj<br><5> config:sharing_config filename:/hypervisor/common/schedule.c func:is_runnable offset:27<br> reason:Pointer param should be declared pointer to const. : obj<br><6> config:part_config filename:/hypervisor/common/schedule.c func:is_runnable offset:27<br> reason:Pointer param should be declared pointer to const. : obj<br><7> config:common filename:/hypervisor/common/schedule.c func:is_runnable offset:27<br> reason:Static procedure is not explicitly called in code analysed. : is_runnable<br><8> config:sharing_config filename:/hypervisor/common/schedule.c func:is_runnable offset:27<br> reason:Procedure is not called or referenced in code analysed. : is_runnable<br><9> config:part_config filename:/hypervisor/common/schedule.c func:is_runnable offset:27<br> reason:Procedure is not called or referenced in code analysed. : is_runnable<br><10> config:part_config filename:/hypervisor/common/schedule.c func:is_running offset:32<br> reason:Pointer param should be declared pointer to const. : obj<br><11> config:sharing_config filename:/hypervisor/common/schedule.c func:is_running offset:32<br> reason:Pointer param should be declared pointer to const. : obj<br><12> config:common filename:/hypervisor/common/schedule.c func:set_thread_status offset:39<br> reason:Type conversion without cast. :  (enum thread_object_state and unsigned short): obj -> status = status<br><13> config:sharing_config filename:/hypervisor/common/schedule.c func:schedule offset:155<br> reason:Pointer not checked for null before use. : next<br><14> config:part_config filename:/hypervisor/common/schedule.c func:schedule offset:155<br> reason:Pointer not checked for null before use. : next<br><15> config:part_config filename:/hypervisor/common/schedule.c func:schedule offset:155<br> reason:Pointer assigned to NULL may be dereferenced. : next<br><16> config:sharing_config filename:/hypervisor/common/schedule.c func:schedule offset:155<br> reason:Pointer assigned to NULL may be dereferenced. : next<br><17> config:common filename:/hypervisor/arch/x86/guest/vcpu.c func:get_running_vcpu offset:201<br> reason:Expression is not Boolean.<br><18> config:common filename:/hypervisor/arch/x86/guest/vcpu.c func:get_running_vcpu offset:201<br> reason:Logical conjunctions need brackets.<br><19> config:common filename:/hypervisor/arch/x86/guest/vcpu.c func:get_running_vcpu offset:202<br> reason:Cast to an unrelated type. : (char* to struct acrn_vcpu*): ( struct acrn_vcpu * ) ( ( char * ) ( curr ) - ( uint64_t ) ( & ( ( struct acrn_vcpu * ) 0 ) -> thread_obj ) )<br><20> config:common filename:/hypervisor/arch/x86/guest/vcpu.c func:get_running_vcpu offset:202<br> reason:Casting operation to a pointer. : (char* to struct acrn_vcpu*): ( struct acrn_vcpu * ) ( ( char * ) ( curr ) - ( uint64_t ) ( & ( ( struct acrn_vcpu * ) 0 ) -> thread_obj ) )<br><21> config:common filename:/hypervisor/arch/x86/guest/vcpu.c func:get_running_vcpu offset:202<br> reason:Cast from pointer to integral type. : (struct thread_object* to unsigned long): ( uint64_t ) ( & ( ( struct acrn_vcpu * ) 0 ) -> thread_obj )<br><22> config:common filename:/hypervisor/arch/x86/guest/vcpu.c func:get_running_vcpu offset:202<br> reason:Casting operation on a pointer. : (char* to struct acrn_vcpu*): ( struct acrn_vcpu * ) ( ( char * ) ( curr ) - ( uint64_t ) ( & ( ( struct acrn_vcpu * ) 0 ) -> thread_obj ) )<br><23> config:part_config filename:/hypervisor/arch/x86/guest/vcpu.c func:context_switch_out offset:708<br> reason:Function return value potentially unused. : (ectx)->ia32_star<br><24> config:sharing_config filename:/hypervisor/arch/x86/guest/vcpu.c func:context_switch_out offset:708<br> reason:Function return value potentially unused. : (ectx)->ia32_star<br><25> config:sharing_config filename:/hypervisor/arch/x86/guest/vcpu.c func:context_switch_out offset:709<br> reason:Function return value potentially unused. : (ectx)->ia32_lstar<br><26> config:part_config filename:/hypervisor/arch/x86/guest/vcpu.c func:context_switch_out offset:709<br> reason:Function return value potentially unused. : (ectx)->ia32_lstar<br><27> config:part_config filename:/hypervisor/arch/x86/guest/vcpu.c func:context_switch_out offset:710<br> reason:Function return value potentially unused. : (ectx)->ia32_fmask<br><28> config:sharing_config filename:/hypervisor/arch/x86/guest/vcpu.c func:context_switch_out offset:710<br> reason:Function return value potentially unused. : (ectx)->ia32_fmask<br><29> config:sharing_config filename:/hypervisor/arch/x86/guest/vcpu.c func:context_switch_out offset:711<br> reason:Function return value potentially unused. : (ectx)->ia32_kernel_gs_base<br><30> config:part_config filename:/hypervisor/arch/x86/guest/vcpu.c func:context_switch_out offset:711<br> reason:Function return value potentially unused. : (ectx)->ia32_kernel_gs_base<br><31> config:part_config filename:/hypervisor/arch/x86/guest/vcpu.c func:prepare_vcpu offset:760<br> reason:Function return value potentially unused. : (vcpu)->thread_obj.notify_mode<br><32> config:sharing_config filename:/hypervisor/arch/x86/guest/vcpu.c func:prepare_vcpu offset:760<br> reason:Function return value potentially unused. : (vcpu)->thread_obj.notify_mode<br><33> config:common filename:/hypervisor/include/arch/x86/guest/vcpu.h func:save_fxstore_guest_area offset:541<br> reason:Static procedure is not explicitly called in code analysed. : save_fxstore_guest_area<br><34> config:common filename:/hypervisor/include/arch/x86/guest/vcpu.h func:rstor_fxstore_guest_area offset:547<br> reason:Static procedure is not explicitly called in code analysed. : rstor_fxstore_guest_area<br>.....<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by HuiHuangShi** [comment]
27 new potential violations to the coding guideline detected. Please help check. Thanks!<br><1> config:common filename:/hypervisor/common/schedule.c func:is_runnable offset:27<br> reason:Static procedure is not explicitly called in code analysed. : is_runnable<br><2> config:sharing_config filename:/hypervisor/common/schedule.c func:is_runnable offset:27<br> reason:Procedure is not called or referenced in code analysed. : is_runnable<br><3> config:part_config filename:/hypervisor/common/schedule.c func:is_runnable offset:27<br> reason:Procedure is not called or referenced in code analysed. : is_runnable<br><4> config:sharing_config filename:/hypervisor/common/schedule.c func:schedule offset:155<br> reason:Pointer not checked for null before use. : next<br><5> config:part_config filename:/hypervisor/common/schedule.c func:schedule offset:155<br> reason:Pointer not checked for null before use. : next<br><6> config:part_config filename:/hypervisor/common/schedule.c func:schedule offset:155<br> reason:Pointer assigned to NULL may be dereferenced. : next<br><7> config:sharing_config filename:/hypervisor/common/schedule.c func:schedule offset:155<br> reason:Pointer assigned to NULL may be dereferenced. : next<br><8> config:common filename:/hypervisor/arch/x86/guest/vcpu.c func:get_running_vcpu offset:202<br> reason:Cast to an unrelated type. : (char* to struct acrn_vcpu*): ( struct acrn_vcpu * ) ( ( char * ) ( curr ) - ( uint64_t ) ( & ( ( struct acrn_vcpu * ) 0 ) -> thread_obj ) )<br><9> config:common filename:/hypervisor/arch/x86/guest/vcpu.c func:get_running_vcpu offset:202<br> reason:Casting operation to a pointer. : (char* to struct acrn_vcpu*): ( struct acrn_vcpu * ) ( ( char * ) ( curr ) - ( uint64_t ) ( & ( ( struct acrn_vcpu * ) 0 ) -> thread_obj ) )<br><10> config:common filename:/hypervisor/arch/x86/guest/vcpu.c func:get_running_vcpu offset:202<br> reason:Cast from pointer to integral type. : (struct thread_object* to unsigned long): ( uint64_t ) ( & ( ( struct acrn_vcpu * ) 0 ) -> thread_obj )<br><11> config:common filename:/hypervisor/arch/x86/guest/vcpu.c func:get_running_vcpu offset:202<br> reason:Casting operation on a pointer. : (char* to struct acrn_vcpu*): ( struct acrn_vcpu * ) ( ( char * ) ( curr ) - ( uint64_t ) ( & ( ( struct acrn_vcpu * ) 0 ) -> thread_obj ) )<br><12> config:part_config filename:/hypervisor/arch/x86/guest/vcpu.c func:context_switch_out offset:708<br> reason:Function return value potentially unused. : (ectx)->ia32_star<br><13> config:sharing_config filename:/hypervisor/arch/x86/guest/vcpu.c func:context_switch_out offset:708<br> reason:Function return value potentially unused. : (ectx)->ia32_star<br><14> config:sharing_config filename:/hypervisor/arch/x86/guest/vcpu.c func:context_switch_out offset:709<br> reason:Function return value potentially unused. : (ectx)->ia32_lstar<br><15> config:part_config filename:/hypervisor/arch/x86/guest/vcpu.c func:context_switch_out offset:709<br> reason:Function return value potentially unused. : (ectx)->ia32_lstar<br><16> config:part_config filename:/hypervisor/arch/x86/guest/vcpu.c func:context_switch_out offset:710<br> reason:Function return value potentially unused. : (ectx)->ia32_fmask<br><17> config:sharing_config filename:/hypervisor/arch/x86/guest/vcpu.c func:context_switch_out offset:710<br> reason:Function return value potentially unused. : (ectx)->ia32_fmask<br><18> config:part_config filename:/hypervisor/arch/x86/guest/vcpu.c func:context_switch_out offset:711<br> reason:Function return value potentially unused. : (ectx)->ia32_kernel_gs_base<br><19> config:sharing_config filename:/hypervisor/arch/x86/guest/vcpu.c func:context_switch_out offset:711<br> reason:Function return value potentially unused. : (ectx)->ia32_kernel_gs_base<br><20> config:part_config filename:/hypervisor/arch/x86/guest/vcpu.c func:prepare_vcpu offset:760<br> reason:Function return value potentially unused. : (vcpu)->thread_obj.notify_mode<br><21> config:sharing_config filename:/hypervisor/arch/x86/guest/vcpu.c func:prepare_vcpu offset:760<br> reason:Function return value potentially unused. : (vcpu)->thread_obj.notify_mode<br><22> config:common filename:/hypervisor/include/arch/x86/guest/vcpu.h func:save_fxstore_guest_area offset:541<br> reason:Static procedure is not explicitly called in code analysed. : save_fxstore_guest_area<br><23> config:common filename:/hypervisor/include/arch/x86/guest/vcpu.h func:rstor_fxstore_guest_area offset:547<br> reason:Static procedure is not explicitly called in code analysed. : rstor_fxstore_guest_area<br><24> config:common filename:/hypervisor/debug/profiling.c func:profiling_vm_list_info offset:888<br> reason:Use of mixed mode arithmetic. :  (short and unsigned short): vm_info_list.vm_list [ vm_idx ].cpu_map [ i ].vcpu_id = vcpu -> vcpu_id<br><25> config:part_config filename:/hypervisor/debug/profiling.c func:profiling_vm_list_info offset:890<br> reason:Function return value potentially unused. : vm_info_list.vm_list.cpu_map.pcpu_id<br><26> config:sharing_config filename:/hypervisor/debug/profiling.c func:profiling_vm_list_info offset:890<br> reason:Function return value potentially unused. : vm_info_list.vm_list.cpu_map.pcpu_id<br><27> config:common filename:/hypervisor/debug/profiling.c func:profiling_vm_list_info offset:890<br> reason:Signed/unsigned conversion without cast. :  (short and unsigned short): vm_info_list.vm_list [ vm_idx ].cpu_map [ i ].pcpu_id = pcpuid_from_vcpu<br><br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by leilu** [comment]
OK to verify

**Comment by leilu** [comment]
OK to verify

**Comment by HuiHuangShi** [comment]
27 new potential violations to the coding guideline detected. Please help check. Thanks!<br><1> config:common filename:/hypervisor/common/schedule.c func:is_runnable offset:27<br> reason:Static procedure is not explicitly called in code analysed. : is_runnable<br><2> config:sharing_config filename:/hypervisor/common/schedule.c func:is_runnable offset:27<br> reason:Procedure is not called or referenced in code analysed. : is_runnable<br><3> config:part_config filename:/hypervisor/common/schedule.c func:is_runnable offset:27<br> reason:Procedure is not called or referenced in code analysed. : is_runnable<br><4> config:sharing_config filename:/hypervisor/common/schedule.c func:schedule offset:155<br> reason:Pointer not checked for null before use. : next<br><5> config:part_config filename:/hypervisor/common/schedule.c func:schedule offset:155<br> reason:Pointer not checked for null before use. : next<br><6> config:part_config filename:/hypervisor/common/schedule.c func:schedule offset:155<br> reason:Pointer assigned to NULL may be dereferenced. : next<br><7> config:sharing_config filename:/hypervisor/common/schedule.c func:schedule offset:155<br> reason:Pointer assigned to NULL may be dereferenced. : next<br><8> config:common filename:/hypervisor/arch/x86/guest/vcpu.c func:get_running_vcpu offset:202<br> reason:Cast to an unrelated type. : (char* to struct acrn_vcpu*): ( struct acrn_vcpu * ) ( ( char * ) ( curr ) - ( uint64_t ) ( & ( ( struct acrn_vcpu * ) 0 ) -> thread_obj ) )<br><9> config:common filename:/hypervisor/arch/x86/guest/vcpu.c func:get_running_vcpu offset:202<br> reason:Casting operation to a pointer. : (char* to struct acrn_vcpu*): ( struct acrn_vcpu * ) ( ( char * ) ( curr ) - ( uint64_t ) ( & ( ( struct acrn_vcpu * ) 0 ) -> thread_obj ) )<br><10> config:common filename:/hypervisor/arch/x86/guest/vcpu.c func:get_running_vcpu offset:202<br> reason:Cast from pointer to integral type. : (struct thread_object* to unsigned long): ( uint64_t ) ( & ( ( struct acrn_vcpu * ) 0 ) -> thread_obj )<br><11> config:common filename:/hypervisor/arch/x86/guest/vcpu.c func:get_running_vcpu offset:202<br> reason:Casting operation on a pointer. : (char* to struct acrn_vcpu*): ( struct acrn_vcpu * ) ( ( char * ) ( curr ) - ( uint64_t ) ( & ( ( struct acrn_vcpu * ) 0 ) -> thread_obj ) )<br><12> config:part_config filename:/hypervisor/arch/x86/guest/vcpu.c func:context_switch_out offset:708<br> reason:Function return value potentially unused. : (ectx)->ia32_star<br><13> config:sharing_config filename:/hypervisor/arch/x86/guest/vcpu.c func:context_switch_out offset:708<br> reason:Function return value potentially unused. : (ectx)->ia32_star<br><14> config:sharing_config filename:/hypervisor/arch/x86/guest/vcpu.c func:context_switch_out offset:709<br> reason:Function return value potentially unused. : (ectx)->ia32_lstar<br><15> config:part_config filename:/hypervisor/arch/x86/guest/vcpu.c func:context_switch_out offset:709<br> reason:Function return value potentially unused. : (ectx)->ia32_lstar<br><16> config:part_config filename:/hypervisor/arch/x86/guest/vcpu.c func:context_switch_out offset:710<br> reason:Function return value potentially unused. : (ectx)->ia32_fmask<br><17> config:sharing_config filename:/hypervisor/arch/x86/guest/vcpu.c func:context_switch_out offset:710<br> reason:Function return value potentially unused. : (ectx)->ia32_fmask<br><18> config:sharing_config filename:/hypervisor/arch/x86/guest/vcpu.c func:context_switch_out offset:711<br> reason:Function return value potentially unused. : (ectx)->ia32_kernel_gs_base<br><19> config:part_config filename:/hypervisor/arch/x86/guest/vcpu.c func:context_switch_out offset:711<br> reason:Function return value potentially unused. : (ectx)->ia32_kernel_gs_base<br><20> config:part_config filename:/hypervisor/arch/x86/guest/vcpu.c func:prepare_vcpu offset:760<br> reason:Function return value potentially unused. : (vcpu)->thread_obj.notify_mode<br><21> config:sharing_config filename:/hypervisor/arch/x86/guest/vcpu.c func:prepare_vcpu offset:760<br> reason:Function return value potentially unused. : (vcpu)->thread_obj.notify_mode<br><22> config:common filename:/hypervisor/include/arch/x86/guest/vcpu.h func:save_fxstore_guest_area offset:541<br> reason:Static procedure is not explicitly called in code analysed. : save_fxstore_guest_area<br><23> config:common filename:/hypervisor/include/arch/x86/guest/vcpu.h func:rstor_fxstore_guest_area offset:547<br> reason:Static procedure is not explicitly called in code analysed. : rstor_fxstore_guest_area<br><24> config:common filename:/hypervisor/debug/profiling.c func:profiling_vm_list_info offset:888<br> reason:Use of mixed mode arithmetic. :  (short and unsigned short): vm_info_list.vm_list [ vm_idx ].cpu_map [ i ].vcpu_id = vcpu -> vcpu_id<br><25> config:part_config filename:/hypervisor/debug/profiling.c func:profiling_vm_list_info offset:890<br> reason:Function return value potentially unused. : vm_info_list.vm_list.cpu_map.pcpu_id<br><26> config:sharing_config filename:/hypervisor/debug/profiling.c func:profiling_vm_list_info offset:890<br> reason:Function return value potentially unused. : vm_info_list.vm_list.cpu_map.pcpu_id<br><27> config:common filename:/hypervisor/debug/profiling.c func:profiling_vm_list_info offset:890<br> reason:Signed/unsigned conversion without cast. :  (short and unsigned short): vm_info_list.vm_list [ vm_idx ].cpu_map [ i ].pcpu_id = pcpuid_from_vcpu<br><br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by HuiHuangShi** [comment]
27 new potential violations to the coding guideline detected. Please help check. Thanks!<br><1> config:common filename:/hypervisor/common/schedule.c func:is_runnable offset:27<br> reason:Static procedure is not explicitly called in code analysed. : is_runnable<br><2> config:sharing_config filename:/hypervisor/common/schedule.c func:is_runnable offset:27<br> reason:Procedure is not called or referenced in code analysed. : is_runnable<br><3> config:part_config filename:/hypervisor/common/schedule.c func:is_runnable offset:27<br> reason:Procedure is not called or referenced in code analysed. : is_runnable<br><4> config:sharing_config filename:/hypervisor/common/schedule.c func:schedule offset:155<br> reason:Pointer not checked for null before use. : next<br><5> config:part_config filename:/hypervisor/common/schedule.c func:schedule offset:155<br> reason:Pointer not checked for null before use. : next<br><6> config:part_config filename:/hypervisor/common/schedule.c func:schedule offset:155<br> reason:Pointer assigned to NULL may be dereferenced. : next<br><7> config:sharing_config filename:/hypervisor/common/schedule.c func:schedule offset:155<br> reason:Pointer assigned to NULL may be dereferenced. : next<br><8> config:common filename:/hypervisor/arch/x86/guest/vcpu.c func:get_running_vcpu offset:202<br> reason:Cast to an unrelated type. : (char* to struct acrn_vcpu*): ( struct acrn_vcpu * ) ( ( char * ) ( curr ) - ( uint64_t ) ( & ( ( struct acrn_vcpu * ) 0 ) -> thread_obj ) )<br><9> config:common filename:/hypervisor/arch/x86/guest/vcpu.c func:get_running_vcpu offset:202<br> reason:Casting operation to a pointer. : (char* to struct acrn_vcpu*): ( struct acrn_vcpu * ) ( ( char * ) ( curr ) - ( uint64_t ) ( & ( ( struct acrn_vcpu * ) 0 ) -> thread_obj ) )<br><10> config:common filename:/hypervisor/arch/x86/guest/vcpu.c func:get_running_vcpu offset:202<br> reason:Cast from pointer to integral type. : (struct thread_object* to unsigned long): ( uint64_t ) ( & ( ( struct acrn_vcpu * ) 0 ) -> thread_obj )<br><11> config:common filename:/hypervisor/arch/x86/guest/vcpu.c func:get_running_vcpu offset:202<br> reason:Casting operation on a pointer. : (char* to struct acrn_vcpu*): ( struct acrn_vcpu * ) ( ( char * ) ( curr ) - ( uint64_t ) ( & ( ( struct acrn_vcpu * ) 0 ) -> thread_obj ) )<br><12> config:part_config filename:/hypervisor/arch/x86/guest/vcpu.c func:context_switch_out offset:708<br> reason:Function return value potentially unused. : (ectx)->ia32_star<br><13> config:sharing_config filename:/hypervisor/arch/x86/guest/vcpu.c func:context_switch_out offset:708<br> reason:Function return value potentially unused. : (ectx)->ia32_star<br><14> config:sharing_config filename:/hypervisor/arch/x86/guest/vcpu.c func:context_switch_out offset:709<br> reason:Function return value potentially unused. : (ectx)->ia32_lstar<br><15> config:part_config filename:/hypervisor/arch/x86/guest/vcpu.c func:context_switch_out offset:709<br> reason:Function return value potentially unused. : (ectx)->ia32_lstar<br><16> config:sharing_config filename:/hypervisor/arch/x86/guest/vcpu.c func:context_switch_out offset:710<br> reason:Function return value potentially unused. : (ectx)->ia32_fmask<br><17> config:part_config filename:/hypervisor/arch/x86/guest/vcpu.c func:context_switch_out offset:710<br> reason:Function return value potentially unused. : (ectx)->ia32_fmask<br><18> config:sharing_config filename:/hypervisor/arch/x86/guest/vcpu.c func:context_switch_out offset:711<br> reason:Function return value potentially unused. : (ectx)->ia32_kernel_gs_base<br><19> config:part_config filename:/hypervisor/arch/x86/guest/vcpu.c func:context_switch_out offset:711<br> reason:Function return value potentially unused. : (ectx)->ia32_kernel_gs_base<br><20> config:part_config filename:/hypervisor/arch/x86/guest/vcpu.c func:prepare_vcpu offset:760<br> reason:Function return value potentially unused. : (vcpu)->thread_obj.notify_mode<br><21> config:sharing_config filename:/hypervisor/arch/x86/guest/vcpu.c func:prepare_vcpu offset:760<br> reason:Function return value potentially unused. : (vcpu)->thread_obj.notify_mode<br><22> config:common filename:/hypervisor/include/arch/x86/guest/vcpu.h func:save_fxstore_guest_area offset:541<br> reason:Static procedure is not explicitly called in code analysed. : save_fxstore_guest_area<br><23> config:common filename:/hypervisor/include/arch/x86/guest/vcpu.h func:rstor_fxstore_guest_area offset:547<br> reason:Static procedure is not explicitly called in code analysed. : rstor_fxstore_guest_area<br><24> config:common filename:/hypervisor/debug/profiling.c func:profiling_vm_list_info offset:888<br> reason:Use of mixed mode arithmetic. :  (short and unsigned short): vm_info_list.vm_list [ vm_idx ].cpu_map [ i ].vcpu_id = vcpu -> vcpu_id<br><25> config:part_config filename:/hypervisor/debug/profiling.c func:profiling_vm_list_info offset:890<br> reason:Function return value potentially unused. : vm_info_list.vm_list.cpu_map.pcpu_id<br><26> config:sharing_config filename:/hypervisor/debug/profiling.c func:profiling_vm_list_info offset:890<br> reason:Function return value potentially unused. : vm_info_list.vm_list.cpu_map.pcpu_id<br><27> config:common filename:/hypervisor/debug/profiling.c func:profiling_vm_list_info offset:890<br> reason:Signed/unsigned conversion without cast. :  (short and unsigned short): vm_info_list.vm_list [ vm_idx ].cpu_map [ i ].pcpu_id = pcpuid_from_vcpu<br><br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by acrnsi** [comment]
OK to verify

**Comment by acrnsi** [comment]
OK to verify

**Comment by HuiHuangShi** [comment]
29 new potential violations to the coding guideline detected. Please help check. Thanks!<br><1> config:common filename:/hypervisor/common/schedule.c func:is_runnable offset:27<br> reason:Static procedure is not explicitly called in code analysed. : is_runnable<br><2> config:sharing_config filename:/hypervisor/common/schedule.c func:is_runnable offset:27<br> reason:Procedure is not called or referenced in code analysed. : is_runnable<br><3> config:part_config filename:/hypervisor/common/schedule.c func:is_runnable offset:27<br> reason:Procedure is not called or referenced in code analysed. : is_runnable<br><4> config:sharing_config filename:/hypervisor/common/schedule.c func:schedule offset:155<br> reason:Pointer not checked for null before use. : next<br><5> config:part_config filename:/hypervisor/common/schedule.c func:schedule offset:155<br> reason:Pointer not checked for null before use. : next<br><6> config:part_config filename:/hypervisor/common/schedule.c func:schedule offset:155<br> reason:Pointer assigned to NULL may be dereferenced. : next<br><7> config:sharing_config filename:/hypervisor/common/schedule.c func:schedule offset:155<br> reason:Pointer assigned to NULL may be dereferenced. : next<br><8> config:sharing_config filename:/hypervisor/arch/x86/guest/vm.c func:start_vm offset:668<br> reason:Pointer assigned to NULL may be dereferenced. : bsp<br><9> config:part_config filename:/hypervisor/arch/x86/guest/vm.c func:start_vm offset:668<br> reason:Pointer assigned to NULL may be dereferenced. : bsp<br><10> config:common filename:/hypervisor/include/arch/x86/guest/vcpu.h func:save_fxstore_guest_area offset:541<br> reason:Static procedure is not explicitly called in code analysed. : save_fxstore_guest_area<br><11> config:common filename:/hypervisor/include/arch/x86/guest/vcpu.h func:rstor_fxstore_guest_area offset:547<br> reason:Static procedure is not explicitly called in code analysed. : rstor_fxstore_guest_area<br><12> config:common filename:/hypervisor/arch/x86/guest/vcpu.c func:get_running_vcpu offset:202<br> reason:Cast to an unrelated type. : (char* to struct acrn_vcpu*): ( struct acrn_vcpu * ) ( ( char * ) ( curr ) - ( uint64_t ) ( & ( ( struct acrn_vcpu * ) 0 ) -> thread_obj ) )<br><13> config:common filename:/hypervisor/arch/x86/guest/vcpu.c func:get_running_vcpu offset:202<br> reason:Casting operation to a pointer. : (char* to struct acrn_vcpu*): ( struct acrn_vcpu * ) ( ( char * ) ( curr ) - ( uint64_t ) ( & ( ( struct acrn_vcpu * ) 0 ) -> thread_obj ) )<br><14> config:common filename:/hypervisor/arch/x86/guest/vcpu.c func:get_running_vcpu offset:202<br> reason:Cast from pointer to integral type. : (struct thread_object* to unsigned long): ( uint64_t ) ( & ( ( struct acrn_vcpu * ) 0 ) -> thread_obj )<br><15> config:common filename:/hypervisor/arch/x86/guest/vcpu.c func:get_running_vcpu offset:202<br> reason:Casting operation on a pointer. : (char* to struct acrn_vcpu*): ( struct acrn_vcpu * ) ( ( char * ) ( curr ) - ( uint64_t ) ( & ( ( struct acrn_vcpu * ) 0 ) -> thread_obj ) )<br><16> config:part_config filename:/hypervisor/arch/x86/guest/vcpu.c func:context_switch_out offset:705<br> reason:Function return value potentially unused. : (ectx)->ia32_star<br><17> config:sharing_config filename:/hypervisor/arch/x86/guest/vcpu.c func:context_switch_out offset:705<br> reason:Function return value potentially unused. : (ectx)->ia32_star<br><18> config:sharing_config filename:/hypervisor/arch/x86/guest/vcpu.c func:context_switch_out offset:706<br> reason:Function return value potentially unused. : (ectx)->ia32_lstar<br><19> config:part_config filename:/hypervisor/arch/x86/guest/vcpu.c func:context_switch_out offset:706<br> reason:Function return value potentially unused. : (ectx)->ia32_lstar<br><20> config:part_config filename:/hypervisor/arch/x86/guest/vcpu.c func:context_switch_out offset:707<br> reason:Function return value potentially unused. : (ectx)->ia32_fmask<br><21> config:sharing_config filename:/hypervisor/arch/x86/guest/vcpu.c func:context_switch_out offset:707<br> reason:Function return value potentially unused. : (ectx)->ia32_fmask<br><22> config:part_config filename:/hypervisor/arch/x86/guest/vcpu.c func:context_switch_out offset:708<br> reason:Function return value potentially unused. : (ectx)->ia32_kernel_gs_base<br><23> config:sharing_config filename:/hypervisor/arch/x86/guest/vcpu.c func:context_switch_out offset:708<br> reason:Function return value potentially unused. : (ectx)->ia32_kernel_gs_base<br><24> config:part_config filename:/hypervisor/arch/x86/guest/vcpu.c func:prepare_vcpu offset:759<br> reason:Function return value potentially unused. : (vcpu)->thread_obj.notify_mode<br><25> config:sharing_config filename:/hypervisor/arch/x86/guest/vcpu.c func:prepare_vcpu offset:759<br> reason:Function return value potentially unused. : (vcpu)->thread_obj.notify_mode<br><26> config:common filename:/hypervisor/debug/profiling.c func:profiling_vm_list_info offset:888<br> reason:Use of mixed mode arithmetic. :  (short and unsigned short): vm_info_list.vm_list [ vm_idx ].cpu_map [ i ].vcpu_id = vcpu -> vcpu_id<br><27> config:part_config filename:/hypervisor/debug/profiling.c func:profiling_vm_list_info offset:890<br> reason:Function return value potentially unused. : vm_info_list.vm_list.cpu_map.pcpu_id<br><28> config:sharing_config filename:/hypervisor/debug/profiling.c func:profiling_vm_list_info offset:890<br> reason:Function return value potentially unused. : vm_info_list.vm_list.cpu_map.pcpu_id<br><29> config:common filename:/hypervisor/debug/profiling.c func:profiling_vm_list_info offset:890<br> reason:Signed/unsigned conversion without cast. :  (short and unsigned short): vm_info_list.vm_list [ vm_idx ].cpu_map [ i ].pcpu_id = pcpuid_from_vcpu<br><br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Pull request merged**
