### PR TITLE
Porting and enabled NUC7I7BNB platform

### PR DESCRIPTION
**Pull request by ionutnechita**
Description:
 - in the past i used the NUC7i7DNB platform
   to be able to start the hypervisor,
   but in the future i will use the
   new configuration, much more dedicated
   on this platform.
 - this commit is under construction

Signed-off-by: Ionut Nechita <ionut_n2001@yahoo.com>

### CODE REVIEW

**Comment by gvancuts** [comment]
> try verify EHL

Why?

**Comment by gvancuts** [comment]
I have mixed feelings about this Pull Request. On one hand, it's great to have additional configs being published that others can benefit from. On the other hand, it will quickly become unmanageable if too many folks push their config upstream. I do not have a clear idea for how to deal with this, but what if we were to set-up a new repo under `github.com/projectacrn` to host other board and scenario XMLs? They would come with no guarantee and no validation would be performed on them, but they could still be useful to others! Thoughts?

**Comment by terryzouhao** [comment]
Yes also mixed feeling from me... Actually current NUC7I7BNB xmls in Pull request is copied from nuc7i7dnb board config folder<https://github.com/projectacrn/acrn-hypervisor/tree/master/misc/config_tools/data/nuc7i7dnb>, no difference now. Just compared NUC7I7BNB VS nuc7i7dnb Spec, same 7th generation KabyLake Core, don’t need any config xml change to support those 2 boards right.
Back to the topic of reference board config xmls in github, first really welcome to try ACRN, share and contribute board config files to benefit others. But to better manage reference XML config file/number, current plan is only maintain config xml of supported hardware<https://projectacrn.github.io/latest/reference/hardware.html> list in github main config folder, so there are <10 board folders under /misc/config_tools/data<https://github.com/projectacrn/acrn-hypervisor/tree/master/misc/config_tools/data> now: typical reference board for each IA silicon generation. Moving forward, similar with other open source project, we will have a longer list of supported hardware list, even with other arch’s folder, e.g., Zepyhr Supported Board<https://docs.zephyrproject.org/latest/boards/index.html>. So similar Zepyhr Board Porting Guide<https://docs.zephyrproject.org/latest/guides/porting/board_porting.html#create-your-board-directory> documents would be good choice to support various scaling/porting right?  Anyway, if there are going to many reference xmls files for scaling boards, create another repo just for sharing purpose maybe a good idea : )

**Comment by HuiHuangShi** [comment]
No new violations to the coding guideline detected.<br>No New Name Conflict<br>No New Function Declaration/Definition Mismatch

**Comment by wenlingz** [comment]
@ionutnechita please add Tracked-On on your commit, for example:
Tracked-On: #5048

**Comment by terryzouhao** [comment]
@ionutnechita Based on original comments:  Current plan of board config folder under '/misc/config_tools/data', is only focused on ACRN supported hardware list in homepage first. So we may reject this pull request to mainline? any further question or idea from you :), thanks.

**Comment by wenlingz** [comment]
@ionutnechita  shall we close this PR now ? please refer terry's comments, thanks

**Comment by wenlingz** [comment]
Close it temporary

**Pull request closed without merging**
