### PR TITLE
doc: fix utf-8 punctuation, branding, spelling

### PR DESCRIPTION
**Pull request by dbkinder**
Fix some stray UTF-8 punctuation and symbol characters, unnecessary
trademark symbols, and some misspellings missed during regular reviews.

Signed-off-by: David B. Kinder <david.b.kinder@intel.com>
Tracked-On: #2712

### CODE REVIEW

**Comment by HuiHuangShi** [comment]
No new violations to the coding guideline detected.<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by dbkinder** [comment]
@NanlinXie Looks like CI is running some tests for this PR with only .rst file changes

**Comment by HuiHuangShi** [comment]
No new violations to the coding guideline detected.<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by wenlingz** [comment]
@dbkinder Receive the email continuously because our scripts check the Tracked-On information whether has the External_ID.
Also, please help check the change, which make doc fail, please refer the log:
*********************************************************************************
New errors/warnings found, please fix them:
==============================================

/workspace/acrn-hypervisor/doc/tools/acrn-crashlog/usercrash/README.rst:76: WARNING: Title underline too short.

Source Code
**********
/workspace/acrn-hypervisor/doc/tools/acrn-crashlog/usercrash/README.rst:76: WARNING: Title underline too short.

Source Code
**********
make[1]: Leaving directory '/workspace/acrn-hypervisor/doc'
make[1]: *** [Makefile:57: html] Error 1
make: *** [Makefile:72: doc] Error 2
Build step 'Execute shell' marked build as failure

**Comment by HuiHuangShi** [comment]
No new violations to the coding guideline detected.<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Pull request merged**
