### PR TITLE
Virtio rpmb clean up assert

### PR DESCRIPTION
**Pull request by yingbinx**
clean up assert from virtio rpmb module.

### CODE REVIEW

**Comment by NanlinXie** [comment]
Can one of the admins verify this patch?

**Comment by yingbinx** [comment]
Yes, I get ACK from my maintainers.

Best Regards


Zeng, Yingbin

E-mail: yingbinx.zeng@intel.com

**Comment by yingbinx** [comment]
> Did u get ack from maintainers?

Yes, I get ACK from my maintainers.

**Comment by yingbinx** [comment]
> > Did u get ack from maintainers?
> 
> Yes, I get ACK from my maintainers.

get ACK from Zhu,Bing

**Comment by ClaudZhang1995** [comment]
OK to verify

**Comment by acrnsi** [comment]
@yingbinx please add your Tracked-On info in your commits

**Comment by dongyaozu** [comment]
Then add the ack information in the patch commit message.

**Comment by wenlingz** [comment]
@yingbinx please add your Tracked-On info in your commits

**Comment by yingbinx** [comment]
close it, and reopen at https://github.com/projectacrn/acrn-hypervisor/pull/3316

**Pull request closed without merging**
