### PR TITLE
Unifying the VPCI partition mode and sharing mode code

### PR DESCRIPTION
**Pull request by donsheng**
Changes include:

Put shared generic functions in vdev.c so that they can be used by both sharing/partition mode code.
Made the vdev list per vpci/vm and it is used by both sharing mode/partition mode
Created a vdev.c to handle all the vdev common functions
Tracked-On: #2534
Signed-off-by: dongshen dongsheng.x.zhang@intel.com

This one is a reopen for the following closed PR:
https://github.com/projectacrn/acrn-hypervisor/pull/2632

Will need to post more patches to eventually unify the VPCI partition/sharing mode code

### CODE REVIEW

**Comment by HuiHuangShi** [comment]
12 new potential violations to the coding guideline detected. Please help check. Thanks!<br><1> config:sharing_config filename:/hypervisor/dm/vpci/sharing_mode.c func:sharing_mode_find_vdev offset:47<br> reason:Pointer not checked for null before use. : tmp<br><2> config:sharing_config filename:/hypervisor/dm/vpci/sharing_mode.c func:sharing_mode_find_vdev_sos offset:68<br> reason:Pointer not checked for null before use. : vpci<br><3> config:sharing_config filename:/hypervisor/dm/vpci/sharing_mode.c func:sharing_mode_find_vdev_sos offset:71<br> reason:Pointer assignment to wider scope.<br><4> config:sharing_config filename:/hypervisor/dm/vpci/sharing_mode.c func:alloc_pci_vdev offset:144<br> reason:Pointer not checked for null before use. : vdev<br><5> config:sharing_config filename:/hypervisor/dm/vpci/sharing_mode.c func:sharing_mode_vpci_init offset:185<br> reason:Pointer not checked for null before use. : vdev<br><6> config:sharing_config filename:/hypervisor/dm/vpci/sharing_mode.c func:sharing_mode_vpci_deinit offset:208<br> reason:Pointer not checked for null before use. : vdev<br><7> config:sharing_config filename:/hypervisor/dm/vpci/pci_priv.h func:pci_vdev_read_cfg_u8 offset:40<br> reason:Static procedure is not explicitly called in code analysed. : pci_vdev_read_cfg_u8<br><8> config:sharing_config filename:/hypervisor/dm/vpci/pci_priv.h func:pci_vdev_read_cfg_u16 offset:45<br> reason:Static procedure is not explicitly called in code analysed. : pci_vdev_read_cfg_u16<br><9> config:sharing_config filename:/hypervisor/dm/vpci/pci_priv.h func:pci_vdev_read_cfg_u32 offset:50<br> reason:Static procedure is not explicitly called in code analysed. : pci_vdev_read_cfg_u32<br><10> config:sharing_config filename:/hypervisor/dm/vpci/pci_priv.h func:pci_vdev_write_cfg_u8 offset:55<br> reason:Static procedure is not explicitly called in code analysed. : pci_vdev_write_cfg_u8<br><11> config:sharing_config filename:/hypervisor/dm/vpci/pci_priv.h func:pci_vdev_write_cfg_u16 offset:60<br> reason:Static procedure is not explicitly called in code analysed. : pci_vdev_write_cfg_u16<br><12> config:sharing_config filename:/hypervisor/dm/vpci/pci_priv.h func:pci_vdev_write_cfg_u32 offset:65<br> reason:Static procedure is not explicitly called in code analysed. : pci_vdev_write_cfg_u32<br><br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by HuiHuangShi** [comment]
116 new potential violations to the coding guideline detected. Please help check. Thanks!<br><1> config:part_config filename:/hypervisor/include/arch/x86/guest/vm.h func: offset:242<br> reason:* or & not attached to type in declaration.<br><2> config:part_config filename:/hypervisor/include/arch/x86/guest/vm.h func: offset:242<br> reason:No prefix for global function.<br><3> config:part_config filename:/hypervisor/include/arch/x86/guest/vm.h func: offset:242<br> reason:No space between * or & and name in declaration.<br><4> config:sharing_config filename:/hypervisor/include/dm/pci.h func: offset:175<br> reason:Identifier reuse: component vs var. : bdf<br><5> config:common filename:/hypervisor/include/dm/pci.h func:bdf_is_equal offset:226<br> reason:Static procedure is not explicitly called in code analysed. : bdf_is_equal<br><6> config:part_config filename:/hypervisor/dm/vpci/partition_mode.c func: offset:81<br> reason:Less than 2 blank lines separating procs.<br><7> config:part_config filename:/hypervisor/dm/vpci/partition_mode.c func:partition_mode_vpci_init offset:91<br> reason:Identifier reuse: var vs proc param. : vm_config<br><8> config:part_config filename:/hypervisor/dm/vpci/partition_mode.c func:partition_mode_vpci_init offset:97<br> reason:Use of numeric literal in expression.        : 0U<br><9> config:part_config filename:/hypervisor/dm/vpci/partition_mode.c func:partition_mode_vpci_init offset:100<br> reason:Tab character in source.<br><10> config:part_config filename:/hypervisor/dm/vpci/partition_mode.c func:partition_mode_vpci_init offset:107<br> reason:Tab character in source.<br><11> config:part_config filename:/hypervisor/dm/vpci/partition_mode.c func:partition_mode_vpci_init offset:115<br> reason:Tab character in source.<br><12> config:part_config filename:/hypervisor/dm/vpci/partition_mode.c func:partition_mode_vpci_init offset:116<br> reason:} not aligned vertically below {.            : Cols 9 and 51 respectively<br><13> config:part_config filename:/hypervisor/dm/vpci/partition_mode.c func:partition_mode_vpci_init offset:118<br> reason:Tab character in source.<br><14> config:part_config filename:/hypervisor/dm/vpci/partition_mode.c func:partition_mode_vpci_deinit offset:124<br> reason:Referenced parameter has possible clear path. : (vm)->vpci.pci_vdevs<br><15> config:part_config filename:/hypervisor/dm/vpci/partition_mode.c func:partition_mode_vpci_deinit offset:129<br> reason:Use of numeric literal in expression.        : 0U<br><16> config:part_config filename:/hypervisor/dm/vpci/partition_mode.c func:partition_mode_vpci_deinit offset:131<br> reason:{ or } not on line by itself.<br><17> config:part_config filename:/hypervisor/dm/vpci/partition_mode.c func:partition_mode_vpci_deinit offset:136<br> reason:} not aligned vertically below {.            : Cols 9 and 54 respectively<br><18> config:common filename:/hypervisor/dm/vpci/pci_priv.h func: offset:84<br> reason:Parameter not declared on new line.          : param 2: vbdf<br><19> config:common filename:/hypervisor/dm/vpci/pci_priv.h func: offset:84<br> reason:Function starts with lower case character.   : pci_find_vdev_by_vbdf<br><20> config:sharing_config filename:/hypervisor/dm/vpci/pci_priv.h func: offset:84<br> reason:No definition in system for prototyped procedure. : pci_find_vdev_by_vbdf<br><21> config:part_config filename:/hypervisor/dm/vpci/pci_priv.h func: offset:84<br> reason:No definition in system for prototyped procedure. : pci_find_vdev_by_vbdf<br><22> config:common filename:/hypervisor/dm/vpci/pci_priv.h func: offset:84<br> reason:Name redeclared in another C name space (MR). : vbdf<br><23> config:common filename:/hypervisor/dm/vpci/pci_priv.h func: offset:86<br> reason:Parameter not declared on new line.          : param 2: pbdf<br><24> config:common filename:/hypervisor/dm/vpci/pci_priv.h func: offset:86<br> reason:Function starts with lower case character.   : pci_find_vdev_by_pbdf<br><25> config:part_config filename:/hypervisor/dm/vpci/pci_priv.h func: offset:86<br> reason:No definition in system for prototyped procedure. : pci_find_vdev_by_pbdf<br><26> config:sharing_config filename:/hypervisor/dm/vpci/pci_priv.h func: offset:86<br> reason:No definition in system for prototyped procedure. : pci_find_vdev_by_pbdf<br><27> config:sharing_config filename:/hypervisor/include/dm/vpci.h func: offset:90<br> reason:Identifier reuse: component vs var. : vpci<br><28> config:common filename:/hypervisor/include/dm/vpci.h func: offset:123<br> reason:{ ... } contents not indented by 2 spaces.<br><29> config:common filename:/hypervisor/include/dm/vpci.h func: offset:123<br> reason:Tab character in source.<br><30> config:common filename:/hypervisor/include/dm/vpci.h func: offset:127<br> reason:{ ... } contents not indented by 2 spaces.<br><31> config:common filename:/hypervisor/include/dm/vpci.h func: offset:127<br> reason:Tab character in source.<br><32> config:part_config filename:/hypervisor/include/dm/vpci.h func: offset:132<br> reason:Extern not at start of header file.<br><33> config:part_config filename:/hypervisor/include/dm/vpci.h func: offset:132<br> reason:No prefix for global function.<br><34> config:part_config filename:/hypervisor/include/dm/vpci.h func: offset:132<br> reason:extern not in nominated include file.<br>.....<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by HuiHuangShi** [comment]
19 new potential violations to the coding guideline detected. Please help check. Thanks!<br><1> config:sharing_config filename:/hypervisor/dm/vpci/sharing_mode.c func:sharing_mode_find_vdev_sos offset:48<br> reason:Pointer not checked for null before use. : vpci<br><2> config:sharing_config filename:/hypervisor/dm/vpci/sharing_mode.c func:sharing_mode_find_vdev_sos offset:51<br> reason:Pointer assignment to wider scope.<br><3> config:sharing_config filename:/hypervisor/dm/vpci/sharing_mode.c func:alloc_pci_vdev offset:124<br> reason:Pointer not checked for null before use. : vdev<br><4> config:sharing_config filename:/hypervisor/dm/vpci/sharing_mode.c func:sharing_mode_vpci_init offset:165<br> reason:Pointer not checked for null before use. : vdev<br><5> config:sharing_config filename:/hypervisor/dm/vpci/sharing_mode.c func:sharing_mode_vpci_deinit offset:188<br> reason:Pointer not checked for null before use. : vdev<br><6> config:common filename:/hypervisor/dm/vpci/pci_priv.h func:pci_vdev_read_cfg_u8 offset:40<br> reason:Static procedure is not explicitly called in code analysed. : pci_vdev_read_cfg_u8<br><7> config:common filename:/hypervisor/dm/vpci/pci_priv.h func:pci_vdev_read_cfg_u16 offset:45<br> reason:Static procedure is not explicitly called in code analysed. : pci_vdev_read_cfg_u16<br><8> config:common filename:/hypervisor/dm/vpci/pci_priv.h func:pci_vdev_read_cfg_u32 offset:50<br> reason:Static procedure is not explicitly called in code analysed. : pci_vdev_read_cfg_u32<br><9> config:common filename:/hypervisor/dm/vpci/pci_priv.h func:pci_vdev_write_cfg_u8 offset:55<br> reason:Static procedure is not explicitly called in code analysed. : pci_vdev_write_cfg_u8<br><10> config:common filename:/hypervisor/dm/vpci/pci_priv.h func:pci_vdev_write_cfg_u16 offset:60<br> reason:Static procedure is not explicitly called in code analysed. : pci_vdev_write_cfg_u16<br><11> config:common filename:/hypervisor/dm/vpci/pci_priv.h func:pci_vdev_write_cfg_u32 offset:65<br> reason:Static procedure is not explicitly called in code analysed. : pci_vdev_write_cfg_u32<br><12> config:sharing_config filename:/hypervisor/dm/vpci/vdev.c func:pci_find_vdev_by_vbdf offset:70<br> reason:Procedure is not called or referenced in code analysed. : pci_find_vdev_by_vbdf<br><13> config:part_config filename:/hypervisor/dm/vpci/vdev.c func:pci_find_vdev_by_vbdf offset:79<br> reason:Pointer not checked for null before use. : tmp<br><14> config:sharing_config filename:/hypervisor/dm/vpci/vdev.c func:pci_find_vdev_by_vbdf offset:79<br> reason:Pointer not checked for null before use. : tmp<br><15> config:common filename:/hypervisor/dm/vpci/vdev.c func:pci_find_vdev_by_vbdf offset:85<br> reason:Pointer assignment to wider scope.<br><16> config:part_config filename:/hypervisor/dm/vpci/vdev.c func:pci_find_vdev_by_pbdf offset:91<br> reason:Procedure is not called or referenced in code analysed. : pci_find_vdev_by_pbdf<br><17> config:sharing_config filename:/hypervisor/dm/vpci/vdev.c func:pci_find_vdev_by_pbdf offset:100<br> reason:Pointer not checked for null before use. : tmp<br><18> config:part_config filename:/hypervisor/dm/vpci/vdev.c func:pci_find_vdev_by_pbdf offset:100<br> reason:Pointer not checked for null before use. : tmp<br><19> config:common filename:/hypervisor/dm/vpci/vdev.c func:pci_find_vdev_by_pbdf offset:106<br> reason:Pointer assignment to wider scope.<br><br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by wenlingz** [comment]
@dongyaozu please help approve it, thanks

**Pull request merged**
