### PR TITLE
Replace debugfs,losetup and fdisk with libraries. 

### PR DESCRIPTION
**Pull request by liuxinw**
Replace debugfs,losetup and fdisk with libraries.

### CODE REVIEW

**Comment by NanlinXie** [comment]
Can one of the admins verify this patch?

**Comment by ailun258** [comment]
looks good to me,  i agree to add those 2 packages ,
@dbkinder @liuxinw

**Comment by dongyaozu** [comment]
@liuxinw did u get ACK from sub-maintainers?

**Comment by liuxinw** [comment]
@dongyaozu Oh, sorry, I forget to add ACK to commit message. I will add ACK and push them again.

**Comment by liuxinw** [comment]
Commits have been refined.
Sorry for the inconvenience.

**Comment by lijinxia** [comment]
Verified+1

**Pull request merged**
