### PR TITLE
doc: fix docs with windows line endings

### PR DESCRIPTION
**Pull request by dbkinder**
Signed-off-by: David B. Kinder <david.b.kinder@intel.com>

### CODE REVIEW

**Comment by HuiHuangShi** [comment]
No new violations to the coding guideline detected.<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by dbkinder** [comment]
@NanlinXie Do you know why this doc-only change is failing a CI build test?

**Comment by HuiHuangShi** [comment]
No new violations to the coding guideline detected.<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by HuiHuangShi** [comment]
No new violations to the coding guideline detected.<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by ClaudZhang1995** [comment]
hi @dbkinder , git am failed .it is faill log :
08:26:00 LOG: Start to git am https://github.com/projectacrn/acrn-hypervisor/pull/4525.patch
error: patch failed: doc/tutorials/running_deb_as_serv_vm.rst:1
error: doc/tutorials/running_deb_as_serv_vm.rst: patch does not apply
error: patch failed: doc/tutorials/running_deb_as_user_vm.rst:1
error: doc/tutorials/running_deb_as_user_vm.rst: patch does not apply
error: patch failed: doc/tutorials/running_ubun_as_user_vm.rst:1
error: doc/tutorials/running_ubun_as_user_vm.rst: patch does not apply
error: patch failed: doc/tutorials/vuart_configuration.rst:1
error: doc/tutorials/vuart_configuration.rst: patch does not apply
Applying: doc: fix docs with windows line endings
Patch failed at 0001 doc: fix docs with windows line endings
Use 'git am --show-current-patch' to see the failed patch

**Comment by ClaudZhang1995** [comment]
hi @dbkinder  ,please rebase your code .The branch has conflicts that must be resolved.

**Comment by HuiHuangShi** [comment]
No new violations to the coding guideline detected.<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Pull request merged**
