### PR TITLE
 Some minor VPCI code cleanup

### PR DESCRIPTION
**Pull request by donsheng**
Some minor VPCI code cleanup:
 - Remove function pci_pdev_foreach() per discussion with Eddie
 - Call function is_prelaunched_vm() instead to reduce code

Tracked-On: #3056

### CODE REVIEW

**Comment by donsheng** [comment]
@dongyaozu, as I answered your questions and do not think there is a problem, so I am PR my patches.

init_vdevs(vm);
Have a look at the code, it seems the logic now is problemtic...
Now, init_vdevs assigns all devices to the vm. This is ok for sdc usage. But for others, how can we do so?
Don:
It is not problematic, in  init_vdev_for_pdev(), it has the following code, which works for both sdc and logical partition code:

**Comment by HuiHuangShi** [comment]
out of license

**Comment by HuiHuangShi** [comment]
out of license

**Comment by HuiHuangShi** [comment]
out of license

**Comment by HuiHuangShi** [comment]
No new violations to the coding guideline detected.<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Pull request merged**
