### PR TITLE
ACRN/HV: Add one new board configuration for ACRN-hypervisor

### PR DESCRIPTION
**Pull request by yakuizhao**
The memory size and IOMMU number are refined to meet with ICL board requirement.
Otherwise the ACRN hypervisor can't be booted on the new ICL board.
ICL(the abbreviation of Ice Lake) is the next-generation platform based on 10nm.
CPU is based on Sunny Cove microarchitecture and GPU is based on gen11.
The new board is named as icl-rvp.

Tracked-On: #3216
Signed-off-by: Zhao Yakui <yakui.zhao@intel.com>
Reviewed-by: Binbin Wu <binbin.wu@intel.com>

### CODE REVIEW

**Comment by dongyaozu** [comment]
@jsun26intel can u review?

**Comment by gvancuts** [comment]
Can you make these minor tweaks to the commit message?

* `ICELAKE` -> `Ice Lake`
* `Sunny Core` -> `Sunny Cove microarchitecture` (note it's Co**v**e and not Co**r**e)

**Comment by yakuizhao** [comment]
@gvancuts , Thanks for the nice review. It will be updated.

**Comment by jsun26intel** [comment]
I am OK with the patch.

**Comment by acrnsi** [comment]
OK to verify

**Comment by acrnsi** [comment]
OK to verify

**Comment by HuiHuangShi** [comment]
No new violations to the coding guideline detected.<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Pull request merged**
