### PR TITLE
fix "warning:ISO C forbids 'return' with expression,in function retur…

### PR DESCRIPTION
**Pull request by 425686558**
…ning void"

returning void function must return void.

Signed-off-by: huihuang.shi <huihuang.shi@intel.com>

### CODE REVIEW

**Comment by NanlinXie** [comment]
Can one of the admins verify this patch?

**Comment by 425686558** [comment]
acked by Eddie Dong

**Comment by dongyaozu** [comment]
you should add the "Acked-by:..." in the commit message...

**Comment by lijinxia** [comment]
Verified+1

**Pull request merged**
