### PR TITLE
dm: virtio: check for paddr_guest2host return value

### PR DESCRIPTION
**Pull request by tomasbw**
paddr_guest2host can return NULL, but code paths in virtio
are not checking the return value.
_vq_record() initializes iov_base pointer using paddr_guest2host()
but there is nothing in the flow that checks for NULL.
Chane _vq_record to return -1 in case the address translation
has failed.

Tracked-On: #5452
Signed-off-by: Tomas Winkler <tomas.winkler@intel.com>
Acked-by: Wang, Yu1 <yu1.wang@intel.com>

### CODE REVIEW

**Comment by HuiHuangShi** [comment]
No new violations to the coding guideline detected.<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Review by ywan170 — APPROVED** [review]

**Review by ywan170 — APPROVED** [review]

**Comment by wenlingz** [comment]
OK to verify

**Comment by HuiHuangShi** [comment]
No new violations to the coding guideline detected.<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by ywan170** [comment]
@tomasbw  please check your patch:

virtio_vq_init: vq enable failed
virtio_vq_init: vq enable failed
virtio_vq_init: vq enable failed
virtio_vq_init: vq enable failed
virtio_vq_init: vq enable failed
virtio_vq_init: vq enable failed
virtio_vq_init: vq enable failed
virtio_vq_init: vq enable failed
virtio_vq_init: vq enable failed
virtio_vq_init: vq enable failed
virtio_vq_init: vq enable failed
virtio_vq_init: vq enable failed

**Comment by tomasbw** [comment]
the issue was fixed, missing return before the error label.

**Comment by HuiHuangShi** [comment]
No new violations to the coding guideline detected.<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Pull request merged**
