### PR TITLE
HV: Add prefix 'p' before 'cpu' to physical cpu related functions

### PR DESCRIPTION
**Pull request by KaigeFu**
This patch adds prefix 'p' before 'cpu' to physical cpu related functions.
And there is no code logic change.

Tracked-On: #2991
Signed-off-by: Kaige Fu <kaige.fu@intel.com>
Acked-by: Eddie Dong <eddie.dong@intel.com>

### CODE REVIEW

**Comment by HuiHuangShi** [comment]
out of time

**Comment by KaigeFu** [comment]
@HuiHuangShi Timeout occurred. Could you help re-scan it?

**Comment by HuiHuangShi** [comment]
75 new potential violations to the coding guideline detected. Please help check. Thanks!<br><1> config:common filename:/hypervisor/include/arch/x86/cpu.h func:get_pcpu_id offset:415<br> reason:Static procedure is not explicitly called in code analysed. : get_pcpu_id<br><2> config:sharing_config filename:/hypervisor/include/arch/x86/cpu.h func:get_pcpu_id offset:417<br> reason:Procedure contains UR data flow anomalies. : cpu_id<br><3> config:part_config filename:/hypervisor/include/arch/x86/cpu.h func:get_pcpu_id offset:417<br> reason:Procedure contains UR data flow anomalies. : cpu_id<br><4> config:common filename:/hypervisor/include/arch/x86/cpu.h func:get_pcpu_id offset:421<br> reason:Procedure is not pure assembler.<br><5> config:common filename:/hypervisor/arch/x86/cpu_caps.c func:init_pcpu_model_name offset:278<br> reason:Casting operation to a pointer. : (char* to unsigned int*): ( uint32_t * ) ( & boot_cpu_data.model_name [ 12 ] )<br><6> config:common filename:/hypervisor/arch/x86/cpu_caps.c func:init_pcpu_model_name offset:278<br> reason:Casting operation to a pointer. : (char* to unsigned int*): ( uint32_t * ) ( & boot_cpu_data.model_name [ 4 ] )<br><7> config:common filename:/hypervisor/arch/x86/cpu_caps.c func:init_pcpu_model_name offset:278<br> reason:Casting operation to a pointer. : (char* to unsigned int*): ( uint32_t * ) ( & boot_cpu_data.model_name [ 8 ] )<br><8> config:common filename:/hypervisor/arch/x86/cpu_caps.c func:init_pcpu_model_name offset:278<br> reason:Casting operation on a pointer. : (char* to unsigned int*): ( uint32_t * ) ( & boot_cpu_data.model_name [ 8 ] )<br><9> config:common filename:/hypervisor/arch/x86/cpu_caps.c func:init_pcpu_model_name offset:278<br> reason:Casting operation on a pointer. : (char* to unsigned int*): ( uint32_t * ) ( & boot_cpu_data.model_name [ 4 ] )<br><10> config:common filename:/hypervisor/arch/x86/cpu_caps.c func:init_pcpu_model_name offset:278<br> reason:Casting operation on a pointer. : (char* to unsigned int*): ( uint32_t * ) ( & boot_cpu_data.model_name [ 12 ] )<br><11> config:common filename:/hypervisor/arch/x86/cpu_caps.c func:init_pcpu_model_name offset:278<br> reason:Cast from integral type to pointer. : (char to unsigned int*): ( uint32_t * ) ( boot_cpu_data.model_name )<br><12> config:common filename:/hypervisor/arch/x86/cpu_caps.c func:init_pcpu_model_name offset:283<br> reason:Casting operation to a pointer. : (char* to unsigned int*): ( uint32_t * ) ( & boot_cpu_data.model_name [ 28 ] )<br><13> config:common filename:/hypervisor/arch/x86/cpu_caps.c func:init_pcpu_model_name offset:283<br> reason:Casting operation to a pointer. : (char* to unsigned int*): ( uint32_t * ) ( & boot_cpu_data.model_name [ 24 ] )<br><14> config:common filename:/hypervisor/arch/x86/cpu_caps.c func:init_pcpu_model_name offset:283<br> reason:Casting operation to a pointer. : (char* to unsigned int*): ( uint32_t * ) ( & boot_cpu_data.model_name [ 16 ] )<br><15> config:common filename:/hypervisor/arch/x86/cpu_caps.c func:init_pcpu_model_name offset:283<br> reason:Casting operation to a pointer. : (char* to unsigned int*): ( uint32_t * ) ( & boot_cpu_data.model_name [ 20 ] )<br><16> config:common filename:/hypervisor/arch/x86/cpu_caps.c func:init_pcpu_model_name offset:283<br> reason:Casting operation on a pointer. : (char* to unsigned int*): ( uint32_t * ) ( & boot_cpu_data.model_name [ 20 ] )<br><17> config:common filename:/hypervisor/arch/x86/cpu_caps.c func:init_pcpu_model_name offset:283<br> reason:Casting operation on a pointer. : (char* to unsigned int*): ( uint32_t * ) ( & boot_cpu_data.model_name [ 28 ] )<br><18> config:common filename:/hypervisor/arch/x86/cpu_caps.c func:init_pcpu_model_name offset:283<br> reason:Casting operation on a pointer. : (char* to unsigned int*): ( uint32_t * ) ( & boot_cpu_data.model_name [ 24 ] )<br><19> config:common filename:/hypervisor/arch/x86/cpu_caps.c func:init_pcpu_model_name offset:283<br> reason:Casting operation on a pointer. : (char* to unsigned int*): ( uint32_t * ) ( & boot_cpu_data.model_name [ 16 ] )<br><20> config:common filename:/hypervisor/arch/x86/cpu_caps.c func:init_pcpu_model_name offset:288<br> reason:Casting operation to a pointer. : (char* to unsigned int*): ( uint32_t * ) ( & boot_cpu_data.model_name [ 36 ] )<br><21> config:common filename:/hypervisor/arch/x86/cpu_caps.c func:init_pcpu_model_name offset:288<br> reason:Casting operation to a pointer. : (char* to unsigned int*): ( uint32_t * ) ( & boot_cpu_data.model_name [ 40 ] )<br><22> config:common filename:/hypervisor/arch/x86/cpu_caps.c func:init_pcpu_model_name offset:288<br> reason:Casting operation to a pointer. : (char* to unsigned int*): ( uint32_t * ) ( & boot_cpu_data.model_name [ 32 ] )<br><23> config:common filename:/hypervisor/arch/x86/cpu_caps.c func:init_pcpu_model_name offset:288<br> reason:Casting operation to a pointer. : (char* to unsigned int*): ( uint32_t * ) ( & boot_cpu_data.model_name [ 44 ] )<br><24> config:common filename:/hypervisor/arch/x86/cpu_caps.c func:init_pcpu_model_name offset:288<br> reason:Casting operation on a pointer. : (char* to unsigned int*): ( uint32_t * ) ( & boot_cpu_data.model_name [ 40 ] )<br><25> config:common filename:/hypervisor/arch/x86/cpu_caps.c func:init_pcpu_model_name offset:288<br> reason:Casting operation on a pointer. : (char* to unsigned int*): ( uint32_t * ) ( & boot_cpu_data.model_name [ 32 ] )<br><26> config:common filename:/hypervisor/arch/x86/cpu_caps.c func:init_pcpu_model_name offset:288<br> reason:Casting operation on a pointer. : (char* to unsigned int*): ( uint32_t * ) ( & boot_cpu_data.model_name [ 36 ] )<br><27> config:common filename:/hypervisor/arch/x86/cpu_caps.c func:init_pcpu_model_name offset:288<br> reason:Casting operation on a pointer. : (char* to unsigned int*): ( uint32_t * ) ( & boot_cpu_data.model_name [ 44 ] )<br><28> config:sharing_config filename:/hypervisor/arch/x86/cpu_state_tbl.c func:load_pcpu_state_data offset:134<br> reason:No prototype for non-static function. : load_pcpu_state_data<br><29> config:part_config filename:/hypervisor/arch/x86/cpu_state_tbl.c func:load_pcpu_state_data offset:134<br> reason:No prototype for non-static function. : load_pcpu_state_data<br><30> config:sharing_config filename:/hypervisor/arch/x86/cpu_state_tbl.c func:load_pcpu_state_data offset:142<br> reason:Pointer not checked for null before use. : cpu_info<br><31> config:part_config filename:/hypervisor/arch/x86/cpu_state_tbl.c func:load_pcpu_state_data offset:142<br> reason:Pointer not checked for null before use. : cpu_info<br><32> config:common filename:/hypervisor/arch/x86/cpu.c func:init_pcpu_pre offset:114<br> reason:Cast from pointer to integral type. : (unsigned char* to unsigned int): ( size_t ) ( & ld_bss_end - & ld_bss_start )<br><33> config:common filename:/hypervisor/arch/x86/cpu.c func:init_pcpu_pre offset:132<br> reason:Unreachable Code found.<br><34> config:part_config filename:/hypervisor/arch/x86/cpu.c func:init_pcpu_pre offset:132<br> reason:Potentially infinite loop found.<br>.....<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by KaigeFu** [comment]
@HuiHuangShi Suppression table updated and mailed to you.

**Pull request merged**
