### PR TITLE
Use Docker for building ACRN

### PR DESCRIPTION
**Pull request by shrmrf**
Hello projectacrn team,

As @gvancuts suggested in the other pull request, I created an example `Dockerfile` and associated `.travis.yml` script.

The [build is running fine](https://travis-ci.org/shrmrf/acrn-hypervisor) for me.

### CODE REVIEW

**Comment by gvancuts** [comment]
Thanks @shrmrf ! This builds ACRN in an Ubuntu environment (unless I've missed something). Do you know if it's possible to do the same using a Clearlinux-based container?

My initial idea was to have a collections of containers, each based on a different OS so we could easily test compiling the acrn-hypervisor and acrn-devicemodel in each of them (with Clearlinux being the most important one) - see my repo here for some more clues on what I had in mind: https://github.com/gvancuts/acrn-dockerfiles

Thanks!

**Comment by shrmrf** [comment]
Yes, I think it shouldn't be a problem. 

Instead of `FROM ubuntu:16.04`, we can use `clearlinux` and use `swupd` to add the `build-essential` bundle instead of `apt`.

I explicitly download (`git clone`) the repo inside the docker container (something we can decide whether it's good/bad/ugly).

Using `docker-compose` we can build all of the `Dockerfile`s in your repo. But I would suggest a process that terminates instead of going into the shell. Should I modify my `.travis.yml` it to use Clearlinux? 

I don't know if you'd agree, instead of using different OSs, why not fix the environment, compiler version etc.? We could then inherit from different `gcc` [containers](https://hub.docker.com/_/gcc/) and test building with them. E.g. the DM is currently failing (tested yesterday) with GCC 7.

**Comment by shrmrf** [comment]
Hey @gvancuts I'm trying to test the `clearlinux:base` container on my machine. I couldn't find a good bundle alternative to `build-essential` on Ubuntu. 

I started a build on Travis for my `Dockerfile`: https://travis-ci.org/shrmrf/acrn-hypervisor/branches

I had to do an ugly hook for ignoring ca-certs. I'm not very familiar with Clearlinux unfortunately. But I don't like the version independence they've given to package managers. For instance, `gcc` is version 7

```bash
root@acf35ecf4e7b / # gcc --version
gcc (Clear Linux OS for Intel Architecture) 7.3.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by shrmrf** [comment]
>I'm not entirely following your proposal (esp. the part about inheriting from different gcc containers), can you expand some more?

What I meant was that instead of going horizontal with OSs, we could fix the OS (e.g. to Ubuntu) and fix the versions of GCC (e.g. 5.x, or 7.x). 

In fact, I think we should lock the versions of all dependencies as much as possible in my opinion. This way, we won't have to stretch ourselves across all OSs. On any linux system, if someone installs the correct versions of dependencies, he should be able to build successfully.

>As long as you're able to download the stuff you want to test (i.e. a Pull Request, tag, release, ecc.), that should work. When exactly are you cloning the repo? Do you already know at that point what is the branch/tag/PR you want to test?
Pull requests are tested automagically by Travis, and so is each branch. The ugly thing about my `Dockerfile` is that I'm always pulling the `master` branch at the moment. A better approach (I realize now, thanks to your comment above` is to copy the contents of the current directory inside the docker container somewhere. 

I can submit a fix if you'd like.

**Comment by jren1** [comment]
@gvancuts Could you please re-visit that patch?

**Comment by shrmrf** [comment]
Hi @jren1 

Do you have the priviledges to enable issues and add external CI systems on the repo as well?

**Comment by nwang-intel** [comment]
@shrmrf, the 2 files(yml and Dockerfile) that are going to be merged points to your own repository, I think it could be better to make it connect to this repository right？

**Comment by mwang106** [comment]
@shrmrf thanks for your contribution,  we will try to use your dockerfile to build hypervisor & dm, and then to confirm if images built by your dockerfile can bring clearlinux sos successfully on APL NUC.

**Comment by terryzouhao** [comment]
Hi @shrmrf, we are trying to follow your "Dockerfile" to build, both from Ubuntu and Clear Linux environment. and verify boot on "Intel Apollo Lake NUC" platform, keep you updated with the result.  BTW, bug system and CI system are all powerful tool to improve efficiency, should be, or already in priority list :) @jren1

**Comment by mwang106** [comment]
@shrmrf I have already tried to use your Dockfile to build hypervisor, one place needs to modify, 'make all' should be make PLATFORM=uefi. After this change, built acrn.efi successfully, will try use it to verify boot.

**Comment by shrmrf** [comment]
Hi @mwang106 @nwang-intel  and @terryzouhao 

Thanks guys for your comments. I'm sorry, I was away for the past few days. 

>@shrmrf, the 2 files(yml and Dockerfile) that are going to be merged points to your own repository, I think it could be better to make it connect to this repository right？

Well, if it gets merged, then this repo will own it. It'll be a part of the official repo then (we can possibly delete my fork). The fork is meant for me to independently test out everything and submit a pull request. I just have everything enabled so that we can take a look at how everything might appear before we commit to the official repository at which point, it's probably more difficult to changing.

>@shrmrf Really interested about your patch, from your travis history and mentioned above, docker build for hypervisor&dm on ubuntu and clearlinux both successfully, have your tried to use them to boot clearlinux sos on any hardware platform, e.g. Intel Apollo Lake NUC?

I haven't tried to boot them. I would be really interested but unfortunately, I don't have an APL NUC at home or at work. But it should work in any case. I'm not sure if 

>Hi @shrmrf, we are trying to follow your "Dockerfile" to build, both from Ubuntu and Clear Linux environment. and verify boot on "Intel Apollo Lake NUC" platform, keep you updated with the result. BTW, bug system and CI system are all powerful tool to improve efficiency, should be, or already in priority list :) @jren1

Coool! I'm more of a fan of Ubuntu (or even other traditional linux distros) because, then we can control the exact version of all dependencies (GCC etc.). With Clear, it's not very clear to me how I can control versions of GCC and other tools. This might be a concern later IMO.


>@shrmrf I have already tried to use your Dockfile to build hypervisor, one place needs to modify, 'make all' should be make PLATFORM=uefi. After this change, built acrn.efi successfully, will try use it to verify boot.

Just did the modification before I started writing the message here... [Seems to pass](https://travis-ci.org/shrmrf/acrn-hypervisor)

**Comment by shrmrf** [comment]
@nwang-intel some artifacts from my version may require cleanup (e.g.):-

https://github.com/shrmrf/acrn-hypervisor/blob/master/Dockerfile#L3

When someone from within the core team wants to take over, they can give me their username and we can put it there or completely remove the `MAINTAINER` macro altogether. 

Also, this is a really simple example meant for CI. I think we can drastically improve on this so that it becomes useful to developers who want to build ACRN on their dev machines (i.e. doing the build and spitting the output on the dev's machine.) This shouldn't be too hard to set up and a simple linux alias can hide all the `docker` cli intricacies.

**Comment by jren1** [comment]
@shrmrf Thank you for great contribution!
@nwang-intel We need a CI system to help us to make sure our code can be built successfully in the different host Linux distributions. I intend to merge this patch, and we can improve it continuously later.

**Comment by jren1** [comment]
@shrmrf can you please rebase your patch and resolve the conflicts?

**Comment by NanlinXie** [comment]
@shrmrf I have tried the latest Dockfile to build hypervisor, built acrn.efi successfully and verified boot on "Intel Apollo Lake NUC" platform successfully.

**Comment by shrmrf** [comment]
Hi @jren1 

I'll resolve the conflicts and update my fork. Please give me until tonight as I'm at work at the moment.

**Comment by gvancuts** [comment]
Thanks a lot for all your work on this @shrmrf !

I don't recall if @jren1 can do this when merging this PR but it would be better to squash all this commits into a single one. We would also need you to add a `Signed-off-by` to your commit(s) (as per https://projectacrn.github.io/contribute.html#developer-certification-of-origin-dco).

Thanks!

**Comment by shrmrf** [comment]
I think @jren1 should have this option of squashing all the commits ... ideally, I should've worked in a branch and merged (squashed) commits into my fork's master.

How can I add a "Signed-off-by" to my commits now?

**Comment by jren1** [comment]
@shrmrf  Yes, I can squash and merge, but it is better to squash by yourself. You can use your github email address as your signed-off-by.

**Comment by shrmrf** [comment]
@jren1 I'll do it from home... after work :)

**Comment by gvancuts** [comment]
I got a little too excited by your work @shrmrf :-) ... so I started experimenting a little further as what I wanted to be able to do are a couple of things:
1. Test compilation for all combinations of variables (`RELEASE` and `PLATFORM`)
2. Test compilation for different host OS (using containers based on different `FROM` baselines)

You can take a look at what I did today on my repo: https://github.com/gvancuts/acrn-hypervisor/commit/e282fddb2e3d5ea196ab32426cda7e8b21fbdea8

Here are the build test results for the current master branch: [Build Status](https://travis-ci.org/gvancuts/acrn-hypervisor)

Just as a test case, I applied the same on top of an old commit for which I knew the `RELEASE=1` and `PLATFORM=uefi` combination failed to build... here are the build results: [Build Status](https://travis-ci.org/gvancuts/acrn-hypervisor) (you can see by clicking on the link that only one of the four combination fails to build).

**Note:** I am only enabling Clearlinux at the moment (as it's the least "naturally" tested although it's critical for our complete integration). We can easily add more OS to the list by updating the `./.travis.yml` file and leveraging any of the predefined Dockerfile in the `.travis-dockerfiles` folder.

**Note2:** a very similar mechanism can be used for the [ACRN Device Model](https://github.com/projectacrn/acrn-devicemodel) (and both can easily be combined should these repositories be combined at some point)

**Comment by shrmrf** [comment]
@gvancuts actually, this looks beautiful. This is exactly what I was going to do tonight. 

I also had a suggestion for developers' machines. I will try to formulate my idea into text later once I've resolved conflicts, and squashed commits and added the "signed-off" thingies tonight..

I think it was a mistake from my side to suggest merge directly into `master`. Should've created a [feature branch](https://www.atlassian.com/git/tutorials/comparing-workflows/feature-branch-workflow) as it migh've been less noisy 👎

**Comment by gvancuts** [comment]
Hi @shrmrf , I was just checking out your PR but there are now 104 commits that appear as part of it. I don't mean to be condescending but if you'd like a few steps to help you clean up all these, here is how you can proceed:
```
$ git checkout <your own master branch>
$ git fetch origin/master # this is assuming that origin points at github.com/projectacrn/acrn-hypervisor. If you use a different remote name for this, adjust this line.
$ dos2unix Dockerfile # I noticed this file is in the Dos text file format
# Edit the .travis.yml file to get rid of the extra space on the line preceding the "scripts:" line
$ git diff origin/master > ../my-travis.patch
$ git reset --hard origin/master # this is will reset your own master branch to the exact same level as the target repo
$ git apply ../my-travis.patch
$ git commit -a -s # the '-s' will add the "Signed-off-by" line, make sure your email address is correctly set
$ git push -f <name-of-the-remote-pointing-at-your-forked-version> +master:master # you could also do "git push -f https://github.com/shrmrf/acrn-hypervisor +master:master
```
 
If everything went according to (my) plan, this PR (#52) should now show just a single commit with the exact same changes you are proposing. If you wish to take some of my changes in this PR at the same time, I can help you get these in (and we can use two "Signed-off-by" lines to both get credit for it).

**Comment by shrmrf** [comment]
@jren1 I looked at rebasing and squashing some of my commits but it seems that I get a lot of empty commit message and unresolved conflict messages. I do not want to rebase and break something on the official repo. 

I'm afraid of breaking stuff here.

**Comment by shrmrf** [comment]
Hi @gvancuts thanks for your suggestion. I did apply it. I think the problem is that I've been merging into my fork from this repo occasionally.

**Comment by gvancuts** [comment]
This added yet another commit. What are the various remotes that are set-up on your machine (`git remote -v`)? If you give me that output, I can most likely give you a sequence of commands to get this fixed up.

**Comment by shrmrf** [comment]
Hi @gvancuts yes. It has in fact created yet another commit. Can we take a look at how we can fix this in an issue (https://github.com/shrmrf/acrn-hypervisor/issues/5)

I also added you as a collaborator to my fork. Perhaps you can take a look directly?

**Comment by shrmrf** [comment]
@jren1 thanks to @gvancuts .. he helped me fix the issues with my repo.

**Pull request merged**
