### PR TITLE
hv mutli-function device passthru fixes

### PR DESCRIPTION
**Pull request by zhangqiang4**
When function 0 in a multi-function PCI device is passthru to Pre-launched VM
or owned by the hypervisor, a dummy function 0 should be emulated for Service
VM if the other functions are left to Service VM.

We met this case on a platform whose LPSS device contains a PCI serial port at
function 0 together with several I2C functions.

The first patch improves the PCI device config initialization logic as
discussed in [1].
The second patch add the dummy multi-function device support.

[1] https://lists.projectacrn.org/g/acrn-dev/message/37656

### CODE REVIEW

**Review by junjiemao1 — APPROVED** [review]

**Review by NanlinXie — APPROVED** [review]
Approved for configtool part

**Comment by wenlingz** [comment]
start to run premerge test

**Comment by wenlingz** [comment]
start to run premerge test

**Comment by wenlingz** [comment]
start to run premerge test

**Comment by wenlingz** [comment]
start to run premerge test

**Comment by wenlingz** [comment]
start to run premerge test

**Comment by zhangqiang4** [comment]
Fail to launch pre-launched vm in partitioned scenario. Will resend this patch set after fix and review.

**Pull request merged**
