### PR TITLE
hv: improve multiboot guest image load addresses assignment

### PR DESCRIPTION
**Pull request by ZideChen0**
Purpose of these two patches:

1) fix issues on assigning bootargs_load_addr so it's possible to boot pre-launched VMs at > 4GB address, and safer for SOS.
2) make ramdisk input available for pre-launched VMs.
3) Fix ramdisk_load_addr assignment issue
4) remove duplicated init_vm_boot_info()

### CODE REVIEW

**Comment by HuiHuangShi** [comment]
27 new potential violations to the coding guideline detected. Please help check. Thanks!<br><1> config:common filename:/hypervisor/boot/sbl/multiboot.c offset:33 ruleid:91D<br> reason:Function return value potentially unused. : mod_addr<br><2> config:common filename:/hypervisor/boot/sbl/multiboot.c offset:58 ruleid:45D<br> reason:Pointer not checked for null before use. : mod_addr<br><3> config:common filename:/hypervisor/boot/sbl/multiboot.c offset:64 ruleid:95S<br> reason:Casting operation to a pointer. : (Unknown_Type to char*): ( const char * ) vm -> sw.linux_info.bootargs_src_addr<br><4> config:common filename:/hypervisor/boot/sbl/multiboot.c offset:64 ruleid:458S<br> reason:Implicit conversion: actual to formal param (MR). :  (struct acrn_vm and unsigned int):  param  4<br><5> config:common filename:/hypervisor/boot/sbl/multiboot.c offset:70 ruleid:45D<br> reason:Pointer not checked for null before use. : load_addr<br><6> config:common filename:/hypervisor/boot/sbl/multiboot.c offset:77 ruleid:440S<br> reason:Cast from integral type to pointer. : (unsigned long to void*): ( void * ) round_page_up ( ( uint64_t ) vm -> sw.linux_info.ramdisk_load_addr )<br><7> config:common filename:/hypervisor/boot/sbl/multiboot.c offset:97 ruleid:95S<br> reason:Casting operation to a pointer. : (void* to struct zero_page*): ( struct zero_page * ) kernel_src_addr<br><8> config:common filename:/hypervisor/boot/sbl/multiboot.c offset:97 ruleid:94S<br> reason:Casting operation on a pointer. : (void* to struct zero_page*): ( struct zero_page * ) kernel_src_addr<br><9> config:common filename:/hypervisor/boot/sbl/multiboot.c offset:99 ruleid:95S<br> reason:Casting operation to a pointer. : (Unknown_Type to struct zero_page*): ( struct zero_page * ) zeropage -> hdr.pref_addr<br><10> config:common filename:/hypervisor/boot/sbl/multiboot.c offset:121 ruleid:1J<br> reason:Unreachable Code found.<br><11> config:common filename:/hypervisor/boot/sbl/multiboot.c offset:121 ruleid:28D<br> reason:Potentially infinite loop found.<br><12> config:common filename:/hypervisor/boot/sbl/multiboot.c offset:123 ruleid:95S<br> reason:Casting operation to a pointer. : (void* to struct multiboot_info*): ( struct multiboot_info * ) hpa2hva ( ( uint64_t ) boot_regs [ 1 ] )<br><13> config:common filename:/hypervisor/boot/sbl/multiboot.c offset:123 ruleid:94S<br> reason:Casting operation on a pointer. : (void* to struct multiboot_info*): ( struct multiboot_info * ) hpa2hva ( ( uint64_t ) boot_regs [ 1 ] )<br><14> config:common filename:/hypervisor/boot/sbl/multiboot.c offset:129 ruleid:1J<br> reason:Unreachable Code found.<br><15> config:common filename:/hypervisor/boot/sbl/multiboot.c offset:129 ruleid:28D<br> reason:Potentially infinite loop found.<br><16> config:common filename:/hypervisor/boot/sbl/multiboot.c offset:136 ruleid:95S<br> reason:Casting operation to a pointer. : (void* to struct multiboot_module*): ( struct multiboot_module * ) hpa2hva ( ( uint64_t ) mbi -> mi_mods_addr )<br><17> config:common filename:/hypervisor/boot/sbl/multiboot.c offset:136 ruleid:94S<br> reason:Casting operation on a pointer. : (void* to struct multiboot_module*): ( struct multiboot_module * ) hpa2hva ( ( uint64_t ) mbi -> mi_mods_addr )<br><18> config:common filename:/hypervisor/boot/sbl/multiboot.c offset:140 ruleid:440S<br> reason:Cast from integral type to pointer. : (unsigned long to char*)<br><19> config:common filename:/hypervisor/boot/sbl/multiboot.c offset:149 ruleid:45D<br> reason:Pointer not checked for null before use. : vm_config<br><20> config:common filename:/hypervisor/boot/sbl/multiboot.c offset:149 ruleid:433S<br> reason:Type conversion without cast. :  (unsigned int and enum acrn_vm_type): vm_config -> type == PRE_LAUNCHED_VM<br><21> config:common filename:/hypervisor/boot/sbl/multiboot.c offset:150 ruleid:440S<br> reason:Cast from integral type to pointer. : (unsigned short to void*): ( void * ) ( ( 1024U * 1024U ) * 16U )<br><22> config:common filename:/hypervisor/boot/sbl/multiboot.c offset:155 ruleid:440S<br> reason:Cast from integral type to pointer. : (unsigned long to void*): ( void * ) hva2gpa ( vm , get_kernel_load_addr ( vm -> sw.kernel_info.kernel_src_addr ) )<br><23> config:common filename:/hypervisor/boot/sbl/multiboot.c offset:156 ruleid:458S<br> reason:Implicit conversion: actual to formal param (MR). :  (int and void):  param  1<br><24> config:common filename:/hypervisor/boot/sbl/multiboot.c offset:179 ruleid:401S<br> reason:Use of sizeof on an array parameter.<br><25> config:common filename:/hypervisor/boot/sbl/multiboot.c offset:193 ruleid:330S<br> reason:Implicit conversion of underlying type (MR). :  (unsigned short and unsigned int): off = strnlen_s ( cmd_dst , ( 1024U * 2U ) - off<br><26> config:common filename:/hypervisor/boot/sbl/multiboot.c offset:193 ruleid:96S<br> reason:Use of mixed mode arithmetic. :  (unsigned short and unsigned int): off = strnlen_s ( cmd_dst , ( 1024U * 2U ) - off<br><27> config:common filename:/hypervisor/boot/sbl/multiboot.c offset:199 ruleid:45D<br> reason:Pointer not checked for null before use. : cmd_src<br><br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by acrnsi** [comment]
OK to verify

**Comment by HuiHuangShi** [comment]
10 new potential violations to the coding guideline detected. Please help check. Thanks!<br><1> config:common filename:/hypervisor/boot/sbl/multiboot.c offset:33<br> reason:Function return value potentially unused. : mod_addr<br><2> config:common filename:/hypervisor/boot/sbl/multiboot.c offset:58<br> reason:Pointer not checked for null before use. : mod_addr<br><3> config:common filename:/hypervisor/boot/sbl/multiboot.c offset:70<br> reason:Pointer not checked for null before use. : load_addr<br><4> config:common filename:/hypervisor/boot/sbl/multiboot.c offset:77<br> reason:Cast from integral type to pointer. : (unsigned long to void*): ( void * ) round_page_up ( ( uint64_t ) vm -> sw.linux_info.ramdisk_load_addr )<br><5> config:common filename:/hypervisor/boot/sbl/multiboot.c offset:121<br> reason:Potentially infinite loop found.<br><6> config:common filename:/hypervisor/boot/sbl/multiboot.c offset:129<br> reason:Potentially infinite loop found.<br><7> config:common filename:/hypervisor/boot/sbl/multiboot.c offset:149<br> reason:Pointer not checked for null before use. : vm_config<br><8> config:common filename:/hypervisor/boot/sbl/multiboot.c offset:149<br> reason:Type conversion without cast. :  (unsigned int and enum acrn_vm_type): vm_config -> type == PRE_LAUNCHED_VM<br><9> config:common filename:/hypervisor/boot/sbl/multiboot.c offset:150<br> reason:Cast from integral type to pointer. : (unsigned short to void*): ( void * ) ( ( 1024U * 1024U ) * 16U )<br><10> config:common filename:/hypervisor/boot/sbl/multiboot.c offset:199<br> reason:Pointer not checked for null before use. : cmd_src<br><br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by HuiHuangShi** [comment]
> 10 new potential violations to the coding guideline detected. Please help check. Thanks!
> <1> config:common filename:/hypervisor/boot/sbl/multiboot.c offset:33
> reason:Function return value potentially unused. : mod_addr
> <2> config:common filename:/hypervisor/boot/sbl/multiboot.c offset:58
> reason:Pointer not checked for null before use. : mod_addr
> <3> config:common filename:/hypervisor/boot/sbl/multiboot.c offset:70
> reason:Pointer not checked for null before use. : load_addr
> <4> config:common filename:/hypervisor/boot/sbl/multiboot.c offset:77
> reason:Cast from integral type to pointer. : (unsigned long to void*): ( void * ) round_page_up ( ( uint64_t ) vm -> sw.linux_info.ramdisk_load_addr )
> <5> config:common filename:/hypervisor/boot/sbl/multiboot.c offset:121
> reason:Potentially infinite loop found.
> <6> config:common filename:/hypervisor/boot/sbl/multiboot.c offset:129
> reason:Potentially infinite loop found.
> <7> config:common filename:/hypervisor/boot/sbl/multiboot.c offset:149
> reason:Pointer not checked for null before use. : vm_config
> <8> config:common filename:/hypervisor/boot/sbl/multiboot.c offset:149
> reason:Type conversion without cast. : (unsigned int and enum acrn_vm_type): vm_config -> type == PRE_LAUNCHED_VM
> <9> config:common filename:/hypervisor/boot/sbl/multiboot.c offset:150
> reason:Cast from integral type to pointer. : (unsigned short to void*): ( void * ) ( ( 1024U * 1024U ) * 16U )
> <10> config:common filename:/hypervisor/boot/sbl/multiboot.c offset:199
> reason:Pointer not checked for null before use. : cmd_src
> 
> No New Name Conflict
> 
> No New Function Declaration/Definition Mismatch

All of above is false positive

**Pull request merged**
