### PR TITLE
support vm event

### PR DESCRIPTION
**Pull request by izhouwu**
VM events refers to certain events that are generated by VMs and needs
to be handled by use-case specifically, such as:
- VM RTC change -> Whether to update physical RTC.
- VM reset -> VM reset only, or system reset.
- VM crash -> Logging and populating diagnostics
The idea of ACRN VM events is to generate those events in HV or DM, and
send them into DM’s event deliver logic through sbuf ring. Leveraging
DM’s monitor socket connected to Libvirt, those events are then emitted
to Libvirt’s infrastructure. Developers can write scripts/APPs using
Libvirt’s API to process those events.

The architecture is like this:
 +------------------------------------------------------+
 |    Service VM                                        |
 | +----------------------------+                       |
 | | DM  +--------------------+ |                       |
 | |     | [ event source ]   | |                       |
 | |     +-+------------+-----+ |                       |
 | |       | (eventfd)  |(sbuf) |                       |
 | |       v            v       |                       |
 | | +------------------------+ | (socket)  +---------+ |
 | | |  [event deliver logic] |-+---------->| Libvirt | |
 | | +------------------------+ |           +---------+ |
 | |       ^            ^       |                       |
 | +-------|------------|-------+                       |
 |         | (eventfd)  | (sbuf)                        |
 +---------|------------|-------------------------------+
 +---------|------------|-------------------------------+
 | kernel [HSM]         |                               |
 |         ^            |                               |
 +---------|------------|-------------------------------+
           |upcall      |
 +---------+------------+-------------------------------+
 | HV     [ event source ]                              |
 +------------------------------------------------------+

For event sources in HV
- HV puts the event in the shared ring.
- The hypervisor notifies the service VM via upcall.
- HSM in the service VM notifies device model via eventfd.
- The device model fetches and handles events from the shared ring.
For event sources in DM
- DM puts the event in the DM event ring.
- DM notifies event delivery logic via eventfd.
- The event delivery logic fetches and handles events from the DM event
  ring.
The DM event delivery logic is hosted in a separate thread.

### CODE REVIEW

**Comment by junjiemao1** [comment]
Please check the build and code scanning failures.

**Comment by Kunhui-Li** [comment]
start to run premerge test

**Review by junjiemao1 — APPROVED** [review]
LGTM. Thanks.

**Review by chejianj — APPROVED** [review]
LGTM

**Pull request merged**
