### PR TITLE
add release notes for v0.1 release

### PR DESCRIPTION
**Pull request by ailun258**
this is the release notes for v0.1,   will add a link to attach change log for people review detail

### CODE REVIEW

**Comment by NanlinXie** [comment]
Can one of the admins verify this patch?

**Comment by hwang37** [comment]
@ailun258 Do you want to give one sentence description for each new feature?

**Comment by ailun258** [comment]
for release note, i don't have plan to describe each feature, but i have plan to create a documentation to list  all  features the ACRN supported, in there, we can have description for each feature,  what's you thought?

**Comment by hwang37** [comment]
@ailun258 Please remove "pre-emption" in this release notes.

**Comment by ailun258** [comment]
okay

**Comment by dbkinder** [comment]
@ailun258 These release notes are not in a reST file format. The section the hypervisor commands should just be a reference to the existing document with these commands. To expedite things, I'm going to merge this as-is and submit a new PR formatting it as a reST file and removing the command references, but you need to be submitting formatted reST content in the future.

**Pull request merged**
