### PR TITLE
misc: life_mngr: add a separate config to allow trigger sysreboot

### PR DESCRIPTION
**Pull request by lifeix**
add a separate config to allow trigger sysreboot

Tracked-On: #7215
Signed-off-by: Fei Li <fei1.li@intel.com>

### CODE REVIEW

**Comment by acrnsi** [comment]
Can one of the admins verify this patch?

**Comment by lifeix** [comment]
@dbkinder @wuxyintel  Please help to review. Thanks

**Comment by wuxyintel** [comment]
> @dbkinder @wuxyintel Please help to review. Thanks

@lifeix Thanks for your patch, I am fine about this, may need to update document to let user aware this new config item since the lifecycle manager config file is updated. Please double check it, thanks!

**Comment by wenlingz** [comment]
@ywan170 please help approve this PR, thanks

**Review by ywan170 — APPROVED** [review]

**Pull request merged**
