### PR TITLE
Porting patches from master to apl_sdc_stable

### PR DESCRIPTION
**Pull request by liuwei987**
Porting patches from master to apl_sdc_stable
Patch list:
9bbd6271e5552b255fefbe62a78e817f52a02f69 dm: flush the input/output during tty open.
4f0dc107424b3841b09937bec8e288353e9accdb hv: vcpuid: remove unnecessary check code
d4e2a79db8e4669db198a28adf0e2ef4d166ec11 hv: vcpuid: leaf 02h has no subleaf, delete un-needed code.
faa0e195d7a5c71f1959456522b1850e12b752d4 dm: virtio: refine header file
a298e6a372d62f698b371a107058f425c97c33d3 hv: coding style: refine set_vcpuid_entries to one exit
4c81c2f6f872e92dfd121c13cc2bdb714336c5a9 dm: pass mac seed not to use vm name on UP2
2c6a8950c293b76f67839a1caf6fbdd9f2055936 Debug: Add one hypercall to quary hardware info
c57861fffe49be696c5440a76c0bedaa928e16db hv: fix enable_msr_interception() function
9e37005fb5a25dbf842227011bd038d96a389c5c HV/DM: Unify the usage of aligned for structure definition with alignment
0f9c2dd05b2a0453411fe303a4a06a92366fb38c hv: assign: change ptirq vpin source type from enum to macro
0ec6d66071e8b1e42299966a40e2eb5cd3d231f6 hv: assign: remove added ptirq entries if fails to add all
f8e9b71a8ca58edf7da36088576958fb46769987 hv: assign: fix MISRA-C violations on multiple exits
15d87c9dc6161061cc1cbeee6afc3e56a1b6d0a3 HV: fix bug adapt uart mmio to bdf for HV cmdline
149449e571057c575de89e75a859b94ac60a759c HV: change serial PCI cfg to bus:dev.func format
775d1c347562aec33f23ff2421f541ba9fe25b1e dm: passthru: add error handling if msix table init failed
7cf057a1de47f30b5e2bcd79d95d1138dce9b1ce dm: passthru: msi/msix handling revisit
62cf55909e07b84513468dadfab41dbba5245938 hv: refine memcpy_s
40cb14b6c4dc384befdc017ede9dadeff2fb80e9 hv: refine memset
e2326a8e194c311addf77ad78e9e9b49674c0e23 hv: add fast string enhanced rep movsb/stosb check on initial
db5e48dd476fbaa2dd469dcc051679ccb423c122 hv: enable/disable snoop control bit per vm

Tracked-On: #2173

### CODE REVIEW

**Comment by dongyaozu** [comment]
@fyin1

**Comment by Mingyuan18** [comment]
@liuwei987 Please add Tracked On ID in Conversation

**Comment by liuwei987** [comment]
> @liuwei987 Please add Tracked On ID in Conversation

Done!

**Comment by wenlingz** [comment]
@liuwei987 DM USB: xHCI: change log level of some logs for S3 online debugging this patch has merged, please fix your PR,thanks

**Pull request merged**
