### PR TITLE
tools: remove libtelemetry code from crashlog

### PR DESCRIPTION
**Pull request by gvancuts**
Remove the code that deals with the libtelemetry API and infrastructure.
Libtelemetry is used in Clear Linux only and not available (out of the
box) on Ubuntu or Yocto (which we use in our reference stack).

Tracked-On: #5653
Signed-off-by: Geoffroy Van Cutsem <geoffroy.vancutsem@intel.com>

### CODE REVIEW

**Comment by ionutnechita** [comment]
https://github.com/projectacrn/acrn-hypervisor/issues/5653#issuecomment-766095411

**Comment by HuiHuangShi** [comment]
No new violations to the coding guideline detected.<br>No New Name Conflict<br>No New Function Declaration/Definition Mismatch

**Comment by wenlingz** [comment]
@NanlinXie please help approve this PR, thanks

**Comment by wenlingz** [comment]
@gvancuts please rebase your code, thanks

**Comment by gvancuts** [comment]
> @gvancuts please rebase your code, thanks

Done.

I also would like to get the blessing of @ionutnechita before we merge this. @ionutnechita , please let us know if you are against this removal!

**Comment by ionutnechita** [comment]
Hi @gvancuts,

For me this change does not bother me, I just wanted to announce that this option is optional.
Yes, we can let it go to change. It's fine for merge.

**Review by NanlinXie — APPROVED** [review]

**Pull request merged**
