### PR TITLE
samples: remove extra option for dm

### PR DESCRIPTION
**Pull request by liuwei987**
remove extra "-l com1,stdio" option for dm

Tracked-On: #1123
Signed-off-by: Wei Liu <weix.w.liu@intel.com>
Reviewed-by: Jason Chen CJ <jason.cj.chen@intel.com>

### CODE REVIEW

**Comment by wenlingz** [comment]
Verified+1

**Comment by ttzeng** [comment]
@liuwei987 could you also cook a patch for NUC as well? Thanks.

**Comment by liuwei987** [comment]
@ttzeng  There is no duplicate for this option. No need to do that.

**Comment by ttzeng** [comment]
@liuwei987 thanks for the clarification.

**Pull request merged**
