### PR TITLE
Acrn config launch

### PR DESCRIPTION
**Pull request by liuwei987**
acrn-config: add launch sample xmls for acrn-config
    
    add launch sample xmls for acrn-config to generate launch scripts.
    
    launch script will generated by acrn-config/launch_config tool,
    acrn-config/launch_config need launch config xml as input.
    
    Tracked-On: #3602
    Signed-off-by: Victor Sun <victor.sun@intel.com>
    Acked-by: Terry Zou <terry.zou@intel.com>

    acrn-config: generate launch script file and apply to the souce file
    
    1. generate launch script file and apply to the source file
    
    usage: launch_cfg_gen.py [h]--board <board_info_file> --scenario <scenario_info_file>
                    --launch <launch_info_file> --uosid <uosid id>
    board_info_file :  file name of the board info
    scenario_info_file :  file name of the scenario info
    launch_info_file :  file name of the launch info
    uosid :  the uos id which to launch:[0..max uos id]
    
    sample:
        $ python3 launch_cfg_gen.py --board ../xmls/board-xmls/apl-mrb.xml
          --scenario ../xmls/config-xmls/apl-mrb/sdc.xml
          --launch ../xmls/launch_config/mrb_launch.xml --uosid 0
    
    v1-v2:
        1). usage: '--vm' -> '--uosid'
        2). add 'uuid' option for acrn-dm
        3). support parse tag from 'rootfs' to 'rootfs_dev'
        4). support parse tag from 'hard_rtos' to 'Preempt-Rt Linux'
        5). support pasre tag from 'redirect_console' to 'console_type'
        6). add 'nvme' passthrough option
        7). modify uos_type to upper string in webUI
        8). support to generate launch file by uosid, this map to scenario
    id
    
    Tracked-On: #3602
    Signed-off-by: Wei Liu <weix.w.liu@intel.com>
    Acked-by: Terry Zou <terry.zou@intel.com>

    acrn-config: generate launch script file and apply to the souce file
    
    1. generate launch script file and apply to the source file
    
    usage: launch_cfg_gen.py [h]--board <board_info_file> --scenario <scenario_info_file>
                    --launch <launch_info_file> --uosid <uosid id>
    board_info_file :  file name of the board info
    scenario_info_file :  file name of the scenario info
    launch_info_file :  file name of the launch info
    uosid :  the uos id which to launch:[0..max uos id]
    
    sample:
        $ python3 launch_cfg_gen.py --board ../xmls/board-xmls/apl-mrb.xml
          --scenario ../xmls/config-xmls/apl-mrb/sdc.xml
          --launch ../xmls/launch_config/mrb_launch.xml --uosid 0
    
    v1-v2:
        1). usage: '--vm' -> '--uosid'
        2). add 'uuid' option for acrn-dm
        3). support parse tag from 'rootfs' to 'rootfs_dev'
        4). support parse tag from 'hard_rtos' to 'Preempt-Rt Linux'
        5). support pasre tag from 'redirect_console' to 'console_type'
        6). add 'nvme' passthrough option
        7). modify uos_type to upper string in webUI
        8). support to generate launch file by uosid, this map to scenario
    id
    
    Tracked-On: #3602
    Signed-off-by: Wei Liu <weix.w.liu@intel.com>
    Acked-by: Terry Zou <terry.zou@intel.com>

### CODE REVIEW

**Comment by wenlingz** [comment]
@binbinwu1 please help review this PR, thanks

**Comment by acrnsi** [comment]
OK to cerify

**Comment by acrnsi** [comment]
OK to verify

**Comment by acrnsi** [comment]
OK to verify

**Comment by HuiHuangShi** [comment]
No new violations to the coding guideline detected.<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Pull request merged**
