### PR TITLE
acrn-config: assign PCPU0~3 to post vm by default

### PR DESCRIPTION
**Pull request by liuwei987**
Assign PCPU0~3 to post-launched VM. The CPU affinity can be overridden with the
'--cpu_affinity' parameter of acrn-dm.
v1-v2:
  1) add 3 POST_STD_VM and 1 KATA_VM to industry scenario for whl-ipc/nuc7i7dnb.
 v2-v3:                                                                                                                                                                                                    
      1) remove the MAX_KATA_VM_NUM from scecnro config.                                                                                                                                                      
      2) add gvtd args for nuc7/nuc6 board. 
Tracked-On: #4641
Signed-off-by: Wei Liu <weix.w.liu@intel.com>
Acked-by: Victor Sun <victor.sun@intel.com>

### CODE REVIEW

**Comment by HuiHuangShi** [comment]
No new violations to the coding guideline detected.<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by HuiHuangShi** [comment]
No new violations to the coding guideline detected.<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by gvancuts** [comment]
Nit: can you fix the typos in your commit message:
```
Assign PCPU0~3 to post-launched VM. The CPU affinity can be overridden with the
'--cpu_affinity' parameter of acrn-dm.
```

**Comment by liuwei987** [comment]
> Nit: can you fix the typos in your commit message:
> 
> ```
> Assign PCPU0~3 to post-launched VM. The CPU affinity can be overridden with the
> '--cpu_affinity' parameter of acrn-dm.
> ```

OK, I will update them, thanks!

**Comment by HuiHuangShi** [comment]
No new violations to the coding guideline detected.<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by HuiHuangShi** [comment]
No new violations to the coding guideline detected.<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by HuiHuangShi** [comment]
No new violations to the coding guideline detected.<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Pull request merged**
