### PR TITLE
DM: Fix the security issues in the DM.

### PR DESCRIPTION
**Pull request by Ragnarliu**
Add the NULL pointer check in case there will have security issues.

Signed-off-by: Liu Long <long.liu@intel.com>
Tracked-On: #5514

### CODE REVIEW

**Comment by HuiHuangShi** [comment]
No new violations to the coding guideline detected.<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by HuiHuangShi** [comment]
No new violations to the coding guideline detected.<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by HuiHuangShi** [comment]
No new violations to the coding guideline detected.<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by wenlingz** [comment]
@fyin1 please help approve this PR, thanks

**Review by fyin1 — APPROVED** [review]

**Pull request merged**
