### PR TITLE
udelay waits for corresponding number of milliseconds passed to API.

### PR DESCRIPTION
**Pull request by sainath14**
Changed the CYCLES_PER_MS to US_TO_TICKS

Signed-off-by: Sainath Grandhi <sainath.grandhi@intel.com>

### CODE REVIEW

**Comment by NanlinXie** [comment]
Can one of the admins verify this patch?

**Comment by lijinxia** [comment]
OK to verify

**Comment by lijinxia** [comment]
OK to verify

**Comment by lijinxia** [comment]
Verified+1

**Pull request merged**
