### PR TITLE
Configs 1

### PR DESCRIPTION
**Pull request by jsun26intel**
HV: add new acrn_vm_config member and config files

    - add new struct member for acrn_vm_config;
    - add sharing_config.c file with initialized vm_config array;
    - add SOS VM config header for apl-mrb and dnv-cb2 board;
    - and partition_config.c file with dummy vm_config array;

Tracked-On: #2291 

Signed-off-by: Victor Sun <victor.sun@intel.com>
Acked-by: Eddie Dong <eddie.dong@intel.com>

### CODE REVIEW

**Comment by wenlingz** [comment]
@jsun26intel please add Tracked-On info on the conversation, and check your code, build fail

**Comment by HuiHuangShi** [comment]
2372<br>3 new potential violations to the coding guideline detected. Please help check. Thanks!  <br><br>1.filename:/hypervisor/arch/x86/guest/vm.c&nbsp;&nbsp;function:create_vm&nbsp;&nbsp;offset:64:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Pointer param should be declared pointer to const. : vm_config<br><br>2.filename:/hypervisor/arch/x86/configs/sharing_config.c&nbsp;&nbsp;function:None&nbsp;&nbsp;offset:10:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Variable should be declared static. : vm_configs<br><br>3.filename:/hypervisor/arch/x86/configs/sharing_config.c&nbsp;&nbsp;function:None&nbsp;&nbsp;offset:10:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Variable declared multiply.                  : vm_configs<br><br>

**Comment by HuiHuangShi** [comment]
2372<br>3 new potential violations to the coding guideline detected. Please help check. Thanks!  <br><br>1.filename:/hypervisor/arch/x86/guest/vm.c&nbsp;&nbsp;function:create_vm&nbsp;&nbsp;offset:64:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Pointer param should be declared pointer to const. : vm_config<br><br>2.filename:/hypervisor/arch/x86/configs/sharing_config.c&nbsp;&nbsp;function:None&nbsp;&nbsp;offset:10:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Variable should be declared static. : vm_configs<br><br>3.filename:/hypervisor/arch/x86/configs/sharing_config.c&nbsp;&nbsp;function:None&nbsp;&nbsp;offset:10:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Variable declared multiply.                  : vm_configs<br><br>

**Comment by HuiHuangShi** [comment]
1-3 are false positive

**Comment by HuiHuangShi** [comment]
2372<br>3 new potential violations to the coding guideline detected. Please help check. Thanks!  <br><br>1.filename:/hypervisor/arch/x86/guest/vm.c&nbsp;&nbsp;function:create_vm&nbsp;&nbsp;offset:64:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Pointer param should be declared pointer to const. : vm_config<br><br>2.filename:/hypervisor/arch/x86/configs/sharing_config.c&nbsp;&nbsp;function:None&nbsp;&nbsp;offset:10:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Variable should be declared static. : vm_configs<br><br>3.filename:/hypervisor/arch/x86/configs/sharing_config.c&nbsp;&nbsp;function:None&nbsp;&nbsp;offset:10:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Variable declared multiply.                  : vm_configs<br><br>

**Comment by HuiHuangShi** [comment]
2372<br>3 new potential violations to the coding guideline detected. Please help check. Thanks!  <br><br>1.filename:/hypervisor/arch/x86/guest/vm.c&nbsp;&nbsp;function:create_vm&nbsp;&nbsp;offset:64:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Pointer param should be declared pointer to const. : vm_config<br><br>2.filename:/hypervisor/arch/x86/configs/sharing_config.c&nbsp;&nbsp;function:None&nbsp;&nbsp;offset:10:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Variable should be declared static. : vm_configs<br><br>3.filename:/hypervisor/arch/x86/configs/sharing_config.c&nbsp;&nbsp;function:None&nbsp;&nbsp;offset:10:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Variable declared multiply.                  : vm_configs<br><br>

**Pull request merged**
