### PR TITLE
config_tools: remove board and scenario attribute

### PR DESCRIPTION
**Pull request by Kunhui-Li**
remove BOARD/SCENARIO attribute dependency for the new configuration.

To do:
will remove all BOARD/SCENARIO attributes in all scenario XML files
and update the upgrader.py after the new configuration works.

Tracked-On: #6690
Signed-off-by: Kunhui-Li <kunhuix.li@intel.com>
Reviewed-by: Junjie Mao <[junjie.mao@intel.com](mailto:junjie.mao@intel.com)>

### CODE REVIEW

**Comment by acrnsi** [comment]
Can one of the admins verify this patch?

**Review by NanlinXie — APPROVED** [review]

**Comment by GGGZZZRRR** [comment]
@Kunhui-Li please check these errors

All warnings:
/home/acrn/workspace/acrn-hypervisor-codescan-native_714/acrn-hypervisor/hypervisor/arch/x86/rtcm.c:11:10: error: 'misc_cfg.h' file not found [clang-diagnostic-error]
#include <misc_cfg.h>
         ^~~~~~~~~~~~
/home/acrn/workspace/acrn-hypervisor-codescan-native_714/acrn-hypervisor/hypervisor/boot/include/boot.h:12:10: error: 'vm_configurations.h' file not found [clang-diagnostic-error]
#include <vm_configurations.h>
         ^~~~~~~~~~~~~~~~~~~~~
/home/acrn/workspace/acrn-hypervisor-codescan-native_714/acrn-hypervisor/hypervisor/include/arch/x86/asm/board.h:13:10: error: 'misc_cfg.h' file not found [clang-diagnostic-error]
#include <misc_cfg.h>
         ^~~~~~~~~~~~

**Comment by szhen11** [comment]
start to run premerge test

**Review by lifeix — APPROVED** [review]

**Comment by GGGZZZRRR** [comment]
@Kunhui-Li please check acrn deb, after installing acrn deb, it generates "acrn....adl-s-crb.bin" under /boot

[ ERROR ] write: 
 and expect: ACRN:\\> failed with timeout: 30
[0m[30m[40m[2J[01;01H[0m[37m[40m[?25h[H[J[1;1H[H[J[1;1H[0m[30m[40m[2J[01;01H[0m[37m[40merror: file `/boot/acrn.shared.adl-s-crb.bin' not found.

error: file `/boot/acrn.shared.adl-s-crb.bin' not found.

error: you need to load the kernel first.

error: you need to load the kernel first.

**Pull request merged**
