### PR TITLE
DM: use sha512sum for all virtual bootloaders

### PR DESCRIPTION
**Pull request by gvancuts**
Use 'sha512sum' for all virtual bootloaders, i.e. vSLB and OVMF (release
and debug version). One can check the integrity of those files using:
$ cd devicemodel/bios
$ sha512sum -c SHA512SUM

Which will return (if everything is fine):
OVMF.fd: OK
OVMF_debug.fd: OK
VSBL.bin: OK
VSBL_debug.bin: OK

Tracked-On: #2870
Signed-off-by: Geoffroy Van Cutsem <geoffroy.vancutsem@intel.com>

### CODE REVIEW

**Comment by HuiHuangShi** [comment]
No new violations to the coding guideline detected.<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by gvancuts** [comment]
Why is there a ``CI: Tracked On error`` label attached to this PR?

**Comment by wenlingz** [comment]
> Why is there a `CI: Tracked On error` label attached to this PR?

You need add the bug info on the git issue, @Mingyuan18 , please help add the externak_ID, thanks

**Comment by wenlingz** [comment]
@dongyaozu please help approve it ,thanks

**Comment by gvancuts** [comment]
PR #2869 was merged which added `SHA512SUM` information for all virtual bootloaders. Closing this one.

**Pull request closed without merging**
