### PR TITLE
DM: update launch scripts to use OVMF.fd directly from the rootfs

### PR DESCRIPTION
**Pull request by gvancuts**
* Update the launch scripts provided as examples on how to launch a Zephyr,
VxWorks or Windows User VM to directly use the 'OVMF.fd' bios file installed
by default in '/usr/share/acrn/bios/'
* Remove the OVMF.fd that was kept under 'doc/tutorials' (no longer needed)
* Adapt the tutorials to reflect this change

Signed-off-by: Geoffroy Van Cutsem <geoffroy.vancutsem@intel.com>

### CODE REVIEW

**Comment by HuiHuangShi** [comment]
No new violations to the coding guideline detected.<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by wenlingz** [comment]
@gvancuts please add Tracked-On, thanks

**Comment by wenlingz** [comment]
@gvancuts you also can use #3673 as this PR's Tracked-On,thanks

**Comment by gvancuts** [comment]
> @gvancuts you also can use #3673 as this PR's Tracked-On,thanks

Done, thanks @wenlingz

**Comment by HuiHuangShi** [comment]
No new violations to the coding guideline detected.<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Pull request merged**
