### PR TITLE
config_tools: clean up board folders under data directory

### PR DESCRIPTION
**Pull request by Kunhui-Li**
1. move tgl-rvp and ehl-crb-b folders under data directory to 1source.
2. delete nuc7i7dnb and whl-ipc-i7 folders under data directory.

Tracked-On: #6315
Signed-off-by: Kunhui-Li <kunhuix.li@intel.com>

### CODE REVIEW

**Review by dbkinder — CHANGES_REQUESTED** [review]
What are the implications on users of removing these boards from the open source project?  For example, is the nuc7i7dnb no longer supported?  That board is listed in our supported hardware documentation: https://projectacrn.github.io/latest/reference/hardware.html

**Comment by gvancuts** [comment]
> 
> 
> What are the implications on users of removing these boards from the open source project? For example, is the nuc7i7dnb no longer supported? @NanlinXie That (deleted) board is listed in our supported hardware documentation: https://projectacrn.github.io/latest/reference/hardware.html

These boards are also widely referenced throughout our documentation (tutorials, etc.)

**Comment by NanlinXie** [comment]
For nuc7i7dnb , we suggest user to follow GSG to generate their board.xml by their own. 
We need update document to check whether there's any invalid link to these files, let's update the document after this patch could be merged.

**Comment by NanlinXie** [comment]
@wenlingz , Why still fail CI test?

**Comment by gvancuts** [comment]
> 
> 
> @wenlingz , Why still fail CI test?

Looking at the names of the tasks that failed, it looks like it failed because it couldn't build for the targets... because we just deleted them in this patch ;-)

**Comment by gvancuts** [comment]
> 
> 
> For nuc7i7dnb , we suggest user to follow GSG to generate their board.xml by their own.
> We need update document to check whether there's any invalid link to these files, let's update the document after this patch could be merged.

There are actually not too many of those instances left in our documentation, mainly the tutorials about hybrid and logical partition.

**Review by gvancuts — APPROVED** [review]

**Comment by wenlingz** [comment]
@NanlinXie please help approve this PR, thanks

**Review by NanlinXie — APPROVED** [review]

**Pull request merged**
