### PR TITLE
doc: Add ACRN configuration tool tutorial

### PR DESCRIPTION
**Pull request by lirui34**
An offline configure tool is designed to configure the BOARD and VM configurations.
Here is the tutorial to tell people how to use it.

Signed-off-by: lirui34 <ruix.li@intel.com>

### CODE REVIEW

**Comment by dbkinder** [comment]
Needs a technical review and resolving merge conflicts.

**Comment by acrnsi** [comment]
OK to verify

**Comment by acrnsi** [comment]
@lirui34  please rebase your code,thanks.

**Comment by acrnsi** [comment]
OK to verify

**Comment by acrnsi** [comment]
OK to verify

**Comment by NanlinXie** [comment]
@jsun26intel  Please help to review.

**Pull request merged**
