### PR TITLE
frame pointer: force enable fno-omit-frame-pointer

### PR DESCRIPTION
**Pull request by iotcg**
No matter the optimization level, keep frame pointer for backtrace

Signed-off-by: Liu Changcheng <changcheng.liu@aliyun.com>

### CODE REVIEW

**Comment by iotcg** [comment]
Don't merge this patch.
This is only for internal team temporary use.

**Comment by NanlinXie** [comment]
Can one of the admins verify this patch?

**Comment by dongyaozu** [comment]
@binbinwu1

**Comment by iotcg** [comment]
@NanlinXie 
I have no plan to merge this patch which is only for temporary debug purpose.
It needs to optimize this patch to keep frame pointer in system if it's needed in official release.

**Comment by binbinwu1** [comment]
@dongyaozu According to comment of iotcg, it is just a debug patch.
@iotcg  If it is a debug patch, you could just upload it to your own repo, or make the title of the patch clear to avoid confusion.

**Comment by iotcg** [comment]
@binbinwu1Sorry for unclear patch title. Please ignore this patch. 
BTW, If frame pointer is needed in official release, it needs more time to refine the patch.

**Comment by dongyaozu** [comment]
@iotcg   Then please don't submit PR..

**Comment by dongyaozu** [comment]
@iotcg can u close this PR?

**Pull request closed without merging**
