### PR TITLE
virtio-blk optimization patches

### PR DESCRIPTION
**Pull request by shiqingg**

### CODE REVIEW

**Comment by yuhuanX** [comment]
Please add Tracked-On in commit message

**Comment by yuhuanX** [comment]
'/hypervisor' part needs 'dongyaozu', 'lifeix' or 'junjiemao1' to approve.

**Review by junjiemao1 — APPROVED** [review]
LGTM. Thanks.

**Comment by yuhuanX** [comment]
start to run premerge test

**Comment by yuhuanX** [comment]
@shiqingg ， adl-s-crb-shared-test fail，please contact me （Huang, YuhuanX)  if you want to debug on the board.

device.generator.DeviceGenerator . Launch Uos rtlaag, launch_script=${boot_script}, comm=ssh
Start / End / Elapsed:	20240605 12:27:17.430 / 20240605 12:29:17.499 / 00:02:00.069
12:29:17.496	INFO	root@192168132sos-dom0:~# 
root@192168132sos-dom0:~# bash /home/auto_script/launch_user_vm_id2.sh
cpu8 online=1
cpu9 online=1
Device "RT" does not exist.
acrn-br0 bridge already exists, adding new RT TAP device to it...
Launch device model with parameters: --cpu_affinity 64,66 -m 1024M --ovmf /usr/share/acrn/bios/OVMF.fd -s 0:0,hostbridge -s 8,ivshmem,dm:/looking_glass_waag,32 --virtio_poll 1000000 -s 3,virtio-console,@stdio:stdio_port -s 4,virtio-net,tap=RT,mac_seed=90:49:fa:07:9a:69-POST_RT_VM1 -s 5,virtio-blk,/root/rt/core-image-weston-intel-corei7-64.wic --rtvm --lapic_pt --logger_setting console,level=4;kmsg,level=3;disk,level=5 POST_RT_VM1
acrn-dm: error while loading shared libraries: liburing.so.2: cannot open shared object file: No such file or directory
root@192168132sos-dom0:~# 	
12:29:17.496	INFO	[2024-06-05 12:29:17.496] [[0;33m WARN [0m] launch uos for 1 time failed: Fail to launch RTVM, refer to the login RTVM log:
12:29:17.499	FAIL	TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

**Comment by yuhuanX** [comment]
start to run premerge test

**Pull request merged**
