### PR TITLE
Hv main refine

### PR DESCRIPTION
**Pull request by fyin1**
This patch set is used to revise the hv_main loop to prevent acrn_handle_pending_request
called twice in one vmexit.

Tracked-On: #3387
Signed-off-by: Yin Fengwei <fengwei.yin@intel.com>
Acked-by: Anthony Xu <anthony.xu@intel.com>

### CODE REVIEW

**Comment by HuiHuangShi** [comment]
2 new potential violations to the coding guideline detected. Please help check. Thanks!<br><1> config:part_config filename:/hypervisor/include/arch/x86/irq.h func: offset:98<br> reason:No real declaration for external variable. : spurious_handler<br><2> config:sharing_config filename:/hypervisor/include/arch/x86/irq.h func: offset:98<br> reason:No real declaration for external variable. : spurious_handler<br><br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by HuiHuangShi** [comment]
4 new potential violations to the coding guideline detected. Please help check. Thanks!<br><1> config:common filename:/hypervisor/dm/vuart.c func: offset:40<br> reason:Macro parameter not in brackets.             : flags<br><2> config:common filename:/hypervisor/dm/vuart.c func: offset:41<br> reason:Macro parameter not in brackets.             : flags<br><3> config:sharing_config filename:/hypervisor/include/arch/x86/irq.h func: offset:98<br> reason:No real declaration for external variable. : spurious_handler<br><4> config:part_config filename:/hypervisor/include/arch/x86/irq.h func: offset:98<br> reason:No real declaration for external variable. : spurious_handler<br><br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by fyin1** [comment]
Need to update patch to address these two coding style issue:
<1> config:common filename:/hypervisor/dm/vuart.c func: offset:40
reason:Macro parameter not in brackets. : flags
<2> config:common filename:/hypervisor/dm/vuart.c func: offset:41
reason:Macro parameter not in brackets. : flags

The other two are incorrect report.

**Comment by HuiHuangShi** [comment]
2 new potential violations to the coding guideline detected. Please help check. Thanks!<br><1> config:part_config filename:/hypervisor/include/arch/x86/irq.h func: offset:98<br> reason:No real declaration for external variable. : spurious_handler<br><2> config:sharing_config filename:/hypervisor/include/arch/x86/irq.h func: offset:98<br> reason:No real declaration for external variable. : spurious_handler<br><br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Pull request merged**
