### PR TITLE
PCID Virtualization Support

### PR DESCRIPTION
**Pull request by binbinwu1**
Guest OS kernels, like Linux kernel, enabled Kernal Page Table Isolation (KPTI) as the mitigation of Meltdown.
Enabling KPTI without the support of PCID will cause significant performance loss when user/kernel space switch is frequent.
This patch series passes-through PCID capabilities to guest VM.

Note: On the hardware platforms that are not affected by Miltdown, Linux doesn't enabled KPTI unless it is forced by kernel parameter "pti=on".

Tracked-On: #4296
Signed-off-by: Binbin Wu <binbin.wu@intel.com>
Acked-by: Eddie Dong <eddie.dong@intel.com>

### CODE REVIEW

**Comment by binbinwu1** [comment]
@wenlingz The failure was caused by the patch or the CI system?

**Comment by wenlingz** [comment]
@binbinwu1 no MISRA-C check, please refer the label

**Comment by wenlingz** [comment]
@HuiHuangShi please help add the MISRA-C check label, thanks

**Comment by HuiHuangShi** [comment]
4 new potential violations to the coding guideline detected. Please help check. Thanks!<br><1> config:part_config filename:/hypervisor/arch/x86/guest/virtual_cr.c func:vmx_write_cr4 offset:339<br> reason:Function return value potentially unused. : guest_cr3<br><2> config:sharing_config filename:/hypervisor/arch/x86/guest/virtual_cr.c func:vmx_write_cr4 offset:339<br> reason:Function return value potentially unused. : guest_cr3<br><3> config:common filename:/hypervisor/arch/x86/guest/virtual_cr.c func:vmx_write_cr4 offset:343<br> reason:Logical conjunctions need brackets.<br><4> config:common filename:/hypervisor/arch/x86/guest/virtual_cr.c func:vmx_write_cr4 offset:343<br> reason:No space between if, while, for and expresn.<br><br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by wenlingz** [comment]
@binbinwu1 please fix the MISRA-C check issues, thanks

**Comment by HuiHuangShi** [comment]
No new violations to the coding guideline detected.<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Pull request merged**
