### PR TITLE
HV: inject physical PCIEXBAR into vhostbridge to better emulate vhostbridge

### PR DESCRIPTION
**Pull request by qianwang-intel**
HV: inject physical PCIEXBAR into vhostbridge to better emulate vhostbridge, and refined init_vhostbridge with dword-alignment

Modified the commit message according to the comments of @dongyaozu

### CODE REVIEW

**Comment by HuiHuangShi** [comment]
12 new potential violations to the coding guideline detected. Please help check. Thanks!<br><1> config:common filename:/hypervisor/dm/vpci/vhostbridge.c func:init_vhostbridge offset:114<br> reason:Cast to an unrelated type. : (char* to struct acrn_vm*): ( struct acrn_vm * ) ( ( char * ) ( vdev -> vpci ) - __builtin_offsetof ( struct acrn_vm , vpci )<br><2> config:common filename:/hypervisor/dm/vpci/vhostbridge.c func:init_vhostbridge offset:114<br> reason:Casting operation to a pointer. : (char* to struct acrn_vm*): ( struct acrn_vm * ) ( ( char * ) ( vdev -> vpci ) - __builtin_offsetof ( struct acrn_vm , vpci )<br><3> config:common filename:/hypervisor/dm/vpci/vhostbridge.c func:init_vhostbridge offset:114<br> reason:Casting operation to a pointer. : (struct acrn_vpci to char*): ( char * ) ( vdev -> vpci )<br><4> config:common filename:/hypervisor/dm/vpci/vhostbridge.c func:init_vhostbridge offset:114<br> reason:Casting operation on a pointer. : (char* to struct acrn_vm*): ( struct acrn_vm * ) ( ( char * ) ( vdev -> vpci ) - __builtin_offsetof ( struct acrn_vm , vpci )<br><5> config:common filename:/hypervisor/dm/vpci/vhostbridge.c func:init_vhostbridge offset:114<br> reason:No space between if, while, for and expresn.<br><6> config:common filename:/hypervisor/dm/vpci/vhostbridge.c func:init_vhostbridge offset:116<br> reason:Start of variable is upper case.             : VIRT_PCI_MMCFG_BASE<br><7> config:common filename:/hypervisor/dm/vpci/vhostbridge.c func:init_vhostbridge offset:121<br> reason:Space missing before or after binary operator.<br><8> config:common filename:/hypervisor/dm/vpci/vhostbridge.c func:init_vhostbridge offset:121<br> reason:Expression needs brackets.<br><9> config:common filename:/hypervisor/dm/vpci/vhostbridge.c func:init_vhostbridge offset:121<br> reason:Signed/unsigned conversion without cast. :  (unsigned int and int): i<br><10> config:common filename:/hypervisor/dm/vpci/vhostbridge.c func:init_vhostbridge offset:121<br> reason:Literal value requires a U suffix.           : 0<br><11> config:common filename:/hypervisor/dm/vpci/vhostbridge.c func:init_vhostbridge offset:122<br> reason:Literal value requires a U suffix.           : 0xff00<br><12> config:common filename:/hypervisor/dm/vpci/vhostbridge.c func:init_vhostbridge offset:122<br> reason:Use of bit operator on signed type. : & used with int: 0xff00<br><br>No New Name Conflict<br>No New Function Declaration/Definition Mismatch

**Comment by HuiHuangShi** [comment]
7 new potential violations to the coding guideline detected. Please help check. Thanks!<br><1> config:common filename:/hypervisor/dm/vpci/vhostbridge.c func:init_vhostbridge offset:114<br> reason:Cast to an unrelated type. : (char* to struct acrn_vm*): ( struct acrn_vm * ) ( ( char * ) ( vdev -> vpci ) - __builtin_offsetof ( struct acrn_vm , vpci )<br><2> config:common filename:/hypervisor/dm/vpci/vhostbridge.c func:init_vhostbridge offset:114<br> reason:Casting operation to a pointer. : (char* to struct acrn_vm*): ( struct acrn_vm * ) ( ( char * ) ( vdev -> vpci ) - __builtin_offsetof ( struct acrn_vm , vpci )<br><3> config:common filename:/hypervisor/dm/vpci/vhostbridge.c func:init_vhostbridge offset:114<br> reason:Casting operation to a pointer. : (struct acrn_vpci to char*): ( char * ) ( vdev -> vpci )<br><4> config:common filename:/hypervisor/dm/vpci/vhostbridge.c func:init_vhostbridge offset:114<br> reason:Casting operation on a pointer. : (char* to struct acrn_vm*): ( struct acrn_vm * ) ( ( char * ) ( vdev -> vpci ) - __builtin_offsetof ( struct acrn_vm , vpci )<br><5> config:common filename:/hypervisor/dm/vpci/vhostbridge.c func:init_vhostbridge offset:116<br> reason:Start of variable is upper case.             : VIRT_PCI_MMCFG_BASE<br><6> config:part_config filename:/hypervisor/dm/vpci/vhostbridge.c func:init_vhostbridge offset:120<br> reason:Function return value potentially unused. : phys_did<br><7> config:sharing_config filename:/hypervisor/dm/vpci/vhostbridge.c func:init_vhostbridge offset:120<br> reason:Function return value potentially unused. : phys_did<br><br>No New Name Conflict<br>No New Function Declaration/Definition Mismatch

**Comment by wenlingz** [comment]
OK to Verify

**Comment by HuiHuangShi** [comment]
6 new potential violations to the coding guideline detected. Please help check. Thanks!<br><1> config:common filename:/hypervisor/dm/vpci/vhostbridge.c func:init_vhostbridge offset:114<br> reason:Cast to an unrelated type. : (char* to struct acrn_vm*): ( struct acrn_vm * ) ( ( char * ) ( vdev -> vpci ) - __builtin_offsetof ( struct acrn_vm , vpci )<br><2> config:common filename:/hypervisor/dm/vpci/vhostbridge.c func:init_vhostbridge offset:114<br> reason:Casting operation to a pointer. : (char* to struct acrn_vm*): ( struct acrn_vm * ) ( ( char * ) ( vdev -> vpci ) - __builtin_offsetof ( struct acrn_vm , vpci )<br><3> config:common filename:/hypervisor/dm/vpci/vhostbridge.c func:init_vhostbridge offset:114<br> reason:Casting operation to a pointer. : (struct acrn_vpci to char*): ( char * ) ( vdev -> vpci )<br><4> config:common filename:/hypervisor/dm/vpci/vhostbridge.c func:init_vhostbridge offset:114<br> reason:Casting operation on a pointer. : (char* to struct acrn_vm*): ( struct acrn_vm * ) ( ( char * ) ( vdev -> vpci ) - __builtin_offsetof ( struct acrn_vm , vpci )<br><5> config:sharing_config filename:/hypervisor/dm/vpci/vhostbridge.c func:init_vhostbridge offset:120<br> reason:Function return value potentially unused. : phys_did<br><6> config:part_config filename:/hypervisor/dm/vpci/vhostbridge.c func:init_vhostbridge offset:120<br> reason:Function return value potentially unused. : phys_did<br><br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Pull request merged**
