### PR TITLE
Change Service VM to supervisor role

### PR DESCRIPTION
**Pull request by YuanXin-Intel**
1. Enable Service VM to power off or restart the whole platform even when RTVM is running.
2. Allow Service VM stop the RTVM using acrnctl tool with option "stop -f".
3. Add 'Service VM supervisor role enabled' option in ACRN configurator

Tracked-On: #8618

Reviewed-by: Junjie Mao <junjie.mao@intel.com>
Reviewed-by: Jian Jun Chen <jian.jun.chen@intel.com>

### CODE REVIEW

**Comment by yuhuanX** [comment]
Can one of the admins verify this patch?

**Review by junjiemao1 — APPROVED** [review]

**Comment by yuhuanX** [comment]
'/devicemodel' needs 'ywan170' or 'chejianj' to approve, '/misc%2Fconfig_tools' needs 'terryzouhao' or 'NanlinXie' to approve

**Comment by wenlingz** [comment]
@chejianj @NanlinXie please help approve this PR, thanks

**Review by chejianj — APPROVED** [review]

**Review by NanlinXie — APPROVED** [review]

**Comment by yuhuanX** [comment]
start to run premerge test

**Pull request merged**
