### PR TITLE
New acrnctl cmd

### PR DESCRIPTION
**Pull request by KaigeFu**

### CODE REVIEW

**Comment by NanlinXie** [comment]
Can one of the admins verify this patch?

**Comment by dongyaozu** [comment]
@KaigeFu  why check fails? solve the issue first?

**Comment by dongyaozu** [comment]
@KaigeFu Solve the build failure first

**Comment by KaigeFu** [comment]
@dongyaozu acrnctl use new lib acrn_mngr and it fail to find it because wrong location of lib. I am working on it.

**Comment by lijinxia** [comment]
Verified +1

**Pull request merged**
