### PR TITLE
HV:vtd:fix all integer related violations

### PR DESCRIPTION
**Pull request by HuiHuangShi**
HV:vtd:fix all integer related violations

Fix vtd.h and vtd.c all integer violations.

Signed-off-by: Huihuang Shi <huihuang.shi@intel.com>
Reviewed-by: Junjie Mao <junjie.mao@intel.com>
Acked-by: Eddie Dong <eddie.dong@intel.com>

### CODE REVIEW

**Comment by NanlinXie** [comment]
Can one of the admins verify this patch?

**Comment by dongyaozu** [comment]
@HuiHuangShi  3 patch ?

**Comment by HuiHuangShi** [comment]
@dongyaozu yes,the rest parches is sent yesterday,and reviewed by junjie.

**Comment by dongyaozu** [comment]
@HuiHuangShi This kind of things should be in 2 PRs... Last exception ...

**Comment by HuiHuangShi** [comment]
@dongyaozu  there have 3 patches,which patches can be merged into a pr.

**Comment by lijinxia** [comment]
Verified+1

**Pull request merged**
