### PR TITLE
doc: more release notes 2.0 edits

### PR DESCRIPTION
**Pull request by dbkinder**
Signed-off-by: David B. Kinder <david.b.kinder@intel.com>

### CODE REVIEW

**Comment by HuiHuangShi** [comment]
No new violations to the coding guideline detected.<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by NanlinXie** [comment]
@dbkinder , could we also update the "using_grub" document into "document updated " section? And could we move the "using_grub" doc from menu "Additional Tutorials" to "Enable ACRN Features"?
https://projectacrn.github.io/latest/tutorials/using_grub.html?highlight=grub

**Comment by dbkinder** [comment]
@nanlin using_grub moved to "enable acrn features" and added to the release notes documents list.

**Comment by HuiHuangShi** [comment]
No new violations to the coding guideline detected.<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Pull request merged**
