### PR TITLE
dm: virtio: check for paddr_guest2host return value-v2.3 branch

### PR DESCRIPTION
**Pull request by yonghuah**
paddr_guest2host can return NULL, but code paths in virtio
are not checking the return value.
_vq_record() initializes iov_base pointer using paddr_guest2host()
but there is nothing in the flow that checks for NULL.
Chane _vq_record to return -1 in case the address translation
has failed.

Tracked-On: #5514
Signed-off-by: Tomas Winkler <tomas.winkler@intel.com>
Acked-by: Wang, Yu1 <yu1.wang@intel.com>

### CODE REVIEW

**Comment by yonghuah** [comment]
this is a back porting from mainline. thanks.

**Comment by HuiHuangShi** [comment]
No new violations to the coding guideline detected.<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by wenlingz** [comment]
@ywan170 please help approve it, thanks

**Comment by wenlingz** [comment]
@fyin1 please help approve this PR, thanks

**Review by fyin1 — APPROVED** [review]

**Pull request merged**
