### PR TITLE
Makefile: enhance misc/Makefile for more intuitive usage

### PR DESCRIPTION
**Pull request by gvancuts**
Enhance the 'misc/Makefile' to improve readability by grouping the
tools based on whether these are `services` or `debug_tools`
(following the folders they're in) and also create separate build
folders instead of putting *both* services and debug_tools in the
build/misc/debug_tools folder (default value).

Tracked-On: #5793
Signed-off-by: Geoffroy Van Cutsem <geoffroy.vancutsem@intel.com>

### CODE REVIEW

**Comment by HuiHuangShi** [comment]
No new violations to the coding guideline detected.<br>No New Name Conflict<br>No New Function Declaration/Definition Mismatch

**Review by ywan170 — APPROVED** [review]

**Comment by gvancuts** [comment]
> 
> 
> @gvancuts
> Yocto build fail with 'Applying 'no-life-mngr.patch' failed' , please sync meta_acrn and rebuild it~
> `ERROR: acrn-tools-5810-1614761391 do_patch: Applying 'no-life-mngr.patch' failed: checking file misc/Makefile Hunk #1 FAILED at 2. Hunk #2 FAILED at 38. 2 out of 2 hunks FAILED ERROR: Logfile of failure stored in: /home/meta-acrn/workspace/build/master-acrn-sos/work/corei7-64-oe-linux/acrn-tools/5810-1614761391/temp/log.do_patch.169 NOTE: recipe acrn-tools-5810-1614761391: task do_patch: Failed NOTE: recipe acrn-hypervisor-5810-1614761391: task do_patch: Started ERROR: Task (/home/meta-acrn/workspace/meta-acrn/recipes-core/acrn/acrn-tools.bb:do_patch) failed with exit code '1'`

I have send a PR to fix the patch in Yocto (see https://github.com/intel/meta-acrn/pull/313) but I'm not sure if this is the right way of fixing this failure?

**Comment by wenlingz** [comment]
> > @gvancuts
> > Yocto build fail with 'Applying 'no-life-mngr.patch' failed' , please sync meta_acrn and rebuild it~
> > `ERROR: acrn-tools-5810-1614761391 do_patch: Applying 'no-life-mngr.patch' failed: checking file misc/Makefile Hunk #1 FAILED at 2. Hunk #2 FAILED at 38. 2 out of 2 hunks FAILED ERROR: Logfile of failure stored in: /home/meta-acrn/workspace/build/master-acrn-sos/work/corei7-64-oe-linux/acrn-tools/5810-1614761391/temp/log.do_patch.169 NOTE: recipe acrn-tools-5810-1614761391: task do_patch: Failed NOTE: recipe acrn-hypervisor-5810-1614761391: task do_patch: Started ERROR: Task (/home/meta-acrn/workspace/meta-acrn/recipes-core/acrn/acrn-tools.bb:do_patch) failed with exit code '1'`
> 
> I have send a PR to fix the patch in Yocto (see [intel/meta-acrn#313](https://github.com/intel/meta-acrn/pull/313)) but I'm not sure if this is the right way of fixing this failure?

@acrnsi-robot  please try #313 to  verify this PR, thanks

**Comment by wenlingz** [comment]
@gvancuts with @saininav 's meta-acrn patch https://github.com/saininav/meta-acrn/commit/8f1649ed364bddc07ffaf61def2346249e6dc53d , this PR can build and test pass now

**Comment by saininav** [comment]
@gvancuts I will re-send behalf of you, when meta-acrn points to latest acrn-hypervisor master.

**Comment by gvancuts** [comment]
> @gvancuts I will re-send behalf of you, when meta-acrn points to latest acrn-hypervisor master.

Thanks @saininav , I appreciate it!

**Pull request merged**
