### PR TITLE
Determine size of drhd_dev_scope based on board file

### PR DESCRIPTION
**Pull request by jiaqingz-intel**
Determine size of drhd_dev_scope based on board file to support devices
that have more than 16 device scope in single DMAR structure, like qemu

Related issues:
https://github.com/projectacrn/acrn-hypervisor/issues/8639
https://github.com/projectacrn/acrn-hypervisor/issues/8494
https://github.com/projectacrn/acrn-hypervisor/issues/8571

### CODE REVIEW

**Review by junjiemao1 — APPROVED** [review]

**Comment by yuhuanX** [comment]
@jiaqingz-intel , please modify "Tracked on: #8494" to "Tracked-On: #8494"

**Comment by yuhuanX** [comment]
@jiaqingz-intel , code scan with clang-tidy  failed. Please see log for detail: https://cbjenkins-pg.devtools.intel.com/teams-acrn/job/acrn/job/acrn-hypervisor-codescan-native/3245/console

acrn-hypervisor/hypervisor/include/arch/x86/asm/vtd.h:476:33: error: ‘DRHD_MAX_DEVSCOPE_COUNT’ undeclared here (not in a function)
  476 | #define MAX_DRHD_DEVSCOPES      DRHD_MAX_DEVSCOPE_COUNT
      |                                 ^~~~~~~~~~~~~~~~~~~~~~~
acpi_parser/dmar_parse.c:18:56: note: in expansion of macro ‘MAX_DRHD_DEVSCOPES’
   18 | static struct dmar_dev_scope drhd_dev_scope[MAX_DRHDS][MAX_DRHD_DEVSCOPES];
      |                                                        ^~~~~~~~~~~~~~~~~~
acpi_parser/dmar_parse.c:18:30: error: ‘drhd_dev_scope’ defined but not used [-Werror=unused-variable]
   18 | static struct dmar_dev_scope drhd_dev_scope[MAX_DRHDS][MAX_DRHD_DEVSCOPES];
      |                              ^~~~~~~~~~~~~~
cc1: all warnings being treated as errors

**Comment by yuhuanX** [comment]
'/misc/config_tools' needs 'terryzouhao' or 'NanlinXie' to approve

**Review by NanlinXie — APPROVED** [review]

**Comment by yuhuanX** [comment]
start to run premerge test

**Pull request merged**
