### PR TITLE
acrn-config: enable only 4 vms for TGL

### PR DESCRIPTION
**Pull request by conghuic23**
Enable only 4 vms for TGL.

Tracked-On: #5013
Signed-off-by: Conghui Chen <conghui.chen@intel.com>

### CODE REVIEW

**Comment by HuiHuangShi** [comment]
No new violations to the coding guideline detected.<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by HuiHuangShi** [comment]
No new violations to the coding guideline detected.<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by conghuic23** [comment]
@wenlingz  please help to trigger the check again.

**Comment by wenlingz** [comment]
@terryzouhao please help approve this PR, thanks

**Pull request merged**
