### PR TITLE
hv: restore stack protector canary if it was configured

### PR DESCRIPTION
**Pull request by yonghuah**
Restores canary values of stack protector on all APs
 if it was configured, instead of generating a new canary
 value.

Tracked-On: #8577

Reviewed-by: Junjie Mao <junjie.mao@intel.com>
Reviewed-by: Fei Li <fei1.li@intel.com>

### CODE REVIEW

**Comment by yuhuanX** [comment]
start to run premerge test

**Comment by yonghuah** [comment]
@lifeix  @junjiemao1  pls review, thanks.

**Comment by yuhuanX** [comment]
start to run premerge test

**Comment by junjiemao1** [comment]
I don't think we are restoring anything anymore in the commit. Instead, we leave an initialized canary untouched when `set_fs_base` is called again (e.g. on resuming from S3). I would recommend rewording the comments and commit messages to faithfully describe the intention behind the code.

**Comment by yonghuah** [comment]
thanks @junjiemao1 , have updated commit message.

**Review by junjiemao1 — APPROVED** [review]

**Comment by yuhuanX** [comment]
start to run premerge test

**Pull request merged**
