### PR TITLE
hv: flush cache after update the trampoline code

### PR DESCRIPTION
**Pull request by fyin1**
Trampoline code is updated as data when preparing the trampoline
code and doing relocation. In this case, we need to flush cache
to make sure the updated code is in RAM.

Tracked-On: #1604
Signed-off-by: Yin Fengwei <fengwei.yin@intel.com>
Reviewed-by: Zide Chen <zide.chen@intel.com>
Acked-by: Anthony Xu <anthony.xu@intel.com>

### CODE REVIEW

**Comment by HuiHuangShi** [comment]
1615<br>2 new potential violations to the coding guideline detected. Please help check. Thanks!  <br><br>1.filename:/hypervisor/boot/reloc.c&nbsp;&nbsp;function:prepare_trampoline&nbsp;&nbsp;offset:234:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:For loop incrementation is not simple.<br><br>2.filename:/hypervisor/boot/reloc.c&nbsp;&nbsp;function:prepare_trampoline&nbsp;&nbsp;offset:235:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Cast from integral type to pointer. : (unsigned long to char*): ( char * ) ( dest_pa + i )<br><br>

**Comment by HuiHuangShi** [comment]
1615<br>No new violations to the coding guideline detected.

**Comment by ClaudZhang1995** [comment]
Ready to merge

**Comment by ClaudZhang1995** [comment]
Ready to merge

**Pull request merged**
