### PR TITLE
HV: vmx code clean up

### PR DESCRIPTION
**Pull request by gzhai7**
Remove uncessary variables and function parameter

Signed-off-by: Edwin Zhai <edwin.zhai@intel.com>
Acked-by: Anthony Xu <anthony.xu@intel.com>

### CODE REVIEW

**Comment by dongyaozu** [comment]
@junjiemao1 can you review from MISRA p.o.v. ?

**Comment by junjiemao1** [comment]
This looks good to me as VMCS fields are always 32-bit integers which fit as the first parameter to exec_vm(read|write).

**Comment by lijinxia** [comment]
@junjiemao1 Could you please rebase and fix the conflicts?

**Comment by lijinxia** [comment]
Verified+1

**Pull request merged**
