### PR TITLE
config-tool: rename PSRARM to SSRAM

### PR DESCRIPTION
**Pull request by yonghuah**
'psram' and 'PSARM' are legacy names and replaced
  with 'ssram' and 'SSRAM' respectively.

Tracked-On: #6012
Signed-off-by: Yonghua Huang <yonghua.huang@intel.com>

### CODE REVIEW

**Comment by yonghuah** [comment]
@szhen11  please review , thanks.

**Comment by szhen11** [comment]
> @szhen11 please review , thanks.

LGTM at config tool part.

**Comment by yonghuah** [comment]
@terryzouhao  pls review .
 - thank you.

**Review by terryzouhao — APPROVED** [review]

**Comment by wenlingz** [comment]
@yonghuah please rebase your code, thanks

**Comment by gvancuts** [comment]
Can you fix the typo in the commit message: `PSRARM` to `PSRAM`

**Comment by yonghuah** [comment]
@gvancuts  @wenlingz  have update this PR,  thanks for review.

-Yonghua

**Pull request merged**
