### PR TITLE
doc: add VT-d posted interrupt documentation

### PR DESCRIPTION
**Pull request by donsheng**
Add VT-d posted interrupt documentation to describe its design logic
Tracked-On: #4506
Signed-off-by: dongshen <dongsheng.x.zhang@intel.com>

### CODE REVIEW

**Comment by HuiHuangShi** [comment]
No new violations to the coding guideline detected.<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by dbkinder** [comment]
@donsheng I made some spelling, grammar, and formatting changes and pushed them directly back to your branch (so you don't have to make the recommended edits yourself).

**Comment by HuiHuangShi** [comment]
No new violations to the coding guideline detected.<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by donsheng** [comment]
> @donsheng I made some spelling, grammar, and formatting changes and pushed them directly back to your branch (so you don't have to make the recommended edits yourself).

Hi, thanks for your help very much!

**Comment by donsheng** [comment]
> LGTM, after my updates directly to your branch.

 (This would happen if we

The left parenthesis is not needed, we need to remove it

**Comment by dbkinder** [comment]
The extra spaces aren't a problem (they will be ignored in the generated HTML), but I fixed them anyway while I removed the stray '('.  If there are no technical issues with my changes, I'll merge this with the CI completes successfully.

**Comment by HuiHuangShi** [comment]
No new violations to the coding guideline detected.<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by HuiHuangShi** [comment]
No new violations to the coding guideline detected.<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Pull request merged**
