### PR TITLE
doc: Add visual OpenStack setup instructions

### PR DESCRIPTION
**Pull request by dbkinder**
Update the OpenStack/libvirt tutorial with detailed instructions with
screen shots.

Signed-off-by: David B. Kinder <david.b.kinder@intel.com>

### CODE REVIEW

**Comment by dbkinder** [comment]
Not ready to merge yet, but I wanted to get review comments on progress so far.

**Comment by HuiHuangShi** [comment]
No new violations to the coding guideline detected.<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by HuiHuangShi** [comment]
No new violations to the coding guideline detected.<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by HuiHuangShi** [comment]
No new violations to the coding guideline detected.<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by dbkinder** [comment]
@NanlinXie @gvancuts Ready for your technical review and then we can merge and publish.

**Comment by HuiHuangShi** [comment]
No new violations to the coding guideline detected.<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by NanlinXie** [comment]
@Leo2Chang Could you help to review?

**Comment by dbkinder** [comment]
@Leo2Chang The .patch file won't be available on GitHub until this PR is merged

**Comment by HuiHuangShi** [comment]
No new violations to the coding guideline detected.<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Pull request merged**
