### PR TITLE
doc: fix misspelling in memory management doc

### PR DESCRIPTION
**Pull request by m8**
fix misspelling in memory management docs
Signed-off-by: Musa Unal umusasadik@gmail.com

### CODE REVIEW

**Review by dbkinder — APPROVED** [review]

**Comment by dbkinder** [comment]
ok to verify

**Comment by dbkinder** [comment]
@m8 @wenlingz @nanlin I suspect the "no Signed-off-by" error is because you need a blank line between your commit description and the ``Signed-off-by:`` line.  Can you amend your commit with this blank line and see if that fixes things.

**Comment by wenlingz** [comment]
> @m8 @wenlingz @nanlin I suspect the "no Signed-off-by" error is because you need a blank line between your commit description and the `Signed-off-by:` line. Can you amend your commit with this blank line and see if that fixes things.

no signed-off-by in commit

**Review by gvancuts — APPROVED** [review]
Hi @m8 , this looks good to me, thanks for sending the patch!

Can you just update your commit message following these guidelines: https://projectacrn.github.io/latest/developer-guides/contribute_guidelines.html#commit-guidelines

Thanks!

**Comment by dbkinder** [comment]
@m8 Looks like the problem is that the commit doesn't have a Signed-off-by line.  You can't fix this by just editing the comment in this GitHub interface.  You need to do a ``commit -s --amend`` to update your commit with a Signed-off-by line, and then do a forced push to submit the fixed commit.

**Comment by m8** [comment]
ok, solved

**Pull request merged**
