### PR TITLE
Doc: Update system power management doc

### PR DESCRIPTION
**Pull request by fyin1**
Signed-off-by: Yin Fengwei <fengwei.yin@intel.com>

### CODE REVIEW

**Comment by NanlinXie** [comment]
@fyin1 , Please modify SOS to Service VM and UOS to User VM.

**Comment by fyin1** [comment]
@NanlinXie Done.

**Comment by acrnsi** [comment]
OK to verify

**Comment by acrnsi** [comment]
OK to verify

**Pull request merged**
