### PR TITLE
HV:  MISRA clean in reloc.c

### PR DESCRIPTION
**Pull request by guoch2**
The patch is to fix MISRA violation in reloc.c by:
 - remove multi-returns in relocate();
 - remove non useful checking in relocate();
 - add suffix U to macro definition

Tracked-On: #861
Signed-off-by: Chaohong guo <chaohong.guo@intel.com>
Acked-by: Anthony Xu <anthony.xu@intel.com>

### CODE REVIEW

**Comment by HuiHuangShi** [comment]
2424<br>1 new potential violations to the coding guideline detected. Please help check. Thanks!  <br><br>1.filename:/hypervisor/boot/reloc.c&nbsp;&nbsp;function:relocate&nbsp;&nbsp;offset:83:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:<#> Switch empty default has no comment (MR).<br><br>

**Comment by HuiHuangShi** [comment]
2424<br>1 new potential violations to the coding guideline detected. Please help check. Thanks!  <br><br>1.filename:/hypervisor/boot/reloc.c&nbsp;&nbsp;function:relocate&nbsp;&nbsp;offset:83:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:<#> Switch empty default has no comment (MR).<br><br>

**Comment by shiqingg** [comment]
The violation has to be fixed.

**Comment by HuiHuangShi** [comment]
2424<br>1 new potential violations to the coding guideline detected. Please help check. Thanks!  <br><br>1.filename:/hypervisor/boot/reloc.c&nbsp;&nbsp;function:relocate&nbsp;&nbsp;offset:83:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:<#> Switch empty default has no comment (MR).<br><br>

**Comment by ClaudZhang1995** [comment]
Ok to verify

**Comment by ClaudZhang1995** [comment]
Ok to verify

**Comment by HuiHuangShi** [comment]
2424<br>No new violations to the coding guideline detected.

**Pull request merged**
