### PR TITLE
Vpic: remove vpic

### PR DESCRIPTION
**Pull request by lifeix**
Just for test.

### CODE REVIEW

**Comment by HuiHuangShi** [comment]
6 new potential violations to the coding guideline detected. Please help check. Thanks!<br><1> config:part_config filename:/hypervisor/dm/vpic.c func:vpic_init offset:33<br> reason:No prototype for non-static function. : vpic_init<br><2> config:sharing_config filename:/hypervisor/dm/vpic.c func:vpic_init offset:33<br> reason:No prototype for non-static function. : vpic_init<br><3> config:sharing_config filename:/hypervisor/arch/x86/guest/virq.c func:acrn_inject_pending_intr offset:426<br> reason:Function return value potentially unused. : guest_irq_enabled<br><4> config:part_config filename:/hypervisor/arch/x86/guest/virq.c func:acrn_inject_pending_intr offset:426<br> reason:Function return value potentially unused. : guest_irq_enabled<br><5> config:sharing_config filename:/hypervisor/arch/x86/guest/vlapic.c func:vlapic_set_local_intr offset:1862<br> reason:Procedure is not called or referenced in code analysed. : vlapic_set_local_intr<br><6> config:part_config filename:/hypervisor/arch/x86/guest/vlapic.c func:vlapic_set_local_intr offset:1862<br> reason:Procedure is not called or referenced in code analysed. : vlapic_set_local_intr<br><br>Name Conflict Violation:<br>ioapic local 215 boot/acpi_base.c<br>ioapic struct 162 include/arch/x86/apicreg.h<br>ioapic member 41 include/common/ptdev.h<br><br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by HuiHuangShi** [comment]
7 new potential violations to the coding guideline detected. Please help check. Thanks!<br><1> config:common filename:/hypervisor/arch/x86/guest/vlapic.c func:vlapic_trigger_lvt offset:907<br> reason:Static procedure is not explicitly called in code analysed. : vlapic_trigger_lvt<br><2> config:part_config filename:/hypervisor/arch/x86/guest/vlapic.c func:vlapic_trigger_lvt offset:907<br> reason:Procedure is not called or referenced in code analysed. : vlapic_trigger_lvt<br><3> config:sharing_config filename:/hypervisor/arch/x86/guest/vlapic.c func:vlapic_trigger_lvt offset:907<br> reason:Procedure is not called or referenced in code analysed. : vlapic_trigger_lvt<br><4> config:sharing_config filename:/hypervisor/arch/x86/guest/virq.c func:acrn_inject_pending_intr offset:426<br> reason:Function return value potentially unused. : guest_irq_enabled<br><5> config:part_config filename:/hypervisor/arch/x86/guest/virq.c func:acrn_inject_pending_intr offset:426<br> reason:Function return value potentially unused. : guest_irq_enabled<br><6> config:part_config filename:/hypervisor/dm/vpic.c func:vpic_init offset:33<br> reason:No prototype for non-static function. : vpic_init<br><7> config:sharing_config filename:/hypervisor/dm/vpic.c func:vpic_init offset:33<br> reason:No prototype for non-static function. : vpic_init<br><br>Name Conflict Violation:<br>ioapic local 215 boot/acpi_base.c<br>ioapic struct 162 include/arch/x86/apicreg.h<br>ioapic member 41 include/common/ptdev.h<br><br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by ClaudZhang1995** [comment]
@lifeix hi,The pr make whl-ipc-i5-uefi fail . It is fial log:
[ ! -e /root/workspace/acrn-hypervisor-premerge-build-image/artifact/out/hv/whl-ipc-i5-uefi/hypervisor/dm/vpci/vsriov.o ] && mkdir -p /root/workspace/acrn-hypervisor-premerge-build-image/artifact/out/hv/whl-ipc-i5-uefi/hypervisor/dm/vpci/ && mkdir -p /root/workspace/acrn-hypervisor-premerge-build-image/artifact/out/hv/whl-ipc-i5-uefi/hypervisor/modules; \
cc  -Iinclude  -Iinclude/lib  -Iinclude/lib/crypto  -Iinclude/common  -Iinclude/arch/x86  -Iinclude/arch/x86/boot  -Iinclude/arch/x86/guest  -Iinclude/arch/x86/lib  -Iinclude/debug  -Iinclude/public  -Iinclude/dm  -Iinclude/hw  -Iboot/include  -Iboot/include/guest  -I/root/workspace/acrn-hypervisor-premerge-build-image/artifact/out/hv/whl-ipc-i5-uefi/hypervisor/include  -Iarch/x86/configs/whl-ipc-i5  -Iscenarios/industry -I. -c  -include /root/workspace/acrn-hypervisor-premerge-build-image/artifact/out/hv/whl-ipc-i5-uefi/hypervisor/include/config.h -Wall -W -ffunction-sections -fdata-sections -fshort-wchar -ffreestanding -fsigned-char -m64 -mno-mmx -mno-sse -mno-sse2 -mno-80387 -mno-fp-ret-in-387 -mno-red-zone -mpopcnt -nostdinc -nostdlib -fno-common -Werror -O2 -fpie -fstack-protector-strong -DSTACK_PROTECTOR -fcf-protection=none -mindirect-branch=thunk-extern -mindirect-branch-register -DCONFIG_RETPOLINE -DHV_DEBUG -DPROFILING_ON -fno-omit-frame-pointer  -gdwarf-2 dm/vpci/vsriov.c -o /root/workspace/acrn-hypervisor-premerge-build-image/artifact/out/hv/whl-ipc-i5-uefi/hypervisor/dm/vpci/vsriov.o -MMD -MT /root/workspace/acrn-hypervisor-premerge-build-image/artifact/out/hv/whl-ipc-i5-uefi/hypervisor/dm/vpci/vsriov.o
[ ! -e /root/workspace/acrn-hypervisor-premerge-build-image/artifact/out/hv/whl-ipc-i5-uefi/hypervisor/arch/x86/guest/vlapic.o ] && mkdir -p /root/workspace/acrn-hypervisor-premerge-build-image/artifact/out/hv/whl-ipc-i5-uefi/hypervisor/arch/x86/guest/ && mkdir -p /root/workspace/acrn-hypervisor-premerge-build-image/artifact/out/hv/whl-ipc-i5-uefi/hypervisor/modules; \
cc  -Iinclude  -Iinclude/lib  -Iinclude/lib/crypto  -Iinclude/common  -Iinclude/arch/x86  -Iinclude/arch/x86/boot  -Iinclude/arch/x86/guest  -Iinclude/arch/x86/lib  -Iinclude/debug  -Iinclude/public  -Iinclude/dm  -Iinclude/hw  -Iboot/include  -Iboot/include/guest  -I/root/workspace/acrn-hypervisor-premerge-build-image/artifact/out/hv/whl-ipc-i5-uefi/hypervisor/include  -Iarch/x86/configs/whl-ipc-i5  -Iscenarios/industry -I. -c  -include /root/workspace/acrn-hypervisor-premerge-build-image/artifact/out/hv/whl-ipc-i5-uefi/hypervisor/include/config.h -Wall -W -ffunction-sections -fdata-sections -fshort-wchar -ffreestanding -fsigned-char -m64 -mno-mmx -mno-sse -mno-sse2 -mno-80387 -mno-fp-ret-in-387 -mno-red-zone -mpopcnt -nostdinc -nostdlib -fno-common -Werror -O2 -fpie -fstack-protector-strong -DSTACK_PROTECTOR -fcf-protection=none -mindirect-branch=thunk-extern -mindirect-branch-register -DCONFIG_RETPOLINE -DHV_DEBUG -DPROFILING_ON -fno-omit-frame-pointer  -gdwarf-2 arch/x86/guest/vlapic.c -o /root/workspace/acrn-hypervisor-premerge-build-image/artifact/out/hv/whl-ipc-i5-uefi/hypervisor/arch/x86/guest/vlapic.o -MMD -MT /root/workspace/acrn-hypervisor-premerge-build-image/artifact/out/hv/whl-ipc-i5-uefi/hypervisor/arch/x86/guest/vlapic.o
arch/x86/guest/vlapic.c:908:1: error: 'vlapic_trigger_lvt' defined but not used [-Werror=unused-function]
  908 | vlapic_trigger_lvt(struct acrn_vlapic *vlapic, uint32_t lvt_index)
      | ^~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make[2]: *** [Makefile:529: /root/workspace/acrn-hypervisor-premerge-build-image/artifact/out/hv/whl-ipc-i5-uefi/hypervisor/arch/x86/guest/vlapic.o] Error 1
make[2]: Leaving directory '/root/workspace/acrn-hypervisor-premerge-build-image/acrn-hypervisor/hypervisor'
make[1]: *** [Makefile:113: hypervisor] Error 2
make[1]: Leaving directory '/root/workspace/acrn-hypervisor-premerge-build-image/acrn-hypervisor'
make: *** [Makefile:238: hypervisor] Error 2

**Comment by HuiHuangShi** [comment]
4 new potential violations to the coding guideline detected. Please help check. Thanks!<br><1> config:sharing_config filename:/hypervisor/arch/x86/guest/virq.c func:acrn_inject_pending_intr offset:426<br> reason:Function return value potentially unused. : guest_irq_enabled<br><2> config:part_config filename:/hypervisor/arch/x86/guest/virq.c func:acrn_inject_pending_intr offset:426<br> reason:Function return value potentially unused. : guest_irq_enabled<br><3> config:part_config filename:/hypervisor/dm/vpic.c func:vpic_init offset:33<br> reason:No prototype for non-static function. : vpic_init<br><4> config:sharing_config filename:/hypervisor/dm/vpic.c func:vpic_init offset:33<br> reason:No prototype for non-static function. : vpic_init<br><br>Name Conflict Violation:<br>ioapic local 215 boot/acpi_base.c<br>ioapic struct 162 include/arch/x86/apicreg.h<br>ioapic member 41 include/common/ptdev.h<br><br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by ClaudZhang1995** [comment]
@lifeix hi .logical_pation test fail. It is fail log link:
http://acrn-jenkins.sh.intel.com:8080/job/acrn-hypervisor-PME_Test_nuc7i7dnb_uefi_logical_partition/248/console

**Comment by ClaudZhang1995** [comment]
@lifeix  please rebase your code .

**Comment by wenlingz** [comment]
have synced with fei, close it

**Pull request closed without merging**
