### PR TITLE
Enable CPU sharing between pre-launch VM and others

### PR DESCRIPTION
**Pull request by shuox**
Enable CPU sharing between pre-launch VM and others

### CODE REVIEW

**Comment by HuiHuangShi** [comment]
No new violations to the coding guideline detected.<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by wenlingz** [comment]
> Will this one conflict with PR5100? We may wait till PR5100 is merged

this PR is on release_2.1 branch

**Comment by fyin1** [comment]
> > Will this one conflict with PR5100? We may wait till PR5100 is merged
> 
> this PR is on release_2.1 branch

Let's check with Victor whether #5100 will be ported to acrn 2.1 or not.

**Comment by fyin1** [comment]
#5100 will not be merged to ACRN 2.1 branch. So let's merge this patch.

**Pull request merged**
