### PR TITLE
hv: pgtable: fix 'Use of function like macro'

### PR DESCRIPTION
**Pull request by shiqingg**
Convert HPA2HVA, HVA2HPA, GPA2HVA and HVA2GPA to inline functions.

v1 -> v2:
 * Modify the following statement.
   rsdp = biosacpi_search_rsdp((char *)hpa2hva((uint64_t)(*addr << 4)),
                                                                0x400);
   Instead of "(uint64_t)(*addr << 4)", "(uint64_t)(*addr) << 4U" would
   be clearer.

Tracked-On: #861
Signed-off-by: Shiqing Gao <shiqing.gao@intel.com>
Reviewed-by: Junjie Mao <junjie.mao@intel.com>

### CODE REVIEW

**Comment by jianlaipinan** [comment]
Ready to merge

**Comment by lijinxia** [comment]
@shiqingg Could you please rebase and fix the conflicts?
@mingqiangchi Could you please review for the conflicts in hypervisor/arch/x86/vmx.c?

**Comment by shiqingg** [comment]
Patch has been rebased. 
The mainly involved conflicts are from the following functions in vmx.c.
exec_vmxon_instr
vmx_off
init_vmcs

**Comment by mingqiangchi** [comment]
LGTM

**Pull request merged**
