### PR TITLE
HV: Fix the missing list_head initializaiton

### PR DESCRIPTION
**Pull request by ZideChen0**
Signed-off-by: Zide Chen <zide.chen@intel.com>

### CODE REVIEW

**Comment by dongyaozu** [comment]
@ZideChen0 please drop this one since the new patches are used

**Comment by lijinxia** [comment]
@ZideChen0 The PR has some merged commits in(0d5405a, e12210a, a1e324c) and 2946fc0 is not a patch. The commit log will get missed up, Could you please rebase properly or re-submit your commits on your folk repo.

**Comment by ZideChen0** [comment]
Yes, I will close it and rebase and push it again. Will double check next time doing PR.

**Comment by gvancuts** [comment]
Hi @ZideChen0 , you don't need to close Pull Request even in case the history has some problems (such as duplicate commits, merge commits, etc.). What you can do, for example is the following:
```
$ git fetch origin # this assumes that origin points at the upstream repo, i.e. github.com/projectacrn/acrn-hypervisor
$ git checkout -b timer_2 origin/master # this creates a new branch where you're starting from a clean history, based on the latest master
$ git cherry-pick <your commit ID from the other branch> # this will try to apply the exact same patch you had in your other branch and apply it here. You may have to resolve some merge issues if your patch conflict with the latest version of maser
$ git push -f <your-fork> +timer_2:timer # this will completely replace the branch that is used as the reference for this PR by your new (cleaned) branch. The PR is then automatically updated with the latest (clean) history.
```

Closing and re-opening a new PR obviously works as well but it's in general better to continue and fix the same PR so that all the history and conversations about it are at the same place.

**Pull request closed without merging**
