### PR TITLE
Cleanup: Don't use HV_DEBUG outside debug dir

### PR DESCRIPTION
**Pull request by lifeix**
@dongyaozu @anthonyzxu @JasonChenCJ

### CODE REVIEW

**Comment by gvancuts** [comment]
I've tried this on various Linux distributions (Clearlinux, Ubuntu 16.04 and Fedora 27*) but it always fails to build the release version (`RELEASE=1`) for uefi (`PLATFORM=uefi`) so :-1: 

*: you need this patch to try it on Fedora/CentOS: https://github.com/projectacrn/acrn-hypervisor/pull/37/commits/cdffa9d08c520dc22332107d0ab2c6fb7366c213 (else it fails for an unrelated reason)

**Comment by lifeix** [comment]
@gvancuts about this error, we should
--- a/include/debug/serial.h
+++ b/include/debug/serial.h
@@ -33,10 +33,14 @@
 
 #ifdef HV_DEBUG
 int serial_init(void);
+void uart16550_set_property(int enabled, int port_mapped, uint64_t base_addr);
 #else
 static inline int serial_init(void) { return 0; }
+static inline void uart16550_set_property(__unused int enabled,
+                                       __unused int port_mapped,
+                                       __unused uint64_t base_addr)
+{
+}
 #endif
 
-void uart16550_set_property(int enabled, int port_mapped, uint64_t base_addr);
-

not just to include uart for release.
Thx

**Comment by gvancuts** [comment]
Not supporting the UART in the release version sounds like the right thing to do to me. Will you add this to this Pull Request?

**Comment by anthonyzxu** [comment]
@gvancuts UART support is not in release version even before this PR

**Comment by anthonyzxu** [comment]
@lifeix please resolve the conflict

**Comment by gvancuts** [comment]
`make PLATFORM=uefi RELEASE=1` is still broken in my testings (tried Ubuntu 16.04, Fedora 27, CentOS 7 and Clearlinux).  Can you fix that before this gets merged?

**Comment by gvancuts** [comment]
> @gvancuts UART support is not in release version even before this PR

Thanks for the clarification!

**Comment by lifeix** [comment]
@anthonyzxu  done
@gvancuts what's your broken meaning ? I didn't have an uefi board, so I can't have a test.

**Comment by anthonyzxu** [comment]
@lifeix 
If you enable serial port , you will see the issue @gvancuts  reported, could you please fix it?

Anthony

diff --git a/bsp/uefi/efi/boot.c b/bsp/uefi/efi/boot.c
index 75e4feb..d158682 100644
--- a/bsp/uefi/efi/boot.c
+++ b/bsp/uefi/efi/boot.c
@@ -444,8 +444,8 @@ again:
        mbi->mi_mmap_length = j*sizeof(struct multiboot_mmap);

        //mbi->mi_cmdline = (UINTN)"uart=mmio@0x92230000";
-       //mbi->mi_cmdline = (UINTN)"uart=port@0x3F8";
-       mbi->mi_cmdline = (UINTN)"uart=disabled";
+       mbi->mi_cmdline = (UINTN)"uart=port@0x3F8";
+       //mbi->mi_cmdline = (UINTN)"uart=disabled";
        mbi->mi_mmap_addr = (UINTN)mmap;

**Comment by JasonChenCJ** [comment]
@gvancuts , after apply all of fei's patches, you should also remove console=ttyS0 & pci_devices_ignore=(0:18:2) in the cmdline for release version.

@lifeix , could you also add a reference acrn-release.conf under bsp/uefi/clearlinux/

**Comment by gvancuts** [comment]
Hi everyone, I will test these new patches a little later today. To be clear, I did not even test this on a real platform. Building the code with both `RELEASE=1` and `PLATFORM=uefi` fails (and I have seen that on all dev OS I've tried so far). Are you able to compile this code as follows: `make RELEASE=1 PLATFORM=uefi`??

**Comment by gvancuts** [comment]
@lifeix , can you send me the complete output of your build (after a `make clean`) to compare this with mine?

A couple of comments:
1. The error I'm getting (which I included above, and pasted below again for your convenience [1]) has nothing to do with EFI.
2. I have run in this `gnu-efi` package missing and I know exactly what error it gives. I have tweaked the [Getting Started Guide](https://projectacrn.github.io/getting_started/index.html#build-acrn-from-source) for a number of different Linux distributions based on those findings (as some need `gnu-efi` but others really need `gnu-efi-devel`).

[1] Error when building with `make PLATFORM=uefi RELEASE=1`:
```
/root/acrn/build/bsp/uefi/cmdline.o: In function `handle_cmd':
/root/acrn/bsp/uefi/cmdline.c:77: undefined reference to `uart16550_set_property'
/root/acrn/bsp/uefi/cmdline.c:87: undefined reference to `uart16550_set_property'
/root/acrn/bsp/uefi/cmdline.c:89: undefined reference to `uart16550_set_property'
collect2: error: ld returned 1 exit status
make: *** [Makefile:196: /root/acrn/build/acrn.out] Error 1
```

**Comment by gvancuts** [comment]
Just got around to re-testing this (now that commit https://github.com/projectacrn/acrn-hypervisor/pull/45/commits/440ee33bea579da136414bde78e88035bb6f041d has been added to the Pull Request) and the issue has been fixed. No more objections from me! 👍

**Pull request merged**
