### PR TITLE
config_tools: Add ivshmem region ID to launch script

### PR DESCRIPTION
**Pull request by zhangckid**
Add missed ivshmem region ID.

Tracked-On: #8645

Reviewed-by: Junjie Mao <junjie.mao@intel.com>

### CODE REVIEW

**Comment by yuhuanX** [comment]
@zhangckid , make[1]: *** [debian/rules:260: override_dh_auto_install-arch] Error 1
make: *** [debian/rules:411: binary] Error 2
dpkg-buildpackage: error: fakeroot debian/rules binary subprocess returned exit status 2
debuild: fatal error at line 1182:
dpkg-buildpackage --rules-target binary -us -uc -ui failed

Please check detailed log in: https://cbjenkins-pg.devtools.intel.com/teams-acrn/job/acrn/view/01-Pre-merge/job/acrn-hypervisor-build-native/57687/console

**Comment by yuhuanX** [comment]
start to build

**Comment by zhangckid** [comment]
Update the patch to setup default region ID as 0

**Review by junjiemao1 — APPROVED** [review]

**Comment by yuhuanX** [comment]
Please 'terryzouhao' or 'NanlinXie' approve this patch

**Review by NanlinXie — APPROVED** [review]

**Comment by yuhuanX** [comment]
start to run premerge test

**Comment by yuhuanX** [comment]
start to run premerge test

**Comment by yuhuanX** [comment]
start to run premerge test

**Comment by yuhuanX** [comment]
@zhangckid , rpl-p-shared-test failed. please check log for detail: https://cbjenkins-pg.devtools.intel.com/teams-acrn/job/acrn/job/rpl-p-shared-test/194/console

root@192168134sos-dom0:/home/auto_script# bash launch_user_vm_id2.sh

pci init ivshmem
ACRN_IOCTL_CREATE_VDEV ioctl() returned an error: Invalid argument
pci ivshmem init failed
vtnet tx thread closing...
mngr_client_new: Failed to accept from fd 36, err: Invalid argument
Stop listening 36...
Stop polling 36...
No correct pm notify channel given
Unable to init vdev (22)

**Comment by zhangckid** [comment]
> @zhangckid , rpl-p-shared-test failed. please check log for detail: https://cbjenkins-pg.devtools.intel.com/teams-acrn/job/acrn/job/rpl-p-shared-test/194/console
> 
> root@192168134sos-dom0:/home/auto_script# bash launch_user_vm_id2.sh
> 
> pci init ivshmem ACRN_IOCTL_CREATE_VDEV ioctl() returned an error: Invalid argument pci ivshmem init failed vtnet tx thread closing... mngr_client_new: Failed to accept from fd 36, err: Invalid argument Stop listening 36... Stop polling 36... No correct pm notify channel given Unable to init vdev (22)

Updated, please check again.

Thanks
Chen

**Comment by yuhuanX** [comment]
start to run premerge test

**Comment by yuhuanX** [comment]
@zhangckid , rpl-p-shared-test still failed.
root@192168134sos-dom0:~# bash /home/auto_script/launch_user_vm_id2.sh
RT TAP device already available, reusing it.
Launch device model with parameters: --cpu_affinity 48,50 -m 1024M --ovmf /usr/share/acrn/bios/OVMF.fd -s 0:0,hostbridge -s 8,ivshmem,hv:/looking_glass_waag,32,0 --virtio_poll 1000000 -s 3,virtio-console,@stdio:stdio_port -s 4,virtio-net,tap=RT,mac_seed=98:4f:ee:18:5e:df-POST_RT_VM1 -s 5,virtio-blk,/root/rt/core-image-weston-intel-corei7-64.wic --rtvm --lapic_pt --logger_setting console,level=4;kmsg,level=3;disk,level=5 POST_RT_VM1
SW_LOAD: get ovmf path /usr/share/acrn/bios/OVMF.fd, size 0x200000
logger: name=console, level=4
logger: name=kmsg, level=3
logger: name=disk, level=5
Found default iasl path: /usr/sbin/iasl
iasl version: 20210105
vm_create: POST_RT_VM1
vm setup asyncio page
vm_setup_memory: size=0x40000000
level 0 free/need pages:9/9 page size:0x200000
level 1 free/need pages:5/1 page size:0x40000000

try to setup hugepage with:
	level 0 - lowmem 0x0, fbmem 0x1000000, biosmem 0x200000, highmem 0x0
	level 1 - lowmem 0x40000000, fbmem 0x0, biosmem 0x0, highmem 0x0
total_size 0x140000000

mmap ptr 0x0x7fd2864c1000 -> baseaddr 0x0x7fd2c0000000
mmap 0x40000000@0x7fd2c0000000
touch 1 pages with pagesz 0x40000000
mmap 0x200000@0x7fd3bfe00000
touch 1 pages with pagesz 0x200000
mmap 0x1000000@0x7fd3bee00000
touch 8 pages with pagesz 0x200000

really setup hugepage with:
	level 0 - lowmem 0x0, biosmem 0x200000, highmem 0x0
	level 1 - lowmem 0x40000000, biosmem 0x0, highmem 0x0
vm_init_vdevs
No pm notify channel given
Listening 36...
polling 36...
pci init hostbridge

pci init virtio-console

pci init virtio-net

pci init virtio-blk

pci init ivshmem

ACRN_IOCTL_CREATE_VDEV ioctl() returned an error: Invalid argument
pci ivshmem init failed
vtnet tx thread closing...
mngr_client_new: Failed to accept from fd 36, err: Invalid argument
Stop listening 36...
Stop polling 36...
No correct pm notify channel given
Unable to init vdev (22)

**Comment by yuhuanX** [comment]
Can one of the admins verify this patch?

**Pull request merged**
