### PR TITLE
crashlogctl

### PR DESCRIPTION
**Pull request by liuxinw**
This patch set is to improve the setup mechanism of ACRN-Crashlog,
including the following aspects:
1. additional feature won't alter default system behavior
2. give the decision-making power to the user on enabling the feature
3. optimize the script
Tracked-On: #1386
Signed-off-by: Miguel Bernal Marin <miguel.bernal.marin@linux.intel.com>
Reviewed-by: Zhi Jin <zhi.jin@intel.com>
Acked-by: Chen Gang <gang.c.chen@intel.com>

### CODE REVIEW

**Comment by miguelinux** [comment]
@NanlinXie I did not open an Issue, it was treated on email only.

**Comment by miguelinux** [comment]
The issue here was to improve chrashlog to be included in Clear Linux

**Comment by miguelinux** [comment]
I just created the issue

https://github.com/projectacrn/acrn-hypervisor/issues/1386

@liuxinw  Can you update the commit messages with **Tracked-On** information.

**Comment by NanlinXie** [comment]
@miguelinux Which issue number should be this PR Tracked-On? #1386 or #1024, or Both?  The Tracked On information in commit information and PR conversation should be identical.

**Comment by liuxinw** [comment]
Sorry for the late response, the tracked-on has been changed to #1386.

**Pull request merged**
