### PR TITLE
HV: cleanup header files under hypervisor dm&common

### PR DESCRIPTION
**Pull request by mcao6**
it removes hypervisor.h and just includes needed header files.

Tracked-On: #1842
Signed-off-by: Minggui Cao <minggui.cao@intel.com>
Acked-by: Eddie Dong <eddie.dong@intel.com>

### CODE REVIEW

**Comment by wenlingz** [comment]
@mcao6 please check your code , please refer below log:
************************************************************
dm/vmptable.c: In function 'mptable_build':
dm/vmptable.c:117:42: error: implicit declaration of function 'per_cpu'; did you mean 'run_vcpu'? [-Werror=implicit-function-declaration]
   mptable->proc_entry_array[i].apic_id = per_cpu(lapic_id, pcpu_id);
                                          ^~~~~~~
                                          run_vcpu
dm/vmptable.c:117:50: error: 'lapic_id' undeclared (first use in this function); did you mean 'lapic_reg'?
   mptable->proc_entry_array[i].apic_id = per_cpu(lapic_id, pcpu_id);
                                                  ^~~~~~~~
                                                  lapic_reg
dm/vmptable.c:117:50: note: each undeclared identifier is reported only once for each function it appears in
cc1: all warnings being treated as errors
make[2]: *** [Makefile:391: /workspace/out/hv/apl-mrb-sbl/hypervisor/dm/vmptable.o] Error 1
make[2]: Leaving directory '/workspace/acrn-hypervisor/hypervisor'
make[1]: Leaving directory '/workspace/acrn-hypervisor'
make[1]: *** [Makefile:50: hypervisor] Error 2
make: *** [Makefile:212: hypervisor] Error 2
Build step 'Execute shell' marked build as failure

**Comment by mcao6** [comment]
updated for build partition mode code

**Comment by HuiHuangShi** [comment]
3 new potential violations to the coding guideline detected. Please help check. Thanks!<br><1> config:common filename:/hypervisor/include/arch/x86/guest/vcpu.h func: offset:311<br> reason:Struct/union not completely specified.       : acrn_vm<br><2> config:common filename:/hypervisor/common/hypercall.c func:inject_msi_lapic_pt offset:425<br> reason:Narrower int conversion without cast. :  (unsigned int and unsigned long): icr.bits.vector = vmsi_data.bits.vector<br><3> config:common filename:/hypervisor/common/hypercall.c func:inject_msi_lapic_pt offset:425<br> reason:Implicit conversion of underlying type (MR). :  (unsigned int and unsigned long): icr.bits.vector = vmsi_data.bits.vector<br><br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by wenlingz** [comment]
@HuiHuangShi please add LDRA check,thanks

**Comment by HuiHuangShi** [comment]
> 3 new potential violations to the coding guideline detected. Please help check. Thanks!
> <1> config:common filename:/hypervisor/include/arch/x86/guest/vcpu.h func: offset:311
> reason:Struct/union not completely specified. : acrn_vm
> <2> config:common filename:/hypervisor/common/hypercall.c func:inject_msi_lapic_pt offset:425
> reason:Narrower int conversion without cast. : (unsigned int and unsigned long): icr.bits.vector = vmsi_data.bits.vector
> <3> config:common filename:/hypervisor/common/hypercall.c func:inject_msi_lapic_pt offset:425
> reason:Implicit conversion of underlying type (MR). : (unsigned int and unsigned long): icr.bits.vector = vmsi_data.bits.vector
> 
> No New Name Conflict
> 
> No New Function Declaration/Definition Mismatch

All of is false positive

**Pull request merged**
