### PR TITLE
vUART two related configuration support

### PR DESCRIPTION
**Pull request by haiwei-li**
vUART Tx/Rx buffer maybe not enough for some testcases. So introduce two options in acrn configurator tool. Rx is 256 and Tx is 8192 by default.

vUART timer is running on BSP now. Introduce an option in acrn configurator tool to set the timer pin to. The default is BSP.

### CODE REVIEW

**Comment by haiwei-li** [comment]
Just wait for the acrn-dev community review to be completed.

**Comment by yuhuanX** [comment]
start to build

**Comment by haiwei-li** [comment]
@junjiemao1 Patch 2/2 is updated. Please reivew, thanks!

**Review by junjiemao1 — APPROVED** [review]

**Review by NanlinXie — APPROVED** [review]

**Comment by yuhuanX** [comment]
start to run premerge test

**Comment by yuhuanX** [comment]
start to run premerge test

**Pull request merged**
