### PR TITLE
Generate C configuration files in build directories

### PR DESCRIPTION
**Pull request by junjiemao1**
The current configuration and build system of the hypervisor suffers from the following challenges.

  1. Both XML configuration files and generated C sources are maintained in
     the git repo for each supported board and scenario. This introduces
     additional burden in maintaining their consistency.

  2. Updating generated C sources will pollute the git-managed files unless
     users specify TARGET_DIR explicitly.

  3. Kconfig still presists though acrn-config already covers all the
     configuration data managed by Kconfig.

This patchset aims at resolving the issues above using the following approaches.

  1. The build system will now generate configuration files in the build
     directory rather than using any existing copies in the code.

  2. Kconfig will be removed. The outputs of Kconfig (i.e. config.h and
     config.mk) will be generated by acrn-config instead.

The changes preserve the command line to generate a build from predefined XMLs in the git repo:

  hypervisor$ make BOARD=ehl-crb-b SCENARIO=hybrid RELEASE=1

The steps can also be split into multiple steps so that users can tweak the configuration before building. After a build directory is configured, there is no need to repeat the variables in the follow-up commands.

  hypervisor$ make BOARD=ehl-crb-b SCENARIO=hybrid defconfig
  hypervisor$ (Invoke the config app to modify build/.config.xml)
  hypervisor$ make

Refer to [PATCH 4/6] for a detailed list of make targets and supported variables. Refer to [PATCH 5/6] for the facilities for applying additional changes to generated C configuration files.

Kconfig-related files in the repo will be removed by a separate PR later.

v3:
 * Adapt the toplevel Makefile to the new build targets

v2:
 * BOARD/SCENARIO now accept either predefined names or paths to an XML
   file. BOARD_FILE/SCENARIO_FILE are now obsoleted and will only be
   effective if BOARD/SCENRAIO are not specified.
 * `defconfig` now generates the configuration files as well
 * Patches to generated configuration files can now be maintained anywhere
   and registered to a build by invoking 'make applydiffconfig'. Refer to
   [PATCH 5/6] for details.
 * Write allocation results to a separate XML file rather than rewriting
   the scenario XML.
 * Add proper SPDX license headers to new files
 * Fix a typo in the message of `oldconfig`

### CODE REVIEW

**Comment by gvancuts** [comment]
Quick note to make sure we do not forget these:
* Additional dependencies: `lxml` and `xsltproc` [1]

I noticed that we cannot use relative paths for the `BOARD` and `SCENARIO` arguments. Absolute paths work correctly.
Using relative paths for `BOARD_FILE` and `SCENARIO_FILE` go a little further but fail somewhere in `hypervisor/scripts/makefile/config.mk`. Can we (easily) allow the use of both relative and absolute paths?

[1] These can be installed on Ubuntu as follows:
```
$ pip3 install --user lxml
$ sudo apt install xsltproc
```

**Comment by junjiemao1** [comment]
> Quick note to make sure we do not forget these:
> 
> * Additional dependencies: `lxml` and `xsltproc` [1]
> 

Thanks for the reminder. We'll update the dependencies in the documentation in a later PR.

> I noticed that we cannot use relative paths for the `BOARD` and `SCENARIO` arguments. Absolute paths work correctly.
> Using relative paths for `BOARD_FILE` and `SCENARIO_FILE` go a little further but fail somewhere in `hypervisor/scripts/makefile/config.mk`. Can we (easily) allow the use of both relative and absolute paths?

I guess you are talking about giving relative paths to the top-level Makefile, as hypervisor/Makefile accepts relative paths via either BOARD/SCENARIO or BOARD_FILE/SCENARIO_FILE. I've updated the PR to properly take care of such relative paths.

**Comment by gvancuts** [comment]
> I guess you are talking about giving relative paths to the top-level Makefile, as hypervisor/Makefile accepts relative paths via either BOARD/SCENARIO or BOARD_FILE/SCENARIO_FILE. I've updated the PR to properly take care of such relative paths.

Yes, that's exactly what I was talking about - thanks for fixing this!

**Review by gvancuts — APPROVED** [review]
Great work!

**Comment by HuiHuangShi** [comment]
No new violations to the coding guideline detected.<br>No New Name Conflict<br>No New Function Declaration/Definition Mismatch

**Comment by wenlingz** [comment]
@dongyaozu @terryzouhao please help approve this PR, thanks

**Comment by dbkinder** [comment]
@wenlingz Note that the CI system needs to have these new dependencies (xsltproc and lxml) added too before this will pass the CI checks.

**Review by terryzouhao — APPROVED** [review]

**Comment by wenlingz** [comment]
> @wenlingz Note that the CI system needs to have these new dependencies (xsltproc and lxml) added too before this will pass the CI checks.

@dbkinder xsltproc and lxml have been added in code build env, make doc don't need these tools, is that OK?

**Comment by junjiemao1** [comment]
> > @wenlingz Note that the CI system needs to have these new dependencies (xsltproc and lxml) added too before this will pass the CI checks.
> 
> @dbkinder xsltproc and lxml have been added in code build env, make doc don't need these tools, is that OK?

@wenlingz This PR alone does not introduce them as additional dependencies to `make doc`. However, we do have plan to use XSLT for document generation in a future PR. How about we handle such impacts in the context of future PRs?

**Comment by wenlingz** [comment]
> > > @wenlingz Note that the CI system needs to have these new dependencies (xsltproc and lxml) added too before this will pass the CI checks.
> > 
> > 
> > @dbkinder xsltproc and lxml have been added in code build env, make doc don't need these tools, is that OK?
> 
> @wenlingz This PR alone does not introduce them as additional dependencies to `make doc`. However, we do have plan to use XSLT for document generation in a future PR. How about we handle such impacts in the context of future PRs?

@junjiemao1 we need add the related explanation in the doc build https://projectacrn.github.io/latest/tutorials/docbuild.html

**Comment by junjiemao1** [comment]
> > > > @wenlingz Note that the CI system needs to have these new dependencies (xsltproc and lxml) added too before this will pass the CI checks.
> > > 
> > > 
> > > @dbkinder xsltproc and lxml have been added in code build env, make doc don't need these tools, is that OK?
> > 
> > 
> > @wenlingz This PR alone does not introduce them as additional dependencies to `make doc`. However, we do have plan to use XSLT for document generation in a future PR. How about we handle such impacts in the context of future PRs?
> 
> @junjiemao1 we need add the related explanation in the doc build https://projectacrn.github.io/latest/tutorials/docbuild.html

David has a separate PR #5652 that updates the documentation.

**Pull request merged**
