### PR TITLE
Modify KBL-NUC/SDC for default build

### PR DESCRIPTION
**Pull request by wenlingz**
Remove default acrn.efi and modify KBL-NUC/sdc for default build 
Tracked-On: #3953
Signed-off-by: wenlingz <wenling.zhang@intel.com>

### CODE REVIEW

**Comment by acrnsi** [comment]
OK to verify

**Comment by acrnsi** [comment]
OK to verify

**Comment by acrnsi** [comment]
OK to verify

**Comment by acrnsi** [comment]
OK to verify

**Comment by acrnsi** [comment]
OK to verify

**Comment by HuiHuangShi** [comment]
No new violations to the coding guideline detected.<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by HuiHuangShi** [comment]
No new violations to the coding guideline detected.<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by wenlingz** [comment]
@fyin1 please help approve this PR, thanks

**Pull request merged**
