### PR TITLE
Change script to enable GVT-d

### PR DESCRIPTION
**Pull request by liujunming**
Change script to enable GVT-d by default.

Tracked-On: #4740

Signed-off-by: Junming Liu <junming.liu@intel.com>

### CODE REVIEW

**Comment by HuiHuangShi** [comment]
No new violations to the coding guideline detected.<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by HuiHuangShi** [comment]
No new violations to the coding guideline detected.<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by binbinwu1** [comment]
Do we need to pass-through gpu for normal UOS by default?

**Comment by binbinwu1** [comment]
@ywan170 What's your comment? Do you think it is OK to add GPU pass-through to both launch scripts by default?

**Pull request closed without merging**
