### PR TITLE
config tool: remove guest_flags in user interface

### PR DESCRIPTION
**Pull request by liuhang-bit**
The concept of guest_flags is hard to understand for users.
    So turn guest_flags into several parameters in config tool
    user interface, list as below:

    GUEST_FLAG_LAPIC_PASSTHROUGH ---> lapic_passthrough
    GUEST_FLAG_IO_COMPLETION_POLLING ---> io_completion_polling
    GUEST_FLAG_VCAT_ENABLED ---> virtual_cat_support
    GUEST_FLAG_SECURE_WORLD_ENABLED ---> secure_world_support
    GUEST_FLAG_HIDE_MTRR ---> hide_mtrr_support
    GUEST_FLAG_NVMX_ENABLED ---> nested_virtualization_support
    GUEST_FLAG_SECURITY_VM ---> security_vm
    GUEST_FLAG_RT ---> vm_type(RTVM)
    GUEST_FLAG_TEE ---> vm_type(TEE_VM)
    GUEST_FLAG_REE ---> vm_type(REE_VM)

    In addition, HV global parameter NVMX_ENABLE is removed
    from user interface, when config tool detects more than
    one VM with nested_virtualization_support, NVMX_ENABLE is
    assigned as 'y' automatically. And Change the corresponding 
    scenario.xml in repo.

    Tracked-On: #6690
    Signed-off-by: hangliu1 <hang1.liu@linux.intel.com>
    Reviewed-by: Junjie Mao <junjie.mao@intel.com>

### CODE REVIEW

**Comment by acrnsi** [comment]
Can one of the admins verify this patch?

**Comment by wenlingz** [comment]
@liuhang-bit please rebase your code, thanks

**Review by NanlinXie — APPROVED** [review]

**Comment by wenlingz** [comment]
@liuhang-bit make doc fail, please refer:
New errors/warnings found, please fix them:
==============================================

/home/acrn/workspace/acrn-hypervisor-build-doc_125/acrn-hypervisor/build/doc/rst/release_notes/release_notes_2.5.rst:112: WARNING: unknown option: hv.FEATURES.NVMX_ENABLED
/home/acrn/workspace/acrn-hypervisor-build-doc_125/acrn-hypervisor/build/doc/rst/release_notes/release_notes_2.5.rst:121: WARNING: unknown option: vm.guest_flags.guest_flag
/home/acrn/workspace/acrn-hypervisor-build-doc_125/acrn-hypervisor/build/doc/rst/tutorials/nvmx_virtualization.rst:127: WARNING: unknown option: hv.FEATURES.NVMX_ENABLED
/home/acrn/workspace/acrn-hypervisor-build-doc_125/acrn-hypervisor/build/doc/rst/tutorials/nvmx_virtualization.rst:156: WARNING: unknown option: vm.guest_flags.guest_flag
/home/acrn/workspace/acrn-hypervisor-build-doc_125/acrn-hypervisor/build/doc/rst/tutorials/nvmx_virtualization.rst:158: WARNING: unknown option: vm.guest_flags.guest_flag
/home/acrn/workspace/acrn-hypervisor-build-doc_125/acrn-hypervisor/build/doc/rst/tutorials/vcat_configuration.rst:37: WARNING: unknown option: vm.guest_flags.guest_flag

make[1]: *** [Makefile:64: html] Error 1
make[1]: Leaving directory '/home/acrn/workspace/acrn-hypervisor-build-doc_125/acrn-hypervisor/doc'
make: *** [Makefile:147: doc] Error 2

**Comment by wenlingz** [comment]
@liuhang-bit dependency patch 120 failed to apply, please check.

**Pull request closed without merging**
