### PR TITLE
dm:add UID parameter for acpidev_pt

### PR DESCRIPTION
**Pull request by weichenli-intel**
Now the acpidev_pt module only use the hid to check the device,it can't
work well if there are more then one instance.

So this patch add UID to identify same type device to fix these issue.

Tracked-On: #6690
Acked-by: Wang, Yu1 <yu1.wang@intel.com>
Signed-off-by: Chenli Wei <chenli.wei@linux.intel.com>

### CODE REVIEW

**Comment by acrnsi** [comment]
Can one of the admins verify this patch?

**Comment by wenlingz** [comment]
@ywan170 please approve this PR, thanks

**Comment by wenlingz** [comment]
@ywan170 @anthonyzxu please help approve this PR, thanks

**Review by ywan170 — APPROVED** [review]

**Comment by ywan170** [comment]
@weichenli-intel do we need also update relative document? The current parameter doesn't mentioned the "hid,uid" format of mmio device passthrough, right?

**Comment by weichenli-intel** [comment]
> @weichenli-intel do we need also update relative document? The current parameter doesn't mentioned the "hid,uid" format of mmio device passthrough, right?

Yes, I will update the doc by another PR, the doc and dm are splited patch.

**Pull request merged**
