### PR TITLE
acrn: allow to specify the build output folder

### PR DESCRIPTION
**Pull request by jren1**
Usages: make O=<any folder>

Signed-off-by: Jack Ren <jack.ren@intel.com>

### CODE REVIEW

**Comment by gvancuts** [comment]
Hi @jren1 , what is the purpose of this patch (besides renaming the `BUILD_DIR` variable to `O` - which I find less intuitive, but I can live with that)?

Is it fixing any issue you've observed?

**Comment by gvancuts** [comment]
Just to give you more context, the `BUILD_DIR` variable was introduced (by me) in PR #225 specifically to allow people to set the build directory (the logic was not in place). PR #257 (finally) adds a little text to explain how to use this (see [this line](https://github.com/projectacrn/acrn-hypervisor/pull/257/files#diff-f25f8087f145213406fc67b2c7c42cb1R397).

**Comment by gvancuts** [comment]
> @gvancuts The clear Linux team complainted that they tried to build both SBL and UEFI platform, but they are over written by each other:
> Command as below (Please try):-
> make PLATFORM=uefi HV_OBJDIR=uefi RELEASE=0
> make PLATFORM=sbl HV_OBJDIR=sbl RELEASE=0
> The output still is inside build and the sbl will overwrite the uefi.
> This patch can solve that issue by simply specifying O=sbl o O=uefi in make command line.
> That patch is waiting for Clear Linux to verify whether it can solve their issue.

This is exactly what my PR (#225) was addressing, is there any reason why they cannot use `make BUILD_DIR=build-uefi` or `make BUILD_DIR=build-sbl` today?

**Comment by jren1** [comment]
Got your context. but we can update the document to tell the people to use O= to put the objects files to anywhere and don't need to modify the Makefile, right?

**Comment by gvancuts** [comment]
> Got your context. but we can update the document to tell the people to use O= to put the objects files to anywhere and don't need to modify the Makefile, right?

They don't need to modify the Makefile today. All they need to do is set the BUILD_DIR variable to whatever they want, e.g.:
   $ make BUILD_DIR=build-uefi PLATFORM=uefi RELEASE=0
   $ make BUILD_DIR=build-sbl PLATFORM=sbl RELEASE=0
And the corresponding build artefacts will be placed in respectively 'build-uefi' and 'build-sbl'.

What I mean is that the feature you are proposing with your patch is already there so unless it's somehow broken, I don't see why we need it. Does that clarify?

**Comment by jren1** [comment]
But that still limit the output folder under acrn-hypervisor folder. For our internal E2E build, the output folder is even not in acrn-hypervisor folder.

**Comment by jren1** [comment]
@miguelinux please help verify whether this patch can allow you to build both sbl and uefi platform in autospec.

**Comment by jren1** [comment]
from @miguelinux ：
”
Looks like it could work.

I will do a PR to add other changes, please merge your patch.
“

**Pull request merged**
