### PR TITLE
HV: introduce relative vm id for hcall api

### PR DESCRIPTION
**Pull request by jsun26intel**
On SDC scenario, SOS VM id is fixed to 0 so some hypercalls from guest
    are using hardcoded "0" to represent SOS VM, this would bring issues
    for HYBRID scenario which SOS VM id is non-zero.
    
    Now introducing a new VM id concept for DM/VHM hypercall APIs, that
    return a relative VM id which is from SOS view when create VM for post-
    launched VMs. DM/VHM could always treat their own vm id is "0". When they
    make hypercalls, hypervisor will convert the VM id to the absolute id
    when dispatch the hypercalls.
    
Tracked-On: #3214
    
Signed-off-by: Victor Sun <victor.sun@intel.com>
Acked-by: Eddie Dong <eddie.dong@Intel.com>

### CODE REVIEW

**Comment by acrnsi** [comment]
OK to verify

**Comment by HuiHuangShi** [comment]
8 new potential violations to the coding guideline detected. Please help check. Thanks!<br><1> config:sharing_config filename:/hypervisor/arch/x86/guest/vmcall.c func:dispatch_sos_hypercall offset:22<br> reason:Pointer param should be declared pointer to const. : vcpu<br><2> config:part_config filename:/hypervisor/arch/x86/guest/vmcall.c func:dispatch_sos_hypercall offset:22<br> reason:Pointer param should be declared pointer to const. : vcpu<br><3> config:common filename:/hypervisor/arch/x86/guest/vmcall.c func:dispatch_sos_hypercall offset:22<br> reason:Procedure exceeds 200 source lines of code.  : dispatch_sos_hypercall<br><4> config:common filename:/hypervisor/arch/x86/guest/vmcall.c func:dispatch_sos_hypercall offset:22<br> reason:Cyclomatic complexity greater than 20.<br><5> config:common filename:/hypervisor/arch/x86/guest/vmcall.c func:dispatch_sos_hypercall offset:119<br> reason:Cast to an unrelated type. : (unsigned long* to struct acrn_irqline_ops*): ( struct acrn_irqline_ops * ) & param2<br><6> config:common filename:/hypervisor/arch/x86/guest/vmcall.c func:dispatch_sos_hypercall offset:119<br> reason:Casting operation to a pointer. : (unsigned long* to struct acrn_irqline_ops*): ( struct acrn_irqline_ops * ) & param2<br><7> config:common filename:/hypervisor/arch/x86/guest/vmcall.c func:dispatch_sos_hypercall offset:119<br> reason:Casting operation on a pointer. : (unsigned long* to struct acrn_irqline_ops*): ( struct acrn_irqline_ops * ) & param2<br><8> config:common filename:/hypervisor/common/hypercall.c func:hcall_get_cpu_pm_state offset:1048<br> reason:Implicit conversion: actual to formal param (MR). :  (unsigned long and unsigned short):  param  2<br><br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by acrnsi** [comment]
OK to verify

**Comment by acrnsi** [comment]
OK to verify

**Comment by acrnsi** [comment]
OK to verify

**Comment by acrnsi** [comment]
OK to verify

**Comment by HuiHuangShi** [comment]
out of license

**Comment by HuiHuangShi** [comment]
6 new potential violations to the coding guideline detected. Please help check. Thanks!<br><1> config:common filename:/hypervisor/arch/x86/guest/vmcall.c func:dispatch_sos_hypercall offset:22<br> reason:Procedure exceeds 200 source lines of code.  : dispatch_sos_hypercall<br><2> config:common filename:/hypervisor/arch/x86/guest/vmcall.c func:dispatch_sos_hypercall offset:22<br> reason:Cyclomatic complexity greater than 20.<br><3> config:common filename:/hypervisor/arch/x86/guest/vmcall.c func:dispatch_sos_hypercall offset:119<br> reason:Cast to an unrelated type. : (unsigned long* to struct acrn_irqline_ops*): ( struct acrn_irqline_ops * ) & param2<br><4> config:common filename:/hypervisor/arch/x86/guest/vmcall.c func:dispatch_sos_hypercall offset:119<br> reason:Casting operation to a pointer. : (unsigned long* to struct acrn_irqline_ops*): ( struct acrn_irqline_ops * ) & param2<br><5> config:common filename:/hypervisor/arch/x86/guest/vmcall.c func:dispatch_sos_hypercall offset:119<br> reason:Casting operation on a pointer. : (unsigned long* to struct acrn_irqline_ops*): ( struct acrn_irqline_ops * ) & param2<br><6> config:common filename:/hypervisor/common/hypercall.c func:hcall_get_cpu_pm_state offset:1048<br> reason:Implicit conversion: actual to formal param (MR). :  (unsigned long and unsigned short):  param  2<br><br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Pull request merged**
