### PR TITLE
config_tools: scenario setting UI with xsd schema config

### PR DESCRIPTION
**Pull request by szhen11**
render scenario setting UI with xsd schema config, validate scenario setting with xsd validation.
update config app when creating new scenarios according to folder reorg

Tracked-On: #5672

Signed-off-by: Shuang Zheng <shuang.zheng@intel.com>
Reviewed-by: Mao, Junjie <junjie.mao@intel.com>
Reviewed-by: Victor Sun <victor.sun@intel.com>

### CODE REVIEW

**Comment by HuiHuangShi** [comment]
No new violations to the coding guideline detected.<br>No New Name Conflict<br>No New Function Declaration/Definition Mismatch

**Comment by wenlingz** [comment]
@terryzouhao please help approve this PR, thanks

**Review by terryzouhao — APPROVED** [review]

**Comment by HuiHuangShi** [comment]
No new violations to the coding guideline detected.<br>No New Name Conflict<br>No New Function Declaration/Definition Mismatch

**Comment by HuiHuangShi** [comment]
No new violations to the coding guideline detected.<br>No New Name Conflict<br>No New Function Declaration/Definition Mismatch

**Pull request merged**
