### PR TITLE
hv: refine coding style for ucode.c

### PR DESCRIPTION
**Pull request by yonghuah**
- reduce exit points for 'acrn_update_ucode()' function.

Tracked-On: #2095
Signed-off-by: Yonghua Huang <yonghua.huang@intel.com>
Acked-by: Eddie Dong <eddie.dong@intel.com>

### CODE REVIEW

**Comment by HuiHuangShi** [comment]
2096<br>2 new potential violations to the coding guideline detected. Please help check. Thanks!  <br><br>1.filename:/hypervisor/arch/x86/guest/ucode.c&nbsp;&nbsp;function:acrn_update_ucode&nbsp;&nbsp;offset:67:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Cast from pointer to integral type. : (unsigned char* to unsigned long): ( uint64_t ) & micro_code [ 0 ]<br><br>2.filename:/hypervisor/arch/x86/guest/ucode.c&nbsp;&nbsp;function:acrn_update_ucode&nbsp;&nbsp;offset:67:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:No cast for widening complex int expression (MR). :  (unsigned char and unsigned long):  param  2<br><br>

**Comment by yonghuah** [comment]
@HuiHuangShi @shiqingg  have update this PR, thanks.

**Comment by HuiHuangShi** [comment]
2096<br>No new violations to the coding guideline detected.

**Comment by yonghuah** [comment]
@wenlingz  have updated ext-id, pls review, thanks.

**Pull request merged**
