### PR TITLE
Fix a small typo

### PR DESCRIPTION
**Pull request by shrmrf**
Fixes a small typo. See also https://github.com/projectacrn/projectacrn.github.io/pull/18

### CODE REVIEW

**Comment by dbkinder** [comment]
@nanlin We should have a CI check that verifies a signed-off by line is in the commit message

**Comment by shrmrf** [comment]
@dbkinder and @gvancuts sorry, I went offline for a few days. 

I updated the commit string and force-pushed to my branch.

**Comment by shrmrf** [comment]
@dbkinder I _have_ in the past contributed (with this `noreply` address that Github generates) to this project.

I don't mind changing my email ID but this is my avoid-spam strategy.

**Comment by dbkinder** [comment]
OK.  I won't hold up this (trivial) PR because of this, but @hwang37 @NanlinXie Can you provide guidance for the validity of the signed-off-by email address.  My understanding is that a valid email address is expected.

**Comment by shrmrf** [comment]
@dbkinder thanks... :+1: 

Jack once told me to use my Github address (https://github.com/projectacrn/acrn-hypervisor/pull/52#issuecomment-378579495)

**Comment by dbkinder** [comment]
Yes. Your signed-off-by email address must match your GitHub account email, and that should be a valid email address where you can be reached.

**Pull request merged**
