### PR TITLE
doc: update CODEOWNERS for tech docs

### PR DESCRIPTION
**Pull request by dbkinder**
Replace Deb (deb-intel) with Ben (fitchbe)for technical writer/reviewer

Tracked-On: #5581

Signed-off-by: David B. Kinder <david.b.kinder@intel.com>

### CODE REVIEW

**Comment by dbkinder** [comment]
[External_System_ID] ACRN-4759

**Comment by dbkinder** [comment]
@wenlingz @NanlinXie Why the MISRA-C_Check failure?

**Comment by HuiHuangShi** [comment]
No new violations to the coding guideline detected.<br>No New Name Conflict<br>No New Function Declaration/Definition Mismatch

**Comment by wenlingz** [comment]
> @wenlingz @NanlinXie Why the MISRA-C_Check failure?

fixed

**Review by gvancuts — APPROVED** [review]
Thanks! And welcome onboard @fitchbe

**Pull request merged**
