### PR TITLE
Modify the maintainer of each sub directory

### PR DESCRIPTION
**Pull request by NanlinXie**
Modify the maintainer of each sub directory

Tracked-On: #3419
Signed-off-by: Xie, nanlin <nanlin.xie@intel.com>

### CODE REVIEW

**Comment by leilu** [comment]
OK to verify

**Comment by dongyaozu** [comment]
@NanlinXie remove my name from device model side?

**Comment by NanlinXie** [comment]
@dongyaozu  Done.

**Comment by acrnsi** [comment]
OK to verify

**Comment by binbinwu1** [comment]
@NanlinXie  Will the maintainers get notification when there are Merge Requests accordingly?

**Comment by HuiHuangShi** [comment]
No new violations to the coding guideline detected.<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Pull request merged**
