### PR TITLE
Remove the assume of virtio-net device name

### PR DESCRIPTION
**Pull request by weichenli-intel**
Now, the DM assumes the device name entered by user is dependent on
the type.

For example, the device of tap type is named tap_TAAG, this patch
remove the above assumption.

User could set any name, no matter the code of DM or actually created,
it is represented by user input.

Commit 1. DM remove the assume logic of device name.

Commit 2. Config tool also change the generation logic of  launch script .

Commit 3. Fix the issue that got wrong device name after specifying mac address

### CODE REVIEW

**Comment by acrnsi** [comment]
Can one of the admins verify this patch?

**Comment by wenlingz** [comment]
@ywan170 please help approve this PR, thanks

**Review by ywan170 — APPROVED** [review]

**Comment by szhen11** [comment]
@weichenli-intel @Kunhui-Li PR #7185 and PR #7189 are failed by CI. Please make them as one PR if they have dependency in acrn-hypervisor repo.

**Comment by GGGZZZRRR** [comment]
test failed: no ip in guest

**Review by NanlinXie — APPROVED** [review]

**Comment by weichenli-intel** [comment]
> @weichenli-intel @Kunhui-Li PR #7185 and PR #7189 are failed by CI. Please make them as one PR if they have dependency in acrn-hypervisor repo.

Done

**Comment by weichenli-intel** [comment]
> test failed: no ip in guest

Now we merged two PR, pls test the unified PR again, thanks.

**Comment by GGGZZZRRR** [comment]
When both mac and mac_seed in the launch script, WaaG ip changes，can not scan WaaG ip by nmap mac

**Comment by weichenli-intel** [comment]
> When both mac and mac_seed in the launch script, WaaG ip changes，can not scan WaaG ip by nmap mac

As we offline check, this is the issue of mac address conflict.

**Comment by szhen11** [comment]
virtio-net config for waag:      `add_virtual_device                       3 virtio-net tap=WaaG,mac=00:16:3E:77:A9:37,mac_seed=${mac:0:17}-POST_STD_VM1`
No IP for WaaG, this issue is not reproduced on master branch(commit id: 4eb14e7a0).

From Service VM:
root@1921681206sos-dom0:/home/auto_script# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: sit0@NONE: <NOARP> mtu 1480 qdisc noop state DOWN group default qlen 1000
    link/sit 0.0.0.0 brd 0.0.0.0
3: acrn-br0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 8a:16:27:de:c7:7d brd ff:ff:ff:ff:ff:ff
    inet 192.168.1.206/24 brd 192.168.1.255 scope global dynamic acrn-br0
       valid_lft 41896sec preferred_lft 41896sec
    inet6 fe80::8816:27ff:fede:c77d/64 scope link
       valid_lft forever preferred_lft forever
4: tap0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc pfifo_fast master acrn-br0 state DOWN group default qlen 1000
    link/ether 0a:91:44:04:50:0d brd ff:ff:ff:ff:ff:ff
5: enp88s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq master acrn-br0 state UP group default qlen 1000
    link/ether 54:b2:03:9f:3e:6d brd ff:ff:ff:ff:ff:ff
6: WaaG: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/ether e6:58:ea:cf:f2:96 brd ff:ff:ff:ff:ff:ff

launch log:
root@1921681206sos-dom0:/home/auto_script# bash launch_user_vm_id1.sh
Error: argument "WaaG,mac=00:16:3E:77:A9:37" is wrong: "dev" not a valid ifname
acrn-br0 bridge already exists, adding new WaaG,mac=00:16:3E:77:A9:37 TAP device to it...
Cannot find device "WaaG,mac=00:16:3E:77:A9:37"
Cannot find device "WaaG,mac=00:16:3E:77:A9:37"
Cannot find device "WaaG,mac=00:16:3E:77:A9:37"
Launch device model with parameters: --windows --cpu_affinity 0,2 -m 4096M --ovmf /usr/share/acrn/bios/OVMF.fd -s 1:0,lpc -s 0:0,hostbridge -s 3,virtio-net,tap=WaaG,mac=00:16:3E:77:A9:37,mac_seed=54:b2:03:9f:3e:6d-POST_STD_VM1 -s 4,virtio-blk,/root/waag/win10-ltsc.img -s 2,passthru,0/2/0 --logger_setting console,level=4;kmsg,level=3;disk,level=5 POST_STD_VM1
SW_LOAD: get ovmf path /usr/share/acrn/bios/OVMF.fd, size 0x200000

@Kunhui-Li  please check the launch script error.

**Comment by Kunhui-Li** [comment]
@szhen11 I have tried that the issue can be found in the master branch. The log is as follows.
Could you help file a Jira issue to track and fix it?
`root@192168132sos-dom0:~# bash /home/auto_script/launch_user_vm_id1.sh
Error: argument "tap_WaaG,mac=00:16:3E:77:A9:41" is wrong: "dev" not a valid ifname
acrn-br0 bridge already exists, adding new tap_WaaG,mac=00:16:3E:77:A9:41 TAP device to it...
Cannot find device "tap_WaaG,mac=00:16:3E:77:A9:41"
Cannot find device "tap_WaaG,mac=00:16:3E:77:A9:41"
Cannot find device "tap_WaaG,mac=00:16:3E:77:A9:41"`

**Comment by szhen11** [comment]
@Kunhui-Li as debugged with you, the WaaG IP issue is related to the generated launch script, please update fix in this PR.

**Comment by Kunhui-Li** [comment]
> @Kunhui-Li as debugged with you, the WaaG IP issue is related to the generated launch script, please update fix in this PR.

Updated

**Pull request merged**
