### PR TITLE
DM: Add in build for acrn manager, acrnlog and acrntrace

### PR DESCRIPTION
**Pull request by YinThong**
acrn-manager = tools/acrn-manager
acrnlog = tools/acrnlog
acrntrace = tools/acrntrace

Reviewed-by: Eddie Dong <eddie.dong@intel.com>
Signed-off-by: Choong Yin Thong <yin.thong.choong@intel.com>

### CODE REVIEW

**Comment by YinThong** [comment]
rebased

**Comment by jren1** [comment]
Please rework the patch, it failed to build because tools has been move out of devicemodel:

make -C tools/acrn-manager
make: *** tools/acrn-manager: No such file or directory.  Stop.
make: *** [acrnctl] Error 2

**Comment by YinThong** [comment]
The entire directory is changes. Base on this latest directory tree the tools seem is independence. Therefore, i should make the changes on the main makefile, no in the devicemodel makefile. Make sense?

**Comment by YinThong** [comment]
Ok i just review the main Makefile my changes is no required anymore. please kindly drop this PR.
tools:
        mkdir -p $(TOOLS_OUT)
        cd $(T)/tools/acrnlog; \
        make OUT_DIR=$(TOOLS_OUT);
        cd $(T)/tools/acrn-manager; \
        make OUT_DIR=$(TOOLS_OUT);
        cd $(T)/tools/acrntrace; \
        make OUT_DIR=$(TOOLS_OUT);

**Comment by dongyaozu** [comment]
@YinThong  Then please drop this PR.

**Comment by jren1** [comment]
@YinThong please drop the PR

**Pull request closed without merging**
