### PR TITLE
Doc: Launch Windows as the Guest VM

### PR DESCRIPTION
**Pull request by fuzhongl**
Part of unsupported parameters for the latest ACRN-DM code are removed.

Signed-off-by: fuzhongl <fuzhong.liu@intel.com>

### CODE REVIEW

**Review by gvancuts — CHANGES_REQUESTED** [review]
There are a few other tweaks we should make while we're updating this document:
* Remove the `"64 448 8"` parameter passed to `launch_win()` in the script
* I guess there should be a space instead of a dot in this sentence " the Intel DCH Graphics Driver.in Windows"?
* "Prepare WaaG lauch script" -> "Prepare WaaG launch script"
* "Lauch WaaG" -> "Launch WaaG"
* The lines referenced in the "Remove following lines in launch_win.sh" section do not match what's in the script
* The slot numbers at the bottom of the document do not match the script we provide above
* The name of the Windows installation disk (ISO) is referenced three times... and three times with different name (`windows10.iso`, `Windows10.iso` and `windows.iso`)... need to unify them
* `-s 7,passthru,0/14/0,d3hot_reset` is not explained and there is zero reference to `d3hot_reset` in our documentation

**Comment by dbkinder** [comment]
... there's also a misspelling of ``BIOS`` as ``BOIS``...

**Comment by dbkinder** [comment]
@fuzhongl I updated your branch with some misspellings I found (such as "BOIS"), and fixed these items @gvancuts mentioned:

* I guess there should be a space instead of a dot in this sentence " the Intel DCH Graphics Driver.in Windows"?
* "Prepare WaaG lauch script" -> "Prepare WaaG launch script"
* "Lauch WaaG" -> "Launch WaaG"

**Comment by fuzhongl** [comment]
> There are a few other tweaks we should make while we're updating this document:
> 
> * Remove the `"64 448 8"` parameter passed to `launch_win()` in the script
> * I guess there should be a space instead of a dot in this sentence " the Intel DCH Graphics Driver.in Windows"?
> * "Prepare WaaG lauch script" -> "Prepare WaaG launch script"
> * "Lauch WaaG" -> "Launch WaaG"
> * The lines referenced in the "Remove following lines in launch_win.sh" section do not match what's in the script
> * The slot numbers at the bottom of the document do not match the script we provide above
> * The name of the Windows installation disk (ISO) is referenced three times... and three times with different name (`windows10.iso`, `Windows10.iso` and `windows.iso`)... need to unify them
> * `-s 7,passthru,0/14/0,d3hot_reset` is not explained and there is zero reference to `d3hot_reset` in our documentation

@gvancuts 
Done, except for **The lines referenced in the "Remove following lines in launch_win.sh" section do not match what's in the script**

It matches with following steps(After copy install_win.sh to launch_win.sh )
```
#. Prepare WaaG launch script

   cp /home/acrn/work/install_win.sh  /home/acrn/work/launch_win.sh

   Remove following lines in launch_win.sh

   .. code-block:: bash

      -s 5,ahci,cd:./Windows10.iso \
      -s 6,ahci,cd:./winvirtio.iso \
```

**Comment by fuzhongl** [comment]
> @fuzhongl I updated your branch with some misspellings I found (such as "BOIS"), and fixed these items @gvancuts mentioned:
> 
> * I guess there should be a space instead of a dot in this sentence " the Intel DCH Graphics Driver.in Windows"?
> * "Prepare WaaG lauch script" -> "Prepare WaaG launch script"
> * "Lauch WaaG" -> "Launch WaaG"

@dbkinder Thanks for help!

**Review by dbkinder — APPROVED** [review]
LGTM, thanks!

**Comment by gvancuts** [comment]
> @gvancuts
> Done, except for **The lines referenced in the "Remove following lines in launch_win.sh" section do not match what's in the script**
> 
> It matches with following steps(After copy install_win.sh to launch_win.sh )
> 
> ```
> #. Prepare WaaG launch script
> 
>    cp /home/acrn/work/install_win.sh  /home/acrn/work/launch_win.sh
> 
>    Remove following lines in launch_win.sh
> 
>    .. code-block:: bash
> 
>       -s 5,ahci,cd:./Windows10.iso \
>       -s 6,ahci,cd:./winvirtio.iso \
> ```

Thanks @fuzhongl . Unless I missed it, these are the lines you need to remove:
```
-s 5,ahci,cd:/home/acrn/work/Windows10.iso \
-s 6,ahci,cd:/home/acrn/work/winvirtio.iso \
```

Note the use of full paths vs. relative paths.

**Comment by fuzhongl** [comment]
> > @gvancuts
> > Done, except for **The lines referenced in the "Remove following lines in launch_win.sh" section do not match what's in the script**
> > It matches with following steps(After copy install_win.sh to launch_win.sh )
> > ```
> > #. Prepare WaaG launch script
> > 
> >    cp /home/acrn/work/install_win.sh  /home/acrn/work/launch_win.sh
> > 
> >    Remove following lines in launch_win.sh
> > 
> >    .. code-block:: bash
> > 
> >       -s 5,ahci,cd:./Windows10.iso \
> >       -s 6,ahci,cd:./winvirtio.iso \
> > ```
> 
> Thanks @fuzhongl . Unless I missed it, these are the lines you need to remove:
> 
> ```
> -s 5,ahci,cd:/home/acrn/work/Windows10.iso \
> -s 6,ahci,cd:/home/acrn/work/winvirtio.iso \
> ```
> 
> Note the use of full paths vs. relative paths.

@gvancuts Sorry for not aware paths issue.
Fixed with new PR: https://github.com/projectacrn/acrn-hypervisor/pull/5894
Thanks for help!

**Pull request merged**
