### PR TITLE
acrn-config: InverVM communication support

### PR DESCRIPTION
**Pull request by yuchuyang**
Config-6523_ivshmem_doorbell
Config-6712_ivshmem_dev_sos

- Enable ivshmeme for SOS VM
- Allocate vbar 1 for pre-launched and SOS VM

Tracked-On: #5426
Signed-off-by: Yang, Yu-chu <yu-chu.yang@intel.com>

### CODE REVIEW

**Comment by HuiHuangShi** [comment]
No new violations to the coding guideline detected.<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by yuchuyang** [comment]
[External_System_ID]ACRN-6523
[External_System_ID]ACRN-6712

**Review by terryzouhao — COMMENTED** [review]
@yuchuyang could you create git issue and track-on for this PR, thanks.

**Comment by HuiHuangShi** [comment]
No new violations to the coding guideline detected.<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by HuiHuangShi** [comment]
No new violations to the coding guideline detected.<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by HuiHuangShi** [comment]
No new violations to the coding guideline detected.<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by HuiHuangShi** [comment]
No new violations to the coding guideline detected.<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by HuiHuangShi** [comment]
No new violations to the coding guideline detected.<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by NanlinXie** [comment]
Unit Test passed.

**Review by terryzouhao — APPROVED** [review]

**Pull request merged**
