### PR TITLE
Update copyright year range in code headers

### PR DESCRIPTION
**Pull request by zihengL1**
Modified the copyright year range in code, and corrected "int32_tel"
into "Intel" in two "hypervisor/include/debug/profiling.h" and
"hypervisor/include/debug/profiling_internal.h".

Tracked-On: #7559
Signed-off-by: Ziheng Li <ziheng.li@intel.com>

### CODE REVIEW

**Comment by acrnsi** [comment]
Can one of the admins verify this patch?

**Comment by NanlinXie** [comment]
@dbkinder  and @gvancuts , any more comments for this PR?

**Review by dbkinder — APPROVED** [review]
Some of the copyright year changes don't agree with what GitHub says is the last update, but this is better.  
For example, GitHub says ``misc/services/acrn_manager/acrnctl.h`` was last modified in 2021, but you're updating the copyright year to be 2022 (for every file in this PR). Is that OK with you @NanlinXie ?

```
git log -1 --format="%ad" --date=format:"%Y/%m/%d" misc/services/acrn_manager/acrnctl.h
2021/12/08
```
Of course, acrnctl.h  (and any other that was last modified before 2022) will now be indeed modified in 2022 by this PR. :)

**Review by NanlinXie — APPROVED** [review]

**Review by ywan170 — APPROVED** [review]

**Review by lifeix — APPROVED** [review]

**Comment by NanlinXie** [comment]
> Of course, acrnctl.h (and any other that was last modified before 2022) will now be indeed modified in 2022 by this PR. :)
Yes, that's why we think it make sense to change all modified file in this PR to 2022:).

**Pull request merged**
