### PR TITLE
config-tools: get the proper MAX_MSIX_TABLE_NUM

### PR DESCRIPTION
**Pull request by yuchuyang**
Calculates MAX_MSIX_TABLE_NUM based on max(counts of msi, table_size of msi-x)

### CODE REVIEW

**Comment by yuchuyang** [comment]
@wenlingz please hold this PR. Thank you so much.

**Comment by NanlinXie** [comment]
@Kunhui-Li , please help on verification.

**Comment by wenlingz** [comment]
@yuchuyang please notify me once this PR can be merged, thanks

**Comment by yuchuyang** [comment]
@wenlingz  please help to merge https://github.com/projectacrn/acrn-hypervisor/pull/6286 if there is no issues.
Then this PR can be merged afterwards, thank you.

**Comment by wenlingz** [comment]
@terryzouhao please help approve this PR, thanks

**Review by terryzouhao — APPROVED** [review]

**Pull request merged**
