### PR TITLE
HV: allow disabling serial port via Kconfig

### PR DESCRIPTION
**Pull request by gvancuts**
This patch allows to disable the serial port directly from Kconfig. This used
to only be possible from the command-line (by passing "uart=disabled"). To
disable the serial port via Kconfig, simply unselect the "Serial IO type"
option.

Tracked-On: #1481
Signed-off-by: Geoffroy Van Cutsem <geoffroy.vancutsem@intel.com>

### CODE REVIEW

**Comment by gvancuts** [comment]
I tested this on a KBL NUC and I do not see any serial output when leaving out the Serial I/O config through menuconfig.

**Comment by HuiHuangShi** [comment]
1931 <br>The PR does not touch any hypervisor source file. Skip coding guideline checks.<br>

**Comment by JasonChenCJ** [comment]
@gvancuts , you may be need check why checks fail here.

**Comment by HuiHuangShi** [comment]
1931 <br>The PR does not touch any hypervisor source file. Skip coding guideline checks.<br>

**Comment by gvancuts** [comment]
Sorry about that @JasonChenCJ , I did not realise it changed the default value.

I have updated the patch to re-enable the Serial Port for the boards we support. Note that if there are board configurations not captured in the source code tree, the serial port will have to be enabled for them by updating their `*.config` file (or via `make menuconfig`).

I'll keep an eye on the CI checks to make sure they pass this time.

**Comment by HuiHuangShi** [comment]
1931 <br>The PR does not touch any hypervisor source file. Skip coding guideline checks.<br>

**Comment by gvancuts** [comment]
@JasonChenCJ @NanlinXie , can you help understand why the CI checks are failing? It looks like we're not seeing the `ACRN:\> ` prompt on the MRB serial line, which could indicate a problem with the serial port config. I do not have an MRB at hand to test this but when I compile the hypervisor using `make hypervisor PLATFORM=sbl RELEASE=0` (which is what the CI system does) and then inspect the `.config` that is left in the build folder, I see these options:
```
CONFIG_SERIAL_MMIO=y
CONFIG_SERIAL_MMIO_BASE=0xfc000000
```
So what could be the reason it's failing?

Note: I noticed this warning when the CI system compiles the `acrn-crashlog` tool (most likely completely unrelated to the failure):
```
make[3]: Entering directory '/workspace/acrn-hypervisor/tools/acrn-crashlog'
Package libtelemetry was not found in the pkg-config search path.
Perhaps you should add the directory containing `libtelemetry.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libtelemetry' found
```
Is the CI system not using Clear Linux to compile ACRN?

**Comment by HuiHuangShi** [comment]
1931 <br>The PR does not touch any hypervisor source file. Skip coding guideline checks.<br>

**Comment by HuiHuangShi** [comment]
1931 <br>The PR does not touch any hypervisor source file. Skip coding guideline checks.<br>

**Pull request merged**
