### PR TITLE
Shebang configurator

### PR DESCRIPTION
**Pull request by gvancuts**
Add shebang header to `acrn_configurator.py`, make it executable and update the documentation accrodingly.

Tracked-On: #7057

### CODE REVIEW

**Comment by acrnsi** [comment]
Can one of the admins verify this patch?

**Review by dbkinder — APPROVED** [review]
Ok, but I really wanted to track this for the next gen configurator work @junjiemao1

**Review by amyreye — APPROVED** [review]

**Comment by junjiemao1** [comment]
Got it. Will do similarly for the next-gen.

**Comment by wenlingz** [comment]
@NanlinXie please help approve this PR, thanks

**Review by NanlinXie — APPROVED** [review]

**Pull request merged**
