### PR TITLE
Vq count

### PR DESCRIPTION
**Pull request by blegowsk**
For review please see: 
https://lists.projectacrn.org/g/acrn-dev/topic/28286521#15087
https://lists.projectacrn.org/g/acrn-dev/message/14902

Tracked-On: #1915

### CODE REVIEW

**Comment by HuiHuangShi** [comment]
1916 <br>The PR does not touch any hypervisor source file. Skip coding guideline checks.<br>

**Comment by dongyaozu** [comment]
Please add right "reviewed-by" or "Acked-by" if you already got. Otherwise, please ping maintainers to ack/review.

**Comment by blegowsk** [comment]
Wang, Yu1 gave ack
Acked-By: Wang, Yu1

**Comment by dongyaozu** [comment]
Those ack inforrmation need to be in the patch commit message so that the git history can trace. @blegowsk

**Comment by blegowsk** [comment]
Done-added Acked-by to commit. Thank you for all the instructions

**Comment by HuiHuangShi** [comment]
1916 <br>The PR does not touch any hypervisor source file. Skip coding guideline checks.<br>

**Comment by dongyaozu** [comment]
Something wrong with the PR? it has 4 patches now and duplicated

**Comment by blegowsk** [comment]
I created new, clean pull request with Tracked on and ack infos. I hope this one is correct.
https://github.com/projectacrn/acrn-hypervisor/pull/1950

**Pull request closed without merging**
