### PR TITLE
confgiure serial PCI BDF instead of MMIO base & hide it from SOS with vPCI support 

### PR DESCRIPTION
**Pull request by mcao6**
configure serial PCI BDF instead of MMIO base; and with these patches, SOS-Kernel PCI driver 
patches( to hide PIC device) can be reverted, it is hard to upstream.

Tracked-On: #1923
Signed-off-by: Minggui Cao <minggui.cao@intel.com>
Acked-by: Eddie Dong <eddie.dong@intel.com>

### CODE REVIEW

**Comment by HuiHuangShi** [comment]
1945<br>No new violations to the coding guideline detected.

**Comment by Mingyuan18** [comment]
@mcao6, please add Tracked-On ID in conversation.

**Comment by mcao6** [comment]
[External_System_ID] ACRN-1698

**Comment by wenlingz** [comment]
@mcao6 please fix your conflict,thanks

**Comment by mcao6** [comment]
ok, will check that soon.

**Comment by mcao6** [comment]
just resolved the conflicts, and it should be OK now.

**Comment by gvancuts** [comment]
Can you also remove the `pci_devices_ignore` instruction in the [acrn.conf](https://github.com/projectacrn/acrn-hypervisor/blob/master/hypervisor/bsp/uefi/clearlinux/acrn.conf#L3) file?

**Comment by HuiHuangShi** [comment]
1945<br>No new violations to the coding guideline detected.

**Comment by HuiHuangShi** [comment]
1945<br>No new violations to the coding guideline detected.

**Comment by mcao6** [comment]
updated to resolve new conflicts

**Comment by HuiHuangShi** [comment]
1945<br>No new violations to the coding guideline detected.

**Pull request merged**
