### PR TITLE
doc: Update hv power management doc

### PR DESCRIPTION
**Pull request by fyin1**
Signed-off-by: Yin Fengwei <fengwei.yin@intel.com>

### CODE REVIEW

**Comment by NanlinXie** [comment]
@fyin1 , Please modify SOS -> Service VM and UOS -> User VM

**Comment by fyin1** [comment]
@NanlinXie  Done.

**Comment by acrnsi** [comment]
OK to verify

**Comment by acrnsi** [comment]
OK to verify

**Pull request merged**
