### PR TITLE
acrn-config: update default pci_dev.c

### PR DESCRIPTION
**Pull request by yuchuyang**
update all default pci_dev.c under misc/vm_configs/scenarios/<scenario>/<platform> for non-xml compilation

Tracked-On: #5425
Signed-off-by: Yang Yu-chu <yu-chu.yang@intel.com>

### CODE REVIEW

**Comment by yuchuyang** [comment]
[External_System_ID]ACRN-6684

**Comment by HuiHuangShi** [comment]
No new violations to the coding guideline detected.<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Review by ionutnechita — COMMENTED** [review]
I tested now this commit 307064629cd67e3c5bb9f31fda91df4ffa73141d;

commit 307064629cd67e3c5bb9f31fda91df4ffa73141d (HEAD -> defult, origin/defult)
Author: Yang Yu-chu <yu-chu.yang@intel.com>
Date:   Tue Nov 17 13:23:48 2020 -0800

    acrn-config: update default pci_dev.c

    update all default pci_dev.c under
    misc/vm_configs/scenarios/<scenario>/<platform> for non-xml compilation

    Tracked-On: #5425
    Signed-off-by: Yang Yu-chu <yu-chu.yang@intel.com>


this modification maybe is not completed. 
not working with compiling ACRN in industrial mode.
make all BOARD=nuc7i7dnb SCENARIO=industry RELEASE=0 

Found nuc7i7dnb configuration for SCENARIO industry under /tmp/acrn-hypervisor/misc/vm_configs/scenarios/industry/nuc7i7dnb
cc main.c static_checks.c vm_cfg_checks.c ../../hypervisor/arch/x86/configs/vm_config.c /tmp/acrn-hypervisor/misc/vm_configs/scenarios/industry/vm_configurations.c /tmp/acrn-hypervisor/misc/vm_configs/scenarios/industry/nuc7i7dnb/pt_intx.c /tmp/acrn-hypervisor/misc/vm_configs/scenarios/industry/nuc7i7dnb/pci_dev.c  -I /tmp/acrn-hypervisor/hypervisor/include  -I /tmp/acrn-hypervisor/hypervisor/include/lib  -I /tmp/acrn-hypervisor/hypervisor/include/lib/crypto  -I /tmp/acrn-hypervisor/hypervisor/include/common  -I /tmp/acrn-hypervisor/hypervisor/include/arch/x86  -I /tmp/acrn-hypervisor/hypervisor/include/arch/x86/boot  -I /tmp/acrn-hypervisor/hypervisor/include/arch/x86/guest  -I /tmp/acrn-hypervisor/hypervisor/include/arch/x86/lib  -I /tmp/acrn-hypervisor/hypervisor/include/debug  -I /tmp/acrn-hypervisor/hypervisor/include/public  -I /tmp/acrn-hypervisor/hypervisor/include/dm  -I /tmp/acrn-hypervisor/hypervisor/include/hw  -I /tmp/acrn-hypervisor/hypervisor/boot/include  -I /tmp/acrn-hypervisor/hypervisor/boot/include/guest  -I /tmp/acrn-hypervisor/build/hypervisor/include  -I /tmp/acrn-hypervisor/misc/vm_configs/boards/nuc7i7dnb  -I /tmp/acrn-hypervisor/misc/vm_configs/scenarios/industry/nuc7i7dnb  -I /tmp/acrn-hypervisor/misc/vm_configs/scenarios/industry -include /tmp/acrn-hypervisor/build/hypervisor/include/config.h -I . -fno-stack-protector -fno-builtin -W -Wall -o /tmp/acrn-hypervisor/build/hypervisor/hv_prebuild_check.out
/usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: /tmp/ccwNRzSQ.o:(.bss+0x0): multiple definition of `sos_pci_devs'; /tmp/ccJ4BviO.o:(.bss+0x0): first defined here
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:43: default] Error 1

ACRN #5510 

thanks.

**Comment by wenlingz** [comment]
@terryzouhao please help approve this PR, thanks

**Comment by gvancuts** [comment]
It looks like this is also meant to be a fix for #5510 , should we add a second `Tracked-On` in this case? @NanlinXie

**Comment by NanlinXie** [comment]
@gvancuts , it is mandantory, but we could add one comment for link.

**Comment by gvancuts** [comment]
> @gvancuts , it is mandantory, but we could add one comment for link.

I understand having one `Tracked-On` line is mandatory but could we have two? It would be useful to track the feature completion **and** the bug that it fixes.

**Comment by gvancuts** [comment]
> /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: /tmp/ccwNRzSQ.o:(.bss+0x0): multiple definition of `sos_pci_devs'; /tmp/ccJ4BviO.o:(.bss+0x0): first defined here
> collect2: error: ld returned 1 exit status
> make[2]: *** [Makefile:43: default] Error 1

That's a different error than the one initially reported in #5510 . I have just tested this PR on my system and it fixes the original problem that I could reproduce.

Could it be that you still have some extra changes in your tree? I'm specifically thinking of the extra `extern` you added to the code at some point.

Thanks!

**Comment by wenlingz** [comment]
@terryzouhao please help approve this PR, thanks

**Review by terryzouhao — APPROVED** [review]

**Pull request merged**
