### PR TITLE
Update the CODEOWNERS information.

### PR DESCRIPTION
**Pull request by NanlinXie**
Update the CODEOWNERS information.

Tracked-On: #5581
Signed-off-by: Xie, nanlin <nanlin.xie@intel.com>

### CODE REVIEW

**Review by gvancuts — APPROVED** [review]
Thanks!

**Review by dbkinder — CHANGES_REQUESTED** [review]
While you're in this file, can you also change references to @deb-intel to @fitchbe

**Review by dongyaozu — APPROVED** [review]

**Comment by HuiHuangShi** [comment]
No new violations to the coding guideline detected.<br>No New Name Conflict<br>No New Function Declaration/Definition Mismatch

**Comment by gvancuts** [comment]
@wenlingz , @dbkinder had requested changes to this PR, why was it merged before they were addressed?

**Comment by wenlingz** [comment]
> @wenlingz , @dbkinder had requested changes to this PR, why was it merged before they were addressed?

@NanlinXie please help give the comments, thanks

**Pull request merged**
