### PR TITLE
hypervisor/ivshmem: Fix some ivshmem  bugs/issues

### PR DESCRIPTION
**Pull request by zhangckid**
Please check each patches detailed comments.

### CODE REVIEW

**Review by lifeix — APPROVED** [review]

**Comment by wenlingz** [comment]
@zhangckid please add Tracked-On, thanks

**Comment by zhangckid** [comment]
> @zhangckid please add Tracked-On, thanks

Done, please check again.

**Comment by wenlingz** [comment]
start to run premerge test

**Comment by wenlingz** [comment]
start to run premerge test

**Pull request merged**
