### PR TITLE
Doc: Remove CL release number from GSG document

### PR DESCRIPTION
**Pull request by NanlinXie**
Doc: Remove CL release number from GSG document

Signed-off-by: Xie, nanlin <nanlin.xie@intel.com>

### CODE REVIEW

**Comment by HuiHuangShi** [comment]
2446 <br>The PR does not touch any hypervisor source file. Skip coding guideline checks.<br>

**Comment by HuiHuangShi** [comment]
2446 <br>The PR does not touch any hypervisor source file. Skip coding guideline checks.<br>

**Comment by gvancuts** [comment]
Hi @NanlinXie , I see you made a new push after my initial review, but I don't see any difference compared to the original submission. Have I missed something?

**Comment by NanlinXie** [comment]
@gvancuts Currently we do not require tracked-on information for document PR  Other comments are addressed, please review.

**Comment by HuiHuangShi** [comment]
2446 <br>The PR does not touch any hypervisor source file. Skip coding guideline checks.<br>

**Comment by HuiHuangShi** [comment]
2446 <br>The PR does not touch any hypervisor source file. Skip coding guideline checks.<br>

**Comment by HuiHuangShi** [comment]
2446 <br>The PR does not touch any hypervisor source file. Skip coding guideline checks.<br>

**Comment by dbkinder** [comment]
This got merged before a doc review was completed.  I've submitted (and merged) a PR to fix some grammar issues.

**Pull request merged**
