### PR TITLE
tools: acrn-crashlog: refine crash complete code

### PR DESCRIPTION
**Pull request by xiaojingrich**
This patch is to remove unused info in server.c

Tracked-On: #3787
Signed-off-by: xiaojin2 <xiaojing.liu@intel.com>
Reviewed-by: Liu, Xinwu <xinwu.liu@intel.com>
Acked-by: CHEN Gang <gang.c.chen@intel.com>

### CODE REVIEW

**Comment by HuiHuangShi** [comment]
No new violations to the coding guideline detected.<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by acrnsi** [comment]
@xiaojingrich #5301 is not a complete link.

**Comment by xiaojingrich** [comment]
Hi Yonghua,

This patch is to resolve this issue: https://jira.devtools.intel.com/browse/ACRN-5301
I only attach the jira number in the patch, but now, it said the link is not a complete link, what should I do for this?
Attach the full link and PR again?
But I see other patch also uses the jira number not the link, so want to confirm with you.

Thanks,
Xiaojing

**Comment by xiaojingrich** [comment]
Have updated the tracked on number.

**Pull request closed without merging**
