### PR TITLE
Introduce SR-IOV feature for ACRN

### PR DESCRIPTION
**Pull request by liuyuan-GitHub**
This patch-set implements SRIOV-capable device discovery and add SRIOV capability interception entries.

SR-IOV(single root input/output virtualization) can isolate PCIe devices and
make the devices to have good performance, close to bare-metal. The SR-IOV
consists of two basic units, one is called PF(Physical Function) that supports
SRIOV PCIe extended capability and manages entire physical device, another is
called VF (Virtual Function) and is a "lightweight" PCIe function which is meant
to be given to a VM as a pass-through device. For more details, please refer to
PCI Express Base Specification Revision 4.0 Chapter 9. 

Tracked-On: #4433

### CODE REVIEW

**Comment by HuiHuangShi** [comment]
102 new potential violations to the coding guideline detected. Please help check. Thanks!<br><1> config:common filename:/hypervisor/include/hw/pci.h func: offset:112<br> reason:Use of function like macro.<br><2> config:common filename:/hypervisor/include/hw/pci.h func: offset:112<br> reason:Macro parameter not in brackets.             : hdr<br><3> config:common filename:/hypervisor/include/hw/pci.h func: offset:113<br> reason:Use of function like macro.<br><4> config:common filename:/hypervisor/include/hw/pci.h func: offset:113<br> reason:Macro parameter not in brackets.             : hdr<br><5> config:sharing_config filename:/hypervisor/include/arch/x86/guest/vlapic.h func: offset:111<br> reason:No real declaration for external variable. : apicv_ops<br><6> config:part_config filename:/hypervisor/include/arch/x86/guest/vlapic.h func: offset:111<br> reason:No real declaration for external variable. : apicv_ops<br><7> config:part_config filename:/hypervisor/include/debug/logmsg.h func: offset:33<br> reason:No real declaration for external variable. : console_loglevel<br><8> config:sharing_config filename:/hypervisor/include/debug/logmsg.h func: offset:33<br> reason:No real declaration for external variable. : console_loglevel<br><9> config:part_config filename:/hypervisor/include/debug/logmsg.h func: offset:34<br> reason:No real declaration for external variable. : mem_loglevel<br><10> config:sharing_config filename:/hypervisor/include/debug/logmsg.h func: offset:34<br> reason:No real declaration for external variable. : mem_loglevel<br><11> config:sharing_config filename:/hypervisor/include/debug/logmsg.h func: offset:35<br> reason:No real declaration for external variable. : npk_loglevel<br><12> config:part_config filename:/hypervisor/include/debug/logmsg.h func: offset:35<br> reason:No real declaration for external variable. : npk_loglevel<br><13> config:part_config filename:/hypervisor/include/arch/x86/cpu.h func: offset:256<br> reason:No real declaration for external variable. : main_entry<br><14> config:sharing_config filename:/hypervisor/include/arch/x86/cpu.h func: offset:256<br> reason:No real declaration for external variable. : main_entry<br><15> config:sharing_config filename:/hypervisor/include/arch/x86/cpu.h func: offset:257<br> reason:No real declaration for external variable. : secondary_cpu_stack<br><16> config:part_config filename:/hypervisor/include/arch/x86/cpu.h func: offset:257<br> reason:No real declaration for external variable. : secondary_cpu_stack<br><17> config:part_config filename:/hypervisor/include/common/schedule.h func: offset:81<br> reason:No real declaration for external variable. : sched_noop<br><18> config:sharing_config filename:/hypervisor/include/common/schedule.h func: offset:81<br> reason:No real declaration for external variable. : sched_noop<br><19> config:sharing_config filename:/hypervisor/include/common/schedule.h func: offset:82<br> reason:No real declaration for external variable. : sched_iorr<br><20> config:part_config filename:/hypervisor/include/common/schedule.h func: offset:82<br> reason:No real declaration for external variable. : sched_iorr<br><21> config:part_config filename:/hypervisor/include/common/schedule.h func: offset:93<br> reason:No real declaration for external variable. : sched_bvt<br><22> config:sharing_config filename:/hypervisor/include/common/schedule.h func: offset:93<br> reason:No real declaration for external variable. : sched_bvt<br><23> config:common filename:/hypervisor/include/common/ptdev.h func:is_entry_active offset:134<br> reason:Static procedure is not explicitly called in code analysed. : is_entry_active<br><24> config:part_config filename:/hypervisor/hw/pci.c func:scan_pci_hierarchy offset:320<br> reason:Procedure contains UR data flow anomalies. : pbdf.value<br><25> config:sharing_config filename:/hypervisor/hw/pci.c func:scan_pci_hierarchy offset:320<br> reason:Procedure contains UR data flow anomalies. : pbdf.value<br><26> config:sharing_config filename:/hypervisor/hw/pci.c func:scan_pci_hierarchy offset:347<br> reason:Function return value potentially unused. : vendor<br><27> config:part_config filename:/hypervisor/hw/pci.c func:scan_pci_hierarchy offset:347<br> reason:Function return value potentially unused. : vendor<br><28> config:part_config filename:/hypervisor/hw/pci.c func:scan_pci_hierarchy offset:348<br> reason:Function return value potentially unused. : hdr_type<br><29> config:sharing_config filename:/hypervisor/hw/pci.c func:scan_pci_hierarchy offset:348<br> reason:Function return value potentially unused. : hdr_type<br><30> config:part_config filename:/hypervisor/hw/pci.c func:scan_pci_hierarchy offset:351<br> reason:Function return value potentially unused. : is_mfdev<br><31> config:sharing_config filename:/hypervisor/hw/pci.c func:scan_pci_hierarchy offset:351<br> reason:Function return value potentially unused. : is_mfdev<br><32> config:common filename:/hypervisor/hw/pci.c func:scan_pci_hierarchy offset:358<br> reason:Logical conjunctions need brackets.<br><33> config:sharing_config filename:/hypervisor/hw/pci.c func:scan_pci_hierarchy offset:367<br> reason:Function return value potentially unused. : bdf_drhd_index<br><34> config:part_config filename:/hypervisor/hw/pci.c func:scan_pci_hierarchy offset:367<br> reason:Function return value potentially unused. : bdf_drhd_index<br>.....<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by liuyuan-GitHub** [comment]
Update the coding violations list and feed it back to Shi,Huihuang.
Re-submit the PR to fix violations.

**Comment by HuiHuangShi** [comment]
64 new potential violations to the coding guideline detected. Please help check. Thanks!<br><1> config:common filename:/hypervisor/include/hw/pci.h func: offset:112<br> reason:Use of function like macro.<br><2> config:common filename:/hypervisor/include/hw/pci.h func: offset:113<br> reason:Use of function like macro.<br><3> config:sharing_config filename:/hypervisor/include/arch/x86/guest/vlapic.h func: offset:111<br> reason:No real declaration for external variable. : apicv_ops<br><4> config:part_config filename:/hypervisor/include/arch/x86/guest/vlapic.h func: offset:111<br> reason:No real declaration for external variable. : apicv_ops<br><5> config:part_config filename:/hypervisor/include/debug/logmsg.h func: offset:33<br> reason:No real declaration for external variable. : console_loglevel<br><6> config:sharing_config filename:/hypervisor/include/debug/logmsg.h func: offset:33<br> reason:No real declaration for external variable. : console_loglevel<br><7> config:part_config filename:/hypervisor/include/debug/logmsg.h func: offset:34<br> reason:No real declaration for external variable. : mem_loglevel<br><8> config:sharing_config filename:/hypervisor/include/debug/logmsg.h func: offset:34<br> reason:No real declaration for external variable. : mem_loglevel<br><9> config:sharing_config filename:/hypervisor/include/debug/logmsg.h func: offset:35<br> reason:No real declaration for external variable. : npk_loglevel<br><10> config:part_config filename:/hypervisor/include/debug/logmsg.h func: offset:35<br> reason:No real declaration for external variable. : npk_loglevel<br><11> config:part_config filename:/hypervisor/include/arch/x86/cpu.h func: offset:256<br> reason:No real declaration for external variable. : main_entry<br><12> config:sharing_config filename:/hypervisor/include/arch/x86/cpu.h func: offset:256<br> reason:No real declaration for external variable. : main_entry<br><13> config:part_config filename:/hypervisor/include/arch/x86/cpu.h func: offset:257<br> reason:No real declaration for external variable. : secondary_cpu_stack<br><14> config:sharing_config filename:/hypervisor/include/arch/x86/cpu.h func: offset:257<br> reason:No real declaration for external variable. : secondary_cpu_stack<br><15> config:part_config filename:/hypervisor/include/common/schedule.h func: offset:81<br> reason:No real declaration for external variable. : sched_noop<br><16> config:sharing_config filename:/hypervisor/include/common/schedule.h func: offset:81<br> reason:No real declaration for external variable. : sched_noop<br><17> config:sharing_config filename:/hypervisor/include/common/schedule.h func: offset:82<br> reason:No real declaration for external variable. : sched_iorr<br><18> config:part_config filename:/hypervisor/include/common/schedule.h func: offset:82<br> reason:No real declaration for external variable. : sched_iorr<br><19> config:part_config filename:/hypervisor/include/common/schedule.h func: offset:93<br> reason:No real declaration for external variable. : sched_bvt<br><20> config:sharing_config filename:/hypervisor/include/common/schedule.h func: offset:93<br> reason:No real declaration for external variable. : sched_bvt<br><21> config:common filename:/hypervisor/include/common/ptdev.h func:is_entry_active offset:134<br> reason:Static procedure is not explicitly called in code analysed. : is_entry_active<br><22> config:part_config filename:/hypervisor/hw/pci.c func:scan_pci_hierarchy offset:320<br> reason:Procedure contains UR data flow anomalies. : pbdf.value<br><23> config:sharing_config filename:/hypervisor/hw/pci.c func:scan_pci_hierarchy offset:320<br> reason:Procedure contains UR data flow anomalies. : pbdf.value<br><24> config:sharing_config filename:/hypervisor/hw/pci.c func:scan_pci_hierarchy offset:347<br> reason:Function return value potentially unused. : vendor<br><25> config:part_config filename:/hypervisor/hw/pci.c func:scan_pci_hierarchy offset:347<br> reason:Function return value potentially unused. : vendor<br><26> config:part_config filename:/hypervisor/hw/pci.c func:scan_pci_hierarchy offset:348<br> reason:Function return value potentially unused. : hdr_type<br><27> config:sharing_config filename:/hypervisor/hw/pci.c func:scan_pci_hierarchy offset:348<br> reason:Function return value potentially unused. : hdr_type<br><28> config:part_config filename:/hypervisor/hw/pci.c func:scan_pci_hierarchy offset:351<br> reason:Function return value potentially unused. : is_mfdev<br><29> config:sharing_config filename:/hypervisor/hw/pci.c func:scan_pci_hierarchy offset:351<br> reason:Function return value potentially unused. : is_mfdev<br><30> config:common filename:/hypervisor/hw/pci.c func:scan_pci_hierarchy offset:358<br> reason:Logical conjunctions need brackets.<br><31> config:sharing_config filename:/hypervisor/hw/pci.c func:scan_pci_hierarchy offset:367<br> reason:Function return value potentially unused. : bdf_drhd_index<br><32> config:part_config filename:/hypervisor/hw/pci.c func:scan_pci_hierarchy offset:367<br> reason:Function return value potentially unused. : bdf_drhd_index<br><33> config:sharing_config filename:/hypervisor/hw/pci.c func:scan_pci_hierarchy offset:372<br> reason:Function return value potentially unused. : bus_map.bus_under_scan<br><34> config:part_config filename:/hypervisor/hw/pci.c func:scan_pci_hierarchy offset:372<br> reason:Function return value potentially unused. : bus_map.bus_under_scan<br>.....<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by liuyuan-GitHub** [comment]
Fixed some code potential violations which are reviewed by Shi,huihuang

**Comment by HuiHuangShi** [comment]
64 new potential violations to the coding guideline detected. Please help check. Thanks!<br><1> config:common filename:/hypervisor/include/hw/pci.h func: offset:112<br> reason:Use of function like macro.<br><2> config:common filename:/hypervisor/include/hw/pci.h func: offset:113<br> reason:Use of function like macro.<br><3> config:sharing_config filename:/hypervisor/include/arch/x86/guest/vlapic.h func: offset:111<br> reason:No real declaration for external variable. : apicv_ops<br><4> config:part_config filename:/hypervisor/include/arch/x86/guest/vlapic.h func: offset:111<br> reason:No real declaration for external variable. : apicv_ops<br><5> config:part_config filename:/hypervisor/include/debug/logmsg.h func: offset:33<br> reason:No real declaration for external variable. : console_loglevel<br><6> config:sharing_config filename:/hypervisor/include/debug/logmsg.h func: offset:33<br> reason:No real declaration for external variable. : console_loglevel<br><7> config:part_config filename:/hypervisor/include/debug/logmsg.h func: offset:34<br> reason:No real declaration for external variable. : mem_loglevel<br><8> config:sharing_config filename:/hypervisor/include/debug/logmsg.h func: offset:34<br> reason:No real declaration for external variable. : mem_loglevel<br><9> config:sharing_config filename:/hypervisor/include/debug/logmsg.h func: offset:35<br> reason:No real declaration for external variable. : npk_loglevel<br><10> config:part_config filename:/hypervisor/include/debug/logmsg.h func: offset:35<br> reason:No real declaration for external variable. : npk_loglevel<br><11> config:part_config filename:/hypervisor/include/arch/x86/cpu.h func: offset:256<br> reason:No real declaration for external variable. : main_entry<br><12> config:sharing_config filename:/hypervisor/include/arch/x86/cpu.h func: offset:256<br> reason:No real declaration for external variable. : main_entry<br><13> config:part_config filename:/hypervisor/include/arch/x86/cpu.h func: offset:257<br> reason:No real declaration for external variable. : secondary_cpu_stack<br><14> config:sharing_config filename:/hypervisor/include/arch/x86/cpu.h func: offset:257<br> reason:No real declaration for external variable. : secondary_cpu_stack<br><15> config:part_config filename:/hypervisor/include/common/schedule.h func: offset:81<br> reason:No real declaration for external variable. : sched_noop<br><16> config:sharing_config filename:/hypervisor/include/common/schedule.h func: offset:81<br> reason:No real declaration for external variable. : sched_noop<br><17> config:sharing_config filename:/hypervisor/include/common/schedule.h func: offset:82<br> reason:No real declaration for external variable. : sched_iorr<br><18> config:part_config filename:/hypervisor/include/common/schedule.h func: offset:82<br> reason:No real declaration for external variable. : sched_iorr<br><19> config:part_config filename:/hypervisor/include/common/schedule.h func: offset:93<br> reason:No real declaration for external variable. : sched_bvt<br><20> config:sharing_config filename:/hypervisor/include/common/schedule.h func: offset:93<br> reason:No real declaration for external variable. : sched_bvt<br><21> config:common filename:/hypervisor/include/common/ptdev.h func:is_entry_active offset:134<br> reason:Static procedure is not explicitly called in code analysed. : is_entry_active<br><22> config:part_config filename:/hypervisor/hw/pci.c func:scan_pci_hierarchy offset:320<br> reason:Procedure contains UR data flow anomalies. : pbdf.value<br><23> config:sharing_config filename:/hypervisor/hw/pci.c func:scan_pci_hierarchy offset:320<br> reason:Procedure contains UR data flow anomalies. : pbdf.value<br><24> config:sharing_config filename:/hypervisor/hw/pci.c func:scan_pci_hierarchy offset:347<br> reason:Function return value potentially unused. : vendor<br><25> config:part_config filename:/hypervisor/hw/pci.c func:scan_pci_hierarchy offset:347<br> reason:Function return value potentially unused. : vendor<br><26> config:part_config filename:/hypervisor/hw/pci.c func:scan_pci_hierarchy offset:348<br> reason:Function return value potentially unused. : hdr_type<br><27> config:sharing_config filename:/hypervisor/hw/pci.c func:scan_pci_hierarchy offset:348<br> reason:Function return value potentially unused. : hdr_type<br><28> config:part_config filename:/hypervisor/hw/pci.c func:scan_pci_hierarchy offset:351<br> reason:Function return value potentially unused. : is_mfdev<br><29> config:sharing_config filename:/hypervisor/hw/pci.c func:scan_pci_hierarchy offset:351<br> reason:Function return value potentially unused. : is_mfdev<br><30> config:common filename:/hypervisor/hw/pci.c func:scan_pci_hierarchy offset:358<br> reason:Logical conjunctions need brackets.<br><31> config:sharing_config filename:/hypervisor/hw/pci.c func:scan_pci_hierarchy offset:367<br> reason:Function return value potentially unused. : bdf_drhd_index<br><32> config:part_config filename:/hypervisor/hw/pci.c func:scan_pci_hierarchy offset:367<br> reason:Function return value potentially unused. : bdf_drhd_index<br><33> config:sharing_config filename:/hypervisor/hw/pci.c func:scan_pci_hierarchy offset:372<br> reason:Function return value potentially unused. : bus_map.bus_under_scan<br><34> config:part_config filename:/hypervisor/hw/pci.c func:scan_pci_hierarchy offset:372<br> reason:Function return value potentially unused. : bus_map.bus_under_scan<br>.....<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Pull request merged**
