### PR TITLE
 hv: basic emulation for guest reboot

### PR DESCRIPTION
**Pull request by ZideChen0**
1) deny guess access to reset register PIO ports (0x64, 0xcf9, ACPI
   reset reg) for all type of VMs, except for post-launched RTVM.

2) set VM_POWERING_OFF flag for post-launched RTVM.

3) parse host ACPI reset register and use it on SOS to deny
   the access from SOS guest.

### CODE REVIEW

**Comment by HuiHuangShi** [comment]
59 new potential violations to the coding guideline detected. Please help check. Thanks!<br><1> config:part_config filename:/hypervisor/include/arch/x86/io.h func:pio_read8 offset:21<br> reason:Procedure contains UR data flow anomalies. : value<br><2> config:sharing_config filename:/hypervisor/include/arch/x86/io.h func:pio_read8 offset:21<br> reason:Procedure contains UR data flow anomalies. : value<br><3> config:common filename:/hypervisor/include/arch/x86/io.h func:pio_read8 offset:25<br> reason:Procedure is not pure assembler.<br><4> config:part_config filename:/hypervisor/include/arch/x86/io.h func:pio_read16 offset:36<br> reason:Procedure contains UR data flow anomalies. : value<br><5> config:sharing_config filename:/hypervisor/include/arch/x86/io.h func:pio_read16 offset:36<br> reason:Procedure contains UR data flow anomalies. : value<br><6> config:common filename:/hypervisor/include/arch/x86/io.h func:pio_read16 offset:40<br> reason:Procedure is not pure assembler.<br><7> config:sharing_config filename:/hypervisor/include/arch/x86/io.h func:pio_read32 offset:51<br> reason:Procedure contains UR data flow anomalies. : value<br><8> config:part_config filename:/hypervisor/include/arch/x86/io.h func:pio_read32 offset:51<br> reason:Procedure contains UR data flow anomalies. : value<br><9> config:common filename:/hypervisor/include/arch/x86/io.h func:pio_read32 offset:55<br> reason:Procedure is not pure assembler.<br><10> config:common filename:/hypervisor/include/arch/x86/io.h func:pio_write offset:57<br> reason:Static procedure is not explicitly called in code analysed. : pio_write<br><11> config:common filename:/hypervisor/include/arch/x86/io.h func:pio_read offset:68<br> reason:Static procedure is not explicitly called in code analysed. : pio_read<br><12> config:common filename:/hypervisor/include/arch/x86/io.h func:mmio_write64 offset:88<br> reason:Casting operation to a pointer. : (void* to unsigned long*): ( volatile uint64_t * ) addr<br><13> config:common filename:/hypervisor/include/arch/x86/io.h func:mmio_write64 offset:88<br> reason:Casting operation on a pointer. : (void* to unsigned long*): ( volatile uint64_t * ) addr<br><14> config:common filename:/hypervisor/include/arch/x86/io.h func:mmio_write32 offset:99<br> reason:Casting operation to a pointer. : (void* to unsigned int*): ( volatile uint32_t * ) addr<br><15> config:common filename:/hypervisor/include/arch/x86/io.h func:mmio_write32 offset:99<br> reason:Casting operation on a pointer. : (void* to unsigned int*): ( volatile uint32_t * ) addr<br><16> config:common filename:/hypervisor/include/arch/x86/io.h func:mmio_write16 offset:110<br> reason:Casting operation to a pointer. : (void* to unsigned short*): ( volatile uint16_t * ) addr<br><17> config:common filename:/hypervisor/include/arch/x86/io.h func:mmio_write16 offset:110<br> reason:Casting operation on a pointer. : (void* to unsigned short*): ( volatile uint16_t * ) addr<br><18> config:common filename:/hypervisor/include/arch/x86/io.h func:mmio_read64 offset:133<br> reason:Casting operation to a pointer. : (void* to unsigned long*): ( volatile const uint64_t * ) addr<br><19> config:common filename:/hypervisor/include/arch/x86/io.h func:mmio_read64 offset:133<br> reason:Cast on a constant value.                    : addr<br><20> config:common filename:/hypervisor/include/arch/x86/io.h func:mmio_read64 offset:133<br> reason:Casting operation on a pointer. : (void* to unsigned long*): ( volatile const uint64_t * ) addr<br><21> config:common filename:/hypervisor/include/arch/x86/io.h func:mmio_read32 offset:144<br> reason:Casting operation to a pointer. : (void* to unsigned int*): ( volatile const uint32_t * ) addr<br><22> config:common filename:/hypervisor/include/arch/x86/io.h func:mmio_read32 offset:144<br> reason:Cast on a constant value.                    : addr<br><23> config:common filename:/hypervisor/include/arch/x86/io.h func:mmio_read32 offset:144<br> reason:Casting operation on a pointer. : (void* to unsigned int*): ( volatile const uint32_t * ) addr<br><24> config:common filename:/hypervisor/include/arch/x86/io.h func:mmio_read16 offset:155<br> reason:Casting operation to a pointer. : (void* to unsigned short*): ( volatile const uint16_t * ) addr<br><25> config:common filename:/hypervisor/include/arch/x86/io.h func:mmio_read16 offset:155<br> reason:Cast on a constant value.                    : addr<br><26> config:common filename:/hypervisor/include/arch/x86/io.h func:mmio_read16 offset:155<br> reason:Casting operation on a pointer. : (void* to unsigned short*): ( volatile const uint16_t * ) addr<br><27> config:common filename:/hypervisor/include/arch/x86/io.h func:mmio_read8 offset:166<br> reason:Cast on a constant value.                    : addr<br><28> config:common filename:/hypervisor/include/arch/x86/io.h func:set64 offset:176<br> reason:Static procedure is not explicitly called in code analysed. : set64<br><29> config:common filename:/hypervisor/include/arch/x86/io.h func:set32 offset:191<br> reason:Static procedure is not explicitly called in code analysed. : set32<br><30> config:common filename:/hypervisor/include/arch/x86/io.h func:set16 offset:206<br> reason:Static procedure is not explicitly called in code analysed. : set16<br><31> config:common filename:/hypervisor/include/arch/x86/io.h func:set8 offset:221<br> reason:Static procedure is not explicitly called in code analysed. : set8<br><32> config:common filename:/hypervisor/include/arch/x86/multiboot.h func: offset:21<br> reason:Struct/union not completely specified.       : acrn_vm<br><33> config:sharing_config filename:/hypervisor/boot/acpi.c func:acpi_fixup offset:454<br> reason:Cast to an unrelated type. : (unsigned char* to Unknown_Type:acpi_table_header*): ( const struct acpi_table_header * ) facp_addr<br><34> config:sharing_config filename:/hypervisor/boot/acpi.c func:acpi_fixup offset:454<br> reason:Casting operation to a pointer. : (unsigned char* to Unknown_Type:acpi_table_header*): ( const struct acpi_table_header * ) facp_addr<br>.....<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by jsun26intel** [comment]
some violations should be filtered after rebase on PR#3108.

**Comment by ZideChen0** [comment]
> some violations should be filtered after rebase on PR#3108.

Just rebased the PR after #3108.

**Comment by acrnsi** [comment]
OK to verify

**Comment by HuiHuangShi** [comment]
56 new potential violations to the coding guideline detected. Please help check. Thanks!<br><1> config:part_config filename:/hypervisor/include/arch/x86/io.h func:pio_read8 offset:21<br> reason:Procedure contains UR data flow anomalies. : value<br><2> config:sharing_config filename:/hypervisor/include/arch/x86/io.h func:pio_read8 offset:21<br> reason:Procedure contains UR data flow anomalies. : value<br><3> config:common filename:/hypervisor/include/arch/x86/io.h func:pio_read8 offset:25<br> reason:Procedure is not pure assembler.<br><4> config:part_config filename:/hypervisor/include/arch/x86/io.h func:pio_read16 offset:36<br> reason:Procedure contains UR data flow anomalies. : value<br><5> config:sharing_config filename:/hypervisor/include/arch/x86/io.h func:pio_read16 offset:36<br> reason:Procedure contains UR data flow anomalies. : value<br><6> config:common filename:/hypervisor/include/arch/x86/io.h func:pio_read16 offset:40<br> reason:Procedure is not pure assembler.<br><7> config:sharing_config filename:/hypervisor/include/arch/x86/io.h func:pio_read32 offset:51<br> reason:Procedure contains UR data flow anomalies. : value<br><8> config:part_config filename:/hypervisor/include/arch/x86/io.h func:pio_read32 offset:51<br> reason:Procedure contains UR data flow anomalies. : value<br><9> config:common filename:/hypervisor/include/arch/x86/io.h func:pio_read32 offset:55<br> reason:Procedure is not pure assembler.<br><10> config:common filename:/hypervisor/include/arch/x86/io.h func:pio_write offset:57<br> reason:Static procedure is not explicitly called in code analysed. : pio_write<br><11> config:common filename:/hypervisor/include/arch/x86/io.h func:pio_read offset:68<br> reason:Static procedure is not explicitly called in code analysed. : pio_read<br><12> config:common filename:/hypervisor/include/arch/x86/io.h func:mmio_write64 offset:88<br> reason:Casting operation to a pointer. : (void* to unsigned long*): ( volatile uint64_t * ) addr<br><13> config:common filename:/hypervisor/include/arch/x86/io.h func:mmio_write64 offset:88<br> reason:Casting operation on a pointer. : (void* to unsigned long*): ( volatile uint64_t * ) addr<br><14> config:common filename:/hypervisor/include/arch/x86/io.h func:mmio_write32 offset:99<br> reason:Casting operation to a pointer. : (void* to unsigned int*): ( volatile uint32_t * ) addr<br><15> config:common filename:/hypervisor/include/arch/x86/io.h func:mmio_write32 offset:99<br> reason:Casting operation on a pointer. : (void* to unsigned int*): ( volatile uint32_t * ) addr<br><16> config:common filename:/hypervisor/include/arch/x86/io.h func:mmio_write16 offset:110<br> reason:Casting operation to a pointer. : (void* to unsigned short*): ( volatile uint16_t * ) addr<br><17> config:common filename:/hypervisor/include/arch/x86/io.h func:mmio_write16 offset:110<br> reason:Casting operation on a pointer. : (void* to unsigned short*): ( volatile uint16_t * ) addr<br><18> config:common filename:/hypervisor/include/arch/x86/io.h func:mmio_read64 offset:133<br> reason:Casting operation to a pointer. : (void* to unsigned long*): ( volatile const uint64_t * ) addr<br><19> config:common filename:/hypervisor/include/arch/x86/io.h func:mmio_read64 offset:133<br> reason:Cast on a constant value.                    : addr<br><20> config:common filename:/hypervisor/include/arch/x86/io.h func:mmio_read64 offset:133<br> reason:Casting operation on a pointer. : (void* to unsigned long*): ( volatile const uint64_t * ) addr<br><21> config:common filename:/hypervisor/include/arch/x86/io.h func:mmio_read32 offset:144<br> reason:Casting operation to a pointer. : (void* to unsigned int*): ( volatile const uint32_t * ) addr<br><22> config:common filename:/hypervisor/include/arch/x86/io.h func:mmio_read32 offset:144<br> reason:Cast on a constant value.                    : addr<br><23> config:common filename:/hypervisor/include/arch/x86/io.h func:mmio_read32 offset:144<br> reason:Casting operation on a pointer. : (void* to unsigned int*): ( volatile const uint32_t * ) addr<br><24> config:common filename:/hypervisor/include/arch/x86/io.h func:mmio_read16 offset:155<br> reason:Casting operation to a pointer. : (void* to unsigned short*): ( volatile const uint16_t * ) addr<br><25> config:common filename:/hypervisor/include/arch/x86/io.h func:mmio_read16 offset:155<br> reason:Cast on a constant value.                    : addr<br><26> config:common filename:/hypervisor/include/arch/x86/io.h func:mmio_read16 offset:155<br> reason:Casting operation on a pointer. : (void* to unsigned short*): ( volatile const uint16_t * ) addr<br><27> config:common filename:/hypervisor/include/arch/x86/io.h func:mmio_read8 offset:166<br> reason:Cast on a constant value.                    : addr<br><28> config:common filename:/hypervisor/include/arch/x86/io.h func:set64 offset:176<br> reason:Static procedure is not explicitly called in code analysed. : set64<br><29> config:common filename:/hypervisor/include/arch/x86/io.h func:set32 offset:191<br> reason:Static procedure is not explicitly called in code analysed. : set32<br><30> config:common filename:/hypervisor/include/arch/x86/io.h func:set16 offset:206<br> reason:Static procedure is not explicitly called in code analysed. : set16<br><31> config:common filename:/hypervisor/include/arch/x86/io.h func:set8 offset:221<br> reason:Static procedure is not explicitly called in code analysed. : set8<br><32> config:common filename:/hypervisor/include/arch/x86/multiboot.h func: offset:21<br> reason:Struct/union not completely specified.       : acrn_vm<br><33> config:common filename:/hypervisor/arch/x86/guest/vmexit.c func:triple_fault_vmexit_handler offset:254<br> reason:Static procedure is not explicitly called in code analysed. : triple_fault_vmexit_handler<br><34> config:sharing_config filename:/hypervisor/arch/x86/guest/vm_reset.c func:get_host_reset_reg_data offset:27<br> reason:Procedure is not called or referenced in code analysed. : get_host_reset_reg_data<br>.....<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by HuiHuangShi** [comment]
out of time

**Comment by HuiHuangShi** [comment]
56 new potential violations to the coding guideline detected. Please help check. Thanks!<br><1> config:part_config filename:/hypervisor/include/arch/x86/io.h func:pio_read8 offset:21<br> reason:Procedure contains UR data flow anomalies. : value<br><2> config:sharing_config filename:/hypervisor/include/arch/x86/io.h func:pio_read8 offset:21<br> reason:Procedure contains UR data flow anomalies. : value<br><3> config:common filename:/hypervisor/include/arch/x86/io.h func:pio_read8 offset:25<br> reason:Procedure is not pure assembler.<br><4> config:part_config filename:/hypervisor/include/arch/x86/io.h func:pio_read16 offset:36<br> reason:Procedure contains UR data flow anomalies. : value<br><5> config:sharing_config filename:/hypervisor/include/arch/x86/io.h func:pio_read16 offset:36<br> reason:Procedure contains UR data flow anomalies. : value<br><6> config:common filename:/hypervisor/include/arch/x86/io.h func:pio_read16 offset:40<br> reason:Procedure is not pure assembler.<br><7> config:sharing_config filename:/hypervisor/include/arch/x86/io.h func:pio_read32 offset:51<br> reason:Procedure contains UR data flow anomalies. : value<br><8> config:part_config filename:/hypervisor/include/arch/x86/io.h func:pio_read32 offset:51<br> reason:Procedure contains UR data flow anomalies. : value<br><9> config:common filename:/hypervisor/include/arch/x86/io.h func:pio_read32 offset:55<br> reason:Procedure is not pure assembler.<br><10> config:common filename:/hypervisor/include/arch/x86/io.h func:pio_write offset:57<br> reason:Static procedure is not explicitly called in code analysed. : pio_write<br><11> config:common filename:/hypervisor/include/arch/x86/io.h func:pio_read offset:68<br> reason:Static procedure is not explicitly called in code analysed. : pio_read<br><12> config:common filename:/hypervisor/include/arch/x86/io.h func:mmio_write64 offset:88<br> reason:Casting operation to a pointer. : (void* to unsigned long*): ( volatile uint64_t * ) addr<br><13> config:common filename:/hypervisor/include/arch/x86/io.h func:mmio_write64 offset:88<br> reason:Casting operation on a pointer. : (void* to unsigned long*): ( volatile uint64_t * ) addr<br><14> config:common filename:/hypervisor/include/arch/x86/io.h func:mmio_write32 offset:99<br> reason:Casting operation to a pointer. : (void* to unsigned int*): ( volatile uint32_t * ) addr<br><15> config:common filename:/hypervisor/include/arch/x86/io.h func:mmio_write32 offset:99<br> reason:Casting operation on a pointer. : (void* to unsigned int*): ( volatile uint32_t * ) addr<br><16> config:common filename:/hypervisor/include/arch/x86/io.h func:mmio_write16 offset:110<br> reason:Casting operation to a pointer. : (void* to unsigned short*): ( volatile uint16_t * ) addr<br><17> config:common filename:/hypervisor/include/arch/x86/io.h func:mmio_write16 offset:110<br> reason:Casting operation on a pointer. : (void* to unsigned short*): ( volatile uint16_t * ) addr<br><18> config:common filename:/hypervisor/include/arch/x86/io.h func:mmio_read64 offset:133<br> reason:Casting operation to a pointer. : (void* to unsigned long*): ( volatile const uint64_t * ) addr<br><19> config:common filename:/hypervisor/include/arch/x86/io.h func:mmio_read64 offset:133<br> reason:Cast on a constant value.                    : addr<br><20> config:common filename:/hypervisor/include/arch/x86/io.h func:mmio_read64 offset:133<br> reason:Casting operation on a pointer. : (void* to unsigned long*): ( volatile const uint64_t * ) addr<br><21> config:common filename:/hypervisor/include/arch/x86/io.h func:mmio_read32 offset:144<br> reason:Casting operation to a pointer. : (void* to unsigned int*): ( volatile const uint32_t * ) addr<br><22> config:common filename:/hypervisor/include/arch/x86/io.h func:mmio_read32 offset:144<br> reason:Cast on a constant value.                    : addr<br><23> config:common filename:/hypervisor/include/arch/x86/io.h func:mmio_read32 offset:144<br> reason:Casting operation on a pointer. : (void* to unsigned int*): ( volatile const uint32_t * ) addr<br><24> config:common filename:/hypervisor/include/arch/x86/io.h func:mmio_read16 offset:155<br> reason:Casting operation to a pointer. : (void* to unsigned short*): ( volatile const uint16_t * ) addr<br><25> config:common filename:/hypervisor/include/arch/x86/io.h func:mmio_read16 offset:155<br> reason:Cast on a constant value.                    : addr<br><26> config:common filename:/hypervisor/include/arch/x86/io.h func:mmio_read16 offset:155<br> reason:Casting operation on a pointer. : (void* to unsigned short*): ( volatile const uint16_t * ) addr<br><27> config:common filename:/hypervisor/include/arch/x86/io.h func:mmio_read8 offset:166<br> reason:Cast on a constant value.                    : addr<br><28> config:common filename:/hypervisor/include/arch/x86/io.h func:set64 offset:176<br> reason:Static procedure is not explicitly called in code analysed. : set64<br><29> config:common filename:/hypervisor/include/arch/x86/io.h func:set32 offset:191<br> reason:Static procedure is not explicitly called in code analysed. : set32<br><30> config:common filename:/hypervisor/include/arch/x86/io.h func:set16 offset:206<br> reason:Static procedure is not explicitly called in code analysed. : set16<br><31> config:common filename:/hypervisor/include/arch/x86/io.h func:set8 offset:221<br> reason:Static procedure is not explicitly called in code analysed. : set8<br><32> config:common filename:/hypervisor/include/arch/x86/multiboot.h func: offset:21<br> reason:Struct/union not completely specified.       : acrn_vm<br><33> config:common filename:/hypervisor/arch/x86/guest/vmexit.c func:triple_fault_vmexit_handler offset:254<br> reason:Static procedure is not explicitly called in code analysed. : triple_fault_vmexit_handler<br><34> config:sharing_config filename:/hypervisor/arch/x86/guest/vm_reset.c func:get_host_reset_reg_data offset:27<br> reason:Procedure is not called or referenced in code analysed. : get_host_reset_reg_data<br>.....<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Pull request merged**
