### PR TITLE
acrn-config: fix typos and text in board_parser.py tool

### PR DESCRIPTION
**Pull request by gvancuts**
Enhance and fix some typos in the text that gets printed out from the
board_parser.py script.

Signed-off-by: Geoffroy Van Cutsem <geoffroy.vancutsem@intel.com>

### CODE REVIEW

**Comment by HuiHuangShi** [comment]
No new violations to the coding guideline detected.<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by binbinwu1** [comment]
@jsun26intel @terryzouhao Could you have a review?

**Comment by wenlingz** [comment]
@gvancuts please add Tracke-On info for this PR, refer this wiki: https://wiki.ith.intel.com/display/OTCCWPQA/How+to+create+git+issue+bug+for+Tracked-On

**Comment by gvancuts** [comment]
> @gvancuts please add Tracke-On info for this PR

Done

**Comment by wenlingz** [comment]
@gvancuts please add JIRA bug in the git issue, “add first comment with "External_System_ID" use format "[External_System_ID] ACRN-123456" in git issue”

**Comment by leilu** [comment]
OK to verify

**Comment by HuiHuangShi** [comment]
No new violations to the coding guideline detected.<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by gvancuts** [comment]
> @gvancuts please add JIRA bug in the git issue, “add first comment with "External_System_ID" use format "[External_System_ID] ACRN-123456" in git issue”

I never do that myself, who can help me do that?

/cc @NanlinXie

**Pull request merged**
