### PR TITLE
acrn-config: refine library for config tool

### PR DESCRIPTION
**Pull request by liuwei987**
- remove the same parameters and functions from launch_cfg_lib
- remove the same parameters and functions from scenario_cfg_lib
- remove the same parameters and functions from board_cfg_lib
- expends parameters and functions to common lib

    Tracked-On: #3854
    Signed-off-by: Wei Liu <weix.w.liu@intel.com>
    Acked-by: Victor Sun <victor.sun@intel.com>
    Acked-by: Terry Zou <terry.zou@intel.com>

### CODE REVIEW

**Comment by HuiHuangShi** [comment]
No new violations to the coding guideline detected.<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by leilu** [comment]
OK to verify

**Comment by HuiHuangShi** [comment]
No new violations to the coding guideline detected.<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by wenlingz** [comment]
@liuwei987 please rebase your code, thanks

**Comment by liuwei987** [comment]
> @liuwei987 please rebase your code, thanks

Done!

**Comment by HuiHuangShi** [comment]
No new violations to the coding guideline detected.<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Pull request merged**
