### PR TITLE
doc: add module design for peripheral ivshmem device

### PR DESCRIPTION
**Pull request by haiwei-li**
GAI Tooling Notice: These contents may have been developed with support from one or more generative artificial intelligence solutions.

This patch is to add doxygen style comments for some elements in vp-dm_vperipheral ivshmem module.

Tracked-On: #8665

### CODE REVIEW

**Comment by haiwei-li** [comment]
@shiqingg pls help to review. Thanks!

**Comment by yuhuanX** [comment]
Can one of the admins verify this patch?

**Review by shiqingg — CHANGES_REQUESTED** [review]

**Review by shiqingg — APPROVED** [review]

**Review by lifeix — APPROVED** [review]

**Comment by yuhuanX** [comment]
start to run premerge test

**Comment by yuhuanX** [comment]
start to run premerge test

**Pull request merged**
