### PR TITLE
Hv vrtc for Prelanuched VM and RTVM

### PR DESCRIPTION
**Pull request by YuanyuanZhao609**
Now ACRN would emulate vRTC for non-RT pre-launched VM, RTVM and
Service VM.
For vRTC read, ACRN would only return the the physical RTC register value;
for vRTC write, ACRN would ignore it.

New implement is:
1. Service OS read and write physical RTC.
2. The initial vRTC of each VM will is same with physical RTC, i.e. the RTC of service VM.
3. Guest VM can re-program its RTC (thu NTP etc.), but the update of guest RTC will be 
emulated by Hypervisor through 'offset_rtctime'.
4. Service VM will update physical RTC. So, if the system shuts down, hypervisor can rely 
on #2 for each VM to get right initial RTC (sync with real NTP), without saving the “offset_rtctime”.
5. A calibration of vrtc will trigger by timer every 3 hours to keep
precision.
6. When write the physical RTC, will reset the 'offset_rtctime' of each
guest VM.

Tracked-On: #7440

### CODE REVIEW

**Comment by acrnsi** [comment]
Can one of the admins verify this patch?

**Comment by GGGZZZRRR** [comment]
@YuanyuanZhao609 please check code scan error
+ cat codescan_report.txt
Total Warnings: 144
Suppressed Warnings: 87

Rule view:
   ----------------------------------------------
   Rule                                    Count
   ----------------------------------------------
   acrn-c-ep-05                            38
   acrn-c-fn-05-06                         1
   acrn-c-ty-02                            16
   clang-analyzer-core.CallAndMessage      1
   clang-analyzer-deadcode.DeadStores      1

File view:
   --------------------------------
   File                      Count
   --------------------------------
   hypervisor/dm/vrtc.c      57
   --------------------------------
   Total                     57
   --------------------------------

All warnings:
/home/acrn/workspace/acrn-hypervisor-codescan-native_1158/acrn-hypervisor/hypervisor/dm/vrtc.c:101:44: warning: parentheses required around operands of conditional operators for explicit precedence [acrn-c-ep-05]
        return month_days[(month) - 1U] + (month == FEBRUARY ? leapyear(year) : 0U);
                                           ^
/home/acrn/workspace/acrn-hypervisor-codescan-native_1158/acrn-hypervisor/hypervisor/dm/vrtc.c:130:24: warning: values of type 'int' cannot be used as operands of bitwise operators [acrn-c-ty-02]
        return ((rtc->reg_b & RTCSB_BCD) ? val : bin2bcd_data[val]);
                              ^
/home/acrn/workspace/acrn-hypervisor-codescan-native_1158/acrn-hypervisor/hypervisor/include/dm/mc146818rtc.h:62:19: note: expanded from macro 'RTCSB_BCD'
#define RTCSB_BCD       0x04    /* 0 = BCD, 1 = Binary coded time */
                        ^
/home/acrn/workspace/acrn-hypervisor-codescan-native_1158/acrn-hypervisor/hypervisor/dm/vrtc.c:142:19: warning: values of type 'int' cannot be used as operands of bitwise operators [acrn-c-ty-02]
        if (rtc->reg_b & RTCSB_BCD) {
                         ^
/home/acrn/workspace/acrn-hypervisor-codescan-native_1158/acrn-hypervisor/hypervisor/include/dm/mc146818rtc.h:62:19: note: expanded from macro 'RTCSB_BCD'
#define RTCSB_BCD       0x04    /* 0 = BCD, 1 = Binary coded time */
                        ^
/home/acrn/workspace/acrn-hypervisor-codescan-native_1158/acrn-hypervisor/hypervisor/dm/vrtc.c:145:11: warning: values of type 'int32_t' (aka 'int') cannot be used as operands of bitwise operators [acrn-c-ty-02]
                lower = val & 0xfU;
                        ^
/home/acrn/workspace/acrn-hypervisor-codescan-native_1158/acrn-hypervisor/hypervisor/dm/vrtc.c:146:11: warning: values of type 'int32_t' (aka 'int') cannot be used as operands of bitwise operators [acrn-c-ty-02]
                upper = (val >> 4) & 0xfU;
                        ^
/home/acrn/workspace/acrn-hypervisor-codescan-native_1158/acrn-hypervisor/hypervisor/dm/vrtc.c:146:12: warning: values of type 'int32_t' (aka 'int') cannot be used as operands of bitwise operators [acrn-c-ty-02]
                upper = (val >> 4) & 0xfU;
                         ^
/home/acrn/workspace/acrn-hypervisor-codescan-native_1158/acrn-hypervisor/hypervisor/dm/vrtc.c:148:7: warning: parentheses required around this expression for explicit precedence [acrn-c-ep-05]
                if (lower > 9U || upper > 9U) {
                    ^
/home/acrn/workspace/acrn-hypervisor-codescan-native_1158/acrn-hypervisor/hypervisor/dm/vrtc.c:148:21: warning: parentheses required around this expression for explicit precedence [acrn-c-ep-05]
                if (lower > 9U || upper > 9U) {
                                  ^
/home/acrn/workspace/acrn-hypervisor-codescan-native_1158/acrn-hypervisor/hypervisor/dm/vrtc.c:168:6: warning: parentheses required around this expression for explicit precedence [acrn-c-ep-05]
        if (ct->mon < 1U || ct->mon > 12U || ct->day < 1U ||
            ^
/home/acrn/workspace/acrn-hypervisor-codescan-native_1158/acrn-hypervisor/hypervisor/dm/vrtc.c:168:22: warning: parentheses required around this expression for explicit precedence [acrn-c-ep-05]
        if (ct->mon < 1U || ct->mon > 12U || ct->day < 1U ||
                            ^
/home/acrn/workspace/acrn-hypervisor-codescan-native_1158/acrn-hypervisor/hypervisor/dm/vrtc.c:168:39: warning: parentheses required around this expression for explicit precedence [acrn-c-ep-05]
        if (ct->mon < 1U || ct->mon > 12U || ct->day < 1U ||
                                             ^
/home/acrn/workspace/acrn-hypervisor-codescan-native_1158/acrn-hypervisor/hypervisor/dm/vrtc.c:169:4: warning: parentheses required around this expression for explicit precedence [acrn-c-ep-05]
                        ct->day > days_in_month(year, ct->mon) ||
                        ^
/home/acrn/workspace/acrn-hypervisor-codescan-native_1158/acrn-hypervisor/hypervisor/dm/vrtc.c:170:4: warning: parentheses required around this expression for explicit precedence [acrn-c-ep-05]
                        ct->hour > 23U ||  ct->min > 59U || ct->sec > 59U ||
                        ^
/home/acrn/workspace/acrn-hypervisor-codescan-native_1158/acrn-hypervisor/hypervisor/dm/vrtc.c:170:23: warning: parentheses required around this expression for explicit precedence [acrn-c-ep-05]
                        ct->hour > 23U ||  ct->min > 59U || ct->sec > 59U ||
                                           ^
/home/acrn/workspace/acrn-hypervisor-codescan-native_1158/acrn-hypervisor/hypervisor/dm/vrtc.c:170:40: warning: parentheses required around this expression for explicit precedence [acrn-c-ep-05]
                        ct->hour > 23U ||  ct->min > 59U || ct->sec > 59U ||
                                                            ^
/home/acrn/workspace/acrn-hypervisor-codescan-native_1158/acrn-hypervisor/hypervisor/dm/vrtc.c:171:4: warning: parentheses required around this expression for explicit precedence [acrn-c-ep-05]
                        year < POSIX_BASE_YEAR || year > 2037U) {
                        ^
/home/acrn/workspace/acrn-hypervisor-codescan-native_1158/acrn-hypervisor/hypervisor/dm/vrtc.c:171:30: warning: parentheses required around this expression for explicit precedence [acrn-c-ep-05]
                        year < POSIX_BASE_YEAR || year > 2037U) {
                                                  ^
/home/acrn/workspace/acrn-hypervisor-codescan-native_1158/acrn-hypervisor/hypervisor/dm/vrtc.c:232:6: warning: parentheses required around this expression for explicit precedence [acrn-c-ep-05]
        if (ct->mon > 12U || ct->year > 2037 || ct->day > days_in_month(ct->year, ct->mon)) {
            ^
/home/acrn/workspace/acrn-hypervisor-codescan-native_1158/acrn-hypervisor/hypervisor/dm/vrtc.c:232:23: warning: parentheses required around this expression for explicit precedence [acrn-c-ep-05]
        if (ct->mon > 12U || ct->year > 2037 || ct->day > days_in_month(ct->year, ct->mon)) {
                             ^
/home/acrn/workspace/acrn-hypervisor-codescan-native_1158/acrn-hypervisor/hypervisor/dm/vrtc.c:232:42: warning: parentheses required around this expression for explicit precedence [acrn-c-ep-05]
        if (ct->mon > 12U || ct->year > 2037 || ct->day > days_in_month(ct->year, ct->mon)) {
                                                ^
/home/acrn/workspace/acrn-hypervisor-codescan-native_1158/acrn-hypervisor/hypervisor/dm/vrtc.c:251:7: warning: parentheses required around this expression for explicit precedence [acrn-c-ep-05]
                if (rtcget(rtc, rtc->sec, &ct.sec) < 0 || rtcget(rtc, rtc->min, &ct.min) < 0 ||
                    ^
/home/acrn/workspace/acrn-hypervisor-codescan-native_1158/acrn-hypervisor/hypervisor/dm/vrtc.c:251:45: warning: parentheses required around this expression for explicit precedence [acrn-c-ep-05]
                if (rtcget(rtc, rtc->sec, &ct.sec) < 0 || rtcget(rtc, rtc->min, &ct.min) < 0 ||
                                                          ^
/home/acrn/workspace/acrn-hypervisor-codescan-native_1158/acrn-hypervisor/hypervisor/dm/vrtc.c:252:5: warning: parentheses required around this expression for explicit precedence [acrn-c-ep-05]
                                rtcget(rtc, rtc->day_of_month, &ct.day) < 0 ||
                                ^
/home/acrn/workspace/acrn-hypervisor-codescan-native_1158/acrn-hypervisor/hypervisor/dm/vrtc.c:253:5: warning: parentheses required around this expression for explicit precedence [acrn-c-ep-05]
                                rtcget(rtc, rtc->month, &ct.mon) < 0 || rtcget(rtc, rtc->year, &year) < 0 ||
                                ^
/home/acrn/workspace/acrn-hypervisor-codescan-native_1158/acrn-hypervisor/hypervisor/dm/vrtc.c:253:45: warning: parentheses required around this expression for explicit precedence [acrn-c-ep-05]
                                rtcget(rtc, rtc->month, &ct.mon) < 0 || rtcget(rtc, rtc->year, &year) < 0 ||
                                                                        ^
/home/acrn/workspace/acrn-hypervisor-codescan-native_1158/acrn-hypervisor/hypervisor/dm/vrtc.c:254:5: warning: parentheses required around this expression for explicit precedence [acrn-c-ep-05]
                                rtcget(rtc, rtc->century, &century) < 0) {
                                ^
/home/acrn/workspace/acrn-hypervisor-codescan-native_1158/acrn-hypervisor/hypervisor/dm/vrtc.c:258:4: warning: Value stored to 'err' is never read [clang-analyzer-deadcode.DeadStores]
                        err = -1;
                        ^     ~~
/home/acrn/workspace/acrn-hypervisor-codescan-native_1158/acrn-hypervisor/hypervisor/dm/vrtc.c:258:4: note: Value stored to 'err' is never read
                        err = -1;
                        ^     ~~
/home/acrn/workspace/acrn-hypervisor-codescan-native_1158/acrn-hypervisor/hypervisor/dm/vrtc.c:267:21: warning: values of type 'int' cannot be used as operands of bitwise operators [acrn-c-ty-02]
                if ((rtc->reg_b & RTCSB_24HR) == 0) {
                                  ^
/home/acrn/workspace/acrn-hypervisor-codescan-native_1158/acrn-hypervisor/hypervisor/include/dm/mc146818rtc.h:61:20: note: expanded from macro 'RTCSB_24HR'
#define RTCSB_24HR      0x02    /* 0 = 12 hours, 1 = 24 hours */
                        ^
/home/acrn/workspace/acrn-hypervisor-codescan-native_1158/acrn-hypervisor/hypervisor/dm/vrtc.c:268:8: warning: values of type 'int32_t' (aka 'int') cannot be used as operands of bitwise operators [acrn-c-ty-02]
                        if (hour & 0x80U) {
                            ^
/home/acrn/workspace/acrn-hypervisor-codescan-native_1158/acrn-hypervisor/hypervisor/dm/vrtc.c:275:4: warning: 4th function call argument is an uninitialized value [clang-analyzer-core.CallAndMessage]
                        RTC_ERR("Invalid RTC hour %#x/%d\n", rtc->hour, ct.hour);
                        ^
/home/acrn/workspace/acrn-hypervisor-codescan-native_1158/acrn-hypervisor/hypervisor/dm/vrtc.c:42:18: note: expanded from macro 'RTC_ERR'
# define RTC_ERR pr_err
                 ^
/home/acrn/workspace/acrn-hypervisor-codescan-native_1158/acrn-hypervisor/hypervisor/include/debug/logmsg.h:95:3: note: expanded from macro 'pr_err'
                do_logmsg(LOG_ERROR, pr_prefix __VA_ARGS__);    \
                ^
/home/acrn/workspace/acrn-hypervisor-codescan-native_1158/acrn-hypervisor/hypervisor/dm/vrtc.c:650:25: note: Calling 'vrtc_get_physical_rtc_time'
        time_t physical_time = vrtc_get_physical_rtc_time(&temp_vrtc);
                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/acrn/workspace/acrn-hypervisor-codescan-native_1158/acrn-hypervisor/hypervisor/dm/vrtc.c:627:9: note: Calling 'rtc_to_secs'
        return rtc_to_secs(vrtc);
               ^~~~~~~~~~~~~~~~~
/home/acrn/workspace/acrn-hypervisor-codescan-native_1158/acrn-hypervisor/hypervisor/dm/vrtc.c:251:7: note: Left side of '||' is false
                if (rtcget(rtc, rtc->sec, &ct.sec) < 0 || rtcget(rtc, rtc->min, &ct.min) < 0 ||
                    ^
/home/acrn/workspace/acrn-hypervisor-codescan-native_1158/acrn-hypervisor/hypervisor/dm/vrtc.c:251:7: note: Left side of '||' is false
/home/acrn/workspace/acrn-hypervisor-codescan-native_1158/acrn-hypervisor/hypervisor/dm/vrtc.c:251:7: note: Left side of '||' is false
/home/acrn/workspace/acrn-hypervisor-codescan-native_1158/acrn-hypervisor/hypervisor/dm/vrtc.c:251:7: note: Left side of '||' is false
/home/acrn/workspace/acrn-hypervisor-codescan-native_1158/acrn-hypervisor/hypervisor/dm/vrtc.c:251:7: note: Left side of '||' is false
/home/acrn/workspace/acrn-hypervisor-codescan-native_1158/acrn-hypervisor/hypervisor/dm/vrtc.c:251:3: note: Taking false branch
                if (rtcget(rtc, rtc->sec, &ct.sec) < 0 || rtcget(rtc, rtc->min, &ct.min) < 0 ||
                ^
/home/acrn/workspace/acrn-hypervisor-codescan-native_1158/acrn-hypervisor/hypervisor/dm/vrtc.c:267:7: note: Assuming the condition is false
                if ((rtc->reg_b & RTCSB_24HR) == 0) {
                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/acrn/workspace/acrn-hypervisor-codescan-native_1158/acrn-hypervisor/hypervisor/dm/vrtc.c:267:3: note: Taking false branch
                if ((rtc->reg_b & RTCSB_24HR) == 0) {
                ^
/home/acrn/workspace/acrn-hypervisor-codescan-native_1158/acrn-hypervisor/hypervisor/dm/vrtc.c:273:9: note: Calling 'rtcget'
                err = rtcget(rtc, hour, &ct.hour);
                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/acrn/workspace/acrn-hypervisor-codescan-native_1158/acrn-hypervisor/hypervisor/dm/vrtc.c:142:2: note: Taking false branch
        if (rtc->reg_b & RTCSB_BCD) {
        ^
/home/acrn/workspace/acrn-hypervisor-codescan-native_1158/acrn-hypervisor/hypervisor/dm/vrtc.c:148:7: note: Assuming 'lower' is > 9
                if (lower > 9U || upper > 9U) {
                    ^~~~~~~~~~
/home/acrn/workspace/acrn-hypervisor-codescan-native_1158/acrn-hypervisor/hypervisor/dm/vrtc.c:148:18: note: Left side of '||' is true
                if (lower > 9U || upper > 9U) {
                               ^
/home/acrn/workspace/acrn-hypervisor-codescan-native_1158/acrn-hypervisor/hypervisor/dm/vrtc.c:154:2: note: Returning without writing to '*retval'
        return errno;
        ^
/home/acrn/workspace/acrn-hypervisor-codescan-native_1158/acrn-hypervisor/hypervisor/dm/vrtc.c:154:2: note: Returning the value -22 (loaded from 'errno'), which participates in a condition later
        return errno;
        ^~~~~~~~~~~~
/home/acrn/workspace/acrn-hypervisor-codescan-native_1158/acrn-hypervisor/hypervisor/dm/vrtc.c:273:9: note: Returning from 'rtcget'
                err = rtcget(rtc, hour, &ct.hour);
                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/acrn/workspace/acrn-hypervisor-codescan-native_1158/acrn-hypervisor/hypervisor/dm/vrtc.c:274:7: note: 'err' is -22
                if (err) {
                    ^~~
/home/acrn/workspace/acrn-hypervisor-codescan-native_1158/acrn-hypervisor/hypervisor/dm/vrtc.c:274:3: note: Taking true branch
                if (err) {
                ^
/home/acrn/workspace/acrn-hypervisor-codescan-native_1158/acrn-hypervisor/hypervisor/dm/vrtc.c:275:4: note: 4th function call argument is an uninitialized value
                        RTC_ERR("Invalid RTC hour %#x/%d\n", rtc->hour, ct.hour);
                        ^
/home/acrn/workspace/acrn-hypervisor-codescan-native_1158/acrn-hypervisor/hypervisor/dm/vrtc.c:42:18: note: expanded from macro 'RTC_ERR'
# define RTC_ERR pr_err
                 ^
/home/acrn/workspace/acrn-hypervisor-codescan-native_1158/acrn-hypervisor/hypervisor/include/debug/logmsg.h:95:3: note: expanded from macro 'pr_err'
                do_logmsg(LOG_ERROR, pr_prefix __VA_ARGS__);    \
                ^                              ~~~~~~~~~~~
/home/acrn/workspace/acrn-hypervisor-codescan-native_1158/acrn-hypervisor/hypervisor/dm/vrtc.c:278:21: warning: values of type 'int' cannot be used as operands of bitwise operators [acrn-c-ty-02]
                if ((rtc->reg_b & RTCSB_24HR) == 0) {
                                  ^
/home/acrn/workspace/acrn-hypervisor-codescan-native_1158/acrn-hypervisor/hypervisor/include/dm/mc146818rtc.h:61:20: note: expanded from macro 'RTCSB_24HR'
#define RTCSB_24HR      0x02    /* 0 = 12 hours, 1 = 24 hours */
                        ^
/home/acrn/workspace/acrn-hypervisor-codescan-native_1158/acrn-hypervisor/hypervisor/dm/vrtc.c:279:8: warning: parentheses required around this expression for explicit precedence [acrn-c-ep-05]
                        if (ct.hour >= 1 && ct.hour <= 12) {
                            ^
/home/acrn/workspace/acrn-hypervisor-codescan-native_1158/acrn-hypervisor/hypervisor/dm/vrtc.c:279:24: warning: parentheses required around this expression for explicit precedence [acrn-c-ep-05]
                        if (ct.hour >= 1 && ct.hour <= 12) {
                                            ^
/home/acrn/workspace/acrn-hypervisor-codescan-native_1158/acrn-hypervisor/hypervisor/dm/vrtc.c:340:6: warning: parentheses required around this expression for explicit precedence [acrn-c-ep-05]
        if (rtctime > 0 && clk_ts_to_ct(rtctime, &ct) == 0) {
            ^
/home/acrn/workspace/acrn-hypervisor-codescan-native_1158/acrn-hypervisor/hypervisor/dm/vrtc.c:340:21: warning: parentheses required around this expression for explicit precedence [acrn-c-ep-05]
        if (rtctime > 0 && clk_ts_to_ct(rtctime, &ct) == 0) {
                           ^
/home/acrn/workspace/acrn-hypervisor-codescan-native_1158/acrn-hypervisor/hypervisor/dm/vrtc.c:345:20: warning: values of type 'int' cannot be used as operands of bitwise operators [acrn-c-ty-02]
                if (rtc->reg_b & RTCSB_24HR) {
                                 ^
/home/acrn/workspace/acrn-hypervisor-codescan-native_1158/acrn-hypervisor/hypervisor/include/dm/mc146818rtc.h:61:20: note: expanded from macro 'RTCSB_24HR'
#define RTCSB_24HR      0x02    /* 0 = 12 hours, 1 = 24 hours */
                        ^
/home/acrn/workspace/acrn-hypervisor-codescan-native_1158/acrn-hypervisor/hypervisor/dm/vrtc.c:369:7: warning: parentheses required around this expression for explicit precedence [acrn-c-ep-05]
                if ((rtc->reg_b & RTCSB_24HR) == 0 && ct.hour >= 12) {
                    ^
/home/acrn/workspace/acrn-hypervisor-codescan-native_1158/acrn-hypervisor/hypervisor/dm/vrtc.c:369:21: warning: values of type 'int' cannot be used as operands of bitwise operators [acrn-c-ty-02]
                if ((rtc->reg_b & RTCSB_24HR) == 0 && ct.hour >= 12) {
                                  ^
/home/acrn/workspace/acrn-hypervisor-codescan-native_1158/acrn-hypervisor/hypervisor/include/dm/mc146818rtc.h:61:20: note: expanded from macro 'RTCSB_24HR'
#define RTCSB_24HR      0x02    /* 0 = 12 hours, 1 = 24 hours */
                        ^
/home/acrn/workspace/acrn-hypervisor-codescan-native_1158/acrn-hypervisor/hypervisor/dm/vrtc.c:369:41: warning: parentheses required around this expression for explicit precedence [acrn-c-ep-05]
                if ((rtc->reg_b & RTCSB_24HR) == 0 && ct.hour >= 12) {
                                                      ^
/home/acrn/workspace/acrn-hypervisor-codescan-native_1158/acrn-hypervisor/hypervisor/dm/vrtc.c:422:35: warning: values of type 'int' cannot be used as operands of bitwise operators [acrn-c-ty-02]
        return (cmos_read(RTC_STATUSA) & RTCSA_TUP)?1:0;
                                         ^
/home/acrn/workspace/acrn-hypervisor-codescan-native_1158/acrn-hypervisor/hypervisor/include/dm/mc146818rtc.h:58:19: note: expanded from macro 'RTCSA_TUP'
#define RTCSA_TUP       0x80    /* time update, don't look now */
                        ^
/home/acrn/workspace/acrn-hypervisor-codescan-native_1158/acrn-hypervisor/hypervisor/dm/vrtc.c:463:38: warning: values of type 'int' cannot be used as operands of bitwise operators [acrn-c-ty-02]
        return ((rtc->rtcdev.reg_b & RTCSB_HALT) != 0U);
                                     ^
/home/acrn/workspace/acrn-hypervisor-codescan-native_1158/acrn-hypervisor/hypervisor/include/dm/mc146818rtc.h:64:20: note: expanded from macro 'RTCSB_HALT'
#define RTCSB_HALT      0x80    /* stop clock updates */
                        ^
/home/acrn/workspace/acrn-hypervisor-codescan-native_1158/acrn-hypervisor/hypervisor/dm/vrtc.c:472:20: warning: values of type 'int' cannot be used as operands of bitwise operators [acrn-c-ty-02]
        if ((rtc->reg_b & RTCSB_AINTR) != 0U) {
                          ^
/home/acrn/workspace/acrn-hypervisor-codescan-native_1158/acrn-hypervisor/hypervisor/include/dm/mc146818rtc.h:63:21: note: expanded from macro 'RTCSB_AINTR'
#define RTCSB_AINTR     0x20    /* 1 = enable alarm interrupt */
                        ^
/home/acrn/workspace/acrn-hypervisor-codescan-native_1158/acrn-hypervisor/hypervisor/dm/vrtc.c:476:7: warning: parentheses required around this expression for explicit precedence [acrn-c-ep-05]
                if (current >= alarm - RTC_DELTA && current <= alarm + RTC_DELTA) {
                    ^
/home/acrn/workspace/acrn-hypervisor-codescan-native_1158/acrn-hypervisor/hypervisor/dm/vrtc.c:476:18: warning: parentheses required around this expression for explicit precedence [acrn-c-ep-05]
                if (current >= alarm - RTC_DELTA && current <= alarm + RTC_DELTA) {
                               ^
/home/acrn/workspace/acrn-hypervisor-codescan-native_1158/acrn-hypervisor/hypervisor/dm/vrtc.c:476:39: warning: parentheses required around this expression for explicit precedence [acrn-c-ep-05]
                if (current >= alarm - RTC_DELTA && current <= alarm + RTC_DELTA) {
                                                    ^
/home/acrn/workspace/acrn-hypervisor-codescan-native_1158/acrn-hypervisor/hypervisor/dm/vrtc.c:476:50: warning: parentheses required around this expression for explicit precedence [acrn-c-ep-05]
                if (current >= alarm - RTC_DELTA && current <= alarm + RTC_DELTA) {
                                                               ^
/home/acrn/workspace/acrn-hypervisor-codescan-native_1158/acrn-hypervisor/hypervisor/dm/vrtc.c:485:11: warning: values of type 'int' cannot be used as operands of bitwise operators [acrn-c-ty-02]
                        ret |= TRIGGER_ALARM;
                               ^
/home/acrn/workspace/acrn-hypervisor-codescan-native_1158/acrn-hypervisor/hypervisor/dm/vrtc.c:459:24: note: expanded from macro 'TRIGGER_ALARM'
#define TRIGGER_ALARM   (RTCIR_ALARM | RTCIR_INT)
                         ^
/home/acrn/workspace/acrn-hypervisor-codescan-native_1158/acrn-hypervisor/hypervisor/include/dm/mc146818rtc.h:67:21: note: expanded from macro 'RTCIR_ALARM'
#define RTCIR_ALARM     0x20    /* alarm intr */
                        ^
/home/acrn/workspace/acrn-hypervisor-codescan-native_1158/acrn-hypervisor/hypervisor/dm/vrtc.c:541:10: warning: parentheses required around this expression for explicit precedence [acrn-c-ep-05]
        return (offset == RTC_SEC || offset == RTC_MIN || offset == RTC_HRS || offset == RTC_DAY
                ^
/home/acrn/workspace/acrn-hypervisor-codescan-native_1158/acrn-hypervisor/hypervisor/dm/vrtc.c:541:31: warning: parentheses required around this expression for explicit precedence [acrn-c-ep-05]
        return (offset == RTC_SEC || offset == RTC_MIN || offset == RTC_HRS || offset == RTC_DAY
                                     ^
/home/acrn/workspace/acrn-hypervisor-codescan-native_1158/acrn-hypervisor/hypervisor/dm/vrtc.c:541:52: warning: parentheses required around this expression for explicit precedence [acrn-c-ep-05]
        return (offset == RTC_SEC || offset == RTC_MIN || offset == RTC_HRS || offset == RTC_DAY
                                                          ^
/home/acrn/workspace/acrn-hypervisor-codescan-native_1158/acrn-hypervisor/hypervisor/dm/vrtc.c:541:73: warning: parentheses required around this expression for explicit precedence [acrn-c-ep-05]
        return (offset == RTC_SEC || offset == RTC_MIN || offset == RTC_HRS || offset == RTC_DAY
                                                                               ^
/home/acrn/workspace/acrn-hypervisor-codescan-native_1158/acrn-hypervisor/hypervisor/dm/vrtc.c:542:7: warning: parentheses required around this expression for explicit precedence [acrn-c-ep-05]
                        || offset == RTC_MONTH || offset == RTC_YEAR || offset == RTC_CENTURY);
                           ^
/home/acrn/workspace/acrn-hypervisor-codescan-native_1158/acrn-hypervisor/hypervisor/dm/vrtc.c:542:30: warning: parentheses required around this expression for explicit precedence [acrn-c-ep-05]
                        || offset == RTC_MONTH || offset == RTC_YEAR || offset == RTC_CENTURY);
                                                  ^
/home/acrn/workspace/acrn-hypervisor-codescan-native_1158/acrn-hypervisor/hypervisor/dm/vrtc.c:542:52: warning: parentheses required around this expression for explicit precedence [acrn-c-ep-05]
                        || offset == RTC_MONTH || offset == RTC_YEAR || offset == RTC_CENTURY);
                                                                        ^
/home/acrn/workspace/acrn-hypervisor-codescan-native_1158/acrn-hypervisor/hypervisor/dm/vrtc.c:592:5: warning: parameter value is reassigned [acrn-c-fn-05-06]
                                value &= 0x7f;
                                ^
/home/acrn/workspace/acrn-hypervisor-codescan-native_1158/acrn-hypervisor/hypervisor/dm/vrtc.c:686:51: warning: values of type 'int' cannot be used as operands of bitwise operators [acrn-c-ty-02]
        vrtcdev->reg_a = cmos_get_reg_val(RTC_STATUSA) & (~RTCSA_TUP);
                                                         ^
/home/acrn/workspace/acrn-hypervisor-codescan-native_1158/acrn-hypervisor/hypervisor/dm/vrtc.c:686:53: warning: values of type 'int' cannot be used as operands of bitwise operators [acrn-c-ty-02]
        vrtcdev->reg_a = cmos_get_reg_val(RTC_STATUSA) & (~RTCSA_TUP);
                                                           ^
/home/acrn/workspace/acrn-hypervisor-codescan-native_1158/acrn-hypervisor/hypervisor/include/dm/mc146818rtc.h:58:19: note: expanded from macro 'RTCSA_TUP'
#define RTCSA_TUP       0x80    /* time update, don't look now */
                        ^

**Comment by szhen11** [comment]
@dongyaozu @lifeix Please help to approve this PR, thanks.

**Comment by junjiemao1** [comment]
Fine with me. @dongyaozu @lifeix Please kindly review and comment/approve. Thanks!

**Review by dongyaozu — APPROVED** [review]

**Pull request merged**
