### PR TITLE
Allow only one active SOS life_mngr socket

### PR DESCRIPTION
**Pull request by peterfang**
At most one VM is allowed to use "--pm_notify_channel uart" at a time, since only one socket connection to SOS life_mngr is allowed.

Monitor the listening socket in SOS life_mngr and close any additional connections after a socket connection is established. Identify a closed socket connection to SOS life_mngr as a failure in dm and fail gracefully.

Tracked-On: #5736
Signed-off-by: Peter Fang <peter.fang@intel.com>
Acked-by: Wang, Yu1 <yu1.wang@intel.com>

### CODE REVIEW

**Comment by HuiHuangShi** [comment]
No new violations to the coding guideline detected.<br>No New Name Conflict<br>No New Function Declaration/Definition Mismatch

**Comment by HuiHuangShi** [comment]
No new violations to the coding guideline detected.<br>No New Name Conflict<br>No New Function Declaration/Definition Mismatch

**Comment by HuiHuangShi** [comment]
No new violations to the coding guideline detected.<br>No New Name Conflict<br>No New Function Declaration/Definition Mismatch

**Comment by wenlingz** [comment]
@peterfang there is no KBL hybrid launch xml, so we use the default launch scripts(default has pm param ), could you add the KBL hybrid launch xml https://github.com/projectacrn/acrn-hypervisor/tree/master/misc/config_tools/data/nuc7i7dnb

**Comment by wenlingz** [comment]
@ywan170 please help approve this PR, thanks

**Comment by ywan170** [comment]
This patches had merged to master branch.
This PR needs @fyin1 to approve as it is for 2.4 branch.

**Review by fyin1 — APPROVED** [review]

**Pull request merged**
