### PR TITLE
update kernel-pk version to align with ACNR v0.1

### PR DESCRIPTION
**Pull request by ailun258**
update kernel-pk version to align with ACRN v0.1 release

Signed-off-by: ailun258 <ailin.yang@intel.com>

### CODE REVIEW

**Comment by NanlinXie** [comment]
Can one of the admins verify this patch?

**Comment by dongyaozu** [comment]
@jren1 please review

**Comment by gvancuts** [comment]
This is a good update since that is currently the correct version of `kernel-pk`. It does not however do any good to the v0.1 code base since the tagged version won't include this (unless someone fiddles with tags which we should really avoid doing).

PS: can you sign-off on your commits @ailun258 ?

**Comment by ailun258** [comment]
@NanlinXie @dongyaozu can you please help to get approval and merge this patch ?

**Comment by ailun258** [comment]
@anthonyzxu  can you please get approved of the patch?

**Comment by wenlingz** [comment]
verify +1

**Pull request merged**
