### PR TITLE
Hlt emulation

### PR DESCRIPTION
**Pull request by shuox**
When multiple vcpus running on same pcpu, it's good for performance
if vcpu can yield pcpu proactively. When vcpus are idle, they should release
pcpu and let scheduler pickup other vcpus to run.

To avoid sleep-after-wakeup race issue, HLT emulation introduces a block_flags
and a per-vcpu lock(vcpu_lock).

v4:
  1) thread will schedule out in wait_event, and scheudle back when get signalled.
  2) change 'done' in sched_event struct to bool type.

v3:
  1) concept: completion -> event
  2) Drop vcpu layer abstraction of event. Just use wait_event/signal_event provided
     by scheduling.

v2:
  Drop block_flags&vcpu_lock approach, and introduce a event completion mechanism
  in scheduling and vcpu layer.

Shuo A Liu (6):
  hv: PAUSE-loop exiting support in hypervisor
  hv: sched: simple event implemention
  hv: vcpu: wait and signal vcpu event support
  hv: Add vlapic_has_pending_intr of apicv to check pending interrupts
  hv: HLT emulation in hypervisor
  hv: Use HLT as the default idle action of service OS

 hypervisor/arch/x86/guest/vcpu.c                  |  5 ++-
 hypervisor/arch/x86/guest/vlapic.c                | 31 +++++++++++++++
 hypervisor/arch/x86/guest/vmcs.c                  |  9 ++++-
 hypervisor/arch/x86/guest/vmexit.c                | 20 +++++++++-
 hypervisor/common/hv_main.c                       |  1 +
 hypervisor/common/hypercall.c                     |  8 ++--
 hypervisor/common/schedule.c                      | 48 +++++++++++++++++++++++
 hypervisor/dm/io_req.c                            | 12 +-----
 hypervisor/include/arch/x86/guest/vcpu.h          |  7 ++++
 hypervisor/include/arch/x86/guest/vlapic.h        |  2 +
 hypervisor/include/common/schedule.h              | 11 ++++++
 hypervisor/scenarios/industry/vm_configurations.h |  2 +-
 hypervisor/scenarios/sdc/vm_configurations.h      |  2 +-
 hypervisor/scenarios/sdc2/vm_configurations.h     |  2 +-
 14 files changed, 136 insertions(+), 24 deletions(-)

### CODE REVIEW

**Comment by HuiHuangShi** [comment]
24 new potential violations to the coding guideline detected. Please help check. Thanks!
<1> config:part_config filename:/hypervisor/arch/x86/guest/vcpu.c func:resume_vcpu offset:714
reason:Procedure is not called or referenced in code analysed. : resume_vcpu
<2> config:sharing_config filename:/hypervisor/arch/x86/guest/vcpu.c func:resume_vcpu offset:714
reason:Procedure is not called or referenced in code analysed. : resume_vcpu
<3> config:common filename:/hypervisor/arch/x86/guest/vcpu.c func:prepare_vcpu offset:821
reason:Type conversion without cast. : (int and enum vcpu_event_type): i < VCPU_EVENT_NUM
<4> config:sharing_config filename:/hypervisor/common/event.c func:wait_event offset:35
reason:Potentially infinite loop found.
<5> config:part_config filename:/hypervisor/common/event.c func:wait_event offset:35
reason:Potentially infinite loop found.
<6> config:part_config filename:/hypervisor/dm/io_req.c func:acrn_insert_request offset:80
reason:Pointer param should be declared pointer to const. : vcpu
<7> config:sharing_config filename:/hypervisor/dm/io_req.c func:acrn_insert_request offset:80
reason:Pointer param should be declared pointer to const. : vcpu
<8> config:sharing_config filename:/hypervisor/dm/io_req.c func:emulate_io offset:526
reason:Pointer param should be declared pointer to const. : vcpu
<9> config:part_config filename:/hypervisor/dm/io_req.c func:emulate_io offset:526
reason:Pointer param should be declared pointer to const. : vcpu
<10> config:common filename:/hypervisor/arch/x86/guest/vmexit.c func:pause_vmexit_handler offset:282
reason:Static procedure is not explicitly called in code analysed. : pause_vmexit_handler
<11> config:part_config filename:/hypervisor/arch/x86/guest/vmexit.c func:hlt_vmexit_handler offset:288
reason:Pointer param should be declared pointer to const. : vcpu
<12> config:sharing_config filename:/hypervisor/arch/x86/guest/vmexit.c func:hlt_vmexit_handler offset:288
reason:Pointer param should be declared pointer to const. : vcpu
<13> config:common filename:/hypervisor/arch/x86/guest/vmexit.c func:hlt_vmexit_handler offset:288
reason:Static procedure is not explicitly called in code analysed. : hlt_vmexit_handler
<14> config:common filename:/hypervisor/arch/x86/guest/vlapic.c func:vlapic_accept_intr offset:593
reason:Implicit conversion: actual to formal param (MR). : (struct sched_event): param 1
<15> config:common filename:/hypervisor/arch/x86/guest/vlapic.c func:ptapic_has_pending_intr offset:1759
reason:Static procedure is not explicitly called in code analysed. : ptapic_has_pending_intr
<16> config:part_config filename:/hypervisor/arch/x86/guest/vlapic.c func:apicv_basic_has_pending_intr offset:2400
reason:Pointer param should be declared pointer to const. : vcpu
<17> config:sharing_config filename:/hypervisor/arch/x86/guest/vlapic.c func:apicv_basic_has_pending_intr offset:2400
reason:Pointer param should be declared pointer to const. : vcpu
<18> config:sharing_config filename:/hypervisor/arch/x86/guest/vlapic.c func:apicv_basic_has_pending_intr offset:2405
reason:Pointer not checked for null before use. : vlapic
<19> config:part_config filename:/hypervisor/arch/x86/guest/vlapic.c func:apicv_basic_has_pending_intr offset:2405
reason:Pointer not checked for null before use. : vlapic
<20> config:part_config filename:/hypervisor/arch/x86/guest/vlapic.c func:apicv_advanced_has_pending_intr offset:2410
reason:Pointer param should be declared pointer to const. : vcpu
<21> config:sharing_config filename:/hypervisor/arch/x86/guest/vlapic.c func:apicv_advanced_has_pending_intr offset:2410
reason:Pointer param should be declared pointer to const. : vcpu
<22> config:common filename:/hypervisor/arch/x86/guest/vlapic.c func:apicv_advanced_has_pending_intr offset:2410
reason:Static procedure is not explicitly called in code analysed. : apicv_advanced_has_pending_intr
<23> config:sharing_config filename:/hypervisor/arch/x86/guest/vlapic.c func:vlapic_has_pending_intr offset:2415
reason:Pointer param should be declared pointer to const. : vcpu
<24> config:part_config filename:/hypervisor/arch/x86/guest/vlapic.c func:vlapic_has_pending_intr offset:2415
reason:Pointer param should be declared pointer to const. : vcpu

No New Name Conflict

Function Declaration/Definition Mismatch Violation:
extern int32_t pause_vmexit_handler(struct acrn_vcpu * vcpu) 33 arch/x86/guest/vmexit.c
define int32_t pause_vmexit_handler(struct acrn_vcpu * __attribute__((unused)) vcpu) 282 arch/x86/guest/vmexit.c

**Comment by HuiHuangShi** [comment]
25 new potential violations to the coding guideline detected. Please help check. Thanks!<br><1> config:part_config filename:/hypervisor/arch/x86/guest/vcpu.c func:resume_vcpu offset:714<br> reason:Procedure is not called or referenced in code analysed. : resume_vcpu<br><2> config:sharing_config filename:/hypervisor/arch/x86/guest/vcpu.c func:resume_vcpu offset:714<br> reason:Procedure is not called or referenced in code analysed. : resume_vcpu<br><3> config:common filename:/hypervisor/arch/x86/guest/vcpu.c func:prepare_vcpu offset:821<br> reason:Value is not of appropriate type. :  (int and unsigned char): i   < 2U<br><4> config:common filename:/hypervisor/arch/x86/guest/vcpu.c func:prepare_vcpu offset:821<br> reason:Signed/unsigned conversion without cast. :  (int and unsigned int): i<br><5> config:sharing_config filename:/hypervisor/common/event.c func:wait_event offset:35<br> reason:Potentially infinite loop found.<br><6> config:part_config filename:/hypervisor/common/event.c func:wait_event offset:35<br> reason:Potentially infinite loop found.<br><7> config:part_config filename:/hypervisor/dm/io_req.c func:acrn_insert_request offset:80<br> reason:Pointer param should be declared pointer to const. : vcpu<br><8> config:sharing_config filename:/hypervisor/dm/io_req.c func:acrn_insert_request offset:80<br> reason:Pointer param should be declared pointer to const. : vcpu<br><9> config:sharing_config filename:/hypervisor/dm/io_req.c func:emulate_io offset:526<br> reason:Pointer param should be declared pointer to const. : vcpu<br><10> config:part_config filename:/hypervisor/dm/io_req.c func:emulate_io offset:526<br> reason:Pointer param should be declared pointer to const. : vcpu<br><11> config:common filename:/hypervisor/arch/x86/guest/vmexit.c func:pause_vmexit_handler offset:282<br> reason:Static procedure is not explicitly called in code analysed. : pause_vmexit_handler<br><12> config:part_config filename:/hypervisor/arch/x86/guest/vmexit.c func:hlt_vmexit_handler offset:288<br> reason:Pointer param should be declared pointer to const. : vcpu<br><13> config:sharing_config filename:/hypervisor/arch/x86/guest/vmexit.c func:hlt_vmexit_handler offset:288<br> reason:Pointer param should be declared pointer to const. : vcpu<br><14> config:common filename:/hypervisor/arch/x86/guest/vmexit.c func:hlt_vmexit_handler offset:288<br> reason:Static procedure is not explicitly called in code analysed. : hlt_vmexit_handler<br><15> config:common filename:/hypervisor/arch/x86/guest/vlapic.c func:vlapic_accept_intr offset:593<br> reason:Implicit conversion: actual to formal param (MR). :  (struct sched_event):  param  1<br><16> config:common filename:/hypervisor/arch/x86/guest/vlapic.c func:ptapic_has_pending_intr offset:1759<br> reason:Static procedure is not explicitly called in code analysed. : ptapic_has_pending_intr<br><17> config:part_config filename:/hypervisor/arch/x86/guest/vlapic.c func:apicv_basic_has_pending_intr offset:2400<br> reason:Pointer param should be declared pointer to const. : vcpu<br><18> config:sharing_config filename:/hypervisor/arch/x86/guest/vlapic.c func:apicv_basic_has_pending_intr offset:2400<br> reason:Pointer param should be declared pointer to const. : vcpu<br><19> config:sharing_config filename:/hypervisor/arch/x86/guest/vlapic.c func:apicv_basic_has_pending_intr offset:2405<br> reason:Pointer not checked for null before use. : vlapic<br><20> config:part_config filename:/hypervisor/arch/x86/guest/vlapic.c func:apicv_basic_has_pending_intr offset:2405<br> reason:Pointer not checked for null before use. : vlapic<br><21> config:part_config filename:/hypervisor/arch/x86/guest/vlapic.c func:apicv_advanced_has_pending_intr offset:2410<br> reason:Pointer param should be declared pointer to const. : vcpu<br><22> config:sharing_config filename:/hypervisor/arch/x86/guest/vlapic.c func:apicv_advanced_has_pending_intr offset:2410<br> reason:Pointer param should be declared pointer to const. : vcpu<br><23> config:common filename:/hypervisor/arch/x86/guest/vlapic.c func:apicv_advanced_has_pending_intr offset:2410<br> reason:Static procedure is not explicitly called in code analysed. : apicv_advanced_has_pending_intr<br><24> config:sharing_config filename:/hypervisor/arch/x86/guest/vlapic.c func:vlapic_has_pending_intr offset:2415<br> reason:Pointer param should be declared pointer to const. : vcpu<br><25> config:part_config filename:/hypervisor/arch/x86/guest/vlapic.c func:vlapic_has_pending_intr offset:2415<br> reason:Pointer param should be declared pointer to const. : vcpu<br><br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by HuiHuangShi** [comment]
23 new potential violations to the coding guideline detected. Please help check. Thanks!<br><1> config:part_config filename:/hypervisor/arch/x86/guest/vcpu.c func:resume_vcpu offset:714<br> reason:Procedure is not called or referenced in code analysed. : resume_vcpu<br><2> config:sharing_config filename:/hypervisor/arch/x86/guest/vcpu.c func:resume_vcpu offset:714<br> reason:Procedure is not called or referenced in code analysed. : resume_vcpu<br><3> config:sharing_config filename:/hypervisor/common/event.c func:wait_event offset:35<br> reason:Potentially infinite loop found.<br><4> config:part_config filename:/hypervisor/common/event.c func:wait_event offset:35<br> reason:Potentially infinite loop found.<br><5> config:part_config filename:/hypervisor/dm/io_req.c func:acrn_insert_request offset:80<br> reason:Pointer param should be declared pointer to const. : vcpu<br><6> config:sharing_config filename:/hypervisor/dm/io_req.c func:acrn_insert_request offset:80<br> reason:Pointer param should be declared pointer to const. : vcpu<br><7> config:sharing_config filename:/hypervisor/dm/io_req.c func:emulate_io offset:526<br> reason:Pointer param should be declared pointer to const. : vcpu<br><8> config:part_config filename:/hypervisor/dm/io_req.c func:emulate_io offset:526<br> reason:Pointer param should be declared pointer to const. : vcpu<br><9> config:common filename:/hypervisor/arch/x86/guest/vmexit.c func:pause_vmexit_handler offset:282<br> reason:Static procedure is not explicitly called in code analysed. : pause_vmexit_handler<br><10> config:part_config filename:/hypervisor/arch/x86/guest/vmexit.c func:hlt_vmexit_handler offset:288<br> reason:Pointer param should be declared pointer to const. : vcpu<br><11> config:sharing_config filename:/hypervisor/arch/x86/guest/vmexit.c func:hlt_vmexit_handler offset:288<br> reason:Pointer param should be declared pointer to const. : vcpu<br><12> config:common filename:/hypervisor/arch/x86/guest/vmexit.c func:hlt_vmexit_handler offset:288<br> reason:Static procedure is not explicitly called in code analysed. : hlt_vmexit_handler<br><13> config:common filename:/hypervisor/arch/x86/guest/vlapic.c func:vlapic_accept_intr offset:593<br> reason:Implicit conversion: actual to formal param (MR). :  (struct sched_event):  param  1<br><14> config:common filename:/hypervisor/arch/x86/guest/vlapic.c func:ptapic_has_pending_intr offset:1759<br> reason:Static procedure is not explicitly called in code analysed. : ptapic_has_pending_intr<br><15> config:part_config filename:/hypervisor/arch/x86/guest/vlapic.c func:apicv_basic_has_pending_intr offset:2400<br> reason:Pointer param should be declared pointer to const. : vcpu<br><16> config:sharing_config filename:/hypervisor/arch/x86/guest/vlapic.c func:apicv_basic_has_pending_intr offset:2400<br> reason:Pointer param should be declared pointer to const. : vcpu<br><17> config:sharing_config filename:/hypervisor/arch/x86/guest/vlapic.c func:apicv_basic_has_pending_intr offset:2405<br> reason:Pointer not checked for null before use. : vlapic<br><18> config:part_config filename:/hypervisor/arch/x86/guest/vlapic.c func:apicv_basic_has_pending_intr offset:2405<br> reason:Pointer not checked for null before use. : vlapic<br><19> config:part_config filename:/hypervisor/arch/x86/guest/vlapic.c func:apicv_advanced_has_pending_intr offset:2410<br> reason:Pointer param should be declared pointer to const. : vcpu<br><20> config:sharing_config filename:/hypervisor/arch/x86/guest/vlapic.c func:apicv_advanced_has_pending_intr offset:2410<br> reason:Pointer param should be declared pointer to const. : vcpu<br><21> config:common filename:/hypervisor/arch/x86/guest/vlapic.c func:apicv_advanced_has_pending_intr offset:2410<br> reason:Static procedure is not explicitly called in code analysed. : apicv_advanced_has_pending_intr<br><22> config:sharing_config filename:/hypervisor/arch/x86/guest/vlapic.c func:vlapic_has_pending_intr offset:2415<br> reason:Pointer param should be declared pointer to const. : vcpu<br><23> config:part_config filename:/hypervisor/arch/x86/guest/vlapic.c func:vlapic_has_pending_intr offset:2415<br> reason:Pointer param should be declared pointer to const. : vcpu<br><br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by wenlingz** [comment]
@shuox  please check your build fail, log as below:
**********************************************************************************************************
arch/x86/guest/vmexit.c: In function 'pause_vmexit_handler':
170 arch/x86/guest/vmexit.c:282:55: error: unused parameter 'vcpu' [-Werror=unused-parameter]
171   282 | static int32_t pause_vmexit_handler(struct acrn_vcpu *vcpu)
172       |                                     ~~~~~~~~~~~~~~~~~~^~~~
173 cc1: all warnings being treated as errors
174 make[2]: *** [Makefile:503: /root/workspace/acrn-hypervisor-premerge-build-image4/artifact/out/hv/whl-ipc-i5-uefi/hyp    ervisor/arch/x86/guest/vmexit.o] Error 1
175 make[2]: Leaving directory '/root/workspace/acrn-hypervisor-premerge-build-image4/acrn-hypervisor/hypervisor'
176 make[1]: *** [Makefile:113: hypervisor] Error 2
177 make[1]: Leaving directory '/root/workspace/acrn-hypervisor-premerge-build-image4/acrn-hypervisor'
178 make: *** [Makefile:238: hypervisor] Error 2
179 make: Leaving directory '/root/workspace/acrn-hypervisor-premerge-build-image4/acrn-ebtool'

**Pull request merged**
