### PR TITLE
Samples:Added the Kernel console parameter in boot.

### PR DESCRIPTION
**Pull request by santoshkumarlaxminarayanrai**
For GP-MRB ACRN using ttyS0 as console,
since this is release bootargs file so ttyS0
will be skipped in booting but needed kernel
console ttyS2 in bootargs to get the Kernel console.

Tracked-On: #1655

Signed-off-by: santoshkumar <santoshkumar.laxminarayan.rai@intel.com>

### CODE REVIEW

**Comment by anthonyzxu** [comment]
Why do we need ttyS2 for SOS in release version?

**Comment by santoshkumarlaxminarayanrai** [comment]
ttyS0 is a ACRN console and in release package for MRB we do not needed ACRN console but we still need kernel console to chose guest OS from SOS.

**Comment by HuiHuangShi** [comment]
1664 <br>The PR does not touch any hypervisor source file. Skip coding guideline checks.<br>

**Comment by HuiHuangShi** [comment]
1664 <br>The PR does not touch any hypervisor source file. Skip coding guideline checks.<br>

**Pull request merged**
