### PR TITLE
sos_bootargs_debug.txt: update to load GuC for SOS

### PR DESCRIPTION
**Pull request by rebeccasf**
Change kernel boot cmdline to load GuC firmware for SOS.

Tracked-On: #1524 
Proposed-by: Charles, Daniel <daniel.charles@intel.com>
Signed-off-by: Chang, Rebecca Swee Fun <rebecca.swee.fun.chang@intel.com>

### CODE REVIEW

**Comment by NanlinXie** [comment]
Can one of the admins verify this patch?

**Comment by rebeccasf** [comment]
Added "Tracked-on" information.

**Comment by NanlinXie** [comment]
OK to verify

**Comment by JasonChenCJ** [comment]
@rebeccasf ,  we should change sos_bootargs_release.txt as well.

**Comment by rebeccasf** [comment]
Hi everyone, please review the 3 commits in this pull request for GuC/HuC firmware loading in SOS.

**Comment by yakuizhao** [comment]
@rebeccasf , what is the purpose of changing the guc option?
Is it used to load Huc from Guc?

**Comment by chivakker** [comment]
@yakuizhao yes we want to enable GuC/HuC to test use cases across the board.  This depends on kernel being able to find the firmware which we've confirmed is the case with current setup on GP2.0 and NUC as advertised by acrn project.

**Comment by yakuizhao** [comment]
@chivakker , it sounds reasonable.
It will be better that the reason is added to the commit log.

**Comment by minhe1** [comment]
> @yakuizhao yes we want to enable GuC/HuC to test use cases across the board. This depends on kernel being able to find the firmware which we've confirmed is the case with current setup on GP2.0 and NUC as advertised by acrn project.

Charles, based on my previous test result, enable_guc=2 on SOS will cause its booting time very long because i915 will wait for the rootfs to find the firmware to load, and eventually it will fail.
Did you ever test this option on our SOS kernel?

**Comment by chivakker** [comment]
@minhe1 that's exactly what we should be able to evaluate and measure properly.

**Comment by minhe1** [comment]
> @minhe1 that's exactly what we should be able to evaluate and measure properly.

No, we cannot use this repo for evaluation purpose. Please fetch this branch, make your own local builds and verify this solution works on APL-MRB. Then submit pull request. Thanks.

**Comment by chivakker** [comment]
@minhe1 may I know what was your test with SOS? Is your testing using late load of GuC/HuC/  We have conducted testing with SOS mainline with late loading of GuC/HuC and it does work with the testing done so far. We're just using GuC for authentication of HuC and then use HuC features. 

I can pin point the patch that implements this and also provide our measurements, although we have not seeing it failing as you describe, so please share details.

**Comment by minhe1** [comment]
> @minhe1 may I know what was your test with SOS? Is your testing using late load of GuC/HuC/ We have conducted testing with SOS mainline with late loading of GuC/HuC and it does work with the testing done so far. We're just using GuC for authentication of HuC and then use HuC features.
> 
> I can pin point the patch that implements this and also provide our measurements, although we have not seeing it failing as you describe, so please share details.

It's tested on previous kernel 4.19-rc7, so I don't expect the guc/huc deferred loading would be there.

**Comment by chivakker** [comment]
FWIW, the patch to load late GuC/HuC is part of kernel base branch here: https://github.com/intel/mainline-tracking/commits/base

**Comment by rebeccasf** [comment]
Since this was approved, please merge this patch by today so that we can have this change build in the next service os. Thank you very much.

**Comment by chivakker** [comment]
when can this be merged? @yakuizhao @minhe1

**Comment by rebeccasf** [comment]
@NanlinXie what does CI: conflict means? Do we need to submit any new series?

**Comment by NanlinXie** [comment]
@rebeccasf  Please resolve conflict and update PR.

**Comment by ClaudZhang1995** [comment]
OK to Verify

**Comment by dongyaozu** [comment]
Do we still have conflict? If not, please merge

**Comment by NanlinXie** [comment]
@rebeccasf  Tracked-On ID should not be the PR number, you need create one new Git Issue and add the Git issue number.

**Comment by rebeccasf** [comment]
@chivakker can you help to open an issue in this github project?

**Comment by chivakker** [comment]
@rebeccasf amend you commit with this number https://github.com/projectacrn/acrn-hypervisor/issues/1638

**Comment by yakuizhao** [comment]
THe updated patch looks good to me and this patch is required when SOS needs to load Guc.

**Comment by rebeccasf** [comment]
@NanlinXie I have updated the Tracked-on info and rebased.

**Comment by rebeccasf** [comment]
Changed to track on https://github.com/projectacrn/acrn-hypervisor/pull/1640

**Pull request closed without merging**
