### PR TITLE
Vmx modularization

### PR DESCRIPTION
**Pull request by JasonChenCJ**
These patches are doing modularization for vmx files, it separate its operations into two parts, one for pure vmx operations, the other for vmcs operations which is vcpu related.

Tracked-On: #1842
Signed-off-by: Jason Chen CJ <jason.cj.chen@intel.com>
Acked-by: Eddie Dong <eddie.dong@intel.com>

### CODE REVIEW

**Comment by acrnsi** [comment]
Ok to verify

**Comment by HuiHuangShi** [comment]
2081<br>15 new potential violations to the coding guideline detected. Please help check. Thanks!  <br><br>1.filename:/hypervisor/arch/x86/pm.c&nbsp;&nbsp;function:None&nbsp;&nbsp;offset:11:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Variable should be defined once in only one file. : host_pm_s_state<br><br>2.filename:/hypervisor/arch/x86/vmcs.c&nbsp;&nbsp;function:None&nbsp;&nbsp;offset:0:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:More than 2000 executable reformatted lines in file.<br><br>3.filename:/hypervisor/arch/x86/vmcs.c&nbsp;&nbsp;function:None&nbsp;&nbsp;offset:12:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Macro redefinition without using #undef.     : DR7_INIT_VALUE<br><br>4.filename:/hypervisor/arch/x86/vmcs.c&nbsp;&nbsp;function:None&nbsp;&nbsp;offset:14:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Scope of variable could be reduced. : cr0_host_mask<br><br>5.filename:/hypervisor/arch/x86/vmcs.c&nbsp;&nbsp;function:None&nbsp;&nbsp;offset:17:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Scope of variable could be reduced. : cr4_host_mask<br><br>6.filename:/hypervisor/arch/x86/vmcs.c&nbsp;&nbsp;function:init_vmcs&nbsp;&nbsp;offset:872:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:DD data flow anomalies found.<br><br>7.filename:/hypervisor/arch/x86/vmx.c&nbsp;&nbsp;function:vmx_on&nbsp;&nbsp;offset:37:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:DD data flow anomalies found.<br><br>8.filename:/hypervisor/arch/x86/vmx.c&nbsp;&nbsp;function:vmx_on&nbsp;&nbsp;offset:37:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Globals used inside procedure.<br><br>9.filename:/hypervisor/arch/x86/vmx.c&nbsp;&nbsp;function:vmx_on&nbsp;&nbsp;offset:41:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Cast from integral type to pointer. : (unsigned char to void*): ( void * ) ( per_cpu_data [ ( get_cpu_id ( ) ) ] .vmxon_region )<br><br>10.filename:/hypervisor/arch/x86/vmx.c&nbsp;&nbsp;function:vmx_on&nbsp;&nbsp;offset:46:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Casting operation on a pointer. : (void* to unsigned int*): ( uint32_t * ) vmxon_region_va<br><br>11.filename:/hypervisor/arch/x86/vmx.c&nbsp;&nbsp;function:vmx_on&nbsp;&nbsp;offset:46:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Casting operation to a pointer. : (void* to unsigned int*): ( uint32_t * ) vmxon_region_va<br><br>12.filename:/hypervisor/arch/x86/vmx.c&nbsp;&nbsp;function:vmx_on&nbsp;&nbsp;offset:60:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:No cast for widening complex int expression (MR). :  (unsigned long and unsigned char): ( 1U << 0U ) | ( 1U << 2U )<br><br>13.filename:/hypervisor/arch/x86/vmx.c&nbsp;&nbsp;function:vmx_on&nbsp;&nbsp;offset:66:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Pointer not checked for null before use. : vmxon_region_va<br><br>14.filename:/hypervisor/arch/x86/vmx.c&nbsp;&nbsp;function:vmx_on&nbsp;&nbsp;offset:66:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Function return value potentially unused. : vmxon_region_pa<br><br>15.filename:/hypervisor/arch/x86/vmx.c&nbsp;&nbsp;function:vmx_off&nbsp;&nbsp;offset:113:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Globals used inside procedure.<br><br>

**Comment by shiqingg** [comment]
violation 1, 2, 7, 8, 9, 13, 14, 15 could be ignored.

violation 3, 4, 5, 12 are original violations and need to be fixed.
So, I will fix violation 3, 4, 5, 12 with other issues together later on.

Regarding to violation 6, need Jason's confirmation.
At line 894, `*vmcs_ptr = (void *)vcpu->arch.vmcs;`, but `vmcs_ptr` is not used anymore later on.
Do we still need this assignment?

Regarding to violation 10 and 11, need Jason's confirmation.
Formal param 1 type of `memcpy_s` is `void *` indeed, any special reason casting `vmxon_region_va` from `void *` to `uint32_t *`?

**Comment by JasonChenCJ** [comment]
@shiqingg :
Regarding to violation 6, need Jason's confirmation.
At line 894, *vmcs_ptr = (void *)vcpu->arch.vmcs;, but vmcs_ptr is not used anymore later on.
Do we still need this assignment?
This is set value for *vmcs_ptr, it's needed for a per_cpu value set.

Regarding to violation 10 and 11, need Jason's confirmation.
Formal param 1 type of memcpy_s is void * indeed, any special reason casting vmxon_region_va from void * to uint32_t *?

It's old violation,  could you help fix it?

**Comment by shiqingg** [comment]
violation 6 could be ignored.

I will fix violation 3, 4, 5, 10, 11 and 12 with other issues together later on.

**Pull request merged**
