### PR TITLE
delete pci_devices_ignore=(0:18:1)

### PR DESCRIPTION
**Pull request by ailun258**
delete pci_devices_ignore=(0:18:1) settings manually, because it has been set in acrn.conf by default, 
not need to change manually

Signed-off-by: ailun258 <ailin.yang@intel.com>

### CODE REVIEW

**Comment by NanlinXie** [comment]
Can one of the admins verify this patch?

**Comment by ailun258** [comment]
@NanlinXie why checking failed for this patch?

**Comment by lijinxia** [comment]
OK to verify

**Comment by ailun258** [comment]
@jren1 @dongyaozu @dbkinder  can you please approval and merge this patch

**Pull request merged**
