### PR TITLE
acrn-dm: enable debug option for acrn-dm

### PR DESCRIPTION
**Pull request by liuwei987**
enable acrn-dm debug option via RELEASE=0(by default)

Tracked-on: #2939
Reviewed-by: Minggui Cao <minggui.cao@intel.com>
Signed-off-by: Wei Liu <weix.w.liu@intel.com>

### CODE REVIEW

**Comment by HuiHuangShi** [comment]
No new violations to the coding guideline detected.<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by liuwei987** [comment]
> I didn't see the reason of the patch. What is the problem?

Hi Eddie,
On current stable branch, the watchdog mapping to warm reset only for the debug purpose, the watchdog mapping to cold reset will only for the release purpose.  Enable the debug option while building by default.

**Comment by acrnsi** [comment]
Ok to verify

**Comment by HuiHuangShi** [comment]
No new violations to the coding guideline detected.<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by acrnsi** [comment]
Ok to verify

**Comment by mcao6** [comment]
@fyin1 could you comment this patch? it is designed as the discussion for debug/release build of DM.

**Comment by HuiHuangShi** [comment]
No new violations to the coding guideline detected.<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by acrnsi** [comment]
Ok to verify

**Comment by HuiHuangShi** [comment]
No new violations to the coding guideline detected.<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by HuiHuangShi** [comment]
No new violations to the coding guideline detected.<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by HuiHuangShi** [comment]
No new violations to the coding guideline detected.<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by HuiHuangShi** [comment]
No new violations to the coding guideline detected.<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Pull request merged**
