### PR TITLE
Remove some unused functions in hypervisor

### PR DESCRIPTION
**Pull request by ying2liu**
v2->v3
Keep get_sos_boot_mode. It will be used by init_vm_boot_info.
v1->v2
Address review comments. Keep ticks_to_ms, TRACE_6C, vuart_deinit and vuart_deinit_connect for future use.

yliu79 (7):
  HV: remove unused function disable_iommu
  HV: remove unused function shutdown_vcpu
  HV: remove unused function resume_vm
  HV: remove unused function copy_to_gva
  HV: remove unused function vcpu_inject_ac
  HV: remove unused function sbuf_is_empty and sbuf_get
  HV: remove unused function is_dbg_uart_enabled

 hypervisor/arch/x86/guest/guest_memory.c         |  6 -----
 hypervisor/arch/x86/guest/vcpu.c                 |  7 ------
 hypervisor/arch/x86/guest/virq.c                 |  6 -----
 hypervisor/arch/x86/guest/vm.c                   | 15 ------------
 hypervisor/arch/x86/vtd.c                        |  5 ----
 hypervisor/debug/sbuf.c                          | 29 ------------------------
 hypervisor/debug/uart16550.c                     |  5 ----
 hypervisor/include/arch/x86/guest/guest_memory.h | 18 ---------------
 hypervisor/include/arch/x86/guest/vcpu.h         |  2 --
 hypervisor/include/arch/x86/guest/vm.h           |  1 -
 hypervisor/include/arch/x86/irq.h                | 11 ---------
 hypervisor/include/arch/x86/vtd.h                |  8 -------
 hypervisor/include/debug/uart16550.h             |  1 -
 hypervisor/release/console.c                     |  1 -
 14 files changed, 115 deletions(-)

### CODE REVIEW

**Comment by HuiHuangShi** [comment]
2 new potential violations to the coding guideline detected. Please help check. Thanks!<br><1> config:part_config filename:/hypervisor/arch/x86/guest/vcpu.c func:resume_vcpu offset:622<br> reason:Procedure is not called or referenced in code analysed. : resume_vcpu<br><2> config:sharing_config filename:/hypervisor/arch/x86/guest/vcpu.c func:resume_vcpu offset:622<br> reason:Procedure is not called or referenced in code analysed. : resume_vcpu<br><br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by acrnsi** [comment]
Ok to verify

**Comment by HuiHuangShi** [comment]
2 new potential violations to the coding guideline detected. Please help check. Thanks!<br><1> config:part_config filename:/hypervisor/arch/x86/guest/vcpu.c func:resume_vcpu offset:622<br> reason:Procedure is not called or referenced in code analysed. : resume_vcpu<br><2> config:sharing_config filename:/hypervisor/arch/x86/guest/vcpu.c func:resume_vcpu offset:622<br> reason:Procedure is not called or referenced in code analysed. : resume_vcpu<br><br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by acrnsi** [comment]
@ying2liu hi.please check your code ,build fail,it is fail log:
run make doc in acrn-hypervisor
make -C /workspace/acrn-hypervisor/doc html BUILDDIR=/workspace/acrn-hypervisor/build/doc
make[1]: Entering directory '/workspace/acrn-hypervisor/doc'

New errors/warnings found, please fix them:
==============================================

/workspace/acrn-hypervisor/hypervisor/include/arch/x86/guest/guest_memory.h:101: warning: end of file while inside a group

/workspace/acrn-hypervisor/doc/developer-guides/hld/hv-memmgt.rst:433: WARNING: doxygenfunction: Cannot find function "copy_to_gva" in doxygen xml output for project "Project ACRN" from directory: doxygen/xml
/workspace/acrn-hypervisor/doc/developer-guides/hld/hv-virt-interrupt.rst:212: WARNING: doxygenfunction: Cannot find function "vcpu_inject_ac" in doxygen xml output for project "Project ACRN" from directory: doxygen/xml
make[1]: Leaving directory '/workspace/acrn-hypervisor/doc'
make[1]: *** [Makefile:57: html] Error 1
make: *** [Makefile:54: doc] Error 2
Build step 'Execute shell' marked build as failure

**Comment by HuiHuangShi** [comment]
2 new potential violations to the coding guideline detected. Please help check. Thanks!<br><1> config:part_config filename:/hypervisor/arch/x86/guest/vcpu.c func:resume_vcpu offset:622<br> reason:Procedure is not called or referenced in code analysed. : resume_vcpu<br><2> config:sharing_config filename:/hypervisor/arch/x86/guest/vcpu.c func:resume_vcpu offset:622<br> reason:Procedure is not called or referenced in code analysed. : resume_vcpu<br><br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Pull request merged**
