### PR TITLE
hv: Cleanup and optimise vioapic.c

### PR DESCRIPTION
**Pull request by rarindam**
Cleaned up usage of vioapic_pincount.
Modified the pin count variables to uint32_t.
Assuming pin count never be below zero, as its
derived from higher level irq value, which
is uint32.

Signed-off-by: Arindam Roy <arindam.roy@intel.com>

### CODE REVIEW

**Comment by NanlinXie** [comment]
Can one of the admins verify this patch?

**Comment by dongyaozu** [comment]
@rarindam please close the patch asap. At least make the check pass...  This has been here for quite long time.

**Comment by lijinxia** [comment]
OK to verify

**Comment by lijinxia** [comment]
SOS boot failed!

**Comment by rarindam** [comment]
Closing the PR as SOS boot failed.

**Pull request closed without merging**
