### PR TITLE
USB: Enable multiple hubs support (Flat Mode)

### PR DESCRIPTION
**Pull request by xiaoguangwu**
This patch series enable support for multiple hubs and multiple layers
of hubs under Flat Mode, which means the physical hub is not visible to
UOS and all ports of the hub are mapped to the root hub ports of UOS.
Tracked-On: #1434
Signed-off-by: Liang Yang <liang3.yang@intel.com>
Signed-off-by: Xiaoguang Wu <xiaoguang.wu@intel.com>
Acked-by: Yu Wang <yu1.wang@intel.com>

### CODE REVIEW

**Comment by dongyaozu** [comment]
8 patches?

**Comment by xiaoguangwu** [comment]
> 8 patches?

@dongyaozu yes, v1-v3 is 6 patches, and v4 add two bug fix, please check mail list, thanks!

**Comment by HuiHuangShi** [comment]
1523 <br>The PR does not touch any hypervisor source file. Skip coding guideline checks.<br>

**Comment by HuiHuangShi** [comment]
1523 <br>The PR does not touch any hypervisor source file. Skip coding guideline checks.<br>

**Pull request merged**
