### PR TITLE
hv:Move BUS_LOCK to atomic.h

### PR DESCRIPTION
**Pull request by mingqiangchi**
now this MACRO is used in atomic.h and bits.h,
move it from cpu.h to atomic.h to avoid
reverse dependency(i.e. from lower layer to upper one)

Tracked-On: #1842
Signed-off-by: Mingqiang Chi <mingqiang.chi@intel.com>

### CODE REVIEW

**Comment by JasonChenCJ** [comment]
> This is more an architecture specific code. Did u check with Jason?

@dongyaozu , yes, actually, the atomic.h is arch specific, I would like to keep this arch specific file in lib now. Do you want we to separate lib into arch and general dir?

**Comment by dongyaozu** [comment]
let generate an x86 sub-dir for lib or generate a lib subdir for arch/x86?  The later one is better

**Comment by mingqiangchi** [comment]
generate a lib subdir for arch/x86  in
include/arch/x86/lib     ?
or  inlclude/lib/arch/x86?

now need to move  these 3 files
include/lib/atomic.h
include/lib/bits.h
include/lib/spinlock.h

**Comment by HuiHuangShi** [comment]
No new violations to the coding guideline detected.<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by mingqiangchi** [comment]
have updated the patch,
Currently the lib folder as follow,
  lib:
      xxxx.c
  include/lib:
      xxxx.h

change lib folder like this,
    lib:
       xxxx.c
       x86:
          xxxx.c
       include:
          xxxx.h
          x86:
	     xxxx.h

**Comment by HuiHuangShi** [comment]
No new violations to the coding guideline detected.<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by mingqiangchi** [comment]
have updated the patch

**Comment by HuiHuangShi** [comment]
No new violations to the coding guideline detected.<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Pull request merged**
