### PR TITLE
Samples: Kernel bootchart generation using cmdline.

### PR DESCRIPTION
**Pull request by santoshkumarlaxminarayanrai**
Parameters will help to generate kernel boot chart.
It can be helpful to debug and identify which subsytem
takes longer time in kernel bootup.

Tracked-On : #1551

Signed-off-by: santoshkumar <santoshkumar.laxminarayan.rai@intel.com>

### CODE REVIEW

**Comment by NanlinXie** [comment]
Can one of the admins verify this patch?

**Comment by JasonChenCJ** [comment]
@santoshkumarlaxminarayanrai , it LGTM

**Comment by ClaudZhang1995** [comment]
OK to Verify

**Comment by dongyaozu** [comment]
please fix the conflict and merge.
Change to this file is very easy to conflict... We may need a better way to solve it.

**Comment by dongyaozu** [comment]
@santoshkumarlaxminarayanrai   fix conflicts?

**Comment by wenlingz** [comment]
@santoshkumarlaxminarayanrai please rebase your code, thanks

**Comment by santoshkumarlaxminarayanrai** [comment]
Sorry for the delay. I am working to resolve the conflict. Will update soon.

**Comment by lijinxia** [comment]
@santoshkumarlaxminarayanrai 
Please remove the commit [c521245](https://github.com/projectacrn/acrn-hypervisor/pull/1539/commits/c521245918a2103ecf6f3d3d1e2f990fc51473d2) and rebase your folk branch with upstream to fix the conflicts.

**Comment by fuzhongl** [comment]
@santoshkumarlaxminarayanrai 
Any more concern, please update the comments. If no more feedback within two weeks, this ticket will be closed by default. 
Appreciate for your understanding.

**Pull request closed without merging**
