### PR TITLE
Audio mediator device model

### PR DESCRIPTION
**Pull request by zhuyingjiang**
Add the device model of audio mediator, and enable it in Makefile. In the launch script add "-s <slot number>, virtio-audio" to add the audio virtual PCI device.

### CODE REVIEW

**Comment by NanlinXie** [comment]
Can one of the admins verify this patch?

**Comment by dongyaozu** [comment]
Can you add the review info (Deng Jie's +1) in commit message?

**Comment by zhuyingjiang** [comment]
OK, add review info from Zhao, Yakui and Deng, Jie

**Comment by lijinxia** [comment]
OK to verify

**Comment by lijinxia** [comment]
Verified+1

**Comment by gvancuts** [comment]
@zhuyingjiang , are you planning to add some documentation/reference about this new feature in the documentation? If not, we should plan it :-)

**Pull request merged**
