### PR TITLE
samples: add cma reservation into sos cmdline

### PR DESCRIPTION
**Pull request by JasonChenCJ**
it's needed for trusty memory reservation.

Signed-off-by: Jason Chen CJ <jason.cj.chen@intel.com>
Acked-by: Eddie Dong <eddie.dong@intel.com>

### CODE REVIEW

**Comment by lijinxia** [comment]
Verified+1

**Comment by gvancuts** [comment]
I'm a little confused by this one, I thought we were moving away from `cma` to exclusively use HugeTLB instead. This seems contrary to that direction, can you explain why?

**Comment by dongyaozu** [comment]
@gvancuts  Yes, we moved to hugetlb solution. But, now there is a need to allocate contiguous memory pages for trusty world.  It is 16MB in size, and we want the VHM to allocate that part, as one of the simplest solution.  Do you have any suggestion ?

**Comment by gvancuts** [comment]
Hi @dongyaozu , I don't have any better suggestion :-)

I was really more curious about it and wanted to make sure I understood the rationale behind it. Thanks for the explanation!

**Comment by dongyaozu** [comment]
@gvancuts in this case, I will merge this patch first, and revisit later on.

**Pull request merged**
