### PR TITLE
acrn-config: keep_gsi set for android only

### PR DESCRIPTION
**Pull request by liuwei987**
- acrn-config: 'keep_gsi' flag set for Android vm

    Tracked-On: #3955
    Signed-off-by: Wei Liu <weix.w.liu@intel.com>
    Acked-by: Victor Sun <victor.sun@intel.com>

### CODE REVIEW

**Comment by HuiHuangShi** [comment]
No new violations to the coding guideline detected.<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by dongyaozu** [comment]
Why we want to remove virtio BLK for RT VM? I thought we could support it at boot time, or if the non-RT thread has margin to query the BLK device.

**Comment by jsun26intel** [comment]
@dongyaozu 
Currently we use a passthru blk device for RT VM.

**Comment by binbinwu1** [comment]
@jsun26intel @liuwei987 Does the config tool support multiple storage devices? For example, one passthru, and another is virtio-blk?

**Comment by jsun26intel** [comment]
now I understand the issue. I though virtio-blk will not be supported in RT VM due to performance reason. We will modify the patch soon.

@liuwei987 ,please PR the keep_gsi and virtio-blk patch separately.

**Comment by liuwei987** [comment]
> now I understand the issue. I though virtio-blk will not be supported in RT VM due to performance reason. We will modify the patch soon.
> 
> @liuwei987 ,please PR the keep_gsi and virtio-blk patch separately.

Done!

**Comment by HuiHuangShi** [comment]
No new violations to the coding guideline detected.<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by HuiHuangShi** [comment]
No new violations to the coding guideline detected.<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Pull request merged**
