### PR TITLE
hv:fix MISRA-C violations in create_vm

### PR DESCRIPTION
**Pull request by mingqiangchi**
-- fix "more than one exit point" and "goto detected" violations
-- change prepare_vm0_memmap to void type
-- Add free_vm_id when create vm failed

Tracked-On: #861
Signed-off-by: Mingqiang Chi <mingqiang.chi@intel.com>
Acked-by: Anthony Xu <anthony.xu@intel.com>

### CODE REVIEW

**Comment by acrnsi** [comment]
Ok to verify

**Comment by HuiHuangShi** [comment]
2124<br>2 new potential violations to the coding guideline detected. Please help check. Thanks!  <br><br>1.filename:/hypervisor/arch/x86/guest/vm.c&nbsp;&nbsp;function:create_vm&nbsp;&nbsp;offset:63:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Procedure contains UR data flow anomalies. : vm<br><br>2.filename:/hypervisor/arch/x86/guest/vm.c&nbsp;&nbsp;function:create_vm&nbsp;&nbsp;offset:195:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Attempt to use uninitialised pointer. : vm<br><br>

**Comment by shiqingg** [comment]
violation 2 needs to be fixed.

**Comment by mingqiangchi** [comment]
have fixed violation 2

**Comment by HuiHuangShi** [comment]
2124<br>1 new potential violations to the coding guideline detected. Please help check. Thanks!  <br><br>1.filename:/hypervisor/arch/x86/guest/vm.c&nbsp;&nbsp;function:create_vm&nbsp;&nbsp;offset:195:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Pointer assigned to NULL may be dereferenced. : vm<br><br>

**Pull request merged**
