### PR TITLE
remove this old image

### PR DESCRIPTION
**Pull request by ailun258**
to align with the ACRN v0.1 release.  we need to remove this image and add another new image 
https://github.com/projectacrn/acrn-hypervisor/blob/master/doc/getting-started/images/gsg-bootmenu.png

Signed-off-by: ailun258 <ailin.yang@intel.com>

### CODE REVIEW

**Comment by NanlinXie** [comment]
Can one of the admins verify this patch?

**Comment by ailun258** [comment]
@dbkinder @jren1 
In order to align with the ACRN v0.1 release. I have updated Getting started guide, 
And we need to change one image for boot menu showing,  i have sent a email out and attached new one,

**Comment by gvancuts** [comment]
@ailun258 , this PR only deletes the current image but does not replace it with the new one. Can you update the PR so it adds the new one?

**Comment by ailun258** [comment]
@gvancuts  i tried, but failed, so i don't know why i cann't push a image to github, i have sent email with new image attached  to David to push,

**Comment by gvancuts** [comment]
You need to update the image in your code tree, commit the changes and push them to your branch. So something like:
```
$ git rm doc/getting-started/images/gsg-bootmenu.png
$ cp <new image> doc/getting-started/images/gsg-bootmenu.png
$ git add doc/getting-started/images/gsg-bootmenu.png
$ git commit -s
```
The `-s` is the sign-off for your commit, you need to add this when you propose changes.

It should be noted that this new image will not be part of the [v0.1 Getting Started Guide](https://projectacrn.github.io/0.1/getting-started/apl-nuc.html) unless someone changes the current tag (which is in general highly discouraged).

**Comment by ailun258** [comment]
@gvancuts  done , but didn't see my commit :-(

**Comment by ailun258** [comment]
ayang3@ayang3-MOBL MINGW64 ~/Downloads/acrn-src/acrn-hypervisor (master)
$ git add doc/getting-started/images/gsg-bootmenu.png
ayang3@ayang3-MOBL MINGW64 ~/Downloads/acrn-src/acrn-hypervisor (master)
$ git commit -s
[master 739c903] update new image to align latest kerne-pk version
 Committer: Yang <ailin.yang@intel.com>
Your name and email address were configured automatically based
on your username and hostname. Please check that they are accurate.
You can suppress this message by setting them explicitly. Run the
following command and follow the instructions in your editor to edit
your configuration file:

    git config --global --edit

After doing this, you may fix the identity used for this commit with:

    git commit --amend --reset-author

 1 file changed, 0 insertions(+), 0 deletions(-)
 rewrite doc/getting-started/images/gsg-bootmenu.png (96%)

**Comment by dbkinder** [comment]
I'm changing this to a console-looking code-block directive so it's easier to update (text)

**Pull request closed without merging**
