### PR TITLE
APL-UP2 hybrid , uefi bringup issues and changes

### PR DESCRIPTION
**Pull request by ranenikhil19**
Tracked-On:#3545
Signed-off-by: Nikhil Rane <nikhil.rane@intel.com>

### CODE REVIEW

**Comment by ranenikhil19** [comment]
@jsun26intel : please help review UEFI , hybrid mode changes for UP2

**Comment by HuiHuangShi** [comment]
No new violations to the coding guideline detected.<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by jsun26intel** [comment]
Hi Nikhil,
Usually the bios info(especially ACPI) of UEFI firmware is quite different with SBL on UP2 board, so actually we treat UP2 UEFI and UP2 SBL as different board configs. We'd better not to add MACRO in one board config to distinguish these two boards, this would make interface complex when all board configs would be auto-generated by offline tools in future.
Currently we only support UP2 SBL officially. If UP2 UEFI is also in our official support list, I prefer to add a "apl-up2_uefi" folder to store its configurations.
BR,
Victor

**Comment by wenlingz** [comment]
@ranenikhil19 could you help review this PR whether the change meet your requirement. thanks

**Pull request closed without merging**
