### PR TITLE
S3 final push again

### PR DESCRIPTION
**Pull request by fyin1**

### CODE REVIEW

**Comment by NanlinXie** [comment]
Can one of the admins verify this patch?

**Comment by dongyaozu** [comment]
check failed @fyin1

**Comment by fyin1** [comment]
This check failure should be related with CI system. I saw error message:
'nucsitmanager.NUCSITManager' with no arguments failed: No library 'SSHLibrary' found.

**Comment by lijinxia** [comment]
Verified+1

**Pull request merged**
