### PR TITLE
doc: add 'logger_setting' parameter information to acrn-dm documentation

### PR DESCRIPTION
**Pull request by gvancuts**
Add the '--logger_setting' parameter information to the 'acrn-dm' parameter
document.

Signed-off-by: Geoffroy Van Cutsem <geoffroy.vancutsem@intel.com>

### CODE REVIEW

**Comment by gvancuts** [comment]
@NanlinXie @mcao6 can you review this for technical accuracy (or assign someone with appropriate expertise)?

**Comment by NanlinXie** [comment]
@fuzhongl , could you help to review it?

**Comment by fuzhongl** [comment]
> @fuzhongl , could you help to review it?

It is fine for me; but need @mcao6  to confirm the detail.
Thanks!

**Comment by mcao6** [comment]
it is fine to me.

**Comment by NanlinXie** [comment]
@dbkinder @deb-intel , please help to review and merge it. Thanks!

**Pull request merged**
