### PR TITLE
acrn-config: add P2SB device to whitelist for apl-mrb

### PR DESCRIPTION
**Pull request by liuwei987**
- hv: add P2SB device to whitelist for apl-mrb
- acrn-config: add P2SB device to whitelist for apl-mrb

    Tracked-On: #3475
    Signed-off-by: Wei Liu <weix.w.liu@intel.com>
    Reviewed-by: Binbin Wu <binbin.wu@intel.com>
    Acked-by: Victor Sun <victor.sun@intel.com>

### CODE REVIEW

**Comment by binbinwu1** [comment]
@dongyaozu  I think the item is added in misc/acrn-config/library/board_cfg_lib.py in the first patch, so acrn-config will generate the hidden device in source code. 
@liuwei987  Could you confirm it?

**Comment by liuwei987** [comment]
> @dongyaozu I think the item is added in misc/acrn-config/library/board_cfg_lib.py in the first patch, so acrn-config will generate the hidden device in source code.
> @liuwei987 Could you confirm it?

You are right, the board_cfg_lib.py has a whitelist of P2SB for board, and config tool will generate the hidden device from the whitelist for board.

**Comment by jsun26intel** [comment]
@dongyaozu
The second patch is for HV code, the first one is for acrn-config tool.
so far we only got request from @lifeix that apl-mrb need this update, not sure status of other boards.

**Comment by HuiHuangShi** [comment]
No new violations to the coding guideline detected.<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Pull request merged**
