### PR TITLE
Hv hide ap trampoline code v1.4

### PR DESCRIPTION
**Pull request by yonghuah**

### CODE REVIEW

**Comment by HuiHuangShi** [comment]
1 new potential violations to the coding guideline detected. Please help check. Thanks!<br><1> config:common filename:/hypervisor/arch/x86/pagetable.c func:modify_or_del_pte offset:99<br> reason:Value is not of appropriate type. :  (int and unsigned long): ( mem_ops -> pgentry_present ( * pte )   == 0UL<br><br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by wenlingz** [comment]
@fyin1 please help approve this PR, thanks

**Comment by HuiHuangShi** [comment]
1 new potential violations to the coding guideline detected. Please help check. Thanks!<br><1> config:common filename:/hypervisor/arch/x86/pagetable.c func:modify_or_del_pte offset:99<br> reason:Value is not of appropriate type. :  (int and unsigned long): ( mem_ops -> pgentry_present ( * pte )   == 0UL<br><br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by HuiHuangShi** [comment]
1 new potential violations to the coding guideline detected. Please help check. Thanks!<br><1> config:common filename:/hypervisor/arch/x86/pagetable.c func:modify_or_del_pte offset:99<br> reason:Value is not of appropriate type. :  (int and unsigned long): ( mem_ops -> pgentry_present ( * pte )   == 0UL<br><br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by wenlingz** [comment]
@yonghuah please check your code which will lead MRB laag test fail, thanks

**Comment by HuiHuangShi** [comment]
1 new potential violations to the coding guideline detected. Please help check. Thanks!<br><1> config:common filename:/hypervisor/arch/x86/pagetable.c func:modify_or_del_pte offset:99<br> reason:Value is not of appropriate type. :  (int and unsigned long): ( mem_ops -> pgentry_present ( * pte )   == 0UL<br><br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Pull request merged**
