### PR TITLE
lib: introduce Hashing to speed up searching

### PR DESCRIPTION
**Pull request by lifeix**
Now searching in ACRN is done by walk each element in an array one by one. If the array
is big, the searching is slow. In order to improve this situation, Hashing was introduced
to ACRN. This serial is an example to use Hashing to speed up PTIRQ entry searching.

Tracked-On: #4550
Signed-off-by: Li Fei1 <fei1.li@intel.com>
Acked-by: Eddie Dong<eddie.dong@Intel.com>

### CODE REVIEW

**Comment by HuiHuangShi** [comment]
24 new potential violations to the coding guideline detected. Please help check. Thanks!<br><1> config:common filename:/hypervisor/include/lib/list.h func:hlist_del offset:132<br> reason:Static procedure is not explicitly called in code analysed. : hlist_del<br><2> config:common filename:/hypervisor/include/lib/list.h func:hlist_del offset:136<br> reason:Expression is not Boolean.<br><3> config:common filename:/hypervisor/include/lib/list.h func:hlist_del offset:137<br> reason:No brackets to then/else.<br><4> config:common filename:/hypervisor/include/lib/list.h func:hlist_add_head offset:141<br> reason:Static procedure is not explicitly called in code analysed. : hlist_add_head<br><5> config:common filename:/hypervisor/include/lib/list.h func:hlist_add_head offset:146<br> reason:Expression is not Boolean.<br><6> config:common filename:/hypervisor/include/lib/list.h func:hlist_add_head offset:147<br> reason:No brackets to then/else.<br><7> config:common filename:/hypervisor/include/lib/list.h func:hlist_add_head offset:149<br> reason:Pointer assignment to wider scope.<br><8> config:common filename:/hypervisor/include/lib/list.h func: offset:152<br> reason:Macro parameter not in brackets.             : ptr<br><9> config:common filename:/hypervisor/include/lib/list.h func: offset:152<br> reason:Macro parameter not in brackets.             : type<br><10> config:common filename:/hypervisor/include/lib/list.h func: offset:152<br> reason:Macro parameter not in brackets.             : member<br><11> config:common filename:/hypervisor/include/lib/list.h func: offset:154<br> reason:Macro parameter not in brackets.             : pos<br><12> config:part_config filename:/hypervisor/common/ptdev.c func: offset:19<br> reason:Variable should be declared static. : ptirq_entries<br><13> config:sharing_config filename:/hypervisor/common/ptdev.c func: offset:19<br> reason:Variable should be declared static. : ptirq_entries<br><14> config:common filename:/hypervisor/common/ptdev.c func:find_ptirq_entry offset:46<br> reason:Implicit conversion of underlying type (MR). :  (unsigned int and unsigned long): hash64<br><15> config:common filename:/hypervisor/common/ptdev.c func:find_ptirq_entry offset:46<br> reason:Narrower int conversion without cast. :  (unsigned int and unsigned long): hash64<br><16> config:common filename:/hypervisor/common/ptdev.c func:find_ptirq_entry offset:49<br> reason:No space after semi colon in for expression.<br><17> config:common filename:/hypervisor/common/ptdev.c func:find_ptirq_entry offset:49<br> reason:For loop initialisation is not simple.<br><18> config:common filename:/hypervisor/common/ptdev.c func:find_ptirq_entry offset:50<br> reason:Cast to an unrelated type. : (char* to struct ptirq_remapping_info*): ( struct ptirq_remapping_info * ) ( ( char * ) ( p ) - __builtin_offsetof ( struct ptirq_remapping_info , link )<br><19> config:common filename:/hypervisor/common/ptdev.c func:find_ptirq_entry offset:50<br> reason:Casting operation to a pointer. : (char* to struct ptirq_remapping_info*): ( struct ptirq_remapping_info * ) ( ( char * ) ( p ) - __builtin_offsetof ( struct ptirq_remapping_info , link )<br><20> config:common filename:/hypervisor/common/ptdev.c func:find_ptirq_entry offset:50<br> reason:Casting operation on a pointer. : (char* to struct ptirq_remapping_info*): ( struct ptirq_remapping_info * ) ( ( char * ) ( p ) - __builtin_offsetof ( struct ptirq_remapping_info , link )<br><21> config:sharing_config filename:/hypervisor/common/ptdev.c func:find_ptirq_entry offset:52<br> reason:Pointer not checked for null before use. : n<br><22> config:part_config filename:/hypervisor/common/ptdev.c func:find_ptirq_entry offset:52<br> reason:Pointer not checked for null before use. : n<br><23> config:common filename:/hypervisor/common/ptdev.c func:ptirq_activate_entry offset:201<br> reason:Implicit conversion of underlying type (MR). :  (unsigned int and unsigned long): hash64<br><24> config:common filename:/hypervisor/common/ptdev.c func:ptirq_activate_entry offset:201<br> reason:Narrower int conversion without cast. :  (unsigned int and unsigned long): hash64<br><br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by HuiHuangShi** [comment]
16 new potential violations to the coding guideline detected. Please help check. Thanks!<br><1> config:common filename:/hypervisor/include/lib/list.h func: offset:131<br> reason:Macro parameter not in brackets.             : member<br><2> config:common filename:/hypervisor/include/lib/list.h func:hlist_del offset:134<br> reason:Static procedure is not explicitly called in code analysed. : hlist_del<br><3> config:common filename:/hypervisor/include/lib/list.h func:hlist_add_head offset:144<br> reason:Static procedure is not explicitly called in code analysed. : hlist_add_head<br><4> config:common filename:/hypervisor/include/lib/list.h func:hlist_add_head offset:153<br> reason:Pointer assignment to wider scope.<br><5> config:common filename:/hypervisor/include/lib/list.h func: offset:156<br> reason:Macro parameter not in brackets.             : ptr<br><6> config:common filename:/hypervisor/include/lib/list.h func: offset:156<br> reason:Macro parameter not in brackets.             : type<br><7> config:common filename:/hypervisor/include/lib/list.h func: offset:158<br> reason:Macro parameter not in brackets.             : pos<br><8> config:part_config filename:/hypervisor/common/ptdev.c func: offset:19<br> reason:Variable should be declared static. : ptirq_entries<br><9> config:sharing_config filename:/hypervisor/common/ptdev.c func: offset:19<br> reason:Variable should be declared static. : ptirq_entries<br><10> config:common filename:/hypervisor/common/ptdev.c func:find_ptirq_entry offset:49<br> reason:No space after semi colon in for expression.<br><11> config:common filename:/hypervisor/common/ptdev.c func:find_ptirq_entry offset:49<br> reason:For loop initialisation is not simple.<br><12> config:common filename:/hypervisor/common/ptdev.c func:find_ptirq_entry offset:50<br> reason:Cast to an unrelated type. : (char* to struct ptirq_remapping_info*): ( struct ptirq_remapping_info * ) ( ( char * ) ( p ) - __builtin_offsetof ( struct ptirq_remapping_info , link )<br><13> config:common filename:/hypervisor/common/ptdev.c func:find_ptirq_entry offset:50<br> reason:Casting operation to a pointer. : (char* to struct ptirq_remapping_info*): ( struct ptirq_remapping_info * ) ( ( char * ) ( p ) - __builtin_offsetof ( struct ptirq_remapping_info , link )<br><14> config:common filename:/hypervisor/common/ptdev.c func:find_ptirq_entry offset:50<br> reason:Casting operation on a pointer. : (char* to struct ptirq_remapping_info*): ( struct ptirq_remapping_info * ) ( ( char * ) ( p ) - __builtin_offsetof ( struct ptirq_remapping_info , link )<br><15> config:part_config filename:/hypervisor/common/ptdev.c func:find_ptirq_entry offset:52<br> reason:Pointer not checked for null before use. : n<br><16> config:sharing_config filename:/hypervisor/common/ptdev.c func:find_ptirq_entry offset:52<br> reason:Pointer not checked for null before use. : n<br><br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by HuiHuangShi** [comment]
18 new potential violations to the coding guideline detected. Please help check. Thanks!<br><1> config:common filename:/hypervisor/include/lib/list.h func: offset:131<br> reason:Macro parameter not in brackets.             : member<br><2> config:common filename:/hypervisor/include/lib/list.h func:hlist_del offset:134<br> reason:Static procedure is not explicitly called in code analysed. : hlist_del<br><3> config:common filename:/hypervisor/include/lib/list.h func:hlist_add_head offset:144<br> reason:Static procedure is not explicitly called in code analysed. : hlist_add_head<br><4> config:common filename:/hypervisor/include/lib/list.h func:hlist_add_head offset:153<br> reason:Pointer assignment to wider scope.<br><5> config:common filename:/hypervisor/include/lib/list.h func: offset:156<br> reason:Macro parameter not in brackets.             : ptr<br><6> config:common filename:/hypervisor/include/lib/list.h func: offset:156<br> reason:Macro parameter not in brackets.             : type<br><7> config:common filename:/hypervisor/include/lib/list.h func: offset:158<br> reason:Macro parameter not in brackets.             : pos<br><8> config:part_config filename:/hypervisor/common/ptdev.c func: offset:19<br> reason:Variable should be declared static. : ptirq_entries<br><9> config:sharing_config filename:/hypervisor/common/ptdev.c func: offset:19<br> reason:Variable should be declared static. : ptirq_entries<br><10> config:common filename:/hypervisor/common/ptdev.c func:find_ptirq_entry offset:49<br> reason:Inconsistent usage of loop control variable.<br><11> config:common filename:/hypervisor/common/ptdev.c func:find_ptirq_entry offset:49<br> reason:For loop incrementation is not simple.<br><12> config:common filename:/hypervisor/common/ptdev.c func:find_ptirq_entry offset:49<br> reason:No space after semi colon in for expression.<br><13> config:common filename:/hypervisor/common/ptdev.c func:find_ptirq_entry offset:49<br> reason:For loop initialisation is not simple.<br><14> config:common filename:/hypervisor/common/ptdev.c func:find_ptirq_entry offset:50<br> reason:Cast to an unrelated type. : (char* to struct ptirq_remapping_info*): ( struct ptirq_remapping_info * ) ( ( char * ) ( p ) - __builtin_offsetof ( struct ptirq_remapping_info , link )<br><15> config:common filename:/hypervisor/common/ptdev.c func:find_ptirq_entry offset:50<br> reason:Casting operation to a pointer. : (char* to struct ptirq_remapping_info*): ( struct ptirq_remapping_info * ) ( ( char * ) ( p ) - __builtin_offsetof ( struct ptirq_remapping_info , link )<br><16> config:common filename:/hypervisor/common/ptdev.c func:find_ptirq_entry offset:50<br> reason:Casting operation on a pointer. : (char* to struct ptirq_remapping_info*): ( struct ptirq_remapping_info * ) ( ( char * ) ( p ) - __builtin_offsetof ( struct ptirq_remapping_info , link )<br><17> config:part_config filename:/hypervisor/common/ptdev.c func:find_ptirq_entry offset:52<br> reason:Pointer not checked for null before use. : n<br><18> config:sharing_config filename:/hypervisor/common/ptdev.c func:find_ptirq_entry offset:52<br> reason:Pointer not checked for null before use. : n<br><br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by yonghuah** [comment]
@lifeix 
 can fix typo in comment/hash.h " Hash factors is selected" -> "..factor.."? thanks.

**Comment by HuiHuangShi** [comment]
18 new potential violations to the coding guideline detected. Please help check. Thanks!<br><1> config:common filename:/hypervisor/include/lib/list.h func: offset:131<br> reason:Macro parameter not in brackets.             : member<br><2> config:common filename:/hypervisor/include/lib/list.h func:hlist_del offset:134<br> reason:Static procedure is not explicitly called in code analysed. : hlist_del<br><3> config:common filename:/hypervisor/include/lib/list.h func:hlist_add_head offset:144<br> reason:Static procedure is not explicitly called in code analysed. : hlist_add_head<br><4> config:common filename:/hypervisor/include/lib/list.h func:hlist_add_head offset:153<br> reason:Pointer assignment to wider scope.<br><5> config:common filename:/hypervisor/include/lib/list.h func: offset:156<br> reason:Macro parameter not in brackets.             : ptr<br><6> config:common filename:/hypervisor/include/lib/list.h func: offset:156<br> reason:Macro parameter not in brackets.             : type<br><7> config:common filename:/hypervisor/include/lib/list.h func: offset:158<br> reason:Macro parameter not in brackets.             : pos<br><8> config:part_config filename:/hypervisor/common/ptdev.c func: offset:19<br> reason:Variable should be declared static. : ptirq_entries<br><9> config:sharing_config filename:/hypervisor/common/ptdev.c func: offset:19<br> reason:Variable should be declared static. : ptirq_entries<br><10> config:common filename:/hypervisor/common/ptdev.c func:find_ptirq_entry offset:49<br> reason:Inconsistent usage of loop control variable.<br><11> config:common filename:/hypervisor/common/ptdev.c func:find_ptirq_entry offset:49<br> reason:For loop incrementation is not simple.<br><12> config:common filename:/hypervisor/common/ptdev.c func:find_ptirq_entry offset:49<br> reason:No space after semi colon in for expression.<br><13> config:common filename:/hypervisor/common/ptdev.c func:find_ptirq_entry offset:49<br> reason:For loop initialisation is not simple.<br><14> config:common filename:/hypervisor/common/ptdev.c func:find_ptirq_entry offset:50<br> reason:Cast to an unrelated type. : (char* to struct ptirq_remapping_info*): ( struct ptirq_remapping_info * ) ( ( char * ) ( p ) - __builtin_offsetof ( struct ptirq_remapping_info , link )<br><15> config:common filename:/hypervisor/common/ptdev.c func:find_ptirq_entry offset:50<br> reason:Casting operation to a pointer. : (char* to struct ptirq_remapping_info*): ( struct ptirq_remapping_info * ) ( ( char * ) ( p ) - __builtin_offsetof ( struct ptirq_remapping_info , link )<br><16> config:common filename:/hypervisor/common/ptdev.c func:find_ptirq_entry offset:50<br> reason:Casting operation on a pointer. : (char* to struct ptirq_remapping_info*): ( struct ptirq_remapping_info * ) ( ( char * ) ( p ) - __builtin_offsetof ( struct ptirq_remapping_info , link )<br><17> config:part_config filename:/hypervisor/common/ptdev.c func:find_ptirq_entry offset:52<br> reason:Pointer not checked for null before use. : n<br><18> config:sharing_config filename:/hypervisor/common/ptdev.c func:find_ptirq_entry offset:52<br> reason:Pointer not checked for null before use. : n<br><br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by HuiHuangShi** [comment]
18 new potential violations to the coding guideline detected. Please help check. Thanks!<br><1> config:common filename:/hypervisor/include/lib/list.h func: offset:131<br> reason:Macro parameter not in brackets.             : member<br><2> config:common filename:/hypervisor/include/lib/list.h func:hlist_del offset:134<br> reason:Static procedure is not explicitly called in code analysed. : hlist_del<br><3> config:common filename:/hypervisor/include/lib/list.h func:hlist_add_head offset:144<br> reason:Static procedure is not explicitly called in code analysed. : hlist_add_head<br><4> config:common filename:/hypervisor/include/lib/list.h func:hlist_add_head offset:153<br> reason:Pointer assignment to wider scope.<br><5> config:common filename:/hypervisor/include/lib/list.h func: offset:156<br> reason:Macro parameter not in brackets.             : ptr<br><6> config:common filename:/hypervisor/include/lib/list.h func: offset:156<br> reason:Macro parameter not in brackets.             : type<br><7> config:common filename:/hypervisor/include/lib/list.h func: offset:158<br> reason:Macro parameter not in brackets.             : pos<br><8> config:part_config filename:/hypervisor/common/ptdev.c func: offset:19<br> reason:Variable should be declared static. : ptirq_entries<br><9> config:sharing_config filename:/hypervisor/common/ptdev.c func: offset:19<br> reason:Variable should be declared static. : ptirq_entries<br><10> config:common filename:/hypervisor/common/ptdev.c func:find_ptirq_entry offset:49<br> reason:Inconsistent usage of loop control variable.<br><11> config:common filename:/hypervisor/common/ptdev.c func:find_ptirq_entry offset:49<br> reason:For loop incrementation is not simple.<br><12> config:common filename:/hypervisor/common/ptdev.c func:find_ptirq_entry offset:49<br> reason:No space after semi colon in for expression.<br><13> config:common filename:/hypervisor/common/ptdev.c func:find_ptirq_entry offset:49<br> reason:For loop initialisation is not simple.<br><14> config:common filename:/hypervisor/common/ptdev.c func:find_ptirq_entry offset:50<br> reason:Cast to an unrelated type. : (char* to struct ptirq_remapping_info*): ( struct ptirq_remapping_info * ) ( ( char * ) ( p ) - __builtin_offsetof ( struct ptirq_remapping_info , link )<br><15> config:common filename:/hypervisor/common/ptdev.c func:find_ptirq_entry offset:50<br> reason:Casting operation to a pointer. : (char* to struct ptirq_remapping_info*): ( struct ptirq_remapping_info * ) ( ( char * ) ( p ) - __builtin_offsetof ( struct ptirq_remapping_info , link )<br><16> config:common filename:/hypervisor/common/ptdev.c func:find_ptirq_entry offset:50<br> reason:Casting operation on a pointer. : (char* to struct ptirq_remapping_info*): ( struct ptirq_remapping_info * ) ( ( char * ) ( p ) - __builtin_offsetof ( struct ptirq_remapping_info , link )<br><17> config:part_config filename:/hypervisor/common/ptdev.c func:find_ptirq_entry offset:52<br> reason:Pointer not checked for null before use. : n<br><18> config:sharing_config filename:/hypervisor/common/ptdev.c func:find_ptirq_entry offset:52<br> reason:Pointer not checked for null before use. : n<br><br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by HuiHuangShi** [comment]
18 new potential violations to the coding guideline detected. Please help check. Thanks!<br><1> config:common filename:/hypervisor/include/lib/list.h func: offset:131<br> reason:Macro parameter not in brackets.             : member<br><2> config:common filename:/hypervisor/include/lib/list.h func:hlist_del offset:134<br> reason:Static procedure is not explicitly called in code analysed. : hlist_del<br><3> config:common filename:/hypervisor/include/lib/list.h func:hlist_add_head offset:144<br> reason:Static procedure is not explicitly called in code analysed. : hlist_add_head<br><4> config:common filename:/hypervisor/include/lib/list.h func:hlist_add_head offset:153<br> reason:Pointer assignment to wider scope.<br><5> config:common filename:/hypervisor/include/lib/list.h func: offset:156<br> reason:Macro parameter not in brackets.             : ptr<br><6> config:common filename:/hypervisor/include/lib/list.h func: offset:156<br> reason:Macro parameter not in brackets.             : type<br><7> config:common filename:/hypervisor/include/lib/list.h func: offset:158<br> reason:Macro parameter not in brackets.             : pos<br><8> config:part_config filename:/hypervisor/common/ptdev.c func: offset:19<br> reason:Variable should be declared static. : ptirq_entries<br><9> config:sharing_config filename:/hypervisor/common/ptdev.c func: offset:19<br> reason:Variable should be declared static. : ptirq_entries<br><10> config:common filename:/hypervisor/common/ptdev.c func:find_ptirq_entry offset:49<br> reason:Inconsistent usage of loop control variable.<br><11> config:common filename:/hypervisor/common/ptdev.c func:find_ptirq_entry offset:49<br> reason:For loop incrementation is not simple.<br><12> config:common filename:/hypervisor/common/ptdev.c func:find_ptirq_entry offset:49<br> reason:No space after semi colon in for expression.<br><13> config:common filename:/hypervisor/common/ptdev.c func:find_ptirq_entry offset:49<br> reason:For loop initialisation is not simple.<br><14> config:common filename:/hypervisor/common/ptdev.c func:find_ptirq_entry offset:50<br> reason:Cast to an unrelated type. : (char* to struct ptirq_remapping_info*): ( struct ptirq_remapping_info * ) ( ( char * ) ( p ) - __builtin_offsetof ( struct ptirq_remapping_info , link )<br><15> config:common filename:/hypervisor/common/ptdev.c func:find_ptirq_entry offset:50<br> reason:Casting operation to a pointer. : (char* to struct ptirq_remapping_info*): ( struct ptirq_remapping_info * ) ( ( char * ) ( p ) - __builtin_offsetof ( struct ptirq_remapping_info , link )<br><16> config:common filename:/hypervisor/common/ptdev.c func:find_ptirq_entry offset:50<br> reason:Casting operation on a pointer. : (char* to struct ptirq_remapping_info*): ( struct ptirq_remapping_info * ) ( ( char * ) ( p ) - __builtin_offsetof ( struct ptirq_remapping_info , link )<br><17> config:part_config filename:/hypervisor/common/ptdev.c func:find_ptirq_entry offset:52<br> reason:Pointer not checked for null before use. : n<br><18> config:sharing_config filename:/hypervisor/common/ptdev.c func:find_ptirq_entry offset:52<br> reason:Pointer not checked for null before use. : n<br><br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by HuiHuangShi** [comment]
22 new potential violations to the coding guideline detected. Please help check. Thanks!<br><1> config:common filename:/hypervisor/include/lib/list.h func: offset:131<br> reason:Macro parameter not in brackets.             : member<br><2> config:common filename:/hypervisor/include/lib/list.h func:hlist_del offset:134<br> reason:Static procedure is not explicitly called in code analysed. : hlist_del<br><3> config:common filename:/hypervisor/include/lib/list.h func:hlist_add_head offset:144<br> reason:Static procedure is not explicitly called in code analysed. : hlist_add_head<br><4> config:common filename:/hypervisor/include/lib/list.h func:hlist_add_head offset:153<br> reason:Pointer assignment to wider scope.<br><5> config:common filename:/hypervisor/include/lib/list.h func: offset:156<br> reason:Macro parameter not in brackets.             : ptr<br><6> config:common filename:/hypervisor/include/lib/list.h func: offset:156<br> reason:Macro parameter not in brackets.             : type<br><7> config:common filename:/hypervisor/include/lib/list.h func: offset:158<br> reason:Macro parameter not in brackets.             : pos<br><8> config:part_config filename:/hypervisor/common/ptdev.c func: offset:19<br> reason:Variable should be declared static. : ptirq_entries<br><9> config:sharing_config filename:/hypervisor/common/ptdev.c func: offset:19<br> reason:Variable should be declared static. : ptirq_entries<br><10> config:common filename:/hypervisor/common/ptdev.c func:find_ptirq_entry offset:49<br> reason:Inconsistent usage of loop control variable.<br><11> config:common filename:/hypervisor/common/ptdev.c func:find_ptirq_entry offset:49<br> reason:For loop incrementation is not simple.<br><12> config:common filename:/hypervisor/common/ptdev.c func:find_ptirq_entry offset:49<br> reason:No space after semi colon in for expression.<br><13> config:common filename:/hypervisor/common/ptdev.c func:find_ptirq_entry offset:49<br> reason:For loop initialisation is not simple.<br><14> config:common filename:/hypervisor/common/ptdev.c func:find_ptirq_entry offset:51<br> reason:Cast to an unrelated type. : (char* to struct ptirq_remapping_info*): ( struct ptirq_remapping_info * ) ( ( char * ) ( p ) - __builtin_offsetof ( struct ptirq_remapping_info , phys_link )<br><15> config:common filename:/hypervisor/common/ptdev.c func:find_ptirq_entry offset:51<br> reason:Casting operation to a pointer. : (char* to struct ptirq_remapping_info*): ( struct ptirq_remapping_info * ) ( ( char * ) ( p ) - __builtin_offsetof ( struct ptirq_remapping_info , phys_link )<br><16> config:common filename:/hypervisor/common/ptdev.c func:find_ptirq_entry offset:51<br> reason:Casting operation on a pointer. : (char* to struct ptirq_remapping_info*): ( struct ptirq_remapping_info * ) ( ( char * ) ( p ) - __builtin_offsetof ( struct ptirq_remapping_info , phys_link )<br><17> config:common filename:/hypervisor/common/ptdev.c func:find_ptirq_entry offset:53<br> reason:Cast to an unrelated type. : (char* to struct ptirq_remapping_info*): ( struct ptirq_remapping_info * ) ( ( char * ) ( p ) - __builtin_offsetof ( struct ptirq_remapping_info , virt_link )<br><18> config:common filename:/hypervisor/common/ptdev.c func:find_ptirq_entry offset:53<br> reason:Casting operation to a pointer. : (char* to struct ptirq_remapping_info*): ( struct ptirq_remapping_info * ) ( ( char * ) ( p ) - __builtin_offsetof ( struct ptirq_remapping_info , virt_link )<br><19> config:common filename:/hypervisor/common/ptdev.c func:find_ptirq_entry offset:53<br> reason:Casting operation on a pointer. : (char* to struct ptirq_remapping_info*): ( struct ptirq_remapping_info * ) ( ( char * ) ( p ) - __builtin_offsetof ( struct ptirq_remapping_info , virt_link )<br><20> config:sharing_config filename:/hypervisor/common/ptdev.c func:find_ptirq_entry offset:56<br> reason:Pointer not checked for null before use. : n<br><21> config:part_config filename:/hypervisor/common/ptdev.c func:find_ptirq_entry offset:56<br> reason:Pointer not checked for null before use. : n<br><22> config:common filename:/hypervisor/common/ptdev.c func:find_ptirq_entry offset:67<br> reason:Pointer assignment to wider scope.<br><br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Pull request merged**
