### PR TITLE
Virtio mei : platform reset fixes 

### PR DESCRIPTION
**Pull request by tomasbw**
Should fix UOS reboots and UOS panic stress testing.

Tracked-On: #1846 #1847 #1848 #1849
Signed-off-by: Alexander Usyskin <alexander.usyskin@intel.com>
Signed-off-by: Tomas Winkler <tomas.winkler@intel.com>

### CODE REVIEW

**Comment by HuiHuangShi** [comment]
1850 <br>The PR does not touch any hypervisor source file. Skip coding guideline checks.<br>

**Comment by HuiHuangShi** [comment]
1850 <br>The PR does not touch any hypervisor source file. Skip coding guideline checks.<br>

**Comment by dongyaozu** [comment]
@shuox can u review?

**Comment by shuox** [comment]
> @shuox can u review?

Sure. 
BTW, I think Yu has acked some of them in mailist.

**Comment by tomasbw** [comment]
Added Yu's Ack and rebased.

**Comment by HuiHuangShi** [comment]
1850 <br>The PR does not touch any hypervisor source file. Skip coding guideline checks.<br>

**Comment by lijinxia** [comment]
@tomasbw Please add Tracked-On info for the commits!

**Comment by HuiHuangShi** [comment]
1850 <br>The PR does not touch any hypervisor source file. Skip coding guideline checks.<br>

**Pull request merged**
