### PR TITLE
doc: more prep for upgrading doc build tools

### PR DESCRIPTION
**Pull request by dbkinder**
Preparing for upgrading to newer versions of doc building tools
including sphing, doxygen, breathe, docutils, etc.  This PR's changes
still work find with the older tool versions, but should eliminate
issues found while moving to newer tool versions (later).

Signed-off-by: David B. Kinder <david.b.kinder@intel.com>

### CODE REVIEW

**Comment by dbkinder** [comment]
@NanlinXie @wenlingz These changes won't impact the current CI build configuration.

**Comment by HuiHuangShi** [comment]
No new violations to the coding guideline detected.<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by HuiHuangShi** [comment]
No new violations to the coding guideline detected.<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by HuiHuangShi** [comment]
No new violations to the coding guideline detected.<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Pull request merged**
