### PR TITLE
Issue8257 build acrn with release version failed

### PR DESCRIPTION
**Pull request by tttech-industrial-buchsbaum**
This change fixes the issue by creating `debian/acrn-tools.install` on the fly when doing a debug build only. Thus, there is no `debian/acrn-tools.install` for the release build, which leads to a virtually empty package and avoid the build errors. The new `/usr/share/doc/acrn-tools/README.Debian` file providess a short explanation for the user.

### CODE REVIEW

**Comment by junjiemao1** [comment]
Is it a defined behavior that lacking a <package>.install file will generate an empty package rather than raise any error?

**Comment by tttech-industrial-buchsbaum** [comment]
@junjiemao1 The non-existing .install file (together with non-existing files at the respective build install location) means the package won't contain anything else the automatically doc part of the package, which also contains a README.Debian for the otherwise empty acrn-tools package. There I've put a not explaining the absence of any tools for release builds.
BTW, I'll update the PR with the conflicts resolved.

**Review by junjiemao1 — APPROVED** [review]
I see. Thanks for the clarification!

**Review by NanlinXie — APPROVED** [review]

**Comment by tttech-industrial-buchsbaum** [comment]
Just rebased my changes to latest master.

**Comment by tttech-industrial-buchsbaum** [comment]
Update to make DEBUG build work again ;-)

**Comment by NanlinXie** [comment]
@tttech-industrial-buchsbaum , please help to rebase your patch, it is conflict again:).

**Comment by tttech-industrial-buchsbaum** [comment]
Merge latest master to get up-to-date with its changes. Verified build for whl-ipc-i5-shared for release and debug build.

**Comment by szhen11** [comment]
@tttech-industrial-buchsbaum there are still unresolved conflicts between this PR with latest master commit 6d57f8254:
+ wget -q --no-cache --no-cookie https://github.com/projectacrn/acrn-hypervisor/pull/8278.patch -O hv.patch
+ git apply hv.patch
hv.patch:38: new blank line at EOF.
+
error: patch failed: debian/rules:302
error: debian/rules: patch does not apply
error: patch failed: debian/rules:388
error: debian/rules: patch does not apply
error: patch failed: debian/rules:147
error: debian/rules: patch does not apply

**Comment by tttech-industrial-buchsbaum** [comment]
Just rebased the patches.

**Pull request merged**
