### PR TITLE
hv: sched: Fix scheduler priority issue

### PR DESCRIPTION
**Pull request by zhangckid**
Fix build issue.

Reviewed-by: Junjie Mao <junjie.mao@intel.com>

### CODE REVIEW

**Review by junjiemao1 — APPROVED** [review]

**Comment by yuhuanX** [comment]
@zhangckid ，please add Tracked-on

**Comment by zhangckid** [comment]
No Tracked-on for this issue

**Comment by yuhuanX** [comment]
You can try to add "Tracked-On: NONE" to pass the TRACK-ON-TEST.

**Comment by junjiemao1** [comment]
> You can try to add "Tracked-On: NONE" to pass the TRACK-ON-TEST.

Using a fake `Tracked-On` is not a good practice. If you are fixing an issue of a previous feature, track on the issue ID of that feature.

**Comment by wenlingz** [comment]
start to run premerge test

**Pull request merged**
