### PR TITLE
Cleanup header file for arch folder

### PR DESCRIPTION
**Pull request by mingqiangchi**
cleanup header file for arch folder, only include some necessary header files,
doesn't include hypervisor.h

Tracked-On: #1842

### CODE REVIEW

**Comment by HuiHuangShi** [comment]
2578<br>48 new potential violations to the coding guideline detected. Please help check. Thanks!  <br><br>1.filename:/hypervisor/include/arch/x86/guest/trusty.h&nbsp;&nbsp;function:None&nbsp;&nbsp;offset:24:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:<#> Struct/union not completely specified.       : acrn_vm<br><br>2.filename:/hypervisor/include/arch/x86/mmu.h&nbsp;&nbsp;function:None&nbsp;&nbsp;offset:57:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:<#> Struct/union not completely specified.       : acrn_vcpu<br><br>3.filename:/hypervisor/arch/x86/static_checks.c&nbsp;&nbsp;function:None&nbsp;&nbsp;offset:22:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:User type declared but not used in code analysed. : CTA_DummyType4914<br><br>4.filename:/hypervisor/arch/x86/static_checks.c&nbsp;&nbsp;function:None&nbsp;&nbsp;offset:23:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:User type declared but not used in code analysed. : CTA_DummyType4915<br><br>5.filename:/hypervisor/arch/x86/static_checks.c&nbsp;&nbsp;function:None&nbsp;&nbsp;offset:24:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:User type declared but not used in code analysed. : CTA_DummyType4916<br><br>6.filename:/hypervisor/arch/x86/static_checks.c&nbsp;&nbsp;function:None&nbsp;&nbsp;offset:25:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:User type declared but not used in code analysed. : CTA_DummyType4917<br><br>7.filename:/hypervisor/arch/x86/static_checks.c&nbsp;&nbsp;function:None&nbsp;&nbsp;offset:26:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:User type declared but not used in code analysed. : CTA_DummyType4918<br><br>8.filename:/hypervisor/arch/x86/static_checks.c&nbsp;&nbsp;function:None&nbsp;&nbsp;offset:27:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:User type declared but not used in code analysed. : CTA_DummyType4919<br><br>9.filename:/hypervisor/arch/x86/static_checks.c&nbsp;&nbsp;function:None&nbsp;&nbsp;offset:28:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:User type declared but not used in code analysed. : CTA_DummyType4920<br><br>10.filename:/hypervisor/arch/x86/static_checks.c&nbsp;&nbsp;function:None&nbsp;&nbsp;offset:29:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:User type declared but not used in code analysed. : CTA_DummyType4921<br><br>11.filename:/hypervisor/arch/x86/static_checks.c&nbsp;&nbsp;function:None&nbsp;&nbsp;offset:30:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:User type declared but not used in code analysed. : CTA_DummyType4922<br><br>12.filename:/hypervisor/arch/x86/static_checks.c&nbsp;&nbsp;function:None&nbsp;&nbsp;offset:31:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:User type declared but not used in code analysed. : CTA_DummyType4923<br><br>13.filename:/hypervisor/arch/x86/static_checks.c&nbsp;&nbsp;function:None&nbsp;&nbsp;offset:32:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:User type declared but not used in code analysed. : CTA_DummyType4924<br><br>14.filename:/hypervisor/arch/x86/static_checks.c&nbsp;&nbsp;function:None&nbsp;&nbsp;offset:33:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:User type declared but not used in code analysed. : CTA_DummyType4925<br><br>15.filename:/hypervisor/arch/x86/static_checks.c&nbsp;&nbsp;function:None&nbsp;&nbsp;offset:34:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:User type declared but not used in code analysed. : CTA_DummyType4926<br><br>16.filename:/hypervisor/arch/x86/static_checks.c&nbsp;&nbsp;function:None&nbsp;&nbsp;offset:35:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:User type declared but not used in code analysed. : CTA_DummyType4927<br><br>17.filename:/hypervisor/arch/x86/static_checks.c&nbsp;&nbsp;function:None&nbsp;&nbsp;offset:36:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:User type declared but not used in code analysed. : CTA_DummyType4928<br><br>18.filename:/hypervisor/arch/x86/static_checks.c&nbsp;&nbsp;function:None&nbsp;&nbsp;offset:37:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:User type declared but not used in code analysed. : CTA_DummyType4929<br><br>19.filename:/hypervisor/arch/x86/static_checks.c&nbsp;&nbsp;function:None&nbsp;&nbsp;offset:39:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:User type declared but not used in code analysed. : CTA_DummyType4931<br><br>20.filename:/hypervisor/arch/x86/static_checks.c&nbsp;&nbsp;function:None&nbsp;&nbsp;offset:40:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:User type declared but not used in code analysed. : CTA_DummyType4932<br><br>21.filename:/hypervisor/arch/x86/static_checks.c&nbsp;&nbsp;function:None&nbsp;&nbsp;offset:41:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:User type declared but not used in code analysed. : CTA_DummyType4933<br><br>22.filename:/hypervisor/arch/x86/static_checks.c&nbsp;&nbsp;function:None&nbsp;&nbsp;offset:42:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:User type declared but not used in code analysed. : CTA_DummyType4934<br><br>23.filename:/hypervisor/arch/x86/static_checks.c&nbsp;&nbsp;function:None&nbsp;&nbsp;offset:43:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:User type declared but not used in code analysed. : CTA_DummyType4935<br><br>24.filename:/hypervisor/arch/x86/static_checks.c&nbsp;&nbsp;function:None&nbsp;&nbsp;offset:44:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:User type declared but not used in code analysed. : CTA_DummyType4936<br><br>25.filename:/hypervisor/arch/x86/static_checks.c&nbsp;&nbsp;function:None&nbsp;&nbsp;offset:45:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:User type declared but not used in code analysed. : CTA_DummyType4937<br><br>26.filename:/hypervisor/arch/x86/static_checks.c&nbsp;&nbsp;function:None&nbsp;&nbsp;offset:46:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:User type declared but not used in code analysed. : CTA_DummyType4938<br><br>27.filename:/hypervisor/arch/x86/static_checks.c&nbsp;&nbsp;function:None&nbsp;&nbsp;offset:47:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:User type declared but not used in code analysed. : CTA_DummyType4939<br><br>28.filename:/hypervisor/arch/x86/static_checks.c&nbsp;&nbsp;function:None&nbsp;&nbsp;offset:48:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:User type declared but not used in code analysed. : CTA_DummyType4940<br><br>29.filename:/hypervisor/arch/x86/static_checks.c&nbsp;&nbsp;function:None&nbsp;&nbsp;offset:49:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:User type declared but not used in code analysed. : CTA_DummyType4941<br><br>30.filename:/hypervisor/arch/x86/static_checks.c&nbsp;&nbsp;function:None&nbsp;&nbsp;offset:50:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:User type declared but not used in code analysed. : CTA_DummyType4942<br><br>31.filename:/hypervisor/arch/x86/static_checks.c&nbsp;&nbsp;function:None&nbsp;&nbsp;offset:51:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:User type declared but not used in code analysed. : CTA_DummyType4943<br><br><br>.... and more

**Comment by mingqiangchi** [comment]
fix "Identifier reuse" violation, others are false positive

**Comment by HuiHuangShi** [comment]
2578<br>47 new potential violations to the coding guideline detected. Please help check. Thanks!  <br><br>1.filename:/hypervisor/include/arch/x86/guest/trusty.h&nbsp;&nbsp;function:None&nbsp;&nbsp;offset:24:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:<#> Struct/union not completely specified.       : acrn_vm<br><br>2.filename:/hypervisor/include/arch/x86/mmu.h&nbsp;&nbsp;function:None&nbsp;&nbsp;offset:57:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:<#> Struct/union not completely specified.       : acrn_vcpu<br><br>3.filename:/hypervisor/arch/x86/static_checks.c&nbsp;&nbsp;function:None&nbsp;&nbsp;offset:22:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:User type declared but not used in code analysed. : CTA_DummyType4914<br><br>4.filename:/hypervisor/arch/x86/static_checks.c&nbsp;&nbsp;function:None&nbsp;&nbsp;offset:23:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:User type declared but not used in code analysed. : CTA_DummyType4915<br><br>5.filename:/hypervisor/arch/x86/static_checks.c&nbsp;&nbsp;function:None&nbsp;&nbsp;offset:24:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:User type declared but not used in code analysed. : CTA_DummyType4916<br><br>6.filename:/hypervisor/arch/x86/static_checks.c&nbsp;&nbsp;function:None&nbsp;&nbsp;offset:25:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:User type declared but not used in code analysed. : CTA_DummyType4917<br><br>7.filename:/hypervisor/arch/x86/static_checks.c&nbsp;&nbsp;function:None&nbsp;&nbsp;offset:26:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:User type declared but not used in code analysed. : CTA_DummyType4918<br><br>8.filename:/hypervisor/arch/x86/static_checks.c&nbsp;&nbsp;function:None&nbsp;&nbsp;offset:27:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:User type declared but not used in code analysed. : CTA_DummyType4919<br><br>9.filename:/hypervisor/arch/x86/static_checks.c&nbsp;&nbsp;function:None&nbsp;&nbsp;offset:28:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:User type declared but not used in code analysed. : CTA_DummyType4920<br><br>10.filename:/hypervisor/arch/x86/static_checks.c&nbsp;&nbsp;function:None&nbsp;&nbsp;offset:29:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:User type declared but not used in code analysed. : CTA_DummyType4921<br><br>11.filename:/hypervisor/arch/x86/static_checks.c&nbsp;&nbsp;function:None&nbsp;&nbsp;offset:30:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:User type declared but not used in code analysed. : CTA_DummyType4922<br><br>12.filename:/hypervisor/arch/x86/static_checks.c&nbsp;&nbsp;function:None&nbsp;&nbsp;offset:31:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:User type declared but not used in code analysed. : CTA_DummyType4923<br><br>13.filename:/hypervisor/arch/x86/static_checks.c&nbsp;&nbsp;function:None&nbsp;&nbsp;offset:32:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:User type declared but not used in code analysed. : CTA_DummyType4924<br><br>14.filename:/hypervisor/arch/x86/static_checks.c&nbsp;&nbsp;function:None&nbsp;&nbsp;offset:33:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:User type declared but not used in code analysed. : CTA_DummyType4925<br><br>15.filename:/hypervisor/arch/x86/static_checks.c&nbsp;&nbsp;function:None&nbsp;&nbsp;offset:34:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:User type declared but not used in code analysed. : CTA_DummyType4926<br><br>16.filename:/hypervisor/arch/x86/static_checks.c&nbsp;&nbsp;function:None&nbsp;&nbsp;offset:35:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:User type declared but not used in code analysed. : CTA_DummyType4927<br><br>17.filename:/hypervisor/arch/x86/static_checks.c&nbsp;&nbsp;function:None&nbsp;&nbsp;offset:36:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:User type declared but not used in code analysed. : CTA_DummyType4928<br><br>18.filename:/hypervisor/arch/x86/static_checks.c&nbsp;&nbsp;function:None&nbsp;&nbsp;offset:37:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:User type declared but not used in code analysed. : CTA_DummyType4929<br><br>19.filename:/hypervisor/arch/x86/static_checks.c&nbsp;&nbsp;function:None&nbsp;&nbsp;offset:39:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:User type declared but not used in code analysed. : CTA_DummyType4931<br><br>20.filename:/hypervisor/arch/x86/static_checks.c&nbsp;&nbsp;function:None&nbsp;&nbsp;offset:40:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:User type declared but not used in code analysed. : CTA_DummyType4932<br><br>21.filename:/hypervisor/arch/x86/static_checks.c&nbsp;&nbsp;function:None&nbsp;&nbsp;offset:41:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:User type declared but not used in code analysed. : CTA_DummyType4933<br><br>22.filename:/hypervisor/arch/x86/static_checks.c&nbsp;&nbsp;function:None&nbsp;&nbsp;offset:42:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:User type declared but not used in code analysed. : CTA_DummyType4934<br><br>23.filename:/hypervisor/arch/x86/static_checks.c&nbsp;&nbsp;function:None&nbsp;&nbsp;offset:43:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:User type declared but not used in code analysed. : CTA_DummyType4935<br><br>24.filename:/hypervisor/arch/x86/static_checks.c&nbsp;&nbsp;function:None&nbsp;&nbsp;offset:44:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:User type declared but not used in code analysed. : CTA_DummyType4936<br><br>25.filename:/hypervisor/arch/x86/static_checks.c&nbsp;&nbsp;function:None&nbsp;&nbsp;offset:45:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:User type declared but not used in code analysed. : CTA_DummyType4937<br><br>26.filename:/hypervisor/arch/x86/static_checks.c&nbsp;&nbsp;function:None&nbsp;&nbsp;offset:46:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:User type declared but not used in code analysed. : CTA_DummyType4938<br><br>27.filename:/hypervisor/arch/x86/static_checks.c&nbsp;&nbsp;function:None&nbsp;&nbsp;offset:47:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:User type declared but not used in code analysed. : CTA_DummyType4939<br><br>28.filename:/hypervisor/arch/x86/static_checks.c&nbsp;&nbsp;function:None&nbsp;&nbsp;offset:48:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:User type declared but not used in code analysed. : CTA_DummyType4940<br><br>29.filename:/hypervisor/arch/x86/static_checks.c&nbsp;&nbsp;function:None&nbsp;&nbsp;offset:49:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:User type declared but not used in code analysed. : CTA_DummyType4941<br><br>30.filename:/hypervisor/arch/x86/static_checks.c&nbsp;&nbsp;function:None&nbsp;&nbsp;offset:50:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:User type declared but not used in code analysed. : CTA_DummyType4942<br><br>31.filename:/hypervisor/arch/x86/static_checks.c&nbsp;&nbsp;function:None&nbsp;&nbsp;offset:51:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:User type declared but not used in code analysed. : CTA_DummyType4943<br><br><br>.... and more

**Comment by HuiHuangShi** [comment]
> 2578
> 47 new potential violations to the coding guideline detected. Please help check. Thanks!
> 
> 1.filename:/hypervisor/include/arch/x86/guest/trusty.h  function:None  offset:24:
>        reason:<#> Struct/union not completely specified. : acrn_vm
> 
> 2.filename:/hypervisor/include/arch/x86/mmu.h  function:None  offset:57:
>        reason:<#> Struct/union not completely specified. : acrn_vcpu
> 
> 3.filename:/hypervisor/arch/x86/static_checks.c  function:None  offset:22:
>        reason:User type declared but not used in code analysed. : CTA_DummyType4914
> 
> 4.filename:/hypervisor/arch/x86/static_checks.c  function:None  offset:23:
>        reason:User type declared but not used in code analysed. : CTA_DummyType4915
> 
> 5.filename:/hypervisor/arch/x86/static_checks.c  function:None  offset:24:
>        reason:User type declared but not used in code analysed. : CTA_DummyType4916
> 
> 6.filename:/hypervisor/arch/x86/static_checks.c  function:None  offset:25:
>        reason:User type declared but not used in code analysed. : CTA_DummyType4917
> 
> 7.filename:/hypervisor/arch/x86/static_checks.c  function:None  offset:26:
>        reason:User type declared but not used in code analysed. : CTA_DummyType4918
> 
> 8.filename:/hypervisor/arch/x86/static_checks.c  function:None  offset:27:
>        reason:User type declared but not used in code analysed. : CTA_DummyType4919
> 
> 9.filename:/hypervisor/arch/x86/static_checks.c  function:None  offset:28:
>        reason:User type declared but not used in code analysed. : CTA_DummyType4920
> 
> 10.filename:/hypervisor/arch/x86/static_checks.c  function:None  offset:29:
>        reason:User type declared but not used in code analysed. : CTA_DummyType4921
> 
> 11.filename:/hypervisor/arch/x86/static_checks.c  function:None  offset:30:
>        reason:User type declared but not used in code analysed. : CTA_DummyType4922
> 
> 12.filename:/hypervisor/arch/x86/static_checks.c  function:None  offset:31:
>        reason:User type declared but not used in code analysed. : CTA_DummyType4923
> 
> 13.filename:/hypervisor/arch/x86/static_checks.c  function:None  offset:32:
>        reason:User type declared but not used in code analysed. : CTA_DummyType4924
> 
> 14.filename:/hypervisor/arch/x86/static_checks.c  function:None  offset:33:
>        reason:User type declared but not used in code analysed. : CTA_DummyType4925
> 
> 15.filename:/hypervisor/arch/x86/static_checks.c  function:None  offset:34:
>        reason:User type declared but not used in code analysed. : CTA_DummyType4926
> 
> 16.filename:/hypervisor/arch/x86/static_checks.c  function:None  offset:35:
>        reason:User type declared but not used in code analysed. : CTA_DummyType4927
> 
> 17.filename:/hypervisor/arch/x86/static_checks.c  function:None  offset:36:
>        reason:User type declared but not used in code analysed. : CTA_DummyType4928
> 
> 18.filename:/hypervisor/arch/x86/static_checks.c  function:None  offset:37:
>        reason:User type declared but not used in code analysed. : CTA_DummyType4929
> 
> 19.filename:/hypervisor/arch/x86/static_checks.c  function:None  offset:39:
>        reason:User type declared but not used in code analysed. : CTA_DummyType4931
> 
> 20.filename:/hypervisor/arch/x86/static_checks.c  function:None  offset:40:
>        reason:User type declared but not used in code analysed. : CTA_DummyType4932
> 
> 21.filename:/hypervisor/arch/x86/static_checks.c  function:None  offset:41:
>        reason:User type declared but not used in code analysed. : CTA_DummyType4933
> 
> 22.filename:/hypervisor/arch/x86/static_checks.c  function:None  offset:42:
>        reason:User type declared but not used in code analysed. : CTA_DummyType4934
> 
> 23.filename:/hypervisor/arch/x86/static_checks.c  function:None  offset:43:
>        reason:User type declared but not used in code analysed. : CTA_DummyType4935
> 
> 24.filename:/hypervisor/arch/x86/static_checks.c  function:None  offset:44:
>        reason:User type declared but not used in code analysed. : CTA_DummyType4936
> 
> 25.filename:/hypervisor/arch/x86/static_checks.c  function:None  offset:45:
>        reason:User type declared but not used in code analysed. : CTA_DummyType4937
> 
> 26.filename:/hypervisor/arch/x86/static_checks.c  function:None  offset:46:
>        reason:User type declared but not used in code analysed. : CTA_DummyType4938
> 
> 27.filename:/hypervisor/arch/x86/static_checks.c  function:None  offset:47:
>        reason:User type declared but not used in code analysed. : CTA_DummyType4939
> 
> 28.filename:/hypervisor/arch/x86/static_checks.c  function:None  offset:48:
>        reason:User type declared but not used in code analysed. : CTA_DummyType4940
> 
> 29.filename:/hypervisor/arch/x86/static_checks.c  function:None  offset:49:
>        reason:User type declared but not used in code analysed. : CTA_DummyType4941
> 
> 30.filename:/hypervisor/arch/x86/static_checks.c  function:None  offset:50:
>        reason:User type declared but not used in code analysed. : CTA_DummyType4942
> 
> 31.filename:/hypervisor/arch/x86/static_checks.c  function:None  offset:51:
>        reason:User type declared but not used in code analysed. : CTA_DummyType4943
> 
> 
> .... and more

All of above is false positive

**Pull request merged**
