### PR TITLE
doc: add network virtualization hld

### PR DESCRIPTION
**Pull request by dbkinder**
Review, edit, and transcode network virtualization doc

Signed-off-by: David B. Kinder <david.b.kinder@intel.com>

### CODE REVIEW

**Comment by dbkinder** [comment]
P.S.  You can see how the graphviz drawings render for this (temporarly) on my internal site: http://dbkinder-desktop.jf.intel.com/acrn/developer-guides/network-virt-hld.html

**Comment by hwang37** [comment]
The page looks good to me. Thanks.

**Comment by ssqre** [comment]
I checked the internal site and had some comments below.

1. Could you please use https://acrn-project.github.io/assets/images/acrn-vnet/network-virtualization-architecture.png to instead of Figure 72

2. There are some issues of "section ACRN Virtio-Network Calling Stack". Using following 
UOS MAC Layer virtio-net Frontend Driver as a example.

i. virtqueue_kick is called by start_xmit rather than virtqueue_add. Indentation reflects the calling relationship
ii. I recommend displaying the function name in bold. This will make it clearer to distinguish from the comments in “(...)”.

start_xmit -->                   // virtual NIC driver xmit in virtio_net
    xmit_skb -->
        virtqueue_add_outbuf --> // add out buffer to shared virtqueue
            virtqueue_add -->
    virtqueue_kick -->           // notify the backend
        virtqueue_notify -->
            vp_notify -->
                iowrite16 -->    // trap here, HV will first get notified

**Comment by ssqre** [comment]
This sentence is not rendered correctly. Should be `brctl show`  to see the bridge `acrn-br0`.

**Comment by dbkinder** [comment]
comments addressed, thanks.  I also changed my mind about using graphviz for these flow diagrams, and went back to a boring (but more compact) code-block.  I had missed that it wasn't a linear flow through the call list in some of the diagrams that's now fixed using the code-block.

**Pull request merged**
