### PR TITLE
Release 2.0 fix pio bars

### PR DESCRIPTION
**Pull request by liujunming**

### CODE REVIEW

**Comment by ywan170** [comment]
These are not the latest version patches that merged to master, right?

**Comment by liujunming** [comment]
> These are not the latest version patches that merged to master, right?

Yes, just porting patches in the 2.6 branch to fix the security issue.

**Comment by wenlingz** [comment]
@liujunming  make doc fail,

make -C /home/acrn/workspace/make_doc/pme-yocto-build-make-doc-01/acrn-hypervisor/doc html BUILDDIR=/home/acrn/workspace/make_doc/pme-yocto-build-make-doc-01/acrn-hypervisor/build/doc
make[1]: Entering directory '/home/acrn/workspace/make_doc/pme-yocto-build-make-doc-01/acrn-hypervisor/doc'

New errors/warnings found, please fix them:
==============================================

/home/acrn/workspace/make_doc/pme-yocto-build-make-doc-01/acrn-hypervisor/build/doc/rst/conf.py:223: RemovedInSphinx40Warning: The app.add_stylesheet() is deprecated. Please use app.add_css_file() instead.
  app.add_stylesheet("acrn-custom.css")
/home/acrn/workspace/make_doc/pme-yocto-build-make-doc-01/acrn-hypervisor/build/doc/rst/conf.py:224: RemovedInSphinx40Warning: The app.add_javascript() is deprecated. Please use app.add_js_file() instead.
  app.add_javascript("https://www.googletagmanager.com/gtag/js?id=UA-831873-64")
/home/acrn/workspace/make_doc/pme-yocto-build-make-doc-01/acrn-hypervisor/build/doc/rst/conf.py:226: RemovedInSphinx40Warning: The app.add_javascript() is deprecated. Please use app.add_js_file() instead.
  app.add_javascript("acrn-custom.js")
/home/acrn/workspace/make_doc/pme-yocto-build-make-doc-01/acrn-hypervisor/build/doc/rst/developer-guides/hld/hld-virtio-devices.rst:496: WARNING: Duplicate C++ declaration, also defined in 'api/devicemodel_api'.
Declaration is 'vhost_dev'.
/home/acrn/workspace/make_doc/pme-yocto-build-make-doc-01/acrn-hypervisor/build/doc/rst/developer-guides/hld/hld-virtio-devices.rst:496: WARNING: Duplicate C++ declaration, also defined in 'api/devicemodel_api'.
Declaration is 'struct virtio_base * base'.
/home/acrn/workspace/make_doc/pme-yocto-build-make-doc-01/acrn-hypervisor/build/doc/rst/developer-guides/hld/hld-virtio-devices.rst:496: WARNING: Duplicate C++ declaration, also defined in 'api/devicemodel_api'.
Declaration is 'struct vhost_vq * vqs'.
/home/acrn/workspace/make_doc/pme-yocto-build-make-doc-01/acrn-hypervisor/build/doc/rst/developer-guides/hld/hld-virtio-devices.rst:496: WARNING: Duplicate C++ declaration, also defined in 'api/devicemodel_api'.
Declaration is 'int nvqs'.
/home/acrn/workspace/make_doc/pme-yocto-build-make-doc-01/acrn-hypervisor/build/doc/rst/developer-guides/hld/hld-virtio-devices.rst:496: WARNING: Duplicate C++ declaration, also defined in 'api/devicemodel_api'.
Declaration is 'int fd'.
/home/acrn/workspace/make_doc/pme-yocto-build-make-doc-01/acrn-hypervisor/build/doc/rst/developer-guides/hld/hld-virtio-devices.rst:496: WARNING: Duplicate C++ declaration, also defined in 'api/devicemodel_api'.
Declaration is 'int vq_idx'.
/home/acrn/workspace/make_doc/pme-yocto-build-make-doc-01/acrn-hypervisor/build/doc/rst/developer-guides/hld/hld-virtio-devices.rst:496: WARNING: Duplicate C++ declaration, also defined in 'api/devicemodel_api'.
Declaration is 'uint64_t vhost_features'.
/home/acrn/workspace/make_doc/pme-yocto-build-make-doc-01/acrn-hypervisor/build/doc/rst/developer-guides/hld/hld-virtio-devices.rst:496: WARNING: Duplicate C++ declaration, also defined in 'api/devicemodel_api'.
Declaration is 'uint64_t vhost_ext_features'.
/home/acrn/workspace/make_doc/pme-yocto-build-make-doc-01/acrn-hypervisor/build/doc/rst/developer-guides/hld/hld-virtio-devices.rst:496: WARNING: Duplicate C++ declaration, also defined in 'api/devicemodel_api'.
Declaration is 'uint32_t busyloop_timeout'.
/home/acrn/workspace/make_doc/pme-yocto-build-make-doc-01/acrn-hypervisor/build/doc/rst/developer-guides/hld/hld-virtio-devices.rst:496: WARNING: Duplicate C++ declaration, also defined in 'api/devicemodel_api'.
Declaration is 'bool started'.
/home/acrn/workspace/make_doc/pme-yocto-build-make-doc-01/acrn-hypervisor/build/doc/rst/developer-guides/hld/hld-virtio-devices.rst:499: WARNING: Duplicate C++ declaration, also defined in 'api/devicemodel_api'.
Declaration is 'vhost_vq'.
/home/acrn/workspace/make_doc/pme-yocto-build-make-doc-01/acrn-hypervisor/build/doc/rst/developer-guides/hld/hld-virtio-devices.rst:499: WARNING: Duplicate C++ declaration, also defined in 'api/devicemodel_api'.
Declaration is 'int kick_fd'.
/home/acrn/workspace/make_doc/pme-yocto-build-make-doc-01/acrn-hypervisor/build/doc/rst/developer-guides/hld/hld-virtio-devices.rst:499: WARNING: Duplicate C++ declaration, also defined in 'api/devicemodel_api'.
Declaration is 'int call_fd'.

**Comment by liujunming** [comment]
> @liujunming make doc fail,
> 
> make -C /home/acrn/workspace/make_doc/pme-yocto-build-make-doc-01/acrn-hypervisor/doc html BUILDDIR=/home/acrn/workspace/make_doc/pme-yocto-build-make-doc-01/acrn-hypervisor/build/doc
> make[1]: Entering directory '/home/acrn/workspace/make_doc/pme-yocto-build-make-doc-01/acrn-hypervisor/doc'
> 
> # New errors/warnings found, please fix them:
> /home/acrn/workspace/make_doc/pme-yocto-build-make-doc-01/acrn-hypervisor/build/doc/rst/conf.py:223: RemovedInSphinx40Warning: The app.add_stylesheet() is deprecated. Please use app.add_css_file() instead.
> app.add_stylesheet("acrn-custom.css")
> /home/acrn/workspace/make_doc/pme-yocto-build-make-doc-01/acrn-hypervisor/build/doc/rst/conf.py:224: RemovedInSphinx40Warning: The app.add_javascript() is deprecated. Please use app.add_js_file() instead.
> app.add_javascript("https://www.googletagmanager.com/gtag/js?id=UA-831873-64")
> /home/acrn/workspace/make_doc/pme-yocto-build-make-doc-01/acrn-hypervisor/build/doc/rst/conf.py:226: RemovedInSphinx40Warning: The app.add_javascript() is deprecated. Please use app.add_js_file() instead.
> app.add_javascript("acrn-custom.js")
> /home/acrn/workspace/make_doc/pme-yocto-build-make-doc-01/acrn-hypervisor/build/doc/rst/developer-guides/hld/hld-virtio-devices.rst:496: WARNING: Duplicate C++ declaration, also defined in 'api/devicemodel_api'.
> Declaration is 'vhost_dev'.
> /home/acrn/workspace/make_doc/pme-yocto-build-make-doc-01/acrn-hypervisor/build/doc/rst/developer-guides/hld/hld-virtio-devices.rst:496: WARNING: Duplicate C++ declaration, also defined in 'api/devicemodel_api'.
> Declaration is 'struct virtio_base * base'.
> /home/acrn/workspace/make_doc/pme-yocto-build-make-doc-01/acrn-hypervisor/build/doc/rst/developer-guides/hld/hld-virtio-devices.rst:496: WARNING: Duplicate C++ declaration, also defined in 'api/devicemodel_api'.
> Declaration is 'struct vhost_vq * vqs'.
> /home/acrn/workspace/make_doc/pme-yocto-build-make-doc-01/acrn-hypervisor/build/doc/rst/developer-guides/hld/hld-virtio-devices.rst:496: WARNING: Duplicate C++ declaration, also defined in 'api/devicemodel_api'.
> Declaration is 'int nvqs'.
> /home/acrn/workspace/make_doc/pme-yocto-build-make-doc-01/acrn-hypervisor/build/doc/rst/developer-guides/hld/hld-virtio-devices.rst:496: WARNING: Duplicate C++ declaration, also defined in 'api/devicemodel_api'.
> Declaration is 'int fd'.
> /home/acrn/workspace/make_doc/pme-yocto-build-make-doc-01/acrn-hypervisor/build/doc/rst/developer-guides/hld/hld-virtio-devices.rst:496: WARNING: Duplicate C++ declaration, also defined in 'api/devicemodel_api'.
> Declaration is 'int vq_idx'.
> /home/acrn/workspace/make_doc/pme-yocto-build-make-doc-01/acrn-hypervisor/build/doc/rst/developer-guides/hld/hld-virtio-devices.rst:496: WARNING: Duplicate C++ declaration, also defined in 'api/devicemodel_api'.
> Declaration is 'uint64_t vhost_features'.
> /home/acrn/workspace/make_doc/pme-yocto-build-make-doc-01/acrn-hypervisor/build/doc/rst/developer-guides/hld/hld-virtio-devices.rst:496: WARNING: Duplicate C++ declaration, also defined in 'api/devicemodel_api'.
> Declaration is 'uint64_t vhost_ext_features'.
> /home/acrn/workspace/make_doc/pme-yocto-build-make-doc-01/acrn-hypervisor/build/doc/rst/developer-guides/hld/hld-virtio-devices.rst:496: WARNING: Duplicate C++ declaration, also defined in 'api/devicemodel_api'.
> Declaration is 'uint32_t busyloop_timeout'.
> /home/acrn/workspace/make_doc/pme-yocto-build-make-doc-01/acrn-hypervisor/build/doc/rst/developer-guides/hld/hld-virtio-devices.rst:496: WARNING: Duplicate C++ declaration, also defined in 'api/devicemodel_api'.
> Declaration is 'bool started'.
> /home/acrn/workspace/make_doc/pme-yocto-build-make-doc-01/acrn-hypervisor/build/doc/rst/developer-guides/hld/hld-virtio-devices.rst:499: WARNING: Duplicate C++ declaration, also defined in 'api/devicemodel_api'.
> Declaration is 'vhost_vq'.
> /home/acrn/workspace/make_doc/pme-yocto-build-make-doc-01/acrn-hypervisor/build/doc/rst/developer-guides/hld/hld-virtio-devices.rst:499: WARNING: Duplicate C++ declaration, also defined in 'api/devicemodel_api'.
> Declaration is 'int kick_fd'.
> /home/acrn/workspace/make_doc/pme-yocto-build-make-doc-01/acrn-hypervisor/build/doc/rst/developer-guides/hld/hld-virtio-devices.rst:499: WARNING: Duplicate C++ declaration, also defined in 'api/devicemodel_api'.
> Declaration is 'int call_fd'.

Hi, Wenling. My patch didn't change any doc.
This PR is for 2.0 branch.

**Comment by dbkinder** [comment]
@wenlingz  @NanlinXie  The CI environment we originally used for building docs for the 2.0 release isn't what you're using now and that is the cause of the doc build failure. We don't have that environment archived (and this has happened before). You can ignore the doc build failure since we're not generating new v2.0 docs.

**Comment by wenlingz** [comment]
> @wenlingz @NanlinXie The CI environment we originally used for building docs for the 2.0 release isn't what you're using now and that is the cause of the doc build failure. We don't have that environment archived (and this has happened before). You can ignore the doc build failure since we're not generating new v2.0 docs.

OK, got it, thanks dave

**Review by yakuizhao — APPROVED** [review]
LGTM

**Review by yakuizhao — APPROVED** [review]
LGTM

**Comment by dbkinder** [comment]
> > @wenlingz @NanlinXie The CI environment we originally used for building docs for the 2.0 release isn't what you're using now and that is the cause of the doc build failure. We don't have that environment archived (and this has happened before). You can ignore the doc build failure since we're not generating new v2.0 docs.
> 
> OK, got it, thanks dave

@wenlingz Let me know if you plan on doing more releases to old branches like this.  There is a patch I did to the release_2.3 branch to handle this issue (https://github.com/projectacrn/acrn-hypervisor/commit/6f3dfb8a59) that might work as well with the release_2.0 branch.

**Comment by wenlingz** [comment]
> > > @wenlingz @NanlinXie The CI environment we originally used for building docs for the 2.0 release isn't what you're using now and that is the cause of the doc build failure. We don't have that environment archived (and this has happened before). You can ignore the doc build failure since we're not generating new v2.0 docs.
> > 
> > 
> > OK, got it, thanks dave
> 
> @wenlingz Let me know if you plan on doing more releases to old branches like this. There is a patch I did to the release_2.3 branch to handle this issue ([6f3dfb8](https://github.com/projectacrn/acrn-hypervisor/commit/6f3dfb8a59)) that might work as well with the release_2.0 branch.

@dbkinder @NanlinXie  could we remove make doc check for the released old branches, because we won't generate new docs for them. Thanks

**Comment by NanlinXie** [comment]
Agree

**Pull request merged**
