### PR TITLE
config_tools: remove GUEST_FLAG_SECURITY_VM in DM_OWNED_GUEST_FLAG_MASK

### PR DESCRIPTION
**Pull request by Kunhui-Li**
GUEST_FLAG_SECURITY_VM only for pre-launch VM, should not be
programmed by device model, so we remove it in DM_OWNED_GUEST_FLAG_MASK.

Tracked-On: #6366
Signed-off-by: Kunhui-Li <kunhuix.li@intel.com>

### CODE REVIEW

**Review by jsun26intel — COMMENTED** [review]
I think config tool might not need to define this macro because it is not configurable.
Maybe the macro should be moved to vm_config.h

**Comment by yfliuuu** [comment]
> I think config tool might not need to define this macro because it is not configurable. Maybe the macro should be moved to vm_config.h

I think user still need to be able to configure this option in xml for per-vm fixup behavior. @lifeix your comments?

**Comment by jsun26intel** [comment]
@yfliuuu this is DM_OWNED mask, why post launched VM need this flag?

**Comment by yfliuuu** [comment]
> @yfliuuu this is DM_OWNED mask, why post launched VM need this flag?

Post launched VM does not need this, but config tool still need to keep this for user to enable fixup for prelaunch VM. I'm replying to your comment of removing it completely from config tool.

**Comment by jsun26intel** [comment]
I mean it could be moved to vm_config.h or somewhere, that doesn't need tool to generate it since it has no configure dependency.

**Comment by jsun26intel** [comment]
the flag of GUEST_FLAG_SECURITY_VM should be set in scenario xml for pre-launched VM only.

**Comment by yfliuuu** [comment]
> I mean it could be moved to vm_config.h or somewhere, that doesn't need tool to generate it since it has no configure dependency.

Oh you mean move the DM_OWNED_GUEST_FLAG_MASK to vm_config.h? I thought you were referring to GUEST_FLAG_SECURITY_VM. If that's the case then I have no comments.

**Comment by Kunhui-Li** [comment]
Please hold this PR for HV change.

**Review by NanlinXie — APPROVED** [review]

**Comment by Kunhui-Li** [comment]
@wenlingz please help remove the label "hold on", the HV patches are ready now, thanks.

**Comment by wenlingz** [comment]
@dongyaozu please help approve this PR, thanks

**Comment by wenlingz** [comment]
OK to verify

**Pull request merged**
