### PR TITLE
hv: hypercall clean "Procedure has more than one exit point"

### PR DESCRIPTION
**Pull request by HuiHuangShi**
Huihuang Shi (3):
  hv: hypercall: fix simple violations of "Procedure has more than one
    exit point"
    fix it by use "if ... else ..." fmt.
  hv: hypercall: fix complicated violations of "Procedure has more than
    one exit point"
    fix it by use "if ... else ..." fmt or add status.
  hv: hypercall: fix "Procedure has more than one exit point"
    fix it by split function into two.

V1->V2:
    1.merge branches.
    2.compact multiple lines into one.
Tracked-On: #861
Signed-off-by: Huihuang Shi <huihuang.shi@intel.com>
Acked-by: Eddie Dong <eddie.dong@intel.com>

### CODE REVIEW

**Comment by Mingyuan18** [comment]
@HuiHuangShi Please add Tracked-on id in Conversation

**Comment by HuiHuangShi** [comment]
2193<br>6 new potential violations to the coding guideline detected. Please help check. Thanks!  <br><br>1.filename:/hypervisor/common/hypercall.c&nbsp;&nbsp;function:add_vm_memory_region&nbsp;&nbsp;offset:493:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Pointer param should be declared pointer to const. : vm<br><br>2.filename:/hypervisor/common/hypercall.c&nbsp;&nbsp;function:add_vm_memory_region&nbsp;&nbsp;offset:493:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Pointer param should be declared pointer to const. : target_vm<br><br>3.filename:/hypervisor/common/hypercall.c&nbsp;&nbsp;function:add_vm_memory_region&nbsp;&nbsp;offset:494:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Pointer param should be declared pointer to const. : pml4_page<br><br>4.filename:/hypervisor/common/hypercall.c&nbsp;&nbsp;function:hcall_gpa_to_hpa&nbsp;&nbsp;offset:727:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Logical conjunctions need brackets.<br><br>5.filename:/hypervisor/common/hypercall.c&nbsp;&nbsp;function:hcall_assign_ptdev&nbsp;&nbsp;offset:761:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Procedure contains UR data flow anomalies. : ret<br><br>6.filename:/hypervisor/common/hypercall.c&nbsp;&nbsp;function:hcall_assign_ptdev&nbsp;&nbsp;offset:780:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Logical conjunctions need brackets.<br><br>

**Comment by HuiHuangShi** [comment]
2193<br>6 new potential violations to the coding guideline detected. Please help check. Thanks!  <br><br>1.filename:/hypervisor/common/hypercall.c&nbsp;&nbsp;function:add_vm_memory_region&nbsp;&nbsp;offset:493:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Pointer param should be declared pointer to const. : vm<br><br>2.filename:/hypervisor/common/hypercall.c&nbsp;&nbsp;function:add_vm_memory_region&nbsp;&nbsp;offset:493:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Pointer param should be declared pointer to const. : target_vm<br><br>3.filename:/hypervisor/common/hypercall.c&nbsp;&nbsp;function:add_vm_memory_region&nbsp;&nbsp;offset:494:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Pointer param should be declared pointer to const. : pml4_page<br><br>4.filename:/hypervisor/common/hypercall.c&nbsp;&nbsp;function:hcall_gpa_to_hpa&nbsp;&nbsp;offset:727:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Logical conjunctions need brackets.<br><br>5.filename:/hypervisor/common/hypercall.c&nbsp;&nbsp;function:hcall_assign_ptdev&nbsp;&nbsp;offset:761:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Procedure contains UR data flow anomalies. : ret<br><br>6.filename:/hypervisor/common/hypercall.c&nbsp;&nbsp;function:hcall_assign_ptdev&nbsp;&nbsp;offset:780:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Logical conjunctions need brackets.<br><br>

**Comment by HuiHuangShi** [comment]
> 2193
> 6 new potential violations to the coding guideline detected. Please help check. Thanks!
> 
> 1.filename:/hypervisor/common/hypercall.c  function:add_vm_memory_region  offset:493:
>        reason:Pointer param should be declared pointer to const. : vm
> 
> 2.filename:/hypervisor/common/hypercall.c  function:add_vm_memory_region  offset:493:
>        reason:Pointer param should be declared pointer to const. : target_vm
> 
> 3.filename:/hypervisor/common/hypercall.c  function:add_vm_memory_region  offset:494:
>        reason:Pointer param should be declared pointer to const. : pml4_page
> 
> 4.filename:/hypervisor/common/hypercall.c  function:hcall_gpa_to_hpa  offset:727:
>        reason:Logical conjunctions need brackets.
> 
> 5.filename:/hypervisor/common/hypercall.c  function:hcall_assign_ptdev  offset:761:
>        reason:Procedure contains UR data flow anomalies. : ret
> 
> 6.filename:/hypervisor/common/hypercall.c  function:hcall_assign_ptdev  offset:780:
>        reason:Logical conjunctions need brackets.
1-6 are false positive

**Comment by HuiHuangShi** [comment]
2193<br>4 new potential violations to the coding guideline detected. Please help check. Thanks!  <br><br>1.filename:/hypervisor/common/hypercall.c&nbsp;&nbsp;function:add_vm_memory_region&nbsp;&nbsp;offset:493:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Pointer param should be declared pointer to const. : vm<br><br>2.filename:/hypervisor/common/hypercall.c&nbsp;&nbsp;function:add_vm_memory_region&nbsp;&nbsp;offset:493:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Pointer param should be declared pointer to const. : target_vm<br><br>3.filename:/hypervisor/common/hypercall.c&nbsp;&nbsp;function:add_vm_memory_region&nbsp;&nbsp;offset:494:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Pointer param should be declared pointer to const. : pml4_page<br><br>4.filename:/hypervisor/common/hypercall.c&nbsp;&nbsp;function:hcall_assign_ptdev&nbsp;&nbsp;offset:761:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Procedure contains UR data flow anomalies. : ret<br><br>

**Comment by HuiHuangShi** [comment]
> 2193
> 4 new potential violations to the coding guideline detected. Please help check. Thanks!
> 
> 1.filename:/hypervisor/common/hypercall.c  function:add_vm_memory_region  offset:493:
>        reason:Pointer param should be declared pointer to const. : vm
> 
> 2.filename:/hypervisor/common/hypercall.c  function:add_vm_memory_region  offset:493:
>        reason:Pointer param should be declared pointer to const. : target_vm
> 
> 3.filename:/hypervisor/common/hypercall.c  function:add_vm_memory_region  offset:494:
>        reason:Pointer param should be declared pointer to const. : pml4_page
> 
> 4.filename:/hypervisor/common/hypercall.c  function:hcall_assign_ptdev  offset:761:
>        reason:Procedure contains UR data flow anomalies. : ret

1-4 are false positive.

**Comment by acrnsi** [comment]
Ready to merge

**Comment by wenlingz** [comment]
@HuiHuangShi please add signed -off-by and ack-by info next time

**Pull request merged**
