### PR TITLE
Config tool ivshmem

### PR DESCRIPTION
**Pull request by YuanyuanZhao609**
According to the new design of DX, implement ivshmem configuration
    and generate hv related files.

### CODE REVIEW

**Comment by acrnsi** [comment]
Can one of the admins verify this patch?

**Comment by YuanyuanZhao609** [comment]
Depend on 
https://github.com/intel-innersource/virtualization.hypervisors.acrn.acrn-dev.acrn-offline-patch/pull/117

**Comment by wenlingz** [comment]
> Depend on [intel-innersource/virtualization.hypervisors.acrn.acrn-dev.acrn-offline-patch#117](https://github.com/intel-innersource/virtualization.hypervisors.acrn.acrn-dev.acrn-offline-patch/pull/117)

please add depends on in 117

**Review by NanlinXie — APPROVED** [review]

**Comment by gvancuts** [comment]
> > Depend on [intel-innersource/virtualization.hypervisors.acrn.acrn-dev.acrn-offline-patch#117](https://github.com/intel-innersource/virtualization.hypervisors.acrn.acrn-dev.acrn-offline-patch/pull/117)
> 
> please add depends on in 117

That PR is not in the public domain, is there a similar one we need for this repository?

**Comment by wenlingz** [comment]
start to run premerge test

**Comment by szhen11** [comment]
> > > Depend on [intel-innersource/virtualization.hypervisors.acrn.acrn-dev.acrn-offline-patch#117](https://github.com/intel-innersource/virtualization.hypervisors.acrn.acrn-dev.acrn-offline-patch/pull/117)
> > 
> > 
> > please add depends on in 117
> 
> That PR is not in the public domain, is there a similar one we need for this repository?

@YuanyuanZhao609 Please don't add Depend-On tag for PRs of public acrn-hypervisor repo, please add the Depend-On tag in PRs of the internal repo.

**Comment by YuanyuanZhao609** [comment]
I have add Depend-On tag on internal repo and remove the link on this page.

**Comment by wenlingz** [comment]
@YuanyuanZhao609  build fail, please refer:
+ make BOARD=adl-s-crb SCENARIO=hybrid RELEASE=n
make[1]: Entering directory '/home/acrn/workspace/acrn-hypervisor-build-native_6291/acrn-hypervisor/hypervisor'
Board XML is fetched from /home/acrn/workspace/acrn-hypervisor-build-native_6291/acrn-hypervisor/misc/config_tools/data/adl-s-crb/adl-s-crb.xml
Scenario XML is being fetched from /home/acrn/workspace/acrn-hypervisor-build-native_6291/acrn-hypervisor/misc/config_tools/data/adl-s-crb/hybrid.xml
/home/acrn/workspace/acrn-hypervisor-build-native_6291/acrn-hypervisor/build/hypervisor/configs/allocation.xml generated
/home/acrn/workspace/acrn-hypervisor-build-native_6291/acrn-hypervisor/build/hypervisor/configs/unified.xml generated
/home/acrn/workspace/acrn-hypervisor-build-native_6291/acrn-hypervisor/build/hypervisor/configs/config.mk generated
WARNING:root:Scenario .scenario.xml is invalid: 4 schema errors.
make[1]: Leaving directory '/home/acrn/workspace/acrn-hypervisor-build-native_6291/acrn-hypervisor/hypervisor'
make -C /home/acrn/workspace/acrn-hypervisor-build-native_6291/acrn-hypervisor/hypervisor BOARD=adl-s-crb SCENARIO=hybrid HV_OBJDIR=/home/acrn/workspace/acrn-hypervisor-build-native_6291/acrn-hypervisor/build/hypervisor RELEASE=n
make[1]: Entering directory '/home/acrn/workspace/acrn-hypervisor-build-native_6291/acrn-hypervisor/hypervisor'
/home/acrn/workspace/acrn-hypervisor-build-native_6291/acrn-hypervisor/build/hypervisor/include/config.h generated
Start pre-build static check ...
make -C ../misc/hv_prebuild BOARD=adl-s-crb SCENARIO=hybrid TARGET_DIR=/home/acrn/workspace/acrn-hypervisor-build-native_6291/acrn-hypervisor/build/hypervisor/configs
make[2]: Entering directory '/home/acrn/workspace/acrn-hypervisor-build-native_6291/acrn-hypervisor/misc/hv_prebuild'
make[2]: *** No rule to make target '/home/acrn/workspace/acrn-hypervisor-build-native_6291/acrn-hypervisor/build/hypervisor/configs/scenarios/hybrid/vm_configurations.c', needed by 'default'.  Stop.
make[2]: Leaving directory '/home/acrn/workspace/acrn-hypervisor-build-native_6291/acrn-hypervisor/misc/hv_prebuild'
make[1]: *** [Makefile:419: pre_build] Error 2
make[1]: Leaving directory '/home/acrn/workspace/acrn-hypervisor-build-native_6291/acrn-hypervisor/hypervisor'
make: *** [Makefile:109: hypervisor] Error 2

**Comment by wenlingz** [comment]
@YuanyuanZhao609 please use EB service to verify your code before you created PR, thanks

**Comment by dbkinder** [comment]
@NanlinXie @wenlingz This PR removed ``IVSHMEM_ENABLED`` from ``types.xsd``  and broke the doc build process. How did it get past the CI check for this?

**Pull request merged**
