### PR TITLE
hv: fix bug in some embedded assembly code in vmx

### PR DESCRIPTION
**Pull request by binbinwu1**
The patch fixes the issue when SOS can't boot using HV release version.

In current code, the assembly code for "sgdt" & "sidt" is not right.
The operand is output, not input.

Also, current code use "rdmsr" instruction to read MSR_IA32_SYSENTER_CS,
which doesn't sepcify the clobbered registers it uses.
This patch uses API msr_read to read MSR_IA32_SYSENTER_CS.

Signed-off-by: Binbin Wu <binbin.wu@intel.com>
Reviewed-by: Yin Fengwei <fengwei.yin@intel.com>
Acked-by: Eddie Dong <eddie.dong@intel.com>

### CODE REVIEW

**Comment by NanlinXie** [comment]
Can one of the admins verify this patch?

**Comment by binbinwu1** [comment]
This patch is to fix the issue that sos can't boot when using HV release version.
So please help to check the patch fixed the issue using HV release version.

**Comment by liuwei987** [comment]
latest source code with the patch, can fix the "sos not boot with release version". 
So v+1.

**Comment by lijinxia** [comment]
Verified+1

**Pull request merged**
