### PR TITLE
hv: align the MAX_IR_ENRIES to MAX_PT_IRQ_ENTRIES

### PR DESCRIPTION
**Pull request by weichenli-intel**
The CONFIG_MAX_IR_ENTRIES and CONFIG_MAX_PT_IRQ_ENTRIES are separate
configuration items, and they can be configured through configuration tool

When the number of PT irq entries are more than IR entries, then some
passthrough devices' irqs may failed to be protected by interrupt
remapping or automatically injected by post-interrupt mechanism.
And it waste memory if the CONFIG_MAX_IR_ENTRIES is larger.

This patch replace the CONFIG_MAX_IR_ENTRIES to MAX_IR_ENTRIES and
enforce it equal to CONFIG_PT_IRQ_ENTRIES. This way can enforce all PT
irqs works with IR or PI mechanism.

Tracked-On: #6745
Signed-off-by: Chenli Wei <chenli.wei@intel.com>
Acked-by: Eddie Dong <eddie.dong@intel.com>
Reviewed-by: Wang, Yu1 <yu1.wang@intel.com>

### CODE REVIEW

**Review by dongyaozu — APPROVED** [review]

**Comment by wenlingz** [comment]
OK to verify

**Comment by wenlingz** [comment]
OK to verify

**Comment by wenlingz** [comment]
try verify EHL

**Comment by dongyaozu** [comment]
I am fine with 1st patch, but not sure on the 2nd one.

**Comment by weichenli-intel** [comment]
update

**Review by dongyaozu — COMMENTED** [review]
This series is bad. We shouldn;t include that many patches

**Pull request closed without merging**
