### PR TITLE
hv: nested virtualization part 4 - master

### PR DESCRIPTION
**Pull request by ZideChen0**
After these patches are merged, it's supposed that it can enable nVMX on SOS without vEPT support.

### CODE REVIEW

**Comment by wenlingz** [comment]
@ZideChen0 please created one PR on release_2.5,thanks

**Review by dongyaozu — APPROVED** [review]

**Comment by wenlingz** [comment]
try verify EHL

**Comment by wenlingz** [comment]
OK to verify

**Comment by wenlingz** [comment]
try verify EHL

**Pull request merged**
