### PR TITLE
Warning removal from hypervisor codebase

### PR DESCRIPTION
**Pull request by kbillore**
This patch prevents direct usage of void pointer without cast.

Tracked-On: #2955
Signed-off-by: Kaushal Billore <kaushal.billore@intel.com>

### CODE REVIEW

**Comment by kbillore** [comment]
%p is not supported in snprintf so used %lx for uint64_t type.

**Comment by HuiHuangShi** [comment]
1 new potential violations to the coding guideline detected. Please help check. Thanks!<br><1> config:common filename:/hypervisor/boot/sbl/multiboot.c func:parse_other_modules offset:57<br> reason:Cast from pointer to integral type. : (void* to unsigned long): ( uint64_t ) mod_addr<br><br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by wuxyintel** [comment]
@kbillore @HuiHuangShi There is violation about type conversion for variable "mod_addr", need to make a deviation for this since design needs to format this 64-bit address as string. Suggestion fill the table using this justification. Reviewed-by: xiangyang.wu@intel.com

**Comment by kbillore** [comment]
How this patch will be merged ?

**Comment by kbillore** [comment]
dongyaozu , how this will be merged ?

**Comment by HuiHuangShi** [comment]
> dongyaozu , how this will be merged ?

@kbillore  please fill the suppression table and give strong justification.Thanks

**Comment by kbillore** [comment]
> > dongyaozu , how this will be merged ?
> 
> @kbillore please fill the suppression table and give strong justification.Thanks

Already shared with @HuiHuangShi @shiqingg  @junjiemao1

**Comment by HuiHuangShi** [comment]
> > > dongyaozu , how this will be merged ?
> > 
> > 
> > @kbillore please fill the suppression table and give strong justification.Thanks
> 
> Already shared with @HuiHuangShi @shiqingg @junjiemao1

The justification is not strong enough

**Pull request closed without merging**
