### PR TITLE
Boot modulization refine

### PR DESCRIPTION
**Pull request by JasonChenCJ**
we are not using ldt, so just init fs & gs with 0x10 which lead to
data segement descriptor in gdt.

Tracked-On: #1842
Signed-off-by: Jason Chen CJ <jason.cj.chen@intel.com>
Acked-by: Eddie Dong <eddie.dong@intel.com>

### CODE REVIEW

**Comment by HuiHuangShi** [comment]
2009<br>1 new potential violations to the coding guideline detected. Please help check. Thanks!  <br><br>1.filename:/hypervisor/arch/x86/irq.c&nbsp;&nbsp;function:fixup_idt&nbsp;&nbsp;offset:458:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Value outside range of underlying type. :  (unsigned int and unsigned long): ( entry & 0xffffffffUL<br><br>

**Comment by shiqingg** [comment]
For the violation mentioned above, one advise here.
from:
(uint32_t)((entry & 0xffffffffUL) >> 16U)
to:
(uint32_t)entry >>16U

@wuxyintel Xiangyang, I remembered that you mentioned to me the similar issue. Could you please help double-check if the above approach is working?

**Comment by wuxyintel** [comment]
Hi shiqing, for this violation, it is ok. Another solution is define "entry_hi_32" and "entry_lo_32" to reduce type conversion. Please refer to commit 5aa1ad, thanks!

**Comment by HuiHuangShi** [comment]
2009<br>No new violations to the coding guideline detected.

**Pull request merged**
