### PR TITLE
hv: pae: fix bug when calculate PDPT address

### PR DESCRIPTION
**Pull request by binbinwu1**
There are two bugs related to PDPT address calculation for PAE mode.

1. Current code doesn't ignore the "Ignored" fileds when load pdpt registers.
Mask the "Ignored" fileds according to SDM Figure 4-7 Vol3.

2. Current code only ignores 4bits instead of 5bits in low "Ignored" filed when
calculate PDPT address in PAE mode for guest memory address translation.

Another issue, PDPTE registers should be loaded for PAE paging mode when handling guest CR4.

Tracked-On: #2561
Signed-off-by: Binbin Wu <binbin.wu@intel.com>
Acked-by: Anthony Xu <anthony.xu@intel.com>
Acked-by: Eddie Dong <eddie.dong@intel.com>

### CODE REVIEW

**Comment by binbinwu1** [comment]
The PR version has a little change. Add a static inline function to get PDPT address in PAE mode.
@dongyaozu

**Comment by HuiHuangShi** [comment]
2562<br>2 new potential violations to the coding guideline detected. Please help check. Thanks!  <br><br>1.filename:/hypervisor/arch/x86/guest/virtual_cr.c&nbsp;&nbsp;function:load_pdptrs&nbsp;&nbsp;offset:37:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Casting operation to a pointer. : (void* to unsigned long*): ( uint64_t * ) gpa2hva ( vcpu -> vm , get_pae_pdpt_addr ( guest_cr3 ) )<br><br>2.filename:/hypervisor/arch/x86/guest/virtual_cr.c&nbsp;&nbsp;function:load_pdptrs&nbsp;&nbsp;offset:37:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Casting operation on a pointer. : (void* to unsigned long*): ( uint64_t * ) gpa2hva ( vcpu -> vm , get_pae_pdpt_addr ( guest_cr3 ) )<br><br>

**Comment by wenlingz** [comment]
OK to verify

**Comment by HuiHuangShi** [comment]
2562<br>2 new potential violations to the coding guideline detected. Please help check. Thanks!  <br><br>1.filename:/hypervisor/arch/x86/guest/virtual_cr.c&nbsp;&nbsp;function:load_pdptrs&nbsp;&nbsp;offset:37:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Casting operation to a pointer. : (void* to unsigned long*): ( uint64_t * ) gpa2hva ( vcpu -> vm , get_pae_pdpt_addr ( guest_cr3 ) )<br><br>2.filename:/hypervisor/arch/x86/guest/virtual_cr.c&nbsp;&nbsp;function:load_pdptrs&nbsp;&nbsp;offset:37:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Casting operation on a pointer. : (void* to unsigned long*): ( uint64_t * ) gpa2hva ( vcpu -> vm , get_pae_pdpt_addr ( guest_cr3 ) )<br><br>

**Comment by acrnsi** [comment]
Ok to vetify

**Comment by acrnsi** [comment]
OK to verify

**Comment by HuiHuangShi** [comment]
2562<br>2 new potential violations to the coding guideline detected. Please help check. Thanks!  <br><br>1.filename:/hypervisor/arch/x86/guest/virtual_cr.c&nbsp;&nbsp;function:load_pdptrs&nbsp;&nbsp;offset:37:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Casting operation to a pointer. : (void* to unsigned long*): ( uint64_t * ) gpa2hva ( vcpu -> vm , get_pae_pdpt_addr ( guest_cr3 ) )<br><br>2.filename:/hypervisor/arch/x86/guest/virtual_cr.c&nbsp;&nbsp;function:load_pdptrs&nbsp;&nbsp;offset:37:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Casting operation on a pointer. : (void* to unsigned long*): ( uint64_t * ) gpa2hva ( vcpu -> vm , get_pae_pdpt_addr ( guest_cr3 ) )<br><br>

**Comment by wenlingz** [comment]
@binbinwu1 Laag launch fail , please check the log,thanks
http://acrn-jenkins.sh.intel.com:8080/job/acrn-hypervisor-premerge-test-mrb-LaaG-image/2349/console

**Comment by acrnsi** [comment]
OK to verify

**Comment by binbinwu1** [comment]
> @binbinwu1 Laag launch fail , please check the log,thanks
> 
> [2019-02-20 20:58:01.467] _launch_uos_one_time (<device.mrb.MRB object at 0x7fc57101e5f8>, 'LaaG', 'serial', '/usr/share/acrn/samples/apl-mrb/launch_uos.sh', 300) {'ssh_laag_flag': False}
> [ ERROR ] write: sh /usr/share/acrn/samples/apl-mrb/launch_uos.sh -V 1
> and expect: login: failed with timeout: 300
> sh /usr/share/acrn/samples/apl-mrb/launch_uos.sh -V 1
> 
> cpu1 online=1
> 
> cpu2 online=1
> 
> cpu3 online=1
> 
> Launch clearlinux UOS
> 
> acrn-br0 bridge aleady exists, adding new tap device to it...
> 
> ```
>    -G: GVT args: low_gm_size, high_gm_size, fence_sz
> ```
> passed gvt-g optargs low_gm 64, high_gm 448, fence 8
> 
> SW_LOAD: get vsbl path /usr/share/acrn/bios/VSBL.bin
> 
> interrupt storm monitor params: 10000, 10, 1, 100
> 
> SW_LOAD: get bootargs root=/dev/vda2 rw rootwait maxcpus=3 nohpet console=hvc0 console=ttyS0 no_timer_check ignore_loglevel log_buf_len=16M consoleblank=0 tsc=reliable i915.avail_planes_per_pipe=0x070F00 i915.enable_guc_loading=0 i915.enable_hangcheck=0 i915.nuclear_pageflip=1 i915.enable_guc_submission=0 i915.enable_guc=0
> 
> VHM api version 1.0
> 
> open hugetlbfs file /run/hugepage/acrn/huge_lv1/D279543825D611E8864ECB7A18B34643
> 
> open hugetlbfs file /run/hugepage/acrn/huge_lv2/D279543825D611E8864ECB7A18B34643
> 
> level 0 free/need pages:0/0 page size:0x200000
> 
> level 1 free/need pages:4/6 page size:0x40000000
> 
> to reserve more free pages:
> 
> to reserve pages (+orig 4): echo 6 > /sys/kernel/mm/hugepages/hugepages-1048576kB/nr_hugepages
> 
> to reserve pages (+orig 0): echo 512 > /sys/kernel/mm/hugepages/hugepages-2048kB/nr_hugepages
> 
> now enough free pages are reserved!

checking

**Comment by binbinwu1** [comment]
> @binbinwu1 Laag launch fail , please check the log,thanks
> 
> [2019-02-20 20:58:01.467] _launch_uos_one_time (<device.mrb.MRB object at 0x7fc57101e5f8>, 'LaaG', 'serial', '/usr/share/acrn/samples/apl-mrb/launch_uos.sh', 300) {'ssh_laag_flag': False}
> [ ERROR ] write: sh /usr/share/acrn/samples/apl-mrb/launch_uos.sh -V 1
> and expect: login: failed with timeout: 300
> sh /usr/share/acrn/samples/apl-mrb/launch_uos.sh -V 1
> 
> cpu1 online=1
> 
> cpu2 online=1
> 
> cpu3 online=1
> 
> Launch clearlinux UOS
> 
> acrn-br0 bridge aleady exists, adding new tap device to it...
> 
> ```
>    -G: GVT args: low_gm_size, high_gm_size, fence_sz
> ```
> passed gvt-g optargs low_gm 64, high_gm 448, fence 8
> 
> SW_LOAD: get vsbl path /usr/share/acrn/bios/VSBL.bin
> 
> interrupt storm monitor params: 10000, 10, 1, 100
> 
> SW_LOAD: get bootargs root=/dev/vda2 rw rootwait maxcpus=3 nohpet console=hvc0 console=ttyS0 no_timer_check ignore_loglevel log_buf_len=16M consoleblank=0 tsc=reliable i915.avail_planes_per_pipe=0x070F00 i915.enable_guc_loading=0 i915.enable_hangcheck=0 i915.nuclear_pageflip=1 i915.enable_guc_submission=0 i915.enable_guc=0
> 
> VHM api version 1.0
> 
> open hugetlbfs file /run/hugepage/acrn/huge_lv1/D279543825D611E8864ECB7A18B34643
> 
> open hugetlbfs file /run/hugepage/acrn/huge_lv2/D279543825D611E8864ECB7A18B34643
> 
> level 0 free/need pages:0/0 page size:0x200000
> 
> level 1 free/need pages:4/6 page size:0x40000000
> 
> to reserve more free pages:
> 
> to reserve pages (+orig 4): echo 6 > /sys/kernel/mm/hugepages/hugepages-1048576kB/nr_hugepages
> 
> to reserve pages (+orig 0): echo 512 > /sys/kernel/mm/hugepages/hugepages-2048kB/nr_hugepages
> 
> now enough free pages are reserved!

I can't reproduce the issue on my board.

**Comment by HuiHuangShi** [comment]
2562<br>2 new potential violations to the coding guideline detected. Please help check. Thanks!  <br><br>1.filename:/hypervisor/arch/x86/guest/virtual_cr.c&nbsp;&nbsp;function:load_pdptrs&nbsp;&nbsp;offset:46:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Casting operation to a pointer. : (void* to unsigned long*): ( uint64_t * ) gpa2hva ( vcpu -> vm , get_pae_pdpt_addr ( guest_cr3 ) )<br><br>2.filename:/hypervisor/arch/x86/guest/virtual_cr.c&nbsp;&nbsp;function:load_pdptrs&nbsp;&nbsp;offset:46:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Casting operation on a pointer. : (void* to unsigned long*): ( uint64_t * ) gpa2hva ( vcpu -> vm , get_pae_pdpt_addr ( guest_cr3 ) )<br><br>

**Comment by HuiHuangShi** [comment]
> 2562
> 2 new potential violations to the coding guideline detected. Please help check. Thanks!
> 
> 1.filename:/hypervisor/arch/x86/guest/virtual_cr.c  function:load_pdptrs  offset:46:
>        reason:Casting operation to a pointer. : (void* to unsigned long*): ( uint64_t * ) gpa2hva ( vcpu -> vm , get_pae_pdpt_addr ( guest_cr3 ) )
> 
> 2.filename:/hypervisor/arch/x86/guest/virtual_cr.c  function:load_pdptrs  offset:46:
>        reason:Casting operation on a pointer. : (void* to unsigned long*): ( uint64_t * ) gpa2hva ( vcpu -> vm , get_pae_pdpt_addr ( guest_cr3 ) )

False Positive

**Pull request merged**
