### PR TITLE
config_tool: load default cpu affinity config by vm_name (release_2.7)

### PR DESCRIPTION
**Pull request by Weiyi-Feng**
1. load default cpu affinity config from scenario file by vm_name.

Tracked-On: #6724
Signed-off-by: Weiyi Feng <weiyix.feng@intel.com>
(cherry picked from commit 0f7d0bb145c2077d65e614fd2f476c05f71103b6)

### CODE REVIEW

**Comment by wenlingz** [comment]
No new violations to the coding guideline detected.
No New Name Conflict
No New Function Declaration/Definition Mismatch

**Comment by wenlingz** [comment]
EHL build fail:
Board configurations for ehl-crb-b is generated successfully.
Traceback (most recent call last):
  File "/home/meta-acrn/workspace/build/master-acrn-sos/work/x86_64-linux/acrn-hypervisor-native/6863-1637314672/git/hypervisor/../misc/config_tools/scenario_config/scenario_cfg_gen.py", line 313, in <module>
    err_dic = main(ARGS)
  File "/home/meta-acrn/workspace/build/master-acrn-sos/work/x86_64-linux/acrn-hypervisor-native/6863-1637314672/git/hypervisor/../misc/config_tools/scenario_config/scenario_cfg_gen.py", line 251, in main
    (err_dic, scenario_items) = validate_scenario_setting(params['--board'], params['--scenario'])
  File "/home/meta-acrn/workspace/build/master-acrn-sos/work/x86_64-linux/acrn-hypervisor-native/6863-1637314672/git/hypervisor/../misc/config_tools/scenario_config/scenario_cfg_gen.py", line 181, in validate_scenario_setting
    vm_info.check_item()
  File "/home/meta-acrn/workspace/build/master-acrn-sos/work/x86_64-linux/acrn-hypervisor-native/6863-1637314672/git/misc/config_tools/scenario_config/scenario_item.py", line 402, in check_item
    err_dic = scenario_cfg_lib.vm_cpu_affinity_check(self.scenario_info, self.cpus_per_vm)
  File "/home/meta-acrn/workspace/build/master-acrn-sos/work/x86_64-linux/acrn-hypervisor-native/6863-1637314672/git/misc/config_tools/scenario_config/../library/scenario_cfg_lib.py", line 315, in vm_cpu_affinity_check
    launch_vm_names = common.get_leaf_tag_map(common.LAUNCH_INFO_FILE, 'vm_name')
  File "/home/meta-acrn/workspace/build/master-acrn-sos/work/x86_64-linux/acrn-hypervisor-native/6863-1637314672/git/misc/config_tools/scenario_config/../library/common.py", line 393, in get_leaf_tag_map
    root = get_config_root(config_file)
  File "/home/meta-acrn/workspace/build/master-acrn-sos/work/x86_64-linux/acrn-hypervisor-native/6863-1637314672/git/misc/config_tools/scenario_config/../library/common.py", line 281, in get_config_root
    tree = ET.parse(config_file)
  File "/home/meta-acrn/workspace/build/master-acrn-sos/work/x86_64-linux/acrn-hypervisor-native/6863-1637314672/recipe-sysroot-native/usr/lib/python3.8/site-packages/defusedxml/common.py", line 105, in parse
    return _parse(source, parser)
  File "/home/meta-acrn/workspace/build/master-acrn-sos/work/x86_64-linux/acrn-hypervisor-native/6863-1637314672/recipe-sysroot-native/usr/lib/python3.8/xml/etree/ElementTree.py", line 1202, in parse
    tree.parse(source, parser)
  File "/home/meta-acrn/workspace/build/master-acrn-sos/work/x86_64-linux/acrn-hypervisor-native/6863-1637314672/recipe-sysroot-native/usr/lib/python3.8/xml/etree/ElementTree.py", line 584, in parse
    source = open(source, "rb")
FileNotFoundError: [Errno 2] No such file or directory: ''

**Comment by wenlingz** [comment]
@NanlinXie please help approve this PR, thanks

**Comment by wenlingz** [comment]
@NanlinXie please help approve this PR, thanks

**Review by yakuizhao — APPROVED** [review]

**Pull request merged**
