### PR TITLE
convert bridge creation to service

### PR DESCRIPTION
**Pull request by shenjoon**
update to systemd config files so that the bridge will be up
when systemd-networkd is started. Removed bridge.sh as
it will no longer be needed once this package is installed

Signed-off-by: Tan Shen Joon <shen.joon.tan@intel.com>

### CODE REVIEW

**Comment by NanlinXie** [comment]
Can one of the admins verify this patch?

**Comment by dongyaozu** [comment]
Did u get any +1 from reviewer's? @shenjoon

**Comment by shenjoon** [comment]
i saw it was reviewed by Jack from mailing list and i thought it would be easier to submit here and review instead of mailing list. Do you recommend getting it from mailing list before submitting a pull request? I'll hold on to this first then.

**Comment by jren1** [comment]
@shenjoon it is not fair for Eddie to check "+1" records in mail list before he approves the patch in github.
That is why we recommend the submitter to add "Reviewed-by:" or "Signed-off-by:" or "Acked-by:" in the patch before submitting it to github.

**Comment by dongyaozu** [comment]
If you get +1 from them, add those info to the patch ... This is typical open source way. Thanks!

**Comment by shenjoon** [comment]
@jren1 noted. Thanks.

**Comment by miguelinux** [comment]
@jren1, @shenjoon, @dongyaozu 

I sent to the ML that this change will be affect/fail the documentation build.

please update doc/getting_started/index.rst

**Comment by miguelinux** [comment]
@shenjoon 

I see 3 commits in this PR

- https://github.com/projectacrn/acrn-hypervisor/commit/8d0af55a1d3e3705646fa1a189cf85bdb0180137.patch
- https://github.com/projectacrn/acrn-hypervisor/commit/b8c38e82df72bfff7f75e359fe20f37f09cb5ad3.patch

Could you sqash this in just one commit? (https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History)

**Comment by miguelinux** [comment]
You can do "git push --force" to your fork and this PR will be updated.

**Comment by shenjoon** [comment]
i try to update the reviewed-by in the patch instead and the items committed is the same actually. Do you want me to git push --force still?

**Comment by shenjoon** [comment]
sorry, i misunderstood. will squash to 1 commit

**Comment by gvancuts** [comment]
@shenjoon , you still need to update the documentation. Are you working on that?

**Comment by shenjoon** [comment]
@gvancuts  yea ... i'll submit another PR for that by tomorrow

**Comment by lijinxia** [comment]
Verified+1

**Comment by gvancuts** [comment]
This breaks the documentation build. It would have been **really** easy to wait for the documentation to be updated in this PR.

**Comment by dbkinder** [comment]
@hwang37 @lijinxia @gvancuts @shenjoon @jren1  I see Geoffroy requested changes be made to this PR before it was merged (he has an X by his review), but this PR was still merged.  What is our policy of merging PRs with change requests still pending?

**Comment by dongyaozu** [comment]
@dbkinder   At moment, we are not very strictly binding document and code together, given that the time spent in documentation review is usually much longer than the code, such as the Crashlog whose Documentation change is still reviewing...  So, at moment, we may merge the code first, and wait for documentation update a little bit later. @shenjoon  committed in email to send another patch for documentation, so I ask Jinxia to merge to make the feature ready earlier...   Moving forward, when the pace get a little bit slow down, Yes, we will merge code+ documentation together only.  Same thing happens to the Junjie's kconfig patch too. Thanks @gvancuts .

**Comment by dbkinder** [comment]
My concern is that a merge happened even though a reviewer @gvancuts requested a change.

**Comment by dongyaozu** [comment]
I think we are talking about same thing. The change request is document, which can be in one patch series or 2 different patch series. It is a kind of balance between features and accuracy in document.

**Pull request merged**
