### PR TITLE
HV: VM Configuration changes

### PR DESCRIPTION
**Pull request by jsun26intel**
- HV: rename board name of up2 to apl-up2
- HV: remove default folder in configs
- HV: vpci_vdev_array cleanup

Tracked-On: #2291

Signed-off-by: Victor Sun <victor.sun@intel.com>
Acked-by: Eddie Dong <eddie.dong@intel.com>

### CODE REVIEW

**Comment by ClaudZhang1995** [comment]
OK to verify

**Comment by HuiHuangShi** [comment]
2615 <br>The PR does not touch any hypervisor source file. Skip coding guideline checks.<br>

**Comment by ClaudZhang1995** [comment]
OK to verify

**Comment by acrnsi** [comment]
OK to verify

**Comment by acrnsi** [comment]
OK to verify

**Comment by acrnsi** [comment]
OK to verify

**Pull request merged**
