### PR TITLE
doc: remove exec attribute for 'acrn-secure-boot-with-grub.rst'

### PR DESCRIPTION
**Pull request by yonghuah**
Remove 'x' attribute of this file and one more minor fix.

Signed-off-by: Yonghua Huang <yonghua.huang@intel.com>

### CODE REVIEW

**Comment by HuiHuangShi** [comment]
No new violations to the coding guideline detected.<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by gvancuts** [comment]
I don't see the 'x' attribute removal in this PR, is this normal?

**Comment by yonghuah** [comment]
@gvancuts , you can find " 100755 → 100644" change for file mode inside this commit, this is normal  .rst file,  does not have to be executable.

**Review by dbkinder — CHANGES_REQUESTED** [review]
there's no mention in the comments that there's a content change here (removing ``linuxefi`` from the modules list?  Was this change intended?

**Review by dbkinder — APPROVED** [review]
Other than the commit message, I'm OK with this change though.

**Pull request merged**
