### PR TITLE
doc: add ACRN lockup logo to README

### PR DESCRIPTION
**Pull request by swinslow**
As part of the trademark registration for ACRN, it is helpful to
ensure that the logo is displayed on the same page from which the
ACRN code can be downloaded.

This PR adds the logo and updates the README file to display it.

Tracked-On: #5601

Signed-off-by: Steve Winslow <steve@swinslow.net>

### CODE REVIEW

**Comment by dbkinder** [comment]
Thanks @swinslow   I made a few tweaks to your PR to make the logo smaller and appear better looking in the GitHub-rendered page. (Alas, this required doing a raw HTML insertion since the GitHub reST renderer doesn't honor the size and alignment attributes.  I also adjusted the image source to be relative (and not to master) so when we tag the release for a specific version things will stay contained.

**Review by dbkinder — APPROVED** [review]

**Comment by swinslow** [comment]
That's great, thank you @dbkinder!

**Comment by gvancuts** [comment]
Thank you both! Should we also do this? https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/customizing-your-repositorys-social-media-preview

**Comment by swinslow** [comment]
Hi @gvancuts, for the purposes I was needing I don't think it should be necessary, but the project can of course feel free to do that if they would like!

**Comment by gvancuts** [comment]
Okidoki! @dbkinder , I'm assuming there is no harm in adding it there. Do you have sufficient rights on the repo to do that?

**Pull request merged**
