### PR TITLE
doc: update industry getting started guide to v1.6.1

### PR DESCRIPTION
**Pull request by lirui34**
Add instruction to launch multiple post launched VMs.

Signed-off-by: lirui34 <ruix.li@intel.com>

### CODE REVIEW

**Comment by HuiHuangShi** [comment]
No new violations to the coding guideline detected.<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by dbkinder** [comment]
I did a review and pushed edits directly to your branch so I could merge for the 1.6.1 release.

**Comment by HuiHuangShi** [comment]
No new violations to the coding guideline detected.<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by HuiHuangShi** [comment]
No new violations to the coding guideline detected.<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Pull request merged**
