### PR TITLE
hv: x2apic support for acrn

### PR DESCRIPTION
**Pull request by sainath14**
All the platforms supported by ACRN supports x2APIC. So enabled
x2APIC for ACRN hv. Removed any code that is needed for xAPIC mode
of operation.

Tracked-On: #1455
Signed-off-by: Sainath Grandhi <sainath.grandhi@intel.com>
Reviewed-by: Eddie Dong <eddie.dong@intel.com>
Reviewed by:  Yonghua Huang <yonghua.huang@intel.com>

### CODE REVIEW

**Comment by dongyaozu** [comment]
This patch will depend on the comprehensive test result from Nanlin.... Please add the result once it is done.

**Comment by dongyaozu** [comment]
This patch will depend on the comprehensive test result from Nanlin.... Please add the result once it is done.

**Comment by anthonyzxu** [comment]
@NanlinXie 
Sainath mentioned he tested S3 for 30 times, only one failed, and the failure doesn't seem to relate to his patch.
is it possible you can do more S3 test?

**Comment by wenlingz** [comment]
@sainath14 we have tried more S3 test, and each time, it always failed , QA described "Android OS is zombie after resume from S3 at the seconed time"

**Comment by sainath14** [comment]
Re-based PR to master.

**Comment by ClaudZhang1995** [comment]
Ready to merge

**Comment by HuiHuangShi** [comment]
1538<br>No new violations to the coding guideline detected.

**Pull request merged**
