### PR TITLE
[TGL] Add pseudo-SRAM support for RTVM (phase-1)

### PR DESCRIPTION
**Pull request by qianwang-intel**
Added the support of pseudo-SRAM (pSRAM) for RTVM on TGL.

For Yocto RTOS having TCC drivers integrated in, the drivers can make use of pSRAM to greatly improve the performance of RT apps on TGL platforms.

### CODE REVIEW

**Comment by wenlingz** [comment]
@fyin1 please help approve this PR, thanks

**Review by ywan170 — COMMENTED** [review]
Looks good to me. Some FIXME need continue handle and try to PR before Friday.
@fyin1  @yaomichael , please approve

**Review by fyin1 — APPROVED** [review]

**Comment by HuiHuangShi** [comment]
No new violations to the coding guideline detected.<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by wenlingz** [comment]
@qianwang-intel  build fail, please check:
4-oe-linux/acrn-devicemodel/5331-1600236629/build/devicemodel/include -I/home/meta-acrn/workspace/build/master-acrn-sos/work/corei7-64-oe-linux/acrn-devicemodel/5331-1600236629/recipe-sysroot/usr/include/acrn -DASL_COMPILER=\"/usr/bin/iasl\" -fstack-protector-strong -DDM_DEBUG -c log/disk_logger.c -o /home/meta-acrn/workspace/build/master-acrn-sos/work/corei7-64-oe-linux/acrn-devicemodel/5331-1600236629/build/devicemodel/log/disk_logger.o -MMD -MT /home/meta-acrn/workspace/build/master-acrn-sos/work/corei7-64-oe-linux/acrn-devicemodel/5331-1600236629/build/devicemodel/log/disk_logger.o
core/sw_load_common.c:37:10: fatal error: ptct.h: No such file or directory
   37 | #include "ptct.h"
      |          ^~~~~~~~
compilation terminated.
Makefile:230: recipe for target '/home/meta-acrn/workspace/build/master-acrn-sos/work/corei7-64-oe-linux/acrn-devicemodel/5331-1600236629/build/devicemodel/core/sw_load_common.o' failed
make[1]: *** [/home/meta-acrn/workspace/build/master-acrn-sos/work/corei7-64-oe-linux/acrn-devicemodel/5331-1600236629/build/devicemodel/core/sw_load_common.o] Error 1
make[1]: *** Waiting for unfinished jobs....
hw/platform/acpi/acpi.c:74:10: fatal error: ptct.h: No such file or directory
   74 | #include "ptct.h"
      |          ^~~~~~~~
compilation terminated.
Makefile:230: recipe for target '/home/meta-acrn/workspace/build/master-acrn-sos/work/corei7-64-oe-linux/acrn-devicemodel/5331-1600236629/build/devicemodel/hw/platform/acpi/acpi.o' failed
make[1]: *** [/home/meta-acrn/workspace/build/master-acrn-sos/work/corei7-64-oe-linux/acrn-devicemodel/5331-1600236629/build/devicemodel/hw/platform/acpi/acpi.o] Error 1

**Comment by HuiHuangShi** [comment]
No new violations to the coding guideline detected.<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by HuiHuangShi** [comment]
No new violations to the coding guideline detected.<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by HuiHuangShi** [comment]
No new violations to the coding guideline detected.<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Pull request merged**
