### PR TITLE
misc: life_mngr: Fix Linux and rtvm not restarting acrn in life_mngr

### PR DESCRIPTION
**Pull request by gaofei2x**
Only Windows virtual machines can restart ACRN through life_mngr. Added Linux and rtvm to restart acrn in life_mngr.

Tracked-On: #8431

Reviewed-by: Li Fei <fei1.li@intel.com>

### CODE REVIEW

**Comment by wenlingz** [comment]
start to run premerge test

**Review by lifeix — CHANGES_REQUESTED** [review]
Have you addressed my comments in the mail list ?

**Comment by gaofei2x** [comment]
> Have you addressed my comments in the mail list ?

Sorry, I just saw it. I'll make some changes

**Review by lifeix — APPROVED** [review]

**Comment by wenlingz** [comment]
start to run premerge test

**Pull request merged**
