### PR TITLE
update the source code build comamnd

### PR DESCRIPTION
**Pull request by ailun258**
after merged the repos into a single repo,  and we created a Makefile on top dir. so we need to change the build structure to meet latest source code merged.

### CODE REVIEW

**Comment by gvancuts** [comment]
This will conflict with #257 that's under review. Can you check that one and see if more changes are needed after that?

**Comment by ailun258** [comment]
@gvancuts  yes,  i didn't check you PR#257, i prefer to use one "make" to build all

**Comment by gvancuts** [comment]
> @gvancuts yes, i didn't check you PR#257, i prefer to use one "make" to build all

@ailun258 does that mean PR #257  is good as far as you're concerned?

(it already uses a single `make` instruction to build it all - see https://github.com/projectacrn/acrn-hypervisor/pull/257/files#diff-f25f8087f145213406fc67b2c7c42cb1R393)

**Comment by ailun258** [comment]
@gvancuts  split component building is Okay(build hypervisor, build tools and build dm),  we can explain user to use top "make" to build all,  it doesn't consume too much time for building all,  of cause, we can have optional way to build each components separately, let's ask @dbkinder merge your PR first, then i can add my part.

**Comment by dbkinder** [comment]
@gvancuts can you resolve the changes in your rewrite in progress (and we can close this PR in preference to your version)

**Comment by gvancuts** [comment]
I've updated PR #257 , can you check that everything you wanted to incorporate is included in it @ailun258 ?

**Comment by dbkinder** [comment]
@gvancuts @ailun258 Can we just close this PR now that #257 is merged?

**Comment by ailun258** [comment]
yes, we can close it now

**Pull request closed without merging**
