### PR TITLE
boot SOS with all cpus then offline for UOS

### PR DESCRIPTION
**Pull request by JasonChenCJ**

### CODE REVIEW

**Comment by NanlinXie** [comment]
Can one of the admins verify this patch?

**Comment by JasonChenCJ** [comment]
It need verify with SOS kernel patch together

**Comment by lijinxia** [comment]
CI auto check can't work with two PRs together, will do manual check. 
Please ignore the CI check results.

**Comment by lijinxia** [comment]
Verified+1
But we can't merge the PR, until the sos kernel patch go into CL release firstly. @yakuizhao Could you please push and give us the GO signal?

**Comment by JasonChenCJ** [comment]
@lijinxia, could we merge this PR now?

**Comment by yakuizhao** [comment]
Now the related kernel patch is shipped in the latest clearlinux image.
I think that this PR can be resumed.

**Comment by lijinxia** [comment]
OK to verify

**Pull request merged**
