### PR TITLE
doc: remove doc dependency on kerneldoc and acrn-kernel repo

### PR DESCRIPTION
**Pull request by dbkinder**
We no longer need to generate API documentation for the upstreamed
gvt-g kernel additions so we can remove the doc generation dependency on
the acrn-kernel repo (and all use of the kerneldoc extension). We also
remove GVT-g API documentation and porting guide that are obsolete with
ACRN v2.6 and referenced this API documentation.

Signed-off-by: David B. Kinder <david.b.kinder@intel.com>

### CODE REVIEW

**Comment by dbkinder** [comment]
@NanlinXie @wenlingz Unexplained CI failure

**Comment by wenlingz** [comment]
OK to verify doc

**Review by gvancuts — APPROVED** [review]
LGTM, thanks!

**Comment by dbkinder** [comment]
@NanlinXie @shuox Are you OK with my merging this now?  It will solve the doc build issues with PR #6283 (and on master for anyone that has pulled the master branch of acrn-kernel since the kernel upgrade happened).  PR #6283 will likely have a merge conflict now requiring some of the doc changes there to be removed in preference for my PR (that removes some docs altogether).

**Review by NanlinXie — APPROVED** [review]
LGTM, thanks!

**Review by shuox — APPROVED** [review]
Thanks.

**Pull request merged**
