### PR TITLE
Vmcfg: Built-in VM Configuration Feature

### PR DESCRIPTION
**Pull request by taoyuhong**
With this feature, you can build a acrn-dm which supports --vmcfg optional
parameter, for example:

Run 'acrn-dm --vmcfg list', you may see:
1: mrb-vm1-aaag
Thus you can run ''acrn-dm --vmcfg 1' to launch UOS with build-in-parameters
for mrb-vm1-aaag

Tracked-On: #1528

### CODE REVIEW

**Comment by NanlinXie** [comment]
@taoyuhong Please also add Tracked-On information in conversation.

**Comment by taoyuhong** [comment]
Tracked-On: #1528

**Comment by wenlingz** [comment]
Tracked-On: #1528
Acked-by: Yin Fengwei <fengwei.yin@intel.com>
Signed-off-by: Tao Yuhong <yuhong.tao@intel.com>

**Comment by mwang106** [comment]
Tracked-On: #1528
Acked-by: Yin Fengwei <fengwei.yin@intel.com>
Signed-off-by: Tao Yuhong <yuhong.tao@intel.com>

**Pull request merged**
