### PR TITLE
Vpci: Pass-thru PCI device in DM-launched VM

### PR DESCRIPTION
**Pull request by lifeix**
TODO:
rename hcall_set_ptdev_intr_info/hcall_reset_ptdev_intr_info etc form _ptdev to _pcidev

v5:
1. fix four MISRA-C voilation
2. restore physical BAR in vpci_assign_pcidev if this device has been reset in ACRN-DM

v4:
patch 1-7 Acked-by: Eddie Dong <eddie.dong@intel.com>
add patch 8 to fix  a dead lock.

v3:
1. change code style to if { Mainbody } else { Error case style }
2. keep use move_pt_device, will revisit deinit_postlaunched_vm_vpci/vpci_assign_pcidev/vpci_deassign_pcidev later
3. add some function beief/retval comments and refine some comments
4. fix BAR low fix memory type lost when guest try to seize BAR size.

v2:
1. rename add_iommu_device/remove_iommu_device to attach_iommu_device/detach_iommu_device
and expose them to use them directly. remove move_pt_device.
2. refine comment for acrn_assign_pcidev and some function/variable name
3. fix a minor bug for over-write post-launched VM raw BAR data (assign offset to BAR index)
4. do the clean work in a separate patch.

v1:
This serial splits pass through PCIe device from DM to HV. As a result, we could
handle all the pass through PCIe device in HV and each guest could access its pass
through on its own, IE, post-launched VM doesn't need to access its pass through
PCIe device through SOS. In this case, we could choice not to let SOS access the
PCIe device which has been assigned to post-launched VM.

Tracked-On: #4371
Signed-off-by: Li Fei1 fei1.li@intel.com

### CODE REVIEW

**Comment by HuiHuangShi** [comment]
47 new potential violations to the coding guideline detected. Please help check. Thanks!<br><1> config:part_config filename:/hypervisor/common/hypercall.c func:hcall_assign_pcidev offset:828<br> reason:Pointer param should be declared pointer to const. : vm<br><2> config:sharing_config filename:/hypervisor/common/hypercall.c func:hcall_assign_pcidev offset:828<br> reason:Pointer param should be declared pointer to const. : vm<br><3> config:common filename:/hypervisor/common/hypercall.c func:hcall_assign_pcidev offset:830<br> reason:No newline after semi colon.<br><4> config:common filename:/hypervisor/common/hypercall.c func:hcall_assign_pcidev offset:834<br> reason:Logical conjunctions need brackets.<br><5> config:part_config filename:/hypervisor/common/hypercall.c func:hcall_deassign_pcidev offset:858<br> reason:Pointer param should be declared pointer to const. : vm<br><6> config:sharing_config filename:/hypervisor/common/hypercall.c func:hcall_deassign_pcidev offset:858<br> reason:Pointer param should be declared pointer to const. : vm<br><7> config:common filename:/hypervisor/common/hypercall.c func:hcall_deassign_pcidev offset:860<br> reason:No newline after semi colon.<br><8> config:common filename:/hypervisor/common/hypercall.c func:hcall_deassign_pcidev offset:864<br> reason:Logical conjunctions need brackets.<br><9> config:part_config filename:/hypervisor/common/hypercall.c func:hcall_set_ptdev_intr_info offset:894<br> reason:Procedure contains UR data flow anomalies. : irq.intx.virt_pin<br><10> config:part_config filename:/hypervisor/common/hypercall.c func:hcall_set_ptdev_intr_info offset:894<br> reason:Procedure contains UR data flow anomalies. : irq.intx.phys_pin<br><11> config:sharing_config filename:/hypervisor/common/hypercall.c func:hcall_set_ptdev_intr_info offset:894<br> reason:Procedure contains UR data flow anomalies. : irq.intx.phys_pin<br><12> config:sharing_config filename:/hypervisor/common/hypercall.c func:hcall_set_ptdev_intr_info offset:894<br> reason:Procedure contains UR data flow anomalies. : irq.intx.virt_pin<br><13> config:sharing_config filename:/hypervisor/common/hypercall.c func:hcall_set_ptdev_intr_info offset:894<br> reason:Procedure contains UR data flow anomalies. : irq.intx.pic_pin<br><14> config:part_config filename:/hypervisor/common/hypercall.c func:hcall_set_ptdev_intr_info offset:894<br> reason:Procedure contains UR data flow anomalies. : irq.intx.pic_pin<br><15> config:part_config filename:/hypervisor/common/hypercall.c func:hcall_reset_ptdev_intr_info offset:928<br> reason:Procedure contains UR data flow anomalies. : irq.intx.virt_pin<br><16> config:sharing_config filename:/hypervisor/common/hypercall.c func:hcall_reset_ptdev_intr_info offset:928<br> reason:Procedure contains UR data flow anomalies. : irq.intx.virt_pin<br><17> config:sharing_config filename:/hypervisor/common/hypercall.c func:hcall_reset_ptdev_intr_info offset:928<br> reason:Procedure contains UR data flow anomalies. : irq.intx.pic_pin<br><18> config:part_config filename:/hypervisor/common/hypercall.c func:hcall_reset_ptdev_intr_info offset:928<br> reason:Procedure contains UR data flow anomalies. : irq.intx.pic_pin<br><19> config:part_config filename:/hypervisor/dm/vpci/vpci.c func:pci_cfgaddr_io_write offset:75<br> reason:Procedure contains UR data flow anomalies. : vbdf.bits.b<br><20> config:sharing_config filename:/hypervisor/dm/vpci/vpci.c func:pci_cfgaddr_io_write offset:75<br> reason:Procedure contains UR data flow anomalies. : vbdf.bits.f<br><21> config:part_config filename:/hypervisor/dm/vpci/vpci.c func:pci_cfgaddr_io_write offset:75<br> reason:Procedure contains UR data flow anomalies. : vbdf.bits.f<br><22> config:sharing_config filename:/hypervisor/dm/vpci/vpci.c func:pci_cfgaddr_io_write offset:75<br> reason:Procedure contains UR data flow anomalies. : vbdf.bits.d<br><23> config:sharing_config filename:/hypervisor/dm/vpci/vpci.c func:pci_cfgaddr_io_write offset:75<br> reason:Procedure contains UR data flow anomalies. : vbdf.bits.b<br><24> config:part_config filename:/hypervisor/dm/vpci/vpci.c func:pci_cfgaddr_io_write offset:75<br> reason:Procedure contains UR data flow anomalies. : vbdf.bits.d<br><25> config:common filename:/hypervisor/dm/vpci/vpci.c func:pci_cfgaddr_io_write offset:82<br> reason:Implicit conversion of underlying type (MR). :  (unsigned short and unsigned int): vbdf.value = cfg_addr -> bits.bdf<br><26> config:common filename:/hypervisor/dm/vpci/vpci.c func:pci_cfgaddr_io_write offset:82<br> reason:Use of mixed mode arithmetic. :  (unsigned short and unsigned int): vbdf.value = cfg_addr -> bits.bdf<br><27> config:sharing_config filename:/hypervisor/dm/vpci/vpci.c func:vpci_init_vdev offset:489<br> reason:Local structure returned in function result. : vdev<br><28> config:part_config filename:/hypervisor/dm/vpci/vpci.c func:vpci_init_vdev offset:489<br> reason:Local structure returned in function result. : vdev<br><29> config:common filename:/hypervisor/dm/vpci/vpci.c func:vpci_init_vdev offset:489<br> reason:Pointer assignment to wider scope.<br><30> config:sharing_config filename:/hypervisor/dm/vpci/vpci.c func:vpci_assign_pcidev offset:577<br> reason:Pointer param should be declared pointer to const. : pcidev<br><31> config:sharing_config filename:/hypervisor/dm/vpci/vpci.c func:vpci_assign_pcidev offset:577<br> reason:Pointer param should be declared pointer to const. : vm<br><32> config:part_config filename:/hypervisor/dm/vpci/vpci.c func:vpci_assign_pcidev offset:577<br> reason:Pointer param should be declared pointer to const. : pcidev<br><33> config:part_config filename:/hypervisor/dm/vpci/vpci.c func:vpci_assign_pcidev offset:577<br> reason:Pointer param should be declared pointer to const. : vm<br><34> config:sharing_config filename:/hypervisor/dm/vpci/vpci.c func:vpci_assign_pcidev offset:588<br> reason:Pointer not checked for null before use. : sos_vm<br>.....<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by HuiHuangShi** [comment]
47 new potential violations to the coding guideline detected. Please help check. Thanks!<br><1> config:part_config filename:/hypervisor/common/hypercall.c func:hcall_assign_pcidev offset:828<br> reason:Pointer param should be declared pointer to const. : vm<br><2> config:sharing_config filename:/hypervisor/common/hypercall.c func:hcall_assign_pcidev offset:828<br> reason:Pointer param should be declared pointer to const. : vm<br><3> config:common filename:/hypervisor/common/hypercall.c func:hcall_assign_pcidev offset:830<br> reason:No newline after semi colon.<br><4> config:common filename:/hypervisor/common/hypercall.c func:hcall_assign_pcidev offset:834<br> reason:Logical conjunctions need brackets.<br><5> config:part_config filename:/hypervisor/common/hypercall.c func:hcall_deassign_pcidev offset:858<br> reason:Pointer param should be declared pointer to const. : vm<br><6> config:sharing_config filename:/hypervisor/common/hypercall.c func:hcall_deassign_pcidev offset:858<br> reason:Pointer param should be declared pointer to const. : vm<br><7> config:common filename:/hypervisor/common/hypercall.c func:hcall_deassign_pcidev offset:860<br> reason:No newline after semi colon.<br><8> config:common filename:/hypervisor/common/hypercall.c func:hcall_deassign_pcidev offset:864<br> reason:Logical conjunctions need brackets.<br><9> config:part_config filename:/hypervisor/common/hypercall.c func:hcall_set_ptdev_intr_info offset:894<br> reason:Procedure contains UR data flow anomalies. : irq.intx.virt_pin<br><10> config:part_config filename:/hypervisor/common/hypercall.c func:hcall_set_ptdev_intr_info offset:894<br> reason:Procedure contains UR data flow anomalies. : irq.intx.phys_pin<br><11> config:sharing_config filename:/hypervisor/common/hypercall.c func:hcall_set_ptdev_intr_info offset:894<br> reason:Procedure contains UR data flow anomalies. : irq.intx.phys_pin<br><12> config:sharing_config filename:/hypervisor/common/hypercall.c func:hcall_set_ptdev_intr_info offset:894<br> reason:Procedure contains UR data flow anomalies. : irq.intx.virt_pin<br><13> config:sharing_config filename:/hypervisor/common/hypercall.c func:hcall_set_ptdev_intr_info offset:894<br> reason:Procedure contains UR data flow anomalies. : irq.intx.pic_pin<br><14> config:part_config filename:/hypervisor/common/hypercall.c func:hcall_set_ptdev_intr_info offset:894<br> reason:Procedure contains UR data flow anomalies. : irq.intx.pic_pin<br><15> config:part_config filename:/hypervisor/common/hypercall.c func:hcall_reset_ptdev_intr_info offset:928<br> reason:Procedure contains UR data flow anomalies. : irq.intx.virt_pin<br><16> config:sharing_config filename:/hypervisor/common/hypercall.c func:hcall_reset_ptdev_intr_info offset:928<br> reason:Procedure contains UR data flow anomalies. : irq.intx.virt_pin<br><17> config:sharing_config filename:/hypervisor/common/hypercall.c func:hcall_reset_ptdev_intr_info offset:928<br> reason:Procedure contains UR data flow anomalies. : irq.intx.pic_pin<br><18> config:part_config filename:/hypervisor/common/hypercall.c func:hcall_reset_ptdev_intr_info offset:928<br> reason:Procedure contains UR data flow anomalies. : irq.intx.pic_pin<br><19> config:part_config filename:/hypervisor/dm/vpci/vpci.c func:pci_cfgaddr_io_write offset:75<br> reason:Procedure contains UR data flow anomalies. : vbdf.bits.b<br><20> config:sharing_config filename:/hypervisor/dm/vpci/vpci.c func:pci_cfgaddr_io_write offset:75<br> reason:Procedure contains UR data flow anomalies. : vbdf.bits.f<br><21> config:part_config filename:/hypervisor/dm/vpci/vpci.c func:pci_cfgaddr_io_write offset:75<br> reason:Procedure contains UR data flow anomalies. : vbdf.bits.f<br><22> config:sharing_config filename:/hypervisor/dm/vpci/vpci.c func:pci_cfgaddr_io_write offset:75<br> reason:Procedure contains UR data flow anomalies. : vbdf.bits.d<br><23> config:sharing_config filename:/hypervisor/dm/vpci/vpci.c func:pci_cfgaddr_io_write offset:75<br> reason:Procedure contains UR data flow anomalies. : vbdf.bits.b<br><24> config:part_config filename:/hypervisor/dm/vpci/vpci.c func:pci_cfgaddr_io_write offset:75<br> reason:Procedure contains UR data flow anomalies. : vbdf.bits.d<br><25> config:common filename:/hypervisor/dm/vpci/vpci.c func:pci_cfgaddr_io_write offset:82<br> reason:Implicit conversion of underlying type (MR). :  (unsigned short and unsigned int): vbdf.value = cfg_addr -> bits.bdf<br><26> config:common filename:/hypervisor/dm/vpci/vpci.c func:pci_cfgaddr_io_write offset:82<br> reason:Use of mixed mode arithmetic. :  (unsigned short and unsigned int): vbdf.value = cfg_addr -> bits.bdf<br><27> config:sharing_config filename:/hypervisor/dm/vpci/vpci.c func:vpci_init_vdev offset:489<br> reason:Local structure returned in function result. : vdev<br><28> config:part_config filename:/hypervisor/dm/vpci/vpci.c func:vpci_init_vdev offset:489<br> reason:Local structure returned in function result. : vdev<br><29> config:common filename:/hypervisor/dm/vpci/vpci.c func:vpci_init_vdev offset:489<br> reason:Pointer assignment to wider scope.<br><30> config:sharing_config filename:/hypervisor/dm/vpci/vpci.c func:vpci_assign_pcidev offset:577<br> reason:Pointer param should be declared pointer to const. : pcidev<br><31> config:sharing_config filename:/hypervisor/dm/vpci/vpci.c func:vpci_assign_pcidev offset:577<br> reason:Pointer param should be declared pointer to const. : vm<br><32> config:part_config filename:/hypervisor/dm/vpci/vpci.c func:vpci_assign_pcidev offset:577<br> reason:Pointer param should be declared pointer to const. : pcidev<br><33> config:part_config filename:/hypervisor/dm/vpci/vpci.c func:vpci_assign_pcidev offset:577<br> reason:Pointer param should be declared pointer to const. : vm<br><34> config:sharing_config filename:/hypervisor/dm/vpci/vpci.c func:vpci_assign_pcidev offset:588<br> reason:Pointer not checked for null before use. : sos_vm<br>.....<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by lifeix** [comment]
Just for test, not ready for PR

**Comment by leilu** [comment]
OK to verify

**Comment by lifeix** [comment]
@dongyaozu Add patch 8. Could you help to review again ?

**Comment by wenlingz** [comment]
@lifeix , make doc fail, please refer the log:
****************************************************
make -C /root/workspace/acrn-hypervisor-premerge-build-image4/acrn-hypervisor/doc html BUILDDIR=/root/workspace/acrn-hypervisor-premerge-build-image4/acrn-hypervisor/build/doc
make[1]: Entering directory '/root/workspace/acrn-hypervisor-premerge-build-image4/acrn-hypervisor/doc'

New errors/warnings found, please fix them:
==============================================

/root/workspace/acrn-hypervisor-premerge-build-image4/acrn-hypervisor/hypervisor/include/dm/io_req.h:258: warning: argument 'whether' of command @param is not found in the argument list of register_mmio_emulation_handler(struct acrn_vm *vm, hv_mem_io_handler_t read_write, uint64_t start, uint64_t end, void *handler_private_data, bool hold_lock)
/root/workspace/acrn-hypervisor-premerge-build-image4/acrn-hypervisor/hypervisor/include/dm/io_req.h:272: warning: The following parameters of register_mmio_emulation_handler(struct acrn_vm *vm, hv_mem_io_handler_t read_write, uint64_t start, uint64_t end, void *handler_private_data, bool hold_lock) are not documented:
  parameter 'hold_lock'
/root/workspace/acrn-hypervisor-premerge-build-image4/acrn-hypervisor/hypervisor/include/dm/io_req.h:258: warning: argument 'whether' of command @param is not found in the argument list of register_mmio_emulation_handler(struct acrn_vm *vm, hv_mem_io_handler_t read_write, uint64_t start, uint64_t end, void *handler_private_data, bool hold_lock)
/root/workspace/acrn-hypervisor-premerge-build-image4/acrn-hypervisor/hypervisor/include/dm/io_req.h:272: warning: The following parameters of register_mmio_emulation_handler(struct acrn_vm *vm, hv_mem_io_handler_t read_write, uint64_t start, uint64_t end, void *handler_private_data, bool hold_lock) are not documented:
  parameter 'hold_lock'
/root/workspace/acrn-hypervisor-premerge-build-image4/acrn-hypervisor/hypervisor/include/dm/io_req.h:258: warning: argument 'whether' of command @param is not found in the argument list of register_mmio_emulation_handler(struct acrn_vm *vm, hv_mem_io_handler_t read_write, uint64_t start, uint64_t end, void *handler_private_data, bool hold_lock)
/root/workspace/acrn-hypervisor-premerge-build-image4/acrn-hypervisor/hypervisor/include/dm/io_req.h:272: warning: The following parameters of register_mmio_emulation_handler(struct acrn_vm *vm, hv_mem_io_handler_t read_write, uint64_t start, uint64_t end, void *handler_private_data, bool hold_lock) are not documented:
  parameter 'hold_lock'
/root/workspace/acrn-hypervisor-premerge-build-image4/acrn-hypervisor/hypervisor/include/dm/io_req.h:258: warning: argument 'whether' of command @param is not found in the argument list of register_mmio_emulation_handler(struct acrn_vm *vm, hv_mem_io_handler_t read_write, uint64_t start, uint64_t end, void *handler_private_data, bool hold_lock)
/root/workspace/acrn-hypervisor-premerge-build-image4/acrn-hypervisor/hypervisor/include/dm/io_req.h:272: warning: The following parameters of register_mmio_emulation_handler(struct acrn_vm *vm, hv_mem_io_handler_t read_write, uint64_t start, uint64_t end, void *handler_private_data, bool hold_lock) are not documented:
  parameter 'hold_lock'

make[1]: Leaving directory '/root/workspace/acrn-hypervisor-premerge-build-image4/acrn-hypervisor/doc'
make[1]: *** [Makefile:61: html] Error 1
make: *** [Makefile:159: doc] Error 2
Build step 'Execute shell' marked build as failure
Setting status of 8713a8923716dbd5d0f794047cc725c07d260579 to FAILURE with url http://acrn-jenkins.sh.intel.com:8080/job/acrn-hypervisor-premerge-build-image/1934/ and message: 'Build finished. '
Setting status of 8713a8923716dbd5d0f794047cc725c07d260579 to FAILURE with url  and message: 'SDC/INDUSTRY/LOGICAL_PARTITION/HYBRID Build Fail
 '
Triggering a new build of RmAcrnHypervisor
PremergeMailAutoSend is disabled. Triggering skipped
Finished: FAILURE

**Comment by leilu** [comment]
OK to verify

**Comment by lifeix** [comment]
> 8/8 is stranger.
> 
> If the read_write doesn't need the lock to be held, then we can unconditionally release it,
That's what I have done.
> If it needs to hold lock internally, release of this lock may lead to other lock-holder waiter to be activated.
So I didn't release the lock if the read_write handler needs hold lock.
> 
> BTW, the code itself is very ugly.
Because we could not use goto :-)

The problem not all the read_write could release the lock because when we do this handler, others may modify the read_write callback.  (Now only the MSI-X Table BAR handler needs hold the lock) If we can make sure no one will modify the read_write when it's calling, we could release the lock for this read_write.

**Comment by HuiHuangShi** [comment]
68 new potential violations to the coding guideline detected. Please help check. Thanks!<br><1> config:part_config filename:/hypervisor/common/hypercall.c func:hcall_assign_pcidev offset:828<br> reason:Pointer param should be declared pointer to const. : vm<br><2> config:sharing_config filename:/hypervisor/common/hypercall.c func:hcall_assign_pcidev offset:828<br> reason:Pointer param should be declared pointer to const. : vm<br><3> config:common filename:/hypervisor/common/hypercall.c func:hcall_assign_pcidev offset:830<br> reason:No newline after semi colon.<br><4> config:common filename:/hypervisor/common/hypercall.c func:hcall_assign_pcidev offset:834<br> reason:Logical conjunctions need brackets.<br><5> config:part_config filename:/hypervisor/common/hypercall.c func:hcall_deassign_pcidev offset:858<br> reason:Pointer param should be declared pointer to const. : vm<br><6> config:sharing_config filename:/hypervisor/common/hypercall.c func:hcall_deassign_pcidev offset:858<br> reason:Pointer param should be declared pointer to const. : vm<br><7> config:common filename:/hypervisor/common/hypercall.c func:hcall_deassign_pcidev offset:860<br> reason:No newline after semi colon.<br><8> config:common filename:/hypervisor/common/hypercall.c func:hcall_deassign_pcidev offset:864<br> reason:Logical conjunctions need brackets.<br><9> config:part_config filename:/hypervisor/common/hypercall.c func:hcall_set_ptdev_intr_info offset:894<br> reason:Procedure contains UR data flow anomalies. : irq.intx.phys_pin<br><10> config:part_config filename:/hypervisor/common/hypercall.c func:hcall_set_ptdev_intr_info offset:894<br> reason:Procedure contains UR data flow anomalies. : irq.intx.virt_pin<br><11> config:sharing_config filename:/hypervisor/common/hypercall.c func:hcall_set_ptdev_intr_info offset:894<br> reason:Procedure contains UR data flow anomalies. : irq.intx.reserved<br><12> config:sharing_config filename:/hypervisor/common/hypercall.c func:hcall_set_ptdev_intr_info offset:894<br> reason:Procedure contains UR data flow anomalies. : irq.intx.phys_pin<br><13> config:sharing_config filename:/hypervisor/common/hypercall.c func:hcall_set_ptdev_intr_info offset:894<br> reason:Procedure contains UR data flow anomalies. : irq.intx.virt_pin<br><14> config:sharing_config filename:/hypervisor/common/hypercall.c func:hcall_set_ptdev_intr_info offset:894<br> reason:Procedure contains UR data flow anomalies. : irq.intx.pic_pin<br><15> config:part_config filename:/hypervisor/common/hypercall.c func:hcall_set_ptdev_intr_info offset:894<br> reason:Procedure contains UR data flow anomalies. : irq.intx.pic_pin<br><16> config:part_config filename:/hypervisor/common/hypercall.c func:hcall_set_ptdev_intr_info offset:894<br> reason:Procedure contains UR data flow anomalies. : irq.intx.reserved<br><17> config:common filename:/hypervisor/common/hypercall.c func:hcall_set_ptdev_intr_info offset:907<br> reason:Logical conjunctions need brackets.<br><18> config:common filename:/hypervisor/common/hypercall.c func:hcall_reset_ptdev_intr_info offset:950<br> reason:Logical conjunctions need brackets.<br><19> config:common filename:/hypervisor/dm/io_req.c func:hv_emulate_mmio offset:505<br> reason:Implicit conversion: actual to formal param (MR). :  (struct _spinlock):  param  1<br><20> config:common filename:/hypervisor/dm/io_req.c func:hv_emulate_mmio offset:509<br> reason:Implicit conversion: actual to formal param (MR). :  (struct _spinlock):  param  1<br><21> config:common filename:/hypervisor/arch/x86/vtd.c func:iommu_attach_device offset:1082<br> reason:Casting operation to a pointer. : (void* to struct dmar_entry*): ( struct dmar_entry * ) hpa2hva ( dmar_unit -> root_table_addr )<br><22> config:common filename:/hypervisor/arch/x86/vtd.c func:iommu_attach_device offset:1082<br> reason:Casting operation on a pointer. : (void* to struct dmar_entry*): ( struct dmar_entry * ) hpa2hva ( dmar_unit -> root_table_addr )<br><23> config:part_config filename:/hypervisor/arch/x86/vtd.c func:iommu_attach_device offset:1086<br> reason:Pointer not checked for null before use. : root_entry<br><24> config:sharing_config filename:/hypervisor/arch/x86/vtd.c func:iommu_attach_device offset:1086<br> reason:Pointer not checked for null before use. : root_entry<br><25> config:common filename:/hypervisor/arch/x86/vtd.c func:iommu_attach_device offset:1109<br> reason:Casting operation to a pointer. : (void* to struct dmar_entry*): ( struct dmar_entry * ) hpa2hva ( context_table_addr )<br><26> config:common filename:/hypervisor/arch/x86/vtd.c func:iommu_attach_device offset:1109<br> reason:Casting operation on a pointer. : (void* to struct dmar_entry*): ( struct dmar_entry * ) hpa2hva ( context_table_addr )<br><27> config:sharing_config filename:/hypervisor/arch/x86/vtd.c func:iommu_attach_device offset:1131<br> reason:Function return value potentially unused. : hi_64<br><28> config:part_config filename:/hypervisor/arch/x86/vtd.c func:iommu_attach_device offset:1131<br> reason:Function return value potentially unused. : hi_64<br><29> config:sharing_config filename:/hypervisor/arch/x86/vtd.c func:iommu_attach_device offset:1133<br> reason:Function return value potentially unused. : lo_64<br><30> config:part_config filename:/hypervisor/arch/x86/vtd.c func:iommu_attach_device offset:1133<br> reason:Function return value potentially unused. : lo_64<br><31> config:part_config filename:/hypervisor/arch/x86/vtd.c func:iommu_attach_device offset:1141<br> reason:Function return value potentially unused. : hi_64<br><32> config:sharing_config filename:/hypervisor/arch/x86/vtd.c func:iommu_attach_device offset:1141<br> reason:Function return value potentially unused. : hi_64<br><33> config:part_config filename:/hypervisor/arch/x86/vtd.c func:iommu_attach_device offset:1143<br> reason:Function return value potentially unused. : lo_64<br><34> config:sharing_config filename:/hypervisor/arch/x86/vtd.c func:iommu_attach_device offset:1143<br> reason:Function return value potentially unused. : lo_64<br>.....<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by lifeix** [comment]
fix four MISRA-C voilation
restore physical BAR in vpci_assign_pcidev if this device has been reset in ACRN-DM

**Comment by HuiHuangShi** [comment]
64 new potential violations to the coding guideline detected. Please help check. Thanks!<br><1> config:common filename:/hypervisor/arch/x86/vtd.c func:iommu_attach_device offset:1082<br> reason:Casting operation to a pointer. : (void* to struct dmar_entry*): ( struct dmar_entry * ) hpa2hva ( dmar_unit -> root_table_addr )<br><2> config:common filename:/hypervisor/arch/x86/vtd.c func:iommu_attach_device offset:1082<br> reason:Casting operation on a pointer. : (void* to struct dmar_entry*): ( struct dmar_entry * ) hpa2hva ( dmar_unit -> root_table_addr )<br><3> config:part_config filename:/hypervisor/arch/x86/vtd.c func:iommu_attach_device offset:1086<br> reason:Pointer not checked for null before use. : root_entry<br><4> config:sharing_config filename:/hypervisor/arch/x86/vtd.c func:iommu_attach_device offset:1086<br> reason:Pointer not checked for null before use. : root_entry<br><5> config:common filename:/hypervisor/arch/x86/vtd.c func:iommu_attach_device offset:1109<br> reason:Casting operation to a pointer. : (void* to struct dmar_entry*): ( struct dmar_entry * ) hpa2hva ( context_table_addr )<br><6> config:common filename:/hypervisor/arch/x86/vtd.c func:iommu_attach_device offset:1109<br> reason:Casting operation on a pointer. : (void* to struct dmar_entry*): ( struct dmar_entry * ) hpa2hva ( context_table_addr )<br><7> config:sharing_config filename:/hypervisor/arch/x86/vtd.c func:iommu_attach_device offset:1131<br> reason:Function return value potentially unused. : hi_64<br><8> config:part_config filename:/hypervisor/arch/x86/vtd.c func:iommu_attach_device offset:1131<br> reason:Function return value potentially unused. : hi_64<br><9> config:sharing_config filename:/hypervisor/arch/x86/vtd.c func:iommu_attach_device offset:1133<br> reason:Function return value potentially unused. : lo_64<br><10> config:part_config filename:/hypervisor/arch/x86/vtd.c func:iommu_attach_device offset:1133<br> reason:Function return value potentially unused. : lo_64<br><11> config:part_config filename:/hypervisor/arch/x86/vtd.c func:iommu_attach_device offset:1141<br> reason:Function return value potentially unused. : hi_64<br><12> config:sharing_config filename:/hypervisor/arch/x86/vtd.c func:iommu_attach_device offset:1141<br> reason:Function return value potentially unused. : hi_64<br><13> config:part_config filename:/hypervisor/arch/x86/vtd.c func:iommu_attach_device offset:1143<br> reason:Function return value potentially unused. : lo_64<br><14> config:sharing_config filename:/hypervisor/arch/x86/vtd.c func:iommu_attach_device offset:1143<br> reason:Function return value potentially unused. : lo_64<br><15> config:part_config filename:/hypervisor/arch/x86/vtd.c func:iommu_detach_device offset:1173<br> reason:Procedure contains UR data flow anomalies. : sid.value<br><16> config:sharing_config filename:/hypervisor/arch/x86/vtd.c func:iommu_detach_device offset:1173<br> reason:Procedure contains UR data flow anomalies. : sid.value<br><17> config:common filename:/hypervisor/arch/x86/vtd.c func:iommu_detach_device offset:1187<br> reason:Casting operation to a pointer. : (void* to struct dmar_entry*): ( struct dmar_entry * ) hpa2hva ( dmar_unit -> root_table_addr )<br><18> config:common filename:/hypervisor/arch/x86/vtd.c func:iommu_detach_device offset:1187<br> reason:Casting operation on a pointer. : (void* to struct dmar_entry*): ( struct dmar_entry * ) hpa2hva ( dmar_unit -> root_table_addr )<br><19> config:common filename:/hypervisor/arch/x86/vtd.c func:iommu_detach_device offset:1197<br> reason:Casting operation to a pointer. : (void* to struct dmar_entry*): ( struct dmar_entry * ) hpa2hva ( context_table_addr )<br><20> config:common filename:/hypervisor/arch/x86/vtd.c func:iommu_detach_device offset:1197<br> reason:Casting operation on a pointer. : (void* to struct dmar_entry*): ( struct dmar_entry * ) hpa2hva ( context_table_addr )<br><21> config:common filename:/hypervisor/dm/io_req.c func:hv_emulate_mmio offset:505<br> reason:Implicit conversion: actual to formal param (MR). :  (struct _spinlock):  param  1<br><22> config:common filename:/hypervisor/dm/io_req.c func:hv_emulate_mmio offset:509<br> reason:Implicit conversion: actual to formal param (MR). :  (struct _spinlock):  param  1<br><23> config:part_config filename:/hypervisor/common/hypercall.c func:hcall_assign_pcidev offset:828<br> reason:Pointer param should be declared pointer to const. : vm<br><24> config:sharing_config filename:/hypervisor/common/hypercall.c func:hcall_assign_pcidev offset:828<br> reason:Pointer param should be declared pointer to const. : vm<br><25> config:common filename:/hypervisor/common/hypercall.c func:hcall_assign_pcidev offset:834<br> reason:Logical conjunctions need brackets.<br><26> config:part_config filename:/hypervisor/common/hypercall.c func:hcall_deassign_pcidev offset:858<br> reason:Pointer param should be declared pointer to const. : vm<br><27> config:sharing_config filename:/hypervisor/common/hypercall.c func:hcall_deassign_pcidev offset:858<br> reason:Pointer param should be declared pointer to const. : vm<br><28> config:common filename:/hypervisor/common/hypercall.c func:hcall_deassign_pcidev offset:864<br> reason:Logical conjunctions need brackets.<br><29> config:part_config filename:/hypervisor/common/hypercall.c func:hcall_set_ptdev_intr_info offset:894<br> reason:Procedure contains UR data flow anomalies. : irq.intx.virt_pin<br><30> config:part_config filename:/hypervisor/common/hypercall.c func:hcall_set_ptdev_intr_info offset:894<br> reason:Procedure contains UR data flow anomalies. : irq.intx.phys_pin<br><31> config:sharing_config filename:/hypervisor/common/hypercall.c func:hcall_set_ptdev_intr_info offset:894<br> reason:Procedure contains UR data flow anomalies. : irq.intx.reserved<br><32> config:sharing_config filename:/hypervisor/common/hypercall.c func:hcall_set_ptdev_intr_info offset:894<br> reason:Procedure contains UR data flow anomalies. : irq.intx.phys_pin<br><33> config:sharing_config filename:/hypervisor/common/hypercall.c func:hcall_set_ptdev_intr_info offset:894<br> reason:Procedure contains UR data flow anomalies. : irq.intx.virt_pin<br><34> config:sharing_config filename:/hypervisor/common/hypercall.c func:hcall_set_ptdev_intr_info offset:894<br> reason:Procedure contains UR data flow anomalies. : irq.intx.pic_pin<br>.....<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by ClaudZhang1995** [comment]
@HuiHuangShi please help to do the ldra check , thanks.

**Comment by shiqingg** [comment]
@HuiHuangShi has checked all the issues related to coding guidelines and confirmed that the label 'Coding Guidelines: PASS' can be added for this PR.

As @HuiHuangShi could not log in Github temporarily, I added this label on behalf of @HuiHuangShi.

**Pull request merged**
