### PR TITLE
acrn-config: add cpu affinity for launch config xmls

### PR DESCRIPTION
**Pull request by liuwei987**
- add vm type sanity check

- refinement for pci_devs in scenario config xmls

- parse cpu_affinity from launch config xmls

- add cpu_affinity for launch config xmls

Tracked-On: #4641
Signed-off-by: Wei Liu weix.w.liu@intel.com
Acked-by: Victor Sun victor.sun@intel.com

### CODE REVIEW

**Comment by HuiHuangShi** [comment]
No new violations to the coding guideline detected.<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by HuiHuangShi** [comment]
No new violations to the coding guideline detected.<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by jsun26intel** [comment]
according to https://github.com/projectacrn/acrn-hypervisor/pull/4708, the command should be "--cpu_affinity"

**Comment by HuiHuangShi** [comment]
No new violations to the coding guideline detected.<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by HuiHuangShi** [comment]
No new violations to the coding guideline detected.<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Pull request merged**
