### PR TITLE
Static config vcpu

### PR DESCRIPTION
**Pull request by shuox**
We are going to make vcpus number pre-defined in HV scenario configurations. It means
devicemodel cannot configure vcpu number any more. Devicemodel only need to do VM
creating, then hypervisor will create vcpus for it according the pre-defined vcpu number.

This patchset also introduces vcpu_affinity[] to indicate pcpu<->vcpu mapping for each VM.
Then we can remove pcpu_bitmap from vm_config as it will be implied in vcpu_affinity[].

v4: 1) consider Kata VM config in SDC scenario.
    2) Change patch 1/9 and 4/9 to keep HC_CREATE_VCPU hypercall and vm_create_vcpu
       for compatbility. Then, we can merge this patchset without kernel change.

v3: 1) pcpu_bitmap -> vm_pcpu_bitmap
    2) use MARCOs for vcpu_affinity[] in vm_conifg
    3) make guest_ncpus static
    4) add some comments.

v2: use __builtin_popcountl() for bitmap_weight according Fengwei's suggestion.

Conghui Chen (2):
  dm: remove guest cpu number option
  dm: script: remove guest cpu number

Shuo A Liu (7):
  dm: get vcpu num from hypervisor when create VM
  hv: make hypercall HC_CREATE_VCPU empty
  hv: Add a helper to account bitmap weight
  hv: return pre-defined vcpu_num from HV to upper layer
  hv: use vcpu_affinity[] in vm_config to support vcpu assignment
  hv: remove unused pcpu assignment functions
  hv: create all VCPUs for guest when create VM

 devicemodel/core/main.c                            | 17 +++-----
 devicemodel/core/vmmapi.c                          |  3 +-
 devicemodel/include/dm.h                           |  1 -
 devicemodel/include/vmmapi.h                       |  2 +-
 devicemodel/samples/apl-mrb/launch_uos.sh          | 50 +++++++++++-----------
 devicemodel/samples/apl-up2/launch_uos.sh          | 50 +++++++++++-----------
 devicemodel/samples/nuc/launch_hard_rt_vm.sh       |  4 +-
 devicemodel/samples/nuc/launch_uos.sh              |  6 +--
 devicemodel/samples/nuc/launch_vxworks.sh          |  4 +-
 devicemodel/samples/nuc/launch_win.sh              |  6 +--
 devicemodel/samples/nuc/launch_zephyr.sh           |  4 +-
 hypervisor/arch/x86/configs/vm_config.c            | 44 +++++++++++++++----
 hypervisor/arch/x86/guest/vcpu.c                   | 19 +-------
 hypervisor/arch/x86/guest/vm.c                     | 31 ++++++++------
 hypervisor/arch/x86/guest/vmcall.c                 |  7 +--
 hypervisor/common/hypercall.c                      | 41 +-----------------
 hypervisor/common/schedule.c                       | 28 ------------
 hypervisor/include/arch/x86/lib/bits.h             |  5 +++
 hypervisor/include/arch/x86/vm_config.h            |  6 ++-
 hypervisor/include/common/hypercall.h              | 17 --------
 hypervisor/include/common/schedule.h               |  4 --
 hypervisor/include/public/acrn_common.h            |  3 +-
 hypervisor/scenarios/hybrid/vm_configurations.c    |  5 ++-
 hypervisor/scenarios/hybrid/vm_configurations.h    |  3 +-
 hypervisor/scenarios/industry/vm_configurations.c  |  7 +++
 hypervisor/scenarios/industry/vm_configurations.h  |  4 ++
 .../logical_partition/vm_configurations.c          |  6 ++-
 .../logical_partition/vm_configurations.h          |  6 +--
 hypervisor/scenarios/sdc/vm_configurations.c       |  4 ++
 hypervisor/scenarios/sdc/vm_configurations.h       |  6 +++
 hypervisor/scenarios/sdc2/vm_configurations.c      |  6 +++
 hypervisor/scenarios/sdc2/vm_configurations.h      |  4 ++
 32 files changed, 182 insertions(+), 221 deletions(-)

### CODE REVIEW

**Comment by ClaudZhang1995** [comment]
OK to verify

**Comment by HuiHuangShi** [comment]
10 new potential violations to the coding guideline detected. Please help check. Thanks!<br><1> config:common filename:/hypervisor/arch/x86/configs/vm_config.c func:sanitize_vm_config offset:69<br> reason:Cyclomatic complexity greater than 20.<br><2> config:common filename:/hypervisor/arch/x86/configs/vm_config.c func:sanitize_vm_config offset:87<br> reason:Literal value requires a U suffix.           : 0<br><3> config:common filename:/hypervisor/arch/x86/configs/vm_config.c func:sanitize_vm_config offset:87<br> reason:Signed/unsigned conversion without cast. :  (unsigned short and int): vcpu_id<br><4> config:common filename:/hypervisor/arch/x86/configs/vm_config.c func:sanitize_vm_config offset:132<br> reason:Logical conjunctions need brackets.<br><5> config:common filename:/hypervisor/arch/x86/guest/vm.c func:create_vm offset:419<br> reason:Cyclomatic complexity greater than 20.<br><6> config:sharing_config filename:/hypervisor/scenarios/sdc/vm_configurations.c func: offset:49<br> reason:Signed/unsigned conversion without cast. :  (unsigned short and unsigned int): .vcpu_num = 3U<br><7> config:part_config filename:/hypervisor/common/hypercall.c func:hcall_create_vm offset:178<br> reason:Function return value potentially unused. : cv.vmid<br><8> config:sharing_config filename:/hypervisor/common/hypercall.c func:hcall_create_vm offset:178<br> reason:Function return value potentially unused. : cv.vmid<br><9> config:common filename:/hypervisor/include/arch/x86/lib/bits.h func:bitmap_weight offset:294<br> reason:Static procedure is not explicitly called in code analysed. : bitmap_weight<br><10> config:common filename:/hypervisor/include/arch/x86/lib/bits.h func:bitmap_weight offset:296<br> reason:Function call with no prior declaration.     : __builtin_popcountl<br><br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by HuiHuangShi** [comment]
8 new potential violations to the coding guideline detected. Please help check. Thanks!<br><1> config:common filename:/hypervisor/arch/x86/configs/vm_config.c func:sanitize_vm_config offset:69<br> reason:Cyclomatic complexity greater than 20.<br><2> config:common filename:/hypervisor/arch/x86/configs/vm_config.c func:sanitize_vm_config offset:132<br> reason:Logical conjunctions need brackets.<br><3> config:common filename:/hypervisor/arch/x86/guest/vm.c func:create_vm offset:419<br> reason:Cyclomatic complexity greater than 20.<br><4> config:sharing_config filename:/hypervisor/scenarios/sdc/vm_configurations.c func: offset:49<br> reason:Signed/unsigned conversion without cast. :  (unsigned short and unsigned int): .vcpu_num = 3U<br><5> config:part_config filename:/hypervisor/common/hypercall.c func:hcall_create_vm offset:178<br> reason:Function return value potentially unused. : cv.vmid<br><6> config:sharing_config filename:/hypervisor/common/hypercall.c func:hcall_create_vm offset:178<br> reason:Function return value potentially unused. : cv.vmid<br><7> config:common filename:/hypervisor/include/arch/x86/lib/bits.h func:bitmap_weight offset:294<br> reason:Static procedure is not explicitly called in code analysed. : bitmap_weight<br><8> config:common filename:/hypervisor/include/arch/x86/lib/bits.h func:bitmap_weight offset:296<br> reason:Function call with no prior declaration.     : __builtin_popcountl<br><br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by acrnsi** [comment]
Ok to verify

**Comment by HuiHuangShi** [comment]
7 new potential violations to the coding guideline detected. Please help check. Thanks!<br><1> config:common filename:/hypervisor/arch/x86/configs/vm_config.c func:sanitize_vm_config offset:69<br> reason:Cyclomatic complexity greater than 20.<br><2> config:common filename:/hypervisor/arch/x86/guest/vm.c func:create_vm offset:419<br> reason:Cyclomatic complexity greater than 20.<br><3> config:sharing_config filename:/hypervisor/scenarios/sdc/vm_configurations.c func: offset:49<br> reason:Signed/unsigned conversion without cast. :  (unsigned short and unsigned int): .vcpu_num = 4U<br><4> config:part_config filename:/hypervisor/common/hypercall.c func:hcall_create_vm offset:178<br> reason:Function return value potentially unused. : cv.vmid<br><5> config:sharing_config filename:/hypervisor/common/hypercall.c func:hcall_create_vm offset:178<br> reason:Function return value potentially unused. : cv.vmid<br><6> config:common filename:/hypervisor/include/arch/x86/lib/bits.h func:bitmap_weight offset:294<br> reason:Static procedure is not explicitly called in code analysed. : bitmap_weight<br><7> config:common filename:/hypervisor/include/arch/x86/lib/bits.h func:bitmap_weight offset:296<br> reason:Function call with no prior declaration.     : __builtin_popcountl<br><br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by HuiHuangShi** [comment]
7 new potential violations to the coding guideline detected. Please help check. Thanks!<br><1> config:common filename:/hypervisor/arch/x86/configs/vm_config.c func:sanitize_vm_config offset:69<br> reason:Cyclomatic complexity greater than 20.<br><2> config:common filename:/hypervisor/arch/x86/guest/vm.c func:create_vm offset:419<br> reason:Cyclomatic complexity greater than 20.<br><3> config:sharing_config filename:/hypervisor/scenarios/sdc/vm_configurations.c func: offset:49<br> reason:Signed/unsigned conversion without cast. :  (unsigned short and unsigned int): .vcpu_num = 4U<br><4> config:part_config filename:/hypervisor/common/hypercall.c func:hcall_create_vm offset:178<br> reason:Function return value potentially unused. : cv.vmid<br><5> config:sharing_config filename:/hypervisor/common/hypercall.c func:hcall_create_vm offset:178<br> reason:Function return value potentially unused. : cv.vmid<br><6> config:common filename:/hypervisor/include/arch/x86/lib/bits.h func:bitmap_weight offset:294<br> reason:Static procedure is not explicitly called in code analysed. : bitmap_weight<br><7> config:common filename:/hypervisor/include/arch/x86/lib/bits.h func:bitmap_weight offset:296<br> reason:Function call with no prior declaration.     : __builtin_popcountl<br><br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by acrnsi** [comment]
OK to verify

**Comment by acrnsi** [comment]
OK to verify

**Comment by HuiHuangShi** [comment]
7 new potential violations to the coding guideline detected. Please help check. Thanks!<br><1> config:common filename:/hypervisor/arch/x86/configs/vm_config.c func:sanitize_vm_config offset:69<br> reason:Cyclomatic complexity greater than 20.<br><2> config:common filename:/hypervisor/arch/x86/guest/vm.c func:create_vm offset:419<br> reason:Cyclomatic complexity greater than 20.<br><3> config:sharing_config filename:/hypervisor/scenarios/sdc/vm_configurations.c func: offset:49<br> reason:Signed/unsigned conversion without cast. :  (unsigned short and unsigned int): .vcpu_num = 4U<br><4> config:part_config filename:/hypervisor/common/hypercall.c func:hcall_create_vm offset:178<br> reason:Function return value potentially unused. : cv.vmid<br><5> config:sharing_config filename:/hypervisor/common/hypercall.c func:hcall_create_vm offset:178<br> reason:Function return value potentially unused. : cv.vmid<br><6> config:common filename:/hypervisor/include/arch/x86/lib/bits.h func:bitmap_weight offset:294<br> reason:Static procedure is not explicitly called in code analysed. : bitmap_weight<br><7> config:common filename:/hypervisor/include/arch/x86/lib/bits.h func:bitmap_weight offset:296<br> reason:Function call with no prior declaration.     : __builtin_popcountl<br><br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by HuiHuangShi** [comment]
7 new potential violations to the coding guideline detected. Please help check. Thanks!<br><1> config:common filename:/hypervisor/arch/x86/configs/vm_config.c func:sanitize_vm_config offset:69<br> reason:Cyclomatic complexity greater than 20.<br><2> config:common filename:/hypervisor/arch/x86/guest/vm.c func:create_vm offset:419<br> reason:Cyclomatic complexity greater than 20.<br><3> config:common filename:/hypervisor/scenarios/sdc/vm_configurations.c func: offset:49<br> reason:Signed/unsigned conversion without cast. :  (unsigned short and unsigned int): .vcpu_num = 4U<br><4> config:part_config filename:/hypervisor/common/hypercall.c func:hcall_create_vm offset:178<br> reason:Function return value potentially unused. : cv.vmid<br><5> config:sharing_config filename:/hypervisor/common/hypercall.c func:hcall_create_vm offset:178<br> reason:Function return value potentially unused. : cv.vmid<br><6> config:common filename:/hypervisor/include/arch/x86/lib/bits.h func:bitmap_weight offset:294<br> reason:Static procedure is not explicitly called in code analysed. : bitmap_weight<br><7> config:common filename:/hypervisor/include/arch/x86/lib/bits.h func:bitmap_weight offset:296<br> reason:Function call with no prior declaration.     : __builtin_popcountl<br><br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Pull request merged**
