### PR TITLE
Abstract scheduler from sched module and polish sched framework

### PR DESCRIPTION
**Pull request by shuox**
This patchset refines schedule module of ACRN for modularization and extendibility.
It mainly does
  1) polish vcpu and schedule modulization
  2) abstract scheduler object for schedule module to enhance scalability
  3) keep current schedule policy in a 'noop' scheduler

We also add status for thread_object. There are three valid status for thread_object now: THREAD_STS_RUNNING, THREAD_STS_RUNNABLE, THREAD_STS_BLOCKED.
In general, thread_obj starts from THREAD_STS_BLOCKED, then be changed to THREAD_STS_RUNNABLE after wake up and be changed to THREAD_STS_RUNNING by being scheduled in. THREAD_STS_RUNNING -> THREAD_STS_RUNNABLE happens in schedule out.
thread_obj will be changed to THREAD_STS_BLOCKED while doing sleep operation.

For scheduler object, we define a struct named acrn_scheduler:
struct acrn_scheduler {
        char name[16];

        /* init scheduler */
        int     (*init)(struct sched_control *ctx);
        /* init private data of scheduler */
        void    (*init_data)(struct thread_object *obj);
        /* pick the next thread object */
        struct thread_object* (*pick_next)(struct sched_control *ctx);
        /* put schedule object into sleep */
        void    (*sleep)(struct thread_object *obj);
        /* wake up schedule object from sleep status */
        void    (*wake)(struct thread_object *obj);
        /* yield current thread object */
        void    (*yield)(struct sched_control *ctx);
        /* prioritize the thread object */
        void    (*prioritize)(struct thread_object *obj);
        /* deinit private data of scheduler */
        void    (*deinit_data)(struct thread_object *obj);
        /* deinit scheduler */
        void    (*deinit)(struct sched_control *ctx);
};
We can add a new scheduler by implementing a new acrn_scheduler.

Now, the real cpu sharing function is not included in this patchset. We will add a new scheduler to support the sharing schedule policy.

V2: Merge the first two patches for renaming mainly. Rebase the rest.

V3: polish the last 6 patches.
    1) remove init_sched_data from reset_vcpu
    2) rename get_schedule_lock -> obtain_schedule_lock
    3) poke_thread -> kick_thread, poke_vcpu -> kick_vcpu
    4) make kick_vcpu do notification only

Conghui Chen (1):
  hv: sched: disable interrupt when grab schedule spinlock

Shuo A Liu (5):
  hv: sched: add pcpu_id in sched_control
  hv: sched: decouple scheduler from schedule framework
  hv: sched: remove do_switch
  hv: sched: support config scheduler for each VM
  hv: sched: add kick_thread to support notification

 hypervisor/Makefile                      |   1 +
 hypervisor/arch/x86/configs/vm_config.c  |   4 +
 hypervisor/arch/x86/cpu.c                |   1 +
 hypervisor/arch/x86/guest/vcpu.c         |  13 +-
 hypervisor/arch/x86/guest/virq.c         |  15 +--
 hypervisor/arch/x86/guest/vlapic.c       |   2 +-
 hypervisor/arch/x86/guest/vm.c           |   4 +-
 hypervisor/common/sched_noop.c           |  55 +++++++++
 hypervisor/common/schedule.c             | 197 +++++++++++++++++++++++--------
 hypervisor/include/arch/x86/guest/vcpu.h |  13 +-
 hypervisor/include/arch/x86/per_cpu.h    |   1 +
 hypervisor/include/arch/x86/vm_config.h  |   1 +
 hypervisor/include/common/schedule.h     |  48 +++++++-
 13 files changed, 279 insertions(+), 76 deletions(-)  create mode 100644 hypervisor/common/sched_noop.c

### CODE REVIEW

**Comment by HuiHuangShi** [comment]
35 new potential violations to the coding guideline detected. Please help check. Thanks!<br><1> config:sharing_config filename:/hypervisor/common/schedule.c func:deinit_thread_data offset:105<br> reason:Pointer param should be declared pointer to const. : obj<br><2> config:part_config filename:/hypervisor/common/schedule.c func:deinit_thread_data offset:105<br> reason:Pointer param should be declared pointer to const. : obj<br><3> config:sharing_config filename:/hypervisor/common/schedule.c func:deinit_thread_data offset:105<br> reason:Procedure is not called or referenced in code analysed. : deinit_thread_data<br><4> config:part_config filename:/hypervisor/common/schedule.c func:deinit_thread_data offset:105<br> reason:Procedure is not called or referenced in code analysed. : deinit_thread_data<br><5> config:sharing_config filename:/hypervisor/common/schedule.c func:wake_thread offset:210<br> reason:Function return value potentially unused. : scheduler<br><6> config:part_config filename:/hypervisor/common/schedule.c func:wake_thread offset:210<br> reason:Function return value potentially unused. : scheduler<br><7> config:sharing_config filename:/hypervisor/common/schedule.c func:kick_thread offset:224<br> reason:Pointer param should be declared pointer to const. : obj<br><8> config:part_config filename:/hypervisor/common/schedule.c func:kick_thread offset:224<br> reason:Pointer param should be declared pointer to const. : obj<br><9> config:common filename:/hypervisor/common/schedule.c func:kick_thread offset:236<br> reason:Else alternative missing in if.<br><10> config:part_config filename:/hypervisor/arch/x86/guest/vm.c func: offset:34<br> reason:Variable should be declared static. : vm_sw_loader<br><11> config:sharing_config filename:/hypervisor/arch/x86/guest/vm.c func: offset:34<br> reason:Variable should be declared static. : vm_sw_loader<br><12> config:common filename:/hypervisor/include/common/schedule.h func: offset:61<br> reason:Basic type declaration used. : int ( * init ) ( struct sched_control * ctl )<br><13> config:common filename:/hypervisor/common/sched_noop.c func:sched_noop_init offset:10<br> reason:Basic type declaration used. : int sched_noop_init<br><14> config:common filename:/hypervisor/common/sched_noop.c func:sched_noop_init offset:10<br> reason:Static procedure is not explicitly called in code analysed. : sched_noop_init<br><15> config:sharing_config filename:/hypervisor/common/sched_noop.c func:sched_noop_pick_next offset:18<br> reason:Pointer param should be declared pointer to const. : ctl<br><16> config:part_config filename:/hypervisor/common/sched_noop.c func:sched_noop_pick_next offset:18<br> reason:Pointer param should be declared pointer to const. : ctl<br><17> config:common filename:/hypervisor/common/sched_noop.c func:sched_noop_pick_next offset:18<br> reason:Static procedure is not explicitly called in code analysed. : sched_noop_pick_next<br><18> config:common filename:/hypervisor/common/sched_noop.c func:sched_noop_pick_next offset:20<br> reason:Casting operation to a pointer. : (void* to struct sched_noop_control*): ( struct sched_noop_control * ) ctl -> priv<br><19> config:common filename:/hypervisor/common/sched_noop.c func:sched_noop_pick_next offset:20<br> reason:Casting operation on a pointer. : (void* to struct sched_noop_control*): ( struct sched_noop_control * ) ctl -> priv<br><20> config:part_config filename:/hypervisor/common/sched_noop.c func:sched_noop_pick_next offset:28<br> reason:Local structure returned in function result. : next<br><21> config:sharing_config filename:/hypervisor/common/sched_noop.c func:sched_noop_pick_next offset:28<br> reason:Local structure returned in function result. : next<br><22> config:part_config filename:/hypervisor/common/sched_noop.c func:sched_noop_sleep offset:31<br> reason:Pointer param should be declared pointer to const. : obj<br><23> config:sharing_config filename:/hypervisor/common/sched_noop.c func:sched_noop_sleep offset:31<br> reason:Pointer param should be declared pointer to const. : obj<br><24> config:common filename:/hypervisor/common/sched_noop.c func:sched_noop_sleep offset:31<br> reason:Static procedure is not explicitly called in code analysed. : sched_noop_sleep<br><25> config:common filename:/hypervisor/common/sched_noop.c func:sched_noop_sleep offset:33<br> reason:Casting operation to a pointer. : (void* to struct sched_noop_control*): ( struct sched_noop_control * ) obj -> sched_ctl -> priv<br><26> config:common filename:/hypervisor/common/sched_noop.c func:sched_noop_sleep offset:33<br> reason:Casting operation on a pointer. : (void* to struct sched_noop_control*): ( struct sched_noop_control * ) obj -> sched_ctl -> priv<br><27> config:common filename:/hypervisor/common/sched_noop.c func:sched_noop_wake offset:40<br> reason:Static procedure is not explicitly called in code analysed. : sched_noop_wake<br><28> config:common filename:/hypervisor/common/sched_noop.c func:sched_noop_wake offset:42<br> reason:Casting operation to a pointer. : (void* to struct sched_noop_control*): ( struct sched_noop_control * ) obj -> sched_ctl -> priv<br><29> config:common filename:/hypervisor/common/sched_noop.c func:sched_noop_wake offset:42<br> reason:Casting operation on a pointer. : (void* to struct sched_noop_control*): ( struct sched_noop_control * ) obj -> sched_ctl -> priv<br><30> config:common filename:/hypervisor/common/sched_noop.c func: offset:52<br> reason:Function pointer is of wrong type.           : Return types differ; sched_noop.init_data: void, sched_noop_pick_next: struct thread_object*<br><31> config:common filename:/hypervisor/common/sched_noop.c func: offset:53<br> reason:Function pointer is of wrong type.           : Return types differ; sched_noop.pick_next: struct thread_object*, sched_noop_sleep: void<br><32> config:part_config filename:/hypervisor/arch/x86/guest/vcpu.c func:kick_vcpu offset:601<br> reason:Pointer param should be declared pointer to const. : vcpu<br><33> config:sharing_config filename:/hypervisor/arch/x86/guest/vcpu.c func:kick_vcpu offset:601<br> reason:Pointer param should be declared pointer to const. : vcpu<br><34> config:common filename:/hypervisor/arch/x86/guest/vcpu.c func:launch_vcpu offset:741<br> reason:Type conversion without cast. :  (enum vm_state and enum vcpu_state): vcpu -> state =<br>.....<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by HuiHuangShi** [comment]
33 new potential violations to the coding guideline detected. Please help check. Thanks!<br><1> config:sharing_config filename:/hypervisor/common/schedule.c func:deinit_thread_data offset:105<br> reason:Pointer param should be declared pointer to const. : obj<br><2> config:part_config filename:/hypervisor/common/schedule.c func:deinit_thread_data offset:105<br> reason:Pointer param should be declared pointer to const. : obj<br><3> config:sharing_config filename:/hypervisor/common/schedule.c func:deinit_thread_data offset:105<br> reason:Procedure is not called or referenced in code analysed. : deinit_thread_data<br><4> config:part_config filename:/hypervisor/common/schedule.c func:deinit_thread_data offset:105<br> reason:Procedure is not called or referenced in code analysed. : deinit_thread_data<br><5> config:sharing_config filename:/hypervisor/common/schedule.c func:wake_thread offset:210<br> reason:Function return value potentially unused. : scheduler<br><6> config:part_config filename:/hypervisor/common/schedule.c func:wake_thread offset:210<br> reason:Function return value potentially unused. : scheduler<br><7> config:sharing_config filename:/hypervisor/common/schedule.c func:kick_thread offset:224<br> reason:Pointer param should be declared pointer to const. : obj<br><8> config:part_config filename:/hypervisor/common/schedule.c func:kick_thread offset:224<br> reason:Pointer param should be declared pointer to const. : obj<br><9> config:common filename:/hypervisor/common/schedule.c func:kick_thread offset:236<br> reason:Else alternative missing in if.<br><10> config:part_config filename:/hypervisor/arch/x86/guest/vcpu.c func:kick_vcpu offset:601<br> reason:Pointer param should be declared pointer to const. : vcpu<br><11> config:sharing_config filename:/hypervisor/arch/x86/guest/vcpu.c func:kick_vcpu offset:601<br> reason:Pointer param should be declared pointer to const. : vcpu<br><12> config:common filename:/hypervisor/arch/x86/guest/vcpu.c func:launch_vcpu offset:741<br> reason:Type conversion without cast. :  (enum vm_state and enum vcpu_state): vcpu -> state =<br><13> config:common filename:/hypervisor/arch/x86/guest/vcpu.c func:launch_vcpu offset:741<br> reason:Use of underlying enum representation value. :  (enum vm_state and enum vcpu_state): vcpu -> state =<br><14> config:common filename:/hypervisor/include/common/schedule.h func: offset:61<br> reason:Basic type declaration used. : int ( * init ) ( struct sched_control * ctl )<br><15> config:common filename:/hypervisor/common/sched_noop.c func:sched_noop_init offset:10<br> reason:Basic type declaration used. : int sched_noop_init<br><16> config:common filename:/hypervisor/common/sched_noop.c func:sched_noop_init offset:10<br> reason:Static procedure is not explicitly called in code analysed. : sched_noop_init<br><17> config:part_config filename:/hypervisor/common/sched_noop.c func:sched_noop_pick_next offset:18<br> reason:Pointer param should be declared pointer to const. : ctl<br><18> config:sharing_config filename:/hypervisor/common/sched_noop.c func:sched_noop_pick_next offset:18<br> reason:Pointer param should be declared pointer to const. : ctl<br><19> config:common filename:/hypervisor/common/sched_noop.c func:sched_noop_pick_next offset:18<br> reason:Static procedure is not explicitly called in code analysed. : sched_noop_pick_next<br><20> config:common filename:/hypervisor/common/sched_noop.c func:sched_noop_pick_next offset:20<br> reason:Casting operation to a pointer. : (void* to struct sched_noop_control*): ( struct sched_noop_control * ) ctl -> priv<br><21> config:common filename:/hypervisor/common/sched_noop.c func:sched_noop_pick_next offset:20<br> reason:Casting operation on a pointer. : (void* to struct sched_noop_control*): ( struct sched_noop_control * ) ctl -> priv<br><22> config:part_config filename:/hypervisor/common/sched_noop.c func:sched_noop_pick_next offset:28<br> reason:Local structure returned in function result. : next<br><23> config:sharing_config filename:/hypervisor/common/sched_noop.c func:sched_noop_pick_next offset:28<br> reason:Local structure returned in function result. : next<br><24> config:part_config filename:/hypervisor/common/sched_noop.c func:sched_noop_sleep offset:31<br> reason:Pointer param should be declared pointer to const. : obj<br><25> config:sharing_config filename:/hypervisor/common/sched_noop.c func:sched_noop_sleep offset:31<br> reason:Pointer param should be declared pointer to const. : obj<br><26> config:common filename:/hypervisor/common/sched_noop.c func:sched_noop_sleep offset:31<br> reason:Static procedure is not explicitly called in code analysed. : sched_noop_sleep<br><27> config:common filename:/hypervisor/common/sched_noop.c func:sched_noop_sleep offset:33<br> reason:Casting operation to a pointer. : (void* to struct sched_noop_control*): ( struct sched_noop_control * ) obj -> sched_ctl -> priv<br><28> config:common filename:/hypervisor/common/sched_noop.c func:sched_noop_sleep offset:33<br> reason:Casting operation on a pointer. : (void* to struct sched_noop_control*): ( struct sched_noop_control * ) obj -> sched_ctl -> priv<br><29> config:common filename:/hypervisor/common/sched_noop.c func:sched_noop_wake offset:40<br> reason:Static procedure is not explicitly called in code analysed. : sched_noop_wake<br><30> config:common filename:/hypervisor/common/sched_noop.c func:sched_noop_wake offset:42<br> reason:Casting operation to a pointer. : (void* to struct sched_noop_control*): ( struct sched_noop_control * ) obj -> sched_ctl -> priv<br><31> config:common filename:/hypervisor/common/sched_noop.c func:sched_noop_wake offset:42<br> reason:Casting operation on a pointer. : (void* to struct sched_noop_control*): ( struct sched_noop_control * ) obj -> sched_ctl -> priv<br><32> config:common filename:/hypervisor/common/sched_noop.c func: offset:52<br> reason:Function pointer is of wrong type.           : Return types differ; sched_noop.init_data: void, sched_noop_pick_next: struct thread_object*<br><33> config:common filename:/hypervisor/common/sched_noop.c func: offset:53<br> reason:Function pointer is of wrong type.           : Return types differ; sched_noop.pick_next: struct thread_object*, sched_noop_sleep: void<br><br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by wenlingz** [comment]
@HuiHuangShi please check MISRA-C

**Comment by HuiHuangShi** [comment]
24 new potential violations to the coding guideline detected. Please help check. Thanks!<br><1> config:part_config filename:/hypervisor/common/schedule.c func:deinit_thread_data offset:105<br> reason:Pointer param should be declared pointer to const. : obj<br><2> config:sharing_config filename:/hypervisor/common/schedule.c func:deinit_thread_data offset:105<br> reason:Pointer param should be declared pointer to const. : obj<br><3> config:sharing_config filename:/hypervisor/common/schedule.c func:deinit_thread_data offset:105<br> reason:Procedure is not called or referenced in code analysed. : deinit_thread_data<br><4> config:part_config filename:/hypervisor/common/schedule.c func:deinit_thread_data offset:105<br> reason:Procedure is not called or referenced in code analysed. : deinit_thread_data<br><5> config:common filename:/hypervisor/arch/x86/guest/vcpu.c func:launch_vcpu offset:741<br> reason:Type conversion without cast. :  (enum vm_state and enum vcpu_state): vcpu -> state =<br><6> config:common filename:/hypervisor/arch/x86/guest/vcpu.c func:launch_vcpu offset:741<br> reason:Use of underlying enum representation value. :  (enum vm_state and enum vcpu_state): vcpu -> state =<br><7> config:common filename:/hypervisor/common/sched_noop.c func:sched_noop_init offset:10<br> reason:Static procedure is not explicitly called in code analysed. : sched_noop_init<br><8> config:part_config filename:/hypervisor/common/sched_noop.c func:sched_noop_pick_next offset:18<br> reason:Pointer param should be declared pointer to const. : ctl<br><9> config:sharing_config filename:/hypervisor/common/sched_noop.c func:sched_noop_pick_next offset:18<br> reason:Pointer param should be declared pointer to const. : ctl<br><10> config:common filename:/hypervisor/common/sched_noop.c func:sched_noop_pick_next offset:18<br> reason:Static procedure is not explicitly called in code analysed. : sched_noop_pick_next<br><11> config:common filename:/hypervisor/common/sched_noop.c func:sched_noop_pick_next offset:20<br> reason:Casting operation to a pointer. : (void* to struct sched_noop_control*): ( struct sched_noop_control * ) ctl -> priv<br><12> config:common filename:/hypervisor/common/sched_noop.c func:sched_noop_pick_next offset:20<br> reason:Casting operation on a pointer. : (void* to struct sched_noop_control*): ( struct sched_noop_control * ) ctl -> priv<br><13> config:part_config filename:/hypervisor/common/sched_noop.c func:sched_noop_pick_next offset:28<br> reason:Local structure returned in function result. : next<br><14> config:sharing_config filename:/hypervisor/common/sched_noop.c func:sched_noop_pick_next offset:28<br> reason:Local structure returned in function result. : next<br><15> config:part_config filename:/hypervisor/common/sched_noop.c func:sched_noop_sleep offset:31<br> reason:Pointer param should be declared pointer to const. : obj<br><16> config:sharing_config filename:/hypervisor/common/sched_noop.c func:sched_noop_sleep offset:31<br> reason:Pointer param should be declared pointer to const. : obj<br><17> config:common filename:/hypervisor/common/sched_noop.c func:sched_noop_sleep offset:31<br> reason:Static procedure is not explicitly called in code analysed. : sched_noop_sleep<br><18> config:common filename:/hypervisor/common/sched_noop.c func:sched_noop_sleep offset:33<br> reason:Casting operation to a pointer. : (void* to struct sched_noop_control*): ( struct sched_noop_control * ) obj -> sched_ctl -> priv<br><19> config:common filename:/hypervisor/common/sched_noop.c func:sched_noop_sleep offset:33<br> reason:Casting operation on a pointer. : (void* to struct sched_noop_control*): ( struct sched_noop_control * ) obj -> sched_ctl -> priv<br><20> config:common filename:/hypervisor/common/sched_noop.c func:sched_noop_wake offset:40<br> reason:Static procedure is not explicitly called in code analysed. : sched_noop_wake<br><21> config:common filename:/hypervisor/common/sched_noop.c func:sched_noop_wake offset:42<br> reason:Casting operation to a pointer. : (void* to struct sched_noop_control*): ( struct sched_noop_control * ) obj -> sched_ctl -> priv<br><22> config:common filename:/hypervisor/common/sched_noop.c func:sched_noop_wake offset:42<br> reason:Casting operation on a pointer. : (void* to struct sched_noop_control*): ( struct sched_noop_control * ) obj -> sched_ctl -> priv<br><23> config:common filename:/hypervisor/common/sched_noop.c func: offset:52<br> reason:Function pointer is of wrong type.           : Return types differ; sched_noop.init_data: void, sched_noop_pick_next: struct thread_object*<br><24> config:common filename:/hypervisor/common/sched_noop.c func: offset:53<br> reason:Function pointer is of wrong type.           : Return types differ; sched_noop.pick_next: struct thread_object*, sched_noop_sleep: void<br><br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Pull request merged**
