### PR TITLE
doc: fix vhm_request doxygen comment

### PR DESCRIPTION
**Pull request by dbkinder**
Table contents weren't rendered correctly in
developer-guides/hld/hv-io-emulation.html, so
fix the doxygen comments.

Tracked-on: #1684

Signed-off-by: David B. Kinder <david.b.kinder@intel.com>

### CODE REVIEW

**Comment by HuiHuangShi** [comment]
2045 <br>The PR does not touch any hypervisor source file. Skip coding guideline checks.<br>

**Comment by eternalNight** [comment]
It look good to me. Thanks for fixing this!

**Comment by junjiemao1** [comment]
It looks good to me. Thanks for fixing this!

**Comment by dbkinder** [comment]
While I'd prefer a developer to merge this PR (since its in a .h file), let me know if it's OK for me to do this.

**Comment by dbkinder** [comment]
@hwang37 Is it OK for me to merge this change?

**Pull request merged**
