### PR TITLE
Fix address space of post launched rfc v2

### PR DESCRIPTION
**Pull request by taoyuhong**

### CODE REVIEW

**Comment by HuiHuangShi** [comment]
No new violations to the coding guideline detected.<br>No New Name Conflict<br>No New Function Declaration/Definition Mismatch

**Comment by iaGuoZhi** [comment]
Hi! @taoyuhong 
Have this problem fixed?
I have tried to post launch a RTVM in MaxTang WHL board(WHL-IPC-I5) wich ACRN version 2.0 . However I came across same error appeared in this issue.

boot_rtvm_error

I have already issued this problem https://github.com/projectacrn/acrn-hypervisor/issues/5970#issuecomment-826776579. Would you mind providing some suggestions to overcome this problem?

**Comment by taoyuhong** [comment]
My issue is OVMF can’t drive NVME ptdev at the pre-merge test env, but I can’t reproduce it on my whl-ipc-i7.
If you use /user/share/acrn/bios/OVMFD_debug.fd, you may see more serial output, and find out the where is the problem.
By the way, have you tried virtio-blk? In my case, vm can launche with virtio-blk device, because it is nvme issue.

**Comment by wenlingz** [comment]
@ywan170 please help approve this PR, thanks

**Review by ywan170 — APPROVED** [review]

**Pull request merged**
