### PR TITLE
hv: disable SMX and add missing unsupported MSRs

### PR DESCRIPTION
**Pull request by ZideChen0**
Need to merge these 2 patches together before both of them touch unsupported_msrs[] and NUM_UNSUPPORTED_MSRS.
Tracked-On: #1867
Signed-off-by: Zide Chen <zide.chen@intel.com>
Acked-by: Eddie Dong <eddie.dong@intel.com>

### CODE REVIEW

**Comment by HuiHuangShi** [comment]
2236<br>No new violations to the coding guideline detected.

**Comment by acrnsi** [comment]
Ok to verify

**Comment by HuiHuangShi** [comment]
2236<br>No new violations to the coding guideline detected.

**Comment by HuiHuangShi** [comment]
2236<br>No new violations to the coding guideline detected.

**Pull request merged**
