### PR TITLE
doc: add sphinx-tabs extension

### PR DESCRIPTION
**Pull request by dbkinder**
The sphinx-tabs extension let's us create a document that can
dynamically display alternate material based on clicking a tab, as used
in the Zephyr getting started guide:
https://docs.zephyrproject.org/latest/getting_started/index.html

Signed-off-by: David B. Kinder <david.b.kinder@intel.com>

### CODE REVIEW

**Comment by HuiHuangShi** [comment]
No new violations to the coding guideline detected.<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by dbkinder** [comment]
@NanlinXie @wenlingz As feared, updating the requirements.txt is not recognized by the CI system as a hint that new python packages need to be installed.  How do we coordinate updates to requirements.txt so the CI gets updated?

**Comment by dbkinder** [comment]
@NanlinXie @wenlingz When the CI docker image is updated with the sphinx-tabs package (as installed by the requirements.txt file here) can you force this PR to try again.  When it passes I'll know then I can continue and merge this PR.  Thanks.

**Comment by wenlingz** [comment]
> @NanlinXie @wenlingz When the CI docker image is updated with the sphinx-tabs package (as installed by the requirements.txt file here) can you force this PR to try again. When it passes I'll know then I can continue and merge this PR. Thanks.

OK

**Comment by leilu** [comment]
OK to verify

**Pull request merged**
