### PR TITLE
Config_tools: Update XML and save board xml when loading from config tool UI

### PR DESCRIPTION
**Pull request by Kunhui-Li**
1. For nuc11tnbi5 board,
    1) Add hybrid.xml, industry.xml, hybrid_rt.xml, logical_partition.xml and industry_launch_2uos.xml.
    2) Update nuc11tnbi5.xml for GSG.
2. Update tgl-rvp board xml.
3. Save the board xml into misc/config_tools/data/[board]/ when loading a new board from config tool UI.

### CODE REVIEW

**Comment by wenlingz** [comment]
OK to verify

**Comment by wenlingz** [comment]
@fyin1 please help approve this PR, thanks

**Review by NanlinXie — APPROVED** [review]

**Comment by gvancuts** [comment]
The upstream PR hasn't been merged yet (and shouldn't be). Why are we merging this?

**Comment by wenlingz** [comment]
> The upstream PR hasn't been merged yet (and shouldn't be). Why are we merging this?

@NanlinXie please help reply ,thanks

**Pull request merged**
