### PR TITLE
HV: guest Px Cx enablement for kbl nuc and apl nuc

### PR DESCRIPTION
**Pull request by jsun26intel**
- add px cx data for kbl nuc refresh;
- validate pstate by checking px ctl range;
- enforce Cx of apl nuc with SPACE_SYSTEM_IO;

Tracked-On: #3158

### CODE REVIEW

**Comment by acrnsi** [comment]
Ok to verify

**Comment by acrnsi** [comment]
OK to verify

**Comment by jsun26intel** [comment]
OK to verify

**Comment by HuiHuangShi** [comment]
out of time

**Comment by HuiHuangShi** [comment]
11 new potential violations to the coding guideline detected. Please help check. Thanks!
<1> config:sharing_config filename:/hypervisor/arch/x86/guest/pm.c func:validate_pstate offset:38
reason:Pointer not checked for null before use. : px_data
<2> config:part_config filename:/hypervisor/arch/x86/guest/pm.c func:validate_pstate offset:38
reason:Pointer not checked for null before use. : px_data
<3> config:common filename:/hypervisor/arch/x86/guest/pm.c func:validate_pstate offset:41
reason:Use of mixed mode arithmetic. : (unsigned char and signed char): ( px_data [ px_cnt - 1
<4> config:common filename:/hypervisor/arch/x86/cpu_state_tbl.c func: offset:113
reason:Struct field initialisation incorrect. : ('char' used, 'unsigned char' expected): sizeof ( ( cx_bxt ) [ 0 ] ) ) , cx_bxt } } , { "Intel(R) Atom(TM) Processor A3950 @ 1.60GHz"
<5> config:common filename:/hypervisor/arch/x86/cpu_state_tbl.c func: offset:117
reason:Use of sizeof on an array parameter.
<6> config:common filename:/hypervisor/arch/x86/cpu_state_tbl.c func: offset:121
reason:Struct field initialisation incorrect. : ('char' used, 'unsigned char' expected): sizeof ( ( cx_bxt ) [ 0 ] ) ) , cx_bxt } } , { "Intel(R) Celeron(R) CPU N3350 @ 1.10GHz"
<7> config:common filename:/hypervisor/arch/x86/cpu_state_tbl.c func: offset:125
reason:Use of sizeof on an array parameter.
<8> config:common filename:/hypervisor/arch/x86/cpu_state_tbl.c func: offset:125
reason:Array initialisation has insufficient items. : model_name[*]; given=41, expected=63
<9> config:common filename:/hypervisor/arch/x86/cpu_state_tbl.c func: offset:128
reason:Use of sizeof on an array parameter.
<10> config:common filename:/hypervisor/arch/x86/cpu_state_tbl.c func: offset:128
reason:Initialisation brace { } fault.
<11> config:common filename:/hypervisor/arch/x86/cpu_state_tbl.c func: offset:129
reason:Array initialisation has insufficient items. : cpu_state_tbl[*]; given=3, expected=5

No New Name Conflict

No New Function Declaration/Definition Mismatch

**Pull request merged**
