### PR TITLE
hv: fix string assigned to non const object

### PR DESCRIPTION
**Pull request by lifeix**
String should assigned to const object

Tracked-On: #861
Signed-off-by: Li, Fei1 <fei1.li@intel.com>

### CODE REVIEW

**Comment by dongyaozu** [comment]
Do we concluded for the usage of const?
Please ask Xiangyang to review and confirm

**Comment by lifeix** [comment]
@wuxyintel 
Please help to confirm. Thanks

**Comment by wuxyintel** [comment]
If the character or value pointed by a pointer  and this character or value is no change in its life cycle, "const" should be used for the corresponding pointer. This patch is fine to me.
Reviewed-by: xiangyang.wu@intel.com

**Comment by HuiHuangShi** [comment]
1994<br>No new violations to the coding guideline detected.

**Pull request merged**
