### PR TITLE
Patch for modularising ioapic.[c/h] and related files

### PR DESCRIPTION
**Pull request by rarindam**
This adds few functions to access the daata structures
defined inside ioapic.c. Removes the same data structures
from ioapic.h
Also this modifies some of the names of existing APIs to
conform to the ioapic module name.
Modified gsi_table identifier to gs_table_data, to avoid
a MISRA C Violation.

Tracked-On: #1842
Signed-off-by: Arindam Roy <arindam.roy@intel.com>

### CODE REVIEW

**Comment by acrnsi** [comment]
Ok to verify

**Comment by wenlingz** [comment]
@rarindam please rebase your code to fix conflict,thanks

**Comment by acrnsi** [comment]
Ok to verify

**Comment by dongyaozu** [comment]
@rarindam did u fix the conflict?

**Comment by rarindam** [comment]
Getting multiple merge conflicts locally too.

**Comment by rarindam** [comment]
Resolving the issue

**Comment by rarindam** [comment]
The branch is all messed up right now. Closing this. Submitting new one.

**Pull request closed without merging**
