### PR TITLE
Remove vtd dynamic allocation

### PR DESCRIPTION
**Pull request by totoroow**
v6 since v5:
	- remove dom_id field.
	- remove dmar_hdrh_unit_count.
	- export cpu_page structure and redefine
iommu_root_table&iommu_ctx_table

v5 since v4:
	- remove the new api for retrieving dmar count.
	- fix a potential bug in dmar looping.
	- check init_iommu()

v4 since v3:
    - remove domain id dynamic allocation.
    - export a new api for retrieving the dmar number.
    - fix a minor bug in v3 when memclr domain structure.

v3 since v2:
    - move iommu number check into hardware_detect_support()
    - more comments on domain index.

v2 since v1:
    - use predefine macros in Kconfig instead of defining a new one.
    - remove unnecessary bus_no and dmar_index check.
    - add a new patch for stripping iommu_domain dynamic allocations.

Tw (3):
  hv: vtd: remove dynamic page allocation for root&ctx table
  hv: vtd: remove dynamic allocation for dmar_drhd_rt
  hv: vtd: remove dynamic allocation for iommu_domain

Tracked-On: #861
Signed-off-by: Tw <wei.tan@intel.com>
Reviewed-by: Binbin Wu <binbin.wu@intel.com>
Acked-by: Eddie Dong <eddie.dong@intel.com>

### CODE REVIEW

**Comment by NanlinXie** [comment]
Can one of the admins verify this patch?

**Comment by totoroow** [comment]
Hold on, pls. There is a issue with this patch.

**Comment by totoroow** [comment]
This is an issue in 2nd commit: we can't move `init_iommu` before `interrupt_init`, as it will request irq for dmar unit. I have updated the patch to fix this.

**Comment by lijinxia** [comment]
OK to verify

**Comment by HuiHuangShi** [comment]
1661<br>6 new potential violations to the coding guideline detected. Please help check. Thanks!  <br><br>1.filename:/hypervisor/arch/x86/vtd.c&nbsp;&nbsp;function:vmid_to_domainid&nbsp;&nbsp;offset:165:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Literal value requires a U suffix.           : 1<br><br>2.filename:/hypervisor/arch/x86/vtd.c&nbsp;&nbsp;function:register_hrhd_units&nbsp;&nbsp;offset:178:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Signed/unsigned conversion without cast. :  (unsigned int and int): info -> drhd_count<br><br>3.filename:/hypervisor/arch/x86/vtd.c&nbsp;&nbsp;function:register_hrhd_units&nbsp;&nbsp;offset:178:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Literal value requires a U suffix.           : 0<br><br>4.filename:/hypervisor/arch/x86/vtd.c&nbsp;&nbsp;function:register_hrhd_units&nbsp;&nbsp;offset:194:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Potential side effect problem in expression. : dmar_drhd_units.lock<br><br>5.filename:/hypervisor/arch/x86/vtd.c&nbsp;&nbsp;function:destroy_iommu_domain&nbsp;&nbsp;offset:915:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:(void) missing for discarded return value.<br><br>6.filename:/hypervisor/arch/x86/vtd.c&nbsp;&nbsp;function:add_iommu_device&nbsp;&nbsp;offset:1033:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:No cast for widening complex int expression (MR). :  (unsigned short and unsigned long):  param  4<br><br>

**Comment by totoroow** [comment]
Update to fix the violation above. 

> 4.filename:/hypervisor/arch/x86/vtd.c  function:register_hrhd_units  offset:194:
       reason:Potential side effect problem in expression. : dmar_drhd_units.lock

There is no problem with this due to lock initialization.

**Comment by HuiHuangShi** [comment]
> Update to fix the violation above.
> 
> > 4.filename:/hypervisor/arch/x86/vtd.c  function:register_hrhd_units  offset:194:
> > reason:Potential side effect problem in expression. : dmar_drhd_units.lock
> 
> There is no problem with this due to lock initialization.

Yeah,it is false positive.

**Comment by HuiHuangShi** [comment]
1661<br>1 new potential violations to the coding guideline detected. Please help check. Thanks!  <br><br>1.filename:/hypervisor/arch/x86/vtd.c&nbsp;&nbsp;function:register_hrhd_units&nbsp;&nbsp;offset:194:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Potential side effect problem in expression. : dmar_drhd_units.lock<br><br>

**Comment by ClaudZhang1995** [comment]
Ready to merge

**Pull request merged**
