### PR TITLE
fix "use of single line comments(s) //"

### PR DESCRIPTION
**Pull request by HuiHuangShi**
Replace "//" with '/*','*/' couples.

Tracked-on:#861
Signed-off-by: Huihuang Shi <huihuang.shi@intel.com>
Acked-by: Eddie Dong <eddie.dong@intel.com>

### CODE REVIEW

**Comment by HuiHuangShi** [comment]
1494<br>No new violations to the coding guideline detected.

**Comment by HuiHuangShi** [comment]
1494<br>No new violations to the coding guideline detected.

**Comment by HuiHuangShi** [comment]
1494<br>No new violations to the coding guideline detected.

**Comment by ClaudZhang1995** [comment]
Ready to merge

**Pull request merged**
