### PR TITLE
HV: parse seed from ABL

### PR DESCRIPTION
**Pull request by YadongQi**
ABL pass seed_lists to HV through different interface/structures.
So, in this patch, add interface to retrieve seed from ABL and refactor
the seed parsing logic.

Tracked-On: #1488
Signed-off-by: Qi Yadong <yadong.qi@intel.com>
Acked-by: Zhu Bing <bing.zhu@intel.com>

### CODE REVIEW

**Comment by HuiHuangShi** [comment]
1490<br>29 new potential violations to the coding guideline detected. Please help check. Thanks!  <br><br>1.filename:/hypervisor/boot/sbl/sbl_seed_parse.c&nbsp;&nbsp;function:parse_seed_list_sbl&nbsp;&nbsp;offset:69:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Casting operation to a pointer. : (unsigned char* to struct seed_entry*): ( struct seed_entry * ) ( ( uint8_t * ) seed_hob + sizeof ( struct seed_list_hob ) )<br><br>2.filename:/hypervisor/boot/sbl/sbl_seed_parse.c&nbsp;&nbsp;function:parse_seed_list_sbl&nbsp;&nbsp;offset:69:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Cast to an unrelated type. : (unsigned char* to struct seed_entry*): ( struct seed_entry * ) ( ( uint8_t * ) seed_hob + sizeof ( struct seed_list_hob ) )<br><br>3.filename:/hypervisor/boot/sbl/sbl_seed_parse.c&nbsp;&nbsp;function:parse_seed_list_sbl&nbsp;&nbsp;offset:69:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Casting operation on a pointer. : (unsigned char* to struct seed_entry*): ( struct seed_entry * ) ( ( uint8_t * ) seed_hob + sizeof ( struct seed_list_hob ) )<br><br>4.filename:/hypervisor/boot/sbl/sbl_seed_parse.c&nbsp;&nbsp;function:parse_seed_list_sbl&nbsp;&nbsp;offset:90:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Implicit conversion: actual to formal param (MR). :  (unsigned char and void):  param  3<br><br>5.filename:/hypervisor/boot/sbl/sbl_seed_parse.c&nbsp;&nbsp;function:parse_seed_list_sbl&nbsp;&nbsp;offset:97:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Implicit conversion: actual to formal param (MR). :  (unsigned char and void):  param  1<br><br>6.filename:/hypervisor/boot/sbl/sbl_seed_parse.c&nbsp;&nbsp;function:parse_seed_list_sbl&nbsp;&nbsp;offset:100:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Casting operation on a pointer. : (unsigned char* to struct seed_entry*): ( struct seed_entry * ) ( ( uint8_t * ) entry + entry -> seed_entry_size )<br><br>7.filename:/hypervisor/boot/sbl/sbl_seed_parse.c&nbsp;&nbsp;function:parse_seed_list_sbl&nbsp;&nbsp;offset:100:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Cast to an unrelated type. : (unsigned char* to struct seed_entry*): ( struct seed_entry * ) ( ( uint8_t * ) entry + entry -> seed_entry_size )<br><br>8.filename:/hypervisor/boot/sbl/sbl_seed_parse.c&nbsp;&nbsp;function:parse_seed_list_sbl&nbsp;&nbsp;offset:100:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Casting operation to a pointer. : (unsigned char* to struct seed_entry*): ( struct seed_entry * ) ( ( uint8_t * ) entry + entry -> seed_entry_size )<br><br>9.filename:/hypervisor/boot/sbl/sbl_seed_parse.c&nbsp;&nbsp;function:parse_seed_list_sbl&nbsp;&nbsp;offset:104:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Implicit conversion: actual to formal param (MR). :  (struct seed_info and void):  param  1<br><br>10.filename:/hypervisor/boot/sbl/sbl_seed_parse.c&nbsp;&nbsp;function:parse_seed_list_sbl&nbsp;&nbsp;offset:105:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Implicit conversion: actual to formal param (MR). :  (struct seed_info and void):  param  1<br><br>11.filename:/hypervisor/boot/sbl/sbl_seed_parse.c&nbsp;&nbsp;function:parse_seed_list_sbl&nbsp;&nbsp;offset:110:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Implicit conversion: actual to formal param (MR). :  (struct seed_info and void):  param  1<br><br>12.filename:/hypervisor/boot/sbl/sbl_seed_parse.c&nbsp;&nbsp;function:sbl_seed_parse&nbsp;&nbsp;offset:160:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Casting operation on a pointer. : (void* to struct image_boot_params*): ( struct image_boot_params * ) param_addr<br><br>13.filename:/hypervisor/boot/sbl/sbl_seed_parse.c&nbsp;&nbsp;function:sbl_seed_parse&nbsp;&nbsp;offset:160:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Casting operation to a pointer. : (void* to struct image_boot_params*): ( struct image_boot_params * ) param_addr<br><br>14.filename:/hypervisor/boot/sbl/sbl_seed_parse.c&nbsp;&nbsp;function:sbl_seed_parse&nbsp;&nbsp;offset:161:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Casting operation on a pointer. : (void* to struct seed_list_hob*): ( struct seed_list_hob * ) hpa2hva ( boot_params -> p_seed_list )<br><br>15.filename:/hypervisor/boot/sbl/sbl_seed_parse.c&nbsp;&nbsp;function:sbl_seed_parse&nbsp;&nbsp;offset:161:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Casting operation to a pointer. : (void* to struct seed_list_hob*): ( struct seed_list_hob * ) hpa2hva ( boot_params -> p_seed_list )<br><br>16.filename:/hypervisor/boot/sbl/sbl_seed_parse.c&nbsp;&nbsp;function:sbl_seed_parse&nbsp;&nbsp;offset:181:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Implicit conversion: actual to formal param (MR). :  (char and unsigned char):  param  2<br><br>17.filename:/hypervisor/boot/sbl/abl_seed_parse.c&nbsp;&nbsp;function:parse_seed_list_abl&nbsp;&nbsp;offset:32:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Casting operation to a pointer. : (void* to struct dev_sec_info*): ( struct dev_sec_info * ) param_addr<br><br>18.filename:/hypervisor/boot/sbl/abl_seed_parse.c&nbsp;&nbsp;function:parse_seed_list_abl&nbsp;&nbsp;offset:32:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Casting operation on a pointer. : (void* to struct dev_sec_info*): ( struct dev_sec_info * ) param_addr<br><br>19.filename:/hypervisor/boot/sbl/abl_seed_parse.c&nbsp;&nbsp;function:parse_seed_list_abl&nbsp;&nbsp;offset:62:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Implicit conversion: actual to formal param (MR). :  (struct seed_info and void):  param  1<br><br>20.filename:/hypervisor/boot/sbl/abl_seed_parse.c&nbsp;&nbsp;function:parse_seed_list_abl&nbsp;&nbsp;offset:65:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Implicit conversion: actual to formal param (MR). :  (unsigned char and void):  param  3<br><br>21.filename:/hypervisor/boot/sbl/abl_seed_parse.c&nbsp;&nbsp;function:parse_seed_list_abl&nbsp;&nbsp;offset:65:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Implicit conversion: actual to formal param (MR). :  (unsigned char and void):  param  1<br><br>22.filename:/hypervisor/boot/sbl/abl_seed_parse.c&nbsp;&nbsp;function:parse_seed_list_abl&nbsp;&nbsp;offset:71:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:No brackets to then/else.<br><br>23.filename:/hypervisor/boot/sbl/abl_seed_parse.c&nbsp;&nbsp;function:parse_seed_list_abl&nbsp;&nbsp;offset:73:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Implicit conversion: actual to formal param (MR). :  (unsigned char and void):  param  1<br><br>24.filename:/hypervisor/boot/sbl/abl_seed_parse.c&nbsp;&nbsp;function:parse_seed_list_abl&nbsp;&nbsp;offset:77:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Narrower int conversion without cast. :  (unsigned int and unsigned char):  param  2<br><br>25.filename:/hypervisor/boot/sbl/abl_seed_parse.c&nbsp;&nbsp;function:parse_seed_list_abl&nbsp;&nbsp;offset:77:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Implicit conversion: actual to formal param (MR). :  (struct seed_info and void):  param  1<br><br>26.filename:/hypervisor/boot/sbl/abl_seed_parse.c&nbsp;&nbsp;function:parse_seed_list_abl&nbsp;&nbsp;offset:77:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Implicit conversion: actual to formal param (MR). :  (unsigned int and unsigned char):  param  2<br><br>27.filename:/hypervisor/boot/sbl/abl_seed_parse.c&nbsp;&nbsp;function:parse_seed_list_abl&nbsp;&nbsp;offset:78:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Implicit conversion: actual to formal param (MR). :  (struct seed_info and void):  param  1<br><br>28.filename:/hypervisor/boot/sbl/abl_seed_parse.c&nbsp;&nbsp;function:parse_seed_list_abl&nbsp;&nbsp;offset:82:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Implicit conversion: actual to formal param (MR). :  (struct seed_info and void):  param  1<br><br>29.filename:/hypervisor/boot/sbl/abl_seed_parse.c&nbsp;&nbsp;function:abl_seed_parse&nbsp;&nbsp;offset:141:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Implicit conversion: actual to formal param (MR). :  (char and unsigned char):  param  2<br><br>

**Comment by HuiHuangShi** [comment]
1490<br>18 new potential violations to the coding guideline detected. Please help check. Thanks!  <br><br>1.filename:/hypervisor/boot/sbl/sbl_seed_parse.c&nbsp;&nbsp;function:parse_seed_list_sbl&nbsp;&nbsp;offset:69:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Casting operation to a pointer. : (unsigned char* to struct seed_entry*): ( struct seed_entry * ) ( ( uint8_t * ) seed_hob + sizeof ( struct seed_list_hob ) )<br><br>2.filename:/hypervisor/boot/sbl/sbl_seed_parse.c&nbsp;&nbsp;function:parse_seed_list_sbl&nbsp;&nbsp;offset:69:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Cast to an unrelated type. : (unsigned char* to struct seed_entry*): ( struct seed_entry * ) ( ( uint8_t * ) seed_hob + sizeof ( struct seed_list_hob ) )<br><br>3.filename:/hypervisor/boot/sbl/sbl_seed_parse.c&nbsp;&nbsp;function:parse_seed_list_sbl&nbsp;&nbsp;offset:69:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Casting operation on a pointer. : (unsigned char* to struct seed_entry*): ( struct seed_entry * ) ( ( uint8_t * ) seed_hob + sizeof ( struct seed_list_hob ) )<br><br>4.filename:/hypervisor/boot/sbl/sbl_seed_parse.c&nbsp;&nbsp;function:parse_seed_list_sbl&nbsp;&nbsp;offset:90:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Cast from integral type to pointer. : (unsigned char to void*): seed<br><br>5.filename:/hypervisor/boot/sbl/sbl_seed_parse.c&nbsp;&nbsp;function:parse_seed_list_sbl&nbsp;&nbsp;offset:97:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Implicit conversion: actual to formal param (MR). :  (unsigned char and void):  param  1<br><br>6.filename:/hypervisor/boot/sbl/sbl_seed_parse.c&nbsp;&nbsp;function:parse_seed_list_sbl&nbsp;&nbsp;offset:100:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Casting operation on a pointer. : (unsigned char* to struct seed_entry*): ( struct seed_entry * ) ( ( uint8_t * ) entry + entry -> seed_entry_size )<br><br>7.filename:/hypervisor/boot/sbl/sbl_seed_parse.c&nbsp;&nbsp;function:parse_seed_list_sbl&nbsp;&nbsp;offset:100:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Cast to an unrelated type. : (unsigned char* to struct seed_entry*): ( struct seed_entry * ) ( ( uint8_t * ) entry + entry -> seed_entry_size )<br><br>8.filename:/hypervisor/boot/sbl/sbl_seed_parse.c&nbsp;&nbsp;function:parse_seed_list_sbl&nbsp;&nbsp;offset:100:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Casting operation to a pointer. : (unsigned char* to struct seed_entry*): ( struct seed_entry * ) ( ( uint8_t * ) entry + entry -> seed_entry_size )<br><br>9.filename:/hypervisor/boot/sbl/sbl_seed_parse.c&nbsp;&nbsp;function:sbl_seed_parse&nbsp;&nbsp;offset:160:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Casting operation on a pointer. : (void* to struct image_boot_params*): ( struct image_boot_params * ) param_addr<br><br>10.filename:/hypervisor/boot/sbl/sbl_seed_parse.c&nbsp;&nbsp;function:sbl_seed_parse&nbsp;&nbsp;offset:160:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Casting operation to a pointer. : (void* to struct image_boot_params*): ( struct image_boot_params * ) param_addr<br><br>11.filename:/hypervisor/boot/sbl/sbl_seed_parse.c&nbsp;&nbsp;function:sbl_seed_parse&nbsp;&nbsp;offset:161:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Casting operation on a pointer. : (void* to struct seed_list_hob*): ( struct seed_list_hob * ) hpa2hva ( boot_params -> p_seed_list )<br><br>12.filename:/hypervisor/boot/sbl/sbl_seed_parse.c&nbsp;&nbsp;function:sbl_seed_parse&nbsp;&nbsp;offset:161:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Casting operation to a pointer. : (void* to struct seed_list_hob*): ( struct seed_list_hob * ) hpa2hva ( boot_params -> p_seed_list )<br><br>13.filename:/hypervisor/boot/sbl/sbl_seed_parse.c&nbsp;&nbsp;function:sbl_seed_parse&nbsp;&nbsp;offset:181:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Implicit conversion: actual to formal param (MR). :  (char and unsigned char):  param  2<br><br>14.filename:/hypervisor/boot/sbl/abl_seed_parse.c&nbsp;&nbsp;function:parse_seed_list_abl&nbsp;&nbsp;offset:32:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Casting operation to a pointer. : (void* to struct dev_sec_info*): ( struct dev_sec_info * ) param_addr<br><br>15.filename:/hypervisor/boot/sbl/abl_seed_parse.c&nbsp;&nbsp;function:parse_seed_list_abl&nbsp;&nbsp;offset:32:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Casting operation on a pointer. : (void* to struct dev_sec_info*): ( struct dev_sec_info * ) param_addr<br><br>16.filename:/hypervisor/boot/sbl/abl_seed_parse.c&nbsp;&nbsp;function:parse_seed_list_abl&nbsp;&nbsp;offset:65:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Implicit conversion: actual to formal param (MR). :  (unsigned char and void):  param  3<br><br>17.filename:/hypervisor/boot/sbl/abl_seed_parse.c&nbsp;&nbsp;function:parse_seed_list_abl&nbsp;&nbsp;offset:74:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Implicit conversion: actual to formal param (MR). :  (unsigned char and void):  param  1<br><br>18.filename:/hypervisor/boot/sbl/abl_seed_parse.c&nbsp;&nbsp;function:abl_seed_parse&nbsp;&nbsp;offset:142:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Implicit conversion: actual to formal param (MR). :  (char and unsigned char):  param  2<br><br>

**Comment by HuiHuangShi** [comment]
1490<br>18 new potential violations to the coding guideline detected. Please help check. Thanks!  <br><br>1.filename:/hypervisor/boot/sbl/sbl_seed_parse.c&nbsp;&nbsp;function:parse_seed_list_sbl&nbsp;&nbsp;offset:69:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Casting operation to a pointer. : (unsigned char* to struct seed_entry*): ( struct seed_entry * ) ( ( uint8_t * ) seed_hob + sizeof ( struct seed_list_hob ) )<br><br>2.filename:/hypervisor/boot/sbl/sbl_seed_parse.c&nbsp;&nbsp;function:parse_seed_list_sbl&nbsp;&nbsp;offset:69:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Cast to an unrelated type. : (unsigned char* to struct seed_entry*): ( struct seed_entry * ) ( ( uint8_t * ) seed_hob + sizeof ( struct seed_list_hob ) )<br><br>3.filename:/hypervisor/boot/sbl/sbl_seed_parse.c&nbsp;&nbsp;function:parse_seed_list_sbl&nbsp;&nbsp;offset:69:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Casting operation on a pointer. : (unsigned char* to struct seed_entry*): ( struct seed_entry * ) ( ( uint8_t * ) seed_hob + sizeof ( struct seed_list_hob ) )<br><br>4.filename:/hypervisor/boot/sbl/sbl_seed_parse.c&nbsp;&nbsp;function:parse_seed_list_sbl&nbsp;&nbsp;offset:90:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Cast from integral type to pointer. : (unsigned char to void*): seed<br><br>5.filename:/hypervisor/boot/sbl/sbl_seed_parse.c&nbsp;&nbsp;function:parse_seed_list_sbl&nbsp;&nbsp;offset:97:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Implicit conversion: actual to formal param (MR). :  (unsigned char and void):  param  1<br><br>6.filename:/hypervisor/boot/sbl/sbl_seed_parse.c&nbsp;&nbsp;function:parse_seed_list_sbl&nbsp;&nbsp;offset:100:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Casting operation on a pointer. : (unsigned char* to struct seed_entry*): ( struct seed_entry * ) ( ( uint8_t * ) entry + entry -> seed_entry_size )<br><br>7.filename:/hypervisor/boot/sbl/sbl_seed_parse.c&nbsp;&nbsp;function:parse_seed_list_sbl&nbsp;&nbsp;offset:100:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Cast to an unrelated type. : (unsigned char* to struct seed_entry*): ( struct seed_entry * ) ( ( uint8_t * ) entry + entry -> seed_entry_size )<br><br>8.filename:/hypervisor/boot/sbl/sbl_seed_parse.c&nbsp;&nbsp;function:parse_seed_list_sbl&nbsp;&nbsp;offset:100:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Casting operation to a pointer. : (unsigned char* to struct seed_entry*): ( struct seed_entry * ) ( ( uint8_t * ) entry + entry -> seed_entry_size )<br><br>9.filename:/hypervisor/boot/sbl/sbl_seed_parse.c&nbsp;&nbsp;function:sbl_seed_parse&nbsp;&nbsp;offset:160:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Casting operation on a pointer. : (void* to struct image_boot_params*): ( struct image_boot_params * ) param_addr<br><br>10.filename:/hypervisor/boot/sbl/sbl_seed_parse.c&nbsp;&nbsp;function:sbl_seed_parse&nbsp;&nbsp;offset:160:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Casting operation to a pointer. : (void* to struct image_boot_params*): ( struct image_boot_params * ) param_addr<br><br>11.filename:/hypervisor/boot/sbl/sbl_seed_parse.c&nbsp;&nbsp;function:sbl_seed_parse&nbsp;&nbsp;offset:161:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Casting operation on a pointer. : (void* to struct seed_list_hob*): ( struct seed_list_hob * ) hpa2hva ( boot_params -> p_seed_list )<br><br>12.filename:/hypervisor/boot/sbl/sbl_seed_parse.c&nbsp;&nbsp;function:sbl_seed_parse&nbsp;&nbsp;offset:161:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Casting operation to a pointer. : (void* to struct seed_list_hob*): ( struct seed_list_hob * ) hpa2hva ( boot_params -> p_seed_list )<br><br>13.filename:/hypervisor/boot/sbl/sbl_seed_parse.c&nbsp;&nbsp;function:sbl_seed_parse&nbsp;&nbsp;offset:181:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Implicit conversion: actual to formal param (MR). :  (char and unsigned char):  param  2<br><br>14.filename:/hypervisor/boot/sbl/abl_seed_parse.c&nbsp;&nbsp;function:parse_seed_list_abl&nbsp;&nbsp;offset:32:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Casting operation to a pointer. : (void* to struct dev_sec_info*): ( struct dev_sec_info * ) param_addr<br><br>15.filename:/hypervisor/boot/sbl/abl_seed_parse.c&nbsp;&nbsp;function:parse_seed_list_abl&nbsp;&nbsp;offset:32:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Casting operation on a pointer. : (void* to struct dev_sec_info*): ( struct dev_sec_info * ) param_addr<br><br>16.filename:/hypervisor/boot/sbl/abl_seed_parse.c&nbsp;&nbsp;function:parse_seed_list_abl&nbsp;&nbsp;offset:65:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Implicit conversion: actual to formal param (MR). :  (unsigned char and void):  param  3<br><br>17.filename:/hypervisor/boot/sbl/abl_seed_parse.c&nbsp;&nbsp;function:parse_seed_list_abl&nbsp;&nbsp;offset:74:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Implicit conversion: actual to formal param (MR). :  (unsigned char and void):  param  1<br><br>18.filename:/hypervisor/boot/sbl/abl_seed_parse.c&nbsp;&nbsp;function:abl_seed_parse&nbsp;&nbsp;offset:142:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Implicit conversion: actual to formal param (MR). :  (char and unsigned char):  param  2<br><br>

**Comment by ClaudZhang1995** [comment]
Ready to merge

**Pull request merged**
