### PR TITLE
 PCI vUART support in HV for EB Test

### PR DESCRIPTION
**Pull request by taoyuhong**
How to use:
Add pci-vuart in vm_config. Because PCI vUART are also virtual pci devices, their config information are in acrn_vm_pci_dev_config, just like that:

struct acrn_vm_pci_dev_config vm0_pci_devs[] = {
           {
                   .emu_type = PCI_DEV_TYPE_HVEMUL,
                   .vbdf.bits = {.b = 0x00U, .d = 0x04U, .f = 0x00U},
                   .vdev_ops = &vuart_pci_ops,
                   .vbar_base[0] = 0x80001000, /*MMIO bar*/
                   .vbar_base[1] = 0x80002000, /*MSIX bar*/
                   .vuart_idx = 2,
                   .t_vuart.vm_id = 1U,
                   .t_vuart.vuart_id = 1U,
           },
        }

If create for post-launched VM, use '-s,<slot>,uart,vuart_idx:<val>' acrn-dm option

### CODE REVIEW

**Comment by wenlingz** [comment]
@taoyuhong  please check your code, build fail:

linux/acrn-devicemodel/5414-1603681351/build/devicemodel/log/disk_logger.o
| hw/pci/uart.c: In function 'pci_uart_init':
| hw/pci/uart.c:117:44: error: 'PAGE_SIZE_4K' undeclared (first use in this function)
|   117 |   pci_emul_alloc_bar(dev, 0, PCIBAR_MEM32, PAGE_SIZE_4K);
|       |                                            ^~~~~~~~~~~~
| hw/pci/uart.c:117:44: note: each undeclared identifier is reported only once for each function it appears in
| Makefile:230: recipe for target '/home/meta-acrn/workspace/build/master-acrn-sos/work/corei7-64-oe-linux/acrn-devicemodel/5414-1603681351/build/devicemodel/hw/pci/uart.o' failed
| make[1]: *** [/home/meta-acrn/workspace/build/master-acrn-sos/work/corei7-64-oe-linux/acrn-devicemodel/5414-1603681351/build/devicemodel/hw/pci/uart.o] Error 1
| make[1]: *** Waiting for unfinished jobs....
| make[1]: Leaving directory '/home/meta-acrn/workspace/build/master-acrn-sos/work/corei7-64-oe-linux/acrn-devicemodel/5414-1603681351/git/devicemodel'
| Makefile:177: recipe for target 'devicemodel' failed
| make: *** [devicemodel] Error 2
| WARNING: /home/meta-acrn/workspace/build/master-acrn-sos/work/corei7-64-oe-linux/acrn-devicemodel/5414-1603681351/temp/run.do_compile.1352:1 exit 1 from 'exit 1'
| 
NOTE: recipe acrn-devicemodel-5414-1603681351: task do_compile: Failed
ERROR: Task (/home/meta-acrn/workspace/meta-acrn/recipes-core/acrn/acrn-devicemodel.bb:do_compile) failed with exit code '1'
NOTE: recipe acrn-tools-5414-1603681351: task do_package: Succeeded
NOTE: recipe acrn-hypervisor-5414-1603681351: task do_compile: Succeeded
NOTE: Tasks Summary: Attempted 2012 tasks of which 1969 didn't need to be rerun and 1 failed.

Summary: 1 task failed:
  /home/meta-acrn/workspace/meta-acrn/recipes-core/acrn/acrn-devicemodel.bb:do_compile
Summary: There were 2 ERROR messages shown, returning a non-zero exit code.
++ upload /home/acrn/workspace/workspace/acrn-hypervisor-premerge-yocto-build-image_sp/artifact/5414 sit-

**Comment by wenlingz** [comment]
@ywan170 please help approve this PR, thanks

**Comment by ywan170** [comment]
The formal patches are still under review in mailing list. This PR is just for EB testing.

**Comment by taoyuhong** [comment]
Just for EB, real PR is #5440

**Pull request closed without merging**
