### PR TITLE
doc: update hld-security verified boot section

### PR DESCRIPTION
**Pull request by yonghuah**
1. Remove vSBL description
2. Add UEFI bootflow description.

Signed-off-by: Yonghua Huang <yonghua.huang@intel.com>

### CODE REVIEW

**Comment by yonghuah** [comment]
@fyin1  can help to review ? thanks.

**Comment by yonghuah** [comment]
@fyin1  have removed ABL related descriptions, please review, thanks.

**Comment by deb-intel** [comment]
@yonghuah, this PR has conflicts and cannot be merged until you resolve them.

**Comment by yonghuah** [comment]
@NanlinXie  have  updated the PR to fix conflict.

**Comment by acrnsi** [comment]
OK to verfiy

**Comment by NanlinXie** [comment]
@deb-intel , Could you help to check and merge this PR, thanks!

**Pull request merged**
