### PR TITLE
HV: enable acpi pm1a register info fixup

### PR DESCRIPTION
**Pull request by jsun26intel**
Previously ACPI PM1A register info was hardcoded to 0 in HV for generic boards, but SOS still can know the real PM1A info so the system would hang if user trigger S3 in SOS. Enabling PM1A register info fixup will let HV be able to intercept the operation on PM1A and then make basic function of S3 work for
all boards;

Also, the MACRO of CONFIG_CONSTANT_ACPI will be defined per scenario usage, so move it from Kconfig to vm_configurations.h;

Tracked-On: #2291

Signed-off-by: Victor Sun <victor.sun@intel.com>
Acked-by: Eddie Dong <eddie.dong@intel.com>

### CODE REVIEW

**Comment by wenlingz** [comment]
@jsun26intel please check your code, build fail
make -C /workspace/acrn-hypervisor/efi-stub HV_OBJDIR=/workspace/acrn-hypervisor/build/hypervisor EFI_OBJDIR=/workspace/acrn-hypervisor/build/efi-stub
make[1]: Entering directory '/workspace/acrn-hypervisor/efi-stub'
[ ! -e /workspace/acrn-hypervisor/build/efi-stub/boot.o ] && mkdir -p /workspace/acrn-hypervisor/build/efi-stub/; \
cc  -I/workspace/acrn-hypervisor/build/hypervisor/include -I. -c -I. -I.. -I../hypervisor/include/arch/x86/guest -I/usr/include/efi -I/usr/include/efi/x86_64 -I../hypervisor/include/public -I../hypervisor/include/lib -I../hypervisor/bsp/include/ -DEFI_FUNCTION_WRAPPER -fPIC -fshort-wchar -ffreestanding -Wall -I../fs/ -Dx86_64 -O2 -I../hypervisor/include/arch/x86 -include config.h -mno-mmx -mno-sse -mno-sse2 -mno-80387 -mno-fp-ret-in-387 -mno-red-zone  boot.c -o /workspace/acrn-hypervisor/build/efi-stub/boot.o
In file included from ../hypervisor/bsp/include/firmware_uefi.h:10,
                 from boot.c:40:
../hypervisor/bsp/include/firmware.h:11:10: fatal error: vm_configurations.h: No such file or directory
 #include <vm_configurations.h>
          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[1]: *** [Makefile:114: /workspace/acrn-hypervisor/build/efi-stub/boot.o] Error 1
make[1]: Leaving directory '/workspace/acrn-hypervisor/efi-stub'
make: *** [Makefile:34: hypervisor] Error 2
Build step 'Execute shell' marked build as failure

**Comment by HuiHuangShi** [comment]
11 new potential violations to the coding guideline detected. Please help check. Thanks!<br><1> config:common filename:/hypervisor/boot/acpi.c func:get_acpi_dt_gas offset:384<br> reason:Cast to an unrelated type. : (unsigned char* to struct packed_gas*): ( struct packed_gas * ) ( dt_addr + dt_offset )<br><2> config:common filename:/hypervisor/boot/acpi.c func:get_acpi_dt_gas offset:384<br> reason:Casting operation to a pointer. : (unsigned char* to struct packed_gas*): ( struct packed_gas * ) ( dt_addr + dt_offset )<br><3> config:common filename:/hypervisor/boot/acpi.c func:get_acpi_dt_gas offset:384<br> reason:Casting operation on a pointer. : (unsigned char* to struct packed_gas*): ( struct packed_gas * ) ( dt_addr + dt_offset )<br><4> config:sharing_config filename:/hypervisor/boot/acpi.c func:get_facs_table offset:394<br> reason:Pointer param should be declared pointer to const. : facp_addr<br><5> config:sharing_config filename:/hypervisor/boot/acpi.c func:acpi_fixup offset:435<br> reason:Pointer not checked for null before use. : sx_data<br><6> config:common filename:/hypervisor/boot/acpi.c func:acpi_fixup offset:442<br> reason:Casting operation to a pointer. : (unsigned char* to unsigned int*): ( uint32_t * ) ( facs_addr + 12U )<br><7> config:common filename:/hypervisor/boot/acpi.c func:acpi_fixup offset:442<br> reason:Casting operation on a pointer. : (unsigned char* to unsigned int*): ( uint32_t * ) ( facs_addr + 12U )<br><8> config:common filename:/hypervisor/boot/acpi.c func:acpi_fixup offset:443<br> reason:Casting operation to a pointer. : (unsigned char* to unsigned long*): ( uint64_t * ) ( facs_addr + 24U )<br><9> config:common filename:/hypervisor/boot/acpi.c func:acpi_fixup offset:443<br> reason:Casting operation on a pointer. : (unsigned char* to unsigned long*): ( uint64_t * ) ( facs_addr + 24U )<br><10> config:part_config filename:/hypervisor/arch/x86/guest/pm.c func:vm_load_pm_s_state offset:106<br> reason:Pointer not checked for null before use. : sx_data<br><11> config:sharing_config filename:/hypervisor/arch/x86/guest/pm.c func:vm_load_pm_s_state offset:106<br> reason:Pointer not checked for null before use. : sx_data<br><br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by HuiHuangShi** [comment]
12 new potential violations to the coding guideline detected. Please help check. Thanks!<br><1> config:sharing_config filename:/hypervisor/boot/acpi.c func:get_acpi_dt_gas offset:384<br> reason:Cast to an unrelated type. : (unsigned char* to struct packed_gas*): ( struct packed_gas * ) ( dt_addr + dt_offset )<br><2> config:sharing_config filename:/hypervisor/boot/acpi.c func:get_acpi_dt_gas offset:384<br> reason:Casting operation to a pointer. : (unsigned char* to struct packed_gas*): ( struct packed_gas * ) ( dt_addr + dt_offset )<br><3> config:sharing_config filename:/hypervisor/boot/acpi.c func:get_acpi_dt_gas offset:384<br> reason:Casting operation on a pointer. : (unsigned char* to struct packed_gas*): ( struct packed_gas * ) ( dt_addr + dt_offset )<br><4> config:sharing_config filename:/hypervisor/boot/acpi.c func:get_facs_table offset:394<br> reason:Pointer param should be declared pointer to const. : facp_addr<br><5> config:sharing_config filename:/hypervisor/boot/acpi.c func:acpi_fixup offset:435<br> reason:Pointer not checked for null before use. : sx_data<br><6> config:sharing_config filename:/hypervisor/boot/acpi.c func:acpi_fixup offset:442<br> reason:Casting operation to a pointer. : (unsigned char* to unsigned int*): ( uint32_t * ) ( facs_addr + 12U )<br><7> config:sharing_config filename:/hypervisor/boot/acpi.c func:acpi_fixup offset:442<br> reason:Casting operation on a pointer. : (unsigned char* to unsigned int*): ( uint32_t * ) ( facs_addr + 12U )<br><8> config:sharing_config filename:/hypervisor/boot/acpi.c func:acpi_fixup offset:443<br> reason:Casting operation to a pointer. : (unsigned char* to unsigned long*): ( uint64_t * ) ( facs_addr + 24U )<br><9> config:sharing_config filename:/hypervisor/boot/acpi.c func:acpi_fixup offset:443<br> reason:Casting operation on a pointer. : (unsigned char* to unsigned long*): ( uint64_t * ) ( facs_addr + 24U )<br><10> config:sharing_config filename:/hypervisor/arch/x86/guest/pm.c func:vm_load_pm_s_state offset:106<br> reason:Pointer not checked for null before use. : sx_data<br><11> config:part_config filename:/hypervisor/arch/x86/guest/pm.c func:vm_load_pm_s_state offset:106<br> reason:Pointer not checked for null before use. : sx_data<br><12> config:common filename:/hypervisor/boot/include/acpi.h func: offset:12<br> reason:Struct/union not completely specified.       : ioapic_info<br><br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by HuiHuangShi** [comment]
11 new potential violations to the coding guideline detected. Please help check. Thanks!<br><1> config:sharing_config filename:/hypervisor/boot/acpi.c func:get_acpi_dt_gas offset:384<br> reason:Cast to an unrelated type. : (unsigned char* to struct packed_gas*): ( struct packed_gas * ) ( dt_addr + dt_offset )<br><2> config:sharing_config filename:/hypervisor/boot/acpi.c func:get_acpi_dt_gas offset:384<br> reason:Casting operation to a pointer. : (unsigned char* to struct packed_gas*): ( struct packed_gas * ) ( dt_addr + dt_offset )<br><3> config:sharing_config filename:/hypervisor/boot/acpi.c func:get_acpi_dt_gas offset:384<br> reason:Casting operation on a pointer. : (unsigned char* to struct packed_gas*): ( struct packed_gas * ) ( dt_addr + dt_offset )<br><4> config:sharing_config filename:/hypervisor/boot/acpi.c func:acpi_fixup offset:435<br> reason:Pointer not checked for null before use. : sx_data<br><5> config:sharing_config filename:/hypervisor/boot/acpi.c func:acpi_fixup offset:442<br> reason:Casting operation to a pointer. : (unsigned char* to unsigned int*): ( uint32_t * ) ( facs_addr + 12U )<br><6> config:sharing_config filename:/hypervisor/boot/acpi.c func:acpi_fixup offset:442<br> reason:Casting operation on a pointer. : (unsigned char* to unsigned int*): ( uint32_t * ) ( facs_addr + 12U )<br><7> config:sharing_config filename:/hypervisor/boot/acpi.c func:acpi_fixup offset:443<br> reason:Casting operation to a pointer. : (unsigned char* to unsigned long*): ( uint64_t * ) ( facs_addr + 24U )<br><8> config:sharing_config filename:/hypervisor/boot/acpi.c func:acpi_fixup offset:443<br> reason:Casting operation on a pointer. : (unsigned char* to unsigned long*): ( uint64_t * ) ( facs_addr + 24U )<br><9> config:sharing_config filename:/hypervisor/arch/x86/guest/pm.c func:vm_load_pm_s_state offset:106<br> reason:Pointer not checked for null before use. : sx_data<br><10> config:part_config filename:/hypervisor/arch/x86/guest/pm.c func:vm_load_pm_s_state offset:106<br> reason:Pointer not checked for null before use. : sx_data<br><11> config:common filename:/hypervisor/boot/include/acpi.h func: offset:12<br> reason:Struct/union not completely specified.       : ioapic_info<br><br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by jsun26intel** [comment]
OK to verify

**Comment by HuiHuangShi** [comment]
11 new potential violations to the coding guideline detected. Please help check. Thanks!<br><1> config:sharing_config filename:/hypervisor/boot/acpi.c func:get_acpi_dt_gas offset:384<br> reason:Cast to an unrelated type. : (unsigned char* to struct packed_gas*): ( struct packed_gas * ) ( dt_addr + dt_offset )<br><2> config:sharing_config filename:/hypervisor/boot/acpi.c func:get_acpi_dt_gas offset:384<br> reason:Casting operation to a pointer. : (unsigned char* to struct packed_gas*): ( struct packed_gas * ) ( dt_addr + dt_offset )<br><3> config:sharing_config filename:/hypervisor/boot/acpi.c func:get_acpi_dt_gas offset:384<br> reason:Casting operation on a pointer. : (unsigned char* to struct packed_gas*): ( struct packed_gas * ) ( dt_addr + dt_offset )<br><4> config:sharing_config filename:/hypervisor/boot/acpi.c func:acpi_fixup offset:435<br> reason:Pointer not checked for null before use. : sx_data<br><5> config:sharing_config filename:/hypervisor/boot/acpi.c func:acpi_fixup offset:442<br> reason:Casting operation to a pointer. : (unsigned char* to unsigned int*): ( uint32_t * ) ( facs_addr + 12U )<br><6> config:sharing_config filename:/hypervisor/boot/acpi.c func:acpi_fixup offset:442<br> reason:Casting operation on a pointer. : (unsigned char* to unsigned int*): ( uint32_t * ) ( facs_addr + 12U )<br><7> config:sharing_config filename:/hypervisor/boot/acpi.c func:acpi_fixup offset:443<br> reason:Casting operation to a pointer. : (unsigned char* to unsigned long*): ( uint64_t * ) ( facs_addr + 24U )<br><8> config:sharing_config filename:/hypervisor/boot/acpi.c func:acpi_fixup offset:443<br> reason:Casting operation on a pointer. : (unsigned char* to unsigned long*): ( uint64_t * ) ( facs_addr + 24U )<br><9> config:sharing_config filename:/hypervisor/arch/x86/guest/pm.c func:vm_load_pm_s_state offset:106<br> reason:Pointer not checked for null before use. : sx_data<br><10> config:part_config filename:/hypervisor/arch/x86/guest/pm.c func:vm_load_pm_s_state offset:106<br> reason:Pointer not checked for null before use. : sx_data<br><11> config:common filename:/hypervisor/boot/include/acpi.h func: offset:12<br> reason:Struct/union not completely specified.       : ioapic_info<br><br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Pull request merged**
