### PR TITLE
HV: instr_emul: Cleanup ASSERT

### PR DESCRIPTION
**Pull request by KaigeFu**
There so many ASSERT following the function vie_read_register and vm_get_seg_desc.
It's better to move the ASSERT to those two functions and make the code more
compact.

Signed-off-by: Kaige Fu <kaige.fu@intel.com>
Acked-by: Eddie Dong <eddie.dong@intel.com>

### CODE REVIEW

**Comment by NanlinXie** [comment]
Can one of the admins verify this patch?

**Comment by lijinxia** [comment]
@KaigeFu Could you please rebase and fix the conflicts?

**Comment by KaigeFu** [comment]
@lijinxia Will rebase on the top of tree.

**Comment by lijinxia** [comment]
Verified+1

**Pull request merged**
