### PR TITLE
[config tool][doc]: remove old configurator

### PR DESCRIPTION
**Pull request by liuhang-bit**
remove configurator in misc/config_tools/config_app, since
there is new configurator in misc/config_tools/configurator.
remove related document.

Tracked-On: #7466

Signed-off-by: hangliu1 <hang1.liu@linux.intel.com>

### CODE REVIEW

**Comment by acrnsi** [comment]
Can one of the admins verify this patch?

**Review by NanlinXie — APPROVED** [review]

**Comment by GGGZZZRRR** [comment]
@liuhang-bit please check this make doc error

+ make doc
make -C /home/acrn/workspace/acrn-hypervisor-build-doc_773/acrn-hypervisor/doc html BUILDDIR=/home/acrn/workspace/acrn-hypervisor-build-doc_773/acrn-hypervisor/build/doc
make[1]: Entering directory '/home/acrn/workspace/acrn-hypervisor-build-doc_773/acrn-hypervisor/doc'
making HTML content
doc build tool versions found on your system...

  breathe                   version: 4.31.0
  sphinx                    version: 3.5.4
  docutils                  version: 0.16
  sphinx-rtd-theme          version: 1.0.0
  sphinx-tabs               version: 1.3.0
  doxygen                   version: 1.8.17


New errors/warnings found, please fix them:
==============================================

/home/acrn/workspace/acrn-hypervisor-build-doc_773/acrn-hypervisor/build/doc/rst/develop.rst:36: WARNING: toctree contains reference to nonexisting document 'tutorials/acrn_configurator_tool'

make[1]: *** [Makefile:64: html] Error 1

**Comment by dbkinder** [comment]
@amyreye If you didn't notice (I just did) this PR remove the old configurator documentation

**Comment by amyreye** [comment]
> @amyreye If you didn't notice (I just did) this PR remove the old configurator documentation

@dbkinder I started a draft for the new configurator doc in Word. Should I convert it to RST now and create a PR? We can then submit more PRs against it as the UI matures.

**Pull request merged**
