### PR TITLE
fix typos in board gen script

### PR DESCRIPTION
**Pull request by amerritt-intel**
Signed-off-by: Alexander Merritt <alex.merritt@intel.com>

### CODE REVIEW

**Comment by acrnsi** [comment]
Can one of the admins verify this patch?

**Comment by wenlingz** [comment]
OK to verify

**Comment by wenlingz** [comment]
@amerritt-intel please add Tracked-On info, it's about one git issue, please refer #4381, please add Tracked-On info on your commit and re-submit it, thanks

**Comment by amerritt-intel** [comment]
Tracked-On: #4388

**Comment by wenlingz** [comment]
@HuiHuangShi please add MISRA-C check info, thanks.

**Comment by HuiHuangShi** [comment]
No new violations to the coding guideline detected.<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Pull request merged**
