### PR TITLE
doc: update documents for "--lapic_pt" feature

### PR DESCRIPTION
**Pull request by lyan3**
- added description of lapic pt feature based on vlapic in HLD virt-interrupt part;
- updated the doc to include description of new acrn-dm option "--lapic_pt".

Tracked-On: #2351
Signed-off-by: Yan, Like <like.yan@intel.com>
Acked-by: Anthony Xu <anthony.xu@intel.com>

### CODE REVIEW

**Comment by gvancuts** [comment]
Hi @lyan3 , thanks for updating the documentation!

Here are some suggestions from me (in a patch format to make your life easier):

```
diff --git a/doc/developer-guides/hld/hld-devicemodel.rst b/doc/developer-guides/hld/hld-devicemodel.rst
index e8b84884..7df568ba 100644
--- a/doc/developer-guides/hld/hld-devicemodel.rst
+++ b/doc/developer-guides/hld/hld-devicemodel.rst
@@ -57,7 +57,8 @@ options:
                [-s pci] [-U uuid] [--vsbl vsbl_file_name] [--ovmf ovmf_file_path]
                [--part_info part_info_name] [--enable_trusty] [--intr_monitor param_setting]
                [--vtpm2 sock_path] [--virtio_poll interval] [--mac_seed seed_string]
-               [--vmcfg sub_options] [--dump vm_idx] [--ptdev_no_reset] [--debugexit] <vm>
+               [--vmcfg sub_options] [--dump vm_idx] [--ptdev_no_reset] [--debugexit]
+               [--vtpm2 sock_path] [--lapic_pt] <vm>
        -A: create ACPI tables
        -B: bootargs for kernel
        -c: # cpus (default 1)
diff --git a/doc/developer-guides/hld/hv-virt-interrupt.rst b/doc/developer-guides/hld/hv-virt-interrupt.rst
index 7f946b60..1e201cb8 100644
--- a/doc/developer-guides/hld/hv-virt-interrupt.rst
+++ b/doc/developer-guides/hld/hv-virt-interrupt.rst
@@ -129,15 +129,17 @@ comes from vIOAPIC. This only occurs for the level triggered interrupts.
 LAPIC passthrough based on vLAPIC
 =================================
 
-LAPIC passthrough is supported based on vLAPIC, after switch to x2apic
-mode. In case of LAPIC passthrough based on vLAPIC, there are following
-characters: 
-- irqs received by the LAPIC could be handled by Guest VM without vmext;
-- Guest VM always see virtual lapic id for security consideration;
-- most MSRs are directly accessible from Guest VM except for XAPICID,
-LDR and ICR: write to ICR would be trapped to avoid milicious IPI; read
-to XAPIC and LDR would be trapped in order to make Guest VM always see
-virtual lapic ID instead of physical ones.
+LAPIC passthrough is supported based on vLAPIC, after switch to x2APIC
+mode. In case of LAPIC passthrough based on vLAPIC, the system will have the
+following characteristics.
+
+* IRQs received by the LAPIC can be handled by the Guest VM without ``vmexit``
+* Guest VM always see virtual LAPIC IDs for security reasons
+* most MSRs are directly accessible from Guest VM except for ``XAPICID``,
+  ``LDR`` and ``ICR``. Write operations to ``ICR`` will be trapped to avoid
+  malicious IPI. Read operations to ``XAPIC`` and ``LDR`` will be trapped in
+  order to make the Guest VM always see the virtual LAPIC IDs instead of the
+  physical ones.
 
 Virtual IOAPIC
 **************
```

**Comment by lyan3** [comment]
Thanks @gvancuts. I will update, it's very kind of you. I have a problem to "make doc" on my local env.

**Comment by lyan3** [comment]
[--vtpm2 sock_path] is already inclued in Line 59.

**Comment by gvancuts** [comment]
> [--vtpm2 sock_path] is already inclued in Line 59.

Good catch, I had missed it completely, thanks! 👍

**Pull request merged**
