### PR TITLE
apl-mrb: Add in weston.service

### PR DESCRIPTION
**Pull request by YinThong**
This service will start weston once power up.

Signed-off-by: Choong Yin Thong <yin.thong.choong@intel.com>

### CODE REVIEW

**Comment by NanlinXie** [comment]
Can one of the admins verify this patch?

**Comment by dongyaozu** [comment]
With current working style, You need to get it reviewed in mailinglist, and get ACK from maintainer. And then send PR request with those review info.    

Very simple patch can go PR directly...

**Comment by dongyaozu** [comment]
@jren1 @gvancuts  can you review?

**Comment by dongyaozu** [comment]
Thanks YinThong for the patches:) Let us wait some time for Geoff to comment

**Comment by gvancuts** [comment]
> In the future, please follow the process:
> 1. send the patches to acrn-dev@lists.acrnproject.org for review
> 2. get the ack-by from maintainer and then send the git pull request here.

We should really update our documentation as today there is no indication there that it's the process one should follow: https://projectacrn.github.io/latest/contribute/contribute_guidelines.html#contribution-workflow

(On a personal note: I realize this is a common methodology in various open-source projects but I find it very cumbersome for me to work with this as it interferes with the corporate IT set-up. I wouldn’t want that to become a barrier for other community members to join and contribute).

**Comment by gvancuts** [comment]
A few questions on this:
* Does that enable the `weston.service` (or does that make it available but still disabled by default)?
* Should we have something similar for `devicemodel/samples/nuc`?
   * I also believe this will unconditionally install this file on *any* platform (since it's part of the `make install` step). I don't think this is the intended behaviour?
* What bothers me a bit with this is that it assumes that `weston` is installed but that dependency is not called out anywhere. So if this patch gets merged as-is, someone would install the `service-os` bundle on a new Clear Linux installation and have a `systemd` service file installed that will not work until he installs an extra bundle and that won't happen automatically nor is documented anywhere.

@miguelinux , could you also review this patch?

**Comment by YinThong** [comment]
@miguelinux will create proper step to be integrated on OS side.

**Pull request closed without merging**
