### PR TITLE
Unify terminology for service vm/user vm

### PR DESCRIPTION
**Pull request by liudlong**
•	User VM: A VM where user-defined environments and applications run. User VMs can run different OSes based on their needs, including for example, Ubuntu for an AI application, Android or Windows for a Human-Machine Interface, or a hard real-time control OS such as Zephyr, VxWorks, or RT-Linux for soft or hard real-time control. There are three types of User VMs: pre-launched, post-launched Standard and post-launched Real-Time User VMs.
•	Service VM: a special Virtual Machine (VM), directly launched by the hypervisor. The Service VM can access hardware resources directly by running native drivers and provides device sharing services to post-launched User VMs through the ACRN Device Model (DM). Hardware resources include CPUs, memory, graphics memory, USB devices, disk, and network mediation.

### CODE REVIEW

**Comment by wenlingz** [comment]
OK to verify

**Comment by wenlingz** [comment]
OK to verify

**Comment by wenlingz** [comment]
@dongyaozu @NanlinXie @ywan170 please help approve this PR, thanks

**Review by ywan170 — APPROVED** [review]

**Review by NanlinXie — APPROVED** [review]
approved for configtool part

**Pull request merged**
