### PR TITLE
Dump guest memory

### PR DESCRIPTION
**Pull request by mingqiangchi**
-- remove show_guest_call_trace
-- refine dump host memory
-- add dump guest memory

Tracked-On: #4144

### CODE REVIEW

**Comment by HuiHuangShi** [comment]
29 new potential violations to the coding guideline detected. Please help check. Thanks!<br><1> config:common filename:/hypervisor/debug/shell.c func:shell_dump_host_mem offset:834<br> reason:Procedure has more than one exit point.<br><2> config:common filename:/hypervisor/debug/shell.c func:shell_dump_host_mem offset:834<br> reason:Static procedure is not explicitly called in code analysed. : shell_dump_host_mem<br><3> config:part_config filename:/hypervisor/debug/shell.c func:shell_dump_host_mem offset:834<br> reason:Pointer param should be declared pointer to const. : argv<br><4> config:sharing_config filename:/hypervisor/debug/shell.c func:shell_dump_host_mem offset:834<br> reason:Pointer param should be declared pointer to const. : argv<br><5> config:common filename:/hypervisor/debug/shell.c func:shell_dump_host_mem offset:846<br> reason:Declaration does not specify an array.       : argv<br><6> config:common filename:/hypervisor/debug/shell.c func:shell_dump_host_mem offset:847<br> reason:Declaration does not specify an array.       : argv<br><7> config:common filename:/hypervisor/debug/shell.c func:shell_dump_host_mem offset:854<br> reason:Cast from integral type to pointer. : (unsigned long to unsigned long*): ( uint64_t * ) addr<br><8> config:part_config filename:/hypervisor/debug/shell.c func:dump_guest_mem offset:864<br> reason:Pointer param should be declared pointer to const. : data<br><9> config:sharing_config filename:/hypervisor/debug/shell.c func:dump_guest_mem offset:864<br> reason:Pointer param should be declared pointer to const. : data<br><10> config:common filename:/hypervisor/debug/shell.c func:dump_guest_mem offset:864<br> reason:Procedure has more than one exit point.<br><11> config:common filename:/hypervisor/debug/shell.c func:dump_guest_mem offset:871<br> reason:Type conversion without cast. :  (struct guest_mem_dump* and void*): data<br><12> config:common filename:/hypervisor/debug/shell.c func:dump_guest_mem offset:877<br> reason:Implicit conversion of underlying type (MR). :  (unsigned int and unsigned long)<br><13> config:common filename:/hypervisor/debug/shell.c func:dump_guest_mem offset:877<br> reason:Implicit conversion of underlying type (MR). :  (unsigned int and unsigned long): ( length >> 5U<br><14> config:common filename:/hypervisor/debug/shell.c func:dump_guest_mem offset:877<br> reason:Type mismatch in ternary expression. :  (unsigned int and unsigned long)<br><15> config:common filename:/hypervisor/debug/shell.c func:dump_guest_mem offset:877<br> reason:Use of mixed mode arithmetic. :  (unsigned int and unsigned long): ( length >> 5U<br><16> config:part_config filename:/hypervisor/debug/shell.c func:shell_dump_guest_mem offset:892<br> reason:Pointer param should be declared pointer to const. : argv<br><17> config:sharing_config filename:/hypervisor/debug/shell.c func:shell_dump_guest_mem offset:892<br> reason:Pointer param should be declared pointer to const. : argv<br><18> config:common filename:/hypervisor/debug/shell.c func:shell_dump_guest_mem offset:892<br> reason:Static procedure is not explicitly called in code analysed. : shell_dump_guest_mem<br><19> config:common filename:/hypervisor/debug/shell.c func:shell_dump_guest_mem offset:892<br> reason:Procedure has more than one exit point.<br><20> config:common filename:/hypervisor/debug/shell.c func:shell_dump_guest_mem offset:907<br> reason:Signed/unsigned conversion without cast. :  (unsigned short and long): vm_id = strtol_deci<br><21> config:common filename:/hypervisor/debug/shell.c func:shell_dump_guest_mem offset:907<br> reason:Declaration does not specify an array.       : argv<br><22> config:common filename:/hypervisor/debug/shell.c func:shell_dump_guest_mem offset:908<br> reason:Declaration does not specify an array.       : argv<br><23> config:common filename:/hypervisor/debug/shell.c func:shell_dump_guest_mem offset:909<br> reason:Declaration does not specify an array.       : argv<br><24> config:sharing_config filename:/hypervisor/debug/shell.c func:shell_dump_guest_mem offset:912<br> reason:Pointer not checked for null before use. : vm<br><25> config:part_config filename:/hypervisor/debug/shell.c func:shell_dump_guest_mem offset:912<br> reason:Pointer not checked for null before use. : vm<br><26> config:sharing_config filename:/hypervisor/debug/shell.c func:shell_dump_guest_mem offset:920<br> reason:Pointer not checked for null before use. : dump.vcpu<br><27> config:part_config filename:/hypervisor/debug/shell.c func:shell_dump_guest_mem offset:920<br> reason:Pointer not checked for null before use. : dump.vcpu<br><28> config:sharing_config filename:/hypervisor/debug/shell.c func:shell_dump_guest_mem offset:923<br> reason:Pointer not checked for null before use. : dump.vcpu<br><29> config:part_config filename:/hypervisor/debug/shell.c func:shell_dump_guest_mem offset:923<br> reason:Pointer not checked for null before use. : dump.vcpu<br><br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by mingqiangchi** [comment]
append another patch to fix some MISRA-C violations

**Comment by HuiHuangShi** [comment]
22 new potential violations to the coding guideline detected. Please help check. Thanks!<br><1> config:sharing_config filename:/hypervisor/debug/shell.c func:shell_dump_host_mem offset:834<br> reason:Pointer param should be declared pointer to const. : argv<br><2> config:part_config filename:/hypervisor/debug/shell.c func:shell_dump_host_mem offset:834<br> reason:Pointer param should be declared pointer to const. : argv<br><3> config:common filename:/hypervisor/debug/shell.c func:shell_dump_host_mem offset:834<br> reason:Static procedure is not explicitly called in code analysed. : shell_dump_host_mem<br><4> config:common filename:/hypervisor/debug/shell.c func:shell_dump_host_mem offset:846<br> reason:Declaration does not specify an array.       : argv<br><5> config:common filename:/hypervisor/debug/shell.c func:shell_dump_host_mem offset:847<br> reason:Declaration does not specify an array.       : argv<br><6> config:common filename:/hypervisor/debug/shell.c func:shell_dump_host_mem offset:854<br> reason:Cast from integral type to pointer. : (unsigned long to unsigned long*): ( uint64_t * ) addr<br><7> config:part_config filename:/hypervisor/debug/shell.c func:dump_guest_mem offset:866<br> reason:Pointer param should be declared pointer to const. : data<br><8> config:sharing_config filename:/hypervisor/debug/shell.c func:dump_guest_mem offset:866<br> reason:Pointer param should be declared pointer to const. : data<br><9> config:common filename:/hypervisor/debug/shell.c func:dump_guest_mem offset:873<br> reason:Casting operation to a pointer. : (void* to struct guest_mem_dump*): ( struct guest_mem_dump * ) data<br><10> config:common filename:/hypervisor/debug/shell.c func:dump_guest_mem offset:873<br> reason:Casting operation on a pointer. : (void* to struct guest_mem_dump*): ( struct guest_mem_dump * ) data<br><11> config:sharing_config filename:/hypervisor/debug/shell.c func:shell_dump_guest_mem offset:894<br> reason:Pointer param should be declared pointer to const. : argv<br><12> config:part_config filename:/hypervisor/debug/shell.c func:shell_dump_guest_mem offset:894<br> reason:Pointer param should be declared pointer to const. : argv<br><13> config:common filename:/hypervisor/debug/shell.c func:shell_dump_guest_mem offset:894<br> reason:Static procedure is not explicitly called in code analysed. : shell_dump_guest_mem<br><14> config:common filename:/hypervisor/debug/shell.c func:shell_dump_guest_mem offset:909<br> reason:Declaration does not specify an array.       : argv<br><15> config:common filename:/hypervisor/debug/shell.c func:shell_dump_guest_mem offset:910<br> reason:Declaration does not specify an array.       : argv<br><16> config:common filename:/hypervisor/debug/shell.c func:shell_dump_guest_mem offset:911<br> reason:Declaration does not specify an array.       : argv<br><17> config:sharing_config filename:/hypervisor/debug/shell.c func:shell_dump_guest_mem offset:914<br> reason:Pointer not checked for null before use. : vm<br><18> config:part_config filename:/hypervisor/debug/shell.c func:shell_dump_guest_mem offset:914<br> reason:Pointer not checked for null before use. : vm<br><19> config:sharing_config filename:/hypervisor/debug/shell.c func:shell_dump_guest_mem offset:922<br> reason:Pointer not checked for null before use. : dump.vcpu<br><20> config:part_config filename:/hypervisor/debug/shell.c func:shell_dump_guest_mem offset:922<br> reason:Pointer not checked for null before use. : dump.vcpu<br><21> config:sharing_config filename:/hypervisor/debug/shell.c func:shell_dump_guest_mem offset:925<br> reason:Pointer not checked for null before use. : dump.vcpu<br><22> config:part_config filename:/hypervisor/debug/shell.c func:shell_dump_guest_mem offset:925<br> reason:Pointer not checked for null before use. : dump.vcpu<br><br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by mingqiangchi** [comment]
ok, will merge 4/4 back to 2,3

**Comment by HuiHuangShi** [comment]
22 new potential violations to the coding guideline detected. Please help check. Thanks!<br><1> config:part_config filename:/hypervisor/debug/shell.c func:shell_dump_host_mem offset:834<br> reason:Pointer param should be declared pointer to const. : argv<br><2> config:sharing_config filename:/hypervisor/debug/shell.c func:shell_dump_host_mem offset:834<br> reason:Pointer param should be declared pointer to const. : argv<br><3> config:common filename:/hypervisor/debug/shell.c func:shell_dump_host_mem offset:834<br> reason:Static procedure is not explicitly called in code analysed. : shell_dump_host_mem<br><4> config:common filename:/hypervisor/debug/shell.c func:shell_dump_host_mem offset:845<br> reason:Declaration does not specify an array.       : argv<br><5> config:common filename:/hypervisor/debug/shell.c func:shell_dump_host_mem offset:845<br> reason:Cast from integral type to pointer. : (unsigned long to unsigned long*): ( uint64_t * ) strtoul_hex ( argv [ 1 ] )<br><6> config:common filename:/hypervisor/debug/shell.c func:shell_dump_host_mem offset:846<br> reason:Declaration does not specify an array.       : argv<br><7> config:part_config filename:/hypervisor/debug/shell.c func:dump_guest_mem offset:864<br> reason:Pointer param should be declared pointer to const. : data<br><8> config:sharing_config filename:/hypervisor/debug/shell.c func:dump_guest_mem offset:864<br> reason:Pointer param should be declared pointer to const. : data<br><9> config:common filename:/hypervisor/debug/shell.c func:dump_guest_mem offset:871<br> reason:Casting operation to a pointer. : (void* to struct guest_mem_dump*): ( struct guest_mem_dump * ) data<br><10> config:common filename:/hypervisor/debug/shell.c func:dump_guest_mem offset:871<br> reason:Casting operation on a pointer. : (void* to struct guest_mem_dump*): ( struct guest_mem_dump * ) data<br><11> config:sharing_config filename:/hypervisor/debug/shell.c func:shell_dump_guest_mem offset:892<br> reason:Pointer param should be declared pointer to const. : argv<br><12> config:part_config filename:/hypervisor/debug/shell.c func:shell_dump_guest_mem offset:892<br> reason:Pointer param should be declared pointer to const. : argv<br><13> config:common filename:/hypervisor/debug/shell.c func:shell_dump_guest_mem offset:892<br> reason:Static procedure is not explicitly called in code analysed. : shell_dump_guest_mem<br><14> config:common filename:/hypervisor/debug/shell.c func:shell_dump_guest_mem offset:907<br> reason:Declaration does not specify an array.       : argv<br><15> config:common filename:/hypervisor/debug/shell.c func:shell_dump_guest_mem offset:908<br> reason:Declaration does not specify an array.       : argv<br><16> config:common filename:/hypervisor/debug/shell.c func:shell_dump_guest_mem offset:909<br> reason:Declaration does not specify an array.       : argv<br><17> config:sharing_config filename:/hypervisor/debug/shell.c func:shell_dump_guest_mem offset:912<br> reason:Pointer not checked for null before use. : vm<br><18> config:part_config filename:/hypervisor/debug/shell.c func:shell_dump_guest_mem offset:912<br> reason:Pointer not checked for null before use. : vm<br><19> config:sharing_config filename:/hypervisor/debug/shell.c func:shell_dump_guest_mem offset:920<br> reason:Pointer not checked for null before use. : dump.vcpu<br><20> config:part_config filename:/hypervisor/debug/shell.c func:shell_dump_guest_mem offset:920<br> reason:Pointer not checked for null before use. : dump.vcpu<br><21> config:sharing_config filename:/hypervisor/debug/shell.c func:shell_dump_guest_mem offset:923<br> reason:Pointer not checked for null before use. : dump.vcpu<br><22> config:part_config filename:/hypervisor/debug/shell.c func:shell_dump_guest_mem offset:923<br> reason:Pointer not checked for null before use. : dump.vcpu<br><br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by gvancuts** [comment]
Are you planning to update `doc/user-guides/acrn-shell.rst` now this has been merged? Thanks!

**Comment by mingqiangchi** [comment]
ok, will update this doc, thanks.

**Pull request merged**
