### PR TITLE
script: fix a minor bug in launch_xenomai.sh

### PR DESCRIPTION
**Pull request by tw4452852**
There a bug in substring detection, fix it.

Signed-off-by: Tw <wei.tan@intel.com>

### CODE REVIEW

**Comment by wenlingz** [comment]
@tw4452852 please add Tracked-On, thanks

**Comment by wenlingz** [comment]
OK to Verify

**Comment by wenlingz** [comment]
@HuiHuangShi please add MISRA-C check, thanks

**Comment by wenlingz** [comment]
@ywan170 please help approve this PR, thanks

**Comment by tw4452852** [comment]
@terryzouhao Done. I've created an issue for tracking.

**Comment by HuiHuangShi** [comment]
No new violations to the coding guideline detected.<br>No New Name Conflict<br>No New Function Declaration/Definition Mismatch

**Pull request merged**
