### PR TITLE
remove deadcode of rdtsc_handler/rdtscp_handler

### PR DESCRIPTION
**Pull request by mcao6**
Guest OS rdtsc/rdtscp doesn't trap into hypervisor, so remove them.

Signed-off-by: Minggui Cao <minggui.cao@intel.com>
Reviewed-by: Jason Chen CJ <jason.cj.chen@intel.com>
Acked-by: Eddie Dong <eddie.dong@intel.com>

### CODE REVIEW

**Comment by lijinxia** [comment]
verified +1

**Comment by lifeix** [comment]
@mcao6 should we need to remove VMX_PROCBASED_CTLS2_RDTSCP bit set in write_cr0() ?

**Comment by mcao6** [comment]
let me check that.

**Comment by mcao6** [comment]
after checked, this bit: VMX_PROCBASED_CTLS2_RDTSCP is used to enable rdtscp for guest OS; not for rdtsc/rdtscp vmexit trap. Also will cook a patch to enable rdtscp for each vcpu of guest OS.

**Pull request merged**
