### PR TITLE
HV: patch set to enable hybrid scenario

### PR DESCRIPTION
**Pull request by jsun26intel**
Hybrid scenario will run 3 VMs: one pre-launched VM, one pre-launched SOS VM and one post-launched Standard VM.

Tracked-On: #3214

Signed-off-by: Victor Sun <victor.sun@intel.com>
Reviewed-by: Jason Chen CJ <jason.cj.chen@intel.com>

### CODE REVIEW

**Comment by HuiHuangShi** [comment]
69 new potential violations to the coding guideline detected. Please help check. Thanks!<br><1> config:part_config filename:/hypervisor/arch/x86/guest/vm.c func:prepare_vm offset:708<br> reason:Pointer not checked for null before use. : vm<br><2> config:sharing_config filename:/hypervisor/arch/x86/guest/vm.c func:prepare_vm offset:708<br> reason:Pointer not checked for null before use. : vm<br><3> config:sharing_config filename:/hypervisor/boot/guest/vboot_info.c func:init_vm_ramdisk_info offset:31<br> reason:Pointer param should be declared pointer to const. : mod<br><4> config:part_config filename:/hypervisor/boot/guest/vboot_info.c func:init_vm_ramdisk_info offset:31<br> reason:Pointer param should be declared pointer to const. : mod<br><5> config:common filename:/hypervisor/boot/guest/vboot_info.c func:init_vm_ramdisk_info offset:38<br> reason:Cast from integral type to pointer. : (unsigned long to void*): ( void * ) round_page_up ( ( uint64_t ) vm -> sw.ramdisk_info.load_addr )<br><6> config:sharing_config filename:/hypervisor/boot/guest/vboot_info.c func:get_kernel_load_addr offset:91<br> reason:Pointer param should be declared pointer to const. : vm<br><7> config:part_config filename:/hypervisor/boot/guest/vboot_info.c func:get_kernel_load_addr offset:91<br> reason:Pointer param should be declared pointer to const. : vm<br><8> config:common filename:/hypervisor/boot/guest/vboot_info.c func:get_kernel_load_addr offset:108<br> reason:Casting operation to a pointer. : (void* to struct zero_page*): ( struct zero_page * ) sw_info -> kernel_info.kernel_src_addr<br><9> config:common filename:/hypervisor/boot/guest/vboot_info.c func:get_kernel_load_addr offset:108<br> reason:Casting operation on a pointer. : (void* to struct zero_page*): ( struct zero_page * ) sw_info -> kernel_info.kernel_src_addr<br><10> config:sharing_config filename:/hypervisor/boot/guest/vboot_info.c func:get_kernel_load_addr offset:109<br> reason:Pointer not checked for null before use. : zeropage<br><11> config:part_config filename:/hypervisor/boot/guest/vboot_info.c func:get_kernel_load_addr offset:109<br> reason:Pointer not checked for null before use. : zeropage<br><12> config:part_config filename:/hypervisor/boot/guest/vboot_info.c func:get_kernel_load_addr offset:115<br> reason:Pointer not checked for null before use. : vm_config<br><13> config:sharing_config filename:/hypervisor/boot/guest/vboot_info.c func:get_kernel_load_addr offset:115<br> reason:Pointer not checked for null before use. : vm_config<br><14> config:common filename:/hypervisor/boot/guest/vboot_info.c func:get_kernel_load_addr offset:115<br> reason:Cast from integral type to pointer. : (unsigned long to void*): ( void * ) vm_config -> os_config.kernel_load_addr<br><15> config:common filename:/hypervisor/boot/guest/vboot_info.c func:get_kernel_load_addr offset:124<br> reason:Pointer assignment to wider scope.<br><16> config:sharing_config filename:/hypervisor/boot/guest/vboot_info.c func:init_vm_kernel_info offset:130<br> reason:Pointer param should be declared pointer to const. : mod<br><17> config:part_config filename:/hypervisor/boot/guest/vboot_info.c func:init_vm_kernel_info offset:130<br> reason:Pointer param should be declared pointer to const. : mod<br><18> config:sharing_config filename:/hypervisor/boot/guest/vboot_info.c func:init_vm_kernel_info offset:137<br> reason:Pointer not checked for null before use. : vm_config<br><19> config:part_config filename:/hypervisor/boot/guest/vboot_info.c func:init_vm_kernel_info offset:137<br> reason:Pointer not checked for null before use. : vm_config<br><20> config:part_config filename:/hypervisor/boot/guest/vboot_info.c func:init_vm_bootargs_info offset:148<br> reason:Pointer param should be declared pointer to const. : mbi<br><21> config:sharing_config filename:/hypervisor/boot/guest/vboot_info.c func:init_vm_bootargs_info offset:148<br> reason:Pointer param should be declared pointer to const. : mbi<br><22> config:part_config filename:/hypervisor/boot/guest/vboot_info.c func:init_vm_bootargs_info offset:151<br> reason:Pointer not checked for null before use. : vm_config<br><23> config:sharing_config filename:/hypervisor/boot/guest/vboot_info.c func:init_vm_bootargs_info offset:151<br> reason:Pointer not checked for null before use. : vm_config<br><24> config:common filename:/hypervisor/boot/guest/vboot_info.c func:init_vm_bootargs_info offset:174<br> reason:Literal value requires a U suffix.           : 0<br><25> config:common filename:/hypervisor/boot/guest/vboot_info.c func:init_vm_bootargs_info offset:174<br> reason:Signed/unsigned conversion without cast. :  (unsigned int and int): vm -> sw.bootargs_info.size<br><26> config:part_config filename:/hypervisor/boot/guest/vboot_info.c func:get_mod_idx_by_tag offset:181<br> reason:Pointer param should be declared pointer to const. : mods<br><27> config:sharing_config filename:/hypervisor/boot/guest/vboot_info.c func:get_mod_idx_by_tag offset:181<br> reason:Pointer param should be declared pointer to const. : mods<br><28> config:common filename:/hypervisor/boot/guest/vboot_info.c func:get_mod_idx_by_tag offset:186<br> reason:Literal value requires a U suffix.           : 0<br><29> config:common filename:/hypervisor/boot/guest/vboot_info.c func:get_mod_idx_by_tag offset:186<br> reason:Signed/unsigned conversion without cast. :  (unsigned int and int): i<br><30> config:common filename:/hypervisor/boot/guest/vboot_info.c func:get_mod_idx_by_tag offset:192<br> reason:Declaration does not specify an array.       : mm_string<br><31> config:common filename:/hypervisor/boot/guest/vboot_info.c func:get_mod_idx_by_tag offset:192<br> reason:Use of mixed mode arithmetic. :  (char and signed char): mm_string [ tag_len ] == 0x0d<br><32> config:common filename:/hypervisor/boot/guest/vboot_info.c func:get_mod_idx_by_tag offset:193<br> reason:Declaration does not specify an array.       : mm_string<br><33> config:common filename:/hypervisor/boot/guest/vboot_info.c func:get_mod_idx_by_tag offset:193<br> reason:Use of mixed mode arithmetic. :  (char and signed char): mm_string [ tag_len ] == 0x0a<br><34> config:common filename:/hypervisor/boot/guest/vboot_info.c func:get_mod_idx_by_tag offset:194<br> reason:Value is not of appropriate type. :  (char and signed char): ( mm_string [ tag_len ] == 0<br>.....<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by wenlingz** [comment]
OK to verify

**Comment by acrnsi** [comment]
OK to verify

**Comment by acrnsi** [comment]
OK to verify

**Comment by jsun26intel** [comment]
we have new PR 3235 to enable hybrid scenario, close the old one.

**Pull request closed without merging**
