### PR TITLE
hv: fix MISRAC violations for crypto lib

### PR DESCRIPTION
**Pull request by GangSecurity**
-Remove upper case
 -Modify/fix code style violations
 -fix value need U suffix
 -Assignment operation in expression
 -remove function like macros

 v1->v2 fix assignment operation in expression
 v2->v3 fix function like macros

Tracked-On: #861
Signed-off-by: Chen Gang G <gang.g.chen@intel.com>
Acked-by: Eddie Dong <eddie.dong@intel.com>

### CODE REVIEW

**Comment by HuiHuangShi** [comment]
2289<br>30 new potential violations to the coding guideline detected. Please help check. Thanks!  <br><br>1.filename:/hypervisor/lib/crypto/mbedtls/md.c&nbsp;&nbsp;function:mbedtls_md_info_from_type&nbsp;&nbsp;offset:49:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Pointer assignment to wider scope.<br><br>2.filename:/hypervisor/lib/crypto/mbedtls/md.c&nbsp;&nbsp;function:mbedtls_md_hmac_starts&nbsp;&nbsp;offset:115:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Pointer not checked for null before use. : temp_key<br><br>3.filename:/hypervisor/lib/crypto/mbedtls/sha256.c&nbsp;&nbsp;function:get_uint32_be&nbsp;&nbsp;offset:60:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Space missing before or after binary operator.<br><br>4.filename:/hypervisor/lib/crypto/mbedtls/sha256.c&nbsp;&nbsp;function:r&nbsp;&nbsp;offset:122:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Declaration does not specify an array.       : w<br><br>5.filename:/hypervisor/lib/crypto/mbedtls/sha256.c&nbsp;&nbsp;function:p&nbsp;&nbsp;offset:131:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:<#> Parameter has same name as global variable.  : k<br><br>6.filename:/hypervisor/lib/crypto/mbedtls/sha256.c&nbsp;&nbsp;function:p&nbsp;&nbsp;offset:131:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Identifier reuse: persistent var vs proc param. : k<br><br>7.filename:/hypervisor/lib/crypto/mbedtls/sha256.c&nbsp;&nbsp;function:mbedtls_internal_sha256_process&nbsp;&nbsp;offset:207:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Space missing before or after binary operator.<br><br>8.filename:/hypervisor/lib/crypto/mbedtls/sha256.c&nbsp;&nbsp;function:mbedtls_internal_sha256_process&nbsp;&nbsp;offset:208:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Space missing before or after binary operator.<br><br>9.filename:/hypervisor/lib/crypto/mbedtls/sha256.c&nbsp;&nbsp;function:mbedtls_internal_sha256_process&nbsp;&nbsp;offset:209:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Space missing before or after binary operator.<br><br>10.filename:/hypervisor/lib/crypto/mbedtls/sha256.c&nbsp;&nbsp;function:mbedtls_internal_sha256_process&nbsp;&nbsp;offset:210:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Space missing before or after binary operator.<br><br>11.filename:/hypervisor/lib/crypto/mbedtls/sha256.c&nbsp;&nbsp;function:mbedtls_internal_sha256_process&nbsp;&nbsp;offset:211:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Space missing before or after binary operator.<br><br>12.filename:/hypervisor/lib/crypto/mbedtls/sha256.c&nbsp;&nbsp;function:mbedtls_internal_sha256_process&nbsp;&nbsp;offset:212:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Space missing before or after binary operator.<br><br>13.filename:/hypervisor/lib/crypto/mbedtls/sha256.c&nbsp;&nbsp;function:mbedtls_internal_sha256_process&nbsp;&nbsp;offset:213:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Space missing before or after binary operator.<br><br>14.filename:/hypervisor/lib/crypto/mbedtls/sha256.c&nbsp;&nbsp;function:mbedtls_internal_sha256_process&nbsp;&nbsp;offset:214:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Space missing before or after binary operator.<br><br>15.filename:/hypervisor/lib/crypto/mbedtls/sha256.c&nbsp;&nbsp;function:mbedtls_internal_sha256_process&nbsp;&nbsp;offset:218:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Space missing before or after binary operator.<br><br>16.filename:/hypervisor/lib/crypto/mbedtls/sha256.c&nbsp;&nbsp;function:mbedtls_internal_sha256_process&nbsp;&nbsp;offset:219:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Space missing before or after binary operator.<br><br>17.filename:/hypervisor/lib/crypto/mbedtls/sha256.c&nbsp;&nbsp;function:mbedtls_internal_sha256_process&nbsp;&nbsp;offset:221:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Space missing before or after binary operator.<br><br>18.filename:/hypervisor/lib/crypto/mbedtls/sha256.c&nbsp;&nbsp;function:mbedtls_internal_sha256_process&nbsp;&nbsp;offset:222:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Space missing before or after binary operator.<br><br>19.filename:/hypervisor/lib/crypto/mbedtls/sha256.c&nbsp;&nbsp;function:mbedtls_internal_sha256_process&nbsp;&nbsp;offset:224:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Space missing before or after binary operator.<br><br>20.filename:/hypervisor/lib/crypto/mbedtls/sha256.c&nbsp;&nbsp;function:mbedtls_internal_sha256_process&nbsp;&nbsp;offset:225:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Space missing before or after binary operator.<br><br>21.filename:/hypervisor/lib/crypto/mbedtls/sha256.c&nbsp;&nbsp;function:mbedtls_internal_sha256_process&nbsp;&nbsp;offset:227:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Space missing before or after binary operator.<br><br>22.filename:/hypervisor/lib/crypto/mbedtls/sha256.c&nbsp;&nbsp;function:mbedtls_internal_sha256_process&nbsp;&nbsp;offset:228:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Space missing before or after binary operator.<br><br>23.filename:/hypervisor/lib/crypto/mbedtls/sha256.c&nbsp;&nbsp;function:mbedtls_internal_sha256_process&nbsp;&nbsp;offset:230:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Space missing before or after binary operator.<br><br>24.filename:/hypervisor/lib/crypto/mbedtls/sha256.c&nbsp;&nbsp;function:mbedtls_internal_sha256_process&nbsp;&nbsp;offset:231:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Space missing before or after binary operator.<br><br>25.filename:/hypervisor/lib/crypto/mbedtls/sha256.c&nbsp;&nbsp;function:mbedtls_internal_sha256_process&nbsp;&nbsp;offset:233:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Space missing before or after binary operator.<br><br>26.filename:/hypervisor/lib/crypto/mbedtls/sha256.c&nbsp;&nbsp;function:mbedtls_internal_sha256_process&nbsp;&nbsp;offset:234:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Space missing before or after binary operator.<br><br>27.filename:/hypervisor/lib/crypto/mbedtls/sha256.c&nbsp;&nbsp;function:mbedtls_internal_sha256_process&nbsp;&nbsp;offset:236:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Space missing before or after binary operator.<br><br>28.filename:/hypervisor/lib/crypto/mbedtls/sha256.c&nbsp;&nbsp;function:mbedtls_internal_sha256_process&nbsp;&nbsp;offset:237:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Space missing before or after binary operator.<br><br>29.filename:/hypervisor/lib/crypto/mbedtls/sha256.c&nbsp;&nbsp;function:mbedtls_internal_sha256_process&nbsp;&nbsp;offset:239:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Space missing before or after binary operator.<br><br>30.filename:/hypervisor/lib/crypto/mbedtls/sha256.c&nbsp;&nbsp;function:mbedtls_internal_sha256_process&nbsp;&nbsp;offset:240:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Space missing before or after binary operator.<br><br>

**Comment by ClaudZhang1995** [comment]
Ok to verify

**Comment by HuiHuangShi** [comment]
2289<br>29 new potential violations to the coding guideline detected. Please help check. Thanks!  <br><br>1.filename:/hypervisor/lib/crypto/mbedtls/md.c&nbsp;&nbsp;function:mbedtls_md_info_from_type&nbsp;&nbsp;offset:49:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Pointer assignment to wider scope.<br><br>2.filename:/hypervisor/lib/crypto/mbedtls/md.c&nbsp;&nbsp;function:mbedtls_md_hmac_starts&nbsp;&nbsp;offset:115:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Pointer not checked for null before use. : temp_key<br><br>3.filename:/hypervisor/lib/crypto/mbedtls/sha256.c&nbsp;&nbsp;function:get_uint32_be&nbsp;&nbsp;offset:60:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Space missing before or after binary operator.<br><br>4.filename:/hypervisor/lib/crypto/mbedtls/sha256.c&nbsp;&nbsp;function:r&nbsp;&nbsp;offset:122:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Implicit conversion: actual to formal param (MR). :  (int and unsigned int):  param  1<br><br>5.filename:/hypervisor/lib/crypto/mbedtls/sha256.c&nbsp;&nbsp;function:r&nbsp;&nbsp;offset:122:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Signed/unsigned conversion without cast. :  (int and unsigned int):  param  1<br><br>6.filename:/hypervisor/lib/crypto/mbedtls/sha256.c&nbsp;&nbsp;function:mbedtls_internal_sha256_process&nbsp;&nbsp;offset:207:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Space missing before or after binary operator.<br><br>7.filename:/hypervisor/lib/crypto/mbedtls/sha256.c&nbsp;&nbsp;function:mbedtls_internal_sha256_process&nbsp;&nbsp;offset:208:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Space missing before or after binary operator.<br><br>8.filename:/hypervisor/lib/crypto/mbedtls/sha256.c&nbsp;&nbsp;function:mbedtls_internal_sha256_process&nbsp;&nbsp;offset:209:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Space missing before or after binary operator.<br><br>9.filename:/hypervisor/lib/crypto/mbedtls/sha256.c&nbsp;&nbsp;function:mbedtls_internal_sha256_process&nbsp;&nbsp;offset:210:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Space missing before or after binary operator.<br><br>10.filename:/hypervisor/lib/crypto/mbedtls/sha256.c&nbsp;&nbsp;function:mbedtls_internal_sha256_process&nbsp;&nbsp;offset:211:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Space missing before or after binary operator.<br><br>11.filename:/hypervisor/lib/crypto/mbedtls/sha256.c&nbsp;&nbsp;function:mbedtls_internal_sha256_process&nbsp;&nbsp;offset:212:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Space missing before or after binary operator.<br><br>12.filename:/hypervisor/lib/crypto/mbedtls/sha256.c&nbsp;&nbsp;function:mbedtls_internal_sha256_process&nbsp;&nbsp;offset:213:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Space missing before or after binary operator.<br><br>13.filename:/hypervisor/lib/crypto/mbedtls/sha256.c&nbsp;&nbsp;function:mbedtls_internal_sha256_process&nbsp;&nbsp;offset:214:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Space missing before or after binary operator.<br><br>14.filename:/hypervisor/lib/crypto/mbedtls/sha256.c&nbsp;&nbsp;function:mbedtls_internal_sha256_process&nbsp;&nbsp;offset:218:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Space missing before or after binary operator.<br><br>15.filename:/hypervisor/lib/crypto/mbedtls/sha256.c&nbsp;&nbsp;function:mbedtls_internal_sha256_process&nbsp;&nbsp;offset:219:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Space missing before or after binary operator.<br><br>16.filename:/hypervisor/lib/crypto/mbedtls/sha256.c&nbsp;&nbsp;function:mbedtls_internal_sha256_process&nbsp;&nbsp;offset:221:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Space missing before or after binary operator.<br><br>17.filename:/hypervisor/lib/crypto/mbedtls/sha256.c&nbsp;&nbsp;function:mbedtls_internal_sha256_process&nbsp;&nbsp;offset:222:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Space missing before or after binary operator.<br><br>18.filename:/hypervisor/lib/crypto/mbedtls/sha256.c&nbsp;&nbsp;function:mbedtls_internal_sha256_process&nbsp;&nbsp;offset:224:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Space missing before or after binary operator.<br><br>19.filename:/hypervisor/lib/crypto/mbedtls/sha256.c&nbsp;&nbsp;function:mbedtls_internal_sha256_process&nbsp;&nbsp;offset:225:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Space missing before or after binary operator.<br><br>20.filename:/hypervisor/lib/crypto/mbedtls/sha256.c&nbsp;&nbsp;function:mbedtls_internal_sha256_process&nbsp;&nbsp;offset:227:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Space missing before or after binary operator.<br><br>21.filename:/hypervisor/lib/crypto/mbedtls/sha256.c&nbsp;&nbsp;function:mbedtls_internal_sha256_process&nbsp;&nbsp;offset:228:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Space missing before or after binary operator.<br><br>22.filename:/hypervisor/lib/crypto/mbedtls/sha256.c&nbsp;&nbsp;function:mbedtls_internal_sha256_process&nbsp;&nbsp;offset:230:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Space missing before or after binary operator.<br><br>23.filename:/hypervisor/lib/crypto/mbedtls/sha256.c&nbsp;&nbsp;function:mbedtls_internal_sha256_process&nbsp;&nbsp;offset:231:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Space missing before or after binary operator.<br><br>24.filename:/hypervisor/lib/crypto/mbedtls/sha256.c&nbsp;&nbsp;function:mbedtls_internal_sha256_process&nbsp;&nbsp;offset:233:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Space missing before or after binary operator.<br><br>25.filename:/hypervisor/lib/crypto/mbedtls/sha256.c&nbsp;&nbsp;function:mbedtls_internal_sha256_process&nbsp;&nbsp;offset:234:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Space missing before or after binary operator.<br><br>26.filename:/hypervisor/lib/crypto/mbedtls/sha256.c&nbsp;&nbsp;function:mbedtls_internal_sha256_process&nbsp;&nbsp;offset:236:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Space missing before or after binary operator.<br><br>27.filename:/hypervisor/lib/crypto/mbedtls/sha256.c&nbsp;&nbsp;function:mbedtls_internal_sha256_process&nbsp;&nbsp;offset:237:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Space missing before or after binary operator.<br><br>28.filename:/hypervisor/lib/crypto/mbedtls/sha256.c&nbsp;&nbsp;function:mbedtls_internal_sha256_process&nbsp;&nbsp;offset:239:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Space missing before or after binary operator.<br><br>29.filename:/hypervisor/lib/crypto/mbedtls/sha256.c&nbsp;&nbsp;function:mbedtls_internal_sha256_process&nbsp;&nbsp;offset:240:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Space missing before or after binary operator.<br><br>

**Comment by HuiHuangShi** [comment]
2289<br>4 new potential violations to the coding guideline detected. Please help check. Thanks!  <br><br>1.filename:/hypervisor/lib/crypto/mbedtls/md.c&nbsp;&nbsp;function:mbedtls_md_info_from_type&nbsp;&nbsp;offset:49:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Pointer assignment to wider scope.<br><br>2.filename:/hypervisor/lib/crypto/mbedtls/md.c&nbsp;&nbsp;function:mbedtls_md_hmac_starts&nbsp;&nbsp;offset:115:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Pointer not checked for null before use. : temp_key<br><br>3.filename:/hypervisor/lib/crypto/mbedtls/sha256.c&nbsp;&nbsp;function:r&nbsp;&nbsp;offset:122:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Implicit conversion: actual to formal param (MR). :  (int and unsigned int):  param  1<br><br>4.filename:/hypervisor/lib/crypto/mbedtls/sha256.c&nbsp;&nbsp;function:r&nbsp;&nbsp;offset:122:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Signed/unsigned conversion without cast. :  (int and unsigned int):  param  1<br><br>

**Comment by GangSecurity** [comment]
I didn't see any lines violate the 4 rules, I think these 4 items are false positive.

**Comment by HuiHuangShi** [comment]
>           I didn't see any lines violate the 4 rules, I think these 4 items are false positive.

4 is false positive,1-3 should provide justification.

**Comment by HuiHuangShi** [comment]
pls fill justification after update table

**Comment by wenlingz** [comment]
OK to verify

**Comment by HuiHuangShi** [comment]
2289<br>4 new potential violations to the coding guideline detected. Please help check. Thanks!  <br><br>1.filename:/hypervisor/lib/crypto/mbedtls/md.c&nbsp;&nbsp;function:mbedtls_md_info_from_type&nbsp;&nbsp;offset:49:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Pointer assignment to wider scope.<br><br>2.filename:/hypervisor/lib/crypto/mbedtls/md.c&nbsp;&nbsp;function:mbedtls_md_hmac_starts&nbsp;&nbsp;offset:115:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Pointer not checked for null before use. : temp_key<br><br>3.filename:/hypervisor/lib/crypto/mbedtls/sha256.c&nbsp;&nbsp;function:r&nbsp;&nbsp;offset:122:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Implicit conversion: actual to formal param (MR). :  (int and unsigned int):  param  1<br><br>4.filename:/hypervisor/lib/crypto/mbedtls/sha256.c&nbsp;&nbsp;function:r&nbsp;&nbsp;offset:122:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Signed/unsigned conversion without cast. :  (int and unsigned int):  param  1<br><br>

**Comment by HuiHuangShi** [comment]
2289<br>4 new potential violations to the coding guideline detected. Please help check. Thanks!  <br><br>1.filename:/hypervisor/lib/crypto/mbedtls/md.c&nbsp;&nbsp;function:mbedtls_md_info_from_type&nbsp;&nbsp;offset:49:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Pointer assignment to wider scope.<br><br>2.filename:/hypervisor/lib/crypto/mbedtls/md.c&nbsp;&nbsp;function:mbedtls_md_hmac_starts&nbsp;&nbsp;offset:115:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Pointer not checked for null before use. : temp_key<br><br>3.filename:/hypervisor/lib/crypto/mbedtls/sha256.c&nbsp;&nbsp;function:r&nbsp;&nbsp;offset:122:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Implicit conversion: actual to formal param (MR). :  (int and unsigned int):  param  1<br><br>4.filename:/hypervisor/lib/crypto/mbedtls/sha256.c&nbsp;&nbsp;function:r&nbsp;&nbsp;offset:122:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Signed/unsigned conversion without cast. :  (int and unsigned int):  param  1<br><br>

**Pull request merged**
