### PR TITLE
fix "goto detected:exception_inject"

### PR DESCRIPTION
**Pull request by HuiHuangShi**
V1->V2:
    rename is_exception_inject to has_exception.
V2->V3:
    remove the else statement and add new if statement to check
has_exception.

Misra C requires not allowed to use goto.

Tracked-On: #861
Signed-off-by: Huihuang Shi <huihuang.shi@intel.com>
Acked-by: Eddie Dong <eddie.dong@intel.com>

### CODE REVIEW

**Comment by acrnsi** [comment]
Ok to verify

**Comment by HuiHuangShi** [comment]
2255<br>No new violations to the coding guideline detected.

**Comment by HuiHuangShi** [comment]
2255<br>No new violations to the coding guideline detected.

**Comment by HuiHuangShi** [comment]
2255<br>No new violations to the coding guideline detected.

**Pull request merged**
