### PR TITLE
dynamic vcpu configuration: backport to release_1.6

### PR DESCRIPTION
**Pull request by ZideChen0**
Notes:  depending on PR #4684 to be merged to master.
 
These two commits don't belong to vcpu dynamic configuration, but need to include them in order to be able to apply other patches:

aa5169810d08 hv: some coding refinement in hypercall.c
cfff8fd2d948 hv: move error message logging into gpa copy APIs

### CODE REVIEW

**Comment by HuiHuangShi** [comment]
8 new potential violations to the coding guideline detected. Please help check. Thanks!<br><1> config:sharing_config filename:/hypervisor/arch/x86/configs/vm_config.c func:sanitize_vm_config offset:126<br> reason:Function return value potentially unused. : (vm_config)->vcpu_num<br><2> config:part_config filename:/hypervisor/arch/x86/configs/vm_config.c func:sanitize_vm_config offset:126<br> reason:Function return value potentially unused. : (vm_config)->vcpu_num<br><3> config:part_config filename:/hypervisor/arch/x86/guest/vm.c func:create_vm offset:504<br> reason:Potentially infinite loop found.<br><4> config:sharing_config filename:/hypervisor/arch/x86/guest/vm.c func:create_vm offset:504<br> reason:Potentially infinite loop found.<br><5> config:sharing_config filename:/hypervisor/common/hypercall.c func:hcall_create_vm offset:175<br> reason:Function return value potentially unused. : (vm_config)->vcpu_num<br><6> config:part_config filename:/hypervisor/common/hypercall.c func:hcall_create_vm offset:175<br> reason:Function return value potentially unused. : (vm_config)->vcpu_num<br><7> config:common filename:/hypervisor/arch/x86/guest/guest_memory.c func:copy_from_gpa offset:412<br> reason:Cast from pointer to integral type. : (void* to unsigned long): ( uint64_t ) h_ptr<br><8> config:common filename:/hypervisor/arch/x86/guest/guest_memory.c func:copy_to_gpa offset:431<br> reason:Cast from pointer to integral type. : (void* to unsigned long): ( uint64_t ) h_ptr<br><br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by HuiHuangShi** [comment]
8 new potential violations to the coding guideline detected. Please help check. Thanks!<br><1> config:sharing_config filename:/hypervisor/arch/x86/configs/vm_config.c func:sanitize_vm_config offset:126<br> reason:Function return value potentially unused. : (vm_config)->vcpu_num<br><2> config:part_config filename:/hypervisor/arch/x86/configs/vm_config.c func:sanitize_vm_config offset:126<br> reason:Function return value potentially unused. : (vm_config)->vcpu_num<br><3> config:part_config filename:/hypervisor/arch/x86/guest/vm.c func:create_vm offset:504<br> reason:Potentially infinite loop found.<br><4> config:sharing_config filename:/hypervisor/arch/x86/guest/vm.c func:create_vm offset:504<br> reason:Potentially infinite loop found.<br><5> config:sharing_config filename:/hypervisor/common/hypercall.c func:hcall_create_vm offset:175<br> reason:Function return value potentially unused. : (vm_config)->vcpu_num<br><6> config:part_config filename:/hypervisor/common/hypercall.c func:hcall_create_vm offset:175<br> reason:Function return value potentially unused. : (vm_config)->vcpu_num<br><7> config:common filename:/hypervisor/arch/x86/guest/guest_memory.c func:copy_from_gpa offset:412<br> reason:Cast from pointer to integral type. : (void* to unsigned long): ( uint64_t ) h_ptr<br><8> config:common filename:/hypervisor/arch/x86/guest/guest_memory.c func:copy_to_gpa offset:431<br> reason:Cast from pointer to integral type. : (void* to unsigned long): ( uint64_t ) h_ptr<br><br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by wenlingz** [comment]
@ZideChen0  build fail, please refer log:
 scenarios/industry/vm_configurations.c:42:4: error: 'struct acrn_vm_config' has no member named 'pcpu_affinity_bitmap'; did     you mean 'cpu_affinity_bitmap'?
142    42 |   .pcpu_affinity_bitmap = VM1_CONFIG_CPU_AFFINITY,
143       |    ^~~~~~~~~~~~~~~~~~~~
144       |    cpu_affinity_bitmap
145 scenarios/industry/vm_configurations.c:55:4: error: 'struct acrn_vm_config' has no member named 'pcpu_affinity_bitmap'; did     you mean 'cpu_affinity_bitmap'?
146    55 |   .pcpu_affinity_bitmap = VM2_CONFIG_CPU_AFFINITY,
147       |    ^~~~~~~~~~~~~~~~~~~~
148       |    cpu_affinity_bitmap
149 make[1]: *** [Makefile:539: /root/workspace/acrn-hypervisor-premerge-build-image/artifact/out/hypervisor/scenarios/industry    /vm_configurations.o] Error 1
150 make[1]: Leaving directory '/root/workspace/acrn-hypervisor-premerge-build-image/acrn-hypervisor/hypervisor'
151 make: *** [Makefile:164: hypervisor] Error 2
152 make: Leaving directory '/root/workspace/acrn-hypervisor-premerge-build-image/acrn-hypervisor'

**Comment by HuiHuangShi** [comment]
8 new potential violations to the coding guideline detected. Please help check. Thanks!<br><1> config:sharing_config filename:/hypervisor/arch/x86/configs/vm_config.c func:sanitize_vm_config offset:126<br> reason:Function return value potentially unused. : (vm_config)->vcpu_num<br><2> config:part_config filename:/hypervisor/arch/x86/configs/vm_config.c func:sanitize_vm_config offset:126<br> reason:Function return value potentially unused. : (vm_config)->vcpu_num<br><3> config:part_config filename:/hypervisor/arch/x86/guest/vm.c func:create_vm offset:504<br> reason:Potentially infinite loop found.<br><4> config:sharing_config filename:/hypervisor/arch/x86/guest/vm.c func:create_vm offset:504<br> reason:Potentially infinite loop found.<br><5> config:sharing_config filename:/hypervisor/common/hypercall.c func:hcall_create_vm offset:175<br> reason:Function return value potentially unused. : (vm_config)->vcpu_num<br><6> config:part_config filename:/hypervisor/common/hypercall.c func:hcall_create_vm offset:175<br> reason:Function return value potentially unused. : (vm_config)->vcpu_num<br><7> config:common filename:/hypervisor/arch/x86/guest/guest_memory.c func:copy_from_gpa offset:412<br> reason:Cast from pointer to integral type. : (void* to unsigned long): ( uint64_t ) h_ptr<br><8> config:common filename:/hypervisor/arch/x86/guest/guest_memory.c func:copy_to_gpa offset:431<br> reason:Cast from pointer to integral type. : (void* to unsigned long): ( uint64_t ) h_ptr<br><br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by wenlingz** [comment]
@fyin1 please help approve this PR, thanks

**Pull request merged**
