### PR TITLE
hv: refine vlapic_calc_dest()

### PR DESCRIPTION
**Pull request by lyan3**
This commit extracts the common logic of vlapic_calc_dest() and vlapic_calc_dest_lapic_pt()
to static inline functions, in order to make vlapic_calc_dest() clean and easy to read.

Tracked-On: #1842
Signed-off-by: Yan, Like <like.yan@intel.com>

### CODE REVIEW

**Comment by HuiHuangShi** [comment]
21 new potential violations to the coding guideline detected. Please help check. Thanks!<br><1> config:part_config filename:/hypervisor/arch/x86/guest/vlapic.c func:set_dest_mask_phys offset:1035<br> reason:Pointer param should be declared pointer to const. : vm<br><2> config:sharing_config filename:/hypervisor/arch/x86/guest/vlapic.c func:set_dest_mask_phys offset:1035<br> reason:Pointer param should be declared pointer to const. : vm<br><3> config:sharing_config filename:/hypervisor/arch/x86/guest/vlapic.c func:is_dest_field_matched offset:1051<br> reason:Pointer param should be declared pointer to const. : vlapic<br><4> config:part_config filename:/hypervisor/arch/x86/guest/vlapic.c func:is_dest_field_matched offset:1051<br> reason:Pointer param should be declared pointer to const. : vlapic<br><5> config:part_config filename:/hypervisor/arch/x86/guest/vlapic.c func:vlapic_calc_dest offset:1107<br> reason:Procedure contains UR data flow anomalies. : vcpu_id<br><6> config:sharing_config filename:/hypervisor/arch/x86/guest/vlapic.c func:vlapic_calc_dest offset:1107<br> reason:Procedure contains UR data flow anomalies. : vcpu_id<br><7> config:common filename:/hypervisor/arch/x86/guest/vlapic.c func:vlapic_calc_dest offset:1121<br> reason:Inconsistent usage of loop control variable.<br><8> config:common filename:/hypervisor/arch/x86/guest/vlapic.c func:vlapic_calc_dest offset:1121<br> reason:For loop incrementation is not simple.<br><9> config:sharing_config filename:/hypervisor/arch/x86/guest/vlapic.c func:vlapic_calc_dest offset:1121<br> reason:Expression has side effects. : vcpu_id<br><10> config:part_config filename:/hypervisor/arch/x86/guest/vlapic.c func:vlapic_calc_dest offset:1121<br> reason:Expression has side effects. : vcpu_id<br><11> config:common filename:/hypervisor/arch/x86/guest/vlapic.c func:vlapic_calc_dest offset:1121<br> reason:Type conversion without cast. :  (enum vm_state and enum vcpu_state): vcpu -> state != VCPU_OFFLINE<br><12> config:common filename:/hypervisor/arch/x86/guest/vlapic.c func:vlapic_calc_dest offset:1121<br> reason:For loop initialisation is not simple.<br><13> config:common filename:/hypervisor/arch/x86/guest/vlapic.c func:vlapic_calc_dest offset:1121<br> reason:Use of comma operator.<br><14> config:common filename:/hypervisor/arch/x86/guest/vlapic.c func:vlapic_calc_dest offset:1121<br> reason:No space after semi colon in for expression.<br><15> config:common filename:/hypervisor/arch/x86/guest/vlapic.c func:vlapic_calc_dest offset:1121<br> reason:No brackets to loop body.<br><16> config:common filename:/hypervisor/arch/x86/guest/vlapic.c func:vlapic_calc_dest offset:1121<br> reason:Assignment operation in expression.<br><17> config:sharing_config filename:/hypervisor/arch/x86/guest/vlapic.c func:vlapic_calc_dest offset:1121<br> reason:Pointer not checked for null before use. : vcpu<br><18> config:part_config filename:/hypervisor/arch/x86/guest/vlapic.c func:vlapic_calc_dest offset:1121<br> reason:Pointer not checked for null before use. : vcpu<br><19> config:common filename:/hypervisor/arch/x86/guest/vlapic.c func:vlapic_calc_dest offset:1123<br> reason:No space between if, while, for and expresn.<br><20> config:sharing_config filename:/hypervisor/arch/x86/guest/vlapic.c func:vlapic_calc_dest offset:1143<br> reason:Pointer assigned to NULL may be dereferenced. : lowprio_dest<br><21> config:part_config filename:/hypervisor/arch/x86/guest/vlapic.c func:vlapic_calc_dest offset:1143<br> reason:Pointer assigned to NULL may be dereferenced. : lowprio_dest<br><br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by HuiHuangShi** [comment]
21 new potential violations to the coding guideline detected. Please help check. Thanks!<br><1> config:part_config filename:/hypervisor/arch/x86/guest/vlapic.c func:set_dest_mask_phys offset:1035<br> reason:Pointer param should be declared pointer to const. : vm<br><2> config:sharing_config filename:/hypervisor/arch/x86/guest/vlapic.c func:set_dest_mask_phys offset:1035<br> reason:Pointer param should be declared pointer to const. : vm<br><3> config:sharing_config filename:/hypervisor/arch/x86/guest/vlapic.c func:is_dest_field_matched offset:1051<br> reason:Pointer param should be declared pointer to const. : vlapic<br><4> config:part_config filename:/hypervisor/arch/x86/guest/vlapic.c func:is_dest_field_matched offset:1051<br> reason:Pointer param should be declared pointer to const. : vlapic<br><5> config:part_config filename:/hypervisor/arch/x86/guest/vlapic.c func:vlapic_calc_dest offset:1107<br> reason:Procedure contains UR data flow anomalies. : vcpu_id<br><6> config:sharing_config filename:/hypervisor/arch/x86/guest/vlapic.c func:vlapic_calc_dest offset:1107<br> reason:Procedure contains UR data flow anomalies. : vcpu_id<br><7> config:common filename:/hypervisor/arch/x86/guest/vlapic.c func:vlapic_calc_dest offset:1121<br> reason:Inconsistent usage of loop control variable.<br><8> config:common filename:/hypervisor/arch/x86/guest/vlapic.c func:vlapic_calc_dest offset:1121<br> reason:For loop incrementation is not simple.<br><9> config:sharing_config filename:/hypervisor/arch/x86/guest/vlapic.c func:vlapic_calc_dest offset:1121<br> reason:Expression has side effects. : vcpu_id<br><10> config:part_config filename:/hypervisor/arch/x86/guest/vlapic.c func:vlapic_calc_dest offset:1121<br> reason:Expression has side effects. : vcpu_id<br><11> config:common filename:/hypervisor/arch/x86/guest/vlapic.c func:vlapic_calc_dest offset:1121<br> reason:Type conversion without cast. :  (enum vm_state and enum vcpu_state): vcpu -> state != VCPU_OFFLINE<br><12> config:common filename:/hypervisor/arch/x86/guest/vlapic.c func:vlapic_calc_dest offset:1121<br> reason:For loop initialisation is not simple.<br><13> config:common filename:/hypervisor/arch/x86/guest/vlapic.c func:vlapic_calc_dest offset:1121<br> reason:Use of comma operator.<br><14> config:common filename:/hypervisor/arch/x86/guest/vlapic.c func:vlapic_calc_dest offset:1121<br> reason:No space after semi colon in for expression.<br><15> config:common filename:/hypervisor/arch/x86/guest/vlapic.c func:vlapic_calc_dest offset:1121<br> reason:No brackets to loop body.<br><16> config:common filename:/hypervisor/arch/x86/guest/vlapic.c func:vlapic_calc_dest offset:1121<br> reason:Assignment operation in expression.<br><17> config:sharing_config filename:/hypervisor/arch/x86/guest/vlapic.c func:vlapic_calc_dest offset:1121<br> reason:Pointer not checked for null before use. : vcpu<br><18> config:part_config filename:/hypervisor/arch/x86/guest/vlapic.c func:vlapic_calc_dest offset:1121<br> reason:Pointer not checked for null before use. : vcpu<br><19> config:common filename:/hypervisor/arch/x86/guest/vlapic.c func:vlapic_calc_dest offset:1123<br> reason:No space between if, while, for and expresn.<br><20> config:sharing_config filename:/hypervisor/arch/x86/guest/vlapic.c func:vlapic_calc_dest offset:1143<br> reason:Pointer assigned to NULL may be dereferenced. : lowprio_dest<br><21> config:part_config filename:/hypervisor/arch/x86/guest/vlapic.c func:vlapic_calc_dest offset:1143<br> reason:Pointer assigned to NULL may be dereferenced. : lowprio_dest<br><br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by lyan3** [comment]
- Violation <1>&<2>: non-const "struct acrn_vm *vm" is required by vm_apicid2vcpu_id();
- Violation <3>&<4>  fixed;
- Violation <19> fixed;
- Violation <20> & <21> are false positive;
- The other violations are cuased by "foreach_vcpu()".

**Comment by HuiHuangShi** [comment]
18 new potential violations to the coding guideline detected. Please help check. Thanks!<br><1> config:part_config filename:/hypervisor/arch/x86/guest/vlapic.c func:set_dest_mask_phys offset:1035<br> reason:Pointer param should be declared pointer to const. : vm<br><2> config:sharing_config filename:/hypervisor/arch/x86/guest/vlapic.c func:set_dest_mask_phys offset:1035<br> reason:Pointer param should be declared pointer to const. : vm<br><3> config:part_config filename:/hypervisor/arch/x86/guest/vlapic.c func:vlapic_calc_dest offset:1107<br> reason:Procedure contains UR data flow anomalies. : vcpu_id<br><4> config:sharing_config filename:/hypervisor/arch/x86/guest/vlapic.c func:vlapic_calc_dest offset:1107<br> reason:Procedure contains UR data flow anomalies. : vcpu_id<br><5> config:common filename:/hypervisor/arch/x86/guest/vlapic.c func:vlapic_calc_dest offset:1121<br> reason:Inconsistent usage of loop control variable.<br><6> config:common filename:/hypervisor/arch/x86/guest/vlapic.c func:vlapic_calc_dest offset:1121<br> reason:For loop incrementation is not simple.<br><7> config:sharing_config filename:/hypervisor/arch/x86/guest/vlapic.c func:vlapic_calc_dest offset:1121<br> reason:Expression has side effects. : vcpu_id<br><8> config:part_config filename:/hypervisor/arch/x86/guest/vlapic.c func:vlapic_calc_dest offset:1121<br> reason:Expression has side effects. : vcpu_id<br><9> config:common filename:/hypervisor/arch/x86/guest/vlapic.c func:vlapic_calc_dest offset:1121<br> reason:Type conversion without cast. :  (enum vm_state and enum vcpu_state): vcpu -> state != VCPU_OFFLINE<br><10> config:common filename:/hypervisor/arch/x86/guest/vlapic.c func:vlapic_calc_dest offset:1121<br> reason:For loop initialisation is not simple.<br><11> config:common filename:/hypervisor/arch/x86/guest/vlapic.c func:vlapic_calc_dest offset:1121<br> reason:Use of comma operator.<br><12> config:common filename:/hypervisor/arch/x86/guest/vlapic.c func:vlapic_calc_dest offset:1121<br> reason:No space after semi colon in for expression.<br><13> config:common filename:/hypervisor/arch/x86/guest/vlapic.c func:vlapic_calc_dest offset:1121<br> reason:No brackets to loop body.<br><14> config:common filename:/hypervisor/arch/x86/guest/vlapic.c func:vlapic_calc_dest offset:1121<br> reason:Assignment operation in expression.<br><15> config:sharing_config filename:/hypervisor/arch/x86/guest/vlapic.c func:vlapic_calc_dest offset:1121<br> reason:Pointer not checked for null before use. : vcpu<br><16> config:part_config filename:/hypervisor/arch/x86/guest/vlapic.c func:vlapic_calc_dest offset:1121<br> reason:Pointer not checked for null before use. : vcpu<br><17> config:sharing_config filename:/hypervisor/arch/x86/guest/vlapic.c func:vlapic_calc_dest offset:1143<br> reason:Pointer assigned to NULL may be dereferenced. : lowprio_dest<br><18> config:part_config filename:/hypervisor/arch/x86/guest/vlapic.c func:vlapic_calc_dest offset:1143<br> reason:Pointer assigned to NULL may be dereferenced. : lowprio_dest<br><br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by HuiHuangShi** [comment]
18 new potential violations to the coding guideline detected. Please help check. Thanks!<br><1> config:part_config filename:/hypervisor/arch/x86/guest/vlapic.c func:set_dest_mask_phys offset:1035<br> reason:Pointer param should be declared pointer to const. : vm<br><2> config:sharing_config filename:/hypervisor/arch/x86/guest/vlapic.c func:set_dest_mask_phys offset:1035<br> reason:Pointer param should be declared pointer to const. : vm<br><3> config:part_config filename:/hypervisor/arch/x86/guest/vlapic.c func:vlapic_calc_dest offset:1107<br> reason:Procedure contains UR data flow anomalies. : vcpu_id<br><4> config:sharing_config filename:/hypervisor/arch/x86/guest/vlapic.c func:vlapic_calc_dest offset:1107<br> reason:Procedure contains UR data flow anomalies. : vcpu_id<br><5> config:common filename:/hypervisor/arch/x86/guest/vlapic.c func:vlapic_calc_dest offset:1121<br> reason:Inconsistent usage of loop control variable.<br><6> config:common filename:/hypervisor/arch/x86/guest/vlapic.c func:vlapic_calc_dest offset:1121<br> reason:For loop incrementation is not simple.<br><7> config:sharing_config filename:/hypervisor/arch/x86/guest/vlapic.c func:vlapic_calc_dest offset:1121<br> reason:Expression has side effects. : vcpu_id<br><8> config:part_config filename:/hypervisor/arch/x86/guest/vlapic.c func:vlapic_calc_dest offset:1121<br> reason:Expression has side effects. : vcpu_id<br><9> config:common filename:/hypervisor/arch/x86/guest/vlapic.c func:vlapic_calc_dest offset:1121<br> reason:Type conversion without cast. :  (enum vm_state and enum vcpu_state): vcpu -> state != VCPU_OFFLINE<br><10> config:common filename:/hypervisor/arch/x86/guest/vlapic.c func:vlapic_calc_dest offset:1121<br> reason:For loop initialisation is not simple.<br><11> config:common filename:/hypervisor/arch/x86/guest/vlapic.c func:vlapic_calc_dest offset:1121<br> reason:Use of comma operator.<br><12> config:common filename:/hypervisor/arch/x86/guest/vlapic.c func:vlapic_calc_dest offset:1121<br> reason:No space after semi colon in for expression.<br><13> config:common filename:/hypervisor/arch/x86/guest/vlapic.c func:vlapic_calc_dest offset:1121<br> reason:No brackets to loop body.<br><14> config:common filename:/hypervisor/arch/x86/guest/vlapic.c func:vlapic_calc_dest offset:1121<br> reason:Assignment operation in expression.<br><15> config:sharing_config filename:/hypervisor/arch/x86/guest/vlapic.c func:vlapic_calc_dest offset:1121<br> reason:Pointer not checked for null before use. : vcpu<br><16> config:part_config filename:/hypervisor/arch/x86/guest/vlapic.c func:vlapic_calc_dest offset:1121<br> reason:Pointer not checked for null before use. : vcpu<br><17> config:sharing_config filename:/hypervisor/arch/x86/guest/vlapic.c func:vlapic_calc_dest offset:1143<br> reason:Pointer assigned to NULL may be dereferenced. : lowprio_dest<br><18> config:part_config filename:/hypervisor/arch/x86/guest/vlapic.c func:vlapic_calc_dest offset:1143<br> reason:Pointer assigned to NULL may be dereferenced. : lowprio_dest<br><br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by HuiHuangShi** [comment]
> 18 new potential violations to the coding guideline detected. Please help check. Thanks!
> <1> config:part_config filename:/hypervisor/arch/x86/guest/vlapic.c func:set_dest_mask_phys offset:1035
> reason:Pointer param should be declared pointer to const. : vm
> <2> config:sharing_config filename:/hypervisor/arch/x86/guest/vlapic.c func:set_dest_mask_phys offset:1035
> reason:Pointer param should be declared pointer to const. : vm
> <3> config:part_config filename:/hypervisor/arch/x86/guest/vlapic.c func:vlapic_calc_dest offset:1107
> reason:Procedure contains UR data flow anomalies. : vcpu_id
> <4> config:sharing_config filename:/hypervisor/arch/x86/guest/vlapic.c func:vlapic_calc_dest offset:1107
> reason:Procedure contains UR data flow anomalies. : vcpu_id
> <5> config:common filename:/hypervisor/arch/x86/guest/vlapic.c func:vlapic_calc_dest offset:1121
> reason:Inconsistent usage of loop control variable.
> <6> config:common filename:/hypervisor/arch/x86/guest/vlapic.c func:vlapic_calc_dest offset:1121
> reason:For loop incrementation is not simple.
> <7> config:sharing_config filename:/hypervisor/arch/x86/guest/vlapic.c func:vlapic_calc_dest offset:1121
> reason:Expression has side effects. : vcpu_id
> <8> config:part_config filename:/hypervisor/arch/x86/guest/vlapic.c func:vlapic_calc_dest offset:1121
> reason:Expression has side effects. : vcpu_id
> <9> config:common filename:/hypervisor/arch/x86/guest/vlapic.c func:vlapic_calc_dest offset:1121
> reason:Type conversion without cast. : (enum vm_state and enum vcpu_state): vcpu -> state != VCPU_OFFLINE
> <10> config:common filename:/hypervisor/arch/x86/guest/vlapic.c func:vlapic_calc_dest offset:1121
> reason:For loop initialisation is not simple.
> <11> config:common filename:/hypervisor/arch/x86/guest/vlapic.c func:vlapic_calc_dest offset:1121
> reason:Use of comma operator.
> <12> config:common filename:/hypervisor/arch/x86/guest/vlapic.c func:vlapic_calc_dest offset:1121
> reason:No space after semi colon in for expression.
> <13> config:common filename:/hypervisor/arch/x86/guest/vlapic.c func:vlapic_calc_dest offset:1121
> reason:No brackets to loop body.
> <14> config:common filename:/hypervisor/arch/x86/guest/vlapic.c func:vlapic_calc_dest offset:1121
> reason:Assignment operation in expression.
> <15> config:sharing_config filename:/hypervisor/arch/x86/guest/vlapic.c func:vlapic_calc_dest offset:1121
> reason:Pointer not checked for null before use. : vcpu
> <16> config:part_config filename:/hypervisor/arch/x86/guest/vlapic.c func:vlapic_calc_dest offset:1121
> reason:Pointer not checked for null before use. : vcpu
> <17> config:sharing_config filename:/hypervisor/arch/x86/guest/vlapic.c func:vlapic_calc_dest offset:1143
> reason:Pointer assigned to NULL may be dereferenced. : lowprio_dest
> <18> config:part_config filename:/hypervisor/arch/x86/guest/vlapic.c func:vlapic_calc_dest offset:1143
> reason:Pointer assigned to NULL may be dereferenced. : lowprio_dest
> 
> No New Name Conflict
> 
> No New Function Declaration/Definition Mismatch

All of above is false positive

**Pull request merged**
