### PR TITLE
support dm to create and destroy ivshmem devices in hypervisor

### PR DESCRIPTION
**Pull request by liuyuan-GitHub**
This patch list add HC_CREATE_VDEV and HC_DESTROY_VDEV two hypercalls to create
and destroy ivshmem vdev in hypervisor.

Users can use ivshmem inter-vm communication hv-land by specifying the hv:/ prefix of
shared memory region name in the device model parameter.

v2: add two hypercalls to create and destroy an emulated device in hypervisor

v3: 1) replace HC_CREATE_DEVICE and HC_DESTROY_DEVICE hypercalls with HC_CREATE_VDEV
       and HC_DESTROY_VDEV
    2) replace IC_CREATE_DEVICE and IC_DESTROY_DEVICE ioctls with IC_CREATE_HV_VDEV
       and IC_DESTROY_HV_VDEV

v4: 1) remove unnecessary parameter from hcall_create_vdev and hcall_destroy_vdev
    2) refine ivshmem dm-land and hv-land in device model

Tracked-On: #4853

Signed-off-by: Yuan Liu <yuan1.liu@intel.com>
Acked-by: Wang, Yu1 <yu1.wang@intel.com>
Acked-by: Eddie Dong <eddie.dong@intel.com>

### CODE REVIEW

**Comment by HuiHuangShi** [comment]
No new violations to the coding guideline detected.<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by HuiHuangShi** [comment]
No new violations to the coding guideline detected.<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by HuiHuangShi** [comment]
No new violations to the coding guideline detected.<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by fuzhongl** [comment]
@liuyuan-GitHub make doc fail, please refer:
make[1]: Entering directory '/home/acrn/acrn-hypervisor/doc'

New errors/warnings found, please fix them:
==============================================

/home/acrn/acrn-hypervisor/hypervisor/include/common/hypercall.h:337: warning: argument 'vmid' of command @param is not found in the argument list of hcall_create_vdev(struct acrn_vm *vm, struct acrn_vm *target_vm, uint64_t param1, uint64_t param2)
/home/acrn/acrn-hypervisor/hypervisor/include/common/hypercall.h:337: warning: argument 'param' of command @param is not found in the argument list of hcall_create_vdev(struct acrn_vm *vm, struct acrn_vm *target_vm, uint64_t param1, uint64_t param2)
/home/acrn/acrn-hypervisor/hypervisor/include/common/hypercall.h:346: warning: The following parameters of hcall_create_vdev(struct acrn_vm *vm, struct acrn_vm *target_vm, uint64_t param1, uint64_t param2) are not documented:
  parameter 'vm'
  parameter 'target_vm'
  parameter 'param1'
  parameter 'param2'
/home/acrn/acrn-hypervisor/hypervisor/include/common/hypercall.h:349: warning: argument 'vmid' of command @param is not found in the argument list of hcall_destroy_vdev(struct acrn_vm *vm, struct acrn_vm *target_vm, uint64_t param1, uint64_t param2)
/home/acrn/acrn-hypervisor/hypervisor/include/common/hypercall.h:349: warning: argument 'param' of command @param is not found in the argument list of hcall_destroy_vdev(struct acrn_vm *vm, struct acrn_vm *target_vm, uint64_t param1, uint64_t param2)
/home/acrn/acrn-hypervisor/hypervisor/include/common/hypercall.h:358: warning: The following parameters of hcall_destroy_vdev(struct acrn_vm *vm, struct acrn_vm *target_vm, uint64_t param1, uint64_t param2) are not documented:
  parameter 'vm'
  parameter 'target_vm'
  parameter 'param1'
  parameter 'param2'
/home/acrn/acrn-hypervisor/hypervisor/include/common/hypercall.h:337: warning: argument 'vmid' of command @param is not found in the argument list of hcall_create_vdev(struct acrn_vm *vm, struct acrn_vm *target_vm, uint64_t param1, uint64_t param2)
/home/acrn/acrn-hypervisor/hypervisor/include/common/hypercall.h:337: warning: argument 'param' of command @param is not found in the argument list of hcall_create_vdev(struct acrn_vm *vm, struct acrn_vm *target_vm, uint64_t param1, uint64_t param2)
/home/acrn/acrn-hypervisor/hypervisor/include/common/hypercall.h:346: warning: The following parameters of hcall_create_vdev(struct acrn_vm *vm, struct acrn_vm *target_vm, uint64_t param1, uint64_t param2) are not documented:
  parameter 'vm'
  parameter 'target_vm'
  parameter 'param1'
  parameter 'param2'
/home/acrn/acrn-hypervisor/hypervisor/include/common/hypercall.h:349: warning: argument 'vmid' of command @param is not found in the argument list of hcall_destroy_vdev(struct acrn_vm *vm, struct acrn_vm *target_vm, uint64_t param1, uint64_t param2)
/home/acrn/acrn-hypervisor/hypervisor/include/common/hypercall.h:349: warning: argument 'param' of command @param is not found in the argument list of hcall_destroy_vdev(struct acrn_vm *vm, struct acrn_vm *target_vm, uint64_t param1, uint64_t param2)
/home/acrn/acrn-hypervisor/hypervisor/include/common/hypercall.h:358: warning: The following parameters of hcall_destroy_vdev(struct acrn_vm *vm, struct acrn_vm *target_vm, uint64_t param1, uint64_t param2) are not documented:
  parameter 'vm'
  parameter 'target_vm'
  parameter 'param1'
  parameter 'param2'
/home/acrn/acrn-hypervisor/hypervisor/include/common/hypercall.h:337: warning: argument 'vmid' of command @param is not found in the argument list of hcall_create_vdev(struct acrn_vm *vm, struct acrn_vm *target_vm, uint64_t param1, uint64_t param2)
/home/acrn/acrn-hypervisor/hypervisor/include/common/hypercall.h:337: warning: argument 'param' of command @param is not found in the argument list of hcall_create_vdev(struct acrn_vm *vm, struct acrn_vm *target_vm, uint64_t param1, uint64_t param2)
/home/acrn/acrn-hypervisor/hypervisor/include/common/hypercall.h:346: warning: The following parameters of hcall_create_vdev(struct acrn_vm *vm, struct acrn_vm *target_vm, uint64_t param1, uint64_t param2) are not documented:
  parameter 'vm'
  parameter 'target_vm'
  parameter 'param1'
  parameter 'param2'
/home/acrn/acrn-hypervisor/hypervisor/include/common/hypercall.h:349: warning: argument 'vmid' of command @param is not found in the argument list of hcall_destroy_vdev(struct acrn_vm *vm, struct acrn_vm *target_vm, uint64_t param1, uint64_t param2)
/home/acrn/acrn-hypervisor/hypervisor/include/common/hypercall.h:349: warning: argument 'param' of command @param is not found in the argument list of hcall_destroy_vdev(struct acrn_vm *vm, struct acrn_vm *target_vm, uint64_t param1, uint64_t param2)
/home/acrn/acrn-hypervisor/hypervisor/include/common/hypercall.h:358: warning: The following parameters of hcall_destroy_vdev(struct acrn_vm *vm, struct acrn_vm *target_vm, uint64_t param1, uint64_t param2) are not documented:
  parameter 'vm'
  parameter 'target_vm'
  parameter 'param1'
  parameter 'param2'
/home/acrn/acrn-hypervisor/hypervisor/include/common/hypercall.h:337: warning: argument 'vmid' of command @param is not found in the argument list of hcall_create_vdev(struct acrn_vm *vm, struct acrn_vm *target_vm, uint64_t param1, uint64_t param2)
/home/acrn/acrn-hypervisor/hypervisor/include/common/hypercall.h:337: warning: argument 'param' of command @param is not found in the argument list of hcall_create_vdev(struct acrn_vm *vm, struct acrn_vm *target_vm, uint64_t param1, uint64_t param2)
/home/acrn/acrn-hypervisor/hypervisor/include/common/hypercall.h:346: warning: The following parameters of hcall_create_vdev(struct acrn_vm *vm, struct acrn_vm *target_vm, uint64_t param1, uint64_t param2) are not documented:
  parameter 'vm'
  parameter 'target_vm'
  parameter 'param1'
  parameter 'param2'
/home/acrn/acrn-hypervisor/hypervisor/include/common/hypercall.h:349: warning: argument 'vmid' of command @param is not found in the argument list of hcall_destroy_vdev(struct acrn_vm *vm, struct acrn_vm *target_vm, uint64_t param1, uint64_t param2)
/home/acrn/acrn-hypervisor/hypervisor/include/common/hypercall.h:349: warning: argument 'param' of command @param is not found in the argument list of hcall_destroy_vdev(struct acrn_vm *vm, struct acrn_vm *target_vm, uint64_t param1, uint64_t param2)
/home/acrn/acrn-hypervisor/hypervisor/include/common/hypercall.h:358: warning: The following parameters of hcall_destroy_vdev(struct acrn_vm *vm, struct acrn_vm *target_vm, uint64_t param1, uint64_t param2) are not documented:
  parameter 'vm'
  parameter 'target_vm'
  parameter 'param1'
  parameter 'param2'
/home/acrn/acrn-hypervisor/build/doc/rst/api/hypercall_api.rst:12: WARNING: Invalid definition: Expected identifier in nested name. [error at 21]
  union acrn_emul_dev::@12  acrn_emul_dev::dev_id
  ---------------------^
/home/acrn/acrn-hypervisor/build/doc/rst/api/hypercall_api.rst:12: WARNING: Invalid definition: Expected identifier in nested name. [error at 21]
  union acrn_emul_dev::@26  acrn_emul_dev::dev_id
  ---------------------^
/home/acrn/acrn-hypervisor/build/doc/rst/api/hypercall_api.rst:12: WARNING: Invalid definition: Expected identifier in nested name. [error at 0]

  ^
/home/acrn/acrn-hypervisor/build/doc/rst/api/hypercall_api.rst:12: WARNING: Invalid definition: Expected identifier in nested name. [error at 0]

  ^
/home/acrn/acrn-hypervisor/build/doc/rst/api/hypercall_api.rst:12: WARNING: Invalid definition: Expected end of definition. [error at 13]
  acrn_emul_dev.dev_id
  -------------^
/home/acrn/acrn-hypervisor/build/doc/rst/api/hypercall_api.rst:12: WARNING: Invalid definition: Expected identifier in nested name. [error at 0]

  ^
/home/acrn/acrn-hypervisor/build/doc/rst/api/hypercall_api.rst:12: WARNING: Invalid definition: Expected identifier in nested name. [error at 0]

  ^
/home/acrn/acrn-hypervisor/build/doc/rst/api/hypercall_api.rst:12: WARNING: Invalid definition: Expected identifier in nested name. [error at 0]

  ^
/home/acrn/acrn-hypervisor/build/doc/rst/api/hypercall_api.rst:12: WARNING: Invalid definition: Expected end of definition. [error at 13]
  acrn_emul_dev.dev_id.fields
  -------------^

Makefile:60: recipe for target 'html' failed
make[1]: *** [html] Error 1
make[1]: Leaving directory '/home/acrn/acrn-hypervisor/doc'
Makefile:207: recipe for target 'doc' failed
make: *** [doc] Error 2
root@acrn-OptiPlex-9010:/home/acrn/acrn-hypervisor#



wenling zhang

**Comment by wenlingz** [comment]
@liuyuan-GitHub  make doc fail, please check log

**Comment by wenlingz** [comment]
@ywan170 please help approve this PR, thanks

**Review by ywan170 — APPROVED** [review]

**Pull request merged**
