### PR TITLE
HV: series patch to fix vm id by uuid

### PR DESCRIPTION
**Pull request by jsun26intel**
- use term of UUID;
- return bool in sanitize_vm_config;
- make vm id statically by uuid;
- show VM UUID in shell

Tracked-On: #2291

Signed-off-by: Victor Sun <victor.sun@intel.com>
Acked-by: Eddie Dong <eddie.dong@intel.com>

### CODE REVIEW

**Comment by HuiHuangShi** [comment]
25 new potential violations to the coding guideline detected. Please help check. Thanks!<br><1> config:part_config filename:/hypervisor/arch/x86/configs/vm_config.c func:uuid_is_equal offset:23<br> reason:Pointer param should be declared pointer to const. : uuid1<br><2> config:sharing_config filename:/hypervisor/arch/x86/configs/vm_config.c func:uuid_is_equal offset:23<br> reason:Pointer param should be declared pointer to const. : uuid2<br><3> config:part_config filename:/hypervisor/arch/x86/configs/vm_config.c func:uuid_is_equal offset:23<br> reason:Pointer param should be declared pointer to const. : uuid2<br><4> config:sharing_config filename:/hypervisor/arch/x86/configs/vm_config.c func:uuid_is_equal offset:23<br> reason:Pointer param should be declared pointer to const. : uuid1<br><5> config:common filename:/hypervisor/arch/x86/configs/vm_config.c func:uuid_is_equal offset:25<br> reason:Casting operation to a pointer. : (void* to struct uuid_u*): ( union uuid_u * ) uuid1<br><6> config:common filename:/hypervisor/arch/x86/configs/vm_config.c func:uuid_is_equal offset:25<br> reason:Casting operation on a pointer. : (void* to struct uuid_u*): ( union uuid_u * ) uuid1<br><7> config:common filename:/hypervisor/arch/x86/configs/vm_config.c func:uuid_is_equal offset:26<br> reason:Casting operation to a pointer. : (void* to struct uuid_u*): ( union uuid_u * ) uuid2<br><8> config:common filename:/hypervisor/arch/x86/configs/vm_config.c func:uuid_is_equal offset:26<br> reason:Casting operation on a pointer. : (void* to struct uuid_u*): ( union uuid_u * ) uuid2<br><9> config:part_config filename:/hypervisor/arch/x86/configs/vm_config.c func:vm_has_matched_uuid offset:36<br> reason:Pointer param should be declared pointer to const. : uuid<br><10> config:sharing_config filename:/hypervisor/arch/x86/configs/vm_config.c func:vm_has_matched_uuid offset:36<br> reason:Pointer param should be declared pointer to const. : uuid<br><11> config:part_config filename:/hypervisor/arch/x86/configs/vm_config.c func:vm_has_matched_uuid offset:40<br> reason:Pointer not checked for null before use. : vm_config<br><12> config:sharing_config filename:/hypervisor/arch/x86/configs/vm_config.c func:vm_has_matched_uuid offset:40<br> reason:Pointer not checked for null before use. : vm_config<br><13> config:sharing_config filename:/hypervisor/arch/x86/configs/vm_config.c func:check_vm_uuid_collision offset:57<br> reason:Pointer not checked for null before use. : following_config<br><14> config:sharing_config filename:/hypervisor/arch/x86/configs/vm_config.c func:check_vm_uuid_collision offset:57<br> reason:Pointer not checked for null before use. : start_config<br><15> config:part_config filename:/hypervisor/arch/x86/configs/vm_config.c func:check_vm_uuid_collision offset:57<br> reason:Pointer not checked for null before use. : following_config<br><16> config:part_config filename:/hypervisor/arch/x86/configs/vm_config.c func:check_vm_uuid_collision offset:57<br> reason:Pointer not checked for null before use. : start_config<br><17> config:part_config filename:/hypervisor/include/arch/x86/vm_config.h func: offset:74<br> reason:Global variable should be declared const. : vm_configs.uuid.value8<br><18> config:sharing_config filename:/hypervisor/include/arch/x86/vm_config.h func: offset:74<br> reason:Global variable should be declared const. : vm_configs.uuid<br><19> config:part_config filename:/hypervisor/include/arch/x86/vm_config.h func: offset:74<br> reason:Global variable should be declared const. : vm_configs.uuid<br><20> config:sharing_config filename:/hypervisor/include/arch/x86/vm_config.h func: offset:74<br> reason:Global variable should be declared const. : vm_configs.uuid.value64<br><21> config:sharing_config filename:/hypervisor/include/arch/x86/vm_config.h func: offset:74<br> reason:Global variable should be declared const. : vm_configs.uuid.value8<br><22> config:part_config filename:/hypervisor/include/arch/x86/vm_config.h func: offset:74<br> reason:Global variable should be declared const. : vm_configs.uuid.value64<br><23> config:part_config filename:/hypervisor/arch/x86/guest/vm.c func:get_vmid_by_uuid offset:37<br> reason:Pointer param should be declared pointer to const. : uuid<br><24> config:sharing_config filename:/hypervisor/arch/x86/guest/vm.c func:get_vmid_by_uuid offset:37<br> reason:Pointer param should be declared pointer to const. : uuid<br><25> config:common filename:/hypervisor/arch/x86/guest/vm.c func:get_vmid_by_uuid offset:41<br> reason:No space between if, while, for and expresn.<br><br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by HuiHuangShi** [comment]
> 25 new potential violations to the coding guideline detected. Please help check. Thanks!
> <1> config:part_config filename:/hypervisor/arch/x86/configs/vm_config.c func:uuid_is_equal offset:23
> reason:Pointer param should be declared pointer to const. : uuid1
> <2> config:sharing_config filename:/hypervisor/arch/x86/configs/vm_config.c func:uuid_is_equal offset:23
> reason:Pointer param should be declared pointer to const. : uuid2
> <3> config:part_config filename:/hypervisor/arch/x86/configs/vm_config.c func:uuid_is_equal offset:23
> reason:Pointer param should be declared pointer to const. : uuid2
> <4> config:sharing_config filename:/hypervisor/arch/x86/configs/vm_config.c func:uuid_is_equal offset:23
> reason:Pointer param should be declared pointer to const. : uuid1
> <5> config:common filename:/hypervisor/arch/x86/configs/vm_config.c func:uuid_is_equal offset:25
> reason:Casting operation to a pointer. : (void* to struct uuid_u*): ( union uuid_u * ) uuid1
> <6> config:common filename:/hypervisor/arch/x86/configs/vm_config.c func:uuid_is_equal offset:25
> reason:Casting operation on a pointer. : (void* to struct uuid_u*): ( union uuid_u * ) uuid1
> <7> config:common filename:/hypervisor/arch/x86/configs/vm_config.c func:uuid_is_equal offset:26
> reason:Casting operation to a pointer. : (void* to struct uuid_u*): ( union uuid_u * ) uuid2
> <8> config:common filename:/hypervisor/arch/x86/configs/vm_config.c func:uuid_is_equal offset:26
> reason:Casting operation on a pointer. : (void* to struct uuid_u*): ( union uuid_u * ) uuid2
> <9> config:part_config filename:/hypervisor/arch/x86/configs/vm_config.c func:vm_has_matched_uuid offset:36
> reason:Pointer param should be declared pointer to const. : uuid
> <10> config:sharing_config filename:/hypervisor/arch/x86/configs/vm_config.c func:vm_has_matched_uuid offset:36
> reason:Pointer param should be declared pointer to const. : uuid
> <11> config:part_config filename:/hypervisor/arch/x86/configs/vm_config.c func:vm_has_matched_uuid offset:40
> reason:Pointer not checked for null before use. : vm_config
> <12> config:sharing_config filename:/hypervisor/arch/x86/configs/vm_config.c func:vm_has_matched_uuid offset:40
> reason:Pointer not checked for null before use. : vm_config
> <13> config:sharing_config filename:/hypervisor/arch/x86/configs/vm_config.c func:check_vm_uuid_collision offset:57
> reason:Pointer not checked for null before use. : following_config
> <14> config:sharing_config filename:/hypervisor/arch/x86/configs/vm_config.c func:check_vm_uuid_collision offset:57
> reason:Pointer not checked for null before use. : start_config
> <15> config:part_config filename:/hypervisor/arch/x86/configs/vm_config.c func:check_vm_uuid_collision offset:57
> reason:Pointer not checked for null before use. : following_config
> <16> config:part_config filename:/hypervisor/arch/x86/configs/vm_config.c func:check_vm_uuid_collision offset:57
> reason:Pointer not checked for null before use. : start_config
> <17> config:part_config filename:/hypervisor/include/arch/x86/vm_config.h func: offset:74
> reason:Global variable should be declared const. : vm_configs.uuid.value8
> <18> config:sharing_config filename:/hypervisor/include/arch/x86/vm_config.h func: offset:74
> reason:Global variable should be declared const. : vm_configs.uuid
> <19> config:part_config filename:/hypervisor/include/arch/x86/vm_config.h func: offset:74
> reason:Global variable should be declared const. : vm_configs.uuid
> <20> config:sharing_config filename:/hypervisor/include/arch/x86/vm_config.h func: offset:74
> reason:Global variable should be declared const. : vm_configs.uuid.value64
> <21> config:sharing_config filename:/hypervisor/include/arch/x86/vm_config.h func: offset:74
> reason:Global variable should be declared const. : vm_configs.uuid.value8
> <22> config:part_config filename:/hypervisor/include/arch/x86/vm_config.h func: offset:74
> reason:Global variable should be declared const. : vm_configs.uuid.value64
> <23> config:part_config filename:/hypervisor/arch/x86/guest/vm.c func:get_vmid_by_uuid offset:37
> reason:Pointer param should be declared pointer to const. : uuid
> <24> config:sharing_config filename:/hypervisor/arch/x86/guest/vm.c func:get_vmid_by_uuid offset:37
> reason:Pointer param should be declared pointer to const. : uuid
> <25> config:common filename:/hypervisor/arch/x86/guest/vm.c func:get_vmid_by_uuid offset:41
> reason:No space between if, while, for and expresn.
> 
> No New Name Conflict
> 
> No New Function Declaration/Definition Mismatch

Type conversion should give strong justification, the conversion between "union uuid type"  and "uint8 *" is not a good way to give strong justification.

**Comment by jsun26intel** [comment]
@dongyaozu 
Per huihuang, type convention is not preferred by LDRA, unless there is a strong justification. Do you have comments?

**Comment by dongyaozu** [comment]
You don't need type conversion

**Comment by HuiHuangShi** [comment]
out of time

**Comment by HuiHuangShi** [comment]
12 new potential violations to the coding guideline detected. Please help check. Thanks!<br><1> config:sharing_config filename:/hypervisor/include/arch/x86/vm_config.h func: offset:69<br> reason:Global variable should be declared const. : vm_configs.uuid.value8<br><2> config:sharing_config filename:/hypervisor/include/arch/x86/vm_config.h func: offset:69<br> reason:Global variable should be declared const. : vm_configs.uuid.value64<br><3> config:part_config filename:/hypervisor/include/arch/x86/vm_config.h func: offset:69<br> reason:Global variable should be declared const. : vm_configs.uuid<br><4> config:part_config filename:/hypervisor/include/arch/x86/vm_config.h func: offset:69<br> reason:Global variable should be declared const. : vm_configs.uuid.value64<br><5> config:sharing_config filename:/hypervisor/include/arch/x86/vm_config.h func: offset:69<br> reason:Global variable should be declared const. : vm_configs.uuid<br><6> config:part_config filename:/hypervisor/include/arch/x86/vm_config.h func: offset:69<br> reason:Global variable should be declared const. : vm_configs.uuid.value8<br><7> config:part_config filename:/hypervisor/arch/x86/configs/vm_config.c func:vm_has_matched_uuid offset:36<br> reason:Pointer not checked for null before use. : vm_config<br><8> config:sharing_config filename:/hypervisor/arch/x86/configs/vm_config.c func:vm_has_matched_uuid offset:36<br> reason:Pointer not checked for null before use. : vm_config<br><9> config:sharing_config filename:/hypervisor/arch/x86/configs/vm_config.c func:check_vm_uuid_collision offset:53<br> reason:Pointer not checked for null before use. : following_config<br><10> config:sharing_config filename:/hypervisor/arch/x86/configs/vm_config.c func:check_vm_uuid_collision offset:53<br> reason:Pointer not checked for null before use. : start_config<br><11> config:part_config filename:/hypervisor/arch/x86/configs/vm_config.c func:check_vm_uuid_collision offset:53<br> reason:Pointer not checked for null before use. : following_config<br><12> config:part_config filename:/hypervisor/arch/x86/configs/vm_config.c func:check_vm_uuid_collision offset:53<br> reason:Pointer not checked for null before use. : start_config<br><br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by HuiHuangShi** [comment]
out of time

**Comment by HuiHuangShi** [comment]
out of license

**Comment by HuiHuangShi** [comment]
12 new potential violations to the coding guideline detected. Please help check. Thanks!<br><1> config:sharing_config filename:/hypervisor/include/arch/x86/vm_config.h func: offset:69<br> reason:Global variable should be declared const. : vm_configs.uuid.value8<br><2> config:sharing_config filename:/hypervisor/include/arch/x86/vm_config.h func: offset:69<br> reason:Global variable should be declared const. : vm_configs.uuid.value64<br><3> config:part_config filename:/hypervisor/include/arch/x86/vm_config.h func: offset:69<br> reason:Global variable should be declared const. : vm_configs.uuid<br><4> config:part_config filename:/hypervisor/include/arch/x86/vm_config.h func: offset:69<br> reason:Global variable should be declared const. : vm_configs.uuid.value64<br><5> config:sharing_config filename:/hypervisor/include/arch/x86/vm_config.h func: offset:69<br> reason:Global variable should be declared const. : vm_configs.uuid<br><6> config:part_config filename:/hypervisor/include/arch/x86/vm_config.h func: offset:69<br> reason:Global variable should be declared const. : vm_configs.uuid.value8<br><7> config:part_config filename:/hypervisor/arch/x86/configs/vm_config.c func:vm_has_matched_uuid offset:36<br> reason:Pointer not checked for null before use. : vm_config<br><8> config:sharing_config filename:/hypervisor/arch/x86/configs/vm_config.c func:vm_has_matched_uuid offset:36<br> reason:Pointer not checked for null before use. : vm_config<br><9> config:sharing_config filename:/hypervisor/arch/x86/configs/vm_config.c func:check_vm_uuid_collision offset:53<br> reason:Pointer not checked for null before use. : following_config<br><10> config:sharing_config filename:/hypervisor/arch/x86/configs/vm_config.c func:check_vm_uuid_collision offset:53<br> reason:Pointer not checked for null before use. : start_config<br><11> config:part_config filename:/hypervisor/arch/x86/configs/vm_config.c func:check_vm_uuid_collision offset:53<br> reason:Pointer not checked for null before use. : following_config<br><12> config:part_config filename:/hypervisor/arch/x86/configs/vm_config.c func:check_vm_uuid_collision offset:53<br> reason:Pointer not checked for null before use. : start_config<br><br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by HuiHuangShi** [comment]
12 new potential violations to the coding guideline detected. Please help check. Thanks!<br><1> config:sharing_config filename:/hypervisor/include/arch/x86/vm_config.h func: offset:69<br> reason:Global variable should be declared const. : vm_configs.uuid.value8<br><2> config:sharing_config filename:/hypervisor/include/arch/x86/vm_config.h func: offset:69<br> reason:Global variable should be declared const. : vm_configs.uuid.value64<br><3> config:part_config filename:/hypervisor/include/arch/x86/vm_config.h func: offset:69<br> reason:Global variable should be declared const. : vm_configs.uuid<br><4> config:part_config filename:/hypervisor/include/arch/x86/vm_config.h func: offset:69<br> reason:Global variable should be declared const. : vm_configs.uuid.value64<br><5> config:sharing_config filename:/hypervisor/include/arch/x86/vm_config.h func: offset:69<br> reason:Global variable should be declared const. : vm_configs.uuid<br><6> config:part_config filename:/hypervisor/include/arch/x86/vm_config.h func: offset:69<br> reason:Global variable should be declared const. : vm_configs.uuid.value8<br><7> config:part_config filename:/hypervisor/arch/x86/configs/vm_config.c func:vm_has_matched_uuid offset:36<br> reason:Pointer not checked for null before use. : vm_config<br><8> config:sharing_config filename:/hypervisor/arch/x86/configs/vm_config.c func:vm_has_matched_uuid offset:36<br> reason:Pointer not checked for null before use. : vm_config<br><9> config:sharing_config filename:/hypervisor/arch/x86/configs/vm_config.c func:check_vm_uuid_collision offset:53<br> reason:Pointer not checked for null before use. : following_config<br><10> config:sharing_config filename:/hypervisor/arch/x86/configs/vm_config.c func:check_vm_uuid_collision offset:53<br> reason:Pointer not checked for null before use. : start_config<br><11> config:part_config filename:/hypervisor/arch/x86/configs/vm_config.c func:check_vm_uuid_collision offset:53<br> reason:Pointer not checked for null before use. : following_config<br><12> config:part_config filename:/hypervisor/arch/x86/configs/vm_config.c func:check_vm_uuid_collision offset:53<br> reason:Pointer not checked for null before use. : start_config<br><br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by HuiHuangShi** [comment]
25 new potential violations to the coding guideline detected. Please help check. Thanks!<br><1> config:common filename:/hypervisor/arch/x86/configs/vm_config.c func:uuid_is_equal offset:24<br> reason:Casting operation to a pointer. : (unsigned char* to unsigned long*): ( uint64_t * ) & uuid1 [ 0 ]<br><2> config:common filename:/hypervisor/arch/x86/configs/vm_config.c func:uuid_is_equal offset:24<br> reason:Cast on a constant value.                    : uuid1<br><3> config:common filename:/hypervisor/arch/x86/configs/vm_config.c func:uuid_is_equal offset:24<br> reason:Casting operation on a pointer. : (unsigned char* to unsigned long*): ( uint64_t * ) & uuid1 [ 0 ]<br><4> config:common filename:/hypervisor/arch/x86/configs/vm_config.c func:uuid_is_equal offset:24<br> reason:Declaration does not specify an array.       : uuid1<br><5> config:common filename:/hypervisor/arch/x86/configs/vm_config.c func:uuid_is_equal offset:25<br> reason:Casting operation to a pointer. : (unsigned char* to unsigned long*): ( uint64_t * ) & uuid1 [ 8 ]<br><6> config:common filename:/hypervisor/arch/x86/configs/vm_config.c func:uuid_is_equal offset:25<br> reason:Cast on a constant value.                    : uuid1<br><7> config:common filename:/hypervisor/arch/x86/configs/vm_config.c func:uuid_is_equal offset:25<br> reason:Casting operation on a pointer. : (unsigned char* to unsigned long*): ( uint64_t * ) & uuid1 [ 8 ]<br><8> config:common filename:/hypervisor/arch/x86/configs/vm_config.c func:uuid_is_equal offset:25<br> reason:Declaration does not specify an array.       : uuid1<br><9> config:common filename:/hypervisor/arch/x86/configs/vm_config.c func:uuid_is_equal offset:26<br> reason:Casting operation to a pointer. : (unsigned char* to unsigned long*): ( uint64_t * ) & uuid2 [ 0 ]<br><10> config:common filename:/hypervisor/arch/x86/configs/vm_config.c func:uuid_is_equal offset:26<br> reason:Cast on a constant value.                    : uuid2<br><11> config:common filename:/hypervisor/arch/x86/configs/vm_config.c func:uuid_is_equal offset:26<br> reason:Casting operation on a pointer. : (unsigned char* to unsigned long*): ( uint64_t * ) & uuid2 [ 0 ]<br><12> config:common filename:/hypervisor/arch/x86/configs/vm_config.c func:uuid_is_equal offset:26<br> reason:Declaration does not specify an array.       : uuid2<br><13> config:common filename:/hypervisor/arch/x86/configs/vm_config.c func:uuid_is_equal offset:27<br> reason:Casting operation to a pointer. : (unsigned char* to unsigned long*): ( uint64_t * ) & uuid2 [ 8 ]<br><14> config:common filename:/hypervisor/arch/x86/configs/vm_config.c func:uuid_is_equal offset:27<br> reason:Cast on a constant value.                    : uuid2<br><15> config:common filename:/hypervisor/arch/x86/configs/vm_config.c func:uuid_is_equal offset:27<br> reason:Casting operation on a pointer. : (unsigned char* to unsigned long*): ( uint64_t * ) & uuid2 [ 8 ]<br><16> config:common filename:/hypervisor/arch/x86/configs/vm_config.c func:uuid_is_equal offset:27<br> reason:Declaration does not specify an array.       : uuid2<br><17> config:part_config filename:/hypervisor/arch/x86/configs/vm_config.c func:vm_has_matched_uuid offset:41<br> reason:Pointer not checked for null before use. : vm_config<br><18> config:sharing_config filename:/hypervisor/arch/x86/configs/vm_config.c func:vm_has_matched_uuid offset:41<br> reason:Pointer not checked for null before use. : vm_config<br><19> config:common filename:/hypervisor/arch/x86/configs/vm_config.c func:vm_has_matched_uuid offset:41<br> reason:Declaration does not specify an array.       : uuid<br><20> config:sharing_config filename:/hypervisor/arch/x86/configs/vm_config.c func:check_vm_uuid_collision offset:58<br> reason:Pointer not checked for null before use. : following_config<br><21> config:sharing_config filename:/hypervisor/arch/x86/configs/vm_config.c func:check_vm_uuid_collision offset:58<br> reason:Pointer not checked for null before use. : start_config<br><22> config:part_config filename:/hypervisor/arch/x86/configs/vm_config.c func:check_vm_uuid_collision offset:58<br> reason:Pointer not checked for null before use. : following_config<br><23> config:part_config filename:/hypervisor/arch/x86/configs/vm_config.c func:check_vm_uuid_collision offset:58<br> reason:Pointer not checked for null before use. : start_config<br><24> config:part_config filename:/hypervisor/include/arch/x86/vm_config.h func: offset:69<br> reason:Global variable should be declared const. : vm_configs.uuid<br><25> config:sharing_config filename:/hypervisor/include/arch/x86/vm_config.h func: offset:69<br> reason:Global variable should be declared const. : vm_configs.uuid<br><br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by HuiHuangShi** [comment]
19 new potential violations to the coding guideline detected. Please help check. Thanks!<br><1> config:common filename:/hypervisor/arch/x86/configs/vm_config.c func:uuid_is_equal offset:24<br> reason:Casting operation to a pointer. : (unsigned char* to unsigned long*): ( uint64_t * ) uuid1<br><2> config:common filename:/hypervisor/arch/x86/configs/vm_config.c func:uuid_is_equal offset:24<br> reason:Cast on a constant value.                    : uuid1<br><3> config:common filename:/hypervisor/arch/x86/configs/vm_config.c func:uuid_is_equal offset:24<br> reason:Casting operation on a pointer. : (unsigned char* to unsigned long*): ( uint64_t * ) uuid1<br><4> config:common filename:/hypervisor/arch/x86/configs/vm_config.c func:uuid_is_equal offset:25<br> reason:Casting operation to a pointer. : (unsigned char* to unsigned long*): ( uint64_t * ) ( uuid1 + 8 )<br><5> config:common filename:/hypervisor/arch/x86/configs/vm_config.c func:uuid_is_equal offset:25<br> reason:Casting operation on a pointer. : (unsigned char* to unsigned long*): ( uint64_t * ) ( uuid1 + 8 )<br><6> config:common filename:/hypervisor/arch/x86/configs/vm_config.c func:uuid_is_equal offset:26<br> reason:Casting operation to a pointer. : (unsigned char* to unsigned long*): ( uint64_t * ) uuid2<br><7> config:common filename:/hypervisor/arch/x86/configs/vm_config.c func:uuid_is_equal offset:26<br> reason:Cast on a constant value.                    : uuid2<br><8> config:common filename:/hypervisor/arch/x86/configs/vm_config.c func:uuid_is_equal offset:26<br> reason:Casting operation on a pointer. : (unsigned char* to unsigned long*): ( uint64_t * ) uuid2<br><9> config:common filename:/hypervisor/arch/x86/configs/vm_config.c func:uuid_is_equal offset:27<br> reason:Casting operation to a pointer. : (unsigned char* to unsigned long*): ( uint64_t * ) ( uuid2 + 8 )<br><10> config:common filename:/hypervisor/arch/x86/configs/vm_config.c func:uuid_is_equal offset:27<br> reason:Casting operation on a pointer. : (unsigned char* to unsigned long*): ( uint64_t * ) ( uuid2 + 8 )<br><11> config:part_config filename:/hypervisor/arch/x86/configs/vm_config.c func:vm_has_matched_uuid offset:41<br> reason:Pointer not checked for null before use. : vm_config<br><12> config:sharing_config filename:/hypervisor/arch/x86/configs/vm_config.c func:vm_has_matched_uuid offset:41<br> reason:Pointer not checked for null before use. : vm_config<br><13> config:common filename:/hypervisor/arch/x86/configs/vm_config.c func:vm_has_matched_uuid offset:41<br> reason:Declaration does not specify an array.       : uuid<br><14> config:sharing_config filename:/hypervisor/arch/x86/configs/vm_config.c func:check_vm_uuid_collision offset:58<br> reason:Pointer not checked for null before use. : following_config<br><15> config:sharing_config filename:/hypervisor/arch/x86/configs/vm_config.c func:check_vm_uuid_collision offset:58<br> reason:Pointer not checked for null before use. : start_config<br><16> config:part_config filename:/hypervisor/arch/x86/configs/vm_config.c func:check_vm_uuid_collision offset:58<br> reason:Pointer not checked for null before use. : following_config<br><17> config:part_config filename:/hypervisor/arch/x86/configs/vm_config.c func:check_vm_uuid_collision offset:58<br> reason:Pointer not checked for null before use. : start_config<br><18> config:part_config filename:/hypervisor/include/arch/x86/vm_config.h func: offset:69<br> reason:Global variable should be declared const. : vm_configs.uuid<br><19> config:sharing_config filename:/hypervisor/include/arch/x86/vm_config.h func: offset:69<br> reason:Global variable should be declared const. : vm_configs.uuid<br><br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by HuiHuangShi** [comment]
19 new potential violations to the coding guideline detected. Please help check. Thanks!<br><1> config:common filename:/hypervisor/arch/x86/configs/vm_config.c func:uuid_is_equal offset:24<br> reason:Casting operation to a pointer. : (unsigned char* to unsigned long*): ( uint64_t * ) uuid1<br><2> config:common filename:/hypervisor/arch/x86/configs/vm_config.c func:uuid_is_equal offset:24<br> reason:Cast on a constant value.                    : uuid1<br><3> config:common filename:/hypervisor/arch/x86/configs/vm_config.c func:uuid_is_equal offset:24<br> reason:Casting operation on a pointer. : (unsigned char* to unsigned long*): ( uint64_t * ) uuid1<br><4> config:common filename:/hypervisor/arch/x86/configs/vm_config.c func:uuid_is_equal offset:25<br> reason:Casting operation to a pointer. : (unsigned char* to unsigned long*): ( uint64_t * ) ( uuid1 + 8 )<br><5> config:common filename:/hypervisor/arch/x86/configs/vm_config.c func:uuid_is_equal offset:25<br> reason:Casting operation on a pointer. : (unsigned char* to unsigned long*): ( uint64_t * ) ( uuid1 + 8 )<br><6> config:common filename:/hypervisor/arch/x86/configs/vm_config.c func:uuid_is_equal offset:26<br> reason:Casting operation to a pointer. : (unsigned char* to unsigned long*): ( uint64_t * ) uuid2<br><7> config:common filename:/hypervisor/arch/x86/configs/vm_config.c func:uuid_is_equal offset:26<br> reason:Cast on a constant value.                    : uuid2<br><8> config:common filename:/hypervisor/arch/x86/configs/vm_config.c func:uuid_is_equal offset:26<br> reason:Casting operation on a pointer. : (unsigned char* to unsigned long*): ( uint64_t * ) uuid2<br><9> config:common filename:/hypervisor/arch/x86/configs/vm_config.c func:uuid_is_equal offset:27<br> reason:Casting operation to a pointer. : (unsigned char* to unsigned long*): ( uint64_t * ) ( uuid2 + 8 )<br><10> config:common filename:/hypervisor/arch/x86/configs/vm_config.c func:uuid_is_equal offset:27<br> reason:Casting operation on a pointer. : (unsigned char* to unsigned long*): ( uint64_t * ) ( uuid2 + 8 )<br><11> config:part_config filename:/hypervisor/arch/x86/configs/vm_config.c func:vm_has_matched_uuid offset:41<br> reason:Pointer not checked for null before use. : vm_config<br><12> config:sharing_config filename:/hypervisor/arch/x86/configs/vm_config.c func:vm_has_matched_uuid offset:41<br> reason:Pointer not checked for null before use. : vm_config<br><13> config:common filename:/hypervisor/arch/x86/configs/vm_config.c func:vm_has_matched_uuid offset:41<br> reason:Declaration does not specify an array.       : uuid<br><14> config:sharing_config filename:/hypervisor/arch/x86/configs/vm_config.c func:check_vm_uuid_collision offset:58<br> reason:Pointer not checked for null before use. : following_config<br><15> config:sharing_config filename:/hypervisor/arch/x86/configs/vm_config.c func:check_vm_uuid_collision offset:58<br> reason:Pointer not checked for null before use. : start_config<br><16> config:part_config filename:/hypervisor/arch/x86/configs/vm_config.c func:check_vm_uuid_collision offset:58<br> reason:Pointer not checked for null before use. : following_config<br><17> config:part_config filename:/hypervisor/arch/x86/configs/vm_config.c func:check_vm_uuid_collision offset:58<br> reason:Pointer not checked for null before use. : start_config<br><18> config:part_config filename:/hypervisor/include/arch/x86/vm_config.h func: offset:69<br> reason:Global variable should be declared const. : vm_configs.uuid<br><19> config:sharing_config filename:/hypervisor/include/arch/x86/vm_config.h func: offset:69<br> reason:Global variable should be declared const. : vm_configs.uuid<br><br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by HuiHuangShi** [comment]
out of time

**Comment by acrnsi** [comment]
Tested.It passed.

**Pull request merged**
