### PR TITLE
doc: refine ivshmem architecture diagram

### PR DESCRIPTION
**Pull request by liuyuan-GitHub**
refine the dm-land and hypervisor-land flows

Signed-off-by: Yuan Liu <yuan1.liu@intel.com>

### CODE REVIEW

**Comment by HuiHuangShi** [comment]
No new violations to the coding guideline detected.<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by liuyuan-GitHub** [comment]
> * Can you use a small "i" in `ivshmem` in the hypervisor box?
Thanks for reminding, I will fix `ivshmem` in the hv box.

> * Do we have two instances of `acrn-dm` running when multiple User VMs are running?
Yes, each post-launched VM is booted by one acrn-dm instance.

**Comment by dbkinder** [comment]
@gvancuts commented on what I would (lower case "i"  so it doesn't look like an "L")

**Comment by HuiHuangShi** [comment]
No new violations to the coding guideline detected.<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Pull request merged**
