### PR TITLE
doc: update CODEOWNERS for doc reviews

### PR DESCRIPTION
**Pull request by dbkinder**
Deb (@deb-intel) added as a reviewer for ACRN documentation.

Tracked-On: #3419
Signed-off-by: David B. Kinder <david.b.kinder@intel.com>

### CODE REVIEW

**Comment by HuiHuangShi** [comment]
No new violations to the coding guideline detected.<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by HuiHuangShi** [comment]
No new violations to the coding guideline detected.<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by acrnsi** [comment]
@dbkinder "Tracked-on" is error,It must be "Tracked-On" ,you should resubmit to modify “Tracked-on” in commits.

**Comment by HuiHuangShi** [comment]
No new violations to the coding guideline detected.<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Pull request merged**
