### PR TITLE
Documentation: update to AcrnGT official name

### PR DESCRIPTION
**Pull request by gvancuts**
Update the ACRN documentation to use the official name of GVT-g
in ACRN to "AcrnGT" (ACRN-GT was previously widely used).

Also update the few occurences of "GVT-G" to "GVT-g" to be
consistent across our documentation. This includes a couple of
file name updates.

Signed-off-by: Geoffroy Van Cutsem <geoffroy.vancutsem@intel.com>

### CODE REVIEW

**Comment by gvancuts** [comment]
To be 100% complete, a small patch should also be applied to the kernel (see below). Should I send this to the `acrn-kernel` repo as a Pull Request?

```
diff --git a/drivers/gpu/drm/i915/gvt/acrn-gvt.c b/drivers/gpu/drm/i915/gvt/acrn-gvt.c
index 73575af3eac9..96a2079eba49 100644
--- a/drivers/gpu/drm/i915/gvt/acrn-gvt.c
+++ b/drivers/gpu/drm/i915/gvt/acrn-gvt.c
@@ -46,7 +46,7 @@
 #include "acrn-gvt.h"
 
 MODULE_AUTHOR("Intel Corporation");
-MODULE_DESCRIPTION("ACRNGT mediated passthrough driver");
+MODULE_DESCRIPTION("AcrnGT mediated passthrough driver");
 MODULE_LICENSE("GPL");
 MODULE_VERSION("0.1");
 
diff --git a/drivers/gpu/drm/i915/gvt/acrn-gvt.h b/drivers/gpu/drm/i915/gvt/acrn-gvt.h
index 0799df2ec557..f69e00b29e34 100644
--- a/drivers/gpu/drm/i915/gvt/acrn-gvt.h
+++ b/drivers/gpu/drm/i915/gvt/acrn-gvt.h
@@ -61,7 +61,7 @@ struct acrngt_hvm_params {
 
 /*
  * struct gvt_acrngt should be a single instance to share global
- * information for ACRNGT module.
+ * information for AcrnGT module.
  */
 #define GVT_MAX_VGPU_INSTANCE 15
 struct gvt_acrngt {
```

**Comment by dbkinder** [comment]
I noticed there's an image in https://projectacrn.github.io/latest/developer-guides/GVT-G-porting.html that needs fixing too

**Comment by gvancuts** [comment]
Good catch @dbkinder !

@hwang37 , who could help amend the picture (I do not have the source file)

**Comment by hwang37** [comment]
@feijiang1 @minhe1 Do you have the original picture to replace "ACRN GT" to "AcrnGT"?

**Comment by feijiang1** [comment]
@hwang37 has created PR https://github.com/projectacrn/acrn-hypervisor/pull/1107 to update the image.

**Comment by gvancuts** [comment]
Rebased after #1107 was merged.

I've just realised that `APL_GVT-g-arch.png` also has an instance of `ACRN-GVT` that should be updated.

**Comment by dbkinder** [comment]
@gvancuts looks like there are merge conflicts to address please.

**Comment by gvancuts** [comment]
@dbkinder done

**Pull request merged**
