### PR TITLE
Release 2.5 fix pio bars

### PR DESCRIPTION
**Pull request by liujunming**

### CODE REVIEW

**Review by dongyaozu — COMMENTED** [review]
Why not use same with the solution of mainline ?

**Comment by liujunming** [comment]
> Why not use same with the solution of mainline ?

Hi, Eddie:

1. If we use the solution of mainline, we also need the change of config-tool component. For config-tool, there's much difference between 2.0 branch and mainline. So just adopt the solution in 2.6 branch to eliminate the change of config-tool component.
2. For the solution in 2.6 branch, it has been fully tested, so adopt the 2.6 solution for stability.

**Comment by wenlingz** [comment]
@yakuizhao please help approve this PR, thanks

**Review by yakuizhao — APPROVED** [review]
LGTM

**Review by yakuizhao — APPROVED** [review]
LGTM

**Review by yakuizhao — APPROVED** [review]
LGTM

**Comment by wenlingz** [comment]
> > Why not use same with the solution of mainline ?
> 
> Hi, Eddie:
> 
> 1. If we use the solution of mainline, we also need the change of config-tool component. So just adopt the solution in 2.6 branch to eliminate the change of config-tool component.
> 2. For the solution in 2.6 branch, it has been fully tested, so adopt the 2.6 solution for stability.

@dongyaozu  can we merge this PR now ? thanks

**Pull request merged**
