### PR TITLE
update launch_uos.sh to align with ACRN v0.1

### PR DESCRIPTION
**Pull request by ailun258**
update the kernel version to align with ACRN v0.1 and Clear version for UOS

Signed-off-by: ailun258 <ailin.yang@intel.com>

### CODE REVIEW

**Comment by NanlinXie** [comment]
Can one of the admins verify this patch?

**Comment by ailun258** [comment]
@jren1  please help review this and get approved

**Comment by ailun258** [comment]
@dongyaozu  please help approved this one,  i merged 2 commits into one

**Comment by dongyaozu** [comment]
@ailun258 This will conflict with PR 696. Not sure how you view them,

**Comment by ailun258** [comment]
@dongyaozu  no conflict with PR 696, 696 is to update acrn.conf for SOS.

**Comment by wenlingz** [comment]
verify+1

**Pull request merged**
