### PR TITLE
hv: vmsr: emulate ia32_misc_enable

### PR DESCRIPTION
**Pull request by binbinwu1**
Passthrough MSR IA32_MISC_ENABLE to guest has potential risk, since
some features used by HV depend on the setting of the MSR.
Also, writing the MSR is slower than a regular WRMSR. So it is expensive
to save/restore the value during VMExit/VMEntry.
This patch series emulate the MSR IA32_MISC_ENABLE read/write to isolate
some features that can't be controlled by guest.
The only feature can be controlled by guest is "ENABLE MONITOR FSM" when HV
doesn't use the feature.
This patch series also update some vcpuid according the value of IA32_MISC_ENABLE
from guest.

v1 -> v2:
Add some emulation in vcpuid according to the change of IA32_MISC_ENABLE.
Clear guest EFER.NXE when guest set "XD Disable".
Allow gust to control "ENABLE MONITOR FSM" feature if HV doesn't use the feaure.

v2 -> v3:
Merge ia32_misc_enable handling into one patch.
Merge vcpuid change into one patch.
If hardware has bug on monitor/mwait, ignore guest enabling of "ENABLE MONITOR FSM"

Tracked-On: #2834
Signed-off-by: Binbin Wu <binbin.wu@intel.com>
Acked-by: Eddie Dong <eddie.dong@intel.com>

### CODE REVIEW

**Comment by acrnsi** [comment]
OK to verify

**Comment by HuiHuangShi** [comment]
10 new potential violations to the coding guideline detected. Please help check. Thanks!<br><1> config:common filename:/hypervisor/arch/x86/guest/vcpuid.c func:guest_cpuid offset:297<br> reason:Cyclomatic complexity greater than 20.<br><2> config:common filename:/hypervisor/arch/x86/guest/vcpuid.c func:guest_cpuid offset:436<br> reason:Logical conjunctions need brackets.<br><3> config:common filename:/hypervisor/arch/x86/cpu_caps.c func:monitor_cap_buggy offset:60<br> reason:inline function should be declared static.   : monitor_cap_buggy<br><4> config:common filename:/hypervisor/arch/x86/cpu_caps.c func:is_fast_string_erms_supported_and_enabled offset:93<br> reason:Value is not of appropriate type. :  (unsigned int and unsigned long): ( misc_enable & (   1UL <<<br><5> config:common filename:/hypervisor/arch/x86/cpu_caps.c func:is_fast_string_erms_supported_and_enabled offset:93<br> reason:Implicit conversion of underlying type (MR). :  (unsigned int and unsigned long): ( misc_enable & (<br><6> config:part_config filename:/hypervisor/arch/x86/guest/vmsr.c func:set_guest_ia32_misc_enalbe offset:476<br> reason:Pointer param should be declared pointer to const. : vcpu<br><7> config:sharing_config filename:/hypervisor/arch/x86/guest/vmsr.c func:set_guest_ia32_misc_enalbe offset:476<br> reason:Pointer param should be declared pointer to const. : vcpu<br><8> config:common filename:/hypervisor/arch/x86/guest/vmsr.c func:set_guest_ia32_misc_enalbe offset:478<br> reason:Literal value requires a U suffix.           : 0<br><9> config:common filename:/hypervisor/arch/x86/guest/vmsr.c func:set_guest_ia32_misc_enalbe offset:506<br> reason:No space between if, while, for and expresn.<br><10> config:common filename:/hypervisor/arch/x86/guest/vmsr.c func:set_guest_ia32_misc_enalbe offset:506<br> reason:Logical conjunctions need brackets.<br><br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by HuiHuangShi** [comment]
out of time

**Comment by HuiHuangShi** [comment]
3 new potential violations to the coding guideline detected. Please help check. Thanks!<br><1> config:common filename:/hypervisor/arch/x86/guest/vcpuid.c func:guest_cpuid offset:297<br> reason:Cyclomatic complexity greater than 20.<br><2> config:part_config filename:/hypervisor/arch/x86/guest/vmsr.c func:set_guest_ia32_misc_enalbe offset:476<br> reason:Pointer param should be declared pointer to const. : vcpu<br><3> config:sharing_config filename:/hypervisor/arch/x86/guest/vmsr.c func:set_guest_ia32_misc_enalbe offset:476<br> reason:Pointer param should be declared pointer to const. : vcpu<br><br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by HuiHuangShi** [comment]
5 new potential violations to the coding guideline detected. Please help check. Thanks!<br><1> config:part_config filename:/hypervisor/arch/x86/guest/vcpuid.c func:guest_cpuid_01h offset:302<br> reason:Pointer param should be declared pointer to const. : eax<br><2> config:sharing_config filename:/hypervisor/arch/x86/guest/vcpuid.c func:guest_cpuid_01h offset:302<br> reason:Pointer param should be declared pointer to const. : eax<br><3> config:common filename:/hypervisor/arch/x86/guest/vcpuid.c func:guest_cpuid_0bh offset:392<br> reason:Space missing before or after binary operator.<br><4> config:part_config filename:/hypervisor/arch/x86/guest/vmsr.c func:set_guest_ia32_misc_enalbe offset:476<br> reason:Pointer param should be declared pointer to const. : vcpu<br><5> config:sharing_config filename:/hypervisor/arch/x86/guest/vmsr.c func:set_guest_ia32_misc_enalbe offset:476<br> reason:Pointer param should be declared pointer to const. : vcpu<br><br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by HuiHuangShi** [comment]
9 new potential violations to the coding guideline detected. Please help check. Thanks!<br><1> config:part_config filename:/hypervisor/arch/x86/guest/vcpuid.c func:guest_cpuid_01h offset:302<br> reason:Pointer param should be declared pointer to const. : vcpu<br><2> config:part_config filename:/hypervisor/arch/x86/guest/vcpuid.c func:guest_cpuid_01h offset:302<br> reason:Pointer param should be declared pointer to const. : eax<br><3> config:sharing_config filename:/hypervisor/arch/x86/guest/vcpuid.c func:guest_cpuid_01h offset:302<br> reason:Pointer param should be declared pointer to const. : eax<br><4> config:sharing_config filename:/hypervisor/arch/x86/guest/vcpuid.c func:guest_cpuid_01h offset:302<br> reason:Pointer param should be declared pointer to const. : vcpu<br><5> config:sharing_config filename:/hypervisor/arch/x86/guest/vcpuid.c func:guest_cpuid_0bh offset:362<br> reason:Pointer param should be declared pointer to const. : vcpu<br><6> config:part_config filename:/hypervisor/arch/x86/guest/vcpuid.c func:guest_cpuid_0bh offset:362<br> reason:Pointer param should be declared pointer to const. : vcpu<br><7> config:common filename:/hypervisor/arch/x86/guest/vcpuid.c func:guest_cpuid_0bh offset:392<br> reason:Space missing before or after binary operator.<br><8> config:part_config filename:/hypervisor/arch/x86/guest/vmsr.c func:set_guest_ia32_misc_enalbe offset:476<br> reason:Pointer param should be declared pointer to const. : vcpu<br><9> config:sharing_config filename:/hypervisor/arch/x86/guest/vmsr.c func:set_guest_ia32_misc_enalbe offset:476<br> reason:Pointer param should be declared pointer to const. : vcpu<br><br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by HuiHuangShi** [comment]
9 new potential violations to the coding guideline detected. Please help check. Thanks!<br><1> config:part_config filename:/hypervisor/arch/x86/guest/vcpuid.c func:guest_cpuid_01h offset:302<br> reason:Pointer param should be declared pointer to const. : vcpu<br><2> config:part_config filename:/hypervisor/arch/x86/guest/vcpuid.c func:guest_cpuid_01h offset:302<br> reason:Pointer param should be declared pointer to const. : eax<br><3> config:sharing_config filename:/hypervisor/arch/x86/guest/vcpuid.c func:guest_cpuid_01h offset:302<br> reason:Pointer param should be declared pointer to const. : eax<br><4> config:sharing_config filename:/hypervisor/arch/x86/guest/vcpuid.c func:guest_cpuid_01h offset:302<br> reason:Pointer param should be declared pointer to const. : vcpu<br><5> config:sharing_config filename:/hypervisor/arch/x86/guest/vcpuid.c func:guest_cpuid_0bh offset:362<br> reason:Pointer param should be declared pointer to const. : vcpu<br><6> config:part_config filename:/hypervisor/arch/x86/guest/vcpuid.c func:guest_cpuid_0bh offset:362<br> reason:Pointer param should be declared pointer to const. : vcpu<br><7> config:common filename:/hypervisor/arch/x86/guest/vcpuid.c func:guest_cpuid_0bh offset:392<br> reason:Space missing before or after binary operator.<br><8> config:part_config filename:/hypervisor/arch/x86/guest/vmsr.c func:set_guest_ia32_misc_enalbe offset:476<br> reason:Pointer param should be declared pointer to const. : vcpu<br><9> config:sharing_config filename:/hypervisor/arch/x86/guest/vmsr.c func:set_guest_ia32_misc_enalbe offset:476<br> reason:Pointer param should be declared pointer to const. : vcpu<br><br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Pull request merged**
