### PR TITLE
config_tools: apply pattern check to virtio devices

### PR DESCRIPTION
**Pull request by Kunhui-Li**
Apply pattern checks to network interface name and virtio input id. Report error if regex doesn't match.

### CODE REVIEW

**Comment by acrnsi** [comment]
Can one of the admins verify this patch?

**Comment by junjiemao1** [comment]
Why do we have to add the regex patterns in vue files rather than in the XML schema?

**Comment by Kunhui-Li** [comment]
> Why do we have to add the regex patterns in vue files rather than in the XML schema?

The regex pattern has been added to the XML schema. But it doesn't work for the customized widgets.
So this patch adds pattern checks similar to the ivshmem in vue files.

**Comment by junjiemao1** [comment]
> > Why do we have to add the regex patterns in vue files rather than in the XML schema?
> 
> The regex pattern has been added to the XML schema. But it doesn't work for the customized widgets. So this patch adds pattern checks similar to the ivshmem in vue files.

So this is to enable real-time checks of the text pattern?

**Comment by Kunhui-Li** [comment]
> > > Why do we have to add the regex patterns in vue files rather than in the XML schema?
> > 
> > 
> > The regex pattern has been added to the XML schema. But it doesn't work for the customized widgets. So this patch adds pattern checks similar to the ivshmem in vue files.
> 
> So this is to enable real-time checks of the text pattern?

Yes.

**Review by junjiemao1 — APPROVED** [review]

**Comment by szhen11** [comment]
@NanlinXie Please help to approve this PR. Thanks.

**Review by NanlinXie — APPROVED** [review]

**Comment by dbkinder** [comment]
How do we guarantee that the duplicated regex patterns in vue and xsd files are kept in sync?  Better is to have a single source for this regex pattern (and the tooltip documentation) in the xsd files.

**Comment by junjiemao1** [comment]
> How do we guarantee that the duplicated regex patterns in vue and xsd files are kept in sync? Better is to have a single source for this regex pattern (and the tooltip documentation) in the xsd files.

This patch does not duplicate the regex pattern; it fetches the pattern from the json schema which is generated from the XSD files.

The error message (b-form-invalid-feedback) is duplicated, though.

**Pull request merged**
