### PR TITLE
doc: fix API documentation misspellings

### PR DESCRIPTION
**Pull request by dbkinder**
Signed-off-by: David B. Kinder <david.b.kinder@intel.com>

### CODE REVIEW

**Comment by NanlinXie** [comment]
Can one of the admins verify this patch?

**Comment by dbkinder** [comment]
@jren1 @hwang37 @anthonyzxu  Is there a reason this PR is not merged yet?  I **could** merge it myself, but I'd rather have the maintainer merge changes to their code.

**Comment by dbkinder** [comment]
@hwang37  Can you help figure out why this PR is not getting merged please.

**Comment by hwang37** [comment]
@dbkinder can you check if it's merged?

**Pull request merged**
