### PR TITLE
support tpm event log for pre-launched Security VM

### PR DESCRIPTION
**Pull request by lifeix**
1. refine the acrn_mmiodev structure to add more MMIO resources, also add a name
field to indicate what the MMIO device is.
2. If a security VM wants to do TPM2 fixup: 1. first find the TPM2 mmiodev by the
name,  then update the vTPM2 ACPI Table for pre-launched Security VM according to
the physical TPM2 ACPI Table.

Tracked-On: #6366
Signed-off-by: Tao Yuhong <yuhong.tao@intel.com>
Signed-off-by: Fei Li <fei1.li@intel.com>

### CODE REVIEW

**Comment by lifeix** [comment]
This patch set dependence on https://github.com/projectacrn/acrn-hypervisor/pull/6362. Need to merge together.

**Comment by wenlingz** [comment]
@lifeix  build fail, please check:
home/meta-acrn/workspace/build/master-acrn-sos/work/x86_64-linux/acrn-hypervisor-native/6367-1628494511/build//hypervisor/configs/scenarios/hybrid_rt/vm_configurations.c:56:2: error: ‘struct acrn_mmiodev’ has no member named ‘user_vm_pa’
 .user_vm_pa = VM0_TPM_BUFFER_BASE_ADDR_GPA,
  ^~~~~~~~~~
In file included from /home/meta-acrn/workspace/build/master-acrn-sos/work/x86_64-linux/acrn-hypervisor-native/6367-1628494511/build//hypervisor/configs/scenarios/hybrid_rt/vm_configurations.h:10:0,
                 from /home/meta-acrn/workspace/build/master-acrn-sos/work/x86_64-linux/acrn-hypervisor-native/6367-1628494511/git/hypervisor/boot/include/boot.h:12,
                 from /home/meta-acrn/workspace/build/master-acrn-sos/work/x86_64-linux/acrn-hypervisor-native/6367-1628494511/git/hypervisor/include/arch/x86/asm/vm_config.h:13,
                 from /home/meta-acrn/workspace/build/master-acrn-sos/work/x86_64-linux/acrn-hypervisor-native/6367-1628494511/build//hypervisor/configs/scenarios/hybrid_rt/vm_configurations.c:7:
/home/meta-acrn/workspace/build/master-acrn-sos/work/x86_64-linux/acrn-hypervisor-native/6367-1628494511/build//hypervisor/configs/scenarios/hybrid_rt/misc_cfg.h:41:39: warning: overflow in implicit constant conversion [-Woverflow]
 #define VM0_TPM_BUFFER_BASE_ADDR_GPA  0xFED40000UL
                                       ^
/home/meta-acrn/workspace/build/master-acrn-sos/work/x86_64-linux/acrn-hypervisor-native/6367-1628494511/build//hypervisor/configs/scenarios/hybrid_rt/vm_configurations.c:56:15: note: in expansion of macro ‘VM0_TPM_BUFFER_BASE_ADDR_GPA’
 .user_vm_pa = VM0_TPM_BUFFER_BASE_ADDR_GPA,
               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/meta-acrn/workspace/build/master-acrn-sos/work/x86_64-linux/acrn-hypervisor-native/6367-1628494511/build//hypervisor/configs/scenarios/hybrid_rt/vm_configurations.c:57:2: error: ‘struct acrn_mmiodev’ has no member named ‘service_vm_pa’
 .service_vm_pa = VM0_TPM_BUFFER_BASE_ADDR,
  ^~~~~~~~~~~~~
/home/meta-acrn/workspace/build/master-acrn-sos/work/x86_64-linux/acrn-hypervisor-native/6367-1628494511/build//hypervisor/configs/scenarios/hybrid_rt/vm_configurations.c:58:1: warning: missing initializer for field ‘host_pa’ of ‘struct acrn_mmiores’ [-Wmissing-field-initializers]
 .size = VM0_TPM_BUFFER_SIZE,
 ^
In file included from /home/meta-acrn/workspace/build/master-acrn-sos/work/x86_64-linux/acrn-hypervisor-native/6367-1628494511/git/hypervisor/include/arch/x86/asm/vm_config.h:14:0,
                 from /home/meta-acrn/workspace/build/master-acrn-sos/work/x86_64-linux/acrn-hypervisor-native/6367-1628494511/build//hypervisor/configs/scenarios/hybrid_rt/vm_configurations.c:7:
/home/meta-acrn/workspace/build/master-acrn-sos/work/x86_64-linux/acrn-hypervisor-native/6367-1628494511/git/hypervisor/include/public/acrn_common.h:670:12: note: ‘host_pa’ declared here
   uint64_t host_pa;
            ^~~~~~~
/home/meta-acrn/workspace/build/master-acrn-sos/work/x86_64-linux/acrn-hypervisor-native/6367-1628494511/build//hypervisor/configs/scenarios/hybrid_rt/vm_configurations.c:58:2: error: ‘struct acrn_mmiodev’ has no member named ‘size’
 .size = VM0_TPM_BUFFER_SIZE,
  ^~~~
In file included from /home/meta-acrn/workspace/build/master-acrn-sos/work/x86_64-linux/acrn-hypervisor-native/6367-1628494511/build//hypervisor/configs/scenarios/hybrid_rt/vm_configurations.h:10:0,
                 from /home/meta-acrn/workspace/build/master-acrn-sos/work/x86_64-linux/acrn-hypervisor-native/6367-1628494511/git/hypervisor/boot/include/boot.h:12,
                 from /home/meta-acrn/workspace/build/master-acrn-sos/work/x86_64-linux/acrn-hypervisor-native/6367-1628494511/git/hypervisor/include/arch/x86/asm/vm_config.h:13,
                 from /home/meta-acrn/workspace/build/master-acrn-sos/work/x86_64-linux/acrn-hypervisor-native/6367-1628494511/build//hypervisor/configs/scenarios/hybrid_rt/vm_configurations.c:7:
/home/meta-acrn/workspace/build/master-acrn-sos/work/x86_64-linux/acrn-hypervisor-native/6367-1628494511/build//hypervisor/configs/scenarios/hybrid_rt/misc_cfg.h:42:39: warning: excess elements in struct initializer
 #define VM0_TPM_BUFFER_SIZE           0x5000UL
                                       ^
/home/meta-acrn/workspace/build/master-acrn-sos/work/x86_64-linux/acrn-hypervisor-native/6367-1628494511/build//hypervisor/configs/scenarios/hybrid_rt/vm_configurations.c:58:9: note: in expansion of macro ‘VM0_TPM_BUFFER_SIZE’
 .size = VM0_TPM_BUFFER_SIZE,
         ^~~~~~~~~~~~~~~~~~~
/home/meta-acrn/workspace/build/master-acrn-sos/work/x86_64-linux/acrn-hypervisor-native/6367-1628494511/build//hypervisor/configs/scenarios/hybrid_rt/misc_cfg.h:42:39: note: (near initialization for ‘vm_configs[0].mmiodevs[0]’)
 #define VM0_TPM_BUFFER_SIZE           0x5000UL
                                       ^
/home/meta-acrn/workspace/build/master-acrn-sos/work/x86_64-linux/acrn-hypervisor-native/6367-1628494511/build//hypervisor/configs/scenarios/hybrid_rt/vm_configurations.c:58:9: note: in expansion of macro ‘VM0_TPM_BUFFER_SIZE’
 .size = VM0_TPM_BUFFER_SIZE,
         ^~~~~~~~~~~~~~~~~~~
/home/meta-acrn/workspace/build/master-acrn-sos/work/x86_64-linux/acrn-hypervisor-native/6367-1628494511/build//hypervisor/configs/scenarios/hybrid_rt/vm_configurations.c:14:55: warning: missing braces around initializer [-Wmissing-braces]
 struct acrn_vm_config vm_configs[CONFIG_MAX_VM_NUM] = {
                                                       ^
/home/meta-acrn/workspace/build/master-acrn-sos/work/x86_64-linux/acrn-hypervisor-native/6367-1628494511/build//hypervisor/configs/scenarios/hybrid_rt/vm_configurations.c:14:55: warning: missing braces around initializer [-Wmissing-braces]
/home/meta-acrn/workspace/build/master-acrn-sos/work/x86_64-linux/acrn-hypervisor-native/6367-1628494511/build//hypervisor/configs/scenarios/hybrid_rt/vm_configurations.c:14:55: warning: missing braces around initializer [-Wmissing-braces]
/home/meta-acrn/workspace/build/master-acrn-sos/work/x86_64-linux/acrn-hypervisor-native/6367-1628494511/build//hypervisor/configs/scenarios/hybrid_rt/vm_configurations.c:14:55: warning: missing braces around initializer [-Wmissing-braces]
/home/meta-acrn/workspace/build/master-acrn-sos/work/x86_64-linux/acrn-hypervisor-native/6367-1628494511/build//hypervisor/configs/scenarios/hybrid_rt/vm_configurations.c:14:55: warning: missing braces around initializer [-Wmissing-braces]
/home/meta-acrn/workspace/build/master-acrn-sos/work/x86_64-linux/acrn-hypervisor-native/6367-1628494511/build//hypervisor/configs/scenarios/hybrid_rt/vm_configurations.c:14:55: warning: missing braces around initializer [-Wmissing-braces]
/home/meta-acrn/workspace/build/master-acrn-sos/work/x86_64-linux/acrn-hypervisor-native/6367-1628494511/build//hypervisor/configs/scenarios/hybrid_rt/vm_configurations.c:14:55: warning: missing braces around initializer [-Wmissing-braces]
/home/meta-acrn/workspace/build/master-acrn-sos/work/x86_64-linux/acrn-hypervisor-native/6367-1628494511/build//hypervisor/configs/scenarios/hybrid_rt/vm_configurations.c:14:55: warning: missing braces around initializer [-Wmissing-braces]
/home/meta-acrn/workspace/build/master-acrn-sos/work/x86_64-linux/acrn-hypervisor-native/6367-1628494511/build//hypervisor/configs/scenarios/hybrid_rt/vm_configurations.c:14:55: warning: missing braces around initializer [-Wmissing-braces]
/home/meta-acrn/workspace/build/master-acrn-sos/work/x86_64-linux/acrn-hypervisor-native/6367-1628494511/build//hypervisor/configs/scenarios/hybrid_rt/vm_configurations.c:14:55: warning: missing braces around initializer [-Wmissing-braces]
/home/meta-acrn/workspace/build/master-acrn-sos/work/x86_64-linux/acrn-hypervisor-native/6367-1628494511/build//hypervisor/configs/scenarios/hybrid_rt/vm_configurations.c:14:55: warning: missing braces around initializer [-Wmissing-braces]
/home/meta-acrn/workspace/build/master-acrn-sos/work/x86_64-linux/acrn-hypervisor-native/6367-1628494511/build//hypervisor/configs/scenarios/hybrid_rt/vm_configurations.c:14:55: warning: missing braces around initializer [-Wmissing-braces]
/home/meta-acrn/workspace/build/master-acrn-sos/work/x86_64-linux/acrn-hypervisor-native/6367-1628494511/build//hypervisor/configs/scenarios/hybrid_rt/vm_configurations.c:14:55: warning: missing braces around initializer [-Wmissing-braces]
/home/meta-acrn/workspace/build/master-acrn-sos/work/x86_64-linux/acrn-hypervisor-native/6367-1628494511/build//hypervisor/configs/scenarios/hybrid_rt/vm_configurations.c:14:55: warning: missing braces around initializer [-Wmissing-braces]
/home/meta-acrn/workspace/build/master-acrn-sos/work/x86_64-linux/acrn-hypervisor-native/6367-1628494511/build//hypervisor/configs/scenarios/hybrid_rt/vm_configurations.c:14:55: warning: missing braces around initializer [-Wmissing-braces]
/home/meta-acrn/workspace/build/master-acrn-sos/work/x86_64-linux/acrn-hypervisor-native/6367-1628494511/build//hypervisor/configs/scenarios/hybrid_rt/vm_configurations.c:14:55: warning: missing braces around initializer [-Wmissing-braces]
Makefile:39: recipe for target 'default' failed
make[1]: *** [default] Error 1
make[1]: Leaving directory '/home/meta-acrn/workspace/build/master-acrn-sos/work/x86_64-linux/acrn-hypervisor-native/6367-1628494511/git/misc/hv_prebuild'
Makefile:394: recipe for target 'pre_build' failed
make: *** [pre_build] Error 2
make: Leaving directory '/home/meta-acrn/workspace/build/master-acrn-sos/work/x86_64-linux/acrn-hypervisor-native/6367-1628494511/git/hypervisor'
WARNING: /home/meta-acrn/workspace/build/master-acrn-sos/work/x86_64-linux/acrn-hypervisor-native/6367-1628494511/temp/run.do_compile.997:172 exit 1 from 'exit 1'
WARNING: Backtrace (BB generated script): 
	#1: bbfatal_log, /home/meta-acrn/workspace/build/master-acrn-sos/work/x86_64-linux/acrn-hypervisor-native/6367-1628494511/temp/run.do_compile.997, line 172
	#2: die, /home/meta-acrn/workspace/build/master-acrn-sos/work/x86_64-linux/acrn-hypervisor-native/6367-1628494511/temp/run.do_compile.997, line 162
	#3: oe_runmake, /home/meta-acrn/workspace/build/master-acrn-sos/work/x86_64-linux/acrn-hypervisor-native/6367-1628494511/temp/run.do_compile.997, line 151
	#4: do_compile, /home/meta-acrn/workspace/build/master-acrn-sos/work/x86_64-linux/acrn-hypervisor-native/6367-1628494511/temp/run.do_compile.997, line 146
	#5: main, /home/meta-acrn/workspace/build/master-acrn-sos/work/x86_64-linux/acrn-hypervisor-native/6367-1628494511/temp/run.do_compile.997, line 185

Backtrace (metadata-relative locations):
	#1: bbfatal_log, /home/meta-acrn/workspace/poky/meta/classes/logging.bbclass, line 72
	#2: die, /home/meta-acrn/workspace/poky/meta/classes/base.bbclass, line 56
	#3: oe_runmake, /home/meta-acrn/workspace/poky/meta/classes/base.bbclass, line 65
	#4: do_compile, autogenerated, line 2
ERROR: Logfile of failure stored in: /home/meta-acrn/workspace/build/master-acrn-sos/work/x86_64-linux/acrn-hypervisor-native/6367-1628494511/temp/log.do_compile.997
Log data follows:
| DEBUG: Executing shell function do_compile

**Comment by wenlingz** [comment]
@NanlinXie @ywan170 please help approve this PR, thanks

**Comment by NanlinXie** [comment]
Approved for configtool part.

**Review by NanlinXie — APPROVED** [review]

**Comment by dongyaozu** [comment]
fine for HV part

**Comment by ywan170** [comment]
DM part looks OK to me.

**Pull request merged**
