### PR TITLE
acrn_config: update text when loading the Configurator

### PR DESCRIPTION
**Pull request by gvancuts**
Update the text that shows up when loading the ACRN Configurator.

Signed-off-by: Geoffroy Van Cutsem <geoffroy.vancutsem@intel.com>

### CODE REVIEW

**Comment by acrnsi** [comment]
Can one of the admins verify this patch?

**Comment by gvancuts** [comment]
@dbkinder what do you think of this new text? My initial motivation was to get rid of the trailing tilde (`~`) that shows up at the end of the "Please wait for 5 seconds~" text when loading the ACRN Configurator.

**Review by dbkinder — CHANGES_REQUESTED** [review]

**Comment by gvancuts** [comment]
Done, PTAL

**Comment by NanlinXie** [comment]
@gvancuts , please add tracked on for this PR, thanks!

**Comment by NanlinXie** [comment]
Filed another PR #7810 to fix tracked on issue and merged , close this PR. @gvancuts

**Pull request closed without merging**
