### PR TITLE
remove "gpu" parameter when pass-thru IGD

### PR DESCRIPTION
**Pull request by liujunming**
remove "gpu" parameter when pass-thru IGD

### CODE REVIEW

**Review by dbkinder — APPROVED** [review]
OK, but curious that #6582 (now closed) changed this name to igd, while this PR removed gpu completely.  @junjiemao1 might this affect existing user-written launch scripts? It appears we'll write out a warning if gpu name is used (as an Invalid passthru option).

**Comment by junjiemao1** [comment]
@szhen11 Would you please help shed some light on the question from David?

**Comment by liujunming** [comment]
@dbkinder Hi, David.

https://github.com/projectacrn/acrn-hypervisor/blob/master/devicemodel/hw/pci/passthrough.c#L605
Yes, You're right.
We'll write out a warning if "gpu" name is used (as an Invalid passthru option)

**Comment by wenlingz** [comment]
@NanlinXie please  help approve this PR, thanks

**Comment by ywan170** [comment]
Please hold this PR, the new version is under review on the mailing list.

**Comment by ywan170** [comment]
DM parts are LGTM.

**Review by NanlinXie — APPROVED** [review]
Approve for configtool part

**Pull request merged**
