### PR TITLE
Add s5 support for dm-launched RTVM

### PR DESCRIPTION
**Pull request by KaigeFu**
This patchset aims at adding s5 support for dm-launched RTVM. The virtual pm port of RTVM
is intercepted by HV. But the HV needs to inform the DM as well. So we will forward the
virtual S5 request to DM too

The main steps for s5 of RTVM is:
  1). Set a flag (VM_POWERING_OFF) indicating that the RTVM is powering off by itself.
  2). Return to DM.
  3). Pause vm. It will check the flag in step #1. If it is set, take action.
      Otherwise reject the request.
  4). Deinit works
  5). Destroy the RTVM.

 Tracked-On: #2865

### CODE REVIEW

**Comment by HuiHuangShi** [comment]
out of time

**Comment by HuiHuangShi** [comment]
39 new potential violations to the coding guideline detected. Please help check. Thanks!<br><1> config:common filename:/hypervisor/arch/x86/guest/vm.c func:pause_vm offset:553<br> reason:Assignment operation in expression.<br><2> config:sharing_config filename:/hypervisor/arch/x86/guest/vm.c func:pause_vm offset:553<br> reason:Expression has side effects. : i<br><3> config:common filename:/hypervisor/arch/x86/guest/vm.c func:pause_vm offset:553<br> reason:Type conversion without cast. :  (enum vm_state and enum vcpu_state): vcpu -> state != VCPU_OFFLINE<br><4> config:common filename:/hypervisor/arch/x86/guest/vm.c func:pause_vm offset:553<br> reason:No brackets to loop body.<br><5> config:common filename:/hypervisor/arch/x86/guest/vm.c func:pause_vm offset:560<br> reason:Inconsistent usage of loop control variable.<br><6> config:common filename:/hypervisor/arch/x86/guest/vm.c func:pause_vm offset:560<br> reason:For loop incrementation is not simple.<br><7> config:part_config filename:/hypervisor/arch/x86/guest/vm.c func:pause_vm offset:560<br> reason:Expression has side effects. : i<br><8> config:common filename:/hypervisor/arch/x86/guest/vm.c func:pause_vm offset:560<br> reason:For loop initialisation is not simple.<br><9> config:common filename:/hypervisor/arch/x86/guest/vm.c func:pause_vm offset:560<br> reason:Use of comma operator.<br><10> config:common filename:/hypervisor/arch/x86/guest/vm.c func:pause_vm offset:560<br> reason:No space after semi colon in for expression.<br><11> config:part_config filename:/hypervisor/dm/vpic.c func:vpic_master_io_read offset:731<br> reason:Pointer param should be declared pointer to const. : vcpu<br><12> config:sharing_config filename:/hypervisor/dm/vpic.c func:vpic_master_io_read offset:731<br> reason:Pointer param should be declared pointer to const. : vcpu<br><13> config:sharing_config filename:/hypervisor/dm/vpic.c func:vpic_slave_io_read offset:777<br> reason:Pointer param should be declared pointer to const. : vcpu<br><14> config:part_config filename:/hypervisor/dm/vpic.c func:vpic_slave_io_read offset:777<br> reason:Pointer param should be declared pointer to const. : vcpu<br><15> config:part_config filename:/hypervisor/dm/vpic.c func:vpic_elc_io_read offset:847<br> reason:Pointer param should be declared pointer to const. : vcpu<br><16> config:sharing_config filename:/hypervisor/dm/vpic.c func:vpic_elc_io_read offset:847<br> reason:Pointer param should be declared pointer to const. : vcpu<br><17> config:part_config filename:/hypervisor/arch/x86/guest/pm.c func:pm1ab_io_read offset:124<br> reason:Pointer param should be declared pointer to const. : vcpu<br><18> config:sharing_config filename:/hypervisor/arch/x86/guest/pm.c func:pm1ab_io_read offset:124<br> reason:Pointer param should be declared pointer to const. : vcpu<br><19> config:part_config filename:/hypervisor/arch/x86/guest/pm.c func:pm1ab_io_read offset:128<br> reason:Function return value potentially unused. : (pio_req)->value<br><20> config:sharing_config filename:/hypervisor/arch/x86/guest/pm.c func:pm1ab_io_read offset:128<br> reason:Function return value potentially unused. : (pio_req)->value<br><21> config:common filename:/hypervisor/arch/x86/guest/pm.c func:rt_vm_pm1a_io_read offset:217<br> reason:Static procedure is not explicitly called in code analysed. : rt_vm_pm1a_io_read<br><22> config:common filename:/hypervisor/arch/x86/guest/pm.c func:rt_vm_pm1a_io_write offset:223<br> reason:Static procedure is not explicitly called in code analysed. : rt_vm_pm1a_io_write<br><23> config:common filename:/hypervisor/arch/x86/guest/pm.c func:rt_vm_pm1a_io_write offset:228<br> reason:Expression is not Boolean.<br><24> config:part_config filename:/hypervisor/arch/x86/guest/pm.c func:register_rt_vm_pm1a_ctl_handler offset:236<br> reason:No prototype for non-static function. : register_rt_vm_pm1a_ctl_handler<br><25> config:sharing_config filename:/hypervisor/arch/x86/guest/pm.c func:register_rt_vm_pm1a_ctl_handler offset:236<br> reason:No prototype for non-static function. : register_rt_vm_pm1a_ctl_handler<br><26> config:part_config filename:/hypervisor/dm/vrtc.c func:vrtc_read offset:46<br> reason:Pointer param should be declared pointer to const. : vcpu<br><27> config:sharing_config filename:/hypervisor/dm/vrtc.c func:vrtc_read offset:46<br> reason:Pointer param should be declared pointer to const. : vcpu<br><28> config:part_config filename:/hypervisor/dm/vrtc.c func:vrtc_read offset:56<br> reason:Function return value potentially unused. : (pio_req)->value<br><29> config:sharing_config filename:/hypervisor/dm/vrtc.c func:vrtc_read offset:56<br> reason:Function return value potentially unused. : (pio_req)->value<br><30> config:part_config filename:/hypervisor/dm/vpci/vpci.c func:pci_cfgaddr_io_read offset:48<br> reason:Pointer param should be declared pointer to const. : vcpu<br><31> config:sharing_config filename:/hypervisor/dm/vpci/vpci.c func:pci_cfgaddr_io_read offset:48<br> reason:Pointer param should be declared pointer to const. : vcpu<br><32> config:part_config filename:/hypervisor/dm/vpci/vpci.c func:pci_cfgdata_io_read offset:106<br> reason:Pointer param should be declared pointer to const. : vcpu<br><33> config:sharing_config filename:/hypervisor/dm/vpci/vpci.c func:pci_cfgdata_io_read offset:106<br> reason:Pointer param should be declared pointer to const. : vcpu<br><34> config:part_config filename:/hypervisor/arch/x86/guest/io_emul.c func:hv_emulate_pio offset:199<br> reason:Pointer param should be declared pointer to const. : vcpu<br>.....<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by KaigeFu** [comment]
@HuiHuangShi PR updated.

**Comment by HuiHuangShi** [comment]
38 new potential violations to the coding guideline detected. Please help check. Thanks!<br><1> config:common filename:/hypervisor/arch/x86/guest/vm.c func:pause_vm offset:553<br> reason:Assignment operation in expression.<br><2> config:sharing_config filename:/hypervisor/arch/x86/guest/vm.c func:pause_vm offset:553<br> reason:Expression has side effects. : i<br><3> config:common filename:/hypervisor/arch/x86/guest/vm.c func:pause_vm offset:553<br> reason:Type conversion without cast. :  (enum vm_state and enum vcpu_state): vcpu -> state != VCPU_OFFLINE<br><4> config:common filename:/hypervisor/arch/x86/guest/vm.c func:pause_vm offset:553<br> reason:No brackets to loop body.<br><5> config:common filename:/hypervisor/arch/x86/guest/vm.c func:pause_vm offset:560<br> reason:Inconsistent usage of loop control variable.<br><6> config:common filename:/hypervisor/arch/x86/guest/vm.c func:pause_vm offset:560<br> reason:For loop incrementation is not simple.<br><7> config:part_config filename:/hypervisor/arch/x86/guest/vm.c func:pause_vm offset:560<br> reason:Expression has side effects. : i<br><8> config:common filename:/hypervisor/arch/x86/guest/vm.c func:pause_vm offset:560<br> reason:For loop initialisation is not simple.<br><9> config:common filename:/hypervisor/arch/x86/guest/vm.c func:pause_vm offset:560<br> reason:Use of comma operator.<br><10> config:common filename:/hypervisor/arch/x86/guest/vm.c func:pause_vm offset:560<br> reason:No space after semi colon in for expression.<br><11> config:part_config filename:/hypervisor/dm/vpic.c func:vpic_master_io_read offset:731<br> reason:Pointer param should be declared pointer to const. : vcpu<br><12> config:sharing_config filename:/hypervisor/dm/vpic.c func:vpic_master_io_read offset:731<br> reason:Pointer param should be declared pointer to const. : vcpu<br><13> config:sharing_config filename:/hypervisor/dm/vpic.c func:vpic_slave_io_read offset:777<br> reason:Pointer param should be declared pointer to const. : vcpu<br><14> config:part_config filename:/hypervisor/dm/vpic.c func:vpic_slave_io_read offset:777<br> reason:Pointer param should be declared pointer to const. : vcpu<br><15> config:part_config filename:/hypervisor/dm/vpic.c func:vpic_elc_io_read offset:847<br> reason:Pointer param should be declared pointer to const. : vcpu<br><16> config:sharing_config filename:/hypervisor/dm/vpic.c func:vpic_elc_io_read offset:847<br> reason:Pointer param should be declared pointer to const. : vcpu<br><17> config:part_config filename:/hypervisor/arch/x86/guest/pm.c func:pm1ab_io_read offset:124<br> reason:Pointer param should be declared pointer to const. : vcpu<br><18> config:sharing_config filename:/hypervisor/arch/x86/guest/pm.c func:pm1ab_io_read offset:124<br> reason:Pointer param should be declared pointer to const. : vcpu<br><19> config:part_config filename:/hypervisor/arch/x86/guest/pm.c func:pm1ab_io_read offset:128<br> reason:Function return value potentially unused. : (pio_req)->value<br><20> config:sharing_config filename:/hypervisor/arch/x86/guest/pm.c func:pm1ab_io_read offset:128<br> reason:Function return value potentially unused. : (pio_req)->value<br><21> config:common filename:/hypervisor/arch/x86/guest/pm.c func:rt_vm_pm1a_io_read offset:217<br> reason:Static procedure is not explicitly called in code analysed. : rt_vm_pm1a_io_read<br><22> config:common filename:/hypervisor/arch/x86/guest/pm.c func:rt_vm_pm1a_io_write offset:223<br> reason:Static procedure is not explicitly called in code analysed. : rt_vm_pm1a_io_write<br><23> config:common filename:/hypervisor/arch/x86/guest/pm.c func:rt_vm_pm1a_io_write offset:228<br> reason:Expression is not Boolean.<br><24> config:part_config filename:/hypervisor/arch/x86/guest/pm.c func:register_rt_vm_pm1a_ctl_handler offset:236<br> reason:No prototype for non-static function. : register_rt_vm_pm1a_ctl_handler<br><25> config:sharing_config filename:/hypervisor/arch/x86/guest/pm.c func:register_rt_vm_pm1a_ctl_handler offset:236<br> reason:No prototype for non-static function. : register_rt_vm_pm1a_ctl_handler<br><26> config:part_config filename:/hypervisor/dm/vrtc.c func:vrtc_read offset:46<br> reason:Pointer param should be declared pointer to const. : vcpu<br><27> config:sharing_config filename:/hypervisor/dm/vrtc.c func:vrtc_read offset:46<br> reason:Pointer param should be declared pointer to const. : vcpu<br><28> config:part_config filename:/hypervisor/dm/vrtc.c func:vrtc_read offset:56<br> reason:Function return value potentially unused. : (pio_req)->value<br><29> config:sharing_config filename:/hypervisor/dm/vrtc.c func:vrtc_read offset:56<br> reason:Function return value potentially unused. : (pio_req)->value<br><30> config:part_config filename:/hypervisor/dm/vpci/vpci.c func:pci_cfgaddr_io_read offset:48<br> reason:Pointer param should be declared pointer to const. : vcpu<br><31> config:sharing_config filename:/hypervisor/dm/vpci/vpci.c func:pci_cfgaddr_io_read offset:48<br> reason:Pointer param should be declared pointer to const. : vcpu<br><32> config:part_config filename:/hypervisor/dm/vpci/vpci.c func:pci_cfgdata_io_read offset:106<br> reason:Pointer param should be declared pointer to const. : vcpu<br><33> config:sharing_config filename:/hypervisor/dm/vpci/vpci.c func:pci_cfgdata_io_read offset:106<br> reason:Pointer param should be declared pointer to const. : vcpu<br><34> config:part_config filename:/hypervisor/arch/x86/guest/io_emul.c func:hv_emulate_pio offset:199<br> reason:Pointer param should be declared pointer to const. : vcpu<br>.....<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by HuiHuangShi** [comment]
out of time

**Comment by HuiHuangShi** [comment]
out of time

**Comment by HuiHuangShi** [comment]
38 new potential violations to the coding guideline detected. Please help check. Thanks!<br><1> config:common filename:/hypervisor/arch/x86/guest/vm.c func:pause_vm offset:553<br> reason:Assignment operation in expression.<br><2> config:sharing_config filename:/hypervisor/arch/x86/guest/vm.c func:pause_vm offset:553<br> reason:Expression has side effects. : i<br><3> config:common filename:/hypervisor/arch/x86/guest/vm.c func:pause_vm offset:553<br> reason:Type conversion without cast. :  (enum vm_state and enum vcpu_state): vcpu -> state != VCPU_OFFLINE<br><4> config:common filename:/hypervisor/arch/x86/guest/vm.c func:pause_vm offset:553<br> reason:No brackets to loop body.<br><5> config:common filename:/hypervisor/arch/x86/guest/vm.c func:pause_vm offset:560<br> reason:Inconsistent usage of loop control variable.<br><6> config:common filename:/hypervisor/arch/x86/guest/vm.c func:pause_vm offset:560<br> reason:For loop incrementation is not simple.<br><7> config:part_config filename:/hypervisor/arch/x86/guest/vm.c func:pause_vm offset:560<br> reason:Expression has side effects. : i<br><8> config:common filename:/hypervisor/arch/x86/guest/vm.c func:pause_vm offset:560<br> reason:For loop initialisation is not simple.<br><9> config:common filename:/hypervisor/arch/x86/guest/vm.c func:pause_vm offset:560<br> reason:Use of comma operator.<br><10> config:common filename:/hypervisor/arch/x86/guest/vm.c func:pause_vm offset:560<br> reason:No space after semi colon in for expression.<br><11> config:part_config filename:/hypervisor/dm/vpic.c func:vpic_master_io_read offset:731<br> reason:Pointer param should be declared pointer to const. : vcpu<br><12> config:sharing_config filename:/hypervisor/dm/vpic.c func:vpic_master_io_read offset:731<br> reason:Pointer param should be declared pointer to const. : vcpu<br><13> config:sharing_config filename:/hypervisor/dm/vpic.c func:vpic_slave_io_read offset:777<br> reason:Pointer param should be declared pointer to const. : vcpu<br><14> config:part_config filename:/hypervisor/dm/vpic.c func:vpic_slave_io_read offset:777<br> reason:Pointer param should be declared pointer to const. : vcpu<br><15> config:part_config filename:/hypervisor/dm/vpic.c func:vpic_elc_io_read offset:847<br> reason:Pointer param should be declared pointer to const. : vcpu<br><16> config:sharing_config filename:/hypervisor/dm/vpic.c func:vpic_elc_io_read offset:847<br> reason:Pointer param should be declared pointer to const. : vcpu<br><17> config:part_config filename:/hypervisor/arch/x86/guest/pm.c func:pm1ab_io_read offset:124<br> reason:Pointer param should be declared pointer to const. : vcpu<br><18> config:sharing_config filename:/hypervisor/arch/x86/guest/pm.c func:pm1ab_io_read offset:124<br> reason:Pointer param should be declared pointer to const. : vcpu<br><19> config:part_config filename:/hypervisor/arch/x86/guest/pm.c func:pm1ab_io_read offset:128<br> reason:Function return value potentially unused. : (pio_req)->value<br><20> config:sharing_config filename:/hypervisor/arch/x86/guest/pm.c func:pm1ab_io_read offset:128<br> reason:Function return value potentially unused. : (pio_req)->value<br><21> config:common filename:/hypervisor/arch/x86/guest/pm.c func:rt_vm_pm1a_io_read offset:217<br> reason:Static procedure is not explicitly called in code analysed. : rt_vm_pm1a_io_read<br><22> config:common filename:/hypervisor/arch/x86/guest/pm.c func:rt_vm_pm1a_io_write offset:223<br> reason:Static procedure is not explicitly called in code analysed. : rt_vm_pm1a_io_write<br><23> config:common filename:/hypervisor/arch/x86/guest/pm.c func:rt_vm_pm1a_io_write offset:228<br> reason:Expression is not Boolean.<br><24> config:part_config filename:/hypervisor/arch/x86/guest/pm.c func:register_rt_vm_pm1a_ctl_handler offset:236<br> reason:No prototype for non-static function. : register_rt_vm_pm1a_ctl_handler<br><25> config:sharing_config filename:/hypervisor/arch/x86/guest/pm.c func:register_rt_vm_pm1a_ctl_handler offset:236<br> reason:No prototype for non-static function. : register_rt_vm_pm1a_ctl_handler<br><26> config:part_config filename:/hypervisor/dm/vrtc.c func:vrtc_read offset:46<br> reason:Pointer param should be declared pointer to const. : vcpu<br><27> config:sharing_config filename:/hypervisor/dm/vrtc.c func:vrtc_read offset:46<br> reason:Pointer param should be declared pointer to const. : vcpu<br><28> config:part_config filename:/hypervisor/dm/vrtc.c func:vrtc_read offset:56<br> reason:Function return value potentially unused. : (pio_req)->value<br><29> config:sharing_config filename:/hypervisor/dm/vrtc.c func:vrtc_read offset:56<br> reason:Function return value potentially unused. : (pio_req)->value<br><30> config:part_config filename:/hypervisor/dm/vpci/vpci.c func:pci_cfgaddr_io_read offset:48<br> reason:Pointer param should be declared pointer to const. : vcpu<br><31> config:sharing_config filename:/hypervisor/dm/vpci/vpci.c func:pci_cfgaddr_io_read offset:48<br> reason:Pointer param should be declared pointer to const. : vcpu<br><32> config:part_config filename:/hypervisor/dm/vpci/vpci.c func:pci_cfgdata_io_read offset:106<br> reason:Pointer param should be declared pointer to const. : vcpu<br><33> config:sharing_config filename:/hypervisor/dm/vpci/vpci.c func:pci_cfgdata_io_read offset:106<br> reason:Pointer param should be declared pointer to const. : vcpu<br><34> config:part_config filename:/hypervisor/arch/x86/guest/io_emul.c func:hv_emulate_pio offset:199<br> reason:Pointer param should be declared pointer to const. : vcpu<br>.....<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Pull request merged**
