### PR TITLE
HV: DMAR info refinement

### PR DESCRIPTION
**Pull request by jsun26intel**
- link CONFIG_MAX_IOMMU_NUM and MAX_DRHDS to DRHD_COUNT
- move dmar info definition to board.c
- clean up DMAR MACROs for sample platform acpi info

Tracked-On: #3977

Signed-off-by: Victor Sun <victor.sun@intel.com>
Acked-by: Eddie Dong <eddie.dong@intel.com>

### CODE REVIEW

**Comment by acrnsi** [comment]
OK to verify

**Comment by HuiHuangShi** [comment]
3 new potential violations to the coding guideline detected. Please help check. Thanks!<br><1> config:common filename:/hypervisor/acpi_parser/dmar_parse.c func:parse_dmar_table offset:239<br> reason:Value is not of appropriate type. :  (int and unsigned char): ! ( dmar_unit_cnt <= ( int32_t<br><2> config:common filename:/hypervisor/include/arch/x86/board.h func: offset:13<br> reason:Struct/union not completely specified.       : acrn_vm<br><3> config:common filename:/hypervisor/include/arch/x86/board.h func: offset:21<br> reason:Array has no bounds specified.<br><br>Name Conflict Violation:<br>plat_dmar_info parameter 534 include/arch/x86/vtd.h<br>plat_dmar_info externvar 20 include/arch/x86/board.h<br>plat_dmar_info parameter 232 acpi_parser/dmar_parse.c<br><br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by HuiHuangShi** [comment]
7 new potential violations to the coding guideline detected. Please help check. Thanks!<br><1> config:common filename:/hypervisor/acpi_parser/dmar_parse.c func:parse_dmar_table offset:239<br> reason:Value is not of appropriate type. :  (int and unsigned char): ! ( dmar_unit_cnt <= ( int32_t<br><2> config:part_config filename:/hypervisor/include/arch/x86/board.h func: offset:21<br> reason:No real declaration for external variable. : plat_dmar_info<br><3> config:sharing_config filename:/hypervisor/include/arch/x86/board.h func: offset:21<br> reason:No real declaration for external variable. : plat_dmar_info<br><4> config:sharing_config filename:/hypervisor/include/arch/x86/board.h func: offset:22<br> reason:No real declaration for external variable. : platform_clos_array<br><5> config:part_config filename:/hypervisor/include/arch/x86/board.h func: offset:22<br> reason:No real declaration for external variable. : platform_clos_array<br><6> config:sharing_config filename:/hypervisor/include/arch/x86/board.h func: offset:23<br> reason:No real declaration for external variable. : board_cpu_state_tbl<br><7> config:part_config filename:/hypervisor/include/arch/x86/board.h func: offset:23<br> reason:No real declaration for external variable. : board_cpu_state_tbl<br><br>Name Conflict Violation:<br>plat_dmar_info parameter 534 include/arch/x86/vtd.h<br>plat_dmar_info externvar 21 include/arch/x86/board.h<br>plat_dmar_info parameter 232 acpi_parser/dmar_parse.c<br><br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by HuiHuangShi** [comment]
11 new potential violations to the coding guideline detected. Please help check. Thanks!<br><1> config:common filename:/hypervisor/acpi_parser/dmar_parse.c func:parse_dmar_table offset:244<br> reason:Literal value requires a U suffix.           : 0<br><2> config:common filename:/hypervisor/acpi_parser/dmar_parse.c func:parse_dmar_table offset:244<br> reason:Signed/unsigned conversion without cast. :  (unsigned int and int): i<br><3> config:common filename:/hypervisor/acpi_parser/dmar_parse.c func:parse_dmar_table offset:245<br> reason:Signed/unsigned conversion without cast. :  (unsigned int and int):  param  1<br><4> config:common filename:/hypervisor/acpi_parser/dmar_parse.c func:parse_dmar_table offset:245<br> reason:Implicit conversion: actual to formal param (MR). :  (unsigned int and int):  param  1<br><5> config:common filename:/hypervisor/acpi_parser/dmar_parse.c func:parse_dmar_table offset:249<br> reason:Literal value requires a U suffix.           : 1<br><6> config:part_config filename:/hypervisor/include/arch/x86/board.h func: offset:21<br> reason:No real declaration for external variable. : plat_dmar_info<br><7> config:sharing_config filename:/hypervisor/include/arch/x86/board.h func: offset:21<br> reason:No real declaration for external variable. : plat_dmar_info<br><8> config:sharing_config filename:/hypervisor/include/arch/x86/board.h func: offset:22<br> reason:No real declaration for external variable. : platform_clos_array<br><9> config:part_config filename:/hypervisor/include/arch/x86/board.h func: offset:22<br> reason:No real declaration for external variable. : platform_clos_array<br><10> config:sharing_config filename:/hypervisor/include/arch/x86/board.h func: offset:23<br> reason:No real declaration for external variable. : board_cpu_state_tbl<br><11> config:part_config filename:/hypervisor/include/arch/x86/board.h func: offset:23<br> reason:No real declaration for external variable. : board_cpu_state_tbl<br><br>Name Conflict Violation:<br>plat_dmar_info parameter 534 include/arch/x86/vtd.h<br>plat_dmar_info externvar 21 include/arch/x86/board.h<br>plat_dmar_info parameter 232 acpi_parser/dmar_parse.c<br><br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by HuiHuangShi** [comment]
8 new potential violations to the coding guideline detected. Please help check. Thanks!<br><1> config:common filename:/hypervisor/acpi_parser/dmar_parse.c func:parse_dmar_table offset:245<br> reason:Signed/unsigned conversion without cast. :  (unsigned int and int):  param  1<br><2> config:common filename:/hypervisor/acpi_parser/dmar_parse.c func:parse_dmar_table offset:245<br> reason:Implicit conversion: actual to formal param (MR). :  (unsigned int and int):  param  1<br><3> config:part_config filename:/hypervisor/include/arch/x86/board.h func: offset:21<br> reason:No real declaration for external variable. : plat_dmar_info<br><4> config:sharing_config filename:/hypervisor/include/arch/x86/board.h func: offset:21<br> reason:No real declaration for external variable. : plat_dmar_info<br><5> config:sharing_config filename:/hypervisor/include/arch/x86/board.h func: offset:22<br> reason:No real declaration for external variable. : platform_clos_array<br><6> config:part_config filename:/hypervisor/include/arch/x86/board.h func: offset:22<br> reason:No real declaration for external variable. : platform_clos_array<br><7> config:sharing_config filename:/hypervisor/include/arch/x86/board.h func: offset:23<br> reason:No real declaration for external variable. : board_cpu_state_tbl<br><8> config:part_config filename:/hypervisor/include/arch/x86/board.h func: offset:23<br> reason:No real declaration for external variable. : board_cpu_state_tbl<br><br>Name Conflict Violation:<br>plat_dmar_info parameter 534 include/arch/x86/vtd.h<br>plat_dmar_info externvar 21 include/arch/x86/board.h<br>plat_dmar_info parameter 232 acpi_parser/dmar_parse.c<br><br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by HuiHuangShi** [comment]
8 new potential violations to the coding guideline detected. Please help check. Thanks!<br><1> config:common filename:/hypervisor/acpi_parser/dmar_parse.c func:drhd_find_iter offset:77<br> reason:Literal value requires a U suffix.           : 0<br><2> config:common filename:/hypervisor/acpi_parser/dmar_parse.c func:drhd_find_iter offset:77<br> reason:Signed/unsigned conversion without cast. :  (unsigned int and int): args -> i<br><3> config:part_config filename:/hypervisor/include/arch/x86/board.h func: offset:21<br> reason:No real declaration for external variable. : plat_dmar_info<br><4> config:sharing_config filename:/hypervisor/include/arch/x86/board.h func: offset:21<br> reason:No real declaration for external variable. : plat_dmar_info<br><5> config:sharing_config filename:/hypervisor/include/arch/x86/board.h func: offset:22<br> reason:No real declaration for external variable. : platform_clos_array<br><6> config:part_config filename:/hypervisor/include/arch/x86/board.h func: offset:22<br> reason:No real declaration for external variable. : platform_clos_array<br><7> config:sharing_config filename:/hypervisor/include/arch/x86/board.h func: offset:23<br> reason:No real declaration for external variable. : board_cpu_state_tbl<br><8> config:part_config filename:/hypervisor/include/arch/x86/board.h func: offset:23<br> reason:No real declaration for external variable. : board_cpu_state_tbl<br><br>Name Conflict Violation:<br>plat_dmar_info parameter 534 include/arch/x86/vtd.h<br>plat_dmar_info externvar 21 include/arch/x86/board.h<br>plat_dmar_info parameter 232 acpi_parser/dmar_parse.c<br><br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by HuiHuangShi** [comment]
6 new potential violations to the coding guideline detected. Please help check. Thanks!<br><1> config:part_config filename:/hypervisor/include/arch/x86/board.h func: offset:21<br> reason:No real declaration for external variable. : plat_dmar_info<br><2> config:sharing_config filename:/hypervisor/include/arch/x86/board.h func: offset:21<br> reason:No real declaration for external variable. : plat_dmar_info<br><3> config:sharing_config filename:/hypervisor/include/arch/x86/board.h func: offset:22<br> reason:No real declaration for external variable. : platform_clos_array<br><4> config:part_config filename:/hypervisor/include/arch/x86/board.h func: offset:22<br> reason:No real declaration for external variable. : platform_clos_array<br><5> config:sharing_config filename:/hypervisor/include/arch/x86/board.h func: offset:23<br> reason:No real declaration for external variable. : board_cpu_state_tbl<br><6> config:part_config filename:/hypervisor/include/arch/x86/board.h func: offset:23<br> reason:No real declaration for external variable. : board_cpu_state_tbl<br><br>Name Conflict Violation:<br>plat_dmar_info parameter 534 include/arch/x86/vtd.h<br>plat_dmar_info externvar 21 include/arch/x86/board.h<br>plat_dmar_info parameter 232 acpi_parser/dmar_parse.c<br><br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by jsun26intel** [comment]
OK to verify

**Comment by HuiHuangShi** [comment]
6 new potential violations to the coding guideline detected. Please help check. Thanks!<br><1> config:part_config filename:/hypervisor/include/arch/x86/board.h func: offset:21<br> reason:No real declaration for external variable. : plat_dmar_info<br><2> config:sharing_config filename:/hypervisor/include/arch/x86/board.h func: offset:21<br> reason:No real declaration for external variable. : plat_dmar_info<br><3> config:sharing_config filename:/hypervisor/include/arch/x86/board.h func: offset:22<br> reason:No real declaration for external variable. : platform_clos_array<br><4> config:part_config filename:/hypervisor/include/arch/x86/board.h func: offset:22<br> reason:No real declaration for external variable. : platform_clos_array<br><5> config:sharing_config filename:/hypervisor/include/arch/x86/board.h func: offset:23<br> reason:No real declaration for external variable. : board_cpu_state_tbl<br><6> config:part_config filename:/hypervisor/include/arch/x86/board.h func: offset:23<br> reason:No real declaration for external variable. : board_cpu_state_tbl<br><br>Name Conflict Violation:<br>plat_dmar_info parameter 534 include/arch/x86/vtd.h<br>plat_dmar_info externvar 21 include/arch/x86/board.h<br>plat_dmar_info parameter 232 acpi_parser/dmar_parse.c<br><br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by HuiHuangShi** [comment]
6 new potential violations to the coding guideline detected. Please help check. Thanks!<br><1> config:part_config filename:/hypervisor/include/arch/x86/board.h func: offset:21<br> reason:No real declaration for external variable. : plat_dmar_info<br><2> config:sharing_config filename:/hypervisor/include/arch/x86/board.h func: offset:21<br> reason:No real declaration for external variable. : plat_dmar_info<br><3> config:sharing_config filename:/hypervisor/include/arch/x86/board.h func: offset:22<br> reason:No real declaration for external variable. : platform_clos_array<br><4> config:part_config filename:/hypervisor/include/arch/x86/board.h func: offset:22<br> reason:No real declaration for external variable. : platform_clos_array<br><5> config:sharing_config filename:/hypervisor/include/arch/x86/board.h func: offset:23<br> reason:No real declaration for external variable. : board_cpu_state_tbl<br><6> config:part_config filename:/hypervisor/include/arch/x86/board.h func: offset:23<br> reason:No real declaration for external variable. : board_cpu_state_tbl<br><br>Name Conflict Violation:<br>plat_dmar_info parameter 534 include/arch/x86/vtd.h<br>plat_dmar_info externvar 21 include/arch/x86/board.h<br>plat_dmar_info parameter 232 acpi_parser/dmar_parse.c<br><br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by HuiHuangShi** [comment]
6 new potential violations to the coding guideline detected. Please help check. Thanks!<br><1> config:part_config filename:/hypervisor/include/arch/x86/board.h func: offset:21<br> reason:No real declaration for external variable. : plat_dmar_info<br><2> config:sharing_config filename:/hypervisor/include/arch/x86/board.h func: offset:21<br> reason:No real declaration for external variable. : plat_dmar_info<br><3> config:sharing_config filename:/hypervisor/include/arch/x86/board.h func: offset:22<br> reason:No real declaration for external variable. : platform_clos_array<br><4> config:part_config filename:/hypervisor/include/arch/x86/board.h func: offset:22<br> reason:No real declaration for external variable. : platform_clos_array<br><5> config:sharing_config filename:/hypervisor/include/arch/x86/board.h func: offset:23<br> reason:No real declaration for external variable. : board_cpu_state_tbl<br><6> config:part_config filename:/hypervisor/include/arch/x86/board.h func: offset:23<br> reason:No real declaration for external variable. : board_cpu_state_tbl<br><br>Name Conflict Violation:<br>plat_dmar_info parameter 534 include/arch/x86/vtd.h<br>plat_dmar_info externvar 21 include/arch/x86/board.h<br>plat_dmar_info parameter 232 acpi_parser/dmar_parse.c<br><br><br>No New Function Declaration/Definition Mismatch<br>

**Pull request merged**
