### PR TITLE
doc: add some docs about graphviz for drawings

### PR DESCRIPTION
**Pull request by dbkinder**
Add some practical examples and pointers to additional information about
using graphviz.

Signed-off-by: David B. Kinder <david.b.kinder@intel.com>

### CODE REVIEW

**Comment by NanlinXie** [comment]
Can one of the admins verify this patch?

**Comment by gvancuts** [comment]
Unless I've missed something, this does not publish it though (not until it's added as part of a `toc` somewhere), am I correct? Any reason why you don't want yet to include it as part of the documentation?

**Comment by dbkinder** [comment]
@gvancuts The content in the howtos folder are published with the tech/* and process/* TOC entries.

**Comment by gvancuts** [comment]
Thanks for the clarification!

**Pull request merged**
