### PR TITLE
Convert logs by printf to acrn-dm logger interface

### PR DESCRIPTION
**Pull request by psun3x**
Tracked-On: #5267

### CODE REVIEW

**Comment by HuiHuangShi** [comment]
No new violations to the coding guideline detected.<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by wenlingz** [comment]
@ywan170 please help approve this PR, thanks

**Comment by wenlingz** [comment]
@psun3x please add Tracked-On in your commit, thanks

**Comment by HuiHuangShi** [comment]
No new violations to the coding guideline detected.<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Review by ywan170 — APPROVED** [review]

**Pull request merged**
