### PR TITLE
SOS: extend the size of SOS CMA from 64M to 128M

### PR DESCRIPTION
**Pull request by fyin1**
We observed some dma allocation in SOS could failed because no
enough memory available. Let's extend the SOS CMA size a little bit

Tracked-On: #1882
Signed-off-by: Yin Fengwei <fengwei.yin@intel.com>

### CODE REVIEW

**Comment by HuiHuangShi** [comment]
1883 <br>The PR does not touch any hypervisor source file. Skip coding guideline checks.<br>

**Comment by ClaudZhang1995** [comment]
Ready to merge

**Comment by gvancuts** [comment]
We don't have such `cma` option by default when using an UEFI platform, should we add one?

**Comment by fyin1** [comment]
I don't need it on UEFI platform for now. Because it's used for trusty which is not enabled on UEFI platform yet.

**Comment by gvancuts** [comment]
> I don't need it on UEFI platform for now. Because it's used for trusty which is not enabled on UEFI platform yet.

Thanks for the confirmation!

**Pull request merged**
