### PR TITLE
Update TSC members and maintainers

### PR DESCRIPTION
**Pull request by gvancuts**
Updates to the TSC members and maintainer list
* Update the Technical Steering Committee (TSC) members following the election
of Junjie Mao as the new chair
* Update Thomas Gleixner's email address since he joined Intel Corporation
* Update the MAINTAINERS files for the 'hypervisor' and 'devicemodel' to
  reflect the fact Anthony Xu is no longer active in the project.

Signed-off-by: Geoffroy Van Cutsem <geoffroy.vancutsem@intel.com>

### CODE REVIEW

**Comment by acrnsi** [comment]
Can one of the admins verify this patch?

**Comment by gvancuts** [comment]
Side question, do we need to keep the `[hypervisor|devicemodel]/MAINTAINERS` files since we have the top-level `CODEOWNERS` that tracks who the official maintainers are. It seems like duplicated information to me (and was in fact out of synch ;-))

**Review by dongyaozu — APPROVED** [review]

**Review by dbkinder — APPROVED** [review]

**Comment by dbkinder** [comment]
Thanks @gvancuts The MAINTAINERS file is not used by GitHub (it's a Linux Kernel thing) so iit's a good idea to delete them as long as we keep the CODEOWNERS file up to date.

**Comment by dbkinder** [comment]
@NanlinXie This PR needs a developer to merge, or let me know if you're OK with me merging this.

**Pull request merged**
