### PR TITLE
doc: add community support and resources to introduction

### PR DESCRIPTION
**Pull request by dbkinder**
Include the project's GitHub README that contains community support and
resource information into the ACRN Introduction documentation.  Also fix
the ACRN misspelling.

Signed-off-by: David B. Kinder <david.b.kinder@intel.com>

### CODE REVIEW

**Comment by acrnsi** [comment]
Can one of the admins verify this patch?

**Comment by dbkinder** [comment]
@NanlinXie @wenlingz This is a doc only PR (only .rst files are updated) and should not require a Tracked_On tag, right?

**Comment by wenlingz** [comment]
> @NanlinXie @wenlingz This is a doc only PR (only .rst files are updated) and should not require a Tracked_On tag, right?

yes, but we just treat all files' change in  /doc as doc PRs currently, @szhen11 @NanlinXie we need have a discussion about doc PR's judgement.

**Comment by dbkinder** [comment]
> > @NanlinXie @wenlingz This is a doc only PR (only .rst files are updated) and should not require a Tracked_On tag, right?
> 
> yes, but we just treat all files' change in /doc as doc PRs currently, @szhen11 @NanlinXie we need have a discussion about doc PR's judgement.

Previously changes in /doc or any .rst file were considered as doc-only (there are .rst files in the root folder and in /misc subfolders too).

**Comment by szhen11** [comment]
> > > @NanlinXie @wenlingz This is a doc only PR (only .rst files are updated) and should not require a Tracked_On tag, right?
> > 
> > 
> > yes, but we just treat all files' change in /doc as doc PRs currently, @szhen11 @NanlinXie we need have a discussion about doc PR's judgement.
> 
> Previously changes in /doc or any .rst file were considered as doc-only (there are .rst files in the root folder and in /misc subfolders too).

We will update the CI scripts to let changes in /doc or any .rst file were considered as doc-only.

**Pull request merged**
