### PR TITLE
doc: update Kata and ACRN tutorial

### PR DESCRIPTION
**Pull request by gvancuts**
Update the Kata and ACRN tutorial based on the latest SW components. Many
previous steps are no longer required and have been removed.

Signed-off-by: Geoffroy Van Cutsem <geoffroy.vancutsem@intel.com>

### CODE REVIEW

**Comment by gvancuts** [comment]
@NanlinXie @deb-intel @vijaydhanraj PTAL

**Comment by vijaydhanraj** [comment]
Hi @gvancuts , now that MACVTAP is enabled by default, we should go towards the unification of the kata documentation between ACRN and Kata sites. But looks like we have elaborated our ACRN documentation more. It will be better to maintain one documentation rather than maintaining two sets. 

If it is fine with you, let us work together to make sure, [this ](https://github.com/kata-containers/documentation/blob/master/how-to/how-to-use-kata-containers-with-acrn.md) is updated and represents the latest changes. We can add to this link on our ACRN kata page.

**Comment by gvancuts** [comment]
> Hi @gvancuts , now that MACVTAP is enabled by default, we should go towards the unification of the kata documentation between ACRN and Kata sites. But looks like we have elaborated our ACRN documentation more. It will be better to maintain one documentation rather than maintaining two sets.

Yes, I agree we should really have a single document that covers this.

> 
> If it is fine with you, let us work together to make sure, [this ](https://github.com/kata-containers/documentation/blob/master/how-to/how-to-use-kata-containers-with-acrn.md) is updated and represents the latest changes. We can add to this link on our ACRN kata page.

My proposal is to do this the other way around, i.e. to maintain the document here (on the ACRN website) and add a pointer to it from https://katacontainers.io/docs/ (add a new "How To" just like there is one for `firecracker` already). There are a couple of reasons why I prefer this approach:
* The rendering we get from the ACRN website is nicer (proper HTML page in a website vs. Github-rendered markdown)
* Updating one vs. the other is the same effort regardless of where it is located, it's a Github PR.

What I really would like to see is the addition of a new "How To" on the main Kata Containers docs page though, else it's unlikely people will easily find this.

**Comment by vijaydhanraj** [comment]
Given that we agree on maintaining a single document here are my thoughts,

1. Kata ACRN “how-to” already exists but is not in the front page as the kata teams feels it is experimental and based on the users they will change.

2. We suddenly cannot stop updating a doc in kata and leave it dangling.

3. Any document that we upload the kata team does a thorough review for changes ( referring to technical kata content)

4. Regarding rendering I am ok with it as long as the content is clear.

Thanks,
-Vijay

On Jan 21, 2020, at 11:17 PM, Geoffroy Van Cutsem <notifications@github.com> wrote:

﻿

Hi @gvancuts<https://github.com/gvancuts> , now that MACVTAP is enabled by default, we should go towards the unification of the kata documentation between ACRN and Kata sites. But looks like we have elaborated our ACRN documentation more. It will be better to maintain one documentation rather than maintaining two sets.

Yes, I agree we should really have a single document that covers this.

If it is fine with you, let us work together to make sure, this <https://github.com/kata-containers/documentation/blob/master/how-to/how-to-use-kata-containers-with-acrn.md> is updated and represents the latest changes. We can add to this link on our ACRN kata page.

My proposal is to do this the other way around, i.e. to maintain the document here (on the ACRN website) and add a pointer to it from https://katacontainers.io/docs/ (add a new "How To" just like there is one for firecracker already). There are a couple of reasons why I prefer this approach:

  *   The rendering we get from the ACRN website is nicer (proper HTML page in a website vs. Github-rendered markdown)
  *   Updating one vs. the other is the same effort regardless of where it is located, it's a Github PR.

What I really would like to see is the addition of a new "How To" on the main Kata Containers docs page though, else it's unlikely people will easily find this.

**Comment by deb-intel** [comment]
@gvancuts Have you completed your edits?

**Comment by gvancuts** [comment]
Hi @vijaydhanraj , I understand you have a desire to keep the main source of documentation for this on the Kata Containers website. I'm personnally a little biased towards the ACRN because I see some advantages to it and also (let's admit it ;-)) because I'm more familiar with it. At the end of the day, both solutions can work IMHO, the key being that it's time to switch over to a single doc and make sure we give it enough love and attention.

> 1. Kata ACRN “how-to” already exists but is not in the front page as the kata teams feels it is experimental and based on the users they will change.

Fair enough

> 2. We suddenly cannot stop updating a doc in kata and leave it dangling.

I agree, we should either keep it up-to-date or delete it.

> 3. Any document that we upload the kata team does a thorough review for changes ( referring to technical kata content)

This is good, there is a similar process in place in ACRN too. Regardless of where we keep this document, we will need both teams to review edits for accuracy. I don't see one project having an advantage over the other in this case, or is there something I'm missing?

> 4. Regarding rendering I am ok with it as long as the content is clear.

OK

**Comment by gvancuts** [comment]
> @gvancuts Have you completed your edits and are ready for this PR to be merged?

Yes. I would like to resolve the open with @vijaydhanraj as well (as to where we keep this doc) but I think we can merge this for now and we'll move it across if that's what we settle on later.

**Pull request merged**
