### PR TITLE
HV: fix bug and improve serial PCI BDF configure

### PR DESCRIPTION
**Pull request by mcao6**
1. for HV command line, there is a interface to dynamically configure uart,
it need update mmio@ to bdf@
2. improve PCI_BDF from bdf@hex-value to bdf@bdf_info, like bdf@0:18.2

Tracked-On: #2031
Signed-off-by: Minggui Cao <minggui.cao@intel.com>
Acked-by: Anthony Xu <anthony.xu@intel.com>

### CODE REVIEW

**Comment by HuiHuangShi** [comment]
2077 <br>The PR does not touch any hypervisor source file. Skip coding guideline checks.<br>

**Comment by wenlingz** [comment]
@mcao6 please check your code,thanks

**Comment by mcao6** [comment]
will resolve the conflicts soon

**Comment by mcao6** [comment]
update for doc format

**Comment by HuiHuangShi** [comment]
2077 <br>The PR does not touch any hypervisor source file. Skip coding guideline checks.<br>

**Comment by mcao6** [comment]
hold on for a while, will check the failure soon, thanks

**Comment by mcao6** [comment]
@jren1 @gvancuts could you give some comments? As your review comments I changed bdf@0xC2 --> bdf@0:18.2 format, to make it more readable and easy to use.  for @dongyaozu Eddie's comments, it doesn't need that.  From my point, this interface is just for debug build, any format is OK, even the MMIO format is good to me.

**Comment by HuiHuangShi** [comment]
2077<br>12 new potential violations to the coding guideline detected. Please help check. Thanks!  <br><br>1.filename:/hypervisor/arch/x86/pm.c&nbsp;&nbsp;function:set_host_wake_vectors&nbsp;&nbsp;offset:56:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Casting operation to a pointer. : (void* to unsigned int*): ( uint32_t * ) vector_32<br><br>2.filename:/hypervisor/arch/x86/pm.c&nbsp;&nbsp;function:set_host_wake_vectors&nbsp;&nbsp;offset:56:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Casting operation on a pointer. : (void* to unsigned int*): ( uint32_t * ) vector_32<br><br>3.filename:/hypervisor/arch/x86/pm.c&nbsp;&nbsp;function:set_host_wake_vectors&nbsp;&nbsp;offset:57:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Casting operation on a pointer. : (void* to unsigned long*): ( uint64_t * ) vector_64<br><br>4.filename:/hypervisor/arch/x86/pm.c&nbsp;&nbsp;function:set_host_wake_vectors&nbsp;&nbsp;offset:57:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Casting operation to a pointer. : (void* to unsigned long*): ( uint64_t * ) vector_64<br><br>5.filename:/hypervisor/arch/x86/pm.c&nbsp;&nbsp;function:do_acpi_s3&nbsp;&nbsp;offset:98:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Pointer param should be declared pointer to const. : sstate_data<br><br>6.filename:/hypervisor/arch/x86/pm.c&nbsp;&nbsp;function:host_enter_s3&nbsp;&nbsp;offset:133:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Value is not of appropriate type. :  (unsigned int* and unsigned int): sstate_data -> wake_vector_32 ) = ( uint32_t<br><br>7.filename:/hypervisor/arch/x86/pm.c&nbsp;&nbsp;function:host_enter_s3&nbsp;&nbsp;offset:147:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Implicit conversion: actual to formal param (MR). :  (unsigned long* and unsigned long):  param  2<br><br>8.filename:/hypervisor/arch/x86/pm.c&nbsp;&nbsp;function:host_enter_s3&nbsp;&nbsp;offset:147:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Cast from pointer to integral type. : (Unknown_Type to unsigned long): ( uint64_t ) restore_s3_context<br><br>9.filename:/hypervisor/arch/x86/pm.c&nbsp;&nbsp;function:host_enter_s3&nbsp;&nbsp;offset:147:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Cast involving function pointer. : (Unknown_Type to unsigned long): ( uint64_t ) restore_s3_context<br><br>10.filename:/hypervisor/arch/x86/guest/pm.c&nbsp;&nbsp;function:enter_s3&nbsp;&nbsp;offset:134:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Pointer param should be declared pointer to const. : vm<br><br>11.filename:/hypervisor/arch/x86/guest/pm.c&nbsp;&nbsp;function:pm1ab_io_write&nbsp;&nbsp;offset:150:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Pointer param should be declared pointer to const. : vm<br><br>12.filename:/hypervisor/include/debug/npk_log.h&nbsp;&nbsp;function:None&nbsp;&nbsp;offset:12:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:No definition in system for prototyped procedure. : npk_log_write<br><br>

**Comment by HuiHuangShi** [comment]
2077 <br>The PR does not touch any hypervisor source file. Skip coding guideline checks.<br>

**Comment by mcao6** [comment]
DOC update will be upload by another PR.

**Comment by dongyaozu** [comment]
This is for debug case only, so probably we can merge it to make it easier.

**Comment by acrnsi** [comment]
Ok to verify

**Pull request merged**
