### PR TITLE
HV: vuart refine

### PR DESCRIPTION
**Pull request by conghuic23**
As there are requirements for switching VM's console at hypervisor side and providing a mechanism to connect vuart between different VMs, so refine the vuart code.

In current implementation, two vuart are added to pre-launched VM's configuration, one is for console, the other is for communication. And these can only be used in debug mode. Will move the vuart code from hypervisor/debug/ to hypervisor/dm/, so that the release version can also use it.

Tracked-On: #2987
Signed-off-by: Conghui Chen <conghui.chen@intel.com>
Acked-by: Eddie Dong <eddie.dong@intel.com>

### CODE REVIEW

**Comment by wenlingz** [comment]
OK to verify

**Comment by acrnsi** [comment]
Ok to verify

**Comment by acrnsi** [comment]
@conghuic23 hi,please check your code , test fail in up2-sbl ,it`s log:
/storage/cwpqa-acrn-robot/venv/lib/python3.5/site-packages/paramiko/kex_ecdh_nist.py:39: CryptographyDeprecationWarning: encode_point has been deprecated on EllipticCurvePublicNumbers and will be removed in a future version. Please use EllipticCurvePublicKey.public_bytes to obtain both compressed and uncompressed point encoding.
  m.add_string(self.Q_C.public_numbers().encode_point())
/storage/cwpqa-acrn-robot/venv/lib/python3.5/site-packages/paramiko/kex_ecdh_nist.py:96: CryptographyDeprecationWarning: Support for unsafe construction of public numbers from encoded data will be removed in a future version. Please use EllipticCurvePublicKey.from_encoded_point
  self.curve, Q_S_bytes
/storage/cwpqa-acrn-robot/venv/lib/python3.5/site-packages/paramiko/kex_ecdh_nist.py:111: CryptographyDeprecationWarning: encode_point has been deprecated on EllipticCurvePublicNumbers and will be removed in a future version. Please use EllipticCurvePublicKey.public_bytes to obtain both compressed and uncompressed point encoding.
  hm.add_string(self.Q_C.public_numbers().encode_point())
/storage/cwpqa-acrn-robot/venv/lib/python3.5/site-packages/paramiko/ecdsakey.py:164: CryptographyDeprecationWarning: Support for unsafe construction of public numbers from encoded data will be removed in a future version. Please use EllipticCurvePublicKey.from_encoded_point
  self.ecdsa_curve.curve_class(), pointinfo
[ ERROR ] write: sos_console 0

 and expect: login: failed with timeout: 30
sos_console 0



Error: Invalid command.

ACRN:\>

ACRN:\>

ACRN:\>
[ WARN ] launch sos for 0 time failed: write: sos_console 0

**Comment by HuiHuangShi** [comment]
2 new potential violations to the coding guideline detected. Please help check. Thanks!
<1> config:sharing_config filename:/hypervisor/include/debug/vuart.h func: offset:84
reason:No real declaration for external variable. : console_vmid
<2> config:part_config filename:/hypervisor/include/debug/vuart.h func: offset:84
reason:No real declaration for external variable. : console_vmid

No New Name Conflict

Function Declaration/Definition Mismatch Violation:
extern int32_t shell_to_vm_console(int32_t argc, char ** argv) 40 debug/shell.c
define int32_t shell_to_vm_console(int32_t __attribute__((unused)) argc, char ** __attribute__((unused)) argv) 845 debug/shell.c

**Comment by conghuic23** [comment]
> @conghuic23 hi,please check your code , test fail in up2-sbl ,it`s log:
> /storage/cwpqa-acrn-robot/venv/lib/python3.5/site-packages/paramiko/kex_ecdh_nist.py:39: CryptographyDeprecationWarning: encode_point has been deprecated on EllipticCurvePublicNumbers and will be removed in a future version. Please use EllipticCurvePublicKey.public_bytes to obtain both compressed and uncompressed point encoding.
> m.add_string(self.Q_C.public_numbers().encode_point())
> /storage/cwpqa-acrn-robot/venv/lib/python3.5/site-packages/paramiko/kex_ecdh_nist.py:96: CryptographyDeprecationWarning: Support for unsafe construction of public numbers from encoded data will be removed in a future version. Please use EllipticCurvePublicKey.from_encoded_point
> self.curve, Q_S_bytes
> /storage/cwpqa-acrn-robot/venv/lib/python3.5/site-packages/paramiko/kex_ecdh_nist.py:111: CryptographyDeprecationWarning: encode_point has been deprecated on EllipticCurvePublicNumbers and will be removed in a future version. Please use EllipticCurvePublicKey.public_bytes to obtain both compressed and uncompressed point encoding.
> hm.add_string(self.Q_C.public_numbers().encode_point())
> /storage/cwpqa-acrn-robot/venv/lib/python3.5/site-packages/paramiko/ecdsakey.py:164: CryptographyDeprecationWarning: Support for unsafe construction of public numbers from encoded data will be removed in a future version. Please use EllipticCurvePublicKey.from_encoded_point
> self.ecdsa_curve.curve_class(), pointinfo
> [ ERROR ] write: sos_console 0
> 
> and expect: login: failed with timeout: 30
> sos_console 0
> 
> Error: Invalid command.
> 
> ACRN:>
> 
> ACRN:>
> 
> ACRN:>
> [ WARN ] launch sos for 0 time failed: write: sos_console 0

In the first patch of the patch list, the command sos_console has been changed to vm_console, please use vm_console to switch to sos console.

**Comment by conghuic23** [comment]
> 2 new potential violations to the coding guideline detected. Please help check. Thanks!
> <1> config:sharing_config filename:/hypervisor/include/debug/vuart.h func: offset:84
> reason:No real declaration for external variable. : console_vmid
> <2> config:part_config filename:/hypervisor/include/debug/vuart.h func: offset:84
> reason:No real declaration for external variable. : console_vmid
> 
> No New Name Conflict
> 
> Function Declaration/Definition Mismatch Violation:
> extern int32_t shell_to_vm_console(int32_t argc, char ** argv) 40 debug/shell.c
> define int32_t shell_to_vm_console(int32_t **attribute**((unused)) argc, char ** **attribute**((unused)) argv) 845 debug/shell.c

Fix the errors, please check again.

**Comment by HuiHuangShi** [comment]
2 new potential violations to the coding guideline detected. Please help check. Thanks!<br><1> config:sharing_config filename:/hypervisor/include/debug/vuart.h func: offset:85<br> reason:No real declaration for external variable. : console_vmid<br><2> config:part_config filename:/hypervisor/include/debug/vuart.h func: offset:85<br> reason:No real declaration for external variable. : console_vmid<br><br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by HuiHuangShi** [comment]
No new violations to the coding guideline detected.<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by HuiHuangShi** [comment]
out of time

**Comment by HuiHuangShi** [comment]
No new violations to the coding guideline detected.<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by acrnsi** [comment]
OK to verify

**Comment by HuiHuangShi** [comment]
No new violations to the coding guideline detected.<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Pull request merged**
