### PR TITLE
doc: update acpica-unix version to latest (20210105)

### PR DESCRIPTION
**Pull request by gvancuts**
Update the ACPI Component Architecture package (acpica-unix) to
the latest version available as of today: 20210105

Tracked-On: #5553
Signed-off-by: Geoffroy Van Cutsem <geoffroy.vancutsem@intel.com>

### CODE REVIEW

**Review by fitchbe — APPROVED** [review]

**Review by dbkinder — APPROVED** [review]
LGTM

**Comment by gvancuts** [comment]
@evshary , could you check that upgrading the `iasl` tool does not break your ROScube user guide?

@NanlinXie , what validation/testing do we need to do before approving and merging this?

**Comment by evshary** [comment]
> @evshary , could you check that upgrading the `iasl` tool does not break your ROScube user guide?

Sure, I'll check that.

**Comment by evshary** [comment]
@gvancuts I can run UOS with the new version of iasl. I think it's OK for ROScube user guide.

**Comment by gvancuts** [comment]
> @gvancuts I can run UOS with the new version of iasl. I think it's OK for ROScube user guide.

Thanks @evshary !

**Pull request merged**
