### PR TITLE
Cleanup header files in guest folder

### PR DESCRIPTION
**Pull request by mingqiangchi**
cleanup arch/x86/guest, only include some necessary header files,
doesn't include hypervisor.h

Tracked-On: #1842
Signed-off-by: Mingqiang Chi <mingqiang.chi@intel.com>
Reviewed-by: Jason Chen CJ <jason.cj.chen@intel.com>

### CODE REVIEW

**Comment by acrnsi** [comment]
Ok to vetify

**Comment by acrnsi** [comment]
OK to verify

**Comment by HuiHuangShi** [comment]
2569<br>17 new potential violations to the coding guideline detected. Please help check. Thanks!  <br><br>1.filename:/hypervisor/arch/x86/guest/assign.c&nbsp;&nbsp;function:ptirq_intx_ack&nbsp;&nbsp;offset:537:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:No prototype for non-static function. : ptirq_intx_ack<br><br>2.filename:/hypervisor/arch/x86/guest/assign.c&nbsp;&nbsp;function:ptirq_msix_remap&nbsp;&nbsp;offset:582:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:No prototype for non-static function. : ptirq_msix_remap<br><br>3.filename:/hypervisor/arch/x86/guest/assign.c&nbsp;&nbsp;function:ptirq_intx_pin_remap&nbsp;&nbsp;offset:672:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:No prototype for non-static function. : ptirq_intx_pin_remap<br><br>4.filename:/hypervisor/arch/x86/guest/assign.c&nbsp;&nbsp;function:ptirq_add_intx_remapping&nbsp;&nbsp;offset:775:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:No prototype for non-static function. : ptirq_add_intx_remapping<br><br>5.filename:/hypervisor/arch/x86/guest/assign.c&nbsp;&nbsp;function:ptirq_remove_intx_remapping&nbsp;&nbsp;offset:789:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:No prototype for non-static function. : ptirq_remove_intx_remapping<br><br>6.filename:/hypervisor/arch/x86/guest/assign.c&nbsp;&nbsp;function:ptirq_remove_msix_remapping&nbsp;&nbsp;offset:799:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:No prototype for non-static function. : ptirq_remove_msix_remapping<br><br>7.filename:/hypervisor/arch/x86/guest/assign.c&nbsp;&nbsp;function:ptirq_add_msix_remapping&nbsp;&nbsp;offset:816:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:No prototype for non-static function. : ptirq_add_msix_remapping<br><br>8.filename:/hypervisor/arch/x86/guest/vmcall.c&nbsp;&nbsp;function:vmcall_vmexit_handler&nbsp;&nbsp;offset:195:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:No prototype for non-static function. : vmcall_vmexit_handler<br><br>9.filename:/hypervisor/arch/x86/guest/pm.c&nbsp;&nbsp;function:validate_pstate&nbsp;&nbsp;offset:13:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:No prototype for non-static function. : validate_pstate<br><br>10.filename:/hypervisor/arch/x86/guest/pm.c&nbsp;&nbsp;function:vm_setup_cpu_px&nbsp;&nbsp;offset:46:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Logical comparison of pointers.              : px_cnt and 20U<br><br>11.filename:/hypervisor/arch/x86/guest/pm.c&nbsp;&nbsp;function:vm_setup_cpu_state&nbsp;&nbsp;offset:90:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:No prototype for non-static function. : vm_setup_cpu_state<br><br>12.filename:/hypervisor/arch/x86/guest/pm.c&nbsp;&nbsp;function:vm_load_pm_s_state&nbsp;&nbsp;offset:100:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:No prototype for non-static function. : vm_load_pm_s_state<br><br>13.filename:/hypervisor/arch/x86/guest/pm.c&nbsp;&nbsp;function:register_pm1ab_handler&nbsp;&nbsp;offset:200:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:No prototype for non-static function. : register_pm1ab_handler<br><br>14.filename:/hypervisor/arch/x86/guest/vmsr.c&nbsp;&nbsp;function:rdmsr_vmexit_handler&nbsp;&nbsp;offset:375:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:No prototype for non-static function. : rdmsr_vmexit_handler<br><br>15.filename:/hypervisor/arch/x86/guest/vmsr.c&nbsp;&nbsp;function:wrmsr_vmexit_handler&nbsp;&nbsp;offset:509:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:No prototype for non-static function. : wrmsr_vmexit_handler<br><br>16.filename:/hypervisor/include/arch/x86/pgtable.h&nbsp;&nbsp;function:hva2hpa&nbsp;&nbsp;offset:100:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Static procedure is not explicitly called in code analysed. : hva2hpa<br><br>17.filename:/hypervisor/arch/x86/guest/guest_memory.c&nbsp;&nbsp;function:hva2gpa&nbsp;&nbsp;offset:439:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Procedure is not called or referenced in code analysed. : hva2gpa<br><br>

**Comment by HuiHuangShi** [comment]
2569<br>17 new potential violations to the coding guideline detected. Please help check. Thanks!  <br><br>1.filename:/hypervisor/arch/x86/guest/assign.c&nbsp;&nbsp;function:ptirq_intx_ack&nbsp;&nbsp;offset:537:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:No prototype for non-static function. : ptirq_intx_ack<br><br>2.filename:/hypervisor/arch/x86/guest/assign.c&nbsp;&nbsp;function:ptirq_msix_remap&nbsp;&nbsp;offset:582:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:No prototype for non-static function. : ptirq_msix_remap<br><br>3.filename:/hypervisor/arch/x86/guest/assign.c&nbsp;&nbsp;function:ptirq_intx_pin_remap&nbsp;&nbsp;offset:672:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:No prototype for non-static function. : ptirq_intx_pin_remap<br><br>4.filename:/hypervisor/arch/x86/guest/assign.c&nbsp;&nbsp;function:ptirq_add_intx_remapping&nbsp;&nbsp;offset:775:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:No prototype for non-static function. : ptirq_add_intx_remapping<br><br>5.filename:/hypervisor/arch/x86/guest/assign.c&nbsp;&nbsp;function:ptirq_remove_intx_remapping&nbsp;&nbsp;offset:789:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:No prototype for non-static function. : ptirq_remove_intx_remapping<br><br>6.filename:/hypervisor/arch/x86/guest/assign.c&nbsp;&nbsp;function:ptirq_remove_msix_remapping&nbsp;&nbsp;offset:799:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:No prototype for non-static function. : ptirq_remove_msix_remapping<br><br>7.filename:/hypervisor/arch/x86/guest/assign.c&nbsp;&nbsp;function:ptirq_add_msix_remapping&nbsp;&nbsp;offset:816:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:No prototype for non-static function. : ptirq_add_msix_remapping<br><br>8.filename:/hypervisor/arch/x86/guest/vmcall.c&nbsp;&nbsp;function:vmcall_vmexit_handler&nbsp;&nbsp;offset:195:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:No prototype for non-static function. : vmcall_vmexit_handler<br><br>9.filename:/hypervisor/arch/x86/guest/pm.c&nbsp;&nbsp;function:validate_pstate&nbsp;&nbsp;offset:13:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:No prototype for non-static function. : validate_pstate<br><br>10.filename:/hypervisor/arch/x86/guest/pm.c&nbsp;&nbsp;function:vm_setup_cpu_px&nbsp;&nbsp;offset:46:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Logical comparison of pointers.              : px_cnt and 20U<br><br>11.filename:/hypervisor/arch/x86/guest/pm.c&nbsp;&nbsp;function:vm_setup_cpu_state&nbsp;&nbsp;offset:90:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:No prototype for non-static function. : vm_setup_cpu_state<br><br>12.filename:/hypervisor/arch/x86/guest/pm.c&nbsp;&nbsp;function:vm_load_pm_s_state&nbsp;&nbsp;offset:100:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:No prototype for non-static function. : vm_load_pm_s_state<br><br>13.filename:/hypervisor/arch/x86/guest/pm.c&nbsp;&nbsp;function:register_pm1ab_handler&nbsp;&nbsp;offset:200:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:No prototype for non-static function. : register_pm1ab_handler<br><br>14.filename:/hypervisor/arch/x86/guest/vmsr.c&nbsp;&nbsp;function:rdmsr_vmexit_handler&nbsp;&nbsp;offset:375:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:No prototype for non-static function. : rdmsr_vmexit_handler<br><br>15.filename:/hypervisor/arch/x86/guest/vmsr.c&nbsp;&nbsp;function:wrmsr_vmexit_handler&nbsp;&nbsp;offset:509:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:No prototype for non-static function. : wrmsr_vmexit_handler<br><br>16.filename:/hypervisor/include/arch/x86/pgtable.h&nbsp;&nbsp;function:hva2hpa&nbsp;&nbsp;offset:100:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Static procedure is not explicitly called in code analysed. : hva2hpa<br><br>17.filename:/hypervisor/arch/x86/guest/guest_memory.c&nbsp;&nbsp;function:hva2gpa&nbsp;&nbsp;offset:439:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Procedure is not called or referenced in code analysed. : hva2gpa<br><br>

**Comment by HuiHuangShi** [comment]
> 2569
> 17 new potential violations to the coding guideline detected. Please help check. Thanks!
> 
> 1.filename:/hypervisor/arch/x86/guest/assign.c  function:ptirq_intx_ack  offset:537:
>        reason:No prototype for non-static function. : ptirq_intx_ack
> 
> 2.filename:/hypervisor/arch/x86/guest/assign.c  function:ptirq_msix_remap  offset:582:
>        reason:No prototype for non-static function. : ptirq_msix_remap
> 
> 3.filename:/hypervisor/arch/x86/guest/assign.c  function:ptirq_intx_pin_remap  offset:672:
>        reason:No prototype for non-static function. : ptirq_intx_pin_remap
> 
> 4.filename:/hypervisor/arch/x86/guest/assign.c  function:ptirq_add_intx_remapping  offset:775:
>        reason:No prototype for non-static function. : ptirq_add_intx_remapping
> 
> 5.filename:/hypervisor/arch/x86/guest/assign.c  function:ptirq_remove_intx_remapping  offset:789:
>        reason:No prototype for non-static function. : ptirq_remove_intx_remapping
> 
> 6.filename:/hypervisor/arch/x86/guest/assign.c  function:ptirq_remove_msix_remapping  offset:799:
>        reason:No prototype for non-static function. : ptirq_remove_msix_remapping
> 
> 7.filename:/hypervisor/arch/x86/guest/assign.c  function:ptirq_add_msix_remapping  offset:816:
>        reason:No prototype for non-static function. : ptirq_add_msix_remapping
> 
> 8.filename:/hypervisor/arch/x86/guest/vmcall.c  function:vmcall_vmexit_handler  offset:195:
>        reason:No prototype for non-static function. : vmcall_vmexit_handler
> 
> 9.filename:/hypervisor/arch/x86/guest/pm.c  function:validate_pstate  offset:13:
>        reason:No prototype for non-static function. : validate_pstate
> 
> 10.filename:/hypervisor/arch/x86/guest/pm.c  function:vm_setup_cpu_px  offset:46:
>        reason:Logical comparison of pointers. : px_cnt and 20U
> 
> 11.filename:/hypervisor/arch/x86/guest/pm.c  function:vm_setup_cpu_state  offset:90:
>        reason:No prototype for non-static function. : vm_setup_cpu_state
> 
> 12.filename:/hypervisor/arch/x86/guest/pm.c  function:vm_load_pm_s_state  offset100
>        reason:No prototype for non-static function. : vm_load_pm_s_state
> 
> 13.filename:/hypervisor/arch/x86/guest/pm.c  function:register_pm1ab_handler  offset:200:
>        reason:No prototype for non-static function. : register_pm1ab_handler
> 
> 14.filename:/hypervisor/arch/x86/guest/vmsr.c  function:rdmsr_vmexit_handler  offset:375:
>        reason:No prototype for non-static function. : rdmsr_vmexit_handler
> 
> 15.filename:/hypervisor/arch/x86/guest/vmsr.c  function:wrmsr_vmexit_handler  offset:509:
>        reason:No prototype for non-static function. : wrmsr_vmexit_handler
> 
> 16.filename:/hypervisor/include/arch/x86/pgtable.h  function:hva2hpa  offset100
>        reason:Static procedure is not explicitly called in code analysed. : hva2hpa
> 
> 17.filename:/hypervisor/arch/x86/guest/guest_memory.c  function:hva2gpa  offset:439:
>        reason:Procedure is not called or referenced in code analysed. : hva2gpa

all of is false positive

**Pull request merged**
