### PR TITLE
HV: move vCOM setting from Kconfig to board configs

### PR DESCRIPTION
**Pull request by jsun26intel**
- The settings of SOS VM COM1 which is used for console is board specific,
    and this result in SOS VM COM2 which used for VM communication is also
    board specific, so move the configure method from Kconfig to board configs
    folder. The MACRO definition will be handled by acrn-config tool in future.

- The vCOM2 of each VM is designed for VM communication, one VM could send
    command or request to another VM through this channel. The feature will
    be used for system S3/S5 implementation. On Hybird scenario, vCOM2 of pre-launched
    VM will connect to vCOM2 of SOS_VM; On Industry scenario, vCOM2 of post-launched
    RTVM will connect to vCOM2 of SOS_VM.

Tracked-On: #3602

Signed-off-by: Victor Sun <victor.sun@intel.com>
Reviewed-by: Eddie Dong <eddie.dong@intel.com>

### CODE REVIEW

**Comment by acrnsi** [comment]
OK to verify

**Comment by acrnsi** [comment]
OK to verify

**Comment by jsun26intel** [comment]
OK to verify

**Comment by HuiHuangShi** [comment]
No new violations to the coding guideline detected.<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Pull request merged**
