### PR TITLE
config: enable parsing dmar table dynamically on UP2

### PR DESCRIPTION
**Pull request by totoroow**
We need to parse dmar table on UP2+SBL, otherwise all
the interrupts from IOAPIC don't work.

Tracked-On: #2572
Signed-off-by: Tw <wei.tan@intel.com>
Reviewed-by: Binbin Wu <binbin.wu@intel.com>

### CODE REVIEW

**Comment by HuiHuangShi** [comment]
2573 <br>The PR does not touch any hypervisor source file. Skip coding guideline checks.<br>

**Comment by wenlingz** [comment]
@dongyaozu please help approve it, which fix SBL_UP2 fail to launch UOS issue, thanks

**Comment by totoroow** [comment]
@wenlingz ,should be SOS not UOS.

**Comment by wenlingz** [comment]
> @wenlingz ,should be SOS not UOS.

Thanks for your correction

**Pull request merged**
