### PR TITLE
Replacing plain type use

### PR DESCRIPTION
**Pull request by lifeix**
Avoid to use basic type.

Tracked-On: #861
Signed-off-by: Li, Fei1 <fei1.li@intel.com>

### CODE REVIEW

**Comment by wenlingz** [comment]
@lifeix please fix your code, it has issue ,please refer:
common/hypercall.c: In function 'hcall_set_vm_memory_regions':
common/hypercall.c:615:15: error: 'set_regions' undeclared (first use in this function)
  while (idx < set_regions.mr_num) {
               ^~~~~~~~~~~
common/hypercall.c:615:15: note: each undeclared identifier is reported only once for each function it appears in
make[2]: *** [Makefile:369: /workspace/out/hv/uefi/hypervisor/common/hypercall.o] Error 1
make[2]: Leaving directory '/workspace/acrn-hypervisor/hypervisor'
make[1]: *** [Makefile:22: hypervisor] Error 2
make[1]: Leaving directory '/workspace/acrn-hypervisor'
make: *** [Makefile:203: hypervisor] Error 2
Build step 'Execute shell' marked build as failure

**Comment by wenlingz** [comment]
@shiqingg please add label,thanks

**Comment by wenlingz** [comment]
@lifeix please rebase your code,thanks

**Comment by shiqingg** [comment]
@HuiHuangShi Could you please trigger the PR scan?

**Comment by HuiHuangShi** [comment]
2010<br>36 new potential violations to the coding guideline detected. Please help check. Thanks!  <br><br>1.filename:/hypervisor/lib/crypto/mbedtls/md.c&nbsp;&nbsp;function:mbedtls_md_hmac_starts&nbsp;&nbsp;offset:157:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Cast from pointer to integral type. : (unsigned char* to unsigned char): ( uint8_t ) ( ipad [ i ] ^ key [ i ] )<br><br>2.filename:/hypervisor/lib/crypto/mbedtls/md.c&nbsp;&nbsp;function:mbedtls_md_hmac_starts&nbsp;&nbsp;offset:158:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Cast from pointer to integral type. : (unsigned char* to unsigned char): ( uint8_t ) ( opad [ i ] ^ key [ i ] )<br><br>3.filename:/hypervisor/lib/crypto/mbedtls/sha256.c&nbsp;&nbsp;function:mbedtls_sha256_finish_ret&nbsp;&nbsp;offset:289:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Value is not of appropriate type. :  (unsigned char* and unsigned char): ( 56 ) ] = ( uint8_t<br><br>4.filename:/hypervisor/lib/crypto/mbedtls/sha256.c&nbsp;&nbsp;function:mbedtls_sha256_finish_ret&nbsp;&nbsp;offset:289:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Value is not of appropriate type. :  (unsigned char* and unsigned char): ( 56 ) + 3 ] = ( uint8_t<br><br>5.filename:/hypervisor/lib/crypto/mbedtls/sha256.c&nbsp;&nbsp;function:mbedtls_sha256_finish_ret&nbsp;&nbsp;offset:289:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Value is not of appropriate type. :  (unsigned char* and unsigned char): ( 56 ) + 1 ] = ( uint8_t<br><br>6.filename:/hypervisor/lib/crypto/mbedtls/sha256.c&nbsp;&nbsp;function:mbedtls_sha256_finish_ret&nbsp;&nbsp;offset:289:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Value is not of appropriate type. :  (unsigned char* and unsigned char): ( 56 ) + 2 ] = ( uint8_t<br><br>7.filename:/hypervisor/lib/crypto/mbedtls/sha256.c&nbsp;&nbsp;function:mbedtls_sha256_finish_ret&nbsp;&nbsp;offset:290:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Value is not of appropriate type. :  (unsigned char* and unsigned char): ( 60 ) + 1 ] = ( uint8_t<br><br>8.filename:/hypervisor/lib/crypto/mbedtls/sha256.c&nbsp;&nbsp;function:mbedtls_sha256_finish_ret&nbsp;&nbsp;offset:290:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Value is not of appropriate type. :  (unsigned char* and unsigned char): ( 60 ) + 2 ] = ( uint8_t<br><br>9.filename:/hypervisor/lib/crypto/mbedtls/sha256.c&nbsp;&nbsp;function:mbedtls_sha256_finish_ret&nbsp;&nbsp;offset:290:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Value is not of appropriate type. :  (unsigned char* and unsigned char): ( 60 ) ] = ( uint8_t<br><br>10.filename:/hypervisor/lib/crypto/mbedtls/sha256.c&nbsp;&nbsp;function:mbedtls_sha256_finish_ret&nbsp;&nbsp;offset:290:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Value is not of appropriate type. :  (unsigned char* and unsigned char): ( 60 ) + 3 ] = ( uint8_t<br><br>11.filename:/hypervisor/lib/crypto/mbedtls/sha256.c&nbsp;&nbsp;function:mbedtls_sha256_finish_ret&nbsp;&nbsp;offset:298:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Value is not of appropriate type. :  (unsigned char* and unsigned char): ( 0 ) + 1 ] = ( uint8_t<br><br>12.filename:/hypervisor/lib/crypto/mbedtls/sha256.c&nbsp;&nbsp;function:mbedtls_sha256_finish_ret&nbsp;&nbsp;offset:298:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Value is not of appropriate type. :  (unsigned char* and unsigned char): ( 0 ) ] = ( uint8_t<br><br>13.filename:/hypervisor/lib/crypto/mbedtls/sha256.c&nbsp;&nbsp;function:mbedtls_sha256_finish_ret&nbsp;&nbsp;offset:298:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Value is not of appropriate type. :  (unsigned char* and unsigned char): ( 0 ) + 2 ] = ( uint8_t<br><br>14.filename:/hypervisor/lib/crypto/mbedtls/sha256.c&nbsp;&nbsp;function:mbedtls_sha256_finish_ret&nbsp;&nbsp;offset:298:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Value is not of appropriate type. :  (unsigned char* and unsigned char): ( 0 ) + 3 ] = ( uint8_t<br><br>15.filename:/hypervisor/lib/crypto/mbedtls/sha256.c&nbsp;&nbsp;function:mbedtls_sha256_finish_ret&nbsp;&nbsp;offset:299:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Value is not of appropriate type. :  (unsigned char* and unsigned char): ( 4 ) + 3 ] = ( uint8_t<br><br>16.filename:/hypervisor/lib/crypto/mbedtls/sha256.c&nbsp;&nbsp;function:mbedtls_sha256_finish_ret&nbsp;&nbsp;offset:299:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Value is not of appropriate type. :  (unsigned char* and unsigned char): ( 4 ) + 1 ] = ( uint8_t<br><br>17.filename:/hypervisor/lib/crypto/mbedtls/sha256.c&nbsp;&nbsp;function:mbedtls_sha256_finish_ret&nbsp;&nbsp;offset:299:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Value is not of appropriate type. :  (unsigned char* and unsigned char): ( 4 ) + 2 ] = ( uint8_t<br><br>18.filename:/hypervisor/lib/crypto/mbedtls/sha256.c&nbsp;&nbsp;function:mbedtls_sha256_finish_ret&nbsp;&nbsp;offset:299:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Value is not of appropriate type. :  (unsigned char* and unsigned char): ( 4 ) ] = ( uint8_t<br><br>19.filename:/hypervisor/lib/crypto/mbedtls/sha256.c&nbsp;&nbsp;function:mbedtls_sha256_finish_ret&nbsp;&nbsp;offset:300:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Value is not of appropriate type. :  (unsigned char* and unsigned char): ( 8 ) + 1 ] = ( uint8_t<br><br>20.filename:/hypervisor/lib/crypto/mbedtls/sha256.c&nbsp;&nbsp;function:mbedtls_sha256_finish_ret&nbsp;&nbsp;offset:300:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Value is not of appropriate type. :  (unsigned char* and unsigned char): ( 8 ) + 3 ] = ( uint8_t<br><br>21.filename:/hypervisor/lib/crypto/mbedtls/sha256.c&nbsp;&nbsp;function:mbedtls_sha256_finish_ret&nbsp;&nbsp;offset:300:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Value is not of appropriate type. :  (unsigned char* and unsigned char): ( 8 ) + 2 ] = ( uint8_t<br><br>22.filename:/hypervisor/lib/crypto/mbedtls/sha256.c&nbsp;&nbsp;function:mbedtls_sha256_finish_ret&nbsp;&nbsp;offset:300:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Value is not of appropriate type. :  (unsigned char* and unsigned char): ( 8 ) ] = ( uint8_t<br><br>23.filename:/hypervisor/lib/crypto/mbedtls/sha256.c&nbsp;&nbsp;function:mbedtls_sha256_finish_ret&nbsp;&nbsp;offset:301:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Value is not of appropriate type. :  (unsigned char* and unsigned char): ( 12 ) + 2 ] = ( uint8_t<br><br>24.filename:/hypervisor/lib/crypto/mbedtls/sha256.c&nbsp;&nbsp;function:mbedtls_sha256_finish_ret&nbsp;&nbsp;offset:301:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Value is not of appropriate type. :  (unsigned char* and unsigned char): ( 12 ) + 1 ] = ( uint8_t<br><br>25.filename:/hypervisor/lib/crypto/mbedtls/sha256.c&nbsp;&nbsp;function:mbedtls_sha256_finish_ret&nbsp;&nbsp;offset:301:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Value is not of appropriate type. :  (unsigned char* and unsigned char): ( 12 ) + 3 ] = ( uint8_t<br><br>26.filename:/hypervisor/lib/crypto/mbedtls/sha256.c&nbsp;&nbsp;function:mbedtls_sha256_finish_ret&nbsp;&nbsp;offset:301:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Value is not of appropriate type. :  (unsigned char* and unsigned char): ( 12 ) ] = ( uint8_t<br><br>27.filename:/hypervisor/lib/crypto/mbedtls/sha256.c&nbsp;&nbsp;function:mbedtls_sha256_finish_ret&nbsp;&nbsp;offset:302:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Value is not of appropriate type. :  (unsigned char* and unsigned char): ( 16 ) + 3 ] = ( uint8_t<br><br>28.filename:/hypervisor/lib/crypto/mbedtls/sha256.c&nbsp;&nbsp;function:mbedtls_sha256_finish_ret&nbsp;&nbsp;offset:302:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Value is not of appropriate type. :  (unsigned char* and unsigned char): ( 16 ) ] = ( uint8_t<br><br>29.filename:/hypervisor/lib/crypto/mbedtls/sha256.c&nbsp;&nbsp;function:mbedtls_sha256_finish_ret&nbsp;&nbsp;offset:302:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Value is not of appropriate type. :  (unsigned char* and unsigned char): ( 16 ) + 1 ] = ( uint8_t<br><br>30.filename:/hypervisor/lib/crypto/mbedtls/sha256.c&nbsp;&nbsp;function:mbedtls_sha256_finish_ret&nbsp;&nbsp;offset:302:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Value is not of appropriate type. :  (unsigned char* and unsigned char): ( 16 ) + 2 ] = ( uint8_t<br><br>31.filename:/hypervisor/lib/crypto/mbedtls/sha256.c&nbsp;&nbsp;function:mbedtls_sha256_finish_ret&nbsp;&nbsp;offset:303:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Value is not of appropriate type. :  (unsigned char* and unsigned char): ( 20 ) + 2 ] = ( uint8_t<br><br><br>.... and more

**Pull request merged**
