### PR TITLE
Acrn support Splitlock Access detection

### PR DESCRIPTION
**Pull request by taoyuhong**
When the destination of an atomic memory operation located in 2 cache lines, it is called a Splitlock Access. LOCK# bus signal is asserted for splitloc access which can reduce performance. #AC for Splitlock Access is a CPU feature, it allows rise alignment check exception #AC(0) instead of asserting LOCK#, that is helpful to detect Splitlock Access.

The design:
•Always enable #AC on split lock in physical side
•Present virtual split lock capability to guest, and directly deliver #AC to guest (virtual split-lock capability helps the guest to isolate violations from user land).
•Guest write of MSR_TEST_CTL is ignored, guest read gets the written value
•If split-lock happens in ACRN, this is a software bug we must fix it.
•If split-lock happens in guest kernel, the guest may not be able to fix the issue gracefully (the guest may behavior differently with that of native OS).  The RT guest should avoid the split-lock, otherwise it is a software bug.

Tracked-On: #4496

### CODE REVIEW

**Comment by HuiHuangShi** [comment]
5 new potential violations to the coding guideline detected. Please help check. Thanks!<br><1> config:common filename:/hypervisor/arch/x86/guest/vmsr.c func:wrmsr_vmexit_handler offset:704<br> reason:Cyclomatic complexity greater than 20.<br><2> config:common filename:/hypervisor/arch/x86/cpu_caps.c func:detect_core_caps offset:228<br> reason:Implicit conversion of underlying type (MR). :  (unsigned int and unsigned long): msr_read<br><3> config:common filename:/hypervisor/arch/x86/cpu_caps.c func:detect_core_caps offset:228<br> reason:Narrower int conversion without cast. :  (unsigned int and unsigned long): msr_read<br><4> config:common filename:/hypervisor/arch/x86/cpu.c func:enable_ac_for_splitlock offset:105<br> reason:No space between if, while, for and expresn.<br><5> config:common filename:/hypervisor/arch/x86/cpu.c func:enable_ac_for_splitlock offset:107<br> reason:Space missing before or after binary operator.<br><br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by HuiHuangShi** [comment]
1 new potential violations to the coding guideline detected. Please help check. Thanks!<br><1> config:common filename:/hypervisor/arch/x86/guest/vmsr.c func:wrmsr_vmexit_handler offset:704<br> reason:Cyclomatic complexity greater than 20.<br><br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by HuiHuangShi** [comment]
4 new potential violations to the coding guideline detected. Please help check. Thanks!<br><1> config:part_config filename:/hypervisor/arch/x86/guest/vmsr.c func:test_ctl_msr_read offset:388<br> reason:Pointer param should be declared pointer to const. : vcpu<br><2> config:sharing_config filename:/hypervisor/arch/x86/guest/vmsr.c func:test_ctl_msr_read offset:388<br> reason:Pointer param should be declared pointer to const. : vcpu<br><3> config:sharing_config filename:/hypervisor/arch/x86/guest/vmsr.c func:test_ctl_msr_write offset:710<br> reason:Pointer param should be declared pointer to const. : vcpu<br><4> config:part_config filename:/hypervisor/arch/x86/guest/vmsr.c func:test_ctl_msr_write offset:710<br> reason:Pointer param should be declared pointer to const. : vcpu<br><br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by leilu** [comment]
OK to verify

**Comment by HuiHuangShi** [comment]
1 new potential violations to the coding guideline detected. Please help check. Thanks!<br><1> config:common filename:/hypervisor/arch/x86/guest/vmsr.c func:wrmsr_vmexit_handler offset:704<br> reason:Cyclomatic complexity greater than 20.<br><br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Pull request merged**
