### PR TITLE
fix spelling errors for acrn-manager

### PR DESCRIPTION
**Pull request by shenjoon**
Signed-off-by: Tan Shen Joon <shen.joon.tan@intel.com>

### CODE REVIEW

**Comment by NanlinXie** [comment]
Can one of the admins verify this patch?

**Comment by miguelinux** [comment]
+1

**Comment by lijinxia** [comment]
OK to verify

**Comment by miguelinux** [comment]
@jren1 this is the patch 002

**Comment by lyan3** [comment]
+1
Thanks Miguel.

**Comment by lijinxia** [comment]
OK to verify

**Comment by miguelinux** [comment]
@jren1 @lijinxia @NanlinXie 
Whay this PR was not merged by today/yesterday (2018w23.5) tag?

**Comment by lijinxia** [comment]
Verified+1

**Pull request merged**
