### PR TITLE
hv: alloc multiboot modules memory

### PR DESCRIPTION
**Pull request by weichenli-intel**
Now the multiboot modules memory have not reserve,it's an issue if
these memory alloc and write before VM start.

Incorrect allocation of multiboot modules memory will cause VM lost
data or start faild.

So we find these modules memory range and reserve these memory from
e820 entry.

All these memory will realloc to VM which own them before the vm start.

Tracked-On: #6690
Acked-by: Anthony Xu <anthony.xu@intel.com>
Signed-off-by: Chenli Wei <chenli.wei@intel.com>

### CODE REVIEW

**Comment by acrnsi** [comment]
Can one of the admins verify this patch?

**Comment by wenlingz** [comment]
@anthonyzxu @dongyaozu please help approve this PR, thanks

**Review by anthonyzxu — APPROVED** [review]

**Comment by wenlingz** [comment]
start to run premerge test

**Comment by wenlingz** [comment]
start to run premerge test

**Pull request merged**
