### PR TITLE
Service VM S3 related issues fix

### PR DESCRIPTION
**Pull request by haiwei-li**

### CODE REVIEW

**Comment by yuhuanX** [comment]
start to run premerge test

**Comment by wenlingz** [comment]
@lifeix @junjiemao1 please help approve this PR, thanks

**Comment by junjiemao1** [comment]
There are still some unresolved discussions in the mailing list about this series.

**Comment by haiwei-li** [comment]
Just wait all are reviewed in acrn-dev community.

**Comment by yuhuanX** [comment]
start to run premerge test

**Review by junjiemao1 — APPROVED** [review]

**Comment by yuhuanX** [comment]
start to run premerge test

**Comment by yuhuanX** [comment]
start to run premerge test

**Pull request merged**
