### PR TITLE
XML assertion-based advanced error reporting

### PR DESCRIPTION
**Pull request by junjiemao1**
This patch series introduces customizations to the Python elementpath library and XML schema assertion attributes so that each assertion in the XML schema can:

  1. Use XPath (up to 2.0) in error messages to fetch specific information about the errors. Refer to the added XML schemas under schema/check directory for examples.

  2. Use XPath (again up to 2.0) in an additional attribute acrn:report-on to specify the XML node(s) related to the error. Such nodes can be those where the error is detected, where the error can be fixed or any other kind that provide users with a concrete context about the error.

### CODE REVIEW

**Comment by acrnsi** [comment]
Can one of the admins verify this patch?

**Review by dbkinder — COMMENTED** [review]
Should misc/config_tools/schema/checks/.pre_launched_vm_support.xsd.swp be part of this PR?

**Comment by junjiemao1** [comment]
> Should misc/config_tools/schema/checks/.pre_launched_vm_support.xsd.swp be part of this PR?

This file was accidentally added to the repo a few days ago, while such binaries should never be committed. I take the chance of this PR to drop it.

**Review by gvancuts — APPROVED** [review]

**Review by NanlinXie — APPROVED** [review]

**Comment by wenlingz** [comment]
start to run premerge test

**Comment by dbkinder** [comment]
Ah, I see now it's being deleted (D).

**Review by dbkinder — APPROVED** [review]

**Pull request merged**
