### PR TITLE
misc: totally remove misc folder

### PR DESCRIPTION
**Pull request by alekdu**
misc now has a new home: https://github.com/intel/ioc-cbc-tools.

The "Execstop" patch will be synced to new git tree soon.

ioc-cbc-tools was just added to Clear Linux, and will be added to
software-defined-cockpit bundle after this patch merged.

Merging this patch may cause some IOC releated feature block until we
get a new Clear Linux release. This is the switch window ...

Signed-off-by: Alek Du <alek.du@intel.com>
Reviewed-by: Yu Wang <yu1.wang@intel.com>

### CODE REVIEW

**Comment by alekdu** [comment]
Hi Jinxia, notification for QA, if this patch will remove IOC related features, so probably your auto test may report some related issues. Please ignore them if it is only related with IOC...

**Comment by dongyaozu** [comment]
@ywan170 can you review?

**Comment by alekdu** [comment]
Hi Eddie, Yu Wang has acked the patch in the mail.

**Comment by lijinxia** [comment]
Verified+1

**Pull request merged**
