### PR TITLE
DM: fix memory leak

### PR DESCRIPTION
**Pull request by mcao6**
1. free memory allocated by strdup in blockif_open
2. free msix.table when its pci device deinit

Tracked-On: #2704
Signed-off-by: Minggui Cao <minggui.cao@intel.com>
Acked-by: Yin Fengwei <fengwei.yin@intel.com>

### CODE REVIEW

**Comment by HuiHuangShi** [comment]
No new violations to the coding guideline detected.<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by HuiHuangShi** [comment]
No new violations to the coding guideline detected.<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by wenlingz** [comment]
@fyin1 please help approve this PR,thanks

**Comment by acrnsi** [comment]
Ok to verify

**Comment by HuiHuangShi** [comment]
No new violations to the coding guideline detected.<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by acrnsi** [comment]
Ok to verify

**Comment by HuiHuangShi** [comment]
No new violations to the coding guideline detected.<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by acrnsi** [comment]
@mcao6 please rebase your code

**Comment by acrnsi** [comment]
@mcao6 please rebase your code

**Comment by acrnsi** [comment]
@mcao6  This branch has conflicts that must be resolved

**Comment by dbkinder** [comment]
I suspect a rebase is needed?

**Comment by mcao6** [comment]
the patch is merged into master branch; for apl_stable branch, this PR could be something wrong, will open another one after close this one.

**Pull request closed without merging**
