### PR TITLE
acrn-config: add PCI vuart config in config tool UI

### PR DESCRIPTION
**Pull request by szhen11**
Add PCI vuart config for scenario setting and launche setting of config
tool UI. The original vuart setting is changed to legacy vuart setting.

Shuang Zheng (3):
  acrn-config: add PCI VUART config in scenario config UI
  acrn-config: add PCI VUART config in launch config UI
  acrn-config: add mutually exclusive logic for legacy vuart and PCI
    vuart on config UI

### CODE REVIEW

**Comment by HuiHuangShi** [comment]
No new violations to the coding guideline detected.<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Review by terryzouhao — APPROVED** [review]

**Comment by yuchuyang** [comment]
[External_System_ID]ACRN-6684

**Review by terryzouhao — COMMENTED** [review]
@szhen11  do you have track-on for this PR ?

**Comment by szhen11** [comment]
> @szhen11 do you have track-on for this PR ?

I will add Tracked-On and review info after EB test.

**Comment by HuiHuangShi** [comment]
No new violations to the coding guideline detected.<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Pull request merged**
