### PR TITLE
dm: update acrn-dm built-in list and description of args

### PR DESCRIPTION
**Pull request by gvancuts**
Update and light clean-up of the buit-in list of arguments from 'acrn-dm'
* Added options in the top part (list with no explanation)
* A couple of typos fixed
* A couple of options put inside an '#ifdef' statement

Tracked-On: #5445
Signed-off-by: Geoffroy Van Cutsem <geoffroy.vancutsem@intel.com>

### CODE REVIEW

**Comment by HuiHuangShi** [comment]
No new violations to the coding guideline detected.<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by HuiHuangShi** [comment]
No new violations to the coding guideline detected.<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by HuiHuangShi** [comment]
No new violations to the coding guideline detected.<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by HuiHuangShi** [comment]
No new violations to the coding guideline detected.<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by gvancuts** [comment]
@NanlinXie , who can help me understand why the one of the test failed? I can't think of a reason why that one would fail and others would be fine... thanks in advance!

**Comment by wenlingz** [comment]
@hwang37 please help approve this PR, thanks

**Comment by gvancuts** [comment]
@wenlingz , are we still waiting for any approval for this?

**Comment by wenlingz** [comment]
> @wenlingz , are we still waiting for any approval for this?

Need @ywan170 help approve this PR

**Comment by wenlingz** [comment]
@ywan170 please help approve this PR, thanks

**Review by ywan170 — APPROVED** [review]

**Pull request merged**
