### PR TITLE
config tool: Redefine vm_type and add load_order

### PR DESCRIPTION
**Pull request by liuhang-bit**
Patches includes:
    1.Add load_order(PRE_LAUNCHED_VM/SERVICE_VM/POST_LAUNCHED_VM) parameter
    2.Change vm_type parameter to values as RTVM, STANDARD_VM, TEE, REE
      TEE and REE are hidden in UI.
    3.Deduce vm severity in vm_configuration from vm_type and load_order
    4. Change the corresponding scenario.xml in repo
   
    Tracked-On: #6690
    Signed-off-by: hangliu1 <hang1.liu@linux.intel.com>
    Reviewed-by: Junjie Mao <junjie.mao@intel.com>

### CODE REVIEW

**Comment by acrnsi** [comment]
Can one of the admins verify this patch?

**Comment by wenlingz** [comment]
@liuhang-bit  build fail, please refer:

+ make BOARD=tgl-rvp SCENARIO=shared RELEASE=n
make[1]: Entering directory '/home/acrn/workspace/acrn-hypervisor-build-native_6331/acrn-hypervisor/hypervisor'
Board XML is fetched from /home/acrn/workspace/acrn-hypervisor-build-native_6331/acrn-hypervisor/misc/config_tools/data/tgl-rvp/tgl-rvp.xml
Scenario XML is being fetched from /home/acrn/workspace/acrn-hypervisor-build-native_6331/acrn-hypervisor/misc/config_tools/data/tgl-rvp/shared.xml
/home/acrn/workspace/acrn-hypervisor-build-native_6331/acrn-hypervisor/misc/config_tools/static_allocators/lib/lib.py:116: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if vm_type is 'PRE_LAUNCHED_VM':
/home/acrn/workspace/acrn-hypervisor-build-native_6331/acrn-hypervisor/misc/config_tools/static_allocators/lib/lib.py:121: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if vm_type is 'POST_LAUNCHED_VM':
/home/acrn/workspace/acrn-hypervisor-build-native_6331/acrn-hypervisor/misc/config_tools/static_allocators/lib/lib.py:126: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if vm_type is 'SERVICE_VM':
/home/acrn/workspace/acrn-hypervisor-build-native_6331/acrn-hypervisor/build/hypervisor/configs/allocation.xml generated
/home/acrn/workspace/acrn-hypervisor-build-native_6331/acrn-hypervisor/build/hypervisor/configs/unified.xml generated
/home/acrn/workspace/acrn-hypervisor-build-native_6331/acrn-hypervisor/build/hypervisor/configs/config.mk generated
WARNING:root:Scenario .scenario.xml is invalid: 21 schema errors.
make[1]: Leaving directory '/home/acrn/workspace/acrn-hypervisor-build-native_6331/acrn-hypervisor/hypervisor'
make -C /home/acrn/workspace/acrn-hypervisor-build-native_6331/acrn-hypervisor/hypervisor BOARD=tgl-rvp SCENARIO=shared HV_OBJDIR=/home/acrn/workspace/acrn-hypervisor-build-native_6331/acrn-hypervisor/build/hypervisor RELEASE=n
make[1]: Entering directory '/home/acrn/workspace/acrn-hypervisor-build-native_6331/acrn-hypervisor/hypervisor'
/home/acrn/workspace/acrn-hypervisor-build-native_6331/acrn-hypervisor/build/hypervisor/include/config.h generated
Start pre-build static check ...
make -C ../misc/hv_prebuild BOARD=tgl-rvp SCENARIO=shared TARGET_DIR=/home/acrn/workspace/acrn-hypervisor-build-native_6331/acrn-hypervisor/build/hypervisor/configs
make[2]: Entering directory '/home/acrn/workspace/acrn-hypervisor-build-native_6331/acrn-hypervisor/misc/hv_prebuild'
make[2]: *** No rule to make target '/home/acrn/workspace/acrn-hypervisor-build-native_6331/acrn-hypervisor/build/hypervisor/configs/scenarios/shared/vm_configurations.c', needed by 'default'.  Stop.
make[2]: Leaving directory '/home/acrn/workspace/acrn-hypervisor-build-native_6331/acrn-hypervisor/misc/hv_prebuild'
make[1]: *** [Makefile:419: pre_build] Error 2
make[1]: Leaving directory '/home/acrn/workspace/acrn-hypervisor-build-native_6331/acrn-hypervisor/hypervisor'
make: *** [Makefile:109: hypervisor] Error 2

**Comment by wenlingz** [comment]
@liuhang-bit please use EB service to verify your code before you created PR, thanks

**Comment by wenlingz** [comment]
@liuhang-bit please rebase your code, thanks

**Comment by szhen11** [comment]
start to run premerge test

**Comment by szhen11** [comment]
@liuhang-bit, launch script generation failed:

+ '[' -f misc/config_tools/data/tgl-rvp/shared_launch_2user_vm.xml ']'
+ python3 misc/config_tools/launch_config/launch_cfg_gen.py --board misc/config_tools/data/tgl-rvp/tgl-rvp.xml --scenario misc/config_tools/data/tgl-rvp/shared.xml --launch misc/config_tools/data/tgl-rvp/shared_launch_2user_vm.xml --user_vmid 0 --out output
Traceback (most recent call last):
  File "misc/config_tools/launch_config/launch_cfg_gen.py", line 267, in <module>
    err_dic = main(ARGS)
  File "misc/config_tools/launch_config/launch_cfg_gen.py", line 214, in main
    (err_dic, pt_sel, virt_io, dm, sriov) = validate_launch_setting(board_info_file, scenario_info_file, launch_info_file)
  File "misc/config_tools/launch_config/launch_cfg_gen.py", line 98, in validate_launch_setting
    dm.check_item()
  File "/home/acrn/workspace/acrn-hypervisor-build-native_6978/acrn-hypervisor/misc/config_tools/launch_config/launch_item.py", line 65, in check_item
    err_dic = scenario_cfg_lib.vm_cpu_affinity_check(self.scenario_info, self.launch_info, cpu_affinity)
  File "/home/acrn/workspace/acrn-hypervisor-build-native_6978/acrn-hypervisor/misc/config_tools/launch_config/../library/scenario_cfg_lib.py", line 334, in vm_cpu_affinity_check
    elif VM_DB[load_order]['load_type'] == "PRE_LAUNCHED_VM":
KeyError: 'POST_LAUNCHED_VM'
+ '[' -f misc/config_tools/data/tgl-rvp/shared_launch_6user_vm.xml ']'
+ python3 misc/config_tools/launch_config/launch_cfg_gen.py --board misc/config_tools/data/tgl-rvp/tgl-rvp.xml --scenario misc/config_tools/data/tgl-rvp/shared.xml --launch misc/config_tools/data/tgl-rvp/shared_launch_6user_vm.xml --user_vmid 0 --out output
Traceback (most recent call last):
  File "misc/config_tools/launch_config/launch_cfg_gen.py", line 267, in <module>
    err_dic = main(ARGS)
  File "misc/config_tools/launch_config/launch_cfg_gen.py", line 214, in main
    (err_dic, pt_sel, virt_io, dm, sriov) = validate_launch_setting(board_info_file, scenario_info_file, launch_info_file)
  File "misc/config_tools/launch_config/launch_cfg_gen.py", line 98, in validate_launch_setting
    dm.check_item()
  File "/home/acrn/workspace/acrn-hypervisor-build-native_6978/acrn-hypervisor/misc/config_tools/launch_config/launch_item.py", line 65, in check_item
    err_dic = scenario_cfg_lib.vm_cpu_affinity_check(self.scenario_info, self.launch_info, cpu_affinity)
  File "/home/acrn/workspace/acrn-hypervisor-build-native_6978/acrn-hypervisor/misc/config_tools/launch_config/../library/scenario_cfg_lib.py", line 334, in vm_cpu_affinity_check
    elif VM_DB[load_order]['load_type'] == "PRE_LAUNCHED_VM":
KeyError: 'POST_LAUNCHED_VM'

**Pull request merged**
