### PR TITLE
doc: update Kata on ACRN tutorial for Ubuntu Service VM

### PR DESCRIPTION
**Pull request by ttzeng**
This commit updates the tutorial of running Kata Containers on Ubuntu
Service VM.

Tracked-On: #4879
Signed-off-by: Tonny Tzeng <tonny.tzeng@intel.com>

### CODE REVIEW

**Comment by HuiHuangShi** [comment]
No new violations to the coding guideline detected.<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by HuiHuangShi** [comment]
No new violations to the coding guideline detected.<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by dbkinder** [comment]
Sigh.  Another update to the document caused a merge conflict.  It was easiest to close this PR and submit a new one (#4882) with the merged edits that included Tonny's content with my grammar edits, and my resolved merged conflicts.

**Comment by NanlinXie** [comment]
@ttzeng , Could you also updated the HV version and Ubuntu version that you verified on?

**Comment by ttzeng** [comment]
> @ttzeng , Could you also updated the HV version and Ubuntu version that you verified on?

@NanlinXie , since the document has been updated, I created a separate PR (#4894) to address your comment. Thanks.

**Pull request closed without merging**
