### PR TITLE
Ivshmem doorbell enable

### PR DESCRIPTION
**Pull request by yonghuah**
This patch set enables doorbell notification function for hv-land ivshmem device.
  With doorbell enabled, one VM can interrupt another VM when they use ivshmem
  devices as Inter-VM communication channel.

  According to ivshmem device specification(ver 1.0), ivshmem device interrupt function 
  shall be based on MSIX mechanism. this patch set refines some vmsix functions
  in hypervisor in order to emuate msix capability for hypervisor emulated PCI device.  

  This patch set adds function to add legacy PCI capability in configuration
  space, hence to add msix capability for hypervisor emulated PCI devices.

  This patch wraps one more interrupt injection function, to make it applicable for
  both vlapic case and lapic PT case.

  Finally, this patch set enables vmsix capability and hence doorbell(interrupt)
  for hv-land ivshmem devices.

### CODE REVIEW

**Review by dongyaozu — APPROVED** [review]

**Comment by wenlingz** [comment]
@yonghuah please chek your code, make doc fail, please refer:
make doc'
make -C /root/workspace/acrn-hypervisor-premerge-build-image4/acrn-hypervisor/doc html BUILDDIR=/root/workspace/acrn-hypervisor-premerge-build-image4/acrn-hypervisor/build/doc
make[1]: Entering directory '/root/workspace/acrn-hypervisor-premerge-build-image4/acrn-hypervisor/doc'

New errors/warnings found, please fix them:
==============================================

/root/workspace/acrn-hypervisor-premerge-build-image4/acrn-hypervisor/hypervisor/include/arch/x86/guest/vlapic.h:150: warning: argument 'msg' of command @param is not found in the argument list of vlapic_inject_msi(struct acrn_vm *vm, uint64_t addr, uint64_t data)
/root/workspace/acrn-hypervisor-premerge-build-image4/acrn-hypervisor/hypervisor/include/arch/x86/guest/vlapic.h:162: warning: The following parameters of vlapic_inject_msi(struct acrn_vm *vm, uint64_t addr, uint64_t data) are not documented:
  parameter 'data'
/root/workspace/acrn-hypervisor-premerge-build-image4/acrn-hypervisor/hypervisor/include/arch/x86/guest/vlapic.h:150: warning: argument 'msg' of command @param is not found in the argument list of vlapic_inject_msi(struct acrn_vm *vm, uint64_t addr, uint64_t data)
/root/workspace/acrn-hypervisor-premerge-build-image4/acrn-hypervisor/hypervisor/include/arch/x86/guest/vlapic.h:162: warning: The following parameters of vlapic_inject_msi(struct acrn_vm *vm, uint64_t addr, uint64_t data) are not documented:
  parameter 'data'
/root/workspace/acrn-hypervisor-premerge-build-image4/acrn-hypervisor/hypervisor/include/arch/x86/guest/vlapic.h:150: warning: argument 'msg' of command @param is not found in the argument list of vlapic_inject_msi(struct acrn_vm *vm, uint64_t addr, uint64_t data)
/root/workspace/acrn-hypervisor-premerge-build-image4/acrn-hypervisor/hypervisor/include/arch/x86/guest/vlapic.h:162: warning: The following parameters of vlapic_inject_msi(struct acrn_vm *vm, uint64_t addr, uint64_t data) are not documented:
  parameter 'data'
/root/workspace/acrn-hypervisor-premerge-build-image4/acrn-hypervisor/hypervisor/include/arch/x86/guest/vlapic.h:150: warning: argument 'msg' of command @param is not found in the argument list of vlapic_inject_msi(struct acrn_vm *vm, uint64_t addr, uint64_t data)
/root/workspace/acrn-hypervisor-premerge-build-image4/acrn-hypervisor/hypervisor/include/arch/x86/guest/vlapic.h:162: warning: The following parameters of vlapic_inject_msi(struct acrn_vm *vm, uint64_t addr, uint64_t data) are not documented:
  parameter 'data'
/root/workspace/acrn-hypervisor-premerge-build-image4/acrn-hypervisor/build/doc/rst/developer-guides/hld/hv-virt-interrupt.rst:110: WARNING: doxygenfunction: Cannot find function "vlapic_intr_msi" in doxygen xml output for project "Project ACRN" from directory: doxygen/xml

make[1]: *** [Makefile:61: html] Error 1
make[1]: Leaving directory '/root/workspace/acrn-hypervisor-premerge-build-image4/acrn-hypervisor/doc'
make: *** [Makefile:184: doc] Error 2

**Comment by wenlingz** [comment]
@yonghuah  build fail, please refer:
os/work/intel_corei7_64-oe-linux/acrn-hypervisor/5409-1603359358/build//hypervisor/dm/vpci/ivshmem.o -MMD -MT /home/meta-acrn/workspace/build/master-acrn-sos/work/intel_corei7_64-oe-linux/acrn-hypervisor/5409-1603359358/build//hypervisor/dm/vpci/ivshmem.o
| dm/vpci/ivshmem.c: In function 'ivshmem_server_bind_peer':
| dm/vpci/ivshmem.c:117:9: error: 'struct ivshmem_shm_region' has no member named 'doorbell_peers'
|   117 |   region->doorbell_peers[vm_id] = ivs_dev;
|       |         ^~
| dm/vpci/ivshmem.c: In function 'ivshmem_server_unbind_peer':
| dm/vpci/ivshmem.c:128:8: error: 'struct ivshmem_shm_region' has no member named 'doorbell_peers'
|   128 |  region->doorbell_peers[vpci2vm(vdev->vpci)->vm_id] = NULL;
|       |        ^~
| dm/vpci/ivshmem.c: In function 'ivshmem_server_notify_peer':
| dm/vpci/ivshmem.c:143:24: error: 'struct ivshmem_shm_region' has no member named 'doorbell_peers'
|   143 |   dest_ivs_dev = region->doorbell_peers[dest_peer_id];
|       |                        ^~
| Makefile:510: recipe for target '/home/meta-acrn/workspace/build/master-acrn-sos/work/intel_corei7_64-oe-linux/acrn-hypervisor/5409-1603359358/build//hypervisor/dm/vpci/ivshmem.o' failed
| make: *** [/home/meta-acrn/workspace/build/master-acrn-sos/work/intel_corei7_64-oe-linux/acrn-hypervisor/5409-1603359358/build//hypervisor/dm/vpci/ivshmem.o] Error 1
| make: Leaving directory '/home/meta-acrn/workspace/build/master-acrn-sos/work/intel_corei7_64-oe-linux/acrn-hypervisor/5409-1603359358/git/hypervisor'

**Comment by yonghuah** [comment]
@wenlingz  fixed this build error, thanks.

**Comment by wenlingz** [comment]
@HuiHuangShi please add MISRA-C check, thanks

**Comment by HuiHuangShi** [comment]
No new violations to the coding guideline detected.<br>No New Name Conflict<br>No New Function Declaration/Definition Mismatch

**Comment by yonghuah** [comment]
@HuiHuangShi  from the log, seems no d MISRA-C  violations are detected. can you update the status? @wenlingz 
thanks.
-Yonghua

**Pull request merged**
