### PR TITLE
Script: Fix snd_soc_skl typo in launch script

### PR DESCRIPTION
**Pull request by liuwei987**
fix snd_soc_sbk/snd_soc_sst_bxt_tdf8532 typo

Tracked-on: #2666
Signed-off-by: wenlingz <wenling.zhang@intel.com>

### CODE REVIEW

**Comment by HuiHuangShi** [comment]
No new violations to the coding guideline detected.<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by dongyaozu** [comment]
@binbinwu1 can u review?

**Comment by binbinwu1** [comment]
Reviewed-by: Binbin Wu <binbin.wu@intel.com>

**Comment by wenlingz** [comment]
@liuwei987 @binbinwu1 this PR can be closed because  I have created PR to fixed on the master, thanks

**Pull request closed without merging**
