### PR TITLE
x86_tee patches upstream

### PR DESCRIPTION
**Pull request by yfliuuu**
These patches are third batch of x86_tee patches.

### CODE REVIEW

**Comment by acrnsi** [comment]
Can one of the admins verify this patch?

**Comment by yfliuuu** [comment]
Force pushed: Update last commit to avoid MISRA-C check problem

**Comment by wenlingz** [comment]
No new violations to the coding guideline detected.
No New Name Conflict
No New Function Declaration/Definition Mismatch

**Comment by wenlingz** [comment]
@dongyaozu please help approve this PR, thanks

**Review by anthonyzxu — APPROVED** [review]

**Pull request merged**
