### PR TITLE
Add configuration files for ASRock system

### PR DESCRIPTION
**Pull request by zhangrouyu**
Add configuration files for ASRock system, with Intel(R) 12th Gen Core(TM)CPU(formerly known as Alder Lake) and 32G memory.

Signed-off-by: zhangrouyu <rouyu.zhang@intel.com>

### CODE REVIEW

**Comment by gvancuts** [comment]
I have not double-checked this so let me ask: the `adl-asrock.xml` files that are included in this PR and the one that will go to master have both been generated by the ACRN Board Inspector tool of the matching version, haven't they?

**Comment by NanlinXie** [comment]
> I have not double-checked this so let me ask: the `adl-asrock.xml` files that are included in this PR and the one that will go to master have both been generated by the ACRN Board Inspector tool of the matching version, haven't they?

The adl-asrock.xml and shared.xml files included in this PR (for release 3.0) have passed QA's feature test. The XML files for master only passed CI build tests in premerge stage and we will verify once we received the ASRock board in lab.

**Review by NanlinXie — APPROVED** [review]

**Comment by gvancuts** [comment]
> > I have not double-checked this so let me ask: the `adl-asrock.xml` files that are included in this PR and the one that will go to master have both been generated by the ACRN Board Inspector tool of the matching version, haven't they?
> 
> The adl-asrock.xml and shared.xml files included in this PR (for release 3.0) have passed QA's feature test. The XML files for master only passed CI build tests in premerge stage and we will verify once we received the ASRock board in lab.

Were both these XML files generated by our tools?

**Comment by NanlinXie** [comment]
> > > I have not double-checked this so let me ask: the `adl-asrock.xml` files that are included in this PR and the one that will go to master have both been generated by the ACRN Board Inspector tool of the matching version, haven't they?
> > 
> > 
> > The adl-asrock.xml and shared.xml files included in this PR (for release 3.0) have passed QA's feature test. The XML files for master only passed CI build tests in premerge stage and we will verify once we received the ASRock board in lab.
> 
> Were both these XML files generated by our tools?

Yes.

**Pull request merged**
