### PR TITLE
script: fix launch_uos script issue due to unseen character

### PR DESCRIPTION
**Pull request by totoroow**
Space is tampered with unseen characters.

Tracked-On: #1995
Reviewed-by: Binbin Wu <binbin.wu@intel.com>
Signed-off-by: Tw <wei.tan@intel.com>

### CODE REVIEW

**Comment by HuiHuangShi** [comment]
2206 <br>The PR does not touch any hypervisor source file. Skip coding guideline checks.<br>

**Comment by totoroow** [comment]
Hi @dongyaozu 

It's script used to launch UOS on UP2, I think our current CI doesn't cover this.

**Comment by wenlingz** [comment]
OK to verify

**Comment by wenlingz** [comment]
OK  to verify

**Comment by wenlingz** [comment]
OK to verify

**Comment by HuiHuangShi** [comment]
2206 <br>The PR does not touch any hypervisor source file. Skip coding guideline checks.<br>

**Comment by HuiHuangShi** [comment]
2206 <br>The PR does not touch any hypervisor source file. Skip coding guideline checks.<br>

**Comment by HuiHuangShi** [comment]
2206 <br>The PR does not touch any hypervisor source file. Skip coding guideline checks.<br>

**Comment by HuiHuangShi** [comment]
2206 <br>The PR does not touch any hypervisor source file. Skip coding guideline checks.<br>

**Pull request merged**
