### PR TITLE
hv: Build mptable for guest if VM type is Pre-Launched

### PR DESCRIPTION
**Pull request by sainath14**
ACRN builds mptable for pre-launched VMs. It uses CONFIG_PARTITION_MODE
to compile mptable source code and related support. This patch removes
the macro and checks if the type of VM is pre-launched to build mptable.

Tracked-On: #2941
Signed-off-by: Sainath Grandhi <sainath.grandhi@intel.com>
Acked-by: Eddie Dong <eddie.dong@intel.com>

### CODE REVIEW

**Comment by HuiHuangShi** [comment]
out of time

**Comment by HuiHuangShi** [comment]
21 new potential violations to the coding guideline detected. Please help check. Thanks!
<1> config:common filename:/hypervisor/dm/vmptable.c func: offset:26
reason:Value is not of appropriate type. : (enum acrn_vm_type and unsigned char): .bus_entry_array = { {.type = 1U ,.bus_id = 0U ,.bus_type = "PCI " , } , {.type = 1U
<2> config:common filename:/hypervisor/dm/vmptable.c func: offset:26
reason:Value is not of appropriate type. : (enum acrn_vm_type and unsigned char): .bus_entry_array = { {.type = 1U
<3> config:common filename:/hypervisor/dm/vmptable.c func: offset:38
reason:Value is not of appropriate type. : (enum acrn_vm_type and unsigned char): .int_entry_array = { {.type = 4U
<4> config:common filename:/hypervisor/dm/vmptable.c func: offset:38
reason:Value is not of appropriate type. : (enum acrn_vm_type and unsigned char): .int_entry_array = { {.type = 4U ,.int_type = 3U ,.int_flags = 0x0U | 0x0U ,.dst_apic_id = 0xFFU ,.dst_apic_int = 0U , } , {.type = 4U
<5> config:sharing_config filename:/hypervisor/dm/vmptable.c func:mpt_compute_checksum offset:69
reason:Procedure contains UR data flow anomalies. : sum
<6> config:sharing_config filename:/hypervisor/dm/vmptable.c func:mpt_compute_checksum offset:73
reason:Pointer not checked for null before use. : bytes
<7> config:sharing_config filename:/hypervisor/dm/vmptable.c func:mptable_build offset:85
reason:Pointer param should be declared pointer to const. : vm
<8> config:sharing_config filename:/hypervisor/dm/vmptable.c func:mptable_build offset:99
reason:Pointer not checked for null before use. : vm_config
<9> config:sharing_config filename:/hypervisor/dm/vmptable.c func:mptable_build offset:105
reason:Pointer not checked for null before use. : mptable
<10> config:part_config filename:/hypervisor/dm/vmptable.c func:mptable_build offset:105
reason:Pointer not checked for null before use. : mptable
<11> config:sharing_config filename:/hypervisor/dm/vmptable.c func:mptable_build offset:135
reason:Potential side effect problem in expression. : startaddr
<12> config:sharing_config filename:/hypervisor/dm/vmptable.c func:mptable_build offset:135
reason:Pointer not checked for null before use. : mpfp
<13> config:sharing_config filename:/hypervisor/dm/vmptable.c func:mptable_build offset:139
reason:Function return value potentially unused. : startaddr.checksum
<14> config:sharing_config filename:/hypervisor/dm/vmptable.c func:mptable_build offset:139
reason:Potential side effect problem in expression. : startaddr
<15> config:sharing_config filename:/hypervisor/dm/vmptable.c func:mptable_build offset:139
reason:Pointer not checked for null before use. : startaddr
<16> config:sharing_config filename:/hypervisor/dm/vmptable.c func:mptable_build offset:139
reason:Pointer not checked for null before use. : mpch
<17> config:sharing_config filename:/hypervisor/include/arch/x86/guest/vm.h func: offset:216
reason:No real declaration for external variable. : vm_sw_loader
<18> config:part_config filename:/hypervisor/include/arch/x86/guest/vm.h func: offset:216
reason:No real declaration for external variable. : vm_sw_loader
<19> config:sharing_config filename:/hypervisor/include/arch/x86/gdt.h func: offset:130
reason:Variable should be declared static. : __attribute__ ( ( aligned ( 16 ) ) )
<20> config:sharing_config filename:/hypervisor/include/arch/x86/page.h func: offset:76
reason:No real declaration for external variable. : ppt_mem_ops
<21> config:part_config filename:/hypervisor/include/arch/x86/cat.h func: offset:21
reason:No real declaration for external variable. : cat_cap_info

Name Conflict Violation:
LAPIC_VERSION macro 36 include/dm/mptable.h
LAPIC_VERSION enumerator 85 include/arch/x86/apicreg.h


No New Function Declaration/Definition Mismatch

**Comment by shiqingg** [comment]
Name Conflict Violation:
LAPIC_VERSION macro 36 include/dm/mptable.h
LAPIC_VERSION enumerator 85 include/arch/x86/apicreg.h

Hi Sainath,
Could you please help rename either the MACRO or Enumerator to fix the name conflict?
Thanks!

**Comment by HuiHuangShi** [comment]
out of time

**Comment by HuiHuangShi** [comment]
21 new potential violations to the coding guideline detected. Please help check. Thanks!
<1> conf ig:common filename:/hypervisor/dm/vmptable.c func: offset:26
reason:Value is not of appropriate type. : (enum acrn_vm_type and unsigned char): .bus_entry_array = { {.type = 1U ,.bus_id = 0U ,.bus_typ e = "PCI " , } , {.type = 1U
<2> config:common filename:/hypervisor/dm/vmptable.c func: offset:26
reason:Value is not of appropriate type. : (enum acrn_vm_type and unsigned char): .bus_entry_a rray = { {.type = 1U
<3> config:common filename:/hypervisor/dm/vmptable.c func: offset:38
reason:Value is not of appropriate type. : (enum acrn_vm_type and unsigned char): .int_entry_array = { { .type = 4U
<4> config:common filename:/hypervisor/dm/vmptable.c func: offset:38
reason:Value is not of appropriate type. : (enum acrn_vm_type and unsigned char): .int_entry_array = { {.type = 4U ,.int_type = 3U ,.int_flags = 0x0U | 0x0U ,.dst_apic_id = 0xFFU ,.dst_apic_int = 0U , } , {.type = 4U
<5> config:sharing_config filename:/hypervisor/dm/vmptable.c func:mpt_compute_checksum offset:69 
reason:Procedure contains UR data flow anomalies. : sum
<6> config:sharing_config filename:/hypervisor/dm/vmptable.c func:mpt_compute_checksum offset:73
reason:Pointer not checked for null bef ore use. : bytes
<7> config:sharing_config filename:/hypervisor/dm/vmptable.c func:mptable_build offset:85
reason:Pointer param should be declared pointer to const. : vm
<8> config:sharing_confi g filename:/hypervisor/dm/vmptable.c func:mptable_build offset:99
reason:Pointer not checked for null before use. : vm_config
<9> config:sharing_config filename:/hypervisor/dm/vmptable.c func:mptab le_build offset:105
reason:Pointer not checked for null before use. : mptable
<10> config:part_config filename:/hypervisor/dm/vmptable.c func:mptable_build offset:105
reason:Pointer not checked for null before use. : mptable
<11> config:sharing_config filename:/hypervisor/dm/vmptable.c func:mptable_build offset:135
reason:Potential side effect problem in expression. : startaddr
<12> c onfig:sharing_config filename:/hypervisor/dm/vmptable.c func:mptable_build offset:135
reason:Pointer not checked for null before use. : mpfp
<13> config:sharing_config filename:/hypervisor/dm/vmpta ble.c func:mptable_build offset:139
reason:Function return value potentially unused. : startaddr.checksum
<14> config:sharing_config filename:/hypervisor/dm/vmptable.c func:mptable_build offset:139 
reason:Potential side effect problem in expression. : startaddr
<15> config:sharing_config filename:/hypervisor/dm/vmptable.c func:mptable_build offset:139
reason:Pointer not checked for null before use. : startaddr
<16> config:sharing_config filename:/hypervisor/dm/vmptable.c func:mptable_build offset:139
reason:Pointer not checked for null before use. : mpch
<17> config:sharing_con fig filename:/hypervisor/include/arch/x86/guest/vm.h func: offset:216
reason:No real declaration for external variable. : vm_sw_loader
<18> config:part_config filename:/hypervisor/include/arch/x86/ guest/vm.h func: offset:216
reason:No real declaration for external variable. : vm_sw_loader
<19> config:sharing_config filename:/hypervisor/include/arch/x86/gdt.h func: offset:130
reason:Varia ble should be declared static. : __attribute__ ( ( aligned ( 16 ) ) )
<20> config:sharing_config filename:/hypervisor/include/arch/x86/page.h func: offset:76
reason:No real declaration for external variable. : ppt_mem_ops
<21> config:part_config filename:/hypervisor/include/arch/x86/cat.h func: offset:21
reason:No real declaration for external variable. : cat_cap_info

No New Name Conf lict

No New Function Declaration/Definition Mismatch

**Pull request merged**
