### PR TITLE
acrn-config: update IOMEM_INFO of tgl-rvp board

### PR DESCRIPTION
**Pull request by liuwei987**
As we did in commit: 697f3fc09f0e2677fa4aa592c8a44da54a8e6ab8, need
    to update IOMEM_INFO for tgl-rvp.

    Tracked-On: #4582
    Signed-off-by: Wei Liu <weix.w.liu@intel.com>
    Acked-by: Victor Sun <victor.sun@intel.com>

### CODE REVIEW

**Comment by HuiHuangShi** [comment]
No new violations to the coding guideline detected.<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by HuiHuangShi** [comment]
No new violations to the coding guideline detected.<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by HuiHuangShi** [comment]
No new violations to the coding guideline detected.<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by leilu** [comment]
OK to verify

**Pull request merged**
