### PR TITLE
hv: fix mapping between GSI Num#2 and PIC IRQ #0

### PR DESCRIPTION
**Pull request by yonghuah**
route GSI number#2 to PIC IRQ#0, as by default IRQ for
 8254 timer is connected to I/O APIC Pin #2 and PIC Pin #0

Tracked-On #861
Signed-off-by: Yonghua Huang <yonghua.huang@intel.com>
Reviewed-by: Eddie Dong <eddie.dong@intel.com>
Acked-by: Anthony Xu <anthony.xu@intel.com>

### CODE REVIEW

**Comment by HuiHuangShi** [comment]
1593<br>4 new potential violations to the coding guideline detected. Please help check. Thanks!  <br><br>1.filename:/hypervisor/common/hypercall.c&nbsp;&nbsp;function:hcall_set_irqline&nbsp;&nbsp;offset:356:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Signed/unsigned conversion without cast. :  (unsigned int and int): irq_pic = ( ops -> nr_gsi<br><br>2.filename:/hypervisor/common/hypercall.c&nbsp;&nbsp;function:hcall_set_irqline&nbsp;&nbsp;offset:356:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Type mismatch in ternary expression. :  (unsigned int and signed char)<br><br>3.filename:/hypervisor/common/hypercall.c&nbsp;&nbsp;function:hcall_set_irqline&nbsp;&nbsp;offset:356:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Use of mixed mode arithmetic. :  (unsigned int and signed char): irq_pic = ( ops -> nr_gsi == 2<br><br>4.filename:/hypervisor/common/hypercall.c&nbsp;&nbsp;function:hcall_set_irqline&nbsp;&nbsp;offset:356:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Literal value requires a U suffix.           : 2<br><br>

**Comment by HuiHuangShi** [comment]
1593<br>No new violations to the coding guideline detected.

**Comment by HuiHuangShi** [comment]
1593<br>No new violations to the coding guideline detected.

**Comment by ClaudZhang1995** [comment]
Ready to merge

**Pull request merged**
