### PR TITLE
doc: update security advisory for v2.1 release

### PR DESCRIPTION
**Pull request by yonghuah**
Add notes for fixed security vulnerabilities for v2.1 release.

Signed-off-by: Yonghua Huang <yonghua.huang@intel.com>

### CODE REVIEW

**Comment by yonghuah** [comment]
@NanlinXie  please review asa.rst update for 2.1 release.

**Comment by HuiHuangShi** [comment]
No new violations to the coding guideline detected.<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by dbkinder** [comment]
I made a slight edit to your PR directly to correct the formatting so your new item looks like the others (first line is a summary)

**Comment by HuiHuangShi** [comment]
No new violations to the coding guideline detected.<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Pull request merged**
