### PR TITLE
hv: vpci: remove PC-Card type support

### PR DESCRIPTION
**Pull request by lifeix**
We only support Type 0 and Type 1 PCI device. Remove PC-Card type support which
was originally described in the [PC-Card] and is used in previous versions of
the programming model.

Tracked-On: #3475
Signed-off-by: Li, Fei1 <fei1.li@intel.com>

### CODE REVIEW

**Comment by HuiHuangShi** [comment]
No new violations to the coding guideline detected.<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by dongyaozu** [comment]
In this case, we assume hardware PCIe devices doesn't have this capability, right？ We need to add assumption for FuSa to make sure the hardware platform follows the assumption.

**Comment by acrnsi** [comment]
OK to verify

**Comment by lifeix** [comment]
> In this case, we assume hardware PCIe devices doesn't have this capability, right？ We need to add assumption for FuSa to make sure the hardware platform follows the assumption.

Yes. FuSa also fellows this assumption.

**Comment by dongyaozu** [comment]
How do we add this assumption? Should we make a copy of the assumption somewhere in the source code too? Please check with Xiangyang

**Comment by wuxyintel** [comment]
@lifeix Please add application constraint about this by following our coding guidelines (https://projectacrn.github.io/latest/developer-guides/c_coding_guidelines.html#c-cs-18-function-information-shall-be-documented-with-doxygen-style-comments). Thanks!

**Comment by HuiHuangShi** [comment]
No new violations to the coding guideline detected.<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by HuiHuangShi** [comment]
No new violations to the coding guideline detected.<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Pull request merged**
