### PR TITLE
Unmap Software SRAM region of PreRTVM from Service VM

### PR DESCRIPTION
**Pull request by yonghuah**
1st patch to refine config tool to update some MACROs for PreRTVM software SRAM settings.
2cnd patch to un-map sw sram region that assigned to preRTVM from EPT of Service VM.

### CODE REVIEW

**Comment by HuiHuangShi** [comment]
No new violations to the coding guideline detected.<br>No New Name Conflict<br>No New Function Declaration/Definition Mismatch

**Comment by wenlingz** [comment]
@yonghuah  this PR is also need to be created in release_2.4 ?

**Review by dongyaozu — APPROVED** [review]
I am fine with HV side changes.

**Comment by yonghuah** [comment]
@wenlingz , yes, i will push one more PR to port it to 2.4 branch after this. thanks.

**Pull request merged**
