### PR TITLE
Clean up vcpu

### PR DESCRIPTION
**Pull request by huix-shh**
vcpu is never scan because of scan tool will be crashed!
After modulization, the vcpu can be scaned by the scan tool.
Clean up the violations in vcpu.c.
Fix the violations:

Huihuang Shi (2):
  HV:fix vcpu violations
  V1->V2:
    change the type of "vcpu->arch.irq_window_enabled" to bool.
  HV:fix vcpu more than one return entry
  V1->V2:
    change the code path to:
    if (condition) {
        normal path
    } else {
        abnormal path
    }
Tracked-On: #861
Signed-off-by: Huihuang Shi <huihuang.shi@intel.com>
Acked-by: Eddie Dong <eddie.dong@intel.com>

### CODE REVIEW

**Comment by acrnsi** [comment]
Can one of the admins verify this patch?

**Comment by HuiHuangShi** [comment]
2 new potential violations to the coding guideline detected. Please help check. Thanks!<br><1> config:common filename:/hypervisor/arch/x86/guest/vcpu.c func:create_vcpu offset:413<br> reason:Literal value requires a U suffix.           : 1<br><2> config:common filename:/hypervisor/arch/x86/guest/vcpu.c func:reset_vcpu offset:566<br> reason:Type conversion without cast. :  (enum vm_state and enum vcpu_state): vcpu -> state != VCPU_INIT<br><br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by HuiHuangShi** [comment]
1 new potential violations to the coding guideline detected. Please help check. Thanks!<br><1> config:common filename:/hypervisor/arch/x86/guest/vcpu.c func:reset_vcpu offset:566<br> reason:Type conversion without cast. :  (enum vm_state and enum vcpu_state): vcpu -> state != VCPU_INIT<br><br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by acrnsi** [comment]
OK to verify

**Comment by HuiHuangShi** [comment]
1 new potential violations to the coding guideline detected. Please help check. Thanks!<br><1> config:common filename:/hypervisor/arch/x86/guest/vcpu.c func:reset_vcpu offset:566<br> reason:Type conversion without cast. :  (enum vm_state and enum vcpu_state): vcpu -> state != VCPU_INIT<br><br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Pull request merged**
