### PR TITLE
Makefile: fix a couple of wrong variable assignments

### PR DESCRIPTION
**Pull request by gvancuts**
Fix a couple of wrong assignments to D_SRCS and C_SRCS.

Signed-off-by: Geoffroy Van Cutsem <geoffroy.vancutsem@intel.com>

### CODE REVIEW

**Comment by lijinxia** [comment]
verified +1

**Comment by lifeix** [comment]
@gvancuts @anthonyzxu

**Comment by ttzeng** [comment]
Echo @lifeix , this PR is causing the build abort due to the missing of `printf/snprintf` required by several files.
```
$ make RELEASE=1 PLATFORM=uefi
...
/opt/mnt/acrn-hypervisor/build/arch/x86/cpu.o: In function `print_hv_banner':
/opt/mnt/acrn-hypervisor/arch/x86/cpu.c:556: undefined reference to `printf'
/opt/mnt/acrn-hypervisor/build/arch/x86/notify.o: In function `setup_notification':
/opt/mnt/acrn-hypervisor/arch/x86/notify.c:82: undefined reference to `snprintf'
/opt/mnt/acrn-hypervisor/build/arch/x86/timer.o: In function `timer_init':
/opt/mnt/acrn-hypervisor/arch/x86/timer.c:311: undefined reference to `snprintf'
/opt/mnt/acrn-hypervisor/build/arch/x86/guest/vm.o: In function `create_vm':
/opt/mnt/acrn-hypervisor/arch/x86/guest/vm.c:119: undefined reference to `snprintf'
/opt/mnt/acrn-hypervisor/build/arch/x86/guest/vlapic.o: In function `dump_isrvec_stk':
/opt/mnt/acrn-hypervisor/arch/x86/guest/vlapic.c:643: undefined reference to `printf'
/opt/mnt/acrn-hypervisor/arch/x86/guest/vlapic.c:646: undefined reference to `printf'
/opt/mnt/acrn-hypervisor/build/common/vm_load.o: In function `general_sw_loader':
/opt/mnt/acrn-hypervisor/common/vm_load.c:217: undefined reference to `snprintf'
/opt/mnt/acrn-hypervisor/build/bsp/uefi/cmdline.o: In function `handle_cmd':
/opt/mnt/acrn-hypervisor/bsp/uefi/cmdline.c:77: undefined reference to `uart16550_set_property'
/opt/mnt/acrn-hypervisor/bsp/uefi/cmdline.c:87: undefined reference to `uart16550_set_property'
/opt/mnt/acrn-hypervisor/bsp/uefi/cmdline.c:89: undefined reference to `uart16550_set_property'
collect2: error: ld returned 1 exit status
Makefile:202: recipe for target '/opt/mnt/acrn-hypervisor/build/acrn.out' failed
make: *** [/opt/mnt/acrn-hypervisor/build/acrn.out] Error 1
```

**Comment by gvancuts** [comment]
This PR got merged in the meantime, I'll send a new one to correct this (restoring printf.c as C_SRCS). I am assuming that we also want acpi.c as C_SRCS so unless you tell me otherwise, I will keep that change that got merged, is that correct?

**Comment by gvancuts** [comment]
If I have:
```
C_SRCS += debug/printf.c
C_SRCS += boot/acpi.c
```
It still fails to build a released version (see below [1])

If I now make this additional change in the Makefile:
```
C_SRCS += debug/uart16550.c
```
I can build a release... the question is: which combination is correct?
Either:
```
C_SRCS += debug/uart16550.c
C_SRCS += boot/acpi.c
```
Or
```
D_SRCS += debug/uart16550.c
D_SRCS += boot/acpi.c
```
I have not tested the binaries created but does it really work in EFI mode if the acpi.c file is not built (which would be what happens now)?

Let me know so I can adjust my patch accordingly. 

[1] make PLATFORM=uefi RELEASE=1
```
[ ! -e /home/gvancuts/work/acrn-hypervisor/build/bsp/uefi/cmdline.o ] && mkdir -p /home/gvancuts/work/acrn-hypervisor/build/bsp/uefi/; \
gcc  -Iinclude  -Iinclude/lib  -Iinclude/common  -Iinclude/arch/x86  -Iinclude/arch/x86/guest  -Iinclude/debug  -Iinclude/public  -Iinclude/common  -Ibsp/include  -Ibsp/uefi/include/bsp  -Iboot/include -I. -c -Wall -W -ffunction-sections -fdata-sections -fshort-wchar -ffreestanding -m64 -mno-red-zone -static -nostdinc -nostdlib -fno-common -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -fstack-protector-strong -DSTACK_PROTECTOR -mindirect-branch=thunk-extern -mindirect-branch-register -DCONFIG_RETPOLINE -gdwarf-2 -O0 bsp/uefi/cmdline.c -o /home/gvancuts/work/acrn-hypervisor/build/bsp/uefi/cmdline.o
[ ! -e /home/gvancuts/work/acrn-hypervisor/build/arch/x86/cpu_secondary.o ] && mkdir -p /home/gvancuts/work/acrn-hypervisor/build/arch/x86/; \
gcc  -Iinclude  -Iinclude/lib  -Iinclude/common  -Iinclude/arch/x86  -Iinclude/arch/x86/guest  -Iinclude/debug  -Iinclude/public  -Iinclude/common  -Ibsp/include  -Ibsp/uefi/include/bsp  -Iboot/include -I. -m64 -nostdinc -nostdlib -gdwarf-2 -DASSEMBLER=1 -c arch/x86/cpu_secondary.S -o /home/gvancuts/work/acrn-hypervisor/build/arch/x86/cpu_secondary.o
[ ! -e /home/gvancuts/work/acrn-hypervisor/build/arch/x86/cpu_primary.o ] && mkdir -p /home/gvancuts/work/acrn-hypervisor/build/arch/x86/; \
gcc  -Iinclude  -Iinclude/lib  -Iinclude/common  -Iinclude/arch/x86  -Iinclude/arch/x86/guest  -Iinclude/debug  -Iinclude/public  -Iinclude/common  -Ibsp/include  -Ibsp/uefi/include/bsp  -Iboot/include -I. -m64 -nostdinc -nostdlib -gdwarf-2 -DASSEMBLER=1 -c arch/x86/cpu_primary.S -o /home/gvancuts/work/acrn-hypervisor/build/arch/x86/cpu_primary.o
[ ! -e /home/gvancuts/work/acrn-hypervisor/build/arch/x86/idt.o ] && mkdir -p /home/gvancuts/work/acrn-hypervisor/build/arch/x86/; \
gcc  -Iinclude  -Iinclude/lib  -Iinclude/common  -Iinclude/arch/x86  -Iinclude/arch/x86/guest  -Iinclude/debug  -Iinclude/public  -Iinclude/common  -Ibsp/include  -Ibsp/uefi/include/bsp  -Iboot/include -I. -m64 -nostdinc -nostdlib -gdwarf-2 -DASSEMBLER=1 -c arch/x86/idt.S -o /home/gvancuts/work/acrn-hypervisor/build/arch/x86/idt.o
[ ! -e /home/gvancuts/work/acrn-hypervisor/build/arch/x86/vmx_asm.o ] && mkdir -p /home/gvancuts/work/acrn-hypervisor/build/arch/x86/; \
gcc  -Iinclude  -Iinclude/lib  -Iinclude/common  -Iinclude/arch/x86  -Iinclude/arch/x86/guest  -Iinclude/debug  -Iinclude/public  -Iinclude/common  -Ibsp/include  -Ibsp/uefi/include/bsp  -Iboot/include -I. -m64 -nostdinc -nostdlib -gdwarf-2 -DASSEMBLER=1 -c arch/x86/vmx_asm.S -o /home/gvancuts/work/acrn-hypervisor/build/arch/x86/vmx_asm.o
[ ! -e /home/gvancuts/work/acrn-hypervisor/build/arch/x86/retpoline-thunk.o ] && mkdir -p /home/gvancuts/work/acrn-hypervisor/build/arch/x86/; \
gcc  -Iinclude  -Iinclude/lib  -Iinclude/common  -Iinclude/arch/x86  -Iinclude/arch/x86/guest  -Iinclude/debug  -Iinclude/public  -Iinclude/common  -Ibsp/include  -Ibsp/uefi/include/bsp  -Iboot/include -I. -m64 -nostdinc -nostdlib -gdwarf-2 -DASSEMBLER=1 -c arch/x86/retpoline-thunk.S -o /home/gvancuts/work/acrn-hypervisor/build/arch/x86/retpoline-thunk.o
gcc -E -x c  -Iinclude  -Iinclude/lib  -Iinclude/common  -Iinclude/arch/x86  -Iinclude/arch/x86/guest  -Iinclude/debug  -Iinclude/public  -Iinclude/common  -Ibsp/include  -Ibsp/uefi/include/bsp  -Iboot/include bsp/ld/link_ram.ld.in | grep -v '^#' > /home/gvancuts/work/acrn-hypervisor/build/link_ram.ld
gcc -Wl,-Map=/home/gvancuts/work/acrn-hypervisor/build/acrn.map -o /home/gvancuts/work/acrn-hypervisor/build/acrn.out -Wl,--gc-sections -static -nostartfiles -nostdlib -Wl,-n,-z,max-page-size=0x1000 -Wl,-z,noexecstack  -T/home/gvancuts/work/acrn-hypervisor/build/link_ram.ld /home/gvancuts/work/acrn-hypervisor/build/debug/printf.o /home/gvancuts/work/acrn-hypervisor/build/boot/acpi.o /home/gvancuts/work/acrn-hypervisor/build/boot/dmar_parse.o /home/gvancuts/work/acrn-hypervisor/build/boot/multiboot.o /home/gvancuts/work/acrn-hypervisor/build/arch/x86/ioapic.o /home/gvancuts/work/acrn-hypervisor/build/arch/x86/intr_lapic.o /home/gvancuts/work/acrn-hypervisor/build/arch/x86/cpu.o /home/gvancuts/work/acrn-hypervisor/build/arch/x86/softirq.o /home/gvancuts/work/acrn-hypervisor/build/arch/x86/cpuid.o /home/gvancuts/work/acrn-hypervisor/build/arch/x86/mmu.o /home/gvancuts/work/acrn-hypervisor/build/arch/x86/notify.o /home/gvancuts/work/acrn-hypervisor/build/arch/x86/intr_main.o /home/gvancuts/work/acrn-hypervisor/build/arch/x86/vtd.o /home/gvancuts/work/acrn-hypervisor/build/arch/x86/gdt.o /home/gvancuts/work/acrn-hypervisor/build/arch/x86/irq.o /home/gvancuts/work/acrn-hypervisor/build/arch/x86/timer.o /home/gvancuts/work/acrn-hypervisor/build/arch/x86/ept.o /home/gvancuts/work/acrn-hypervisor/build/arch/x86/io.o /home/gvancuts/work/acrn-hypervisor/build/arch/x86/interrupt.o /home/gvancuts/work/acrn-hypervisor/build/arch/x86/vmexit.o /home/gvancuts/work/acrn-hypervisor/build/arch/x86/vmx.o /home/gvancuts/work/acrn-hypervisor/build/arch/x86/assign.o /home/gvancuts/work/acrn-hypervisor/build/arch/x86/trusty.o /home/gvancuts/work/acrn-hypervisor/build/arch/x86/guest/vcpu.o /home/gvancuts/work/acrn-hypervisor/build/arch/x86/guest/vm.o /home/gvancuts/work/acrn-hypervisor/build/arch/x86/guest/instr_emul_wrapper.o /home/gvancuts/work/acrn-hypervisor/build/arch/x86/guest/vlapic.o /home/gvancuts/work/acrn-hypervisor/build/arch/x86/guest/guest.o /home/gvancuts/work/acrn-hypervisor/build/arch/x86/guest/vmcall.o /home/gvancuts/work/acrn-hypervisor/build/arch/x86/guest/vpic.o /home/gvancuts/work/acrn-hypervisor/build/arch/x86/guest/vmsr.o /home/gvancuts/work/acrn-hypervisor/build/arch/x86/guest/vioapic.o /home/gvancuts/work/acrn-hypervisor/build/arch/x86/guest/instr_emul.o /home/gvancuts/work/acrn-hypervisor/build/lib/spinlock.o /home/gvancuts/work/acrn-hypervisor/build/lib/udelay.o /home/gvancuts/work/acrn-hypervisor/build/lib/strnlen.o /home/gvancuts/work/acrn-hypervisor/build/lib/memchr.o /home/gvancuts/work/acrn-hypervisor/build/lib/stdlib.o /home/gvancuts/work/acrn-hypervisor/build/lib/memcpy.o /home/gvancuts/work/acrn-hypervisor/build/lib/strtol.o /home/gvancuts/work/acrn-hypervisor/build/lib/mdelay.o /home/gvancuts/work/acrn-hypervisor/build/lib/div.o /home/gvancuts/work/acrn-hypervisor/build/lib/strchr.o /home/gvancuts/work/acrn-hypervisor/build/lib/strcpy.o /home/gvancuts/work/acrn-hypervisor/build/lib/memset.o /home/gvancuts/work/acrn-hypervisor/build/lib/mem_mgt.o /home/gvancuts/work/acrn-hypervisor/build/lib/strncpy.o /home/gvancuts/work/acrn-hypervisor/build/lib/crypto/tinycrypt/hmac.o /home/gvancuts/work/acrn-hypervisor/build/lib/crypto/tinycrypt/sha256.o /home/gvancuts/work/acrn-hypervisor/build/lib/crypto/hkdf.o /home/gvancuts/work/acrn-hypervisor/build/common/hv_main.o /home/gvancuts/work/acrn-hypervisor/build/common/hypercall.o /home/gvancuts/work/acrn-hypervisor/build/common/schedule.o /home/gvancuts/work/acrn-hypervisor/build/common/vm_load.o /home/gvancuts/work/acrn-hypervisor/build/common/stack_protector.o /home/gvancuts/work/acrn-hypervisor/build/bsp/uefi/vm_description.o /home/gvancuts/work/acrn-hypervisor/build/bsp/uefi/uefi.o /home/gvancuts/work/acrn-hypervisor/build/bsp/uefi/cmdline.o /home/gvancuts/work/acrn-hypervisor/build/arch/x86/cpu_secondary.o /home/gvancuts/work/acrn-hypervisor/build/arch/x86/cpu_primary.o /home/gvancuts/work/acrn-hypervisor/build/arch/x86/idt.o /home/gvancuts/work/acrn-hypervisor/build/arch/x86/vmx_asm.o /home/gvancuts/work/acrn-hypervisor/build/arch/x86/retpoline-thunk.o
/home/gvancuts/work/acrn-hypervisor/build/bsp/uefi/cmdline.o: In function `handle_cmd':
/home/gvancuts/work/acrn-hypervisor/bsp/uefi/cmdline.c:77: undefined reference to `uart16550_set_property'
/home/gvancuts/work/acrn-hypervisor/bsp/uefi/cmdline.c:87: undefined reference to `uart16550_set_property'
/home/gvancuts/work/acrn-hypervisor/bsp/uefi/cmdline.c:89: undefined reference to `uart16550_set_property'
collect2: error: ld returned 1 exit status
make: *** [Makefile:204: /home/gvancuts/work/acrn-hypervisor/build/acrn.out] Error 1
```

**Comment by ttzeng** [comment]
@gvancuts looks like we also need to deal with `bsp/uefi/cmdline.c`, the cmdline function is required by `init_bsp()`, unless we define an empty macro for it?

**Comment by gvancuts** [comment]
I'm not following you @ttzeng? `bsp/uefi/cmdline.c` is used for both `RELEASE=0` and `RELEASE=1` when `PLATFORM=uefi` is used - see https://github.com/gvancuts/acrn-hypervisor/blob/160b8b773b471b4572816162f6df0e2f84d94fae/Makefile#L153-L155

**Comment by gvancuts** [comment]
Thanks for the clarification @ttzeng . It looks to me like the right solution is to use this combination:
```
C_SRCS += debug/uart16550.c
C_SRCS += boot/acpi.c
```
I'll prepare a new PR with these changes and ask for a review.

**Comment by anthonyzxu** [comment]
@gvancuts your fix is correct, but we need to fix the building error.

diff --git a/include/debug/printf.h b/include/debug/printf.h
index 2bd9894..f19fee3 100644
--- a/include/debug/printf.h
+++ b/include/debug/printf.h
@@ -31,6 +31,7 @@
 #ifndef PRINTF_H
 #define PRINTF_H

+#ifdef HV_DEBUG
 /** The well known printf() function.
  *
  *  Formats a string and writes it to the console output.
@@ -85,4 +86,27 @@ int vsnprintf(char *dst, int sz, const char *fmt, va_list args);

 int snprintf(char *dest, int sz, const char *fmt, ...);

+#else
+
+static int printf(const char *fmt, ...)
+{
+       return 0;
+}
+
+static int vprintf(const char *fmt, va_list args)
+{
+       return 0;
+}
+
+static int vsnprintf(char *dst, int sz, const char *fmt, va_list args)
+{
+       return 0;
+}
+
+static int snprintf(char *dest, int sz, const char *fmt, ...)
+{
+       return 0;
+}
+
+#endif /* HV_DEBUG */
 #endif /* PRINTF_H */

**Comment by ttzeng** [comment]
@anthonyzxu I think you are referring `#ifndef HV_DEBUG`?

**Comment by anthonyzxu** [comment]
@ttzeng
No,  it is "#ifndef HV_DEBUG"

**Comment by ttzeng** [comment]
Ah you are right @anthonyzxu it should `#ifdef HV_DEBUG` to get the actual `printf()` get compiled. Sorry for the confusion.

**Comment by ttzeng** [comment]
@anthonyzxu one question related to the debug build want to consult with you: in theory, does the `cmdline.c` need to be included for a release build?

**Comment by anthonyzxu** [comment]
@ttzeng Yes, I think so.  right now mi_cmdline is only for serial port, we might add other cmdline parameters later, and pass through acrn.efi parameter.

**Comment by lifeix** [comment]
@gvancuts @anthonyzxu We need printf family for release not empty macro. Please do not try to change it.   We may move the .c/.h file to lib/ later. And we should include any others in the debug/ for release.

**Comment by anthonyzxu** [comment]
@lifeix we should move int vsnprintf(char *dst, int sz, const char *fmt, va_list args) and int snprintf(char *dest, int sz, const char *fmt, ...) to lib/ , they are not for debug. 
should not include any C files from debug/ for release.

**Comment by lifeix** [comment]
@anthonyzxu Yes. But I think we could put the whole printf family as a whole.

**Comment by anthonyzxu** [comment]
@lifeix keeping printf, vprintf and charout in debug/ to reduce the code size for release.

**Pull request merged**
