### PR TITLE
update launch_uos.sh to align with Latest release

### PR DESCRIPTION
**Pull request by ailun258**
update the kernel version to align with ACRN v0.1 and latest release

Signed-off-by: ailun258 <ailin.yang@intel.com>

### CODE REVIEW

**Comment by NanlinXie** [comment]
Can one of the admins verify this patch?

**Comment by ailun258** [comment]
@minhe1  close old one, and submit new one with one patch

**Comment by ailun258** [comment]
@dongyaozu  i forgot the my password of the github account,  so i modified the file and submitted the patch here in gitbub directly, i wanted to modify the patch, but after submitted , it really shows 2 commit with one PR,

**Comment by ailun258** [comment]
@anthonyzxu  please get approved this patch

**Comment by dongyaozu** [comment]
You need to merge the 2 commit into 1 for merge

**Pull request closed without merging**
