### PR TITLE
doc: update supported hardware document

### PR DESCRIPTION
**Pull request by dbkinder**
Fixes: #5741

Signed-off-by: David B. Kinder <david.b.kinder@intel.com>

### CODE REVIEW

**Comment by dbkinder** [comment]
@nanlin I've submitted this PR to update the supported hardware document with the information you sent me.  I do note that some of the boards on your list don't have a corresponding XML file so are they truly supported?   Also I see PR #6176 is removing some board XML files that I'm referencing in this update.  Should we just delete those rows, or just indicate ``N/A`` for those boards?

**Comment by fuzhongl** [comment]
> @nanlin I've submitted this PR to update the supported hardware document with the information you sent me. I do note that some of the boards on your list don't have a corresponding XML file so are they truly supported? Also I see PR #6176 is removing some board XML files that I'm referencing in this update. Should we just delete those rows, or just indicate `N/A` for those boards?

Echo to @dbkinder 👍 
Prefer to remove all info about the boards which don't have a corresponding XML file.

**Comment by NanlinXie** [comment]
> @nanlin I've submitted this PR to update the supported hardware document with the information you sent me. I do note that some of the boards on your list don't have a corresponding XML file so are they truly supported? Also I see PR #6176 is removing some board XML files that I'm referencing in this update. Should we just delete those rows, or just indicate `N/A` for those boards?

For the board that we don't have predefined XML file , we could add note to let them try configtool to generate the board.xml on their own board.

**Comment by gvancuts** [comment]
The boards that do not have a corresponding XML are variations of other boards. I'm starting to think we should do the following:
* Specify which board/system is supported and has a pre-defined XML file in the repo
* Add a note that similar systems (e.g. running i5 instead of i7) should be easy to bring up provided an adequate `$(BOARD).xml` is generated and used
* There is also actually a board that's not listed but *does* have a XML set of files: `apl-up2`

**Comment by dbkinder** [comment]
I'm going to merge this now.  We can submit further edits as needed.

**Pull request merged**
