### PR TITLE
remove support of UEFI boot

### PR DESCRIPTION
**Pull request by ZideChen0**
We no longer support UEFI boot, thus we can remove the de-privilege boot
mode from ACRN:

From the user's perspective:

- "FIRMWARE=sbl/uefi" is removed from Makefiles and it defaults to direct boot
  mode, which supports SBL/ABL, or GRUB boot.
- no more acrn.efi can be built.
- the firmware name is removed from the installed ACRN image, for example:
  acrn.apl-up2.sbl.sdc.32.out will be changed to acrn.apl-up2.sdc.32.out

### CODE REVIEW

**Comment by HuiHuangShi** [comment]
No new violations to the coding guideline detected.<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Review by dongyaozu — APPROVED** [review]

**Comment by HuiHuangShi** [comment]
No new violations to the coding guideline detected.<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by wenlingz** [comment]
It needs meta-acrn help to modify the file to build in Yocto, has sent the JIRA to meta-acrn team

**Comment by ZideChen0** [comment]
I have added [External_System_ID] to issue #5197, hopefully the Tracked-On failure issue can be fixed.

**Review by terryzouhao — APPROVED** [review]

**Comment by HuiHuangShi** [comment]
No new violations to the coding guideline detected.<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by HuiHuangShi** [comment]
No new violations to the coding guideline detected.<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Pull request merged**
