### PR TITLE
acrn-config: add cfl-k700-i7 industry xmls

### PR DESCRIPTION
**Pull request by jsun26intel**
Add cfl-k700-i7 board xml and its industry xml to support ACRN industry
scenario on cfl-k700-i7 board.

Tracked-On: #5212

Signed-off-by: Victor Sun <victor.sun@intel.com>

### CODE REVIEW

**Comment by jsun26intel** [comment]
@wenlingz  please hold on this PR, I need to rebase when 5202 get merged.

**Comment by HuiHuangShi** [comment]
No new violations to the coding guideline detected.<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by HuiHuangShi** [comment]
No new violations to the coding guideline detected.<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by jsun26intel** [comment]
OK to verify

**Comment by wenlingz** [comment]
@terryzouhao please help approve this PR, thanks

**Review by terryzouhao — APPROVED** [review]
CFL config file.

**Pull request merged**
