### PR TITLE
Support CAT Features

### PR DESCRIPTION
**Pull request by taoyuhong**
User can use CAT to optimise VM performance. 

vm config examples:

1. set CAT_ENABLE to acrn_vm_config.guest_flags, and set the acrn_vm_config.clos
struct acrn_vm_config vm_configs[CONFIG_MAX_VM_NUM] = {
    {
        .guest_flags |= CLOS_REQUIRED,
        .clos = 1,
    },
};

Tracked-On: #2462
Signed-off-by: Tao Yuhong <yuhong.tao@intel.com>
Acked-by: Eddie Dong <eddie.dong@intel.com>

### CODE REVIEW

**Comment by wenlingz** [comment]
@taoyuhong please modify your patch, current has "board =  kbl-nuc-i7",thanks

**Comment by taoyuhong** [comment]
Have successfully run "make hypervisor BOARD=kbl-nuc-i7" on my local PC

**Comment by HuiHuangShi** [comment]
11 new potential violations to the coding guideline detected. Please help check. Thanks!<br><1> config:common filename:/hypervisor/include/arch/x86/cpu.h func:asm_pause offset:307<br> reason:Static procedure is not explicitly called in code analysed. : asm_pause<br><2> config:common filename:/hypervisor/include/arch/x86/cpu.h func:asm_hlt offset:312<br> reason:Static procedure is not explicitly called in code analysed. : asm_hlt<br><3> config:common filename:/hypervisor/include/arch/x86/cpu.h func:get_cpu_id offset:414<br> reason:Static procedure is not explicitly called in code analysed. : get_cpu_id<br><4> config:common filename:/hypervisor/include/arch/x86/cpu.h func:msr_read offset:438<br> reason:Static procedure is not explicitly called in code analysed. : msr_read<br><5> config:common filename:/hypervisor/include/arch/x86/cpu.h func:msr_write offset:443<br> reason:Static procedure is not explicitly called in code analysed. : msr_write<br><6> config:common filename:/hypervisor/include/arch/x86/cpu.h func:stac offset:464<br> reason:Static procedure is not explicitly called in code analysed. : stac<br><7> config:common filename:/hypervisor/include/arch/x86/cpu.h func:clac offset:469<br> reason:Static procedure is not explicitly called in code analysed. : clac<br><8> config:common filename:/hypervisor/include/arch/x86/board.h func: offset:16<br> reason:Array has no bounds specified.<br><9> config:common filename:/hypervisor/arch/x86/cat.c func:init_cat_cap_info offset:49<br> reason:Logical conjunctions need brackets.<br><10> config:common filename:/hypervisor/include/arch/x86/msr.h func: offset:599<br> reason:Struct/union not completely specified.       : acrn_vcpu<br><11> config:common filename:/hypervisor/include/arch/x86/cpuid.h func:cpuid offset:122<br> reason:Static procedure is not explicitly called in code analysed. : cpuid<br><br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by HuiHuangShi** [comment]
> 11 new potential violations to the coding guideline detected. Please help check. Thanks!
> <1> config:common filename:/hypervisor/include/arch/x86/cpu.h func:asm_pause offset:307
> reason:Static procedure is not explicitly called in code analysed. : asm_pause
> <2> config:common filename:/hypervisor/include/arch/x86/cpu.h func:asm_hlt offset:312
> reason:Static procedure is not explicitly called in code analysed. : asm_hlt
> <3> config:common filename:/hypervisor/include/arch/x86/cpu.h func:get_cpu_id offset:414
> reason:Static procedure is not explicitly called in code analysed. : get_cpu_id
> <4> config:common filename:/hypervisor/include/arch/x86/cpu.h func:msr_read offset:438
> reason:Static procedure is not explicitly called in code analysed. : msr_read
> <5> config:common filename:/hypervisor/include/arch/x86/cpu.h func:msr_write offset:443
> reason:Static procedure is not explicitly called in code analysed. : msr_write
> <6> config:common filename:/hypervisor/include/arch/x86/cpu.h func:stac offset:464
> reason:Static procedure is not explicitly called in code analysed. : stac
> <7> config:common filename:/hypervisor/include/arch/x86/cpu.h func:clac offset:469
> reason:Static procedure is not explicitly called in code analysed. : clac
> <8> config:common filename:/hypervisor/include/arch/x86/board.h func: offset:16
> reason:Array has no bounds specified.
> <9> config:common filename:/hypervisor/arch/x86/cat.c func:init_cat_cap_info offset:49
> reason:Logical conjunctions need brackets.
> <10> config:common filename:/hypervisor/include/arch/x86/msr.h func: offset:599
> reason:Struct/union not completely specified. : acrn_vcpu
> <11> config:common filename:/hypervisor/include/arch/x86/cpuid.h func:cpuid offset:122
> reason:Static procedure is not explicitly called in code analysed. : cpuid
> 
> No New Name Conflict
> 
> No New Function Declaration/Definition Mismatch

All of above is false positive except 9 should be fixed.

**Pull request merged**
