### PR TITLE
DM: add disk logger and improve log system 

### PR DESCRIPTION
**Pull request by mcao6**
add logger to save log into file system, also improve some parts of log system.

patch as followings:
  DM: add static for local variables
  DM: add disk-logger to write log into file system
  DM: add disk-logger configure in launch script
  DM: use pr_dbg in vrtc instead of printf
  DM: add deinit API for loggers

Tracked-On: #3012
Signed-off-by: Minggui Cao <minggui.cao@intel.com>
Reviewed-by: Yin Fengwei <fengwei.yin@intel.com>

### CODE REVIEW

**Comment by HuiHuangShi** [comment]
No new violations to the coding guideline detected.<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by mcao6** [comment]
update disk-logger for a bug when log file reach the max index, it need use INDEX_AFTER to compare for the next file index.

**Comment by acrnsi** [comment]
OK to verify

**Comment by acrnsi** [comment]
@mcao6 This branch has conflicts that must be resolved

**Comment by mcao6** [comment]
update to resolve rebase conflicts.

**Comment by HuiHuangShi** [comment]
No new violations to the coding guideline detected.<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Pull request merged**
