### PR TITLE
config_tools: fix cpu offline issue in launch script

### PR DESCRIPTION
**Pull request by Kunhui-Li**
In launch script, update cpu offline method to fix the issue
that it isn't offline cpu on ADL-S board.

Tracked-On: #6266
Signed-off-by: Kunhui-Li <kunhuix.li@intel.com>

### CODE REVIEW

**Comment by wenlingz** [comment]
OK to verify doc

**Comment by wenlingz** [comment]
@NanlinXie please help approve this PR, thanks

**Comment by NanlinXie** [comment]
@szhen11 , could you confirm it resolve your problem?

**Comment by szhen11** [comment]
> @szhen11 , could you confirm it resolve your problem?

@Kunhui-Li , do you test it on legacy platform(TGL for example) and ADL-S?

**Comment by Kunhui-Li** [comment]
Yes, I have tested it on the TGL and ADL-S platforms, it work.

**Comment by szhen11** [comment]
> Yes, I have tested it on the TGL and ADL-S platforms, it work.

Thanks. LGTM.

**Review by NanlinXie — APPROVED** [review]

**Pull request merged**
