### PR TITLE
HV: get tss address from per cpu data

### PR DESCRIPTION
**Pull request by yuchuyang**
TR selector initianlization using pre-defined HOST_GDT_RING0_CPU_TSS_SEL
rather than loading from register. Instead calculating real base address
of TSS based on TR selector and gdt, getting it from per cpu data.

Tracked-On: #1394
Signed-off-by: Yang, Yu-chu <yu-chu.yang@intel.com>
Acked-by: Anthony Xu <anthony.xu@intel.com>

### CODE REVIEW

**Comment by ClaudZhang1995** [comment]
OK to verify

**Comment by HuiHuangShi** [comment]
1428<br>1 new potential violations to the coding guideline detected. Please help check. Thanks!  <br><br>1.filename:/hypervisor/arch/x86/vmx.c&nbsp;&nbsp;function:init_host_state&nbsp;&nbsp;offset:800:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Implicit conversion: actual to formal param (MR). :  (struct tss_64 and void):  param  1<br><br>

**Comment by HuiHuangShi** [comment]
1428<br>1 new potential violations to the coding guideline detected. Please help check. Thanks!  <br><br>1.filename:/hypervisor/arch/x86/vmx.c&nbsp;&nbsp;function:init_host_state&nbsp;&nbsp;offset:800:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Implicit conversion: actual to formal param (MR). :  (struct tss_64 and void):  param  1<br><br>

**Comment by wenlingz** [comment]
Please add External_System_ID

**Comment by wenlingz** [comment]
@yuchuyang  Please add External_System_ID in the git issue #1394

**Comment by yuchuyang** [comment]
[External_System_ID] 259221

**Comment by yuchuyang** [comment]
> 1428
> 1 new potential violations to the coding guideline detected. Please help check. Thanks! 
> 
> 1.filename:/hypervisor/arch/x86/vmx.c  function:init_host_state  offset:800:
>        reason:Implicit conversion: actual to formal param (MR). : (struct tss_64 and void): param 1

Added (void *) to casting the pointer to void pointer, need to verify.
@wenlingz would this solve the potential violation? Not sure how to check at my side to see if there is still an issue...

**Comment by HuiHuangShi** [comment]
1428<br>No new violations to the coding guideline detected.

**Comment by wenlingz** [comment]
@yuchuyang [External_System_ID] must write in the git issue, we have added it

**Comment by HuiHuangShi** [comment]
1428<br>No new violations to the coding guideline detected.

**Comment by haoweiah** [comment]
Ready to merge

**Pull request merged**
