### PR TITLE
config_tools: modify README file

### PR DESCRIPTION
**Pull request by Kunhui-Li**
1. Update python script name that is executed to generate board xml file
from run.py to cli.py in README file.
2. Update the OS requirement under native Linux in
misc/config_tools/board_inspector/README file.

Tracked-On: #6134
Signed-off-by: Kunhui-Li <kunhuix.li@intel.com>

### CODE REVIEW

**Review by NanlinXie — APPROVED** [review]

**Comment by gvancuts** [comment]
Could we use a better name than `cli.py` for the tool? Not sure what it's supposed to stand for but to me I read it as "command-line interface", which does not give any hint as to what the tool actually does.

**Comment by junjiemao1** [comment]
> Could we use a better name than `cli.py` for the tool? Not sure what it's supposed to stand for but to me I read it as "command-line interface", which does not give any hint as to what the tool actually does.

It is named so because the package name (i.e. ``board_inspector``) already indicates what scripts under this directory is aimed at. Naming it ``board_inspector.py`` seems to be redundant.

It is quite common to name the module that is supposed to be used as the command line interface as ``cli.py`` in python packages, e.g. gitlab, xmlschema and flask.

**Comment by gvancuts** [comment]
> It is named so because the package name (i.e. `board_inspector`) already indicates what scripts under this directory is aimed at. Naming it `board_inspector.py` seems to be redundant.
> 
> It is quite common to name the module that is supposed to be used as the command line interface as `cli.py` in python packages, e.g. gitlab, xmlschema and flask.

Really? Is this the gitlab Python utility you're referring to: https://python-gitlab.readthedocs.io/en/stable/cli-usage.html? If so, it seems that it may be the name of the `.py` file but that it's wrapped up in a command you can run from a terminal that uses a much more meaningful name.

**Comment by junjiemao1** [comment]
> > It is named so because the package name (i.e. `board_inspector`) already indicates what scripts under this directory is aimed at. Naming it `board_inspector.py` seems to be redundant.
> > It is quite common to name the module that is supposed to be used as the command line interface as `cli.py` in python packages, e.g. gitlab, xmlschema and flask.
> 
> Really? Is this the gitlab Python utility you're referring to: https://python-gitlab.readthedocs.io/en/stable/cli-usage.html? If so, it seems that it may be the name of the `.py` file but that it's wrapped up in a command you can run from a terminal that uses a much more meaningful name.

Yes, that's right. I only looked at the source code of these packages which do not contain the wrapper scripts (which are created by pip upon installation). I should have noticed that earlier.

There are two options for improvement:

1. Rename ``cli.py`` or create another wrapper script with a meaningful name.
2. Create a ``setup.py`` for the board inspector so that users (or Yocto builds) can install the tool along with all dependencies using ``pip``. The wrapper script can then be created by ``pip`` instead.

Any preference?

**Comment by gvancuts** [comment]
> Yes, that's right. I only looked at the source code of these packages which do not contain the wrapper scripts (which are created by pip upon installation). I should have noticed that earlier.

Thanks for the confirmation! And no worries for not noticing this before.

> 
> There are two options for improvement:
> 
>     1. Rename `cli.py` or create another wrapper script with a meaningful name.
> 
>     2. Create a `setup.py` for the board inspector so that users (or Yocto builds) can install the tool along with all dependencies using `pip`. The wrapper script can then be created by `pip` instead.

I like that!! So we would install the tool and dependencies in a single command, e.g. `sudo pip install acrn_board_inspector` for example?

> 
> 
> Any preference?

Love the idea of having a the board inspector that can be installed using `pip`!

**Comment by junjiemao1** [comment]
> I like that!! So we would install the tool and dependencies in a single command, e.g. `sudo pip install acrn_board_inspector` for example?

Using a single command means we need to publish the board inspector on pypi. At least we can reduce the deployment of the board inspector to two steps:

1. Copy the board_inspector directory to target, and
2. ``sudo pip3 install <path to board inspector>``

> 
> > Any preference?
> 
> Love the idea of having a the board inspector that can be installed using `pip`!

Got it. I'll take a look how this can be done when I have time.

**Pull request merged**
