### PR TITLE
hv: vtd: check bus number when assign/unassign device

### PR DESCRIPTION
**Pull request by binbinwu1**
Input parameter "bus" of assign_iommu_device/unassign_iommu_device may be from hypercall.
And the conext tables are static allocated according to CONFIG_IOMMU_BUS_NUM.
Need to check the bus value to avoid access invalid memory address with invalid value.

Tracked-On: #2743
Signed-off-by: Binbin Wu <binbin.wu@intel.com>
Acked-by: Anthony Xu <anthony.xu@intel.com>

### CODE REVIEW

**Comment by HuiHuangShi** [comment]
out of time

**Comment by HuiHuangShi** [comment]
No new violations to the coding guideline detected.<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Comment by acrnsi** [comment]
@binbinwu1 your code make partition mode test fail ,please check your code.

ACRN:\>sos_console 1


----- Entering Guest 1 Shell -----

0000:00:01.0

[    0.957577] hub 1-0:1.0: USB hub found

[    0.957826] hub 1-0:1.0: 8 ports detected

[    0.958594] xhci_hcd 0000:00:01.0: xHCI Host Controller

[    0.959076] xhci_hcd 0000:00:01.0: new USB bus registered, assigned bus number 2

[    0.959503] xhci_hcd 0000:00:01.0: Host supports USB 3.0  SuperSpeed

[    0.959979] usb usb2: New USB device found, idVendor=1d6b, idProduct=0003, bcdDevice= 4.19

[    0.960490] usb usb2: New USB device strings: Mfr=3, Product=2, SerialNumber=1

[    0.960900] usb usb2: Product: xHCI Host Controller

[    0.961199] usb usb2: Manufacturer: Linux 4.19.23-quilt-2e5dc0ac xhci-hcd

[    0.961583] usb usb2: SerialNumber: 0000:00:01.0

[    0.962193] hub 2-0:1.0: USB hub found

[    0.962443] hub 2-0:1.0: 7 ports detected

[    0.963125] ACPI: <n/a>: failed to evaluate _DSM (0x1001)

[    0.963573] usbcore: registered new interface driver cdc_acm

[    0.963895] cdc_acm: USB Abstract Control Model driver for USB modems and ISDN adapters

[    0.964398] usbcore: registered new interface driver uas

[    0.964737] usbcore: registered new interface driver usb-storage

[    0.965129] usbcore: registered new interface driver ums-realtek

[    0.965521] usbcore: registered new interface driver usbserial_generic

[    0.965903] usbserial: USB Serial support registered for generic

[    0.966302] usbcore: registered new interface driver ark3116

[    0.966636] usbserial: USB Serial support registered for ark3116

[    0.967001] usbcore: registered new interface driver belkin_sa

[    0.967373] usbserial: USB Serial support registered for Belkin / Peracom / GoHubs USB Serial Adapter

[    0.967912] usbcore: registered new interface driver ch341

[    0.968256] usbserial: USB Serial support registered for ch341-uart

[    0.968630] usbcore: registered new interface driver cp210x

[    0.968957] usbserial: USB Serial support registered for cp210x

[    0.969339] usbcore: registered new interface driver digi_acceleport

[    0.969712] usbserial: USB Serial support registered for Digi 2 port USB adapter

[    0.970172] usbserial: USB Serial support registered for Digi 4 port USB adapter

[    0.970619] usbcore: registered new interface driver f81232

[    0.970950] usbserial: USB Serial support registered for f81232

[    0.971323] usbcore: registered new interface driver ftdi_sio

[    0.971662] usbserial: USB Serial support registered for FTDI USB Serial Device

[    0.972127] usbcore: registered new interface driver mct_u232

[    0.972468] usbserial: USB Serial support registered for MCT U232

[    0.972847] usbcore: registered new interface driver mos7720

[    0.973219] usbserial: USB Serial support registered for Moschip 2 port adapter

[    0.973659] usbcore: registered new interface driver mos7840

[    0.973994] usbserial: USB Serial support registered for Moschip 7840/7820 USB Serial Driver

[    0.974536] usbcore: registered new interface driver option

[    0.974866] usbserial: USB Serial support registered for GSM modem (1-port)

[    0.975328] usbcore: registered new interface driver oti6858

[    0.975663] usbserial: USB Serial support registered for oti6858

[    0.976023] usbcore: registered new interface driver pl2303

[    0.976372] usbserial: USB Serial support registered for pl2303

[    0.976728] usbcore: registered new interface driver spcp8x5

[    0.977080] usbserial: USB Serial support registered for SPCP8x5

[    0.977438] usbcore: registered new interface driver ssu100

[    0.977767] usbserial: USB Serial support registered for Quatech SSU-100 USB to Serial Driver

[    0.978280] usbcore: registered new interface driver ti_usb_3410_5052

[    0.978660] usbserial: USB Serial support registered for TI USB 3410 1 port adapter

[    0.979119] usbserial: USB Serial support registered for TI USB 5052 2 port adapter

[    0.979568] usbcore: registered new interface driver whiteheat

[    0.979911] usbserial: USB Serial support registered for Connect Tech - WhiteHEAT - (prerenumeration)

[    0.980453] usbserial: USB Serial support registered for Connect Tech - WhiteHEAT

[    0.980895] usbcore: registered new interface driver keyspan_pda

[    0.981264] usbserial: USB Serial support registered for Keyspan PDA

[    0.981633] usbserial: USB Serial support registered for Xircom / Entrega PGS - (prerenumeration)

[    0.982492] mousedev: PS/2 mouse device common for all mice

[    0.983669] rtc_cmos rtc_cmos: registered as rtc0

[    0.983975] rtc_cmos rtc_cmos: alarms up to one day, 114 bytes nvram

[    0.984381] i2c /dev entries driver

[    0.984694] IR NEC protocol handler initialized

[    0.984955] IR RC5(x/sz) protocol handler initialized

[    0.985269] IR RC6 protocol handler initialized

[    0.985530] IR JVC protocol handler initialized

[    0.985788] IR Sony protocol handler initialized

[    0.986066] IR SANYO protocol handler initialized

[    0.986335] IR Sharp protocol handler initialized

[    0.986604] IR MCE Keyboard/mouse protocol handler initialized

[    0.986933] IR XMP protocol handler initialized

[    0.987267] usbcore: registered new interface driver uvcvideo

[    0.987594] USB Video Class driver (1.1.1)

[    0.988312] intel_powerclamp: CPU does not support MWAIT

[    0.988986] device-mapper: uevent: version 1.0.3

[    0.989419] device-mapper: ioctl: 4.39.0-ioctl (2018-04-03) initialised: dm-devel@redhat.com

[    0.990164] hidraw: raw HID events driver (C) Jiri Kosina

[    0.990767] usbcore: registered new interface driver usbhid

[    0.991107] usbhid: USB HID core driver

[    0.991438] ashmem: initialized

[    0.991625] intel_telemetry_core Init

[    0.992171] intel_rapl: Found RAPL domain package

[    0.992445] intel_rapl: Found RAPL domain core

[    0.992701] intel_rapl: Found RAPL domain uncore

[    0.992967] intel_rapl: Found RAPL domain dram

[    0.993580] intel_rapl: Found RAPL domain package

[    0.993864] intel_rapl: Found RAPL domain core

[    0.994140] intel_rapl: Found RAPL domain uncore

[    0.994405] intel_rapl: Found RAPL domain dram

[    0.995702] u32 classifier

[    0.995867]     Actions configured

[    0.996351] xt_time: kernel timezone is -0000

[    0.997141] Initializing XFRM netlink socket

[    0.997450] NET: Registered protocol family 10

[    0.998209] Segment Routing with IPv6

[    0.998467] mip6: Mobile IPv6

[    0.998950] sit: IPv6, IPv4 and MPLS over IPv4 tunneling driver

[    0.999581] NET: Registered protocol family 17

[    0.999849] NET: Registered protocol family 15

[    1.000150] bridge: filtering via arp/ip/ip6tables is no longer available by default. Update your scripts to load br_netfilter if you need this.

[    1.000869] can: controller area network core (rev 20170425 abi 9)

[    1.001263] NET: Registered protocol family 29

[    1.001524] can: raw protocol (rev 20170425)

[    1.001771] can: broadcast manager protocol (rev 20170425 t)

[    1.002111] can: netlink gateway (rev 20170425) max_hops=1

[    1.002485] l2tp_core: L2TP core driver, V2.0

[    1.002741] l2tp_ppp: PPPoL2TP kernel driver, V2.0

[    1.003016] 8021q: 802.1Q VLAN Support v1.8

[    1.003310] Key type dns_resolver registered

[    1.003560] mce: Unable to init MCE device (rc: -5)

[    1.004092] SSE version of gcm_enc/dec engaged.

[    1.005912] sched_clock: Marking stable (977034803, 28861764)->(1026056773, -20160206)

[    1.007090] registered taskstats version 1

[    1.007332] Loading compiled-in X.509 certificates

[    1.009496] Loaded X.509 cert 'Build time autogenerated kernel key: 5f22390eac0587c5a027bb1aeca715e0ffa0782f'

[    1.010984] Key type big_key registered

[    1.011667]   Magic number: 3:638:175

[    1.011889] misc network_throughput: hash matches

[    1.012282] console [netcon0] enabled

[    1.012499] netconsole: network logging started

[    1.012977] rtc_cmos rtc_cmos: setting system clock to 2011-11-11 11:11:13 UTC (1321009873)

[    1.013496] Invalid pltconfig, ensure IPC1 device is enabled in BIOS

[    1.013868] ALSA device list:

[    1.014059]   No soundcards found.

[    1.014593] RAMDISK: Couldn't find valid RAM disk image starting at 0.

[    1.014979] Waiting for root device /dev/sda3...



[ WARN ] launch sos for 0 time failed: write: sos_console 1

**Comment by HuiHuangShi** [comment]
No new violations to the coding guideline detected.<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

**Pull request merged**
